>Amblygaster_clupeoides|021266|TR37175|c0_g1_i1|m.58442
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------GAGCTGCAGAGGGTTGTGGAGAAGGGAGGCAAGTCATATACA
GTGAAGGGGGAGG----------------CGGGGCTTAATGGTCTCAGCACAGAGAGTCG
ACGCTACGTAGAACTGGCAGAGGAGGGTCACAGGATGTGTCTGTCTCTAGAAGCAGCTAT
-----------TAGTGCAGAGGAGCAGCGCAGCAGCAAAAACACTCCGTT----------
----CTTCCCCATCACCAT-----TGGCAGGAA--------------ACCCACCAGCTCT
AACCAGCCGGCTCCTGC------------TGAAGTGGCCCAGGTGT------------GT
GTGAGTCCGCCT---GAACCCCCCCACATCACACCGTCTATGATCTCTTATGGTGGATCT
GACCTGACAGCAGTGAGTTTGGGAAAGAGCG-CCGCCCTAAAGGCCAGCCTTGAGACACG
CAGCACTGCAGGCAAAGTCCTCAAGTCTGTGTTTGTACCCAACATTGGCTGGGCTTCA--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>Corydoras_julii_viscera_mixture_8|007295|scaffold12752|m.8840
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------CCTTTCATGACACAAAG-----------TGGGTCC
ACTGCAAGCAAAGACTC-------------------------------------------
------------TGGGACTAGTGATGGAGGCTCCATAGACAGTGGTATTGC----CACAA
TTTCTACAGCATCCAATGCTACCACCACTAATAACAGCAGCAGCAATCGACT---TCAGA
GGAAAACTAGACAAGTGATTGGACAGGCTTTACCCAATCGCATGGTTCCACTGCCCAACC
AGTCTCAGCAATCCACCAGCAGCAGCTTTAAAGAAGAACATGACTGGC-AGCCACATTTT
CTGAACAGTGTGAGATTTCCTGTGGATCCTGTCAGTGGACGGCCACATTCCCGCTACCTG
AGGCGAGCTCATTCCAGCG---------------ATCGGTCAGGTTCTGGATTTACCCAC
GCTAGACATGATGTGGAATTGGAGAGATGCCACTCAGATGAGATGCTTTCAGGCTCTGGA
CACATTTTCCCATCAACATCCAGTTATCAGGAC---------ACTTTGCCTGGTTACTCT
GA------------------------------------------------------ACGT
GGTCGTCTGCCC-------------------------------TCCCCGCCAGTAAAACA
ACCTGCNNNNNNNNNNNNNNNNNNNNNNNNN-----------------------------
------------------------------------------------------------
------NAGTAA------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>Distichodus_sexfasciatus_gill_4|009211|scaffold13329|m.14432
CACACAAGACCAGAGGCAGAACTTGAGCGATGCCACTCGGAGGAGGTTCTTTCGGGATCT
GGCCATATTTTCTCAACAGGGTCCGCTTACCGGGAAGCTCCACACGACTACTCTGAACAT
GGACGGCTGCCCTCTCCTCCAGTCAAACAGCCTGCAAACTCTGGGTCTTCCTTCACCACT
CCAGCACATCCTGTCAGATTACAGATGGTAGAATCAGAAACGCAGCCATGGTTTGGCACT
GATGGGTCTTTCAAGAGACCTGCAGATGTCAGCACCCACAGCAGCGGTGGGAATTTGCAT
TCTGGGCGGGAGGCAGCGAGAGCTCCACCTTCCTGCAGCGACAGACCAGCAGTGAGAGGA
ACCAGTGGCCTTCTCCCTCACCCGTACCACCTCTCCTCCTCTCAGAACCACCCAGGACCC
TACAGGGAGGATGGGCTTGGTGCTGGACATTTCCCAGCCCCTCAGGCCTGTTTAGATGTG
CAGTCTGCTCACATGTCTAAAAGCAAAACTATTGAGGGAAAAGAGAAGAGGATTCCGTTT
CCCCCTCTCTGTGCAGCCAGATTAAAGCCTATTAGACAGAAGACCAAAAATGCTGTGGTC
AGCATCCTTGACACAGGAGAAGTGTGCATGGAGCTCTTGAAGGGTCAGGGAAGTCAAGAG
AGGGTCAAAGAAGTGTTGAGGATATCCTGTGATGGCTCCATGGTGACGACGTACCAGCCT
AATGAAGGAAAAGGCTTCCCTGTGCTGGACCATCCGCCCTCTCCTCCAGAAGACATTTTT
ATATGCAGTTATGAGGatttgccAGAAAAATACTGGAAGAAATATCAGTATGCTACGAAG
TTTGTCCAGTTAGTGAAGTCAAAAACACCCAAAGTAACACTGTACACCAAGTTTGCTAAG
TGCATGCTGATGGAGAACTCTCCTAATGCAGATCTGGAATTGTGCTTCTATGATGGTGCC
AAAACTCATAAGACAAGCCATCAGGTCCGGGTGGTTGAGAAGAGCGGCAAGTCGTACACA
GTAAAGGGCGACG----------------TAGGCCTGAGCGGTGTGAGTCCAGAGTGCAG
ACACTACATGGAGCTCACAGAAGAGGGACACAGAATGTGTCTGTCTTTAGAGGTTGCCAT
-----------TAGTGCAGAGGAGCAACGCAGTGCTAGAACTACACCATA----------
----TTTTCCCATCACTAT-----TGGCAGGGGGGGGGGGCNNNNNNGCCTGCTAACCCG
AGCTCCTCGCTGCCAGGGGCTGAGCC----------------------------------
-----------------------------------------------------TAGCTCT
GAACGCAGTCCTGCAGTCCCCGCTGAGGTAG-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>Melanotaenia_praecox_viscera_mixture_8|002023|C419862|m.27201
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------GAGAAATACTGGAAGAAGTATCAGTATGCCTCCAAG
TTTGTGCAGCTTGTGAAATCGAAGACTCCTAAAGTGACCCTTTACACCAAGTATGCTAAA
GTTATGCTGATGGAGAACTCTCCCAATGCAGACCTTGAAGTTTGTTTTTATGATGGAGCA
AAAACTCACAAGACATCAGAGCTGGTGCGCGTG---GAGAAGAGTGGGAAATCATATACT
GTGAAAGGGGAGG----------------TGGGGCTGAGCGGCCTGAGCCCAGAGAGCAG
GCTGTATGTGGAGCTATCAAATGAGGGCCATAACATGTGTTTGTCGCTGGAGGCTGCCAT
-----------TGCGGCAGAGGAGCAGCGCAGCACCAAGAAAGTTCCTTT----------
----CTTCCCCATAACTAT-----TGGCAGGCG--------------ACCTGCCACTTCA
GACTCCCCTTCCTTATCGTCCACGCCCTCACAGCAGGTAC------------CTCCTGAT
GCAGCTTCTCCT------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>Pantodon_buncholzi_mixed|013148|scaffold16049|m.21382
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---ATCTTGGATACAGGTGAGGTGTGTGTGGAGCTCCTGAAGGGACAGGGAGCCCAGGAA
AGGGTTAGAGAAGTGCTGCGCATCTCGTGTGACGGCACCATGGTAACCATCTACCAGCCC
AGAGAAGGCAAAGAGCTGCCTGCACTGGACAGGCCTTCCACACCACCTCAGGATATATTC
ATCTGCAGCTATGAGGACCTGCCAGAGAAGTACTGGAAGAAGTACCAGTATGCCACCAAA
TTTGTCCAACTTGTTAAATCAAAGACACCCAAAGTCACACTTTACACCAAATATGCCAag
tgtatgctgatggagaattcccccagtgctGACCTGGAAGTGTGTTTCTATGATGGAGCC
AAGCTGCACAGATCAGCAGAGGTGGTGCGTGTGGTGGAGAGGACAGGAAAGGCATACACC
GTCAAGGGGGAGG----------------TGGGACGCAGTGGTCTCAGCCCAGAGAGCAA
AGCCTACATGGAGCAGGCGGAGCAGGGCCACCGCATGTGTGTGGCAGTGGAGGCTGCAGT
-----------CACTGTAGAGGAACAGCAAAGCGCTCAGGCCACACCCTT----------
----CTTCCCCATCACTGT-----TGGAAGGCG--------------TCCTACCAACCCA
GCCTGTGTCAGCGCTGCATCTCTCCCTGCTGCAG------------------CTCCACTG
GAGAGTCCAGTA---AACCCACCCAACATCACCCCATCGATGATCTCCTATGATGGCTCA
GACGTCACCTCTTCTAGCCTGGCTAAGGGTCNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNGTCCTCAAGTCTGTGTTTGTGCCCAACATTGGCTGGGCTTCGCA
GCTGACGAGTGGTGA---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>Sargocentron_rubrum_gill_6|003738|C705825|m.47308
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------AAAGAAGTCCTTCGGATATCCTGTGATGGTTCAATGGTGACGATATACCAACCA
AATGATGGGAAGGGTTTTCCCGTGCTGGATTGCCCCCCTGCCCCTCCTGAAGATATTCTC
ATTTGTAGCTACGAGGACCTTCCAGAGAAATATTGGAAGAAGTACCAGTATGCCTCCAAG
TTTGTGCAGCTTGTAAAATCCAAGACTCCCAAAGTGACCCTTTACACCAAGTATGCCAAG
TGCATGCTGATGGAGAACTCCCCAAACGCAGACCTGGAGGTTTGCTTTTATGATGGAGCA
AAGACCCACAAGACGTCAGAGCTGGTGCGAGTGGTCGAGAAGAGCGGGAAGTCGTACACA
GTGAAGGGCGAGG----------------TGGGGCTGAGCGGCCTGAGCCCAGAGAGCCG
CTTGTATGTGGAACTGTCAGACGAAGGTCACAGCATCTGTCTGTCTCTAGAGGCCGCCAT
-----------CACCGCAGAGGAGCAGCGCAGCACCAAGAACACTCCTTT----------
----CTTCCCAATAACTAT-----CGGCAGGAG--------------ACCTGCCAACCCA
GAATCCCCTTGCTCATCATCGCTGCCATCCCAACCGATGC------------CAGCCGAT
GTGGCTTCACCTCCCCAACATCCACAGATCACTCCGTCGATGATCTCCTATGATGGATCA
GATTTCACGTCAGCCAGCCTGAACAAGAAAA----GCTCCCCGGCACGACAGGACCTGGC
CCACAGCACGGGGAAAGTGGTTAAGTCGATATTCGTGCCCAACATTGGATGGGCATCCCA
GCTGACCAGTGGGGAAGTTTGGGTGCAGTTTAACGACGGGTCTCAGCTGGTGGTGCAGGC
AGGAGTTTCATGCATCACATACACGTCGCCAGAGGGCCGGATCACCAGGTACAAGGAGAA
TGAGAAGTTGCCGGAGCTCGTGAAGGAAAAGCTTCACTGCCTCTCCACCATCCTGGGACT
GCTGGCCAACCCAGCAGCACATCGCCTGCAACAGCCTCACTAA
>Scleropages_formosus_red_gill|001048|C1206350|m.68384
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------CTTGTGCGAATTGTCGAGAAGACAGGGAAGTCATTCACA
GTGAAGGGTGAGG----------------TGGGGCTGTCTGGCTTAAGTCCTGAGACCAA
GGCCTACATGGAACAATTCAGCGAGGGACACCACATGTGCCTGGCTTTGGAGGCAGCAGT
-----------CTCTGCTGAGGAGCAGCGCAGTTCAAGGACTACACCCTT----------
----CTTTCCCATCACCAT-----TGGCAGGAG--------------GCCCACCAATGCT
GGCTTCCCAAACCCCACCTCTCAGAGCATACAAGCTGGCAGGTCGTCTCATGTTCCAGCT
GAAGGTCCAACC---AAGATGACCCCCATCAGCCCTTCGATGATCTCATGCGATAGTTCA
GACTTCACCTCTGGC---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>Synodus_sp._gill_5|025496|scaffold8853|m.9931
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------GAAGATCTTCCAGAGAAATACTGGAAGAAGTATCAGTATGCGTGCAAG
TTTGTCCAGCTTGTGAAGTCCAAGACTCCCAAAGTGACCCTTTACACCAAGTTCGCCAAG
TGCATGCTGATGGAGAACTCTCCCCAGGCGGACCTGGAGGTCTGCTTCTATGACGGGGCG
AAGATCCACAAGACGTCGGAGCTGGTGCGGGTGGTGGAGCGCGGTGGGAAGGCGTACACG
GTGAAGGGCGAGG----------------CCGGGCTGGGCAGCCTGGGGCCGGACAGCCG
GCGCTACGTGGAGCTGGCAGAGCAGAGCCACAGcATGTGCCTGGCCCTGGAGGCCGCCGT
-----------CAGCGCAGAGGAGACGCACAGCGCCAACGGGACGCCCTT----------
----CTTCCCCATCGCCAT-----CGGCAGGAG--------------ACCTGTGAACCCA
GATACGCCGTAC------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
