>Amblygaster_clupeoides|024298|TR42809|c2_g1_i1|m.64530
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------ATCTCTGACTGTGTCACTACTGAGC------
ATGTCCAAGAGGT------------------------GGAGCCTAAATGGGTGAATAC--
------------------------------------------------------------
--------------------------------------------------TGAGCA----
--------------------------------------TGTGCAGGAGAGGATCTCTGAC
TG---------------------------CGTCACTACTAAGCATGTTCAAGAGGTGGAG
CCTAACTGTGTCAGTACTGAGCGTGTGCAGGTGGTG------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------TCCGAGTGCATCAATACTGAG-----------------
-----------------------------------------------------------C
CTGTGCAGACAGATGTTTCTG---------------------------------------
-------------------------------------------------------CCCAT
TCAGAGGAAGACCA----------------------------------------------
------------GTCATCTGCGGCCCCTTCTGGCTCCTCCCG------------------
------------------------------------------------------TCCACC
TTCTTCTCCACAGA----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------CTCCCTGTCAGGAGTCTTTC
CTGAAAG--------------------------------------CTTTAAATCTCACT-
------------------------------------------------------------
---------------------------------------GCCACCCAG------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------AGTCCTGCATTG
GTAGG----------------------------------AAGAAGGA-------------
------------------------------------------------------------
-------------CAGCGTCTTCTGGTTC-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------ACAGGGCACAGATG---
-----------------------------------------CTGCTGGACAGC-------
--AAGCAGACACCATCAGT------AGCTACTGCTGCCCTCTAGAGGATGATGACTT---
------------------------------------------------------------
------------------------GGACGAAGAAGGTGATTGTATTGAT-----------
-------GTGGAGATGCAGGATGAGGAGATCTACC------------AGC----------
-----------------------------TCTTACCAAAGAAGCATTGGCTACCTCATGT
GTCAGTCTACCAGTTGGCCCTCCTCTCTATCCCTGTTGGTCAGCCCCCACCCCAGTTCCG
T-CTCCGCCAGGGGAAAGGTTCAATGGAGTTCCTGATCCAGGAGATCACTGAAGAGAATG
TGTCTG--------------------------------------------CAGAGTGCCA
A----------------------------------AGCCCTGCCAGAGTGGCAGTGCCAG
CCAAGCAGAGGCACTGTGCTGTGTGCCGCATAGAGGGCATGCTGTACCACTGTGCCACCT
GTCACCGTGGATACCACAAAGGATGTCATATCCCTCCTCTCATCACTAGAC------TCA
GGGAGGGCTGGGTGTGTGGCCTGTGTCTGGATATGTCGGCGGAGGTGAGACTGCAGGA--
-AGGCTTAGAGGGAGGCTCCTGTATGAGCCCT------CAGGATCAGAAGAAATGTGAGC
ACTTGCTGCTCTCCCTGTGGTGTAGCAAATATAGGCCTGCACTTTTCATGCAAAATAAGG
AGCCGGTGTCCTCTACCTCCAATGCCATGAGCATCATTCTCATCCGCGGACGGTTGCTAC
AGAAGCT---------CCCGCCTCCGTACCGCACCCCTGCAGAATTTGTGTCCGACATCT
GGCTCCTGCTGGACATCCTCCTCAAAAAGGCAAAGTGGAAGGCTGAGTGTGAGAGGCAGC
TGCGGGCCCTGCAGATGATCTTCTCCCGGCGACTACAGCGGATCTTCAGCCAAATTCTCC
ACCCGTCTCTCCTCCGCAACCCCTACAG-------CCAGCGGCAGAGAGGCCGACCCCGC
AAGCAGCAGCAGCAGCCACAGCAGCCGGCGGAGAGACCCTCCAACCGTGGGAAGGAGGCA
AAGGTGGAGCGAGGCACTGGGATAGCAGGCCGACGCAGAAGCACGAGAA-----------
---AGCCGAGGGCTGGGAG-GAAGGAGAAACAGCAGACATGGACACAGACACGGATGCCG
TTACAGTCACAAACGCAGATGCCTTTAGG---GTCACGGATGCTGATGCAGTCACAGATG
C------------------------CATCACAGACTGAG-----TTACAGACACAGACGC
AGATGCAGACCCAATCACAGATTCAACTACAGTCAATGATGCTGTTACAGTCACAGACAG
AGACACAGATGCAACTACAGTAG
>Corydoras_julii_viscera_mixture_8|011529|scaffold20246|m.15304
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------ATGTTTTATAACAATGA------
-------------------------------------CACGCCAACAAGCA---------
-------------------------------------------------AATTGTCTTTC
TATAG-------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------GTCG
CATGATTTGATGAGCA--------------------------------------------
------------------------------------------------------------
------CAAAGAAGACTGCAAGGCACTTTAGCCCTATTTTTGCAAGCATTTCACCAT---
------------------------------------------------------------
-----------------------TTTGTGTGGTGAACA----------------------
------------------------CAAAACCACTGGTACCGA------------------
-----------------------------------------------------------A
CAATGTATCCAGTGTTGACAAA--------------------------------------
------------------------------------------------G-----------
--AAGGTAATGC------------------------------------------------
--------------------CAGCATGTCCACTAACCCTTTG------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------GAGCAAGTCACAGAAGAACT---------------------
----------GACTGCAATTT-------------------CCAATTCGTTACCAATTGAC
CTGAATA-----------------------------------------------------
-------------------------------------TCTCAGGGAGAGAGAAAACAGCC
ATTTTATCAGCC------------------------------ATCCAAATGAA-------
---GTTATCG--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------GAAAATACATCTAGTACAAAT
GCCATGCAAACATGTACCAGTGA-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----CCATGAATCAGAAAAGACTGA-----------------------------------
-----------------------------------------------------CATTAAT
ATGCCAACT-------------TCCAAAAATCAATTAG-----ACAGTTTACAGAAT---
----TACAAACAAAATTCAACTCAA------------------ACTGGAGGATCTATT--
--AAACAAGAAGTG------------GATGCTGTGGACATTGTAAAGCTCGCAA------
------------------------------------------------------------
--------ACACCTCTTCTGTGAAGGATCACAGGGAACATGGTACA----TCCATAACTC
-------------------GAATAAGAGATG-------------------AGCATGGA--
--------AACCTGACAGTGCTGAAA-----TCAGTGGGCAGGAGCTGGCTGCCAGAAGT
TGCAATCCGCCGCCTG------TCTCTCCCTAATTATCCATCATCTCTTCCTC-------
--CCGCTTTCCATGTCAAACGAAAAAAGCAT----------------GGTGAAGGATATC
AGctcagcatCG---------------------------TTCAGGA----TGGGGTGCAG
AGTACTTTTTCA-----------------------GATGGTGCATCACGCCCCATGATGA
ACAATAACCCTCACTGTGCCGCCTGCAGGGTATCGGGAAATGTCTTTCAGTGCTGTATTT
GCCAGCGGTTTTACCACAGAGAGTGTCACCTTCCTCCTGTTCCGTTAACCCAATCTCATA
GTTCTGACTGGCGGTGCACTCTGTGTGGAGATTTCTCTGAGCCTGTACACCC--------
-TACCATGGCAACCAAACCTGCATCAGGTCTAAGACCCACTGATCAGAGGAAGTGTGAGT
TTCTGCTGCTTTCCCTCACCTGTCATAAGTACAGCTCTACCCTTTATAGGCCAGTTAAGC
TGTCATCTGAA---GCACTTTGTTACTTGGATGCTACTTTAATACGGGGACGTCTTTTAA
AGAAGCT---------TATCCCACATTACCGCACTGCAGCAGAGTTTGTTTCCGATATCT
GGCTTATCCTTCACCTGCTAGTTAAAACTCCCAAGGAGGCAGTGCATGTGCAGCAG----
--------CTTCAGAGATTCTTCTCAAAACAGCTGTGCAGTGTGTTTGGTCAGAAGCTAC
CTCTGTCGCTCTTACAGAACCCC-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>Distichodus_sexfasciatus_gill_4|011629|scaffold17254|m.18967
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----AAGATTCTGAGCACAGAAGGCTAT--------------------------------
----GGCATCCTAC------------TGCACAAAAAGCTAAT--------------TGAT
AAATGTGTAA--------------------------------------------------
----------------------------------ACAAACTTCTGTCACAGAAG------
-ACACAACAAACTGAAACTATGATTCTGCCATTTCTCCATATCAACAAGGA---------
------CTTCTGCTA-----------------------------------------TCTT
GTTAAAAGCTATGGTT-------------------------CAGTTAAAGTGAGC-----
----------------------------------------------AGAGTTCCTTTGAC
T---------------------------------GGTTCAGAAAAAAACAATTGTAGCAG
CATGCCTAAAGATGCA----------GCCAAAGAAGAAAAC-------------------
----------------------------------------AGTGGCCACTCCGGTTTAAA
CG----CTAAATCTGCCTCAACACCGTCTGTGCCTGTTGCTGCAGCCTCTCAGCCACTAG
GTGGCGCTGCGTT-----------------------------------------------
----CAGAATAGTCGCTGGTCCTTCTCAGTGTGGGACATCAGATTCAACCTC--------
----------------------ATCAGAAGCATCGCAACCCAC-----------------
----------------------------------------------------------CA
CAATGCCAGCAAATTCTG----TCTTGGCTCTGCTGAATATGTGTAATAGACATCATTGT
ATAGCTCCTAGCACGAGCCGTACTAATTCCTCCTCAACTCCTG----CTTGCAATTCTCA
TCAGAGTAATGCTGCTGAGGTGAGCCAAGCCGGAGTCAAGCCGCATGCCTCAGCTAGGTC
TTCTCATACTA-ACCAGGTGCAGTCTGGCCAGACGGCTTTCGCAGACACTCTTCAGC-GT
GTCCCTCCAGTTCCCCCTAAGGTGCAGATTGCAGATTTGCCGTATACTCAAACTTCTGTC
AATACATCTACTCC-----------AGTACTCTCCATC--------CTCCT---------
------------------------------------------------------------
-------------------CAACATGGTCCAAAACGTCTCCTGCTCTAATGCGATTTCTG
TT----------------CCTGCCAAGAGTCAATCTAATGCCACCTGCTCGC---CCACC
TTGAGGGACAGTAGCACATCACAGCAGCCTGTGCAAACAGGGTTTTTCTCTACAGTACC-
-----TGTGGCTTCCAAACATCTTCCTCCCCATGGT------GAAAATAAAGCAGAAGCT
TGTTTCACGTCCA--------GCAGTCATGAACTTCCT-GCCACTCAAATGCACTGCACC
ACC-------AA----------------------------TATCCAAGTCCAAAGTCAAG
ACGTCACT-----------AGACCTACCCGAAATCTACAGTCAG--CACTCCCGGTGAAG
GCGCCGGCAGATTCTTTGGGTGAGGGCAACATCAGCCAGCTTGACATGGTTTCTCCCTCG
GTTGAGGACCAGGAT------------------------GGCAACATGCCCACCTCTACA
GTGCCAGAGACAGACACCAGTGAAATGCCAGTGGAGCCGAAACCGCATTTGCCCAATTCC
ACTACGCCTGGTCCTGTTTCCTCCGTTTC----------------AGTAGAGAACCACTC
TCCT--------------------------------AATCACAGCTTTATCTCCTCACCT
AAATCACTGCAGAAAGATGCACCGATTCC--------------ATCCTCCGGTGAAAGCG
CCTCTGCTTCCAAG---------------------------------------CACTGGA
CCACCAACT-------------TACCAACGTCATTCCG-----GCAGGTTTTAGAT----
-----ATGATCGATGATCGTGCCA------------------------------------
------AAACGGGA------------GATGTTGTCCCTACTGAGG---------------
------------------------ATACTTCTCCAAGTT---------------------
--------TTATCTCCAGTGTGAACGAGGAAGATGAGGAGGCTACTGATATTAGCGATTC
GGAACCCATGGAAATGGCAGAAGAAGCCGTG-------------------CAATTTGACA
ACACTCCTGAATCGACAA-----------------GCAATGTCAAGAGATTTTTGCGTGT
ATCCCTGGTAGAGTTGCCCATCTCTCTTCCTCCCTCAGGATCTTCTCTGCCTCAGTTTCA
CATTATTCCTAGTGACCAGACAGGTGAA-ATACTGCTTCAGGAGATCCAAGAGGGCAAGG
AAACCCAGAAAAT-------------------------TCTGAGGATTCCTGCGCTGCCG
ACAACTGCATCAC-----------CAACACAGTCCAG---TCCCGACTCTCAACTACCAG
CTGAGGTGCTGGACTGCAACGTCTGTCTGTCTGCTGGGGCCTCACTGCTGTGTACAGAAT
GTGGCAGAAGCTTTCATACCAACTGCCATGTGCCACCCATC---TTGAGA----CCAACT
GAAGTG--TGGGTGTGTTCCCTGTGCCATAATGTGTTGGACAACTTTGACCCATTCAGCT
GTGACAGGCTAAAGGAACCCTACCTCAGTCTG------CAGGATCAGAGGAAGTGTGAGC
AGACCCTTCTCACTTTGATGTGTGAGGAACACAGCTACTTTCTCTATCGGGCTGCCAAGT
ACTCAGCTGG------------ATGTATGGATTTTGACTTTATTGTTGGACGCCTGCTGG
GGAAGAG---------GAGCCCCCCGTACCGCACTGCAGCTGAAATGGTGTCGGATGTCT
GGGGTGTTTTTGCGGTCTTGTTAACACATTCCAAGAAGAAGCACTTGGTGGTCAAG----
--------CTTCAGAGTTTATTCCAAAAGCGGCTGAATGCAACCTTTGGGATGAGTCTTC
ATGCTTCACTCTTGAGTCCTCCTTACA---------------------------------
-------TTGAGGACCTGAAGGGGGCGCCAGAGACCACACTCAGCA--------AAGTC-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>Gasteropelecus_sp._gill_3|022445|scaffold34412|m.38892
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----AACATCATTAATATGGCAG-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------GCAG
CAAAAATAAAGATGC---------------------------------------------
------------------------------------------------------------
---------------------------CTGTACCCTTTCTAGTAGGCCC-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------TCTGATCAGAGGACCTCTG------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------ATGATCCA-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------GGTCATAGAGAGTAT-GCAACTCTGTTGC--------
------------------------------------------------------------
--------------------------CCCAGAGGCCCCAGTATA--AGTTCCCAGTGCAG
GCGCCAGCTGATTCTGTGTACGAGAGGAACATTTGCATGTATGGCAAGGCTTCTCCGACT
GCTGAGGAGTCGGAT------------------------GACAACCTGCCTACTTCCACA
GTGTCTGAGACTGATACCAAAGAACTTGCAGCAGGCCAAGAAGAGTGCCTGACCTCATCC
------CCCTCTCCAGCTTCTACTGTTCC----------------AATATCGGATTACCC
TCCT--------------------------------GACAATAAAACTTTTCCTGTGCCA
AAAATTACACTCAAGAGCACCCGCACCAT--------------ATCCTCTTCAGGAAAGG
CCTCCACATCCAAG---------------------------------------CACTGGA
GTGAAGGCT-------------TGCCATCATCACTTCA-----GCAGATTTTAGAA----
-----ATGAAAGATGCTTCTGCCA------------------------------------
------GAACTGTA------------GACGGTGTGTCTGCTGAGGAGACACTCACTGCAT
CTGA------------TGGTAACCATACTTCCCCATCTTC--------------------
------CCCTACACTCCTCTTCAAGGGCAGCAACGTGAAGACTATT---------GATTC
TGAACCTGTTGAAGAGGAAGAGGAAGACAT----------------------AATGGAGT
GGGAATTTGAATTTCCAG-----------------AGGACAGCAATAAGTCACTGTGTGT
AGCCCTGCAGCGGTTGCCTATTACTCTTCCTAGCTCAGGATCACCTCTGCCTCAGTTCCA
GATTTTGTCTTGTCGCCAGCAAAATGAA-ATCTTGCTTCAAGAGATCCAAGAAGAACAGC
CCACCCAGGGA----------------------------CTCAAAATCTCTGGATTGCCA
GATGCAGCCTCAT-----------GTTCACAGTCTAGTACTTCTGACTTCTCCCCACTGG
ATGACCTGATGGATTGTGCTGTCTGTCTGTCTGCTGGAGCTAcactgatttgtgcagaat
gtgggagaaGCTATCATACTCACTGCCATGTTCCACCAGTG---TTCAGA----CCAGTT
GAGGCG--TGGATGTGTACTTTATGTCAGGATATATTCAGTGACACTGACCCATTCAGTC
ATGATAGACTAGAGGAGCCCTACCTCAGTCTG------CAGGACCAGAGGAAGTGTGAAC
AGCTCTTGCTTACCCTGATGTGTGAGCAGCACAGTTACCTACTCTACAATGCACCCAAGC
ACACTGCTGG------------GTGTGTGGAGTTTGATTTTATTCGTGGACGGCTTCAAG
GGAAAAG---------GACTCCTCCATATCGCTCTGCAGCTGAGCTGGTCTCAGATCTCT
GGGCACTGTTTGATGTCCTATCAGCAAATTCCAAGAAGAAAGACTTGGTCAACAAG----
--------CTTCAAAACTCATTTAAAGAGCGGCTGGATGTAGTCTTTGGGATGAGCCTCC
ATGCTTCTCTCTTAAGGCCTCTCAACA---------------------------------
-------ATGAGGAACAGAAGGGGGCGCCAAAGACTGAGCTGGACA--------AAGACA
ATGC--------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------CAAAACC-
-A---------------------CTCTTAAGAGAATGAGAGATTTTTTAGCTGCAAACTC
CAACACA---GTAGCAAAGAAGCCCCTTACAGACAAC-----------------------
---TCCAGCAATAACT-CCC-CG
>Lepidogalaxias_salamandroides_Head_2|014695|scaffold12231|m.16086
TT----------------------------------------------------------
------------------------------------------------TCCATC------
------------------------------------------------------------
------------------------------------------------------------
--AAACCATTTTCAAAATCCCTCCTCACAATCTC--------------------------
----AGTCTTCTCCATCAAATTC---TACTCAG---------------------------
------------------------------------------------------------
-------------------------TGTCAATCCCCTTTGTCTCATTCGACCATCTTGGA
CTCTCCACAATCT-------CATTGCTCTCACCCTCACGATCCCAAAAATGTGGCTCCAA
AA----CCTCAGCCTGTCCCCTCCAACCCTCCAAAACCTCATA-----CAGCCATTTTCC
CCTCTGTCCC--------------------------------------------------
---------------------------------------------------TTCCCTACC
TTCC-----------------------------------------AAATCTCAAACTAAC
CAAAACCAGCTTGGTATTGGTTCACTTCAAGTTTTA------------------------
-----------------------------------------------------GCTCTGC
CAGCCTCTAGACAAACCCTGCTACCTTCCACACCAGCCATTAAAAGATCTCAGCCATTGC
TGTATGCTCTTCT----------------AATGGGTTCCGTTTTGCCTTG-------CCC
GTCACGCAACAAT----------AGTCAATCAAAATACTCAAACTC--------------
---------------CGGTAGTTTCAACAGCAGCAACGTCAAT-----------------
------------------------------------------------------------
--GCACAGCCAGTTTCCTCCACT-------------------------------------
------------------------------------------------------------
--AATTT-----------------------------------------------------
---CCAGACCACCATTTCTGCCGTCCATCTTGGTGCCTCCAG---------TTCATTGGA
AGTGCACAACCTTTCTACAAA--------------------------CCCAAGCACTATG
TACCTAGCCACACC----------------------------------------------
------------------------------------------------------------
------------------CATGCCTGCCGCAGACCTTTTA--------------------
--------GGATTACCTACTTGCCTACTTTCCAACCGGC-CTACTTTACAACTTTCTGTT
TTGGAAG---------------------------------------------GCCAACTT
------------------------------------------------------------
---------------------------------------GCCACCCAAGTTAACAAAACC
AT--------------------------------------------------------GA
GCCTCCCTCAG--------------CCCCAAGAAGTTGGTCCCG--TCCTCACAGTCAAG
GCTCTTGCCGACTCCCCCTGTGACAGCACATTC---------------ACTCCTGGCTGT
GTAGCTTCCCCAGAC------------CCCCATCTTACAGAGAACGAGCCCACTTCAACT
GTGTCTGATCCTGAGACCGATTTTCCCAC-------------------------------
-------------CGGGGCCTCCAGCTCCATCACAGTTCTCCCCCAAAaTAAGATGGCTT
CCTCGGGCAGTGAAGTTGCCAAAGGTGCCGTTCCAAGCTTATCAATCTCCGCCAACACAG
AACCTGCCTCTGGAGGCACTGCAAACTCCTCACCTATGCTCAGACCTCTTGCCACTGAGG
ACTTTGTACTTGATCCTGTACCCACGGCTTTGCCTTTATCGGTGGCTACTGATAGCTGGG
TTGCCAGCTCACTGCTAAAGTCTACCAGTACCTCTGTGGGGCCACAGCATATAGACAACC
CCATCCCAAGAGAGGATTCCACAAGGGAATCTACCATAAAACCACTGAGCACCCTTCTAG
GGAAGAGAACGTCATCCGTCCAGCCTGATGATAATCTCGTCGAAAAGGCAAAATGGCAGG
ACAAGGAGACAGACATGGGAATCCATACTGCCACCCAGTCGGTTGACAAGGCCGATTTGA
GCCCGAACTGGCCAGCCTCGCTTAAAGAAATACTGGAAATGGGATCGCC---TATAACCC
AGGACC-----AGACAACGTCAGAGGAGCTCAACTCAACACCCCCGAAAGACTCTCAAGC
GACGTCAAAGTCTTGTGACATCAAAGGTGTTCTTATCGCCGAAAATATGTCACCGAGAGT
CTCTTTGTTTCGGCTGCCCTTATCCAAACCTCCTGCCGGGGGACCCCTACCCCGGTTCCG
T-GTTAAGTCAGGGGCCAACACAAAGAAGATCCAGCTGGAGGAGATTAAAGAGGACCACC
AGCCCCAAGAGATT--------------------GACTTCTCAGGACCCTCAAA------
-------------------------------------------------CCCAACCACAG
ATCACCAGCTGTGCTGTAGCGCGTGCCACACGCACGGGAGCACGCTGCAGTGCGCCCAAT
GTAGGAGGAGCTTCCACAAAACATGCCACGttccacctatcatctcca------cctccc
GGAAAGGGTGGCGGTGCTCGTTGTGTCAGGATTTTTTGGAGAGTTCGGACCCCTACAGAA
CAGAGAGGAGGAGGAAGCCGATTCTGAGCCTG------CTGGACCAGAGG----GTAAGA
CTCTTTGTTTGTCTCTCTGTTGTGAGTGTCTCATCTGAACCCTTT---------------
------------------------GTTTTTTTT---------------------------
----------------CTCCCCTCCCTAACA----------------------GAAATGT
GA----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>Melanotaenia_praecox_viscera_mixture_8|007187|scaffold11022|m.9954
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------GAGT------
------------------------------------CTGAATCTAGAGGGG---------
-------------------------------------------------AACCGTTTTCT
CCTGAAA-----------------------------------------------------
------------------------------------------------------------
----------------------------------------------------CATCAGAG
GATGAACTGGTCAGTGAG------------------------------------------
------------------------------------------------------------
-----TCTGAATCTAGAGGGGAACCATTTACTCCTGAAACATCAGACAACGAAC------
------------------------------------------------------------
--------------------------------TGGTCATTAA------------------
----------------------GTCAGAACCATCTTCACCTG------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------AAAACAA----------------------------------------------
------------ACTGTTCGTCATCAAATCTGGAGACTCT--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------GAACACACCGGGGAACCGTT---------------------
-------------------------------------------------------TTCTC
CTGAAAA------------------------------TGAGGTGCCCATCAA--------
------------------------------------------------------------
------------------------------------------ATTTAAACCTATAG----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------GGAAACCATTTTACACTGAAT
gcatca------------------------------------------------------
--------------------ttttgtctg-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----atgaaaGCCAATCTTCATG---------------------CTTACAGTCTGAT--
--ACTGAGACATCA------------GACAGTGAG---AGTGAAGAGCCAGTGAGCTC--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----TGGGAATCCACAGCAGGATACCAACTTGTTCCAGTGGGAG-------CCCAGAGT
TTCTCTAACCAGACTGCCTCTATCCCTGCCTGGACAGGGATGTCCTCTGCCTCATTTTCG
T-TTGATCTTAGGAGAAGAGGAAGATGAGATTTACCTGGAGGAGATTATGGAGGACTCCC
AGTCCAGTTCTGTGT---CTAATGGAAACACCAACAACTCTGATAACGCCTGCGATGATG
AATCAGATGTCACCAAAGACTTCACATCACCTCTGACCTCTCCTGAGTCTCCGATGTCCG
TGGAGATCCTTTCCTGCTCGGCATGTGGCTCATCCGGCGCATCGAAAATCTGCTCAGCct
gcggtcgaggatacCACAGAGACTGCCATGTTCCTCCAGTTGGAGCTGA------CATCT
GGTCAGAGTGGATCTGCTCGCTATGTCAGGACCTGCTGGACCCGTCGGACCCCTACAGCG
CCGACAGACCGGAGACTCCACAGAGCGGCTGN---------------------NNNNNNN
NNNNCCTGTTGCACCTGAAGGTCGAAGGCTGCAGCCGGGTGTCT----------------
----------------------GAGCCCGGTTTTTGGTCGGATCTGCTGTTG-CTGTCAG
AGCGTCTGACCCAATATTCTCCTCCTTATCAGTCAGCTGGACAGCTGGTCTCTGACATCT
GGACTTTGTTTGAAGACGTCT---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------CACAGGT-
------------------------------------------------------------
------------------------------------------------------------
----------------------A
>Pantodon_buncholzi_mixed|011711|scaffold14533|m.18934
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------TGCCCCGTCCGGGCGAGCCGCTACCCCAATTCCG
T-CTGCTCCCAGCCTCCAGCGAGCAAAGCATAAAGTTACAAGTGCTGGAGGATGAGTCTC
CATCCCCCAGTGTG----------------------------------------------
------------------------------------------------------------
-----------GGCTGCATAGTGTGCCAGACCGCAGGCCAGCTACACACATGTGAAGCGT
GCGGACGCCGTTTCCACGGTGACTGCCATCTGCCACCGATCAGCTCAACAC---CCTGCA
GCAGGGAATGGAAGTGCTTGCTGTGCTGGGACCTATCTGACAACGAGGACCCATACTGCA
GCGAAAGGAAGCGAAAGCCTTCACTGAGCTTG------GTGGATCAGAAAAAGTGCGAGT
ATCTCCTGCTGTCCCTCATGTGTAAGAAGTGCAGCTCCATCCTGTACCACGTAAGGCAGC
GCTCCTGTCA------------TTATATTGACATGGCTCTGATCCGAGGACGTCTGCTGA
GGGGTCT---------GTCTCCTGCCTACCGCACCCCNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNTG--ACTTCCTTAGAGCCCAGACTGGTTGGGAAG----
--------CTGCAGAAAAGCTTCCAGAAGAAGCTGAGCGTAGTTTTTAG-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------
>Sargocentron_rubrum_gill_6|004543|C717859|m.48646
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------CACATCCCAGCTATC------AGACACTCCATTT
GGTCGGAGTGGAGCTGCTCGTTGTGTCAGGACCTGTCGGACCCCAGAGACCCGTACAGCT
CCGAGAGACGCCGGACGCCCTGCCTCAGCCTG------CTGGACCAGAGGAAATGTGAGC
ATCTCCTCCTCTTCCTGATGTGCGAGGACTCTGGTGATGTCTGGCATCATGCGG---AGC
CGTCCGGCGG------------CGGCTCTCAGCTCGGCCTCATCTCACAGCGACTGTCCC
ACCTCCG---------CTCGCCTCCGTACCGAACGCCGGCCGAGTTCGCCTCTGACGTCT
GGCTTTTATTGGACAGCGCATCCGCCTCAAAGCAGGACAGTGAAGTGCTCACCAAG----
--------CTCCAGCAGAGTTTCCAGGCCAGGCTAGTGGAAACTTTCGGGGTGGAGCTTC
ATCCGTCTCTGCTGAAGCAGGGCATTCTGGGATGGGCAGAGATGGAGGGAGATGC----A
GGAGAGCCTGAAGGGTCAAAGGTCGTGACGGACCCGACGGTCAGCG---GGACGGAGACG
AGCGAGGATGAGGGCAGTGGCTCGGAGCGCTCGAGCAGCGACGCGTTGAGCTCTTTGACG
TTCAGCGACAGTCTGAGCGAGGAGGAAGACCAGGAGGTCGCCGAGGGGTCACGGGGGTCA
--GAGGTCACATCGGCGGCTCGTTGCAGGCCAATCACGGAAG--GGAGAGGCCATACGTC
CGAGGAGGCCCGGCTGAGGGAGACTCGCAAGAGGCTGAGGGAGTTTCTGGGCTTGAACCG
CTGGCCT---CCGCCCAAGAAACCGACGCCGGACAAGACGGCGG----------------
------------------AGTGA
>Scleropages_formosus_red_gill|023324|scaffold36866|m.48204
ATGTGGACCCAGGACGGTCGCCCCGAGGAGGTGCAGGCGCGGGACGGGGGGTCGCGTTCC
TCCCAGGAGGACCCCTCCACGTGCCCGGCGTCTCCTGCCGCCCCCGTGTCCTTCGGGGAT
TGCGGCGCGTGCGGAGCTGCTCTGAGGCCCGAGACGAGCCCCCAGCTTCTGCCCTGCTTA
CATTCGCTGTGCAGAGCGTGCACGTTCCCGCCGGCGTGCCCCGCCGCCGGTGAGGGCACG
AGAGAATGTCCGCTGTGTAAACGGTCATATGCTCTGCTGGAGGTCACGGATAACCCTTTT
CTCAAGTATTCTGCATCTTCTTCGGGTACTCAGGAAGTCAGTAAGTGTTCCGGGTGTGAG
GAGTTTGCAATCAGCGGCTGGTGTGTGCAGTGCGGAGAAGCTCTCTGCTCAGTCTGTGTG
TCTGCGCATCAGAGAGTGAGGGTCACGCGAGATCACACTGTCCTGCCCCAGAAG------
CTTCCCACAAACT----CTACCCCAACATTGTTTTGCCGCACCCACAAAGAGGAGCCAGT
GAAGCTCTTCTGTAAAT--CGTGCAATCAGCTGACGTGTCGGGATTGTCAGCTGACTTTT
CACAGAAACCACAGTTACCAGTTCCTCCATGAGGCCCTGACAAGTCAAAGGGAGCAGATT
GAGTCTCTGTTGGCAAGACTGAGACAGCAGAAAAACATGGTGAAAGAGAGTCTCCTGGAC
TTGAATGGAAGGTTACTGGACTTGACAGTTATGAAATCCAGGCTAAAGGATGAGCTGCAG
GAAACCTTGGTTCGCATGCGCTATGTGTTGATGAAGAGATCGGTGAAGTTGTTCAAGGAT
GTGCAGGACCTGTGTGGGAGAGAGGCAGAGCGAGTCACTGAGAGGCAGGCCATGCTTAGA
AGGCTTCGGGAACGGCAGGAGCACGTCTTGTCCTTCACAGAGAAAGCACT-AGCCACAGG
CAACCACTTTGCTCTACTTTCCAGCAAAAGACAGATTCAGTTTCAGCTAGAGGACATTTT
ATCCCAGAATGTTTTCCCTGCAGCATCTGTGATGGACCTGAAATTCCACTTTGACCAGGA
CCTCTGTAATCGTATCACCAGATTTGGAAAAATCATTACTGAGGAAGTCCCCTTTGCTCG
CTCAGATGCGCATATCAATCCAAACCAGACTCTGGATCGGCCATTCCAAACTCAGGGTCA
CAATGTCTCCAAACCCCTTGGTTCCCG---------------------------------
-----------------------TAATTACACCTCCATTTCTGTTGCTTTCCCTCCCTCT
CCAACCCAGTGTCA-------------------------------------AGCTGATCC
TTCTCAGATTACACCCATTTCAGTCTGCTCTGTCCCCACTTC-------CTTCCAGCAGC
CTCCCTTTACTTCCTCTT----------TTGCCAATGTCACATTTCGTCCATCCTCTGCT
CTTCCAGCCACTCCTCATTTTATCCAGTCTTCTCCATCTAGCCATGTTTCTCCTGGACCT
CCGTTGCGTTCTTTCCAATACCACACTCGTCCGTACCGAGCAAAAAACTGTAAGACCTGG
TCTTTTCACAACTATCAACCAAAAAAGCCCAGACTGGCTCTTCGCCCAGTTTGCCCTGTC
TTACCTGATGGCCTTCAGTTTGTTGAGTCTCAACCTTCTGCTGCCTCCCCACTAATTATT
CTGAAGT-CTGTCTCCTCTCCAGTCAGGCTCTAC-----------CCCGTCACCCCACCT
CCCATTGTCATTGCATTAGATCCTCCCACCACCAGTATTTTGGATGGAAACACAGAAACT
ATTACCACATGCGCAGTTCAAGCCATTACGCAGACTCTCTCTACTCAGGTCCACAACGCA
GTCCCAACTGAACCTTGGCACTTGGACCTGGCTATAGAATCAGTCAAGTCCTTGAGTGAC
ATTTCACTCAGGCGAGAAGAACAACCTTTAAAGAGCCCATCAGGTTTCCTTCCTGTGAAA
GCTCTAGCAGATTCTCCATGTGAAAGGGCTGCT---------------GCTGCTGGCTGT
GGGAGGAAACTGGACAGGGACAGACAAACCCATGCTGCAGAGAATGAACCCACCTCAACT
GTAACAGAGACTGAGAATGTCTTTCCGGCTGAGG--------------------------
----TCCCTGACACAGAGGCTATTGTTCCTGAAAGG----CTGCAAGTCCAAGAACATGT
CCCTA--------------------------TGTCAGCTAATGGAGCCGTATCTACCATA
GGTCCCACAATGCAGAGAGCACAGAGTCA--------------GCCCTGCACTGAACAGG
ATTCTATTTCTCAGAC------------------------------------AGACTCAA
ATGATCCCC------------ATGATATTACAACTAGAAA--CACTGACTCGAAGAAATC
---AAATGAGAAAGAATTGCCCCATG-----------ATGG--TCTGCCTGTTCTCGTGG
CCGGTCAAACACCA------------GAAGCCAAGACCACTAAAATGCCAATAAGTATTG
AAAAATTG------CT--------------------------------------------
------------------------GGAAAGACCAGAGAACACCACCTCT-----CAAGTC
TCCTCTGATGAAGATGAAAAAAGAAGTGTT----------------------TATAAGCC
AAGCATGAGTGTTTCCAGCACTGAGGGAGCTTCCTTCAACGGGAACATGTTTCCTCGGGT
GTCTGTGCTGCAGCTGCCAATTTCACTGCCGACCCCTGGTCAGCCACTTCCCCAGTTTCG
C-CTCCTCCCAGGGTCCACCAAGCACAAAGTCTTCCTTGAAGTTATTGATGGGGATCATC
AGTCTGCATCAGTGAACTCCACTGA----GCCAAATCTCTCAGGCACGTCTCAGCCGCTA
GACTTGCCTGTGTC---------CCATCG-----------------------------GG
TCACGAGAACAAACTGTGCGGTCTGTCGGACCCCCGGGCAGTTGCAGCTGTGTGCGCGTT
GTGGGAGGGGTTTTCACAGGGACTGCCATATCCCACCACTCAGTTCCA------CCAGTT
GCAGTGAGTGGAAGTGCTTGTTATGTCAGGACCTTTCTGAGGATGAAGACCCATACAGCA
CTGAGAGAGAGAGAAGGCCTTCCCTAAGCTTA------CCTGATCAGAAAAAATGTGAGT
ACCTCTTACTGGCCTTAATGTGTAATCCACACAGCACTGTCCTTTTTCACACAGTTAAGC
TCTCATCACA------------TTATATTGACAGTAATCTAATTCGAGGGAGGTTATTAA
GAAAACA---------GTCACCTTCCTACCGCACTCCTTCTGAATTTGTATCTGATATAT
GGGTGCTCTTGGACACTTTGTTAGAAATTTCAGAGGAAACCAAGATGGTTGCAAAG----
--------TTGCAAAGGTTCTTCCAGAAGGAGTTGAGCAAAACTTTTGGTAAGAGCCTCC
ACCCCTCCCTCCTGAAATGCCCTGTCA--------GCAGATTTGTGGGGAGT--------
---ACGGATGATGAGGAAATGGAGGCATCCAGGAAGAGAGTGAAAAGCAAGGAGGAGTCA
GTGCAG------------------------------------------------------
TTCAGTCCTGATGTGCCTGTGAAGAAACATTGCCA-------------------------
-------------------------------------GGATGGTGGAAGTGGCACAGGC-
------------------------------------------------------------
------------------------------------------------------------
------AGCAACAAC-----TAA
