>Amblygaster_clupeoides|021809|TR38373|c0_g1_i1|m.59506
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------GACAAAGTGACCATCTTCTGCAATGGAACA
GGCCTGCCGATACCAGAGGTGGACTGGAAGGTCAATGACCTGGTCTCAATCAACAAGCAT
GACGCAATTTTGGGCAACACCACTCATGCAGTCAACCTGACTCTGATCGATATCAGCAGA
GAGGACAACAGCTTTCTGCTGACCTGCGTTGCGGAGAATAAAGTGGGGATGATTAATGCC
TCTGTTCATCTCACTGTGCAATTTCCTCCCACCATTGTGAAGCTGGAGGAACCCGTCCGG
CGTCACCACACCTGCATTGAATTTACGGTGCGCGGCTACCCGCACCCGACGCTGCGCTGG
TACATGGATGACAGGGAGCTGGAGGAGACGGAGTACGTGCGCACCGACATGGACATCTAC
---AAGGACTACC------TGGAGGGCTGCCTCACCTTCCAGAACCCCACCCACCACAAC
AACGGC------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Distichodus_sexfasciatus_gill_4|005818|C908431|m.53565
AACACAAGGCTTACATATGTGTCACTGCAAGCTTTTAAGAACAATCTCAAACTGCAGTAC
CTGAACCTGAAAGACAACAACCTGTCATCTCTGTCCTGGAAGACATTTCGGCATTTGAAC
ATTTCCTACCTAGTGTTGTCAGGAAACCCTCTGCAGTGCACCTGCGAGAATGTGTGGATG
AAGCAGTGGAAGGGAGACGACACTGATTCTGCTGAACTGCTTTGTGTGGAAGAAGATGGA
AAGAGAAGACCTCTCTCCAGACTTAATTTGCCCAGCTGTGTTGTCCCCACGGTCACCCTC
AGACCCCAACATGTGACAGTTCAGGAGGGATCAAATGTGACACTGAACTGCAACACTTCA
GGAATGCCCACCCCAGATCTCACCTGGAACA---TCTGTAGCAACACCTTAAACTACAAG
GTTGTCACTTCAGG---------ATCGTTCTCCGAACTCAAGCTTTTCAATGTCTCCTTT
CTGGACAACGAGTGTAAAATTAGCTGCAACTCTGACAACGCAGCAGGAGAGAGTGAGGCC
TCTCTTCAGCTCAACATACTTTTTCCTCCGAGAATCAGCAAGCTGATGGATGCCATTCCA
GACCACCATTGGTGCATCCCCTTCAGCATATCTGCCAACCCACACCCGGAGTTGAGCTGG
CTGTTCCGCAACAAGTCTATAACTGAGGGAGACTACATCAGCACCAGGATCCACGACTAT
TCCGAGCATGAGT------ACCACGGATGCTTGCAGCTTGACAGTCCGACACACTACAAC
AATGGCAAGTACACGCTGGTGGCCCGGAACTATTTAGGAGAGGACAGGAAGTCCATCAAT
GCCCACTTCATGCACGAACCCTGGAATGGCACATCATCTTCAGAACCAGTGTTG--TACT
ATGACCAACCAACAGATGACACACCTCTTGGACCACCTGAGGATCGAGTGGCTGTGTACG
TGGTCGTGGGAATCGCCGCCGTCACTTTCGCAGGCTTTGTGCTAATGCTGGTCGTCCTCA
AGTTTGGCCGAAACTCCAAGTTTGGCATTAAAGGTTTCGTTTTATTTCGTAACGTTCCAG
TGGAAGTCGTGGGACGATAA
>Gasteropelecus_sp._gill_3|018061|scaffold29210|m.30658
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------GAGGAAGGAGGG
AAGAGGAGGGTCCTGTCCAGTGTCAGCCTGCCCCGCTGTGTCATCCCCACGGTCACTCTC
AGCCACCAAAGAGTGACCCTTCTGGAGGGGTCAAACCTGACCATCACCTGTAAAGCCTCG
GGAACACCCACACCTGATCTCAGATGGAACAATGTCCCCAAGCTTAAATCCAATCACCAG
AACGTGACCTCAGG---------ACAGTCATATGTGCTCAGCATCTTCAACCTCTCNTCG
TTCGACAACGAGCACAAAATTGTCTGCAGCGCTGAGAACACGGCTGGAGAGGGTGAAGCT
TCTCTTCAGCTCGATGTTCACTTCCCCCCGAAAATCAGCAAGCTCATGGATGCCATTTCA
GACCACCACTGGTGCATCCCCTTCAGTGTTTCTGGCAACCCGCAGCCGAAGCTGACCTGG
ATGTTCCGTGGAGTGGCCATTGAGGAGGGGGCCTTCATCAGCACCCGCATCCACGACTAC
TCTGAGAACGAGT------ACCACGGCTGCTTGCAGCTGGACAGCCCTACACACATCAAC
AAC---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Lepidogalaxias_salamandroides_Head_2|001342|C464557|m.35285
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------CGCGGG
CAAAGGAAGCCCTTCTCCAGGTTTTCCCCCCCGGCCTGTGAGCCTCCAAAAGTGGAGGTC
AACCCTTCTTTTGTCAACAAGACAGAGGGAAGTGACGTGACGGTGACGTGTTCAGTGTCA
GGGTCTCCTACACCTAAACTCAGCTGGAATTTAACCTCCCTGCCCA---CCTTCTATGAA
AATTACACCTATGA---------TCTGGAGAGCACGCTTATTTTGAAAGACCTTTCACCC
AAAGACAATGAGAGGAGGATCACCTGCAGTGCAGAGAACGTGGTTGGCCAAACCGAAGCC
TCCGTCCTTCTAAACATCCTCTTTCCCCCCACCATCCTGCATCTG---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Melanotaenia_praecox_viscera_mixture_8|000751|C402424|m.25450
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------GTTTCCTAC
AAGGACAACCTGCACAATCTGACTTGTGAGGCTGAGAACCAAGCTGGGCCCAAAGAGGAG
ATGGTGCAATTGGACATTGAGTTTCCTGTCAAAATCCTCTTCCTGAGAGATGCCGTGCAG
CAGCATAACTGGTGTTTCCCCTTTGCCGTGGATGGCAATCCTGAGCCGAAGATTTCCTGG
CTGTACAATGACATTAAACTGAGAGAGAACCCTTTTGCATACACACAGTTAATCACAGAT
TCAGGCGACGGATCTGTGAAACACGGATGTCTCTTCCTGAACAAGCCAACCCACCTCGAC
AACGGCAACTACACCCTGATTGTGGAGAATAAGCTG------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Sargocentron_rubrum_gill_6|022854|scaffold6153|m.6970
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------ATGTGGATC
AAGCTGTGGCTGGGGGAGGAGGTCGACACACAGGAGCTGCGCTGCATCGATGACAGAGGG
GGACGCAAGCCGCTgtcaaaactCACACTACCTAACTGTGTGGTTCCCATGGCAACACTG
AGCCCATCCAAGGTGACAGTGAAGGAAGGGGCAGATGTGGTGCTGACCTGTAACACCTCT
GGGGTGCCCTCANNNNTGGTCA---------------------------CCAACTATGAG
ATCCAGACGTCAGG---------CCAGATGTCACTGCTGCGTCTGTCCAACCTCTCGTCG
CTGGACCACAACAGCAAGATCACCTGCAGTGCCGAGAACGTGGTGGGAGAGAAGGAGTCT
TCGCTGCTGCTGGATATCCTCTTTCCTCCCAACATCACTAAGCTGAGTGATGCAATCCCA
GACCACCATTGGTGCATCCCCTTCAGCGTGTCAGGAAACCCGGAGCCCCAGCTGCAGTGG
CTGCTAAACGGCGAGGCGGTGTTGGAGGGCGATTACATCATGACCATGATCCATGACGTC
ACAGAGAGAGAGT------ATCACGGCTGCCTGCAGCTGGACAACCCCACACACCTCAAC
AACGGCCTGTACACACTGCTGGCTACCAACGAATACGGACAAGACCGCAAGGCGGTGATG
GCTCACTTCATGCTCGACCCCTGGGAGGGAAC--------CGAGACAGATCCTGTCTATT
ATGATCCACCCACAGATAGCCCCCCTGTG-------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Scleropages_formosus_red_gill|013745|scaffold20975|m.27365
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------GAGAACATTGTTGGGGAAAATGAGTCC
TCTGTACTGCTGGACATTTTCTTTGCTCCGAATATAACCAAGCTTATGGACGCAGTATCG
GACCACCACTGGTGCATCCCCTTCAGCGTGGCCGGGAACCCGCAGCCGGAGCtgcgctgg
ctgtttAACGGGGTGGAGCTGGCAGAAGACGAATATATCCAAACCATGATCCACGAGTAT
GCCGATGGCGAGT------TCCACGGATGCCTGCAGCTGGACAACCCGACACATCTCAAC
AACGGCCAGTACACCCTGGTGGCCCAAAACAAGTTTGGC---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
