>Chanos_chanos_liver|002917|gb|GDQX01013563.1||m.4396
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------GAGGGGGGCCCACGGGGTTTTGGCTTCAGTCTGAGGGGGGGCAGT
GAGTATAACATGGGCCTGTATGTACTGGGACTGATGGAGGGAGGACCTGCCTCACGCAGC
CAGAAAATACAGGTGAGTGACCAGCTAGTGGAGATCAATGGAGACAGCACAGTGGGGATG
ACTCACAGCCAGGCTGTGGAACAGATCCGCAAGGGCGGCCACCGCATCCACCTGGTCCTG
AAGAAAGGCAATGGTTACGTACCTGACTAT------------------------------
--------------GACCGTGAGGAAGGAACAGCCTCCCCCTCCTCCTCATTTCACTCTG
AGGAGCCGGGTGTGGCTGCAATAG-------------------------ATTACTCTCTG
CCAAGGGACGGTAGGAGGGTGGATAAAGTAAAAAAGGACAGAAGAGAGAGGAGAAATAAG
GGAAG-----------------------CAGTGTAGAAGGAA---------GGAGCAGCA
GGAGAGGAGGCGGTGGAGAGGGGAGGGGGACTCCTTAC----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Corydoras_julii_viscera_mixture_8|015579|scaffold25412|m.21612
------------------------------------------------------------
---------------------------TTCGGATTCATCATCGCTACACAGGACGTTGGA
AATGCATCATCGTCGCTCTTCTCCCACAGGTTTATGACGGTGCGCAGAGGGAGTCCAGCA
GCTCGCAGTGGTCAGATCCAGCAGGGCGATCAGCTGGAGGCGGTGGAGGGACGTTCGGTG
CTCAACCTGCCTCACAGAGAGGTGGCTCAGATCCTGAGGAGAGCAGGAAACACACTTCGC
CTCACCATCGTCCCACGTGCTAATAACAATGCCTCCAACTTAACAGAATACACAGA---C
AAAACAGAGAGCAAGTTAAAAAAGGGCCTTCCACCCAAACAAA---AGGACCAGAGGTAC
TACAGCGTGGACCTGGAGAGGGGGCCGACTGGCTTTGGGTTCAGTTTGCGTGGGGGCAGC
GAGTACAACATGGGCCTTTACGTGCTGGGGCTGATGGAGGGGGGACCGGCATCCCGCAGC
CAAAAAATACAGGTGAGCGATCAGCTGGTGGAGATTAACGGTGACAGTACGGGTGGCATG
ACACACAGCCAGGCGGTGGAGCAGATCCGCAAAGGAGGACACCGCATCCATCTGGTCCTG
AAGAAGGGAAACGGATACGTGCCAGATTAC------------------------------
--------------GACCATGAAGGTGGAGCGGCCTCCCCCTCCTCC---GTCTGCTGTG
AAGACACAGGTGCAGCAGGAGTAGTTTTGTCCCAACCAGGGAGTATTAAGAAACCGCTGA
AAAAACGAGCAGAGGAGCGAATAAAACCAGAAGCAGAGGAGGAGCGGCGAGGCGCTCAGG
AGAGAGAACAGGATTCAGGCAACTTGGCAAGCAACGCAGCAAACTCCCACTCAGGAAGGA
AGAGAGAGCGAGAGAGGGCCACGCAGAGTGCAACCAAAACGACTTTGAGGACCACAGAGG
GAGAGGAGGAGGGTTTGCTGGAAGGAGAACAGAGGCATGGGGAGGAGGATCGAGGGCGTG
GGAAAAGGAGGAGTTCAGGGGGGAGAAGACGCAGCGGGAAGGGTGGAACTCCAGAGGGAG
ACGGGAGA----------------------------------------------------
-----------------------------------------------AGACGGAGGGAGA
AGGATGAGCAGCCAGATCAAAGAAGGAAGAAAGAAAATGAGGAGACTAGAGAGAGGAGAA
AGAAGGAGAAGCAGGAAGACCTGAATGTCTTGGAGGCCAGGAACGAGGCTGAAGAGAGAG
CACCCTTTTCCTTCCTCATGTCTTTTGATGAAGATGGCAACCTTTCTGAAGTCGAGTCCA
CGCACAGCTTCTCGGAAGTCAGTGTGACCGCCGCGAGCATCTCATTCGCGGAGTCGACCT
GGCCCTATGACCTAAGCGACTCCCGGGAGATCCTCCCTGTCCCGAACCTGTCCCCAGGCC
CCTGGCTCGTTCCCAATCCCCACAAACTCTCTCAGGTCTTAGACGAAAATCGTCTGAGCC
GAAGTCGA------GGAGATCTGTGGTTCTGA
>Distichodus_sexfasciatus_gill_4|002985|C869857|m.48984
------------------------------------------------------------
------------------CAGTCTGCCGTCAAGTCCGTCA---------AGGACTCCAA-
-----ACCATCGTCTCTGTTCTCCCACCGGTTCGTGGCGGTGCGCAGGGGCAGTCCGGCG
GCACGCAGTGGTCAGATCCAGCACGGTGACCAGCTGGAGGCGGTAGAGGGCAGATCGGTC
CTCACGCTGCCCCATCCTGACCTGGCACAGATCCTCAGGAGGGCAGGAAACACACTGAGA
CTCACCATCCTGCCCCGCTCACACACAAACGCCTCAAACCTGTCGGAGTTCACAGATCTG
GATCCAGAGGGCAAGTTAAGAAAAGGACAGAGATCCAGACAAA---AGGACTCGCGGTAC
TACAATGTGGATTTGGAGCGAGGCCCGACTGGGTTTGGTTTCAGTCTGAGAGGGGGCAGT
GAGTACAACATGGGGCTGTACGTACTGGGACTGATGGAGGGGGGACCGGCCTCACGCAGC
CAGAAGATACAGGTGAGTGACCAGCTGGTGGAGATTAACGGGGACAGCACAGTGGGCATG
ACACACAGCCAGGCGGTGGAGCAGATCCGCAAGGGCGGCCATCGCATCCACCTGGTGCTG
AAGAAGGGCAACGGATACGTCCCCGACTAC------------------------------
--------------GACCATGAGGGCGGAGCAGCTTCCCCTTCCTCC---GTCAGCCCCG
AGGAGCCTGCC-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Gasteropelecus_sp._gill_3|000815|C861705|m.43309
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------ATTCAGCATGGGGATCAGTTAGAGGCAGTGGAGGGCAGGTCCGTG
GTTACACTGCCTCACAGAGATCTGGCACAGATACTGCGACGAGCAGGGAACACACTCCGA
CTCACCATTATCCCCCGCTCCAACACCAATACCTCCAATCTCTCAGAATACACAGACTTT
GATCCAGAGAGCAGATTAAGAAAAGGGCCGAGATCCAAACAAA---AGGACCCCCGATAT
TACAGTGTGGATCTGGAACGGGGCCCTACTGGTTTTGGTTTCAGTCTCAGAGGAGGGAGT
GAATACAACATGGGCCTGTATGTGCTGGGCCTGATGGAGGGTGGACCAGCATCTCGCAGC
CAGAAAATACAG------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Lepidogalaxias_salamandroides_Head_2|005388|C505186|m.42105
------------------------------------------------------------
---ATGTTGGAGAGAATCCAGTCAGCGCTAAAAAGTGTCA---------AAGACTCCAA-
-----ACCCTCCACCCTGTTGTCCCACCGGTTCGTGACGGTGCGGAGGGGGACCCCTGCG
GCACGGAGCGGGCAGATCCAGCCTGGGGACCAGCTGGAGGCCGTGGAGGGCCGCTCCGTG
CTCACACTGCCCCATCGAGACCTCGCTCAGCTGCTGCGCCGAGCTGGCAACACCCTCCGA
CTCACCATCATCCCTCGCTCGAGCACAAACTCCTCTAGTCTTTCAGAATCCACAGAGTTT
GAGCCTGAGCATAGGACAAGAAAAGGCCATAGAACCCGGCCAAAGCAGGACTCTCGGTTC
TACAGTGTGGATCTGGAGCGGGGGCCCACAGGCTTCGGCTTCAGCCTGCGGGGGGGCAGT
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Melanotaenia_praecox_viscera_mixture_8|005774|C459396|m.32826
ACAGGACTGAGACAGACAGGACGTGTAGTTCTTTTGGTCTTTTTTGGGTCTGGATGGTCC
ATCATGTTGGATCGGCTGCAGTTGGCTCTGAAATCGGTCA---------AAGATTCCAA-
-----AACCGCCTCCCTGATGTCCCACCGCTTTGTGACGGTGCGGCGTGGCAGCCCGGCG
GCACGCAGTGGCCAGATCCAGCCCGGAGACCAGCTGGAGGCAGTGGAGGGTCGACCTGTT
TCTGGTCTGCAGCATCGAGACCTGGCCCAGATCCTGAGGAGGGCAGGGAACACGCTGAGG
CTGAACATCACCCCCCG-----ACAGCAAC-CGTCCTCCCTCTCAGAAGGAGCCAACCTC
AACATCGATGGTTGCCTGATCAAAGGGTCCAGAGGGAGGTCAAAGGAGGAGTCCAGGTTC
TACAGCGTGGAGCTGGAACGAGGTCCAACTGGTTTTGGCTTCTCTTTGAGGGGGGGCAGC
GAGTACAACATGGGACTGTATGTTTTGGGTCTCATGGAAGGGGGGCCGGCCCAACGCAGC
AACAAGATCCAGGTGTCTGACCAGCTGGTGGAGATAAACAGCGACAGTACGGCAGGAATG
ACCCACAGTCAGGCGGTGGAGCAGATCCGGAGAGGAGGACATCGGATCCACCTGGTCCTG
AAGAAGGGAAACGGATACGTTCCAGACTAC------------------------------
--------------GGCCCTGAGGAAGGAGCCCTCTCCCCCTCCTCCTCTTCACACACCG
AGGAGCAGGATTTAGTAACCATGA-------------------------CAACTACCTCC
CTCAGCCAACAAGGAGGAGGTGGTACGGGAGAAGAAGAAGGAGAGAGGAGGAGGAGGAGG
AGGAG-----------------------AGACATGGAAACCAA------ATGGAGAACAG
TATCAAGAGAAGGAGGAGGAGGGTTGGGACCTCCTGATCTAGACCTCGA----CCTTGTG
GAGAAAGAAGCAAGGGAGGAAGAGGTGAGGAGGAGGA-GGGAGGAGGAAGAGGCGGCAAA
GAGATTGCAAGTAGAACAGAAGAGGATAATAAAGAAGATGGGAAAGGAGGAGAGGGAGAG
GAGGAGGAGTCAGACGGTCAGGCAGAAGAAACGTGATGACCAGAGGGAGCAGGAGAGGAG
GAGCAGGAGCTTACCCAGAAACAGGGCTTCATCCTGGGGCTCGCAGCAGATGGAGGTGGC
AGGAGGAGCAGAGCGGAGGAGGAGTGAGACAAAGAGCAGCAGGAAGGAGGAGGAAAGCGA
TAACAACTCCACACACCTTGCAAAGCATCCTGGGAGCTCAGCCGGAGCCC----AGCGGG
TAGCGTTCTCCTTCCTCATGCCGATGGACAACGCCAAGCGTCAGTCTGACAGCGAATCAG
CAGCCAGCTATTCAGAGGTCAGCCTATCAGGAGCAAGCATCGCCACAGGGAGGGAGGACT
-------CTGATTGGAGGAAAGCTGAGTCGTCATGGCGACAGGGGAGC--ACCCCAGGCC
CGTGGCTGAAACCGAGCCAGCAGAAACTGACACAGGTTCTGATTGGCAGTCGGCTCGTTG
GGCGGGGACTAGCGGGCGGTCTCTCTCTCTGA
>Pantodon_buncholzi_mixed|011854|scaffold14678|m.19146
AAGAGA------------------------------------------------------
--AGACCTGGGGAGGGTTTTGGCTTTGTCATTGCATCTCAGGACCCTG-TGAATGGCAA-
-----CGCCTCCTCCCTGCTTCCTCACCGCTTTGTGACAGTGCGTAAGGGCACCCCAGCA
GCGCGCAGTGGTCACATCAGACCTGGGGACCACCTAGAGGCAGTAGAGGGTCGTTCTGTG
GTGTCCCTTCCACACCGTGAGCTGGCCCAGATCCTTCGGCGTGCTGGCaaCACCCTGCGC
CTAACCATCATCCCTCGCACAAGCATCAACACTTCTGATT---------CTACAGAAATT
GAACCCGACTACAAAACCAAGAAGGGGCATAAATCGCAAGCAA---AGGACTCCAGGTAT
TACAGTGTGGACCTGGAGCGGGGCCCTACAGGCTTTGGCTTCAGCTTGCGGGGAGGCAGT
GAGTACAACATGGGCTTGTATGTTCTGGCGCTGATGGAGGGAGGCCCAGCATCACGCAGC
CTAAAGATGCAGGTGAGTGACCAGCTGGTGGAGATAAACGGCGATAGCACAGCAGGAATG
ACCCATAGCCAGGCAGTGGAGCAGATCCGGAGGGGCGGACATCGCATCCACCTGGTCCTG
AAGAGGGGGAACGGATATGTGCCTGACTACGGACCATTTCATGCTGTGCAGCTGTTCTCA
TTGCTGTTTCCATTGGCCCTAAGCCCGGAGCAGCCTCCCCCTCCTCCTCATCGTACCCAG
AGGAGCCGGGTGTGGCTGCGATAG------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Synodus_sp._gill_5|019986|scaffold25464|m.35569
------------------------------------------------------------
---ATGTTGGAACGCCTGCAGTCAGCCCTGAAAACGGTCA---------AGGACGCCAA-
-----GCCCTCCTCCATGCTGTCCCACCGCTTCGTGACGGTGCGCAGGGGGAGTCCCGCG
GCCCGCAGCGGTCAGATCCAGCCGGGGGACCAGCTGGAGTCTGTGGAGGGGCGGTCTGTG
GTGTCCCTGCCCCACCGAGACCTGGCCCAGATCCTGAGGAGGGCCGGGAACACCCTACGC
CTGCACATCATCCCACGGTCCAACACTAATACTTCCAACCTATCAGACGCGGCGGAGCTG
GATACGGACGGCCGGTTGAAGAAGGTGCAGCGGGGGAGGTCAAAGcaggacgcccggttc
tacagcgtgtcCCTGGAGCGCGGTCCCACAGGGTTCGGGTTCTCCCTGCGGGGGGGCAGT
GAGTACAACATGGGGCTGTACGTCCTGGGCCTGATGGAGGGGGGGCCAGCCCAGCGCAGC
CACAAGATACAGGTCTCAGACCAGCTGGTGGAGATAAATGGAGACAGCACTGCGGGGATG
ACTCACAGCCAGGCCGTGGAGCAGATCAGGAGAGGAGGACACCGGATACACCTCGTTCTG
AAGAAGGGCAACGGATACGTCCCTGACTAT------------------------------
--------------GACCCTGAGCAGGGAGCCCTCTCCCCCTCCACCTCACCCATCCCAG
AGGAGCAGGGTTTGGATCCAGTAA-------------------CCATGACAACCGCCTCC
CTCAGCATGCAGAGAGGAGGAGGAGGAGGGGATGAGAGGAGGAGAAAAGGGGGAGGGAGG
AAGAG-----------------------AAGCAACAAAGGGAACAGCGCCCGAGGAGGTG
GGGGAGGAGGAGGAGGAGGGGGGAGAGCGACCCCCGACCTGGACCTGGA----TCAGCTG
GAAGGGGGGGAGGCAGGGGGGGAGGAGCGAAGGAGCC-AGGCTGCCAGACCGAAGGAGAG
GAAGAAGAGCGCGCTCAGGGGGAGAGCGACACGAGAGGAAGGCTGGGTGGACGAGTGGAC
CGCGGAG-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
