>Amblygaster_clupeoides|006835|TR17233|c0_g1_i1|m.32377
---------------------------------------------------ATGATCAAA
AGTCAGGATCAAGATGAATTTATTGCTGTCCGCGTTCAAGACCCTCGCATTCAAAATGAG
GGATCATGGAACTCGTACGTGGACTTCAAGATATTCCTCCATACTAACAGCAAGGCCTTC
ACCGCTAAGACTTCCTGTGTGCGCCGGCGCTACAGCGAGTTTGTGTGGCTGAGAAAGAAG
TTGCAGAAGAATGCTGGCTTGGTGCCTGTCCCAGAACTGCCAAGCAAGTCTTTCTTTTTT
TCATTCAATAATGAAGATTTTATCGAGAAGAGAAGGAAGGGCCTCCAATCCTTCCTGGAC
ACGGTTGTACATATGACGGTGTGCCTGTCAGACAGCCAGCTTCACCTGTTCCTTCAGACC
CAGCTGCCTGTTAGCCATATCCAAGACTGTGTGCAGGGTCTCACCCCATACACCGTCACA
GATGCCATCCTCACCTACGCTTCCTCCAATCAGGGCTGGGCTCAGG---AACAGGACAGT
GACACGCAGGAGCAATGTCCAACTCCTGTTCCCTATGAATCCATGGAG---AGCCCTTCT
CCCCACATGCCCTCCACTCAGCATGGGCCACCTCATACTCTCACAGCCAGTGGGGCAGCT
GCTTCTGTTGCTGCTGTGTCTGATTCTGTGACAGTGGACGTCCACGATGTTAACTTCGTG
GAATTAAAAGCACATACTCAGAGC------------AAGATGCT-------GGCTCCAAC
GGGTGACTGTCACATGAAAG-----------------CCATAGCGGAGGTTCACA---CG
GAAGATGCTGACTTGATAATTGTTGA---CCAGGAAGATGCTATCAT-------------
-CGAGGGAAAAGCCTCTGTGGGAACACAGCAGAGTAGGGGCGGTTA----------TGAA
GACACAGCTCTGGAAGCTGTTGGCCAAGTGGAGAGACTTTTG------------------
-------------------------------------ACAGAG-----------GTTAGA
CTTGGCG-AGGAGACTGTTACTGA------------TCAGCATCAAGAGGTCACCTTAGA
AGCCATCCATGAGGAATCACCTGAAGGTCAGGGGAGTTTCTTGGTAGAACA------AAA
TGAGGTGGAGATGGTGA-------------------------------------------
-----CAATAGAGATGA-------------------------------------------
-----------------------------------CTGGAGAA-----------------
-------------GACACATTGAA---------------------------------TGT
AGAACCCCTCCAAGAGGAAGGGAACTGTTTAAATAG------------------TGCTTC
TGACAATGACAGTTCTCTTTTGGAGCCACCTGC---------------------------
--------------------------------------TGTGCCTCAGAGTCTTGCTGAC
CATGAGAGTTTGCACAATAAAAGTGAAACAGACACCATCAAGAA----------------
------------------------------------TGGGCCAGTGGAG-----------
-------------------------------GAACACC----------------------
-----ATGGAGTTCAAAGCCAAAGTGAGGATGAGAAAGTAGAGATGACACCTGTTGGGGA
-------------------------------------------------------GAAAA
ACTCAGCACAGGCCGATGTAGATGAGGGTGTG----------------------------
-------TGTGTGGAAAACGCGGAACTGGAGGATGTCACTAACAA---------------
---------GGTTTTGCACAGTGATTACCTCCAAAGTCCGGATCACTGCGAAGAG-----
-------------------AACGACAAGACCAATGGTGTCCTGTCCAACGGACA------
--------------------------------------------------------CACC
AGCGACAG--------------------------------CTCAGTGATGAG--------
------------TGCCATTGAAGATTC---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------CACAGAGGA
AACCTCAGACTGTGATT----------------TCAGAAAAATGGTCAGCACCACCGTAA
T-----------------------------------------------------------
TGAGTCTGTGGTGTCCGACATTGGCGAGGACTG---------------------------
----CACAGTTATTTTGGAAGACGA------------GTCTCTTG---------------
--------------------------------AGGGCTGTGACCCTA------------A
AGCTAAA-----------------------------------------------------
------------------------------------------------------------
---------------ATCTGCCGT------------------------------------
------------------------------------------------------------
----------------GACGGGATTGGACAGCC---------------------------
--------------------------------------------------------TTAC
ACAGACCTCAGTACAC-------------------------------AGGCGGAGGGCAC
T--------------------GAAGGGGACCCCCA-------------------------
------------------------------------------------------------
--------------------TGGAAATGCCGGTCA-------------AGAGCAGGTTGA
T-----------------------------------------------------------
----GGTCTAATCAACCACATG---------GAGGCCACACCATGA
>Corydoras_julii_viscera_mixture_8|005167|C1248048|m.30912
---------------------------------------------------ATGATCAAA
AGTCATG---AAGATGAATTCATTGCAGTGAGAGTTCAAGATCCCCGTGTAATCAATGAA
GGATCATGGAACTCATATGTGGACTTCAAGATTTTCCTTCATACAAACAGCACAGCCTTC
ACAGCTAAAACATCATGCGTGCGACGGAGATACAGTGAGTTTGTGTGGCTTAAGAAGACC
CTGCAAAAGAATGCTGGTCTTGTACCTGTTCCTGACCTGCCTGGAAAGTCCTTT---TTC
ACCTTTAACAATACCGACTTCATTGAAAAGAGAAGAAAAGGTTTACAGAGCTTCTTGGAC
AAGGTGGTACACATGACGGTGTGTCTGTCCGACAGCCAGCTCCATTTATTTCTGCAGACT
CAGCTTCCTGTTGGCCACATTCAGGACTGTGTAAGAGGTCACACTCCTTACAGCGTGACC
GATGCCATTTTAACGTACGCCTCATCTAATTGCGGCTGGGCACAGG---AAGAAGTCTGT
GGGTCCCTCGTGGCATGCCCTATGCCAATTCCCTATGAATCAATAGAG---AGCCCGTGT
CCTAGTTTTTCAACTCACCTATTAGGCAGTGCTCAAAATAAA------------------
---------------------------GCATGGACTGGCGATAATGAGCTCATCTCTGTA
GCGCTTAACTTGTGTAAAGATAACGGCGATGAC---GAAGCACCTACTAAAGTTCTCAGT
AAGGAAAAAATACAGAATGGTGAGC------------TGGTAGTGGAGGTTTACCACCCG
GTAA---------CTCATTTGGAAAC---CCAAAACACTACCGAACAAGCCTATCTCAGC
ATACCAGATAAGAGGATGCAAACACACAACACCGAGGAAATTGATA------CATCTAGT
GATTCAATGGCACAGATGCAACCTGCAGGGGATACGCCTCAA------------------
------------------------------------------------------CCAAAA
CATGTAGCAAGTAATAATAACTGG------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----TTTGACTTGTCATTTTAA--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------
>Distichodus_sexfasciatus_gill_4|006690|C915873|m.55185
ATGTGTTGCTT-------------CACCTTTGG--------------CAGGATGATCAAA
AGTCAGG---AAGATGAATTTATTACTGTCAGGGTTCAAGATCCCAGAGTAATGAATGAG
GGATCATGGAACTCATATGTGGACTTTAAGATTTTCCTTCATACTAACAGCAAGGCATTT
ACTGCTAAAACATCCTGTGTGCGCCGGAGATACAGTGAGTTTGTGTGGCTTAAGAAGAAA
CTCCAAAAGAATACTGGTCTTGTGCCTGTTCCTGACCTGCCGAGAAAGTCTCTT---TTC
TCATTTTACAATACAGACTTCATTGAAAAGAGGAGAAAGGGTCTACAGGATTTCCTGGAC
AGAGTGGTGCACATGACAGTGTGTCTGTCAGACAGCCAGCTTCATCTGTTTCTGCAGACT
CAGCTTCCTGTTGGTCACATTGAGGACTGTGTCCAAGGCCACACCCCTTACAGTGTGACG
GACGCCATTCTGACTTATGCCTCTTCCAATCGCGGCTGGGCTCAGG---AAGAAGAGGGC
TGTACACTAGACCCATGCCTAGTGCCAGTATCTTATGAATCCATGGAG---AGCCCCTCA
CCGCACCTTCCTACTTTGCAGTATGATGCAGCTAGAAAGGAG------------------
---------------------------CCAGGGATGG---TCGATGGCCTGAACTCTGCA
GAGCTAAGATTGCATGAAGCAGACGTTACTTTATCTAATACACCTCCCAGAGATGGCCAG
GAAGAGGGAGCGCGGGAAAGGCAGACATGTGGTGATGTGGTAATAGAGGTCCATCA----
-----ACAAGATTTGCATTTGGAAAA---ACAAAACACTACACAGAA---------CGGC
GATCTCAAACCGGTAACACAAATGCAAAACCACACAGGGGACAACATTGCAGATTTTGCA
GATACAGTGTCAGAGGTACACAGTTCCAAAAGTAAGTCTCCA------------------
------------------------------------------------------GCTGTA
CATGGAGCTGGCAGTGGCTCTTGG------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----GTCAGTTTGATTTTTTAA--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------
>Gasteropelecus_sp._gill_3|014255|scaffold23819|m.23786
---------------------------------------------------ATGATCAAA
AGTCAGG---AAGATGAATTCATTGCTGTGAGGGTTCAGGATCCTCGGGTAGTGAATGAA
GGATCATGGAACTCGTACGTGGACTTCAAGATTTTTCTTCATACTAACAGCAAGGCATTC
ACAGCTAAAACCTCCTGTGTGCGCCGCCGATACAGTGAGTTTGTGTGGCTGAAGAGGAAA
CTGCAAAAAAATGCTGGCCTCGTACCTGTTCCTGACCTGCCTGGAAAATCACTG---TTT
TCTTTTAACAACACAGACTTCATTGAAAAAAGGAGACAGGGTCTTCAGAGCTTCCTCGAC
AAGGTGCTGCACATGACAGTGTGTTTGTCAGACAGCCAGCTTCATCTGTTCCTGCAGACT
CAGCTTCCTGTAGGCCACATTCAGGACTGTGTGCAGGGACACACGCCATACAGTGTGACA
GACGCCATTCTGACTTATGCCTCCTCAAACCGTGGCTGGGCTCAAG---AGGAAGAGGAT
GGGTCATTTGAGCCATGCCCAAATCCAATTTCATATGAATCAATGGAGAGCAGCCCTTCT
CCCCACATTCCCACTTTACACTGTGAAGGAGCTGCCAATGAT------------------
---------------------------CCGATGGTGGACATCACTGACCTCAACTCTGTA
GAACTTAGAGTATGTGAAGCAGATGAGGCTAAGCCTAACACAGCTGAtggagatgggcag
gaacaaagaatacaggaagaggagattcGTGAGCACCTGGTGGTTGAGGTCCATCACCC-
-----TCATGGTTCTCTTTTGGAAGACACTAAGGAAGACATGCATAA---------CGGC
GTGCCAGAGGAGGCAACACAAACACATGATAACACAGAAGATGCCA---------TTGCA
GATACAACCCTACAGGTACCCAGTTCAGCAGACAGGTTTCGG------------------
------------------------------------------------------CCAAAA
CATGTAGTAAGTAATGATAGGTGG------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----GTCAGTCTTTTTTTTAACCA------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------CACTCAACCACA-------------------GTTCTGA
>Lepidogalaxias_salamandroides_Head_2|020569|scaffold19331|m.26584
------------------------------------------------------------
---------------GCCTTTACCCTGCCACCGTGTCCTTTACCGCGGAGGCGAGGTGAA
AGGTCACG----CTGTATCTCCGCCCCC-----CCTCCCCAGACCAACAGCAAGGCCTTC
ACCGCCAAGACGTCGTGCGTGCGTCGGCGCTACAGCGAGTTCGTCTGGCTGAAGAAGAAG
CTGCAGAAGAACTCGGGCCTGGTGCCTGTGCCCGAGCTGCCGGGCAAGTCGCTC---TTC
TCCTTCCTAAACGAGGACTTCCTGGAGAAGAGGAGGAAGGGCTTGCAGTGTTTCCTGGAC
AGGGTGCTGCACATGACCGTGTGCCTGTCGGACAGCCAGCTCCACCTCTTCCTGCAGACG
CAGCTGCCGGTCGGACACATCCAAGACTGTGTGCAGGGCCACACGCCGTACACTGTGACC
GACGCCATCCTCACCTATGCCTCGTCCAATCGGGGGTGGGCCCAGG---AGGAAGAGGGC
GTGGCGCAGGAACCTAGCATAATTCCGGTTCCCTACGAGTCACCGGAG---AGCCCTGCA
CCTCACCTGCCTACCTTACCTCCTGCAGAACCCTTTAACGCT-----------------C
ACGCCCAGCAA-------------------------------------------------
---------------------------------------------GTCGAAAGCCCACCG
GACTTATGA---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------
>Melanotaenia_praecox_viscera_mixture_8|017817|scaffold5182|m.4413
---------------------------------------------------ATGATCAGG
AATCACGAAGAAGATGAGTTTGTTGCAGTGCGGGTCCAAGATCCTCGCATTCAGAACGAG
GGTTCTTGGAATTCATATGTCGATTATAAGATATTTCTGCATACCAACAGTAAAGCCTTC
ACAGCTAAGACATCCTGTGTGCGACGGCGTTACAGCGAGTTTGTGTGGCTCAAGAAGAAG
CTGCAGAAGAATGTAGGCTTGGTTCCAGTCCCAGACCTTCCAGGAAAATCCTTC---TTC
TCCTTCAGCAACGAGGACTTTCTGGAAAACAGAAGGAAAGGACTTCAGGCCTTCTTAGAC
AAAGTGGTCCACATGACGGTATGTCTGTCAGACAGCCAGCTCCATCTCTTCCTGCAGACC
CAGCTTCCTATTGGGCACATCCAGGACTGCGTTCAGGGCCTTACTCCATTCTCCGTGACC
GACTCTATACTCACCTACGCCTCGTCCAATCGGGGTATGGTTCAGGCTCAGGAGGAGGAC
TCCATCAAGGAGCCTAGTTTGAAC---ATTTCTTATGAGTCCATGGAA---AGTCCAGCT
CCCCACCAACCTTGCCTACAAACCACTGCTACCTTCAACTCT---------GGTTTTTTC
TCATGTGGAGACTCTGACCCTCTGGAAGATGTACTGGAGCTCAGTGAGCAGAGCTCAGAT
G------AAATGCGAGGCAAGGA-------------GAAACCCTCAATAAGGATCTCTCA
GTCCAGTAACCATCTAGAAG-----------------CTGTTGTTGAGGAATGTGGCCCa
agagaggccacatttTATCTGGGTGAGACACAAGATGATGCA------------------
--GAGAGCCTCAGCCCACCAGAGC---------AGAGAGGCTGTCT--------CATACA
CACACCAGTGGAGGTGCACTCACCCATGGTGACGGACTGT--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------
>Pantodon_buncholzi_mixed|014031|scaffold16923|m.22929
ATGCGATGGTTTTTGTCACGGTGTCACTTCTGGAGGCAGAAGCTTGCTAGGATGATGAAA
CACCAAGAACAAGATGAGTTTGTCACAGTGCGGGTCCAGGACCCACGGATCCAGAACGAG
GGCTCCTGGAGCGCTTATGTGGACTTTAAGATCTTCCTCCATACCAACAGCAAGGCCTTC
ACAGCAAAGACCTCGTGTGTACGTCGCCGCTACAGTGAGTTTGTGGTACTGAAGAAGAGA
CTGCAGAAGAATGCAGGGCTTGTNNNNNNNNNNNNNNNNNNNNNNNNN------------
---NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNCAAGGGTCTTCAGCACTTCCTGGAC
AAGCTGCTGCTGCTGACTGTGTGTCTGTCGGACAGCTGGCTGCATCTCTTCCTGCAAACA
CAGCTGCCTATGAGTCACATACAGGACTGCGTACACGGGCACACTCCGTACACGGTGACC
GAGGCCATCCTCACCTACGCCTCCTCCAACCGCGGATGGGCTCAGG------AAGAGGAG
ACTGTCCAGGATCACATCGTCTTCCCTGTGTCCTACGAGTCCGTGGAC---AGCCCTGCT
CCTCACTTACCTTCAATCCAAAATGGACAGAGCATTGACTGCAAGACC------------
---------------------------ACAGAGCTTGGGAGCCACAAGGATGTTTCCTGT
GGATTTGAAAGCGGTGATGAGGA-------------AGAGCTTC----------------
-------------------------------------TCATTGTGGGAAGCAACGAGTCT
GGAGCCGCTGCCACGTTC-------------------------------------ACAAC
TTGTGAGGTTCAGGTCCATAAGGACGAGG--AGATGGAAGATGGTGATG---GGATTGTG
TTTTCCGTTCCAGA----------------------------------------------
------------------------------------------------------GCAGGA
CATCCAGGAGGAGAACGTGCCTGA------------------------------------
------------------------------------------------------------
---GGTGGACGTTG----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------AGACTCAA------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------ACACTTTGCGATGA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------TGTTTGCT----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----GTGAATTACCTGCTCAACCC-------------CTTTCTGAC--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------TGA
>Sargocentron_rubrum_gill_6|012520|scaffold20097|m.24420
---------------------------------------------------ATGATCAGC
AGTCACGAAGAAGATGAGTTTATTGCTGTGCGGGTCCAAGACCCCCGCGTTCAAAATGAA
GGATCCTGGAATTCATATGTGGACTACAAAATATTTCTTCATACCAACAGTAAGGCCTTC
ACAGCCAAGACGTCATGTGTGCGCCGGCGCTACAGTGAGTTTGTCTGGCTGAAGAAGAAG
CTGCAGAAGAATGCTGGCTTGGTGCCAGTTCCAGACCTTCCTGGCAAGTCTCTC---TTC
TCCTTCAGCAATGTTGACTTTCTGGAGAGTAGGAGGAAAGGCCTTCAGGTCTTTCTGGAC
AAAGTGCTGCACATGACAGTATGCCTGTCAGACAGCCAGCTCCACCTCTTCCTCCAGACT
CAGCTGCCAGTTGGCCACATCCAGGACTGTGTGCAGGGCCACACCCCTTACACTGTGACG
GACGCCATCCTCACCTACGCCTCGTCCAATCGGGGCTTGGCTCAAGCTCAGGAGGATGAC
TCAATCAAGGAACCCAGTTTGACTGCAGTTTCTTATGAGTCTATGGAG---AGCCCAGCT
CCACATCTACCCTCTCTACAAAATAAAGAGACCTCTAACACT---------GGACTACTC
TCCTCAAGTGACGCTGACCCTCTTGAGGGTATAGTTGAAGTCCATGATAGCGACACAGAG
GTA---CAGGTCAGTCACTCTGG-------------GAAATCCTCCCTGAGGGTCTTGCA
GAAGAACAGCCACCTAGAGG-----------------CTGTTATTGAGCAATGCAGCCCG
GACGAGGTAACCTTTTTCCTGGGGGACAGCCAGGATGAGCCAGACCC-------------
-TGAGAGGCCCAGCCTTGCAGAACCGACTCAGAAGAGGAGCTGTCA--------AATACA
GACACCAGTAGAGGTGCACTCGCCCATGGGGCCTAGTTCTGA------------------
---------------------------------------GGAGAGCCATATGACATTAGA
TATAGCAAAGGAGACAATTCCTAGTGATCAAAGTGTTCCTTATCCAGACACCCAGGAGAA
AGCTGGTCAAGGG---------GACAGTCTTGGGG-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------AGACTAA----------------------------------TCT
AGAAACACTCAGCTGTGAGCCAGAGTTTCCGGA---------------------------
------------------------------------------------------------
------------------------------------------------------ACCACG
AATCAGTCCT---GAAAGGATTCTAGAATGCGCCACCTCCGAGG----------------
------------------------------------------------------------
------------------------------------------------------------
--------------AGATCAGTTATGAGGAACAGATTCTAGAA----CACCACGCAAG--
---------------------TTCCAGGGAACCAGTTCTAGACGACAGCCGTCCTGAGAA
GCTGGCTCTGGAACACAG------------------------------------------
------------------------------------------------------------
---------TGCCGTCTCTGAGGCTGAAGTTCTAGATCACATTAGCGGCTCAGAG-----
-------------------GAGGAGCACATTCCAGAA-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----GTCAGCTGTCCAG------------------------------ATGAGACTCGGAG
CTCAGACGGGCAAACGGACCTAGACAATAAACAAAGTGATGACCCCG-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------GGAGCACAAATGAGAAGGCAC
T-----------------------------------------------------------
----------------------CAAGACAGCGNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGTAA-------------------------
------------------------------------------------------------
----------------------------------------------
>Synodus_sp._gill_5|018937|scaffold24473|m.33496
---------------------------------------------------ATGATCAGG
AGTCACGAAGAAGATGAGTTTGTGGCGGTACGGGTCCAGGACCCACGGGTGCAGAATGAG
GGCTCCTGGTATTCTTTCGTGGATTACAAGATATTTCTCCATACCAACAGCCGGGCCTTC
ACCGCCAAAACATCCTGTGTGCGTCGACGCTACAGCGAGTTTGTCTGGCTTAAGAAGAGA
TTGCAGAAGAATGCTGGTTTGGTACCTGTGCCAGACCTTCCCCGGAGATCCTTC---TTC
TCCTTCAGCAATGAGGACTTTTTGGAGAGGAGGAGGAGAGGGTTGCAAGTTTTCCTGGAC
AAAGTGCTGCACCTGACGGTCTGTCTGTCAGACAGTCAGCTGCACCTCTTCCTGCAGACA
CAGCTGCCAGTCGGTCACATCCTGGACTGTGTACAAGGCCACACCCCCTACACTGTGACA
GATGCCATCCTCACCTACGCCTCATCCAATCAGGGCTGGGCTCAGGCTCAAGAGGAGGAC
CTCAGCCAGGAACCCAGTCTGAATCCAGTTCCTTATGAGTCCATGGAG---AGCCCAGCT
CCTCACCTTCCTGCCGTTCAAAACAAAGAGACAGCCAACCCT---------GTGCCCCAC
ACATCCAGTGATCATGGCCCCCTTGAGTCCACAGCAGTGGTTCATAGTGCTGATGCTGCA
GAATCTAACCTAAGTAAGGCCGA-------------AACGCCTTCGCTAAAGGTCATCCA
GATGGACAACCACCTAGAGG-----------------CTTTCTTGGAGAGTCACAGTCCA
GCAGGTGCAACTTTTTACCTGGGTGATGGGCAGGATGAGCTAGCCCC-------------
-TGACAGATCGAGTCCAGAGGACAAAACTCCACCAAGGAGCTTTCG--------AATACA
GACACCAGTTCAAGTTCACTCTCCCATGGGGGCTGGCTTTGAAGACAAATTTGAGACATC
ATCGCAGAAAGTGACTCAGGAGGAGAGCGGTCATGCAACAGAGAGCTGTGGTTTATTAGA
TATAG---AAGAgctaaTTCCTGTTGCACAGATCCTTTACCATGGAGACTTCAAGAAAGA
GGATGGTGAAGGG---------GATAGCTTGGGGACTTTTGCAGTGGCACATTCCTGCCA
TGAAGTGGAGGTTGTAGAACGTTATCTTGGCTCTGAGGAGCCAGTTGTAGAGCATGTCAT
CTCCTCTGGAAAGATCACATACGGTGTGGTTAGCTCTGATAACTCGGCTTTGAAATGCAC
TACGTCTGTCAGGGTTTGTGAGCATGGTGTCAGCTCTGGAGAAGAAAATGCAGAAAGCAA
AATTCTACAGCCTGACAGATTAGACGAGCCAGTTTCCGAAGATAACTCAGTGGAGGCTGT
AGAAGTTGTCGGCCTTGGGGGAGAGATTCTAGGTCAAGTTTATTCTGTGGAGCCTGTTCT
TGAACATGACCACTCTTCAAAAAATGCTCCTGTACACAGCCCTTCTGAAGAGCAGGTAGT
GGAACATATTTCCTGTGATGCTCTAATTCAAGAACACGTAAGCCTTGATGATTCGCCATT
GATCAACCCTGGGGAAAAGGTGCTGGAACACATATCCTCCAAAGGGCACATCTCAGAACA
TTGTCCATCTGAACATGTCCTAGAAGAAGAGAACGGAGAACTGGTGGAACAAGTTATTTC
TGATGAAATGGTTGTGGAACTGTTACCATCTGAACATCAGGTTTGTGACTATGTTGTACT
TGAGGAAGAAGTTCAGAACAGTGTTGAGAAGCAGGCTCCAGAAAATGCACCATTTGAAGA
ACATACTCCAGAACCTGTCCCTTCTAATGGACAGGTCTTGAACCAAGTTCATTCCGAAAA
GCTGATTCAAGAACAACATGTACTAGAATATGCCCCCTCTCAAGATCTTATTGTAGAACA
TTTAGACTTTGAGGGAGAATCTGTAGAACAGGATATTTGTGATGAGAAGGTTGTGGAACA
TTTGCCATCTGTTGCACTTGAGGAAGAAGTTCAAATACAGAACAGTGTTGAAAAGCAGGC
TCTAGAAAATGTACCATCTGAAGAACATATTCTAGAACTCATGTTTAATGAACAGGTCAT
AAAACAAGTTGGCCCTGAAAAATGGATTCAAGAACATGAAAACCTTGAAAAAGATCCATC
AGCATCAGTCACGTCTAAGGGCTTGGCACTGGAAAATGTACTCTCTGATGAACCAGTCTT
GGAACACAGGCCTGCAATTGAGGATTCAGAAAATGCTGATGAACAAGCTCTAAAAGGCAT
TTCTTCTGACCCGCAAGATAAAGGTTGTTTTCAATCAGAACAACATGCTTTAGAACATGA
CCACTCTAACGAACAGGCTTCAGAAAATGCACCTTCTCAAGAACGGGCTCTAGAGCATTT
AGGCATTGAGGGAGATGTCTGGGATCAAGTTCACGCTGATGAAAAGGTAGAAGAGCATGC
CAACATTGGTGGCGATGTTCGAGAGCAAGTCAGGTTTGATGAGCAGGTTCTCGGATATGC
CTTTGAAGAACCACTTCTGAAAGATGGACCCTCTGATAAGAATGGCGCCCTTGAAGAACA
AGCCTTAATATATGTTTCCTCCAAAGAGCAGGCTCTTGAAAATGTTAATTTTGAAGGTAG
CGTTCTTCAACAGGTTCACTTTGAGGGGCAGACGGTGGAAGACTTTTCCTCTGAGGCACA
GGAACATGTTACATCAGAGAATGATGAAGACTATGTTAGTATCAGTGAGCAGGTTCCTGC
AGTTGTCAGCTGCTCTGCCCAACAGAATGAAGAAATTACCTCTTACAAGGAAACATTCAG
TTCAGATATCGAAACAGCTGTTTACATCAAACAAAGTGATGACCTAGTCTGCTTGAATGA
AGCTGAAGCTGACTCTGAGAGCAGTCAAAAGGGAAATCTCTCTGAGCCCCATGCAACAGA
GGTAGAAAAGCCTGGAAATGGTAATATCCAAGAAAAGTGTAAACTACTAGACCAAAACCT
CACAACTGAGAGAGCATCTGCTGTTAAAACTTGTGATGTAGAGAACAGCAATATGTCACC
AGATGATGCTGTGAAAATGGACTCTGATAATGAAAGTAAGAATGACGAAGAGTATGGCGA
TGATGAAGGTGAAGAAAACATGATTGAGCAGACAAATGGATATTTGGAAACGGCTCCTCA
GGAGAAACATCACAAAACAGATTGTTTGGAATCCCAAACATTGAAGCAGACATCAAGTAT
TGAAACCCCTGTACAAGTCAGAAGCAGCTCCGGGGTAGAGGAGTGCAAGGGGGAAGTTAC
CAGGATCCAGGCTGAAGAAGAGAAGGGAATCTCCATCCTGTTTGACCCCAGTAGCTCAGA
TCAAAGCTTGCAGTCCTGTTCGCAGGGTAGTGGACACTTGATAATGGACAATGAGCTGGA
TGCCCAGCGCAGAAAAGGTGTGGATGAGTCAGCTAGTGATCAATGCTCAGAGCAGGTCAC
TCTGTCTGAAAAGTACACTGAAGCCTCAGAGCAGAACCGGGAAAGCAACCTCAGTGAGCA
CACAGATGAAAACAACCAGGCGGACAGTAATGATGCTGAGTCATAA
