>Amblygaster_clupeoides|021723|TR37796|c0_g1_i1|m.59369
CCTTCTGAGAGTCTGC--------------------------------------------
-------------------------------------------------------ATGTG
TACTACCAAAAGCAGATG------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--TGCCGACCC-------------------------------------------------
----------------------------------------------------------TC
GTCCTCCCAGTCCTGTTTGGACCGCT---------CGGAGGACATCTTCCCGGCATCCAG
CCCCCAGGCGGCCCAGCTTAAGCAGTCCGGGTTTGGGTTGGAGAGCCTGGCCTCGGCTCT
GTCCAGAGACAGCCTGTCCAGTGCATACA-------------CAGAGTCCACTCTACTCT
ACT---GTCAGTCCACACTGGATCACTCAGAAGG------CCCAGCAGAGAACATCCCCA
GGACTAGTGAACGTGCCCGGCCCAGACTGTGCAAGATGACTGGGCTCGACCTGTCC----
----------------------TCCTCAGCAGACAGCGCCACCAGCAGGGCTTCCAGTGA
GAAGACCCAGTGCACAGCGCTGTATTCCCGCCAA--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------
>Gasteropelecus_sp._gill_3|024487|scaffold4706|m.4486
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------GTTCTAGAGGGTA---------CAGAGGAGTTACAGTCTCAGGCCAG
TTTCAATCCAACTATGCCCCAACAGCAA---CTGGGACTGGAGAGCATGGATGCTGCCCC
AACTGAAGATAGCTTGACCAGCATGTACA-------------CTGAGTCCACACTGCTCT
ACA---GTCAGTACACGCTGGA------------------GTCTGACGATCCTGTGCCCA
GGACCAGTGAGCGCTCTCGTCCAAAACTTTGCCGCCTGCCAGgcctggagctgtcc----
----------------------tcatctgccgacAGTGCAGCCAGCGCTGCTCTCAGTGA
CACCACACAGTGCACAGCGCTGTGCTCTCGGCAGGGCACTGGAGACACCATTGAAGAGCC
AGAAGACATTCAAGCA--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------AGACCTCAACCCTCGG------------------------
----GTAACATGTGG---------------------------------------------
------------------------------------------------------------
---------------
>Lepidogalaxias_salamandroides_Head_2|020360|scaffold19086|m.26193
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------ATGTCAAGGATGTTTCAGAGGAGGATTCAGGGA--------------------
----------------------------------------------------AGGGTGAA
ATTGTGCAAAGGATCCTGGACATCCT----------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------CAANNNNNNN
NNNNNNNNCGCAGTGGCTCAACTTGCTCACTAAGCAGTTTGTGGACACGTCCACTTTGCT
GTGTAACGAACGCT--ACCACCTCATCCA-------------CAACAACCAAAAGACTCC
TC-----CCAGGGAGCGTAGGAATGACCAGCTG----------------------TCCCT
GGGCAGTGAGAGCCCCACAGTGGAGACCTGTTTGGATGAGGGGGGCACTGACACCGTTTT
GAGTGACGGGGGCACTGACACCTTTTTGACTGACGGGGGCACTGACACCGTTTTCAGTGA
CGAAGGCACTGACACTGCTTTTAGCGACGGGGGCACTGAGACCAGGGACACTGAGACCAG
GGACACTGACACCGTTTTCGATGAGGGTGCCACCAGCGAGTTGGAGCTGAAAGAGCAGAG
CG----------------------------------------------------------
--------------ACCCAGGCAAGGCCG-------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------CGCCGCAGAGC------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------
>Melanotaenia_praecox_viscera_mixture_8|001502|C412466|m.26462
GACCACGAGGGCCCGC--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------TGGAGGACCAGAGCCCTT
CATCAGAGAGTGCAGAAAACACCAGAGGAGGAGACGAAGATGTA----------------
-----AAGAGCAATGGTGAAAGTCAGGAAGGGAAGACAGAAAACAACATC-AGCTCAGCA
TCCACCCTGGAGAACCTGGATGTTACTGAGTTAAACTCTCTAGAAAAAGGTTATGTGGAC
TTTGCTGAACC-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------AAGTACCAGCTCAGCTGCTACA-------------CCTGGACCACCTCCTGCT
AC-----TGAAACAGAGCCGACCGGGTCAAAGGGTG-----------------GACTGGG
GAGTAAGAACAAAGACCCAGAGGAAAATATGGAAAGAGATGGAGATCCGGT---------
------------GAAGTTGGAAGCCCCAAAGAAACGCAGCGGCATCCGATTCCGCAAAAA
AACAAAGAAATCCAAAGAA-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------
>Sargocentron_rubrum_gill_6|008736|scaffold14917|m.17277
TGGCTCAACAGTCTGTGTCAGGAACACATCGATATCTCCACTGTGCTCCGGATTGAGCGC
TGCATGCTAACGCAGCAGGCTAGACAGGGTAACGTTCCCTCTAGAGAAGCAATCCATGTT
TACTACCAACAGCAGATGTTGAAGACCTCCAGAGAGTCATGTTTGGACTACAGTACCCAT
GAGGCTGAAGGACGAGAAGACCCCAGCTCCCATGGTGCCAAGTGGCAGAGCTTAGCTTGG
GATCTTGTAGCAGGGAGAAGACGAGAGGAAGAGGAACAGGAGGACAGGAGAACCGATGCT
GATGGAGGAGCAGCAGAGGACGGTCGAGCAGAAAGACAAACAGGAAGAGGAGGTCCAGAA
ACAGAGATGCAAAGGCTTGGAGATAGCAGAGCAGAGACTGTATCAGGAGGAGACACCCCA
CCTGCAAAACCACAGACAGAACCACTGGAGACCACAGAGGGTAAACCACAGACAGTATTC
AGAGAGGAAGGTGAAGCAGAGGGCTCACCTGTAGGTCTTGAGGCTCAGACAGTATTAGAC
GTTGTCTCAGTAGACCTCAGACCACAGACAAAGACCGAAGGAGTTTTCCCTGAACAAAAA
TCAGATTCAGAGACAGTGTTAGATGTTCCAGC--AGATACAGAAACCAAAACAGAGGCAG
GAACAGTAACAGGTAGAGATGTCCATGCAGCTGAAAgcccagctgtatgtgttccaCCAG
AGA---TTGTAACAGCAGAAGATGACTCAGAAGGAGATTTCCCAGAATGCTCAGTGGCCA
AAACCAGCCAAAGACCACGGCCCAAACTCTACAGGATGGAGAGAATAGAATCCTCTTCCT
C-----------GTCATCCTCTTCCTCAGTGGAGGAGAGGATCAG---------TAGAAC
AGACAGTCAGTGTACAGCTCTCTTTTCTCGTCAGGGGACGTCAGACAGCGCCGGGGAATC
AAACTGGCAACCTCCCCCTGCCTCGGACACTGATATACAGCCTGAGCACAAAGAAACACA
CACATATTTAGACACACCCACTCACCACACACACATCTTCACCAGCACCTCCTCCCCCTC
CTCACCCCTCCCTCCTCCCGGTGAGGCCGACATCCCCCCCTCCTACAGCCTCGCTCTGGG
CCTGGACGCCC-------------------CTGATGAGGTTG------GGGGAGGGGAGG
GGACGTCGGGGGCCTTCAGGAAGCGGCCGTT-CGTTAAGGTGCATGAGGAGAAAAGTGAC
TTCCTgtctgagcctgcctccatttcctgtcccctGCTGTCACGCACCCAGGAGCTGACA
GCCAGCGACCTGCTGAGGAACAGAACTTTTTACAATGAGGAGTTGGAGGCATCAGATCGT
TTCTGTGGCAACCAGCCCCAGCTGCTCCAGCTGTGCTATGCACTCTACAACATCCTCGCA
GCTAGGTCGGAGACG
>Scleropages_formosus_red_gill|003493|C1277420|m.73405
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------GACCAGA---------TAGAGGAGGAAGACTCGACGTGCAA
TTCCCAGAGTGCCATGCTCAAGCAGTAC------AAGATGGAGAGTCAGGACTCAATGGC
CTCTCGTGATAGCATTTCCAGCGCCTACA-------------CCGAGGCCACCATGCTCT
TCTCCCGCCAGTCCACACTGGATGATCTGGACGC------GACGTCCGAGTCCATCCCCA
AAACCAGCGAGCGTGCCCGGCCCAAATTGCGTAAAATGTACAGCATGGAGATTTCC----
-------------------ACATCCTCGGCGGACAGCGGCAGCAGCATTGTGTCCAGCGA
GGCCACCCAGTGCATCATTCTGTCATCACGCCAGGGTACTGCAGAGACCATTGAGGAAGT
GGAGGATGAGCAGGAACCTGGCGATGATGAGCAAAGCCAGTGGAGACCCACAGAACAAAA
TGCAGAAGGGG-------------------------------------------------
-------------------AGCAAGACCCATGGT------------------------GG
CCTGGAGAACCAGGTGTAGAGGAGCTCAAGCCAATGGGGGAGAAGGAAGAAGAGGAGGAG
GAGGGCTATGAGCTTAACGATGATGACTGTTGTCTGAAGGTGGAT---------------
-------GAGTGCATGGCCCAATCCTACACCCCTGACACAGATGCCCCCGCCACCTGCAC
TGATGCAACATACCCAA-------------------------------------------
------------CAGACGCAGACGTGCCA-------------------------------
---------------
>Synodus_sp._gill_5|023972|scaffold6519|m.7103
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------GAGGAGAATGGAGACGCAGAGGAATCTGGCC--------------------
----------------------------------------------------ACTCAGAC
ATGGTCCGGAGGATCCTGGACATCTTGCAGTT----------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------CCTATGGGCCATC-----------------TTTCTGGCCATGGTGGA
CGGACTGACCCAGTGGCTCAACCTTCTGACCAAACAGTACCGGGACACCTCCACCGTGCT
GTGCAACGAGCGCT--ACATGCTGATCCA-------------TAAGATCGGACAGAGCGC
AG-----CCACCCAGTCCCTG---GAGCAGCTG----------------------TCCCA
GGGCAGTGACAGCCCCACGCTAGAGACCTGCCTGGACGACACAGAGACAGAACACACACA
CAGCTGTCTGGAGGTGCAGGGTGTGGATGTGGCCGGGCGCTCCACCCCTCTGCCCCGGCT
GGGACTCGGCTCCACCCTGACCCCAGAGCCCCCCCCCGGCAGCACCCTCGAGCTGAGCCC
AGACCAGCGCAgcaaaCGGCACTCCAGGACCGCCAGCGAACT---GCTGAGAGACAGACA
GT----------------------------------------------------------
--------------TCTTCATCGAGGAGC-------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------TGGAGCAGAGCAGAGACTTCTACGCCTCCCAGGGCCGCCCTCTGAAGCTGCTG
------------------------------------------------------------
------------------------------------TTTGCTCTGTACAACCTGCT----
-----------GGCC
