>Amblygaster_clupeoides|021600|TR37594|c1_g1_i1|m.59143
------------------------------------------------------------
------------------------------------------------------------
---------AAACCAGATCAGCAGCCCTCCAGCCAAGGAGCTCTTTCTTCCATCCGGGCT
GCTATCATGAGAACCTCTAGAAG---------------------CACATCTCATGAGCAG
CAGAGAGA------------------------------GAGACGCCATAGGAGACCACAG
ATCACCATCCTCTCTGCAGAGCCAATGGCTCC---TTCCTGGTTCCCAGCAGCCCCTTCA
GCTTTGC-----------------------------------------------------
-AGGTTCCTCCCCCCTCTTATGAACAGGTGCTGAGAGAAAAGACTCGTGAACAGCAACAG
CAGCAGCAGTT----TGCGCCTCCCTCTCCTTCTCCGTCTCCTGTCACCACTTCATCCCT
CGCTCCTGCTCCCACTCAATCTCCCTCTCCCTCTCCGTCACACTCCACCATCGCAACGCA
GACTGA--------TGTCCCACCTGTACCCCCACCC-------ATCCCTCTACAGCCGAC
TGTTGCAGACAACCCAGCTGGAAGACCAGCCCTGAGGAGACCCCCCAGGCCTCCCAAA--
------CCCCCCTGTCTCCCCAAGCCAGACA--------------------TGGCGACGC
AGACCC--------------------------------------CCACAGCTCGCCCAC-
------------------------------------------------------------
------------------------------------------------------------
---------------------------CAGAAGAGCAGCCGGTCCGTCCCAGGCCTCGCC
CCCGCTCCAGAGCCAGCCTGCGGCCAATGAGC----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------GAAGAGCTGACTGGCTCTCAGCCAATCT----
------------------------------------------------------------
---------GCAGTGAGA------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------TGCAGCCAATGAA-----------------------------------
------------------------------------------------------------
-------------------------------------------------------CAGTT
GCA---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--TACCTAAGTCCCGGTCTCTGA-------------------------------------
------------------------------------------------------GCACTG
ACATTGT-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------TGTTGCTCAGCCTG-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------TTAGCAGCGAAAGAG-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------CAGTGCCTCAACCAAT--------------------------------------
-------------------CAGGAGAGAGCATGCAGTGACTGATCCA-------------
----------------------------------------------
>Corydoras_julii_viscera_mixture_8|015739|scaffold25578|m.21850
ATGGCCGAGGCCAGAGTCGGGGAGGAGGAGGACAGCCT---GCGGGAGACCCGGGAGAGC
GGCGGCGGAGGAGCCCGAAGAAACCCGAGGACCTCCGGAAACACTCCAGCAGAGCGGGCA
GACAGGAACAAGCCTGAACAACGTCTCAGCACTCAAGGGGCTCTTTCTTCGATCCGAGCT
GCTATTAAACGGACGTCCACCAGACCAG------------------GGCCGCCGGAGCAA
AACAGGGA------------------------------------GAGACGGCGTCCACAA
ATCACCATTGTTGCAGCTGAACCACTGGCCTCGAATGCCTGGTTTCCTTCTCCACCCGGA
GCATTTCCTGCAGCCCCACCACCTCCCGCTCAGCCGTCCTGGACTGGTGTTC--------
-AGCTTCCCCCTCCCTCTTACGAACAGGTGATCAGAGAAAAGAGTCGAGAGCAG------
----AGCACTTCCACTCCCACTGTCTCAACTCCTGCTCCTCCTTTTACCCCTTCCTCCTC
TTCCTCCTCATCCTCCTCATCTCCAGCTTTGCA---CCTTACTGCCACCATCTCCACCCA
AACTGAACCGGAGGTATCAGAGCCAGCCAGCCTCACC----AGACCTCAGATGCGCCGGC
CCCCAAAACCACCTC--------GCCCAACCCTCCCAGCAGCCCCTAAACCCACAGA---
-------GTCTTCACCAGCACACGCCA-----------CTTTAATTGAGCTCGATGAGCC
TGACCC--TCCCTGTGCCATACGAACCCAAACATGTCCTG----CCTCTGT---------
------CGACCTGCTGGACGA---------ACCCCTGTCCGAGCAGTTCGGAACTCAGAC
TGAC------TTTGATGTTGATTCAACAGACTCT----TTGGCCTCATTGTCCATCGCCT
CCTCCCAAACCACCCAGTGCCCAGTAAAGCAGGATGTGTCAAACCGCCCAAAGCCACGCC
CTCGCTCTAAAGCCTTCTTGCAGCCAG---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------CCGTCAAAA------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------AT
GAGAACCAGGATGT----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----GTCAAACCGCC---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------CAAAG-------------------------------------------------
------------------------------------------------------------
----------------------------------------------
>Distichodus_sexfasciatus_gill_4|006984|C918051|m.55788
ATGGCGGAGGCGCGAGCCGTGGACGAGGAGGAAAGTTT---ACGGGAGGCGCGCGAGGCC
GGC---------GCGAGGCGAAACCC------------------GTCGTCAGAGCGAGCA
GAGAGGAACAAGCCCGAACAACGCCTTTCCAGTCAAGGACCTCTCTCTTCCATACGAGCG
GCGATCAAAAGGACTTCCAGACCGGCGA------------------CCCAAACCGAGCAC
AACAGAGA------------------------------------AAGACGACGTCCAGAG
ATCACCATCCTTTCTGCCGAACCGCTGCCCTCCAACTCCTGGTTTCCGGGAGGTTCGGGG
GCATTTCCAGCTGCTCCACCTCCTGCTCCGCCCTCCTGGACTGCTGGTGTCCTTACAGTA
CAACTTCCCCCACCTTCGTACGAACAGGTGATCAGAGAAAAGAGTCGGGAGCAC-AAC--
----------------------------GTTCCCACCTCCTCCGTCTCCTCGTCCCCTTC
CTCCTCCTCCTCTTCCTCGTCTCCGGCCCCACGTCGTTCCACTGTCACCATCGCTACGCA
AACCGAAACTGAAGTTTCTGGATCTCAAAGCCGAACC----GGACCCCCGGTTCGTCGAC
CTCCGAAACCGCCCC--------GTCCCACCCTTCCGCTCACACCCAAACCGGCTGAGC-
--------------CCGTCCCCCCTCAAACA---CACGCTCTGATCGAACTGGACGATCC
CGAACTGCCCTCA---------------ACACACG---------CTCCGACGCCCACACA
CAGCCACGACATTTCGCACCA---------GCCTTTATCCGAGCAGTGTGGAGTCCAAAC
TGACGAGAGCTTTGTCG-----TCAGCGGTGACG-ACCTCCCCCACATTTCCCACGATCC
CCCGCTACGTCGACGGGCG-------AACGAGGACGTTTCGGCGCGTCCCAGACCACGTC
CTCGATCCAAAGTTTGCTTACAGCCAGTCAACCGAGAGGACGTCCTAAATCAACCAATGT
CACGAGAGGTCAAGGTTCAGACCTTGGTGCGGCTGAAGGATGACGGCACCGAAAGCGTTT
ATGCCGGATTCGCAGACAGTTCCAT---------GGATTCTTGCTCCAATAAATATCTAC
AAGAACTCTTGGACGTTTTCGGATACGATGAGAAGAACTGCCAAAGT-------------
-----------------------------------------GACCAGCAAAGCGAAAGTG
ACCAAAGTGAGAATGAG-----------GAAGATCCAA-----CTTCAGACAGCTTTCTC
GGCAACGTTCCGTCACCATCTCCCGAA---------------------------------
---------CCGTTAAAA-----AGACCACAACCACGTCCGAGAACTCAGAATCCCAAAA
CGCCAAAC------------------------GTCCTTAAACCGTCGGACCCAACG----
------------------CAGGACAAGCAGAAGATCGA-AACTTCATCTGA---------
------------CAAAACGAATAAA---------CAGAAAGTCAGCCCTCCGATCCCTGC
TCCCAGACCTCTGCTCAAAAAAGCTTCAGTATCCCCCCAGCCGAGCTCTTCGGAGGAGGA
GAGAACCGAAATGGGGCGACTCCCTCC-----------TGCCCCAAAACCCCCGTTGGCT
GCC---------------------------------------------------------
--CGCAGATCTCGAGTTCCGACCCAGGCTGAAGAGCCCACTACTGGAGGGCCTAAAACTT
TCAG---AAAGCGGGATGTGGACGATCAGAACAGCAGCTCGGGTTCGG--GTTCTGATGT
TCCGCTGAGGCCAGCACCCGTCAACGCAGGCAG---------------------------
------------------CGTAAAATGTCCTGCCGGCCCGAGCCAAAACCAGCTGGCCTC
TAAAGCTAAGCCCCCACTGCTGA-------------------------------------
------------------GGAGACCCCCACC-------------------TCCAGCACAA
ACATCTG-----------------------------------------------------
--------------------------------------CACAGGTGCCTGCTAGTGCCGC
AAATACTACCAAAGCTGCAGCTTGTCCCGTCCCGTCACTGCCACCACGTCCGAGTGAAGG
TCGACTGCTTCCACTTCGTCCTCCTCCCATCAAAC-------------------------
------------------------------------------------------------
-----------------------TGAACAAATCGCCAGCTACGTCCCAAACC---CCGGC
TCCAACCGATAAGCCAAAAAGCTGCAAAACACCAAAACGAGGACCACCGCTGCCCCCCAG
ACCAAAGCCGGGGCATCCTGTCTACAAAGAGTACCTGAACAAAGTTCTTCCAGAAAGTTC
AACATCGAATCAGTCAGACTCTGAGACGCAAGCTCCCAGCTTTGAGAAAGAAGAGCTCTT
CGTCACTCTGGATGACACAACTCCTGCACAAACCCCCGGCTTCCCCTCAGAGAAGGACAA
AGGTCAGAGCGAGGCCAAGAGCGCTG----------------------------------
---------------------------------------------------AGGTATTTT
CAGCAGCATCGG----------------------------ATGAACCATGCATGACAAAA
GAAG-AGAAGAACCCTCCTCCAAACAGCAGCGTCAGCTATGTGGCCCGGTTTGCGTACGA
AGGC---GAAGATGACGAGCTGACGTTGCGAGAGGGCGACGTGGTCCAGTTAATCGAATA
TGTAAATGAGGAGTGGGGACGCGGCCGCCTGGAAGATGGACGAACGGGACTCTTTCCTCT
AAATTTTGTCCAG-----------------------------------------------
------------------------------------------------------------
----------------------ATCGTCCCAAAAAAGCCTGCTCCGGAATCTTTTGCGCC
CCCTG-------------------------------------------------------
--------------------GGAGAGAGATGCAGAAAGG---------------------
------------------------------------------------------------
------CAGAGCTTTATATGATTTCCTTTCAGAGGCTGAAGATGAGCTGTGTCTCAAGGT
CGGGGACGTGGTTCACTCTCTGGAGGAGGCAGATGACGAGTGGTTTGTGGGAGAATTCGA
TGGGAAGCGTGGCATCGTTCCCAAAAACTACATCCAAATACTCTAA
>Lepidogalaxias_salamandroides_Head_2|006161|C512438|m.43381
ATGGCCGAAGCGAGGATCGAAGAGGAAGAGGAGAGCGT---GCGAGAACCGAGGGAACTC
GTC---------ACGAGACGGAATCC---------TAGACCCGCACCCGCAGACCGCTCA
GAGAGACATAAGCAGGAGCCTCGTCTGTCTGGCCCTGGTGCTCTCTCCTCCATTAGAGCA
GTCATTAAGAGAACTTCCTCGAGGCCTG------------------CCTATAGCGATCCA
ACCCGAGA------------------------------------CAGACGGCGTCCCGAG
ATCACCATCCTGTCCGCAGAGCCGCTAGCTTCTAACGCCTGGTTCCCTGGAGCTTCCGCT
GGATACCCGCCACCCCCCCCTCCAGTACAGCAGCTCTGGGGGGCCAG-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------CTTCCCGGCAACCATC--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------CAGGCCCCG--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------
>Melanotaenia_praecox_viscera_mixture_8|018694|scaffold6676|m.5674
ATGGCCGAGGCAAGGTCAGAAGAAGAGGAGGAGAGCATGAGGAGAGAAACTCGGGAACAA
GTG---------GTCCGGAGACAGCC------------AAACAGCTCCGGAGGTCGTCCT
GACCGCCGTAAGCCAGAGCATCGCC---ACAGCCAAGGCCCTCTTTCGTCCCTCAGAGCA
GCCATCAAGAGGACCTCCACCAGGCCGACTTCTCTCTTAGAGA---CACCCAGGGACAGA
GATAGAGATAGGGACTCGGACAGAGACAGAGACAGAGACAGAGNTAGGAGGCGACCAGAG
ATCACCATCCTGTCTGCAGAGCCTTTGGCCTCCACGTCCTGGTTCCCTGGGGCGGCTGGA
GGATTCCCTCCTCCCCCTCCTCCTGCTGCACAGATCTGGGGGTCGACGATCCCTCCCGCC
ATACAGCCTCCTCCTTCCTATGAGGAGGTGATCAGAGAGAAGACACAGGAGCAG------
----------------------------GTCCTCCTCCCATCT---------TCCTCCTC
TTCTTCCTCATCCTcctcatgcccagt---------ctcttcaataaccatcgcgacGCA
GACCGA----------TCCGGGATCTTCCCCTGATCCTCAGGAATCACAAGTAAGGAGAC
CAGTGAGACCCCCCC--------GGCCGCCTCTTCCGAACCCTCCAAAATCAACCGACGT
TGAGAACGTCACCACCACCAACTGCCAATCAGCGCTCACGTCTGTTGACATTGACAGCGT
GGTGCCGCATGCATGTTCTGAGACGGTTGCACACG---------CCTCCACAGACACACA
ATGCTGTGATCTCCTCActgagctgtgttcaccttTGACCTCAACCTGCAGCACGCAGAC
TAA-------------------TCAATGGGATCA------GAGTACTTCTCATGTGGTGC
CTCCTCTTACCACCAGCC---------CTCCTGTCCTGTCGGAGCGTCCCACACCACGTC
CT----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------
>Sargocentron_rubrum_gill_6|005688|scaffold10346|m.11567
ATGGCCGAAGCCAGGACTGACGAAGAGGAGGAAAACAT---GAGAGAAACCAGGGAACAA
GTG---------GTGAGACGACAGCC------------AAACAGCTCCGGAGGTCGTCCA
GACAGACGCAAACCAGAGCATCGTC---ACAGCCAGGGTCCTCTCTCGTCCATCAGAGCC
GCCATCAAGAGGACCTCCACCAGGTCTACCTCTCTGTCCGAGG---CGCCCAGAGAGCGA
GAGCGAGA------------------------------------CAGGAGGCGACCGGAG
ATCACCATCCTGTCAGCAGAGCCGCTTGCCTCCACTTCCTGGTTCCCGGGGGCGTCTGCA
GGTTTTCCTCCTCCGCCTCCGCCCGCCGCACAGATCTGGGGTCCCACAATCCCCCCGTCC
ATACAGCCTCCTCCCTCCTATGAGGAGGTGATCAGAGAAAAGACTCAGGAGCAG------
----------------------------GTTctcctccccccttcctcctcctccTCCTC
CTCCTCCTCCTCCTCACAACGTCCCAT---------TTCCACGACGACCATCGCCACGCA
GACCGA----------CCCAGGCTCTGCCCCCGAGCCCTGTGGCTCTCAGGTTAAGAGAC
CAGTGAGGCCACCAC--------GACCGTCTCTCCCCTACACTCTTAAGCCTTCCCACGT
TGATGACATCATCAATCCTGCCAGCCAATCATCGCTCATCTCCTTGTG---TGACAGCGC
CGGACCAAACACACAGCCTGCCGGCGTCACGCACGCCACGCACTCCTCCACACACACACA
GTGCTGCGACCTCTTCGCTGACATTTTTTCACCTTTGACCTCGGCCTCTGGTGCTCAAAC
TGA-------------------TCAATGGGATCAAACTGTGGCTGCTGTTACCGTGGCGA
CTCCTTCTGACACCTCCG---------CAGGCGCCCCGCTGGAGCGTCCCAGGCCCCGTC
CCCGCTCCAGGCCCCGCCTCCAGCCTGACAGCA---------------------------
---CAGAGGTCAAAGTTCAGACTCTGGTGAAACTCCGTGAGGACGGTTT---GGCCACGC
TTGCCGCCCGCAAAGGAAGTGACATCACCAATCAGGAAGTGAGCCAGGGGAAGTACCTGC
AGGAGCTCCTCGAGGCCTTCAGCTCTGACGACTGGGGCTTCCCAGATCACCGTAGTGACG
GCAGCGGGCTCAGCCAATCAGAGGGCGAGGAGGGAGACGAGGACCAGGAAGAGGAAATAG
AGGAGGGGGAAATGGCGACTCTGAAAGCGAGGATCCAG---GCCTTCGAACAGCAGC---
AGCAGGTGGCTGACGGTAGCTATGGAAACGGTACCTGTGGAGACCGTGGGAGCGTTGATG
AGGCCGCCTTCGCTAAAAGACCCGAACCCCGGCCACGCCCGCGTCTCCAGGG--CCAGCC
CGCCAAACCAGCCCCTCCTGCCGTTGCCCCAAAACCCAAAACCTTCGCACCCAACATCAA
GCCGTCCAGCAAGGGATTCTGGGAAGACAGACCATTGACAGCAGCATCAGACTCAGGTGG
CGTCGACGCCCCTAAAACAACTGAAACCCCGACTGCAGATGTGAACCCTGCTGAACCGGC
GCCTTCCTGTCCCCCAAAACCTGCTCCAGTTTTGGCTCCA-CAAGCCCCAAAAACCACAG
AAAAACCGGTA---G-TGATTCCCCCCAAACCCCTCTGTCCCATAGAACCTCACCCAGCT
GCCCCGGCCCCAGTCCCCGCCCCCCGCCCGCCCCCACCCAAACAGAGCTCCTGTCAGGGT
GACACCAACCCCAAACCCCCACCCAGGCCTCCAGTCGCCCCCAGGGCCGGCGCCGGAGCT
CCGACCCAGGACAGGAGCAGCACGGCTGGGCCGGCCGGCCCGACTCTGCCCCCCCGACCC
TCCACAGAGGGCGGCA-ACGCCGGTGCAAGCAGTGGCGGGGCGGAGCCTCCCACACCGGG
CACGGAGACACAGACAAACACCAACCACACTGTGAAACCAGGAAGTGCCCGTCCAGGCCT
CCCGACCAAACCGCCAGCGCTGACCTCACCACGCAGAGCCAGCGCTCCAGCTGTGGCCTC
CAAGCCTGCCGGACCCTCGCCAACTCCCACCAACCCAGATCCGGCCCCCGTCCTGCACAA
ACCTCCTGCCCCGGCTGCAGCCTCTAAGCCAGCTCCAGGACCGGCTCCGGCCCCGGGCCT
CAAGCCCCCGGCTCCGGCCCTCAGGAAGGGCCCTCCGGCTCAGACGAAAGCCGATACCGC
GTGCACTGC--AAACCCGAACTCGTTGGACCCC-CCTCTGCCTCCACGGCCGTCAGGGGT
GAAGCTCCTCCCCCTTCGCCCTCCACCCATCAAATCTATTCCCGGCCGACCGCCCCCTCC
TGCCGTCAGCACTACTTCCTCCTCTCCAGCCAACCAGACGCCTCCTCCTACCAAAACTAG
CCCCTCCCCCTCTCCCTCTCCAGCCAACCAGGTGCCTCTTCCTTCCAAGACCACTCCACC
TCCGGCCAATCAGAAGCAAGCTCAAAAGGTGCCGAAAAGAGGGCCCCCTCTGCCCCCCCG
CCCTAAACCTGGTCACCCCCTGTACAG---------------------------------
------------------------------------CAGCTATGTGAAACAGGAAGTCCT
GGTTGTCCTGGATGACCCAAGCCCCGC---------------CCCCTCTGAGAATCTTAT
GGGTGAAGGGAGGGGTCAGACCGCCGTCACCCCTCTCATCGACCAATCACAGTGTCTGCT
GGACCTGGACATCCAACCAGAACTGGTCCCTGATCTGGACAACCAATCAAAACGCAGCTT
GGAGGGCCTTGGCCTGTCAGAGTCTCAGTCCATCCTGCCTGTGCAGCCTGCAGAGCAGAA
GGAACAACCAGAGCCTGCTGCTGTCAGCGGTCCCAGGTGTGTGGCCAAGTTCGACTATGA
GGGCGAGGAGGAGGACGAGCTCACCTTCTCCCAGGGTGATGTCATCGCCCTGCTGGAGCT
GATTGGACAGGAGTGGGGGCGGGGCCA---GATCCACGGGCGAATCGGAATCTTCCCCCT
CAGCTTCGCCGAGGTGGTGGAGCCCCTCCCGCAGCCGCCGCCGTCGTCCCCAGGGGAGAC
AGCAAAAATCGCACCAACGCCGACTGCAGATCCCGCAGCGGTAGAAACTCCTGCAGCACC
AAAACCCTCACAGGACCAGGACTCTGTGGCGGAGGAGTGGGCGCTGGCCTTGTTCGACTT
CCCCGGTCAGACTGCGGAGGATCTGTCCTTCCAGAAGGGGGCGCTGATCAGAGTGACGCA
GCACATCGACGCCGAGTGGAGGAGAGGCAGGCTGGAGGGGAGGGAGGGGCTGTACCCTGC
CGCCTTCACACAGCCCTGGGACGCTCAGCCAATCCCAGGCCAGCAGCCGGCGGTTAAAGG
CGTGGCCAAGGCTCTGTTTGATTTCACAGCAGAGAGCGAAGACGAGCTGACGCTGAAGGT
GGGTGACACCGTAACGGAGGTGGAGCCAGTGGATGAGCAGTGGATTATGGGAGTCATTGG
CGGCAAGCGTGGAATTGTGCCCAAAAACTACATTTCACTTATTTAA
>Synodus_sp._gill_5|019082|scaffold24615|m.33784
ATGGCGGAGGCCAGAGCCGAGGACGAGGAGGAGAACGT---GAGGGAGCCGCGAGATGCC
GTG---------GTTCGAAGGCAGCCCCG---CCAGAACAGCACCCCGGCAGATCGAGCT
GACAGACGCAAACCAGAGCACCGTC---ACAGCCAGGGTCCTCTGTCCTCCATCCGGGCA
GCCATCAAGAGAACTTCCAACAGGTCCACATCTCTCAGCGAGGCCCCTCCCAGAGAGAGA
Gaccggga------------------gcgcgacaGGGAGCGAGACAGGAGGCGACCAGAG
ATCACCATCCTATCAGCAGAGCCTTTGGCATCCACTTCCTGGTTCCCTGGGGGTTCAGGG
GGATTTCCTCCACCCCCTCCCCCTCACGCTCAGATCTGGGGCCCCAGCATACCCCCCTCA
GTACAGCCTCCCCCCTCGTATGAGGAGGTGATCAGGGAGAAGTCTCAGGAGCAG------
----------------------------GACCTCCACCCTCCGGCACTCCCCTCCTCTTC
CTCTTCACCCACCTCCAGGTGTCTGGT---------TTCCACGACGACCATCGCCACACA
GACTGA----------CCAAGATCCTGTCCCAGAA------AGTTTCAATGTCAGAAGAC
CAGTAAAACCTCTGA--------GGCCGTCTTTGCCAAACGGTCCCAGATCGTCAAATTT
TGATGACATCAGCATCCTCCCCAGCCAGTCACGGCTCTC------------TGGTGGTGA
CGGTCT---TGCAGAGCCCAGAGTGCACACGCACT---------CGGTGCCTCGCTCACG
CTCCTGTGACTTCCTCTGTGACCCCTTCTCACTCCTGACCTCAAATTCCGATGCACAAAC
TGA-------------------CCAATGGCAGCACACCTCCAAAGCGATCGCTGTGGTAA
CACCCTGTAACCCC----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------
