>Amblygaster_clupeoides|037969|TR65016|c1_g1_i1|m.90625
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------GTTGGTATGGGGGGAGAAAGAGAGGG
GGAGGAGGAGGAG------GAGGAGGAGGACGAGGAGGACGAGGACA-------------
------------------------------------------------------------
-----------------------------AAGAGGATGTGATTGGACCAGTGGAACAACG
CTTGGCGTCTCTGGAGTTAGACTCGGAACCGGAACCCAGCACTCCATCTAGCA-------
--------CCTCGGCACTTACATCAAC------ATCAACTCCGGAAACGGAAACAGAAAC
GGAAACTGACTTGGAGCTTCCAAGAACACCAAACCAGGTAACACAACCAACTCCAACATC
AACACCAGCTCCAACTCCGTCCCTGCTGCTTCGGTCGACCACAGGGCTACAGGCTGCTTT
AGACTCCTCCAGCTCGGAGTCC---TCCATCTCCTACCCAGCC-----------------
------------------------------------------------------------
----------------------AGACGGATGCCCACCTCTGTTTCGACTCC---------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------AGT
TGTACCCTTCTCCCCATTCCCTTGTGTCAAAGCACCGCGGAAATCGGCGGCGGCCCGGAA
CTTGGGCCTCTACGGCCCGACGTCGCGTACACCCACCGTGCACTTCCCCCAGATGAGCAA
AGGCATGAGCCAGATGAGTAGCAGTAGTAGTAGTACTACCATCTCTACCAGGAGGCGATG
A
>Corydoras_julii_viscera_mixture_8|012559|scaffold21800|m.16937
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------AATGAAGAGGAACCACAGGAAGAGGGAGGAAA
TGAAGAGACTCAGGATCAGGAGAAGGAAGATGAGCCAGTTGAGGAGA-------------
-----------------------------------TTATCGAAAAACAAGACTCAGCTTG
CCACCCTCAGGAGGGATCATGTACTT---CTGAAGAGGAAGTACATGATCTGGAAGAACA
GTTGTCTGCTCTTGAGTTGGATCCATCCGTGTTA------TCGCCAACATCGAATGAGCC
AGAATCTCCctcaccATCAACATCGAATGAGCCAGAATCTCCCTCACCGCAGTTAGAAAT
AGAAAGTGATCCACAATCAC------------------------------------CTGT
GGCATGTGCCCCACCTATGCCCTCTTCTGC---------------CCTCCAATCCACCTC
TGACTCCTCCAGTTCAGAGAGCACTGGAGACCCTCTGAGGC-------------------
------------------------------------------------------------
-----------------------AAAGTTCCTCAATACCGGAAATGAACGGCAAAGCACA
GCA---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---CGTCTTCTCCCCTTTCCCCTGTGTCAAAGCCCCCCGCAAGTCCATAGCTGCCCGAAA
CCTGGGTCTCTATGGTCCCACTCCCAGAACTCCCATGGTGCACTTTCCACATATGAGCAA
AACCCTAACACGCGTGGGTGCT---------ACTTCAGCTTCGTCCACCAGGCGGCGATG
A
>Gasteropelecus_sp._gill_3|021572|scaffold33515|m.37223
TTTGAGATCTATTTAAGGCCCAA-----TTTACACCAC----------------------
------------------------------------------------------------
ATGTTCTCCTC-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------AGGACTGGCAG
TGGAAGCTGAGCCTGTT-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------ACTCCTCATAAGCCCAGTGATTC-----
-----------------------TGGTAAATGTCCAGCCACAAGCGTCCTGGCTTCCCAG
GTCCACACGT---CACCTGTAGTCAACCATCTCCTTCTGG---GAAGAAAGCCTAGAGCT
GCCCAGCGTCCCTCCAGGAACG---------------GTATCCTTCAGG---------CT
GGATCACCTCCCCAAGCTCAGTC-------------------------------------
--CACCCCAAACCAGGACCACGTAGCTCGAGCTAGACTTCAGTCTCCCTGGCGCACCCAT
GTGCGTGTCCATCGAAGAAACCTGGCCAGGGCACGGGCACAGCTGGGCTTCGATGACTCT
TTAACACTGGATGATGATGATGACGACAGCCCTGAGCACCAACCTGAGACAGGAGGAGTT
GAA----AGTACAACAGAGGAGCAGAAACAGCAGAATGGGGAGGACAGCAACTTGGAGAA
TGTAGATGgtgaggggcaGGACAATGGGGAGGAGCCTGCTGAAGGGG-------------
-----------------------------------TTACAGCAGAAGAATGCGTAGAACT
CCATTTGCAAGAAGCTGAGTGTGGAGAAAAAGTCGAGGAAATGCAGGAGATGGAACAACG
GTTGTCTGCTCTAGAGCTAGAACCATCAGCACAAGATTGTTCTCCAGCTGTCAGTGATGG
GGAATCAGGTTCCGATGTCCTACAGCCAGACTCTGTGGATTCAGCAGAGCAATCGGAGTC
CAAACCGACGCTGCAGTCGC----------------------------------AACTAG
AGCCCGAATCCGACCTGCAGTCGCAGCAGTTTTGCTCCTC-----TCGTCGCACCACCTC
TGACTCTTCCAGCTCAGAAAGTGGTGGCAGTTCTCTCAGAC-------------------
------------------------------------------------------------
-----------------------TGAGCACATCA------------------AAGCCACA
GCA---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---GATCTACTCCCCTTTCCCCTGTGTCAAAGCGCCTCGCAAGTCTGCCGCTGCCAGGAA
CTTGGGCCTTTATGGCCCCACATCAAGGACTCCC--------------------------
------------------------------------------------------------
-
>Lepidogalaxias_salamandroides_Head_2|010922|C553188|m.51681
ATGGA-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------CCACGCAGGGAAAACGGAGGCC
CTGGCGCCTGAGGAGGGCGAGAG-GACATTGGAGGAGGAAAGCTGTGGCAGGGAGGAGTC
TGGTCACAAAGATGAAGGTCAAGAAGAGGAGGAAGATAAGTCCGGTAAAGAGGAGGAGCA
CAAGGAGAAGCAGGAGCCCAAGGAGGCGGATGTTTGTGAAGAGGCCG-------------
-----------------------------------GCTGCACAGTCGAGCTCTCCCACCA
TGACTCTGGGGTGGGCT------------CAGACGAGGGGGTAGGCCAAGTCCAGCAGCA
GCTGGCAACCCTGGAGTTGGGGCCTGAATCAGCCTCGCCCTCTACTA-------------
-----------------------------------------CCGTGGACGACCAAAACGT
AGACCCAGAGCCCAATGTCC----------------------------------------
-----ATGCACTCTCTCCCCCTCTCCCAGCAAAG------------AGTCGGAGGGAGTC
TGACTCGTCGAGCTCGGAGAGC---GGGAGTTCTCTCCGGC-------------------
------------------------------------------------------------
-----------------------AGAAGCGCAGTTCTCCTTCGGTGGCCGGAGATCTGGG
GAAA--------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------AGCCT
GTCGCCGTTCTCGCCCTTCCCCAGTGTAAAGCCACTGCGTAAGTCTGCTGCAGCGCGGAA
CCTGGGCCTCTACGGCCCCACTGCACGAACTCCAACCGTCCAGTTCCCTCACATGAGCAG
AAGTGGAAACCCAGTGGGTGGC---------AGTTCCACCATCTCCACCAGGAGGCGATG
A
>Pantodon_buncholzi_mixed|005228|C638522|m.37134
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------AAGTACCAGAAACAGTGGAAAGAGCAGCGT
GGGGAGCACAGCCTGTCCTGCAGTAACATCGCAGAGCTGAGCCCCGGGGCGGTGGGAGCG
GGGCG-------------------------------------------------------
-----CGCTGAACACCAGGCAGCCATTAACAGCATGATGTTGGAGAGGATGAGCACCGAC
ATCAGCGCCCTTAAAAGGCAGTACAGTCGCATCAAGCGACGGCAGCAGCAGCAAGCCGGC
ATGGTCTACATTCGTGC-------------------------------------------
-----------------------AGATAAATGCCCATCCACGAGCCTGCTGGCTTCTCAG
TTACACACAT---CCCCTGTGGTAAACCATCTGCTGCTGG---GAAAGAAGCTGAAGGCT
GAGCGGAG---CTCTAATAATG---------------GCTCGGTCCCA------------
------CTGCCCCAGGCCCACTC-------------------------------------
--CACCCCGGTGCGTGACGAAAGCTCCCGGGCGAGGCTGAACTCACCGTGGCGCGTGCAT
GTCCGGAACCACCGCAGAAACCTGGCACGGGCTCGCGCCCAACTGGGGTACACAGACACT
GAGGAGCTTGTGCAGGAGGTGG-----GGCAATGGGAGCAAACT-----CAGCAAGAGCT
---------------GGAGGAAGAAATAACGCAGGTTGAGAAGGATGACGACGAACAAGT
CGAGGAGGCTGAG------AAGGATGACGACGAACAAGTCAAAGAAGCCAAGGAGCATGT
GGAAGTCACAAGGGATGAGGCAGTGAATGAGGAGGAGCATGAGGTAGTGCTGGAGGATGA
AGCTGCGCCTCTTGCGC------------CAGCACAGGATGTTATTCAGGTTGAGCAGCA
GCTGGCTTCACTGGAGCTCGAGCCAGACTCAGAA--------------------------
-------------------------------------GAAGCCGGTCTAAACCCAACGCC
TGACCCAGATCCCCAACTTC----------------------------------------
-----CTGTCCTGCCTCCTCCCCCTCTATGCCTG---------------CGCAAACAGTC
CGACTCGTCCAGCTCAGATGGC---TCCTCCTCTATCCGCC-------------------
------------------------------------------------------------
-----------------------ATAGCCCCTCTGCCCCAGCCCTTGCCCCCAAAGCCCG
GCA---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---GTCCTTCTCTCCTTTTCCCAGCGTCAAACCACTCCGCAAGTCGGCCACCGCC-----
------------------------------------------------------------
------------------------------------------------------------
-
>Sargocentron_rubrum_gill_6|009791|scaffold16436|m.19362
ATCGAGTACTGTCAGACAGCCGATGAGTTTTACAGCACGATGGGCTGTCTGACTCAGGAG
ATGCTGGAGCACAGCCTCATCGATCCTACTGAACTCATGCAGGAGGTTTACTCCATGGCT
GTGTTTCCCTTCCCTCAGCTGGCTGAGCTGAGAGAGAAATACACCTACAACATCACTCCC
TTCCCTACTTCTGTCAAATCCAATGGAAGTGGAGGTCTGGGCAGCTGGGAGAGTGATGAT
GATGATGCTGACATGGATGATGAAGATTCGGTGGTGACGGCTCTTGGTTGTCTGGGTCCC
TTGGGTGGCCTACTGGCCCCCGAGTTGCAGAGATACCAGAAACATCTCAAAGACCAGCGT
GGAGAGCAGGGC------------AACATAGCAGAGCTGAGCCCCGGGGCAGTGGGGGCT
GGAGGagcaggaggaggaggaggaggagggggaggagcaggAGGAGGAGGAGTAGGGGGA
GGCAAAGCAGAACATCAAGCAGCCATCAATAGCATGATGATGGAGCGGATGAGCACCGAC
ATCAACGCCCTGAAGAAGCAATACGCACGCATCAAGAGGCGGCAGCAGCAACAGGCTATG
CAACTCTACATACGCACAGGACCCGGACTCAGAGTGACCACAAGCCCAGGGATTTCTCAG
GAGCCTCCCAACAAACCCAAAGATGATAAATGCCCTGCCACCAATGTCCTGGCCTCCCAG
CTCAACCCCTCCACCCCAGTGGTCAACCACCTCCTTCTGGGTCGGAAGGCACGTGGAGGT
TCTCGAGG---CTCCAGACCTACATCCACCACCACATCCATGCTCCCAGGGGCCCGTCCT
GCTCCTCCGCCACAAACCCAGGCCTCACCAGCCAGGCAGCGCTGCGGCTCGCTGCCCTCC
AACAGCACTGGGCCTGCAGGAAGCTGTGGAGGAGGCGTGGCGTCGCCCTGGCGCGCTCAT
GTCCGGGTTCACCGTAGGAATATAGCCATGGCCCGAGCACAGCTAGGCTTTGGGGATTCG
GAGGTGAAGGAAGAGGAAGAGG---AGGAAGCAGGAGGAGGATCAGAGGGAAGAGAGGGT
GGA----GAAGACAGGGAGGGGAAGGAAGAGCAGGAGGAGACAGATGGAAAGGGAAAGGT
TAATGACGAGGAGGGCGAGGAGAAGAAAGAGGAGAGTGAGGAGGAGA-------------
--------------------------------------------GTGAACTCTCTACGTC
CCCTGCGGACATGAGAG------------AAGAAGCAGGAGTGGGAAACGTGGCAGAACG
ACTTGCCTCCCTGGATCTAGAGGCCGAATCAAACCCGTCTTCACCACCCAGCT-------
--------CTCCCCCTGTCACACCAT---------------CAGAGTGTTATCCTGAGTT
TAAAGCCGCACCCCAAGTCC----------------------------------------
-----CCATCCTCCCTCCTCCACCATCATCACA------------CCGACGCCACGAGTC
CGACTCTTCGAGTTCAGAAAGCAACACTGGCTCCCTCAGGCCTTCTTCTCACCACTCCCT
CACCTCCTGCATCCCTCCCTCCCCACCTTCCGCTCTGAGTCCGTCAACCTCTCCGGTCCC
TACATCGGCTCCCGTCGACCCACAATACTCGACCTCCCCCACTCTGTCCTCCAAATCCTG
CCTACCATCTTCCCCTTCCCTTCTACGCCTCTCCCCTCTCTCCGCTCCCACCTCCTCCAC
TTTTACCATGACTCCATCTCCCTCTACCCCCTCCCTCTCCTCTCTATCCTCATCGTCTAA
ATCTCAAATCCCCACTTCCCCGTCCACCCCGCAGCTCTCGTCCACTTCCACCCCTAAACA
GACCATCTTCTCTCCATTCCCTTGCGTCAAGCAGCCTAAGAAATCAGTAGCGGCCAGAAA
CCTGGGTCTCTACGGCCCCACATCCAGAACACCGATGGTACATTTCCCCCAGCTCAGCCG
CAACCTCAACCGC-----------------------------------------------
-
>Scleropages_formosus_red_gill|030207|scaffold46724|m.63500
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------GGTAAATGTCCGGTCAGCAGCCTCCTGGCCTCCCAG
GTCCACCCGT---CCCCTGTGGTCAACCACCTTCTTCTGG---GGAAGAGACTGAAAGGA
GCGAGGGG---TTCCAGGAATG---------------GCTTGATCCCA------------
GGCCCCCTCCCTCAGGCACAGTC-------------------------------------
--CAGTCCCAGCCGGGATGGTAGTCCTAGGGGCCGGATGAACTCGCCGTGGCGCGCCCAT
GTCCGGACGCACCGGCAGAACTTGGCACGCGCCCGCGCCCAGCTGGGCTTCAGGAATACA
GTCGAGTTG---------------------------------------------------
------------------------------------------------------------
-------------------GTGGATGACGATGAGCTGACCGAGGAAACGCAGGCAGAAAG
TACAGCGACGGAGCAGGACCCAGAGGACAAAG---TCACTACCCTGGAGCTGGTAGACAG
CGACCCCCAAATTGTAC------------CCGAGGAGGGGCTGGAGCAGGTGGAGCAGCA
ACTGGCCTCCCTGGATTTGCAGCACAGCTCTGAGCCACAGTCTCCAG-------------
-----------------------------------------CCACAGCGGAACCAACCCA
GGACCCTGAGCCTCCGGTCC----------------------------------------
-----CTACCCTGCCACCGCCACCACCACCCCAGCCCTC------ACGTCGCAAAGAGTC
GGACTCCTCCAGTTCAGAGAGC---GGCGGCTCCCTTCAAC-------------------
------------------------------------------------------------
-----------------------GAAGCCCCTCCAGCCTGACAGTACCTCCCAAGGGCCG
ACA---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
GACGGCCTTCTCCCCTTTCCCCAGCGTGAAGCCCCTCCGCAAATCTGCTGCTGCCAGGAA
CTTGGGACTGTATGGTCCAACGGAGCGAACCCCCACCGTTCACTTCCCGCAGATGAGCAA
AACTGTGAATCGCGTGGCTGGC---------AGTACTGTCAGCACCACTAGAAGGCGATG
A
