>Amblygaster_clupeoides|021266|TR37175|c0_g1_i1|m.58442
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------GAGCTGCAGAGGGTTGTGGAGAAGGGAGGCAAGTCATATACA
GTGAAGGGGGAGGCGGGGCTTAATGGTCTCAGCACAGAGAGTCGACGCTACGTAGAACTG
GCAGAGGAGGGTCACAGGATGTGTCTGTCTCTAGAAGCAGCTATTAGTGCAGAGGAGCAG
CGCAGCAGCAAAAACACTCCGTTCTTCCCCATCACCATTGGCAGGAA-------------
-ACCCACCAGCTCTAACCAGCCGGCTCCTGC-----------------------------
----------TGAAGTGGCCCAGGTGT------------GTGTGAGTCCGCCT---GAAC
CCCCCCACATCACACCGTCTATGATCTCTTATGGTGGATCTGACCTGACAGCAGTGAGTT
TGGGAAAGAGCG-CCGCCCTAAAGGCCAGCCTTGAGACACGCAGCACTGCAGGCAAAGTC
CTCAAGTCTGTGTTTGTACCCAACATTGGCTGGGCTTCA---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------
>Corydoras_julii_viscera_mixture_8|014314|scaffold24067|m.19666
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------TATATGGAGCTT
ACAGATGAGGGCCACAGGATGTGTCTGTCCTTAGAAGCAGCTATCAGTGCTGAGGAGCAG
CGCAGTGCTAAAGCCACTTCATTTTTTCCTATCACTATAGGCAGGAA-------------
-GCCAACTCACCCTGATTCTCCATTTCCTGCAAGCCAGCAGGTGTCGAACTGTGGCCCTG
CAGGTACACATGAGGTTGCTCAGGTGT------------GCTTAACCCCCCCT---CAGG
TGCCTCACATCACCCCTTCGATGATCTCCTACAGTGGATCTGATTTCACAGCAGCTAGTT
TGTCGNAAAG---------------------ATGGACGAGGTGTCAGCACAGGGAAGGTG
CTCAAGTCCATTTTTGTACCCAACATTGGCTGGGCTTCACAGCTAACAAGTGGAGAGGTA
TGGGTTCAGTTTAA----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------
>Distichodus_sexfasciatus_gill_4|009211|scaffold13329|m.14432
CACACAAGACCAGAGGCAGAACTTGAGCGATGCCACTCGGAGGAGGTTCTTTCGGGATCT
GGCCATATTTTCTCAACAGGGTCCGCTTACCGGGAAGCTCCACACGACTACTCTGAACAT
GGACGGCTGCCCTCTCCTCCAGTCAAACAGCCTGCAAACTCTGGGTCTTCCTTCACCACT
CCAGCACATCCTGTCAGATTACAGATGGTAGAATCAGAAACGCAGCCATGGTTTGGCACT
GATGGGTCTTTCAAGAGACCTGCAGATGTCAGCACCCACAGCAGCGGTGGGAATTTGCAT
TCTGGGCGGGAGGCAGCGAGAGCTCCACCTTCCTGCAGCGACAGACCAGCAGTGAGAGGA
ACCAGTGGCCTTCTCCCTCACCCGTACCACCTCTCCTCCTCTCAGAACCACCCAGGACCC
TACAGGGAGGATGGGCTTGGTGCTGGACATTTCCCAGCCCCTCAGGCCTGTTTAGATGTG
CAGTCTGCTCACATGTCTAAAAGCAAAACTATTGAGGGAAAAGAGAAGAGGATTCCGTTT
CCCCCTCTCTGTGCAGCCAGATTAAAGCCTATTAGACAGAAGACCAAAAATGCTGTGGTC
AGCATCCTTGACACAGGAGAAGTGTGCATGGAGCTCTTGAAGGGTCAGGGAAGTCAAGAG
AGGGTCAAAGAAGTGTTGAGGATATCCTGTGATGGCTCCATGGTGACGACGTACCAGCCT
AATGAAGGAAAAGGCTTCCCTGTGCTGGACCATCCGCCCTCTCCTCCAGAAGACATTTTT
ATATGCAGTTATGAGGatttgccAGAAAAATACTGGAAGAAATATCAGTATGCTACGAAG
TTTGTCCAGTTAGTGAAGTCAAAAACACCCAAAGTAACACTGTACACCAAGTTTGCTAAG
TGCATGCTGATGGAGAACTCTCCTAATGCAGATCTGGAATTGTGCTTCTATGATGGTGCC
AAAACTCATAAGACAAGCCATCAGGTCCGGGTGGTTGAGAAGAGCGGCAAGTCGTACACA
GTAAAGGGCGACGTAGGCCTGAGCGGTGTGAGTCCAGAGTGCAGACACTACATGGAGCTC
ACAGAAGAGGGACACAGAATGTGTCTGTCTTTAGAGGTTGCCATTAGTGCAGAGGAGCAA
CGCAGTGCTAGAACTACACCATATTTTCCCATCACTATTGGCAGGGGGGGGGGGCNNNNN
NGCCTGCTAACCCGAGCTCCTCGCTGCCAGGGGCTGAGCCTAGCTCTGAACGCAGTCCTG
CAGTCCCCGCTGAGGTAG------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------
>Melanotaenia_praecox_viscera_mixture_8|002023|C419862|m.27201
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------GAGAAATACTGGAAGAAGTATCAGTATGCCTCCAAG
TTTGTGCAGCTTGTGAAATCGAAGACTCCTAAAGTGACCCTTTACACCAAGTATGCTAAA
GTTATGCTGATGGAGAACTCTCCCAATGCAGACCTTGAAGTTTGTTTTTATGATGGAGCA
AAAACTCACAAGACATCAGAGCTGGTGCGCGTG---GAGAAGAGTGGGAAATCATATACT
GTGAAAGGGGAGGTGGGGCTGAGCGGCCTGAGCCCAGAGAGCAGGCTGTATGTGGAGCTA
TCAAATGAGGGCCATAACATGTGTTTGTCGCTGGAGGCTGCCATTGCGGCAGAGGAGCAG
CGCAGCACCAAGAAAGTTCCTTTCTTCCCCATAACTATTGGCAGGCG-------------
-ACCTGCCACTTCAGACTCCCCTTCCTTATCGTCCACGCCCTC-----------------
----------ACAGCAGGTACCTCCTG------------ATGCAGCTTCTCCT-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------
>Pantodon_buncholzi_mixed|013148|scaffold16049|m.21382
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---ATCTTGGATACAGGTGAGGTGTGTGTGGAGCTCCTGAAGGGACAGGGAGCCCAGGAA
AGGGTTAGAGAAGTGCTGCGCATCTCGTGTGACGGCACCATGGTAACCATCTACCAGCCC
AGAGAAGGCAAAGAGCTGCCTGCACTGGACAGGCCTTCCACACCACCTCAGGATATATTC
ATCTGCAGCTATGAGGACCTGCCAGAGAAGTACTGGAAGAAGTACCAGTATGCCACCAAA
TTTGTCCAACTTGTTAAATCAAAGACACCCAAAGTCACACTTTACACCAAATATGCCAag
tgtatgctgatggagaattcccccagtgctGACCTGGAAGTGTGTTTCTATGATGGAGCC
AAGCTGCACAGATCAGCAGAGGTGGTGCGTGTGGTGGAGAGGACAGGAAAGGCATACACC
GTCAAGGGGGAGGTGGGACGCAGTGGTCTCAGCCCAGAGAGCAAAGCCTACATGGAGCAG
GCGGAGCAGGGCCACCGCATGTGTGTGGCAGTGGAGGCTGCAGTCACTGTAGAGGAACAG
CAAAGCGCTCAGGCCACACCCTTCTTCCCCATCACTGTTGGAAGGCG-------------
-TCCTACCAACCCAGCCTGTGTCAGCGCTGCATCTCTCCCTGC---------------TG
CAGCTCCAC------------------------------TGGAGAGTCCAGTA---AACC
CACCCAACATCACCCCATCGATGATCTCCTATGATGGCTCAGACGTCACCTCTTCTAGCC
TGGCTAAGGGTCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNGTC
CTCAAGTCTGTGTTTGTGCCCAACATTGGCTGGGCTTCGCAGCTGACGAGTGGTGA----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------
>Sargocentron_rubrum_gill_6|003738|C705825|m.47308
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------AAAGAAGTCCTTCGGATATCCTGTGATGGTTCAATGGTGACGATATACCAACCA
AATGATGGGAAGGGTTTTCCCGTGCTGGATTGCCCCCCTGCCCCTCCTGAAGATATTCTC
ATTTGTAGCTACGAGGACCTTCCAGAGAAATATTGGAAGAAGTACCAGTATGCCTCCAAG
TTTGTGCAGCTTGTAAAATCCAAGACTCCCAAAGTGACCCTTTACACCAAGTATGCCAAG
TGCATGCTGATGGAGAACTCCCCAAACGCAGACCTGGAGGTTTGCTTTTATGATGGAGCA
AAGACCCACAAGACGTCAGAGCTGGTGCGAGTGGTCGAGAAGAGCGGGAAGTCGTACACA
GTGAAGGGCGAGGTGGGGCTGAGCGGCCTGAGCCCAGAGAGCCGCTTGTATGTGGAACTG
TCAGACGAAGGTCACAGCATCTGTCTGTCTCTAGAGGCCGCCATCACCGCAGAGGAGCAG
CGCAGCACCAAGAACACTCCTTTCTTCCCAATAACTATCGGCAGGAG-------------
-ACCTGCCAACCCAGAATCCCCTTGCTCATCATCGCTGCCATC-----------------
----------CCAACCGATGCCAGCCG------------ATGTGGCTTCACCTCCCCAAC
ATCCACAGATCACTCCGTCGATGATCTCCTATGATGGATCAGATTTCACGTCAGCCAGCC
TGAACAAGAAAA----GCTCCCCGGCACGACAGGACCTGGCCCACAGCACGGGGAAAGTG
GTTAAGTCGATATTCGTGCCCAACATTGGATGGGCATCCCAGCTGACCAGTGGGGAAGTT
TGGGTGCAGTTTAACGACGGGTCTCAGCTGGTGGTGCAGGCAGGAGTTTCATGCATCACA
TACACGTCGCCAGAGGGCCGGATCACCAGGTACAAGGAGAATGAGAAGTTGCCGGAGCTC
GTGAAGGAAAAGCTTCACTGCCTCTCCACCATCCTGGGACTGCTGGCCAACCCAGCAGCA
CATCGCCTGCAACAGCCTCACTAA
>Scleropages_formosus_red_gill|001048|C1206350|m.68384
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------CTTGTGCGAATTGTCGAGAAGACAGGGAAGTCATTCACA
GTGAAGGGTGAGGTGGGGCTGTCTGGCTTAAGTCCTGAGACCAAGGCCTACATGGAACAA
TTCAGCGAGGGACACCACATGTGCCTGGCTTTGGAGGCAGCAGTCTCTGCTGAGGAGCAG
CGCAGTTCAAGGACTACACCCTTCTTTCCCATCACCATTGGCAGGAG-------------
-GCCCACCAATGCTGGCTTCCCAAACCCCACCTCTCAGAGCAT-----------------
----------ACAAGCTGGCAGGTCGTCTCATGTTCCAGCTGAAGGTCCAACC---AAGA
TGACCCCCATCAGCCCTTCGATGATCTCATGCGATAGTTCAGACTTCACCTCTGGC----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------
>Synodus_sp._gill_5|025496|scaffold8853|m.9931
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------GAAGATCTTCCAGAGAAATACTGGAAGAAGTATCAGTATGCGTGCAAG
TTTGTCCAGCTTGTGAAGTCCAAGACTCCCAAAGTGACCCTTTACACCAAGTTCGCCAAG
TGCATGCTGATGGAGAACTCTCCCCAGGCGGACCTGGAGGTCTGCTTCTATGACGGGGCG
AAGATCCACAAGACGTCGGAGCTGGTGCGGGTGGTGGAGCGCGGTGGGAAGGCGTACACG
GTGAAGGGCGAGGCCGGGCTGGGCAGCCTGGGGCCGGACAGCCGGCGCTACGTGGAGCTG
GCAGAGCAGAGCCACAGcATGTGCCTGGCCCTGGAGGCCGCCGTCAGCGCAGAGGAGACG
CACAGCGCCAACGGGACGCCCTTCTTCCCCATCGCCATCGGCAGGAG-------------
-ACCTGTGAACCCAGATACGCCGTAC----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------
