>Amblygaster_clupeoides|037175|TR64237|c0_g1_i1|m.88701
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--GGGCCAGAAAACACG---------------GAAGACTCAAAGTCAAGTGCA-------
------------------------------------------------------------
---------------AGTCAGGAAGTCCCTTCAGTGG-------TGAATAATGTGCAGAT
ATGCTCAAAATCAAGTAGG----GGCTCTCCTGGACAATC--------------------
------------------------------------------------------------
--------------AGGAAATAATTACTG----CTGTGAAATATGCAAGAAAACATTTAA
ACACCCAAGCAACCTGGAGCTCCACAAGCGCTCACATACTGGTGAAAAACCATTCCAGTG
TAACTTATGTGGAAAACATTTTTCACAGT-------------------------------
------------------------------------------------------------
--------CAGGTAATTTGCAGACGCATCTACGCCGACATTCAGGAGAAAAACCGTACAT
CTGTGAACTCTGTGGGAAAAGCTTTGCTGCCTCAGGGGATGTCCAGCGTCATATTGTCAT
CCACACAGGGGAAAGGCCTCATCTGTGTGATGTTTGCGGACGAGGTTTCGGTGACTTTAG
TAACTTGAAAGAACATAAAAAA--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>Corydoras_julii_viscera_mixture_8|009428|scaffold16734|m.12052
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------ATGGACATGCTGATGCTGCTGNNNNNNNNNNN---------
------------------------------------NNNNNNGAAATCCGACGCCT-C--
------------------------------------------------------------
------------------------------------------------------------
-----------------------CCTGTTAGACGTGAAGCTGGAGGTCACTGCACTACAA
CACGAAGACGAACCACAGCAGCCGTCATGTGATGTATCCAGAACCTCCACTCCTCGTACC
GTGGGCCAGATGG--------------------AGGAGCCTACTGTAGGTAAACCAGAGC
AAAACAGTAATAAAGGAGCAGCTGATAATGTACACACCAATCAAATCATGATCTT---AA
AACTGGAGC-------GTTGTGATGTGACCCCA---------------------------
------------------------CCCGACGTGCCCACTCAGGACGGNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNATGAGCGTTCA-------------
---------------TTCAAAAACTGCTGACGCTTGTGAAGTTTGTCATGAAACTTT---
-------GGCTTCCTGTAGGTGCAAAA---------------------------------
-------CGAGGAGAGCAGGTGTCGCAGG-------------------------------
------------------------------------------------------------
---------AGAGA------------------------------GGGTCAAACCATTCCT
CTGCAAATTATGTGGGAAATCCTTCTCCACTTCCAGCGTTCTCAAAAAGCATATTCAAAT
TCACACGGGTGAAAGACCATTTCTTTGCAGGTTTTGTGGGCGAGCCTTTGGTCAGAAAAT
TCACTGTAAAGAACACGAGAGGATC-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>Distichodus_sexfasciatus_gill_4|005762|C907959|m.53478
GTTTTGGGCAACGCTTTGCTCCCCGAGCCTGACCTCCATTGCCCCTCTGTTGATGCTGGT
TCTGTACAAAGCAAACGGCCACAGCCACCACCGTCCC------CCTCAGACACAGCCAAT
AGTGTTCCAGCTCCGTCAGAGAGGCAGCCTCTGCATGGTTACAAGTTGAGGAGCTTTTAC
AGCAAACAGTATTTCAAACAGAGTGCTGCCCAAAACGCCAGTTCCAACCTGAGCCAGGCA
CAGTCGAGCCCTCTAGTGGTGGAGGAGCCATAT---------------------------
----------------------TGCAA---------------------------------
--------------------------------------------------CACTGGCACA
ACCAATCAGACACTACAAAACAGACAAGTAAACACAGCCAGCCAGTCACTG---------
TGCTCTGCACTAACCAACCAGATGTTGCTGCCAACGGCCTCAAATGTTGGAAGCCTCCCG
CTGTCTCAC--CAAGCTGAGTGTGTGTTGCCGCAGACATCTGCAAGTTGTGCCAGTGCTA
CCGTATCCACTTCTTCCTCGTACTCTTGTCAGGATGTGCTAAACCCGCCTCCATTGGCCC
CTCCTGCTGATGCCATGATCTTGCCCCCTACAGATGGAGAAAAGAGTCCACCAGCTGCAA
GGGCACCACGCCATAAGAAAGCTGTGTACCTGAAAAAGTTTAATTACCTTCGCTCACACC
ATAATCTAGAAGA---------------------AGGTCTGGAACCGCATGCAGCGACGG
AGAGTTGTGATGCAAAAAGAATGCA----------ACGACCAGAACCAGAGTTGC---AG
AACCGGCCCAGAACCAGTGCAGACGTGCCTCAAGAAGGTGGGGTCTCAGAAGCTGCAGAA
GCAAATGAGCCCAAGACGGCTCAGCCTCTGCCGCCCAGCCCCTCCCC-------------
--------------ACCAGTGCCAGAACCTTCCCAGCCTAAAGGTCAAAAAGAGGGGACA
GGGGGCAGTAACTCAGCTAATAAGTACTG----CTGTGAAGTGTGTGGCAAGACGTTCAA
GCACCCCAGCAACCTGGAGCTGCACAAGCGCTCACATACAGGTGAGAGGCCATTCCAGTG
TAACATCTGTGGGAAAAGCTTCTCGCAGG-------------------------------
------------------------------------------------------------
--------CAGGAAACCTGCAGACGCATTTACGCCGACATTCTGGAGAGAAGCCCTACAT
CTGTGAACTCTGTGGAAAAAGTTTTGCTGCTTCTGGTGATGTCCAGCGTCATATAATAAT
CCACTCAGGAGCTCGACCTCATCTGTGTGACATCTGTGGACGAGGCTTTAGTAATTTCAG
CAATCTTATGGAGCACAAGAAGACTCACAGTTCAGAGAAGGAGTTCATCTGTGAACAGTG
CGGCAAGTCCTTCAACATGCAGAGAAAACTGTTAAAACACACCATGAGACACACTGGAGA
GAAGCCATACGGCTGCCAGACCTGTGGAAAGTGTTTTGCCGGATCAGGCGACCTCCAACG
GCATGTGCGGTCGCATACAGGCGAGCGCCCATACACATGCGACATGTGTGGCAAAGGTTT
CACGCGGACAGCAGTTCTGCGCCGACACCGAAACTCCCACTGCAAACCTG-TGCCGGCCG
CAGACGCACCC--------------------------------------------AAACA
CATAACAGACATTAAAGCGCCTGCTCAGACGCACACCACAGACGC---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------ACAAACCCTCGCTG------------------------AG
GCGCCAGTCAAAGTGGACGCTCCACAG---------------------------------
------------------------TCTGCA-------------------------
>Gasteropelecus_sp._gill_3|008459|scaffold14294|m.13294
A-----------------------------------------------------------
-------------AACGGCTACAGCCTGCACCACCGCCTGGCACTGTAGAAACAGCCAGT
AGCATGGTGACACTACCTGAAAGGCAACCTCTACAAGGCTACAAGCTGAGGGATTTTTAC
AGTAAGCAGTATTTCAAACAGAGCGCTGTGCAGAACTGCAGTCCCACCATGAGTCAGGTG
CACT---GCCCTCTAGGGGTGGAGGAGCAGTACAACGCCAgtcAGCCCCTTCAGAGCATC
ACCACAAATGTAGCCAATCAAATGCAACAGAGTACGCCTACAAATGGAGCCAATCAGATA
CAGCAGAATACGCCCATGAATGTAAGCAATCAGACACTGCAGAATGTGTCCACGAATGTA
GCCAATCAGATGCTCCAGAATATGCCAACAAGTGTAGCCAACCAATCACTGTCGACATTA
TCCTCTTCAGCAGCCAATCAGATGCT--------TTCATTCGGACACTCGAACCC---CA
CTAGCTCAGCTCCAGTGGATCCTTTGATGCCTCAGATGCCAACATCCTGTGCCAATGCC-
--------------------TCTTCCTGCCCTGAGGTCCCAAACCCAATGCCTTTGGCTC
CGTCCAACCTTGTCACCCAATTGCTCCCTACAGATGGGAGAAAAAGCCCCCCTGCTCCAC
GTACACTTCGACCCAAAAAGACTGTGTATTTGAAGAAGTTTAATTACCTTCGCTCTCACC
TCGCTCTGGAGGA---------------------GGAGGCTGAGCCGAGCAGGGTGATTG
ACAGCTGCATTGCAGAGACAGTCCA----------GCAGTCTGGGACACAGATCC-----
-AGCCAGCCAaTGTTTGCTCAGATGTGCCCTTTGTGGGTGGGGTTCCTGAGCCAGAGGAA
CCACCCGAGCCCAGTTTGG---TCCCCCAGCCACCCAGTCCACCCTC-------------
--------------ACCTCGGCCAGAACCCTCACAGATTAAAGACCAGATAGAAGGGGGT
GGAGACACTAA---CAGTAACAAATATTG----CTGTGAAGTCTGTGGGAAAACCTTCAA
ACACCCCAGCAACCTGGAGCTGNNNNN------------NNNNNNNNNNNNNNNNNNNNN
NAACGTATGTGGGAAAAACTTTTCTCAGG-------------------------------
------------------------------------------------------------
--------CAGGAAACCTACAGACGCATTTACGTCGCCATTCTGGGGAGAAGCCCTACAT
CTGTGAGCTCTGTGGGAAAAGTTTTGCTGCATCTGGggatgttcagcgccacatcattat
ccACTCTGGAGCTCGGCCTCACCTCTGTGACATTTGTGGACGAGGCTTCAGTAATTTCAG
TAACCTGAAAGAGCACAAGAAGACCCACAGTTCCGATAAAGAGTACATCTGTGAGCAGTG
CGGCAAATCCTTCAACATGCAGAGAAAACTACTTAAACACATGATGAGACACACGGGAGA
GAAACCATACTGCTGCCAGACCTGCGGGAAGTGTTTTGCTGGGTCAGGTGACCTCCAGAG
GCATGTGCGCTCACACACAGGTGAGCGGCCCTATGTGTGTGACACGTGTGGAAAGGGGTT
CACTCGCACAGCAGTGCTGCGGCGACACCGAGCC---CACTGTAAGCCCGCTGACAGTTC
GGACGCTAACATGCGAGCACCAGGAGATGCCAGAGAGGACGACACACTCCTGGAGCCACA
CACCACGGATGCTAACACACTAGCACAGCCACGAAACATGGAGGCCAACAAAGCTACAAC
GACACCGACAGCAAACACTGCACCTCCATCCAGTGGCAATAAGGCTCAGCCACGCCCCCT
GCCTGTTTCAACACCACCCCCTGCAGAAATGTGCCGGCCCACCCTGCCCCACACTGACCC
CT--------------------CCTCCTCTGCCACTTCCTTCCCATCTCACTCCTCCTCC
TCTTCCTCCTCCTCtctCTCAGAGCTGCGCTCTGTTGTTCCACATCATCTCCTAGCCCCA
CCTACTCTCAACAAGCCCCTCCCTTCACACCAGAAAGCCCCTCCTCCTCACTTGAAACCT
AACCTCCTTCCTGATCCC------------------------------------------
-------------------------------------GGCTCTGCTCTGCGGCCCCATCT
GCTGGGCCCTGAGACACATTGCGGCCCCCCGCTGCCTGGCCGCAGCGGTGGAACAGGTAG
CGGTCAGACACACAGCGCCCCCTACAGGAGCTCTGAGGG---CTTCTGCTCCAGTGGTGC
TCTGTGGGGCCTGGCCATGAAGACTCTGCAGAGTGATAGTGACATGGACCAATGA
>Lepidogalaxias_salamandroides_Head_2|011112|C554354|m.52029
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------CCCGACGAGGAGCGGAGCAATAC---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------TC
CCAATTCAC---------------------------------------------------
------------------------------------------------------------
------------------------------------AGGGAAAGGGCTCCCCCCCAAACA
GACAGCTGCGCCCCAAAAAGGCCGTCTACCTGAAGAAGTATGACTATTTGCGTTTGCACA
CGGCCCTGGAAGACATGTTTTTTGAG------------------CGAAGTGAACCGGCCC
ATGGCTGCTCAAAAGA-------------------GCCCCACGGTGAGAAGGACCCCGAG
AAGCTGA------------GAGAGGCACCGCTGGACTGCTTGGCTGCAGCCGGAGACGTT
GGCTCTGAGACGGTGCCGG---CGTCTCGCTCGCCCAGCCCCCCGTCTGACAACAGAGAG
GAACCAGAGGGAAAATCAGATGGCCATCACCCAGAACCAAGTGGGCA-------------
-----------------GAAGCAGTACTG----CTGTGAGATGTGTGGGAAAACCTTCAA
GCACCCAAGCAACCTGGAACTCCACAAGCGCTCCCACACCGGTGAGAAACCCTTCCAATG
CAATGTCTGTGGGAAAAACTTTTCTCAGGTGAGGGTGCTGGGGCTTCTCCTGCTGTTCTC
ATGGCAGACGTCTCAGGTACAGGTAGCGGGAATGCAAACGACTGTTTCTGCTCATGTTCC
ACTTCAGGCAGGTAATCTACAGACACACTTACGACGACATTCAGGAGAGAAGCCATACAT
CTGTGAACTCTGTGGCAAAAGCTTCGCGGCCTCTGGGGACGTCCAGCGACACATTGTCAT
TCACACAGGAGAGAGGCCTCACCTGTGTGACATCTGTGGGCGTGGGTTCAGCAACTTCAG
CAATCTGAAAGAGCATAAGAAGACACACACAACAGACAAAGAGTTCACCTGTGACCAGTG
TGGGAAATCCTTCAACATGCATCGGAAGCTGTTAAAGCACAAGATCCGGCACACTGGGGA
GAGGCCATACACCTGCCAAACCTGTGGTAAAAGCTTTGCTGGGTCAGGTGACCTGCGTCG
TCACGTCCGCACGCACACAGGAGAGCGGCCGTACAACTGCGACACGTGCGGCAAGTGCTT
CACGCGCTCCGCAGTCCTGCGCAGACACTGCACCATGCACTGCAAAACCGCAGCCGCCAG
CAAAGGCAGC-----------------------------------------------ACG
GAGAGCTGCGATCAACCTGCCGG----------TGACGAAGGAGCC--------------
------------------------CCCTTCCTCGGGTCTGGAGACCAAGCAGCCCCACAG
GC----------------CCCTAAAGAGCCAGAGCAGCCCTTTCCGCCAGCCACTCTCCC
AGGGCAAGGCAACCCACCGCACGCCTGCGTGGAGCCTGCTTCAGACGTCA--GCCTCAGC
CCGTCCTCCAGCTCATTCTCTGAGCATCACTC---------------------------C
GTCGGGCCCCACCAGCTCTCCTCCCAGAAGGAGAAGTGTCCCCCGCCT----------CC
GGGCTCCCTCAAGATCCCCAAAGCTCCAGTGCCTCAGGAGGCCATGGCCATGTGCTCTTT
CGCTCCGGAGACTGGCCCCGCTGGTGTGGAGGCTTCTGCCCCAGCCACGCGCCTCTCTCT
CCTTGCTACCGACAGCCACTGTGCCCACCCTATG------------------------GC
CAACCGGTATAACAGCGCCCCCTACAGAGGGAGGGAAGGCCCCTTTTTCTCTAGTGTCAC
ACTGTGGGGGCTTGCTATGAAGACGCTGCAGAATGACAATGACATAGACCAATGA
>Melanotaenia_praecox_viscera_mixture_8|002321|C424340|m.27619
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------GTGGTGCAATGTGATGCTCC-----
--------------------AGAGGCTCCAGTAGAAGTCAGCACTGCAAGTAGAGAAGAG
ACTTCAGAGAC---ACCAG---ATGTCCATCTTCCCAGTCCTACTCCAGTTGACCATGAG
GAGCAAAATTTGAAGCCTGCTCCAGAGCCTCCACAGCAAACAGGACA-------------
-----------------CAAGCAGTACTG----TTGTGAGATTTGTGGAAAGATCTTCAA
ACATCCAAGCAACTTGGAGCTGCACAAGCGCTCACATACTGGTGAGAAGCCCTTTCAGTG
CAACATTTGTGGGAAACACTTCTCACAGG-------------------------------
------------------------------------------------------------
--------CCGGAAATTTACAGACACATTTGCGACGACATTCTGGGGAGAAACCATACAT
CTGTGAGTTATGTGGTAAAAGCTTTACTGCATCAGGGGATGTCCACCGTCACAAAGTGGT
TCACACAGGAGAGAAGCCACATCTGTGTGACATATGTGGCCGAGGATTTAACAACTTGAG
TAATCTCAAGGAGCACAAGAGAACTCATACAACA--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>Sargocentron_rubrum_gill_6|002863|C689133|m.45918
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------AAGCGCTCGCACACCGGTGAGAAGCCCTTTCAGTG
TAATGTTTGTGGGAGAAACTTTTCACAGG-------------------------------
------------------------------------------------------------
--------CTGGGAATTTACAGACACATTTGCGACGACATTCTGGAGAGAAACCATACAT
CTGTGAGCTATGTGGAAAAAGCTTTGCCGCAGCAGGAGATGTTCAGCGTCACATTGTGGT
CCACACAGGAGAGAGGCCGCATCTATGTGATATATGTGGTCGAGGGTTTAGCAACTTTAG
CAACCTCAAGGAGCACAAGAAGACTCACACCACAGACAAGATGTTCACCTGTGACCTGTG
TGGAAAATCCTTCAACATGCACAGAAAGCTACTGAAGCACAAGATCCGCCATGCTGGAGA
AAAACCGCACCGTTGTGACACTTGTGGGAAGTGTTTCATCGGCTCAGGGGACCTGCGGCG
CCACGTGCGTTCACATACTGGTGAGAGACCCTACATCTG---CATCTGTGGCAAGAGTTT
CACCCGCTCTGCCCTGCTGAGGAGACACACCAACATGAACTGCAAGGGGGCTCCAGACGA
CAGCCCCGTC-----------------------------------------------ACG
GACAGCTCTGAGCAGCCCGGAGGCTC-------AGACGGGACAGCC--------------
------------------------CCGTTCCCCAAACGGGTCAGCCACAGCAAAACTCCA
GC-------------AGGCTCCAGTGAGCAG-------CCTTTCCCCAGTATGATGTCCC
A-----------------------------------------------------------
-----------------------------------------------------------C
ACGGGGCTCGACAAGTCTTCACC---------------TCCTCCTCCC------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------CCACCA
>Synodus_sp._gill_5|016470|scaffold21818|m.28593
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------CCGAAGAAGGCCGTCTACTTGAAGAAGTATAACTACTTACGATCCCAGA
AGGCGTTGGAGGAGATGTGTGCTGAGACCATCAGTGACCCGATCCTCAGCGAACCCATCC
TCAGCTGTCCCAAAGAGAGTCGCCAAGAAGAGTCTTTGGTCCAGAGCGAAGCTCC-----
--------------------AGAAGGTTCTGCTGACTGTCCCTCCGAAGGCAGAGAGGAA
ACTCCTGAGGCAGCATTGG---ACACCCAGCCCCCCAGTCCCACACCCATGGATGAAGAC
AAGCAGGAGCCCAAGACGGCCTCAGAGCCAGCGCAGACAGCTGGCCA-------------
-----------------TAAAAtgtaCAG----CTGCGCTGTCTGCGGGAAGGAGTTCAA
GCACCCAAGCAACCTGGAGCTCCACAAGCGCTCGCACACCGGGGAGAAGCCTTTTCAGTG
CAACGTCTGCGGGAAAAACTTTTCTCAGG-------------------------------
------------------------------------------------------------
--------CAGGTAATTTGCAGACACATCTGCGGCGACACTCGGGGGAGAAACCGTACAT
CTGTGAGCTCTGCGGCAAAAGCTTCGCCGCCGCGGGGGACGTTCAGCGTCACATCGTGGT
CCACACCCGGGTCAGACCTCACCTGTGTGACATATGCGGGAGAGGATTTAGTAATTTCTG
CAATCTGAAGGAGCACAAGAAGACTCACTCTACAGAGAAGACATTCTCCTGTGACCAGTG
TGGCAAGTCCTTCAACATGCACAGGAAACTGCTTAAGCACAAGGGCAGACACAGTGGAGA
GAAACCCCACCGCTGTGACACCTGCGGGAGGTGTTTCATTGGCTCCGGGGACCTTCGCCG
TCACGTGCGCTCCCACACCGGGGAGAGACCCTACCTCTGCACCGCCTGCGGGAAGAGCTT
CACCCGCTCCTCCCTCCTGCGCAGGCACAGCAACCAGCACTGCAAGGGCCCCCTGGACTC
CAACCCGGCC-----------------------------------------------CCG
GACCCCTCCGACCAG-------------------AATGGGGCCGCC--------------
------------------------TCCTTCCCCAAACCCACGGATCCCACCCCGGCTCCC
AC----------------CACCGAGGAACCA-------CCCTTCCCCTCCGCCCTGCCCC
A-----------------------------------------------------------
-----------------------------------------------------------C
GCCGGGCTGGACAAACCCTCC---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
