>Amblygaster_clupeoides|037970|TR65016|c1_g2_i1|m.90627
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------GTTGGTATGGGGGGAGAAAGAGAGGGGGAG
GAGGAGGAG------GAGGAGGAGGACGAGGAGGACGAGGACA-----------------
------------------------------------------------------------
-------------AAGAGGATGTGATTGGACCAGTGGAACAACGCTTGGCGTCTCTGGAG
TTAGACTCGGAACCGGAACCCAGCACTCCATCTAGCACCTCGGCACTTACATCAACATCA
ACTCCGGAAACGGAAACAGAAACGGAAACTGACTTGGAGCTTCCAAGAACACCAAAC---
----------CAGGTAACACAACCAACTCCAACATCAACACCA-GCTCCAACTCCGTCCC
TGCTGCTTCGGTCGACCACA------GGG-------------CTACAGGCTGCTTTAGAC
TCCTCCAGCTCGGAGTCC---TCCATCTCCTACCCAGCCAGACGGATGCCCACCTCTGTT
TCGACTCCAGGGGGGCTGTCAAGGTACCAGCAGCCTCCAGT-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-TGTACCCTTCTCCCCATTCCCTTGTGTCAAAGCACCGCGGAAATCGGCGGCGGCCCGGA
ACTTGGGCCTCTACGGCCCGACGTCGCGTACACCCACCGTGCACTTCCCCCAGATGAGCA
AAGGCATGAGCCAGATGAGTAGCAGTAGTAGTAGTACTACCATCTCTACCAGGAGGCGAT
GA
>Corydoras_julii_viscera_mixture_8|012559|scaffold21800|m.16937
AATG--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------AAGAGGAACCACAGGAAGAGGGAGGAAATGAA
GAGACTCAGGATCAGGAGAAGGAAGATGAGCCAGTTGAGGAGATTATCGAAAAACAAGAC
TC---AGCTTGCCACCCTCAGGAGGGATCATGTACTT-----------------------
-------------CTGAAGAGGAAGTACATGATCTGGAAGAACAGTTGTCTGCTCTTGAG
TTGGATCCATCCGTGTTA------TCGCCA------------------------------
---------------ACATCGAATGAGCCAGAATCTCCctcaccATCAACATCGAATGAG
CC------AGAATCTCCCTCACCGCAGTTAGAAATAGAAAGTGATCCACAATCAC--CTG
TGGCATGTGCCCCACCTAT----------GCCCTCTTCTGCCCTCCAATCCACCTCTGAC
TCCTCCAGTTCAGAGAGCACTGGAGACCCTCTGA------------GGCAAAGTTCCTCA
ATACCGGAAATGAACGGCAAAGCACAGCA-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----CGTCTTCTCCCCTTTCCCCTGTGTCAAAGCCCCCCGCAAGTCCATAGCTGCCCGAA
ACCTGGGTCTCTATGGTCCCACTCCCAGAACTCCCATGGTGCACTTTCCACATATGAGCA
AAACCCTAACACGCGTGGGTGCT---------ACTTCAGCTTCGTCCACCAGGCGGCGAT
GA
>Gasteropelecus_sp._gill_3|021572|scaffold33515|m.37223
TTTGAGATCTATTTAAGGCCCAAT-----TTACACCACA---------------------
------------------------------------------------------------
-TGTTCTCCTC-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------AGGACTGGCAG
TGGAAGCTGAGCCTGTT-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------ACTCCTCATAAGCCCAGTGATTC-----
-----------------------TGGTAAATGTCCAGCCACAAGCGTCCTGGCTTCCCAG
GTCCACACGT---CACCTGTAGTCAACCATCTCCTTCTGG---GAAGAAAGCCTAGAGCT
GCCCAGCGTCCCTCCAGGAACG---------------GTATCCTTCAGGC---------T
GGATCACCTCCCCAAGCTCAGTC-------------------------------------
--CACCCCAAACCAGGACCACGTAGCTCGAGCTAGACTTCAGTCTCCCTGGCGCACCCAT
GTGCGTGTCCATCGAAGAAACCTGGCCAGGGCACGGGCACAGCTGGGCTTCGATGACTCT
TTAACACTGGATGATGATGATGACGACAGCCCTGAGCACCAACCTGAGACAGGAGGAGTT
GAAAGTACAACAGAGGAGCAGAAACAGCAGAATGGGGAGGACAGCAACTTGGAGAATGTA
GATGgtgaggggcaGGACAATGGGGAGGAGCCTGCTGAAGGGGTTACAGCAGAAGAATGC
GT---AGAACTCCATTTGCAAGAAGCTGAGTGTGGAGAAA--------------------
-------------AAGTCGAGGAAATGCAGGAGATGGAACAACGGTTGTCTGCTCTAGAG
CTAGAACCATCAGCACAAGATTGTTCTCCA------------------------------
---------------GCTGTCAGTGATGGGGAATCAGGTTCCGATGTCCTACAGCCAGAC
TC------TGTGGATTCAGCAGAGCAATCGGAGTCCAAACCGACGCTGCAGTCGCAACTA
GAGCCCGAATCCGACCTGCAGTCGCAGCAGTTTTGCTCCTCTCGTCGCACCACCTCTGAC
TCTTCCAGCTCAGAAAGTGGTGGCAGTTCTCTCA------------GACTGAGCACATC-
-----------------AAAGCCACAGCA-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----GATCTACTCCCCTTTCCCCTGTGTCAAAGCGCCTCGCAAGTCTGCCGCTGCCAGGA
ACTTGGGCCTTTATGGCCCCACATCAAGGACTCCC-------------------------
------------------------------------------------------------
--
>Lepidogalaxias_salamandroides_Head_2|010922|C553188|m.51681
AT----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------GGACCACGCAGGGAAAACGGAGGCC
CTGGCGCCTGAGGAGGGCGAGA-----GGACATTGGA-----------------------
-----------GGAGGAAAGCTGTGGCAGGGAGGAGTCTGGTCACAAAGATGAAGGTCAA
GAAGAGGAG------GAAGATAAGTCCGGTAAAGAGGAGGAGCACAAGGAGAAGCAGGAG
CCCAAGGAGGCGGATGTTTGTGAAGAGGCCGGCTGCACAGTCGAGCTCTCCCACCATGAC
TCTGGGGTGGGCTCAGACGAGGGGGTAGGCCAAGTCCAGCAGCAGCTGGCAACCCTGGAG
TTGGG-------------------------------------------------------
--------------------------GCCTGAATCAGCCTCGCCCTC-------------
-----------TACTACCGTGGACGACCAAAACGTAGACCCAGAGCCCAATGTCC--ATG
CACTCTCTCCCCCTCTCCC----------AGCAAAG------AGTCGGAGGGAGTCTGAC
TCGTCGAGCTCGGAGAGC---GGGAGTTCTCTCC------GGCAGAAGCGCAGTTCTCCT
TCGGTGGCCGGAGATCTGGGGAAAAGCCTG------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--TCGCCGTTCTCGCCCTTCCCCAGTGTAAAGCCACTGCGTAAGTCTGCTGCAGCGCGGA
ACCTGGGCCTCTACGGCCCCACTGCACGAACTCCAACCGTCCAGTTCCCTCACATGAGCA
GAAGTGGAAACCCAGTGGGTGGC---------AGTTCCACCATCTCCACCAGGAGGCGAT
GA
>Pantodon_buncholzi_mixed|005228|C638522|m.37134
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------AAGTACCAGAAACAGTGGAAAGAGCAGCGT
GGGGAGCACAGCCTGTCCTGCAGTAACATCGCAGAGCTGAGCCCCGGGGCGGTGGGAGCG
GGGCG-------------------------------------------------------
-----CGCTGAACACCAGGCAGCCATTAACAGCATGATGTTGGAGAGGATGAGCACCGAC
ATCAGCGCCCTTAAAAGGCAGTACAGTCGCATCAAGCGACGGCAGCAGCAGCAAGCCGGC
ATGGTCTACATTCGTGC-------------------------------------------
-----------------------AGATAAATGCCCATCCACGAGCCTGCTGGCTTCTCAG
TTACACACAT---CCCCTGTGGTAAACCATCTGCTGCTGG---GAAAGAAGCTGAAGGCT
GAGCGGAG---CTCTAATAATG---------------GCTCGGTCCCA------------
------CTGCCCCAGGCCCACTC-------------------------------------
--CACCCCGGTGCGTGACGAAAGCTCCCGGGCGAGGCTGAACTCACCGTGGCGCGTGCAT
GTCCGGAACCACCGCAGAAACCTGGCACGGGCTCGCGCCCAACTGGGGTACACAGACACT
GAGGAGCTTGTGCAGGAGGTGG-----GGCAATGGGAGCAAACT-----CAGCAAGAGCT
-----------GGAGGAAGAAATAACGCAGGTTGAGAAGGATGACGACGAACAAGTCGAG
GAGGCTGAG------AAGGATGACGACGAACAAGTCAAAGAAGCCAAGGAGCATGTGGAA
GTCACAAGGGATGAGGCAGTGAATGAGGAGGAGCATGAGGTAGTGCTGGAGGATGAAGCT
GCGCCTCTTGCGCCAGCACAGGATGTTATTCAGGTTGAGCAGCAGCTGGCTTCACTGGAG
CTCGA-------------------------------------------------------
--------------------------GCCAGACTCAGAA---------------------
------------GAAGCCGGTCTAAACCCAACGCCTGACCCAGATCCCCAACTTC--CTG
TCCTGCCTCCTCCCCCTCT----------ATGCCTG---------CGCAAACAGTCCGAC
TCGTCCAGCTCAGATGGC---TCCTCCTCTATCC------------GCCATAGCCCCTCT
GCCCCAGCCCTTGCCCCCAAAGCCCGGCA-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----GTCCTTCTCTCCTTTTCCCAGCGTCAAACCACTCCGCAAGTCGGCCACCGCC----
------------------------------------------------------------
------------------------------------------------------------
--
>Sargocentron_rubrum_gill_6|009791|scaffold16436|m.19362
ATCGAGTACTGTCAGACAGCCGATGAGTTTTACAGCACGATGGGCTGTCTGACTCAGGAG
ATGCTGGAGCACAGCCTCATCGATCCTACTGAACTCATGCAGGAGGTTTACTCCATGGCT
GTGTTTCCCTTCCCTCAGCTGGCTGAGCTGAGAGAGAAATACACCTACAACATCACTCCC
TTCCCTACTTCTGTCAAATCCAATGGAAGTGGAGGTCTGGGCAGCTGGGAGAGTGATGAT
GATGATGCTGACATGGATGATGAAGATTCGGTGGTGACGGCTCTTGGTTGTCTGGGTCCC
TTGGGTGGCCTACTGGCCCCCGAGTTGCAGAGATACCAGAAACATCTCAAAGACCAGCGT
GGAGAGCAGGGC------------AACATAGCAGAGCTGAGCCCCGGGGCAGTGGGGGCT
GGAGGagcaggaggaggaggaggaggagggggaggagcaggAGGAGGAGGAGTAGGGGGA
GGCAAAGCAGAACATCAAGCAGCCATCAATAGCATGATGATGGAGCGGATGAGCACCGAC
ATCAACGCCCTGAAGAAGCAATACGCACGCATCAAGAGGCGGCAGCAGCAACAGGCTATG
CAACTCTACATACGCACAGGACCCGGACTCAGAGTGACCACAAGCCCAGGGATTTCTCAG
GAGCCTCCCAACAAACCCAAAGATGATAAATGCCCTGCCACCAATGTCCTGGCCTCCCAG
CTCAACCCCTCCACCCCAGTGGTCAACCACCTCCTTCTGGGTCGGAAGGCACGTGGAGGT
TCTCGAGG---CTCCAGACCTACATCCACCACCACATCCATGCTCCCAGGGGCCCGTCCT
GCTCCTCCGCCACAAACCCAGGCCTCACCAGCCAGGCAGCGCTGCGGCTCGCTGCCCTCC
AACAGCACTGGGCCTGCAGGAAGCTGTGGAGGAGGCGTGGCGTCGCCCTGGCGCGCTCAT
GTCCGGGTTCACCGTAGGAATATAGCCATGGCCCGAGCACAGCTAGGCTTTGGGGATTCG
GAGGTGAAGGAAGAGGAAGAGGA---GGAAGCAGGAGGAGGATCAGAGGGAAGAGAGGGT
GGAGAAGACAGGGAGGGGAAGGAAGAGCAGGAGGAGACAGATGGAAAGGGAAAGGTTAAT
GACGAGGAGGGCGAGGAGAAGAAAGAGGAGAGTGAGGAGGAGAGT---------------
------------------------------------------GAACTCTCTACGTCCCCT
GCGGACATGAGAGAAGAAGCAGGAGTGGGAAACGTGGCAGAACGACTTGCCTCCCTGGAT
CTAGA-------------------------------------------------------
--------------------------GGCCGAATCAAACCCGTCTTCACCACCCAGCTCT
CCCCCTGTCACACCATCAGAGTGTTATCCTGAGTTTAAAGCCGCACCCCAAGTCC--CCA
TCCTCCCTCCTCCACCATC----------ATCACAC------CGACGCCACGAGTCCGAC
TCTTCGAGTTCAGAAAGCAACACTGGCTCCCTCA-----GGCCTTCTTCTCACCACTCCC
TCACCTCCTGCATCCCTCCCTCCCCACCTTCCGCTCTGAGTCCGTCAACCTCTCCGGTCC
CTACATCGGCTCCCGTCGACCCACAATACTCGACCTCCCCCACTCTGTCCTCCAAATCCT
GCCTACCATCTTCCCCTTCCCTTCTACGCCTCTCCCCTCTCTCCGCTCCCACCTCCTCCA
CTTTTACCATGACTCCATCTCCCTCTACCCCCTCCCTCTCCTCTCTATCCTCATCGTCTA
AATCTCAAATCCCCACTTCCCCGTCCACCCCGCAGCTCTCGTCCACTTCCACCCCTAAAC
AGACCATCTTCTCTCCATTCCCTTGCGTCAAGCAGCCTAAGAAATCAGTAGCGGCCAGAA
ACCTGGGTCTCTACGGCCCCACATCCAGAACACCGATGGTACATTTCCCCCAGCTCAGCC
GCAACCTCAACCGC----------------------------------------------
--
>Scleropages_formosus_red_gill|030207|scaffold46724|m.63500
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------GGTAAATGTCCGGTCAGCAGCCTCCTGGCCTCCCAG
GTCCACCCGT---CCCCTGTGGTCAACCACCTTCTTCTGG---GGAAGAGACTGAAAGGA
GCGAGGGG---TTCCAGGAATG---------------GCTTGATCCCAGG----------
--CCCCCTCCCTCAGGCACAGTC-------------------------------------
--CAGTCCCAGCCGGGATGGTAGTCCTAGGGGCCGGATGAACTCGCCGTGGCGCGCCCAT
GTCCGGACGCACCGGCAGAACTTGGCACGCGCCCGCGCCCAGCTGGGCTTCAGGAATACA
GTCGAGTTG---------------------------------------------------
------------------------------------------------------------
---------------GTGGATGACGATGAGCTGACCGAGGAAACGCAGGCAGAAAGTACA
GC---GACGGAGCAGGACCCAGAGGACAAAGTCACTACCCTGGAGCTGGTAGACAGCGAC
CCCCAAATTGTACCCGAGGAGGGGCTGGAGCAGGTGGAGCAGCAACTGGCCTCCCTGGAT
TTGCA-------------------------------------------------------
--------------------------GCACAGCTCTGAGCCACAGTC-------------
-----------TCCAGCCACAGCGGAACCAACCCAGGACCCTGAGCCTCCGGTCC--CTA
CCCTGCCACCGCCACCACC----------ACCCCAGCCCTCACGTCGCAAAGAGTCGGAC
TCCTCCAGTTCAGAGAGC---GGCGGCTCCCTTC------------AACGAAGCCCCTCC
AGCCTGACAGTACCTCCCAAGGGCCGACAG------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--ACGGCCTTCTCCCCTTTCCCCAGCGTGAAGCCCCTCCGCAAATCTGCTGCTGCCAGGA
ACTTGGGACTGTATGGTCCAACGGAGCGAACCCCCACCGTTCACTTCCCGCAGATGAGCA
AAACTGTGAATCGCGTGGCTGGC---------AGTACTGTCAGCACCACTAGAAGGCGAT
GA
