>Amblygaster_clupeoides|004035|TR12822|c4_g1_i1|m.26900
GAAAAG------------GAGCATCTCCAGGTCCAGGTTAGTGTCAAAAGTGAAGAAATC
ACTGGATTGAATTCAGAAATTCAAAGAATTGAACAAACTCTCCAGGAATCAGAAAAGGAA
TGGCTGTGTGTCCTTGATAGAGAGGCACAAGATAAGAATTTCCTCAAAGAGAAACTAGAG
ACTCTTGAAAATGAGCTTATGTCTAAAGATAGCAAAGTGCGTGGTTTACAACAAGACTTA
GATCATTTGAATAAAAAGCTGGCAGAGGCAACAGCTGCTTTAAATGTTAGTTCAGAGAGA
CTCCGAGAAAAAGAAAATGATGCATTGTCAAATAAAGGTAAGCTAGAAGAAATTTTGAAC
ACTGTACAAGCAAAAGACAAAGAAAATCAGGATTTGAGGGTAGCATTACAGGACATGGAG
GGAGAGTTACAAAAAATAGAGCATAGCAAGCAATCTGTAGATAAAAATCTGTCTGAAATT
ACACAAACTATGTCAGATAAATTGATTGCCTCTGAAGAGGAAAAATACACCTTGCAAAAC
AAAATTAAAGAATTGCACAAGAATCATCAATTTGAGGTAGCGTCCCTAAGAGAGGAATTA
CAAAGTCTCTCAGCACAGTTGCAGCAACAACAGCAGGATCTGTTAGAAACTAAGGAGGTT
TGCAAAAATGGGAATGAGGAATTCAGTCTGTTGCAGGAGAAAATGCAGAGTCTTCAGCAG
CAACTGCTTACAGAAAAAGAAAATCTGAAAGAGGCAGGTGTTAAACAGACTACTTTACTT
AATGAAATTCACTGTAAAGATGACAAGATAAATTGCATGAACATCCAGATAAGCCAACAA
AAGGAACTTATCACTGGGCTTAGCCAGCAGCTAAAAGAGAAAGATGCCTCTGTCACACAA
GTGGTTACTTCTGCCTCAAATGAGAGGATGAAATTCACTGAAGAAAAGAACAGTCTCCTT
TCCCAAATGGAAAACCTGGAGAAGGCTCACATTATCACAATCAAGGAGCTTGAAAATGTC
TCCAATACTTTAGAAGAAACCAAAACAAACATGTCCCTTTGTCAAACAGAATTTGAATCT
AAGGATGTACAGATAAAAGAATTGGTCCAACAGATGGGACAATTGAAAACAGAACTTCAA
AAAATGACAAAAGAAAAAGAAGCTATGAAGAAGAAGCTCCAGGCAGCTTTAGTTGTCCGA
AAAGAGCTTCTAAAGAAAATAGAAAATTATGAAAAGCAGAGGACAGAAGACACAAAGGTA
TTAGATTTGCAAAATAGAATTCAGGAACTAATTTTACAAATTCAGACTGCAGAAGCAGAG
CACAAAGCTCTTGTTGATGATTTACAACATGAGGTAGAGTCAAAAAAGACAGAGATCCTA
GAATTTGCTCAAGAGGTGTCGGGGAAAGATGAACTAATAAAACAACAGGGAGATTATATG
GAAAGTTTAAGGGAAAAGTTACTCGAAAAGGAGGTCAGTTTAACCACATCTCTTCAGACC
CTTGAAGAAAATGGAAAAGCTATTGACAGTCTCAAAACAAGCATCAGTGAAAAAGAACAG
GAAAACACTGAATTGCTGCTCAAAGTTGATCAATTAAGTCGAGTAATTGATGAAACAGAA
CAGCTCTTGAGAGATCAAGAGAGCTCCAAAGTCTCATCAGTAGATACAGAAAGTGAACTT
GTCAAGGTGACACAGGAGAAGGCAGTTCTGCAGAAGAAGGCACATGCTGCACTGTTGGCC
AGGAAAGAAACCATGAAGAAGGCTCAAGAGAGTGAGAAGAAGTACATGCAGGAGATTGCA
GAACTAAAAGATGACTTTAAAGCACTCCTTGAAAAGCACTGCCAACAAACAAATGAGCTT
AATGCTGTGCAGTTGAAGCATGATGATAACATTAAAGAATTAGAGGAAAGCAGGCAGGTT
GCAACCTCTTATCAGAGTCAGCTAGAGAAGTTAACTGAGCAGAGAGACAATGTGCTACAA
GATCTAAGGATTGCCATAGCTGAGAAAGAAAGCCAAGACAAAGCTTTGCAAACATATATT
GAAGAGATTAAACA-AGTTCAACTTCTCTTAGAGAAGGCTAATGCAGAAATTACAAGAAA
GGACATGGCATTGGTGACCCTTGAAAAGCATTCAACAGACCTTGCTGGAAAATTGGAGTC
TGCTCAGTTAGAATGCAAAAACTGTCTCAGAGAGATAAAAGAAATGACTGACCAGCTTGC
AAAACAGGGACAAGAGATTGAAAGTTTACAGAACCAGAACCTTCATGAAACACAGTTAAA
TCAAACTCATTTACTTGAGCTGAATGAAGAATTACGGCAAAAGGTGAAGGAATTGGAAGA
TCAAAAACAACAACTGTCTCAGGACTTGGAAAATATTGCTAGAAGACACTGTGAAGAAAA
CACTCAGGCTAAGTTGGAGCTTGAAACTGAACTGG---------TGAAGAAATCTGAGGA
ACTAGAATCTCTTCAGAATTCTTCAATACAGACACAGATAGAGCTTGAAAGAGTACATTC
ACAGTGGTTGGCATC-------TCAGA----AGGAGGTAGAGAGCTG-------------
----------------TAAACTCCTGATTGAAAGCCTACAGCAAGAGAAAGACACAGTCT
TTAAAGATTTGGAAAGCAATCAGAACCAAGTTGCTATATTTGAGTCTCAGCTTAAAGAAC
TGCAAAGACAAAATGATGACCTTTTACAGAAAAACATGACCATG-GAGACAAAGCAATCA
AACATTGACGTT---------GTCAAAGCATCAG---------------CTGATCCAATT
GATCTGAACCTTAA------------------TGAAGAGAATGCTGATC------TGCTT
GCCCTCCAAGCCATTGTCACTGAAAAAGATGAGCACATATCTGTCCTGGAACAGCAACTA
CAGAGGCAAATTCACCTCCATGAACTTGCAATGGATAAGATGAGAACTGAGGTGAATGAA
CTCCAGCAGAGGTCAAGAGACACCAAACAGGCAAATGAAAACAAACCAAATGAACAA---
---------CTGACAAAGAAATTGCAGGCTGCTTTGATCTCTCGCAAAGAATTACTAAAG
GAAAACCATGAATTGAAAGAAAAAAATCAAACATTGTCTTCAGAAAATGAGCAAAGTCGT
GCCGCATCTGCTGGCCTTGAACACACAGTCGTAGAACTAAGACGGCAGAAGACAGATCTG
GAAACCTCTTTATCCTCCCTTCGCAGTGACAGAGAGCAGTTAGCTGGTGAAGTAGAGCGA
ATGTCAAGTGAAAACCACAATCTCTCAGCAGCTTGTGACAGCCTTAAACTGACAATAGAG
AGCATCACACAACAGAAGGAAGCTTTTTCATGCCAGTTAGAGTCACTGAAAGATTCTCAG
ACAGTAGAACTGTCAGAGTGGAAATCAAAGCACACAGAACTAAAGCAAGAGTATGAATCT
CTTTTGCAAGCTTATGAAAATGTCAGTAGCGAAATGGATAAGATGAGGCAACTTTTGGAA
GGAGCGAGAAGAGAGAGACAGGAAGCTATTTTGAAAATCCATAAATTTGAGTCAGAGAGA
CAAAACCTTGAGAAACAAATGACTGAAATAGAGGAAGAGAATGAGAGAATAAAAGACAAG
ATGAGGAAGTTTGCAAAGGCCAAACAGCAACGAATGGAAGAACTTGAAGAGGAAAATGCC
AAAATCAGACAAGATCTCAATGAATATGACGAGAAACAAAAATCTGTTGTAGAGCAACTC
ACAGCAAAGAACCAGCATTTAGAAGCAGAAATTACTCTGCTTAAAGATTCTTCTCAGGAA
CTTAGGTCCCGATTTGATGAAATTCAACTTGAAAACCAAAATCTGGCCAAAGAACTTGAA
ACGGCAAGCTCTTCATTAGAAAAGTGGCATGAAGAATCACAGACTAGTGAGAGTAATTTG
CAACTCCAGCTCAATGAGGCATTGCATTTAAAAAAGTCTTTGACAGCGCAGATAGAATCA
CAGAAGGCTAAAATAGAGGCACAGCAAAACCTTGTTGAGGCAGCACAGGCAGAGAAAGTA
CATCTCTCTGAACAGATGCAACAGCTGCAGATGAATCATGAAGGTGAACTGAAAGAAAGG
GAGAAAGCTGTGAGTGAACTTAAGGAGGTTCTAAGTAAGAATGGTCAAGAAACCATTAGT
CTCAATGAGAAGGTTAGAATCTTAGAAGATGACAAGTGTTTGTTGCAAGAAGAGTTAGAA
AATGCCCAAGAGATATCAGACAAAGTAAAAAACGAGAATGAGTATTTGGAAACAGTGCTT
GTGAAAAACTCAGAGAGAATTGATGAGTTGACACAAATGGTGAGTGTGCTACAGTCACAG
AATTCCCATTTAACAACACAGCTGACCGAGAATAAAGACGAAAAGACCAAGGTATGCCAA
GAGAAGGAGGTACAGCATCTGAAACTTGTTAAAGAGTTTGAGGAAAAGCTGAAGACTGTC
CAGAGGGGTCGTGAGGGCTCCAAAAATATACAGAAAGAGCTCCAAGAACTTCTAAAAGAA
AAGCACCAAGAGATCAATCAGTTACAAAGTGATTGTATCAGATATCAAGAGTTGATTCTG
AATCTGGAACGATCGTTGAAGACTTCAGAGTCTGAACAACATCAAATGCAGAAAGACCTA
GAGGAAAACAGTAAGACTGTAACTGGAATGATGGAACAAAGGAAAAAGCTGGAGAATGAA
CTATCAAATCAACAGAAAGTCATTGAGGAGACGAAGAAACAGTTGGCAACATGTATTTCT
GAGAAAGATCAGTTACAGAATGAGTTGGAGCACAAGAATAAACTTTTGGAATTGCAAACA
AAGGAGAAAGAGGGTGAAATGGAAAAAATAATTACCCAACAAAAGTTTATTCATAAAGAT
AAGGAAATTGAACTTCAGAGAAGAATTGATGAGTTGTTGCACGACAAAGAAAAGGAGTCT
GAAGTGTCAGTGTTTTTGAAAAGGCATGTAGATCACAAAGATTTACAAATAAAACAACTG
ACAAGAGAATTTGAAACCTTATCTGCAAAGCTTGCTGTCCTTACAGACAAGCCAGAGAAT
GTTGAGCCACTGAAGCATTGGAATGATGTTTTCCAGAAAACATTACATGAAAAGGATGCT
CAGCTTCTTGATCAAGGCAGTGTTGTAGCTAGACTCCTTGAAGATATTCGGAGCAAAGGA
ACGACAATAAGTGAAATGCAAGTTACTATCAAGAGGCTTGAGAGGACGTTGAGCGATTAC
ACGGTAGCGGCTTCAGCACAACAGAGACAACTC---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Distichodus_sexfasciatus_gill_4|007194|C919453|m.56341
------------------------------------------------------------
--------------AAACAGTCAGCACAT-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------GCAGCCTCGTCACTTCTTGAAGAGCTGGAG------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------TCTCTTAAACAAAATCTCGAGAAGGCGA----
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------CT
GCTGAACTGGCTCGTAAAGACC--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----AATTGCTGATTCAGG--CAGAAAGCCGTTGTAA----TGACATTTCAGAAAAAG--
------------------------------------------------------------
---------------------------------------------------TACTACATG
TTGGATCTGAC-------------------------------------------------
---------------------CTTGACTGTGCTGTTAAAGAGATCAGTATGAAGAATGAG
GAAA------------------------------------------------TAGCAAGA
CAAACGG------------------------------------------------ATTGC
ATTCAAGTGGC---GGAGCAGCAACTTCAGCAGCT-------------------------
--GAAAGAAGCCATAGTCAAG---------------------------------------
------------------------------------------------------------
------ATGCAGGCTGAGCAT---------------------------------------
------------CAAAGTCAGTTGGATGAGCTCA--------------------------
-------------------------------------------------ATGGATCTATT
AGAGATCTTAAATCTACTTTGACTGCAGCTGAAAAAGAC---------AGTTACAAG---
------------------------------------------------------------
----------------------------------ATAAATGATCTGAAAAATGAGCTT--
------------------------------------------------------------
------------------------------------------------------------
-----------------------------GAAAAACTGGTG-----------GAGGATAG
AAATTCTCTCAAGGCGGAGCTGGAATCTGTGCTGGGAACCGTTTTTGAGAAGAATAATGA
ACTACTTGCCTTACAGAAAACATTAGCGATGACCCAGGAGCAGGTTTCACAGGAACATTC
CCAGTGGCAGGAATCAAGATGT----------GAAGTTGAACAACTG-------------
-----------------AAAGTACAAGTAGAAACGCTACAAGGAGAAAATGACGGATATA
TTACAGAGCTGAAGAAGTGCAAACATGACATGACAATTCTCGAGAACAATCTCAGTCAAC
TTGAAGCACAAAACAAGGAGTTGC------------------TG-AAGACTAAGACCCTA
GACACCACAGTTTCATTGCACCAAGAACCATTAGCACGGTCTTACCAACCTGAAATACCT
AAAGCAACCTGTGA---ACAACATTCTCTTTTTGAAGGGAGCAATAATAACAATCTTCCA
GAGCTTCAGACCTTACTCACAGAGAAGGAAGAGCTTATATCTGCCCTAGAACAACAGCTA
CAAAGACAAATTCACCTTCATCAGGTTGAAATGGAAAAGATTCGAATTGAAGTCGGTGAG
CTTCAGCAAAAACCAAAAACTGA------------------------AAAAGAACAG---
---------TTGACAAAAAAGCTTCAAGCAGCACTAATCTCTCGAAAAGAGCTGATGAAG
GAGAACCAGGGTGTAAAAGAACAAATGCAGAAGCTGTCATCACACAATGACCAGATGCAG
TCTGAGCTGGCATCTCTTAAGGGCATACTCTCTGAATTAAAACAACAGAAAATTGACCTG
GAAAGTCAGATTTCCACCTTGACTTCTGACAAGCAGAATCAATCTGCCGACTTTGATCGT
ATTCTAAGTGATAATCATAATCTGTCAGCAGCTTGTGAAAGCCTTAAGTTCACCATAGAG
AACATTACCCAACAGAAACAAGCTTTTTCATGCCAGCTCGAGTCTCTAAAAGACTCCCAG
ACAGTAGAGCTTTCAGAATGGAAATCTAAGCATGCTGATTTAAAGCAGGAGTATGAATCT
CTGCTGCAGGCTTACGAGAATGTCAGCAGTGAAATGGACAAGATGAGACAACTTCTTGAA
GCAACTAAGAGGGAAAGGCAGGAAGCTCTTCTGAAGGTCCAGAAATATGAATTTGAGAAG
GACAGTTTTGGAAAGCAAGCGGCAGAACTGGAGGAGGAAAATGACAAAATGAAAGAAAAA
ATGAGGAAGTTTGCTAAGTTAAAGCAACAGAAGATTGAGGAGCTCGAAGAGGAAAATGAG
AAGATCAGAAACGATTTGATGCTGTTCGATGACAAACACAAGAACACTGTTGATGAATTG
AGGCTGCGAAATAATGAGCTTGAAAGTGAAGTGAAATCTCTCCAACTATTGTCTGATGAG
CTCAGACAGAACTTGTGTGAAATTCGGCAAGATAACGATAACTTGGCCCAGGAGCAGAAA
GAAGCAAACTTGTCTCTTGAGGCTTGGCGCATGGAGTCAAAAACAGCTGAAAACAATTTG
CAGCTCAAGCTAAACGAAGCTCTTAGCTTGAACAGCACCTTCACAGCACAAATTGAAGCT
CAAAAGGCAGATATAGCTGCACAAGTTGACCTGGTTGAGTCCGTACAAAAGCAGAAAAAT
GATCTTTTTATGAAGTTGAAACAGGCAGAGGATCAATATGCCAATGAACTGAAGGAAAAG
GACAAAACAGTATCAGAACTTCAGCATGTGATTCAAGGAAACAAACAGGAAACCATAAGT
CTCAATGAGAAAGTGAAGATTTTGGAAGATGACAAATGTCTGCTGCAAGAGGAACTTGAG
AACATCCAAGAGATATCAGATAAAGTGAAAAATGAAAATGAGTATTTGGAGACAATGCTT
CTGAAAAACTCTGAAAGGATTGATGAATTGACCGAGGCTCTGAACGCATTGAAAACCCAA
AACATGCAGCTTTCCTTGCAACTTCAAGACGTTAAGGAGCAAAAGGCAAATGTTTGCAAA
GAAAAAGAAGAGCAGCACCTGAAACTAGTGAAAGATTTCGAGGAAAAGCTTAAAGCACTA
CAGAGAGGCACTGAGGGCTCCAAAAATTTGAAGAAGGAGCTTCAAGAGTTGCTTAAAGAG
AAGCATCAAGAGATTAACCAGTTACAGCATGACTGTATTACGTACCAAGAACTGATTTTG
AACCTTGAAAGGTCTCTGAAGCACTCGCAGACAGAGCAGCAACAAGTGGAGAAGGAGCTG
AGAGAAATGAGCGACAAGGTTGTGGATTTGCAGAAAGAGAACGAGACTCTTGAAACCGAA
CTAAAATCTCTCAAAAATATCCTCAATGAGACCACAAAAGATGTGTCCAGAGTGACTTCA
GAAAAAGACCGACTCCTGCAGGAAATGTCTGAGACACAACAGCAGTCAGAACTAGAGCTG
GTGGAGAAGGAGAAATTGTTAGAAAAACTGGCTGAACAGCAAGAAGCTCTTCTTAGGGAA
CAGCGAGCTGAACTTCAAAAACAGATCAGTGACCTGCAGGAGCAGAATGAAAGGGAAGCT
AAAGTTATTGTTTCTTTACAGAAGCAGGTGGAAGCCAGAGATTTACAGATCAAAACTCTG
CAGAGAGAAGCAGAGACACATTCAGCCAAGCTAGCCATACTGAGTGTAGACACGGCTAGC
AGTGATGCAGCAAAGCAGTGGGACAGTATTTTCCAAAAAGCCTTACATGATAAAGACAGT
CAGCTACTCGAACAAGGTTTTGTTATTGCTCGCCTTTTAGAGGACATTAGGGGAAAAGCT
AGGACTCTAAATGACTTGCAGATTGCTAACAAGAAACTGGAGAAAACACTAAACGAGTAT
TCGGTGGCAGCCGCAGCGCACCAGAGGCAGCTCTTTATAGTGGGTGCAAGCAATACTGAA
CTCAACCAAAACATTGAAATACTTAATAAACAATCTGCAGAACAGAGTGCCTTGATCGAG
AGTTTAGAAAATGATAAAAGCATGCTCATCAAAAAGCTTGAAGAGCAGATATATTTAGCC
TCACAACTGCAGTCCAGCCTTGAGCATTCTGAAAATGTTTTGGCAAAAACTGAGTCTCAA
CTCCTTACAGTGCAGTCTCAGCACAGCAAGCTTATAGTTGATCTAGAGAGACAGGAAGCC
ATCTCATTGAATTTAAAATCTCTACTTCAAAACAAAGACACAGAGATATCTTCCTTGTTA
AATTCAAAAGATGGCCAGATGTCAGGGTATCTAGAGCAACTGCAGGCTAATCATCGTGCT
CAGGTGACAGGTTATGAGGACAGACTTGCTGCCATCTATTCCAAACGAGAGAGTGCTGAG
CAAGAATTAAGAAGGTTTGAAAGTAAGGTCCGAAGTCTCCAAACCAAATTAGACAGGTCT
GTTCAGGATGCTCAACAGATGACAGCGAATATAGCCACCTTGAGAAATGCTGTTGTGGAT
TTACAAGCGGAGAAGGAGCGTTTGGTGTCCGCAATAA------------------ATCAA
AGTAGAGCAAAGGCCATGGAAGAGTCAACTGAAGGTGGTCTTGGTGGGACCAAGGGCCTG
AAACAAGAGATCAAAACCCTTCTCCACCAGATGGACGATCTGAACTCGGAGAATGCCATG
CTCAAGGCACAGCTCATCCGTTATAGGGAGGATTTAAATCAGGTGTTGTCCCTTAAAGAC
AACCAGCTGAAGGACCTCCTGAAAAAGCAGCAGGACTCAATAAAAAACCTTGAAAACCAA
AAACGATCTGTAGAAATGCAGCATCGCGACGCCCTTTTGGAGGTACGCAAGGAAGCAGAG
GAGATACAAGCCTTAAAGGATCAAAATTCCACACTACAGTCTCAGGTACGTAATCTAGAC
GAAGATTTATTAGCCTTAAGGAAGGAGAAGTTGGAGGCAAACGAGAGCAAAGTGATCGCT
GACCTGCAGCAAGCGGTGGCAACCAAAGCTGCTGAATGTAACGACCTTCAACAAAAACTG
TTTGCCCAAAAGGTGGCTACGGATGACTTGACTAGGGGTCTGAAGGAAACGATAAAGGAG
TCAGAGAGGAAATTAACAGAGGCTGAAGAGAAGTACGGTAAAGAACTTGCCATTTTCAGG
AGGGAAGTGGACCTCATGAGGAACGAGAGGGAGACAGCTGAGCAAAGAGTGGCAGATTTA
GCTAGAGACTTGATGCAGACAGAACAGCAGTTGTCTGAGGCTACAGGCCACAATAAAAAA
CTTAAATCACAAAACGAATCACTTGGAAAAGCCATGGCGGCATTACAAAACGACCGTGAT
CAACTCATTGAGGATTTCAAGATTTTACGAAGCAGGTATGATGAAGAACTCAGGGAAACA
ACGGCAGCCGTGAACAAATTTGAGAGACAACTAAATGACACCGCCTCAGAGCTGTCTGCT
GTGGAAACGGAAAAGAATGTGCTGGTCCAAAAGCTCCTGGCACTGGAAAGCGGCAATCCC
CACTCAAAACTGTCTGGGATGGTGAATGATCTTGCACAAGTTGTATCGGAAAAGGAAGCA
GAACTCAAACAGCTGTCGCTGGAGAATGGTTCCTATAGCAGGCAGGTCACAGCATTCTCT
AAAGCCATGGCCAGTTTGCAGACTGACCGAGACAGGCTGGTGGAGGACCTCCGAAGGGCC
AAGCGGGAATTTGAATGTAGACAACTTTCAAGCACCGATACTGTCGCTTCCCTCAAAGCA
GAAGATTCAAATAGCCTTAGCGTCAGTGTTGATGCCCTTCAGACTGAGAGAGATGGCCTG
CGTAAGGAGGTTGTAAACTTGAGG------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Gasteropelecus_sp._gill_3|021826|scaffold33776|m.37741
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------GATGA
ACTTCGTTCCTTGCAGAAAAGCTTAACTTTAACCCAACAGAAAGTTTCTGAGGAACATTG
CCGGTGGCAAGAATCAAGATTC----------GAAGTTGAGAAATTG-------------
-----------------AGAGTTCAATTGGAAACTCTGCAAAAGGAAAAAGAGAACTGCA
TTGTGGACTTTGAGAAATCCCAACAAGAAGTTGGACTTCTTGAGTCACAGCTAAAGCAGC
TTGAAGCACAAAATGTTGAACT-------------------------GATTGAATCAACA
GACAAGAGATTTTCATCAGACCTTGAAGCACCTGTACAGTACACAGAAACTGATTTCTCT
CCAGTGACCTTTAGGCCACAAAAGACCGATCTGAAAGAGAGCGATAAGA------TGTTG
GAGTTTCAGGCTCTGCTCGTGGAGAAAGAGGAGCTTATATCTGCTCTAGAACAACAGCTC
CAGAGGCAAATTCACCTCCATGAGGTTGAGATGGAGAAAATGAGAATTGAAGTCGGTGAG
CTTCAGCGAAAACCAGCAGCAGAT------GCTTCAGAAAACAGATCAGTTGAGCAA---
---------CTAACAAAGAAACTTCAAGCAGCCTTAATTTCACGAAAAGAGCTAATGAAA
GACAATCGATCTATAAAGGAAGAAATGCAGGAACTGTCAGCACAGAGCAACAGGATGCAA
ACCGAGATGTCATCTCTTGAAAGTGTAGTTTCTGATTTGAAACGACAGAACTCAGATTTG
GAGAGTCTTGTCTCTGGCCTGAGTGCTGAAAAGCAGAAACTTTCTGCAAATGTGGATCGA
ATTCTGAGTGAAAATCACAGCCTGTCCGCAGCCTGTGAAAGCCTTAAACTCACAATAGAG
AACATAACCCAACAGAAGCAAGCCTTTTCATGCCAGCTTGAGTCCCTGAAAGATTCCCAG
ACTGAAGAGCTCTCTGAATGGAAATCCAAGCATGCAGATTTGAAACAAGAGTATGAGTCT
CTTTTACAAGCTTATGAGAATGTTAGCAGTGAAATGGATAAGATGAGACAGCTTCTTGAA
GGGGCCAAGAGAGAACGACAGGAAGCATTTCTAAAAGCTCATAAATATGAATCAGAACGA
GAAGGTCTTGAAAAGCAAGTTGGTGAACTTGAGGAGGAGAATGAGAAAATTAAAGAGAAA
ATGAGAAAGTTTGCCAAGCTAAAGCAACAAAAAATTGAAGAGCTTGAAGAGGAAAATGAA
AAAATTAGGCAGGACCTGATCTCCTTTGATGACCAACAGAAATGCAATATAGATGACATG
ACCCTAAAGAACAGTCAGCTGGAAAGTGAAATAAAATCTCTGCAAGAATTGACTGGGGAG
CTCAGAGATAAGATGAGCAAACTTCAACAAGAGAACCTCAACCTCACACAAGAACTGAAG
GATACCAGCTTGTCCCTTGAGAAGTGGCACATGGAATCTAAAGCGACTGAAAGTAATCTG
CAGCTTAAACTCAGCGAGGCTCTGACTTTGAACGCTACCTTCACAGCCCAGATTGAGGCC
CAAAAAGCAGATATTGCATCACAAATTGAAATGGTGGAGTCTGTCCAAAATGAGAAGTTG
AATCTTTTGGAGAAACTGAAACAGGCAGAAAAAGACCATCACTCTGAACTCGCTGAAAGG
GACACAACTGTAGCAGAACTTCGGAATGTGATTGAAGGAAACAGACAAGAAACCATAAGC
CTAAACGAAAAGGTTAGGATTTTAGAAGATGACAAATGTCTGTTACAAGAGGAACTTGAG
AACATCCAAGAAACCTCTGATAAAGTGAAAAATGAGAATGAATATTTGGAGACAGTGCTT
CTCAAAAATTCTGAAAGAATTGACGAATTGACCGAGGCAGTGAGCATCTTGCAAGCACAA
AATACTCAAATGTCAGCACATCTGATTGAAGCCAGGGAGGAGAAGGGGAAGGTTTGCAGA
GAAAAGGAAGATCAGAATTTGAAGCTTGTGAAGGAATTTGAGGATAAACTCAAAACACTT
CAAAGAGGCAGTGAAGGCTCAAAAAACATGAAGAAGGAGCTTCAAGAACTGTTAAAAGAG
AAGCATCAGGAGATCAACCAGCTGCAGCATGATTGCATCAAATACCAGGAGCTAATATTG
AACCTAGAAAGGTCTTTAAAGCAGTCTCAGACTGAGTACCAACAAGTGGAGAAGGAGCTG
AGAGAAATGAGGGAGAAGGCCACAGATTTGCAGGAAGAGAATAACAGTCTTGAAACTGAA
CTAAAGACCCTCAAAAATGTCCTCAATGAGACCACAAAGGAATTGGCCAAAGTGACTTCA
GAAAAAGACAGACTTTTCCAAGAATTTGTCAAGAGTCAACAACAGTCCGAGTTGGAGTCT
GTGGAGAAAGAGAAGTCTTTGGAAAAACTAGCAGAACAACAGCAAGCTCTTCTCAATGAA
CAGCGGGTTGAACTGCAGAAACAGATCAACGACTTGATAGAACAGAGTGATGGGGACGCG
AAATTAATTTCATCATTACAGAAGCAAGTAGAATCCAAAGGTTTGCAAATCAGAACTCTG
CAAAGAGAAGCTGAGACAAATTTGGCCAAACTTGCAGCACTCAGTGTAGATGCAAGCAAG
AGTGATGCTGCCAAGCATTGGGACGGTGTGTTTCAAAAAGCCTTACAGAATAAAGATAGT
CAGCTTCTGGAGCAAGGCTTCGTTATCACACGACTTTTAGAGGACAGCAGAGGTAAAGGA
AGAGCATTAAATGATTTGCAGGTAACCAACAAGAAATTAGAGAGGACACTGAATGAGTAT
TCAGTAGCAGCTGCAGCACATCAGAGACAGCTCTTCATAATGGGGGCAAGCAATACCGAA
CTTAACCAAAACATTGAAATACTTACCAAACAGTCAACAGAACAGAGTGCCTTGATCGAG
AGCTTAGAAAAGGATAAAAGTACTTTACTCAAACAATTAGATGAAGAAACCTCTTCTGTC
TCCCAACTACAGTCCGGTCTTGAGCACTTAGAAAACATGTTGGCAAAGACTCAGTCTCAG
CTCCTTTTAGCCGAGTCTCAATACAGTAAGCTTCAGGTAAACCTAGAGAAGCAAGAATCA
ATTGCACTGCACTTGAAATCTCTGCTTCAAAGCAAAGACAAAGAGATATCCTCCTTGCTG
TCCTCTAAAGATGGTCAGGTTTCCGGATATCTGGAGCAACTCCATGCTAATCATCGTTCA
CAGGAAGCCGGATATGAGGAGAGGTTAACAGAGCTCTATGTCAAGCGAGAGAGTTCAGAG
AAAGAATTAAGATCGTACGAAAGCAAAGTTCGAAATCTGCAGGCCAGGTTAGACAGGTCT
GCTCAGGAGAAAGAACAGATTGCAGCAAATATTAACTCCTTAAGGAGTTCCATTGTGTCT
TTGCAAACTGAAAAGGAACGTTTGGTATCAGAAGTCA------------------ACCGA
AACAAGGCAAGGGTTACAGACAGCTCACCTGAAGGAAGCATGGGTGCAACAAAGGGTCTG
AAAGAAGAGATCAGGACGCTCCTTCATCAAATGGATGATATTAATTCAGAGAATGCCATG
CTCAAAGCGAAGCTCATCAGATACAGGGAGGATTTAAACCAAGTGTTGGCCCTGAAAGAC
AACCAACTGAAGGATCTTCTCAAAAAGCAACAAGATTCAATAAAAAACCTTGAGAACCAA
AAAAGATCAGCTGAAATGCAGCATCACCATGTCCTTCTGGAGGTGCAGAAGGAAGCGGTG
GAAATCAAAGCCTTAAAAGATCAAAATTCTAAACTACAGTCTCAGGTACAGGAACTAGAG
GATGGTTTATTGGccttacataaagagcgtctggaggccaacgagagcaaagtgattgct
gacttaCAGCAGGCTGTGGCAGACAAAGCTGCAGAATGTAACGAACTACAACAAAAACTC
TTTGCCCAGAGGATAGCGACAGATGATCTGAATAAGAGCCTGAAGGAAACAATGAAGGAT
TCAGAGAGAAAATTAGCAGAAGCTGAAGAAAAGTACAATAAAGAACTGGATACTGTGGAA
CGTGAGGTTGACCTTATGAGAAATGAGAGAGAAACAGCAGAGCAAAGAGTTGCAGATTTG
GCCAGAGACTTGATGCAAACGGAGCAGCAGTTATCCGAGGCCACAAGTCTTAAAAAGAAC
CTAAAATCACAGAACGAGTCTCTGGGGAAAGCTATGGCCGCGTTGCAAAATGATCGGGAT
CAGCTGATTGATGATTTCAAGGTTTTACGCAGCAGGTATGATGATGAACTAAGGGAAGCG
ACAGCAGCAATGAATAGATTCGAGAGACAGCTTAACGATGCCACTTCAGAACTATCGGCC
GTCACATCAGAGAAGCATGTATTGGTCCAAAAGCTTTTGGCTCTTGAAAGCACCAATCCA
CACCCTCAGTTATCCGGGATGGTGAACGACCTCTCTCGAGCCGTTTCAGAAAAGGAGGCA
GAACTTAAACAACTCTCATTGGAGAACAACTCCTATAGCAGACAGGTTACAGCGTTCTCC
AAAGCCATGGCCAGTTTGCAGACTGACCGAGACAGGCTGATGGAGGAACTCAGAAAGTCC
AAGAGGGAATTTGAGGGCAGACAACAATCGAATCCCCATACAGTCACTTCCATCAAAGCG
GGAGAGTCGAATAGCCTT------AGTGTTGATGCCCTTCAGACTGAGAGAGATGGCCTG
CGTAAGGAGATTGTGAACCTGAGGTCTCAGAATGCAGAACTGGTGGAGTTGAAGCAGAAG
TATGATGATCAGCAGAGGGAACTCCAACAGGCAAAGGCTTACAAACTGCAATGTGAAAAA
GATATTAGTGGGTACCAGGCAGAACTGGCGGATCTCAGGTCTGAGAAGAGCAAACTGCTG
TATGAATGTCAAGCCCTCAGAGAGGCC---------------------------------
AGCAAGGCATCAGTGGCTCTTGCAGGTAAAGATGTGTCTTCAGAACAGCTGATGCAGCTG
CAGACAGAGAGAATTCAGCTTCAGACTCATCTGCAGCGCTGCCTGGTGGAGATCCAGCAA
AGAGACCTGGGCTTCCAGCAGATCAATGCTAAGCTTCAGCAGTCTGTAGAGGAGAAAGCT
GCAGTATCTGCACAGTTCAGAGCCGTGTCTCAAACTCTCAGAGAGACACAGCTGAGCCTC
AGTGAGCTGCAGAACCGCTGCTACTGGCTGGAGAACCAGCACCATGCACAGCGACCACAG
ACACAGCAGGGCTCTGTTCATGTGGAAGTTGCTCCAGGAGCTCCTCAAGAAAGAAGCAAT
TCTGTGGCTGATCTGGACGGACTGGATGTCAGAGATCTGAGGGGCAGGTTGGTGGAGGCA
GAGCTCCAGCTTGACGCTGCCCAGCAAAATGTATCTCAACTTGGTGATAGGCTGGAGGAG
GAGAGGGCCAGACGGGAAGCAGCCGAGGAGGCTCTGGGATTGGCTGAGCAGAGAGTAAAG
AGTATGGAACCCAGTCCATCCAAATCATCCCAGAGAGACTTCAGTATTCAGCTGGAGGTG
GATGACGAGTGGGAGGCTTTGATTTTAGATCCTAACCAACACCTGCTCACACGCAAGTTC
AAGAGCGGAGTACATTCCTGCAGACGCTGGCTGAGAGGCCGCAGTTTGTACTGCACTAAA
ATGCTGACATCCAGGGCCAAGTCTCGTTACCTATTCATGGCTTACATTCTCACTCTCCAC
CTCCTGGTCTTCATGTGCTTCACTGGTGCTCTGTAG
>Lepidogalaxias_salamandroides_Head_2|015856|scaffold13644|m.18114
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------ATCGACATT
CAAAAGTTGGAACTCGCAGACCAGCATGAAATCGCTCAGTTGTTGCACAAGGAAAAAAAT
AGTTTATCTGAAAAATTTAACCAACTACAGAAGGACTATCAACTAGTGGTTATAGAAAAG
AATTATGCTCTGTCAGAACTTCAGGAGATCATCAACAAAAACAACCAAGATGCTATCAGT
CTGAATGAGAAGGTAAAGATCCTGGAGGATGACAAATCtCTCTTACTGGAGGAGCTGGAA
AATGTTCAGGAGACATCAGACAAAGTGAAAAATGAGAATGAGTATTTGGAAACGGTGATC
CTCAAAAACTCTGAGATGATCGATGAGATGACAGAAGAAATTAAGGTTCTTCAGATTGAG
AACAAGCAACTATCAACTCAACTAAAGGCAAGTCAAGAGAAG------------TCCAAC
CTGGAGAACGAGCAGCAGCATAAATGGGTGAAGGAGCTCAAGGAGAAAATGAAGGCCATT
CACAGGGGGAACCAGGAATCCAAAAATGTTCAGAAGGAGTTGCAGGAGCTTCTCAAAGAA
AAGCACCAGGAAATCAACCAGCTTCAACATGACTGCATCCAATACCAGGAGTGTATTGTG
GACCTTCAGAAGTCGTTAAAAAATTATCTCACTGAACGTGAGCAAATGGAGAAAGAACTG
AAACATCTGAAAGAGAAGACGTCCAGATTTGGAGAAGGGGGAAGGCGCCTGGAAGCTGAA
CTAAAGTCACACAAGAACAGTCTCATTGAGACCAGGATGGATGCTGCAAG----------
-----------------------GTCTGACAACCAGAGCCAGCAGCCAGACACTCAGAGC
AAAGATAAAAAAAGACCTCTGGATGGCAAGGGGCAACGGCAGAAGGCTATTCCTGAGGCT
CAGCAGGTTACATTACAGGAACAGGTTAATGAGCTGGCTGATCTGAAAGAGGCTGAGAGT
CAGCTGGATGTAGAGTTAATAAGTTTGTTAGATTACCCCCATTTA---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Melanotaenia_praecox_viscera_mixture_8|019155|scaffold7470|m.6396
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------ATGGACAAGATGAGGCAGCTCTTAGAA
GGAGCCAAGAGGGACAGGCAGGACGCCCTCAGAAAACTGCACAGCCGCGAGGCCGAAGTG
GTGGATCTGGAGAAGCAAGCCAGAGAGGCGGAGGAAGAAAATGGCAGGCTTAAAGAGAGG
ATGCACAAGTTTACCAAAGAGAAGCGGCAGAAGATGGAGGAGCTGGAGGATGAAAATCAG
AGGATAAAGATAGAGCTGATGGAGCTCAGCAGGAACCACAACAGGGATCTGAGCGAGCTG
AGAGACAAAAACCAGCAACTGGAAGCAGAAATGTGCCAACTCCGAGAGTCCTcagaggat
ctcagagggagactTGCTGTGATTCAGGCTGAAAATGGCCAGCTGGCAGGAAAACTGGAA
GCAACGAGCCGTTCCCTGGAAGAGAGGAGCTTGGAATCAAACACATATGCAAACAATATG
CAACTTAAACTTGACGAAGCACTTAGTTTAAATAATTCGCTGACAGCTCAGATTGAGGCC
CAGAAAACAGAACTCGGTGCCCAGCTGGAAATCGGCGACTTGTTACAAAAGgagaagcAA
AATCTGTCAGAAAGAATAGAAAACATACAGAATGATCACGAGGTGCAGCTGGGAAAGAAA
GACGATGCCATCAAGGAGCTTAAAGACGTCATCAACAAGCACAGCCAGGAGACGGTGAGT
CTGAACGAGAAGGTGAGGATCCTGGAGGACGATAAGACGCTTCTGCAGGAGGAGCTTGAA
AACGCTCAAGAGATCTCTGACAAAGTGAAAAATGAAAACGAATATTTAGAAACCGTCGTC
CTGAAGAATTCCGAGCGGATCGACGAGCTGACGGAGTCCGTCAACGCTCTGCAGGCGCAG
AACACGCAGCTGTCCTCTCAGCTTCGAGCCAGTTCCGACGCAACCGATCGAGTCCGGCga
GAAAAGGAGCAGGAGCAGCTCAAGCTGGTCCGAGAGCTCGAGGAGAAACTCAAGAACGTT
CAGAGAGGAAGCGAGGGGTCCAAAAATGTGAGGAGAGAGCTGCAGGACCTGCTCAAGGAA
AAGCACCAGGAGATAAATCAGCTG------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------
>Sargocentron_rubrum_gill_6|010074|scaffold16845|m.19889
CAGCAGACCAATGAGTTAAACGCTGTCCAGTTGAAGTTTGACG-----------------
--------------AGAAGGTCAAGGAATTGGAAGACATCC-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------GTAACGCTTCTTTGTCACACCTCGGTGAATTGGAG------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------AGTTTGAGACAGCTTGTTGAGGAAAGGGAT--
----------------------------------AAAACCCTGCAGGatttgaaGTTGTC
T-----------------------------------------------------------
---------------------------------------------------------CTT
GCTGAGAAGGAGAGTCAAAGCCAC------------------------------------
----------------------------------------------TCTCTGCCA-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------GTTTTACAAACAGAGCTTGA----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----AACTGTTAAATCCAGTTTGGAAAGCTTGTCTTC----TGAGATTGCAGGAAAAG--
-ATGAGGCTCTCAT---------------------------------------GGCCTTG
GAGCT-----------------------------------AAGGTCACAATCGCTGAATT
CAAAACTTCAC-------------------------------------------------
------------------ATGGTTGAGAATGATTTGGCAGAAGCTCATGCAAAGATACAA
GAAA------------------------------------------------AAACAGAA
GAACTGGAGAAATGTCAGC------------------------------------ATGTT
ATTAACACGGC---TGAGCTGAAGAGCCAACAGGA-------------------------
--GAAGCAAACTGTAATAG-----------------------------------------
------------------------------------------------------------
------ATGAAAATTCAGTTTTG-------------------------------------
------------CAAAGCCAATTAAGCA--------------------------------
-------------------------------------------TTTCTCAGGCGGCAGTA
GAGGAACTTAAACA---------------TAAGTTAGAC---------AGTTACATG---
------------------------------------------------------------
-------------------------------TGTGAAAATGAACAGAAGTATCAAATTTC
AA----------------------------------------------------------
--------------------TGGATGAAAA------------------------------
----------------------------GAAAGCCCTTCTG-----------GAGCAAAG
AGATCTGATGAAAGTGGAGTTTGAGACAGCACTTGCCTCAGTTTCCCAGAAATCATCAGA
AATTAAAAACCTCCAAAACACTTTAGCCGAAACACAGCAGCAGTT---------------
----CAGTGAGGATAAAGATGTTTTGACTAGGGAACTTGAAAAACTACAGCTGCAATGTT
CTGAACAGGAAAGTAACAAGTTACACATGGAATTATTACAACAAGAGAAAGAAAATGCTT
TCATGTGTGTTGATCAACTCAGAGATGAGATAGCCACATTACATAAGCAACTGAAGGAGG
CTGAGAAACTAAATGAGCAGCTACATCAGAAGATCCCTGTTTTGCATGAGAAAGGTTTAA
ATCAGGAAGATGTTAACAGA-GATGAAGCCCAGTCTCTTTGCAAATGCGCTGAAAAATTT
GAAGCAAAACTTAA---------------------GGAGAGAGAAGATG---CATTGTTA
ATTTCTCAGGCTCAGGTGTCAGAAAAGGAAGAGCTCATCTCTGCCCTTGAACAGCAATTA
CAGCGGCAAATTCACCTGCATGAAGTTACCATGGAGAAGATGAGAACAGAGGCCGGTGAG
CTTCAGAGGTCTCGAGAAGATGGC------ACCAAAATGAAAGATCAAGACAACCAGAAC
ACTACTCTCCTAACGAGGAAGCTTCAGGCAGCTTTAATTTCTAGGAAAGAACTCTTAAAA
GAAAACACAACTCTCAAAGAAAAAGTAGAAACACTGTCAGCCAAACATGAAGAAAAAGAA
GCAGAGTCTTTGGCCTTGGAATCATCAGTGTCCAAGTTGAAACAAAAAAATGTGGATCTG
GAAAGCAGTGTGTCATCCCTGAGCAAGGAGAAAGACAAACTCACAGCAGAAGTTGATCGC
GTCCTTAATGATAATCACAATCTATCTGCAGCATGTGAAAGCCTGAAGCGAACCATAGAG
AACATTACTCAACAGAAGCAAGCTTTTTCATGCCAGCTTGAATCTCTTAAGGATTCTCAG
ACAGAGGAGTTGTCTGAGTGGAAGTCAAAGCACTCAGAGCTGAAACAGGAGTACGAGTCT
CTTTTGCAAGCTTATGAAAATGTTAGCAGTGAAATGGATAAGATGAGGCAGCTTTTGGAG
GGAGCAAAAAGAGAAAGGCAGGATGCCCTTCGTAAAGTACACAAATATGAGACTGAGAGG
GAGAGTCTGGAGAAGCAGGCTAGAGAGGTGGAGGAAGAAAATGTTAGGATTAAAGAGAAG
ATGCGCACATTTTCTAAAGCAAAGCAGCAGAAGATTGAGGAGCTGGAAGAAGAGAATCAA
AAAATCAGAAAAGAGCTGACTGAGTTTGATGAAAAACAGAAAATAACAGCTGATGAGCTG
ATTGTTAAAAATCAACAATTGGAGTCTGAGATCTGCAAGCTTAAAGAGTCATCAGAGGAA
CTTGAAAAGAAACTTACAGAGATTCAGGCTGACAATAGTAAACTGGAAGAAAAACTTACA
GAGGCTAGCTGTTCATTAGAAAAGAGTCATTTGCAATCAAAATCATGTGAAAACAACATG
CAATTTAAACTTGATGAAGCACTCAATTTGAATAATTCACTGACTGCCCAGATTGAGGCC
CAGAAAACAGAACTTGGTGCTCAACTGGAAATCAATGATTTATTGCAAAGAGAGAAGCAA
CATCTTTCTGCAAGAATTGAGCAAATACAAAATGACCATGAATTGCAAATAGGAGAGAAG
GACAATGTCATTAAAGAGCTCAAAGACATTATCAACAAGCACAGCCAAGAGACTATAAGC
CTAAATGAGAAGGTTAGGATCTTGGAGGATGACAAGTCTCTTTTGCAAGAGGAACTTGAA
AATGTTCAAGAGACTTCAGATAAAGTGAAGAATGAAAATGAATATTTGGAAACTGTGATC
CTCAAGAACTCTGAAAGGATTGATGAATTGACCGAGTCTGTCAGTGTTTTACAAATCCAA
AACACACAGCTGTCTTCGCAGCTAGCAGCAAATAAGTTGACGACTACTCAGGTTTGTCAA
GAAAAAGAGGAAGAGCAGCTGAGACTAGTCAAAGAATTTGAGGAGAAGCTCAAGATGGTT
CAGAGAGGCAATGAGGGGTCCAAAAATGTGAAGAAGGAACTGCAAGAGCTGCTGAAAGAA
AAGCATCATGAAATAAATCAGCTGCAGCAAAACTGTATAAAATACCAGGAACTGATTTTA
GATTTAGAGGGGTCTTGGAAGACTTCTCAGTCTGCATGTGAACAGTTAGAAAAAGAACTG
AAGAAAAGCTCAGAGAAGATAACCATTTTAGAGGAGAGAGGCAAACATCTTGAAGTTGAG
CTAATTACACATAAGAAACTCCTCCAGGAGGCTACAGAAAGCATTGTGAGTATTCAGTCT
GAGAAAGACCAACTGGCCCTGGAAATATCACAGAAAAGTAAGAGCTGTGAGCATGAGGTC
AATGACA---------CACAAGAAAATATTAATGAGCAACAAAAAAGTGCTTATGTGGAA
AAACAAATT---TTACAGAAACAGATTGATGACCTTCGGAGTTTAAAAGAAGAAGAAAGC
CAAATAGTCAATGAACTTAGACAGCAAATGGATTCCCAAGATCTACAGATTAACACCCTG
AAGAGAGAGGCTGAGACTAATGCAGCAATGCTGTCTGCTTTGTCCTCCACTCCTCAAGGG
GCAGATGCTACAAAACAGTGGAACGACTTGTACCAGAAGACCTTGCATGAAAAGGATAAC
CAGCTTTTAGAACAGGGTTTCGTAATCAAAAGGTTCCTTGAAGAAATGAGGGTGAAAGAC
AAAGAGTTGAATGAACTACGAGTGACCAAGTCAAGACTAGAAAGGACGCTCAATGAATAC
TCGGTTGCTGCTGCTGCACAACAGAGACAGCTGTTCGTAATGGGTGCCAGCAATACTGAA
CTGAACGAAACTGTGGAGCTTATGACTCTGCAGTTAAAGGAACTAAGAGTTCAAGTTGAA
AGAATAGAAAAAGATAAAAACTTACTTAACAGACAGCTTGCTGACATGGAAGATGGAACA
TCCCAAATGCAGCTTAAACTCCAGCAATCGGAGAAGATGAACACAGACACAGAAGCTCAG
CTACTCCTGTTACAGTCTCAAAAGGACAAACTTCAGTCGGACTTTGAGAAGCAGGAGGCC
ATTTCTGTACAGTTGAAAACACTCCTCAAGAGCAAAGATGCTGAGATCTCTTCCTTGCTG
TCCTCTAGAGATGGACAGATGTCAGGCTATCTAGAACAACTTCAGACTAATTATCGTGCC
CAGATAGCAAGTTATGAGAATAAGCTCGCATCTTTATATGAACAAAGAGAAAAGGCTGAC
AAAGAGTTCAGAGGGCTAGAGACCAAGGTCAGAAGTCTGCAAATCAAATGTGACAGGTCT
GCCCAGGAGAAGGAGCACATAGCAGCTAAGATGGAGTCATTCAGGAACTCTATGGTGTCT
TTACAGACTGAGAGGGAGCGACTGATGTCTGAATACAGAATGCTAGAAGCAAAAAATCAG
TTAGGACTGAGAGGTGTAGAGGGCTCTGCTGAAGGGGAAGTCAGTGCAACCAAAGGCCTT
AAACATGAAATAAGGAAGCTGTTACATCAGATGGATGATCTCAACTCAGAGAATGCCATG
CTCAGGGCGCAACTGGTTCGCTACAGAGAGGACTTGAATCAAGTCCTCTCCCTAAAGGAC
AACCAGTTGAAGGTGCTGCTCAAGAAGCAGCAAGACATGATCAAAAACCTTGAAAACCAA
AAGGCTGCTGCTGAAAAGCAGCACAGAGAGTCTCTCTTGGAACTCCAGAAGGAAGAGGAG
GCAAGCAATACTTTAAAAGCAGAGATATCTAAACTCAAAACTCAGGTCACAAAACTGGAA
GCAGACATTTTAGCTCTGAAAAAAGAAAGAACCATGACGAATGAAGGTAAAGTGATTGCT
GACTTGCAGCAAGCTGTGGCAGCCAAATCTGCTGAATGTAATGACCTCCAGCAAAAACTT
TTTGCCCAGAAAAACATAACTGATGAACTGAAGGACAAATTGCAGCTGCTAGAAAATGAG
ACAGACAAAAAGCTGGCAGATGCTGAGGATAAATACAACAGTGAGTTGGATACCTTTGAG
CGGGAGGTGGAACTGATGAGGAACGAGCGGGAGACAGCAGATAAAAGGGTGGCAGAGCTA
GCAAAAGACCTACTCCAAACAGAGCAGCTGTTATCGGAGGCCAAAGCTCAAAGCAAAGAC
ATGAAGGCTCAGAATGAGTCCCTGGGAAAAGCCATGGCTGCTTTACAGAATGACCGTGAC
CAGCTCATTGAAGATTTCAAGATCCTGCGAAACAGATATGATGAAGAACTCCGAGAAACT
CAGGCAGCCTTAACCAAGGTTGAGCGCAGTCTCCAGGATGCCACTTCAGAGTTGGCCATG
TTTGCAAAAGAGAGACAAATCTTTGTACATAAAATCAATGCCTTAGAGAGCAAGGACGCA
CAGACAGAGTTGAACAAGTTACTGGATGAGGTAACCAAGGCTTTGTCAGAAAAGGAAAGA
GAACTGAAGCAGGTCATCATGGAAAATAACTCCTACAGCAGGCAAGTGTCAGCATTCTCC
AGATCCATGGCCAGCCTCCAGAATGATCGTGACAGGCTGATGGATGAGCTGGCCGGGGCC
AAAAGAGTGACTGAGTCCAGGCAAGGGTCAGGTCCAGAGGCAGTGGCCTCCGTCAGTGTG
GAGGAGTCAGATGG------AAGTGGTGTCAGAGCCCTCCAGAATGAGAGAGCTGGGCTG
G---------------------------------------------AGCTGAGCCAGAAG
GTAGATGAGCTGCAGAGAAAATTACAACAGGCACAAGACTACAGAGTGCAAACTGAGAAA
GAAGTCAGCTGCTACCAGAAAGAAATAGCAGATCTCAGGTCTGAGAGAAATAGTCTGCAT
GGTGAATACGAAGCCCTAAAGGAGAAACAGCTGGCTGCAGACAGGAAGGATGGACAACCA
GTCAAGGAAACTGTTGCTTTGGCAGGTCAAAGTGGAATGGAGGAGATGGTGAGACAGTTG
GAGACAGAGAGGATCCAGCTTCACAGAGACTTGCAGCGCTGCCTTTATGAGATCCAGCAG
AGAGACCAGTACTACCAGCAGCTCAACACCAGGCTGCAGCAGGCAGTGGAGGAGAAAGGT
GCTGTAGCAGCCCAGCTTAGAGCAGTTTCCCAAACGCTGAGGGATACA------------
---------CAGGACCGCTGCCACTGGCTGGAGAGCCAGGTCCAAG---------GCCAG
GCACAGCAGGGGTCAGTATGTGCCGAGGTCGCTCCAGGAGCCCCCCAGGAGAGGAGTAGC
CTCTCTGTCACCATGGAAACGGCTGAGGCCAGTCAGCTCAGAGAAAGGCTGCTGGAGGTG
GAGC------------------------------------------GGAGTCTGAGAGAG
GAGAGAGCCAGGAGGGAGGCAGCCGAGGAGGCTCTGAGCATCTCTGAGGAAAGGGCAAAG
AGTGTTGGGTCCAG---------------CCAGAGGGATTTCACCATCCAGCTGGAAGCA
GAAGATGAGTGGGACGGCCTCGTTCTTGACCCCACCCAGCCGCTGCTCACACGCAAGGTA
AAAGGTGGGGTGTTGGCGTGCCGGCGGTGGCTCAGAGGGAGGAGCCTCTACTGCTCCAAG
CTGCTGACGACCCGTGCTCGCTCCCGATATTTCTTTTTAGCCTACTTGCTCACGCTGCAT
GTCGTTGTCCTCATGTGCCTCACCGGTGCCCTTTAA
>Synodus_sp._gill_5|020896|scaffold26302|m.37478
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------TTGGAAGATGACAAATCAGTTTTGCAAGAGGAACTTGAA
AATGTTCAAGAGATCTCAGACAAAGTCAAAAATGAAAATGAATATTTGGAAACTGTGATC
CTTAAAAACTCAGAAAGAATTGATGAATTGACTGAGACTGTAAATGCTCTGCAATCCCAA
AATACACAGCTATCTTCTCAGTTGATGGCCAGTAAACTTGAGAAGACCCAGATATGTAAG
GAAAAAGAAGGGCAGCAACTGAAATTGGTCAAAGAGTTTGAGGAAAAGCTTAAACTGGCT
CAGAGAGGAAATGAAGGATCTAAAAATGTAAAAAAGGAGTTGCAAGAATTACTCAAAGAG
AAACATCATGAAATAAATCAAATGCAGCAAGACTGTATCCAATACCAGGAACTGATTTTA
GATTTAGAGAAGTCATGTAAGGCCTCAAAGTCTTCTCATGAAAACTTAGAAAAAGAACTG
AAAGACAGCTCTATCAAGATATCCACTTTAGAAGAAGGAAATAAACTGCTTGAATCTGAG
TTAATGACTCAAAAGCATCTCCTCCAGGAAGCAATTGAAAACATCTCAAGTGTCAAATCT
GAAAAAGACCAATTGGCCTTAGAAATATCAGAAAAGAGTAAGCAGTTGGAAAATCAATTC
ACGGAAAGAACAAAAACACTTGAAAATTTAATGGAGCAACAAAAAAGTGTCTATATGGAG
AGAGAGGTTTACTTACAAAAACAGGTGGAGGAAATTCAGGCTTTAAAAGATCAGGAGAGC
CAGTTAGTTATTGAGCTGAGACAACAGATAGACTCTCAAGATCTCCAGATAAAAACCCAG
AAAAGAGAGGCAGAGACAAATATGACTCAGCTATTAGCTCTTTCTTCCTCCGCTCGGGGG
GAAGATGCTACAAAATTGTGGAATGAATTGTTCCATAAGACTCTACATGAGAAGGATAGC
CAACTCTTGGAGCAAGGTTTTGTGATCAGAAGATTTCTTGAAGACATGAGGGTGAAGGAG
AAAGACGTGAATGAACTTCGACTAACTAAGTCAAGACTAGAGAGGACACTAAATGAATAT
TCAGTTGCTGCCACTGCACAACAGAGACAGTTGTTTATCATGGGTGCTACCAATACTGAA
CTCAATGAAACAGTGGAGGTCATGAATGTAGAGCTGAAGGAACTGAGTGCTCAAATGGAG
AAGTTAGAAAAAGACAAAAGTCTTCTGAACAGACAGCTCGTTGATAGGGAAGATGTTTTG
GCACAAATGCAGCTGAGTCTTCATCAGTTTGAGAAAGAGCATTCAGATGCAGATGCTCAA
CTATTGCATTTAAAACCCTTAAATGATCAGCTCCAGGCTGATTTAGAAAAACAGGAAGCA
ATTTCTCTGCAATTGAAGACGCTCATTCAAAGTAAAGATGCTGAAATTGCCTCTTTGCTG
TCCTCTAGAGGTGGGCAGATGTCAGGTTATCTTGAAGAGCTTCAAGCTAATCATCGAGCC
CAAATAGCAGGCTATGAAGATAGAATAACTGCTTTATATAATGTAAAGCAAAATGTTGAC
AAGGAGCTCAGAAAACTAGAGACCAAAGTCAAAAGTCTACAAGCAAAGGTTGACAGGTCA
GTTCAAGAAAAGGAGTTAATCGGTGCCAAAATGGAGACATTCAGGAACTCTATGGTGTCT
CTACAGACTGAAAGGGAACATGTGATGTCTGAGTTCAGAATGCTGGAAGCCAGGTATCAG
GTAGGCTTGAGGGGAGGAGAGGGGTCAGCTGAAGGCGATCCTCTTGCAACCAAAGGCCTT
AAACATGAAATAAGAACTCTGTTACACCAGATGGATGACCTTAACTCAGAAAACGCCATG
CTCAGGGCACAACTGGTTCGCTACAGGGAGGATTTGAATCAGGTCCTGTCCCTTAAAGAC
TGCCAGTTGAAGGAGCTACTCAAGAAGCAGCAAGATACAATCAGAAACCTTGAAACTGAA
AAGAATGCTGTGGAAAAACAGCAGAAGGAGTCACAGATGAAACTGCAGGTGGAAGAAGAG
GCAAGTGATGCCTTAAGAGCAGAAATATCTCAACTTAAATCTCAGGTCAAAAAACTCCAG
ACTGATGTATCTTATCTACAAACAGAGAGAAGTGAGACAAATGAAGGCAAAGTGATCACT
GACTTGCAGCAAGCTGTAATGTTAAAAGCAGCTGAATGTAATGATCTCCAGCAAAAACTT
CTTACTCAAAAACATACCACAGATGAATTAAAAGACAAACTTGAAAGGCTAGAAACTGAA
ATTGATAAGAAACTTGGAGAAGCTGAAGATAAATACAACAGCGAGTTAGATGGCTTTGAG
AGGGAGGTGGAACTAATGAGAAATGAGCGAGAAACAGCAGATCAAAGAGTCGCGGAGCTA
GCTAAGGACTTATTGCACACTGAGCAACTCTTATCTGAAACAAAATCCCAAGTCAAAAAT
ATGAAGATCCAGAATGAATCCATGAGTAAAGCCATGGTTGCCTTACAGAATGACCGAGAC
CTTCTCATTGAAGACTTCAAGATCCTACGGAACAGATATGATGAGGAGCTCAGAGAGGCT
CAGTCTGCCTTGGCCAAGGTGGAGCACCGGTTCAGAGACGTCACATCTGAGTTGGCTGGG
TTAGCTAAAGAGAGACAGATTCTTGTTCATAAAGTTGCAGCACTACAGAGCATTGATTCA
CAGCCAGAGATGAACAAGTTAGTTGATGAACTGTCTAAGACTTTGTCAGAAAAAGAAATT
GAGCTGAAGCGAGTCACCCTGGAGAATGATGCATACAGCAGGCAGGTGTCGGCCTTCTCC
AGTTCTATGGCCAGCCTTCAAAATGACCGGGACAGGCTGATGGATGAGCTGGCAGGAGCC
AAAAGAGTTGTTGAAACTAGGCAAGGGTCAAGTCCAAATGCAATCACCTCCATGCTTGAG
GGAGTGTCTAACAGCCAAGGAATCTTTGTTGATGCCCTCGGGAATGAGAGTTACATGCTG
C------------------------------------------AGGAAATGAGACAGAAG
CTGGATGAGCTGCAGAAAGCATTGGAGGAGGCACGGGCACACATATTGCAAACTGAAAAA
GAAACCAACTCCTACAAGGCAGAGCTAACTGATCTTAGGAATGAGAGGAATACTCTTCTG
AGAGAATGTGAAGCATCCAGAAAACCCCAGCAGACTGCAGA---GAAGGCTGGACAATTG
GTTAAGGAGACGGTTGCGTTGGTCGGTCAGGGAGAGGGGCAGGACATGGTCACCCAGCTG
CAGGCAGAGAGGGTGAGGTTACACACAGACCTGCAGCGCTGCCTCTACGAGATCCAGCAG
AGGGACCAGCACTGCCAGCAGCTCAACGCCAAGCTGCAGCAGGCCATGGAGGAGAGAGGA
ACTATGTCAGCTCAGTTGAGAGTGGTCTCCCAAAACTTAAGGGACTCC------------
---------CAGGACCGTTGCCTCTGGCTGGAGAGTCAAGGGCAGG---------CTGAA
ACACTGCAGcagtcggtgtttactgaagtggcaCCAGGGGGACCTCAAGATATGAGCAGC
CTTTCAGTCAGTATTGAATCAACAGAGGTTGGCCAGCTCAGAGACCGGCTGCTGGAGGTT
GAAC------------------------------------------AGAGCCTGGCCGAG
GAGAGAGCCAGGAGAGAAACTGCTGAAGAGGCCTTGGCTTTGGCTCAAGACAGTGTTCCC
AGTCTGGACACCAGCCCGTCCAAAGCCAGCCCCAAAGACTTCAGCATCCAGCTGGAAACC
GATGAGGAATGGGAGGCACTCATCCTGAACCCCAGCCAGCCCTACCTCGCACGCAAGGTG
AAAGGTGGGGTCCTGGCGTGCCGCCGCTGGGTCCGGGGGAGGAGTCTGTACTGTACCAAG
CTGCTGACGACTCGCGCCCGCTCCCGCTACTTCTTCCTGGCCTACCTGCTCGCTTTGCAT
GTGATGGTCCTCATGTGCCTCACCGGCGCCCTCTAG
