>Amblygaster_clupeoides|030273|TR54110|c0_g1_i1|m.74715
AAAA-----------------------ACGAAGAAGAGAAGATAATCTTGCAACAGGTCC
TCATCTTTAACATCTGCATGAACTTCACCATGAAGATGCTAGTTGTGACCGTACTTGT--
-TGCCATGATGGCACTGATGAGGACTAATGCTCTTCCTGAAGCAGAGGCCTCTCCTACGA
CAGAATCAACAGAGCCAGAAAAAGAAGAAGTAGAATCTCCAGCTGGATCAAGTCTTGACA
AAGAAGCAGCA------GAACCTGACAGCGGATCAGAAGGGGGAGTGGATGAGGCAGAAC
CAGCTGAAGA---AGAAAAACATGAAGT-------------------TGCCAAGAGAGCC
TTAT--------GTTACTACAGGGGTTGGCACCGGTATGGAAGACAACGTTTCCGCTACT
TTCCAGGTTCCAGGACTTGGGCTTTAGCTCAGAGACACTGTCAGGCCATGGGTGGAAACC
TTGCATCTGTGCATAGCAGGGCCCAGGATTTATGGTTTCGGCGATTGGCAGGGAACAG--
-------------ACCAACATGGATCGGATTCTCTGATGCACAACAGGAGCGTTACTGGT
TCTGGATTGATGGTACACGTGTCAACTTTGCTGGCTGGTGTCCTAGAGAGCCAAATAATG
------TTCATGGCAAGCAGCACTGTGGACTAATTA---ATTGGACAGGTCGAAGGTGCT
GGGATGACCAGAACTGCTTAGCTCGTTATGGATATATCTGTGCAAT--------------
---------------------------------------------------------AAG
AGGCTGA-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------
>Chanos_chanos_liver|006072|gb|GDQX01026851.1||m.9016
------------------------------------------------------------
-----------------------------ATGGAGATTCCGAGCATCTCTGTGTTCCTCT
GGCTTTTTCTGACTCTC-------------------------------------------
------------------------------------------------------------
--------------------AGTGCTGCAGGCCTCGAAGAGGTGAGTGCTGAGA------
------------------------------------------------------------
------------GCTGTACTAGTGGCTGGACCCAACATGGATCACGCTGCTTCAAATTCA
TCTCGACCCAGAAAACATGGGCTAGTGCTGAGAGATCCTGTTTGGATGCTGGGGGGAACC
TTGCCTCTGTGCATAGCTATGATGAGCAAATATTCATACAGGATTTGATCCTCTCAGCAA
CTCACGGTTTCCCCCGTACCTGGATTGGAGGGTATGACGCTCCACAGGACACAGTATGGT
TCTGGAGCGATGGGACTAAAGTGGACTTTAAGTTTTGGGCTTATGAGAAACCAGACGGTC
------------CCCGGGACAACTGTATGGTGACTA---ATTCTGCAGGTGCATTGAAGT
GGGATAATGATTACTGTACGAGCCTTCGACCATACATGTGTGCCAGAGAGCTCCATGAGC
CGCTGAAGCCGCGTGAACACCTGCTTTTCCTCGTTGGAGCCTACCGTGGGGCTGTGAACA
GAACTAATGAACTTCACGATAAGGAACCCCTGTCCGATTTAGATACAGCCGCAGTTGCCC
CGAATGTAACTATACTGAACACCCAGCATTCTTGGCTCTGTCCGTATGGCTGGGAGGAAT
ATGAATCTGTATGCTATGCCTTTATCAACATCAAGGAATCCTGGAGTGAAGCAGAGCAAA
GGTGTAAGCAAGTTGGTGGACACCTCGCCTCTGTGCACAGCAATGAACAATATAATTTCC
TTAGGCAGTTAGTCTGGACCCAAGCCTCTGAAAACGTTCGTACTTGGATTGGCGGTACAG
ATGCTTTTAAAGAGGGCAGCTGGACATGGACTGATGGAACCATATGGAACTACAATAACT
GGGCAAGTGGCCAGCCCAACAACCTTGATGGAAAACAGCACTGCCTGGACATGAACTTTG
GGGAAAAGTGGAATGATGAAAACTGTGAAGTCACACTTCCCTTTATTTGTCGAAAGCCAG
TCTACTAA
>Corydoras_julii_viscera_mixture_8|012076|scaffold21100|m.16160
CGACTGAAGGCACCA----ACCGACACAGCAAGAAGAGACGATCG---------------
----CACTGTTGTCTTCATCATCTCCACCATGAAGCTGTTGACTCTGGCTGCACTTCTTT
GTGCCATGTTGGCTCTGACCAGAGCTGCTGCTTTCGCAGATGTTCAGAAGTTTGAGTCTG
GTAAAGAAGAAACCATCCAGGAAGCTCTTCCAGAAGCAGAAGCAGAACCACAGGCTGAGA
CTGAGGAAACCAACCCAGAGGGTTTTGCAGAACCAGAACCACAGGCTGAGATTGAGGAAA
CCAACCAAGA---AGGAGAAAACGCTGT-------------------GGTCAAGACGGCT
ACATGCCG--CCGTTGTCCCAAGGGCTGGACTTATTACTGGGGTCGTTGTTTCGTCTATA
TTAGATACTACCTGACTTGGCACAAGGCTGCGAAATACTGTCGGGCCTTGGGAGGAAACC
TTGCATCTGTGCGCAGCTTCTACGAGTACAGAGCTCTTCAGAATATTGTTGCAAGAGCCA
ACTGCTATCGACCAACTACCTGGCTTGGAGGCTATAA------ATCGGGATATTACTGGT
ACTGGCTCGACGGCACACGTTTCTCTTACACTAACTGGTGCTGTGGAGAGCCCACTGCAA
------------CTGCCCAGTACTGCATCCAGATGA---ATTATACAGCCAAAAAGTGCT
GGGATAATGTCGAGTGTAATGTCACTCGTCCGTCCATCTGCTCCAG--------------
---------------------------------------------------------GAA
AGCTGCGTGA--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------
>Distichodus_sexfasciatus_gill_4|003241|C874545|m.49411
A-----------------------------------------------------------
---------------------------------------TGAATATTTTTGTGATTGTCT
TTGTCATGTTGGCTTTGGATGCAGCTAC--------------------------------
------------------------------------------------------------
---ATGCCATACGCTG--------------------------------------------
-----------CCTGAGGCTGATTCACA-------------------CATCTTGAGGA--
------------AATGCACTGATGGCTGGGAGAGATTTGGGCCGAAGTGCTACAAATATG
TCAAAGAGGAAAAAACATGGGCAGAAGCAGAGCAACATTGTCTGTCCTTGGGTGGAAACC
TTGCTTCAGTACACAGTATGCAGACACATCAGTTTCTTAAGAGATTGTCAAAAAGCAGCA
CTGGCGTCTACTCTCGTACCTGGATAGGCGGTTATGATGCTCCTCAGGAATTTATTTGGT
TGTGGAGCGATGGCTCCCTGTTTGATTTCAGTGCATGGATTTCTGGTGAGCCAAACAACG
------GTGACTATGCTGAGGCATGTGTGGAAATGA---ACTATGGAGCTGAAGTCCTCT
GGAATGATCACCGCTGTCATATTAAAAAATACTCGGTGTGTCAAAA--------------
------GGCAGCAAGGATTAATATTCTTCC---------------------CTTTCAGCA
AGAATAA-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------
>Melanotaenia_praecox_viscera_mixture_8|003994|C444422|m.30008
------------------------------------------------------------
-----------------------------ATGAAGCTTCTGACTCTCCCTTTACTTCTCT
GTGCCATGATAGCTCTG-------------------------------------------
------------------------------------------------------------
-----------------AGCAGAGCTGCAGATGCTGATGAAGGGCATGACGTCAAGAAAC
GTGAGGCAGA---AGAAGAGAAGCAACT-------------------CGTCAAGAGATCA
CCGT--------TTTGCCCCGGAGGCTGGGCGGGACACGGACGTCGCTGTTTCTTGTATT
TTCCACATGCTTTAACATGGGCGCAAGCTGAGAAAACCTGCCAGGACTACGGAGGAAACC
TTGCTTCTGTGCATGACGTTAAACATTTTAAATGGCTTCGTAGATACGTTCACAGCAAGA
CTCATGGCAGAACAGTGGTATGGATTGGAGGCTATAACATTCCACAGTATGGTTACTGGT
TCTGGAGCAATGGTAAAGCTTTCCGTTATGCATCGTGGTGCGCAGGACATCCCGTAAACA
---------ACGGCTACCAGAACTGCATTCGGCTCAGTGATACTGGGTGTAGCAGATGCA
TGGATACTGCTAACTGCTTCTACCAGCACCCCTTTGTCTGCGTCAG--------------
---------------------------------------------------------GAG
AAAGTAA-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------
>Sargocentron_rubrum_gill_6|024043|scaffold8171|m.9245
------------------------------------------------------------
-----------------------------------atgttggctgtgttt---cttctct
gtgctgcctttgctctgagcggaGCAACAGCTCCAGTGAACGAGACGGTGGCTGCT----
---------------------------------------GAGCAGGACAAGTCTCTGGGG
AGGAAGCC---------AGAGGAGCTTCTGACTGAGAAGCCAGAGAGGCTGGAGGAAAAC
GAGGCTCTGGCTCAGGAGGTGGCAAAAGGCAACGTTTCAGTTTTCCGTGTGAAGAGAGAT
ACCA--------CATGTCCAACAGGCTGGTCCACATATAGATCTCGATGCTTTGTCGTCA
TCACCGTCCCACACACCTGGTCAGAGGCAGAGAGCTATTGTTTGCACCTTGGTGCCAACC
TTGCCTCCATCCACAGCTCATCTGAGTACCACTTTGTTCAGGAGCTTGTGAGGAAGAAAA
CTGGTAGATTTCCTCGAACCTTCATcggtggcactgatgctgctaagaatcGTGTGTGGC
GATGGACTGATGGTTCCAGGTTTGACTATAAGGCCTGGAGCCAGGGAGAGCCCAACAATT
TTTGGGGCTGGGGCAGAGAACCATGTCTTGAGATCA---ACTACGGATCTGGGAGAGGCT
GGAACGACGTGAGATGCGGATATGAGTTTCCCTTTGTGTGCGGCAC--------------
---------------------------------------------------------AAG
GCCGTAA-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------
>Scleropages_formosus_red_gill|021407|scaffold33887|m.43920
AAAG-AACGACATCATTTCAGTGTCACAGAAAAAA-------------------------
---------------TCTGGAGCCGCATCATGGGGCCACTGAGCATCTCTGTGTTGCTCT
TCACTGCTCTTGTTCTCAGT----------------------------------------
------------------------------------------------------------
-----------------GGTGCTTTCGCTGCACCCAGAGCTCAGGAACAGCGTGAGAAAT
CAGTGATTAT---TGAGGGATACATGGA------------------------AAACACCT
CTGCTACACAAGGATGTCCTTCTGGATGGCGTAGGTTTAACTCACGCTGCTTCCACTACA
TCAGCCAAAAAACATCGTGGGTGCATGCACAGATTCATTGTATCCGCTTCAGTGCGTCCC
TCGCATCTATACACAGCCTACAGGAATACCGCTTTGTGCAAAATGTCACACGGAGGTTGG
GCAACAACTTTCCTT---------------------NNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNATGGGACTCCATTTGACTTCACCAAATGGACCCCTGGAGAACCCAATAACC
---------GTGGAGGTGAAAATTGCCTTGAAATGA---ACTTTGGAGATCAAAAATTGT
GGAACGATATCTCCTGCAAGAAATACAATCCATCTGTTTGTGCGAG--------------
---------------------------------------------------------ACA
AGCTTCATAA--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------
>Synodus_sp._gill_5|012856|scaffold17419|m.21366
------------------------------------------------------------
-----------------------------ATGAGGAAGCTGTGCATCCACCTGCTGCTGT
GTGCTGCTGTGCTCATCGTCACCGCTGCTGAAGAACCAGGTGATGTGAGGCTTGGAGACC
AAGAGGAGCCGAGTA------------------------AGGTGGAGGCTGTCGCCCTGA
AGGAGGCT---------GGTGGGGCAGTTTTGGAGGATAACAGCACCGTTGCAGAGAATG
TAGCCCTGAA---GGAAGACAACAGAGTGACTCACATGGATTCAGTGCAGCCAGAGAGGA
ACCAAGCGCTCTGGTGTCCTGGCGACTGGACGCCATATGGGTCAAGGTGCTTCCGCTTCT
TCCCCGTGCAGCGGACCTGGATAGATGCAGAGTTTTTCTGTCAGCGTTACGGAGGGCACC
TGGCATCTGTTCACAGCAGAGAAGAGCATCTCTTCTTACTGGAAATGATCAGAGGAGCTG
CTGGTGACTATGTTCCCACCTGGATCGGGGGCCATGATGCCATAAAGACAAATACGTGGT
TGTGGATCGACGGATCCTGTTTTGATTTCCAGACATGGAACCAAGGAGAACCAAATGGAG
---------GAGATATGGAGAACTGTCTGGAAATGA---ACTGGGAAGTACACAGAGGCT
GGAATGACCTCAGATGTAATGAGGTCCATCCCCATATTTGCTCTAT--------------
---------------------------------------------------TTCTGAGAG
GTGTTGA-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------
