>Amblygaster_clupeoides|028042|TR49120|c1_g1_i1|m.70787
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------ATGAGGAAAGCCAGTGGAGCCC
TGCACTTCTATATCAATGGCATTGACCAAGGAGTGGCTGCAGCACAGACACCAGGTGTCG
TTTATGGGGTCGTCGACCTTTATGGTATGGCTGTCAAGGTTACCATAGTCCACAATCACA
ACCACAGCGACCGTCTCCGGCGAAACAACGCCATTATGAGGGCGTTGTCGCCTGATGTCG
GACGGCCACGCCCCGCGCTGTCATTAACCCCTGACCCCGAGACCCAGGACCGCCTGCTGT
TCCATCCTAACTGTGGGCAGAAGGCCGCCATCATTGGCGACGGAAGAACAGCTCTGCGTC
CTCATGCGACGGACGACTTCAACCACGGTGTGGTCCTGAGCAGCCGTCCGCTGCGCTCCA
ACGAGGTGTTCCAGGTGCGTATCGACAAGATGGTGGACAAGTGGGCCGGCTCCATCGAGA
TCGGCGTGACGACACACAACCCCGCCTACCTGCAGCTCCCATCCACGATGACCAACCTGC
GCTCAGGGACGTGGATGATGACGGGCAATGGGGTGATGCACAACGGCACCACCATACTGG
ACGAATACGGACACAACCTGGACCGGCTCAAAGCGGGTGATACTGTGGGGGTGGTGCGTA
AGGAGGACGGAAGTCTGCACTTCTTTGTAAACGGTGTGGCTCAGGGCCCCGCCGCCTGGA
ATGTGCCGCCCTGCGTCTACGCCGTGGTCGACCTTTACGGACAAGCCGCCCAAGCCACCA
TCATGGACGACATGGCTGACCTCCCCCCTCTGCCGGACGACAGCTCGGAGGGCCCCACGG
CCATGTCGCCGGGCAGCCCGTGCTCGGTCGGCGGTGGCAACGCCGCCAACGACCTGCGTT
TTCACCACCTGCACGGCACCAACGCCGTCATCACCAACGGCGGGCGA-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Distichodus_sexfasciatus_gill_4|012718|scaffold19081|m.21097
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------AGTGGAGCAT
TACATTTCTACATTAATGGCATAGACCAAGGTGTGGCTGCTAATCAGACACCTGGCGTGG
TGTATGGGGTCGTGGACCTTTATGGCATGGCTGTTAAAGTCACCATCGTGCACAACCACA
ACCATAGTGACCGTTTACGGCGCAACAACGCCATCATGAGGGCCCTGTCGCCTGACGTTG
GGCGACCCCGGCCTGCACTTTCGCTGACCCCTGACCCAGAAGCCCCGGACCGCCTGCTCT
TCCACACCAATTGTGGCCAAAAGGCAGCCATTATCGGAGACGGCAGAACTGCTCTTCGGC
CTCATGCAATGGACGATTTTAATCACGGGGTCGTGCTAAGCAACCGTCCCCTGCATTCCA
ATGAGGTGTTCCAAGTTCGCATTGACAAAATGGTGGACAAATGGGCGGGATCAATCGAGA
TCGGAGTGACAACGCATAACCCCGCCTACCTGCAGCTACCCTCCACCATGACCAACCTGC
GCTCAGGGACGTGGATGATGACAGGCAACGGAGTGATGCACAACGGAACGACTATATTGG
ATGAGTACGGACACAACTTGGACAGACTCAAAGCCGGAGACACAGTTGGTGTTGTGCGTA
AAGACGACGGCAGCTTGCATTTCTTTGTAAACGGAGTGCCTCAGGGCCCGGCCGCCTGGA
ATGTGCCACCCAGCGTGTATGCCGTGGTGGATCTCTATGGACAGGCAGCCCAAGCGACAA
TTATGGATGACATGGCTGACCTTCCCCCTCTCCCAGATGACAGCTCTGAGGGGCCGGTTG
CGATGTCCCCAGGAAGCCCCTGTTCCGTCACTGGGGCCAGCACGGCCACGGACCTCCGAT
TCCATCAGCTGCACGGCACTAACGCAGTGATCACCAACGGCGGCCGCACAGCNNNNNNNC
--------------GAGTTTAA--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Gasteropelecus_sp._gill_3|014470|scaffold24160|m.24175
------------------------------------------------------------
------------------------------------------------------------
------------AGCCGGGAGCCGCTCCGTGATCGGGACGTCTTCACAGTTCGAATCGAC
AAGAAGGTGAACTCTTGGAGTGGCTCCATAGAAATTGGTGTGACAGCTCTTGACCCAGCT
GCACTGGATTTTCCCAGCAGTGCCACAGGACTGAAAGGTGGGTCCTGGATTGtgtcaggc
tgttcggttctaaaggatGGGCGCTCAGTGTTGGAAGAGTACGGCCGTGACCTGGACCAG
CTTGGGGAGGGTGACTGTGTAGGGATCCAGCGCAACGGCCGGGGGGAGCTACACTTGTGG
GTCAACGGACAGGACTGTGGCACAGCTGCCAGCGGCTTACCCTCCCGCCTGTGGGCAGTG
GTGGACCTCTACGGCAAGTGTACTCAGGTCACGGTGGTCAGTTGTGAGCCACCTCCAGAC
ACTGAAGTGGAGGGTCACGAGGAAGATGAAGAGGAGCGGGAGGAAGAAGTGGCACCGGCA
TCTCCAGGTGCTCTTATGACTGaggCCAGCCATGATCATGAGAACCATACTGGAGCACTT
GTGCTGAACAGTGTTCCTGCCCTGGCTACAGTGATGAACGGTTCAGCTGAGGAAGTGCCT
GAAGTCACAAGGGGACAAAGCCGACCGGACAAGTTCCCCAACAACTTTGAGTCAGATACT
GTCCTTACAGAACACCAGTTATTTGATGTGTTCAACAATGCCATTGTCTCACTGTATCGT
TCGGAAGGTGAGAGTGGAGAAGACTTGGGGA----------------------TAGGAGG
AGTTGGAGGAGGGTCAG---------------ACTCCTCCAGAGGTGGGACAGGATGTAG
CAATGGAACCAGAGGATCAGGAGGAAATGACAGTGGCATCGGTGGTGGCGCTGAAGGTGG
A---AGTAGCGCAAACAACAGTCCA----TCAGGAAATGCAGGTGGCACTGCAGGGATGG
CAGTGGGCACTGGTGGTATGACCACCAATGATGCTCTGCTCTTCCATGAGAAATGTGGCA
CACTGATTAAACTGAGCAACAACAACAAGACAGCTGAGAGGAGGAGGCCACTGGACGAAT
TTAATAATGGAGTGGTCATGACCAACCGCCCACTGAGGCACAATGAGATGTTTGAGATTC
GTATTGATAAACTGGTGGATAAATGGTCAGGATCCATTGAGATTGGAGTAACAACCCACA
ACCCTAATAATCTGGACTACCCAGCAACAATGACCAACTTGCGCTCAGGTACAATCATGA
TGAGTGGCTGTGGGATTTTAACCAATGGGAAGGGAACGCGTAGGGAGTACTGTGAATTCA
GTCTGGATGAACTTCAGGAAGGGGATCATATAGGGCTAATGAGGAAAGCCAGCGGAGCGT
TACACTTCTACATCAATGGTATAGATCAAGGTGTAGCTGCTAGTCAGACCCCAGGTGTGG
TATATGGGGTTGTGGACCTTTATGGCATGGCAGTCAAAGTGACCATTGTtcataatcaCA
ACCATAGTGACCGTTTACGTCGGAACAATGCCATTATGAGAGCATTGTCACCCGATGTTG
GGCGTCCTCGTCCATCCCTCTCATTGACCCCAGACCCAGAAGCCCCAGACCGCTTGCTCT
TTCATCCAAACTGTGGCCAGAAGGCAGCCATCATTGGTGATGGAAGGACTGCACTACGGC
CTCACGCAACAGATGACTTTAATCATGGGGTGGTGCTAAGCAACCGGCCTCTTCATTCCA
ACGAAGTGTTCCAGGTGCGCATTGACAAAATGGTGGACAAATGGGCAGGGTCTATTGAAA
TTGGAGTAACAACACACAATCCTGCCTACTTGCAGTTACCCTCCACCATGACAAACTTGC
GATCAGGGACATGGATGATGACAGGCAATGGAGTCATGCACAATGGAACAACAATACTGG
ATGAATATGGACATAACTTGGACAGACTAAAAGCTGGCGATACTGTAGGCGTAGTGCGCA
AGGATGATGGCAGCCTGCATTTTTTTGTGAATGGCGTCCCTCAGGGGCCAGCAGCCTGGA
ATGTGCCCCAAAGTGTGTATGCTGTAGTAGACCTATATGGACAGGCAGCCCAAGCAACCA
TCATGGATGACATGGCTGACCTCCCTCCACTCCCAGACGACAGTTCTGAAGGGCCGATGG
CAATGTCCCCTGGCAGCCCCTGTtccatCACTGGGGCCAGTGCAGCCAGCGACCTGCGCT
TCCATCAGCTGCATGGAACTAATGCGGTGATCACTAATGGTGGCCGCACAGCACTCCGAC
AGAACTGCCGCAGTGAGTTCAATGATGCCATCGTAATCTCCAACAGGTGCCTTCGTGATG
GAGAGTTGTTTGAGATTGTAATTCAGAAGATGGTGGACCGCTGGTCAGGCTCAATAGAGG
CAGGAGTGACTGCCATCAGACCAGAGGAGCTGGAGTTTCCCAACACGATGACTGACATTG
ACTATGACACCTGGATGCTGAGTGGCACAGCAATCATGCAGGATGGAAACACCATGCGGA
ATAACTATGGCTGTGATCTGGATTCTCTGAGCACAGGATCTAGGATTGGCATGATGCGGA
CAGCCTCAGGAGATCTGCACTACTACATAAATGGAGTGGATCAAGGAGTGGCTtgcactg
gaCTGCCACCAGGTAAAGAGGTGTATGCAGTGATTGATCTATATGGCCAGTGTGTGCAGG
TGTCCATCACAAGCTCATCTGGCCCTCTGGACAATAGCCTGTGCACCAGTAATATCACAG
AAAAGAGTTTTCCCATACACTCGCCAGTGGCAGGGGTGGCTCATCGCTTACACAGCAAAC
ATGGGAAAAATGTGGTGTTACTTGGAGATGGTTGTCAGGCTGTTAGAGTGGGAGGTTATG
CTCATGGAATTGTGTTCAGTGCAAAGGAGCTCAAGACAGATGAACTGTTTGAGGTGAAGA
TCAATGAGGTGGATGAGCAATGGTCTGGCTCACTCCGCATTGGCTTGACAACCCTGCAGC
CTCCTGACCTGCCTTCCTGTCCCCTTAGCGGCCTCTCGCCCTCCCTCACTCAGCTCAGGT
CAAAAGTCACCTGGCTGCTTGCTGGTTCAGAGGTCAGACGCAACGGTGTGCTGCAGAGGC
AGAACTATGGCTGTTCACTGGACCGCCTAACTGTAGGGAACCGTGTTGGTGTGAAGCGAT
GCAGTGATGATACAATGCACATCTTCATTGACGGAGAGGATATGGGACCAGCAGCTACTG
CTGTGGCAAAGAATGTGTATGCAGTGCTGGATCTCTATGGGAAGGTGACAGCGCTGTCCA
TTGTCAGCTCAACGGTAATAGAGGACACAGAGAGTGTGAAGGCTCCCTCGCTGTCATCCG
ACAGCTGCAGTGAGGGAGAGGAGGACACCACTCCGTGTGAAAATGATCCAGCCCTGGTGC
CTATGTCAATGACGTTTCTGGAGAATCATGGGAAGAACATCCAGCTGTCCAATCAGAACC
TGACTGCTGCCAGAGTGTCCAGCTATAACCAAGGCCTACTGGTCACAGCACAAGCTTTAC
CCCGCCAGCAGCTtttCCAGTTTCAAATAGACAGGCTGAACACATCTTGGACATCATCTT
TGTCGCTGGGTGTGATTGGTCATTCTCCTGACCGCCTCAACTTCCCTTCTACGGCCTGCT
GCCTTAAACGTTCTGTCTGGCTGCTGCAGCGAGATTCTGTCTTCCACAACTCACTTAAGA
TCTGTGAGAACTATGGTCCTAATTTGGACACGTGTCCAGAAGGGACTGTGCTTGGAGTTT
TGGTTGATGCAAATGGCTGTCTCCACCTGTATGTGAATGGGATGGATCAGGGAGTGGCAG
CCCAGGACATACCCAGTCCCTGCTATCCCCTCATTGATCTTTATGGACAGTGTGAACAGG
TTACCATAGTGACCAACCATGTGCCGGCAGTGGGTGCCGAGAGCAGTGATGTTCGTTGCC
AAGGTGACATGGAGAAGGCTGATATGGTGGATGGAATAAAGGAAAGTGTATGTTGGACAC
CTCCTCCTGAGGTCAACCCCAATAAGACCTGCGAGTACCAAGCCCTCTGCTCTAGATTCA
AGGAACTTCTCACACTGCCTGATGGTTACTTTAATGAGGATGCCAAGTATAACCTCTGCT
ACTGTGAGTCTTGTCATAAGCTACGGGGTGATGAGGCATACTACAAGCGTGGCGAACCAC
CCAGGGACTATGCACTGCCATTTGGCTGGTGCCGATTTGCCCTGCGGATCAAGCCACACT
GTGAGGTATCAAATACCTTTAAGAAGTGGCATATTGCTTATCATGGGACGAGCGTAGGCT
CTCTTCGTCGTGCACTGGATCAGAGCCAGGTCCTGACAGAGTCATCATCCGTGTTCTCAG
CATCCCCAGTGAAAGTGGAGGGTCATGGCAGCTATGGAGAACCAGAAGAGAACAGTGCAC
CAGAACGAGAAATCCCTCGTGTGCGCCTCTCTCCTACAATGCGCTACTCTGGTCTGGAGG
TCTTTGCCCCTAAAGTGCAATTCCGAGACCCACGCTCCCTGCGCTGTCACAATGCCCAGG
TGGGCTTTCAGGTGTGTGTGCGTCCGGGCTCCTACAAGGTGGGGCCTCAGTCACTAGGCA
TCAGCGAACCGTTGGATCCCAGATTCAGCAACACGGAGATAGAGTGGATTACCAAGGAGA
AAGGAGGCACCCTTCTCTATGGTCTGTTGATCCGTGTGGAGTGA
>Lepidogalaxias_salamandroides_Head_2|019845|scaffold18518|m.25268
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----GGGGTAGTGGACCTGTATGGCATGGCGGTCAAGGTCACCATCGTGCACAACCATA
ACCATAGCGACCGGCTACGGCGGAACAACGCCATCATGAGGGCTCTCTCTCCGGACGTGG
GCCGTCCGCGGCCCGCCCTCTCACTGACCCCCGACCCCGACACTCAAGACCGCTTGCTCT
TTCACTCCAACTGCGGGCAGAAAGCCGCCATCATCAGTGAGGGCAGGACCGCCCTTCGCC
CACATGCGACGGACGACTTCAACCACGGCGTGGTCCTCAGCAGCAGGCCGCTGCGCTCCA
ATGAGGTCTTCCAGGTGCGCATAGACAAGATGGTGGACAAGTGGGCAGGGTCCATTGAGA
TTGGCGTGACGACGCATAACCCTGCCTACCTGCAGCTGCCGTCCACTATGACCAACCTGC
GATCAGGTACCTGGATGATGACAGGTAATGGGGTGATGCACAACGGAACCACAATACTCG
ATGAGTACGGCCACAATCTAGACCGGCTCAAGGCGGGAGACACGGTGGGCGTGGTGCGGA
AGGAGGATGGTAGCCTGCACTTCTTCGTGAACGGCGTGGCCCAGGGCCCGGCGGCGTGGA
ACGTCCCCCCCAGCGTGTACGCCGTGGTGGACCTGTATGGCCAGGCAGCTCAGGCCACCA
TCATGGATGACATGGCCGACCTGCCCCCCCTACCGGACGACTGCTCCGATGGCCCTGCCA
TCATGTCCCCCGGCAGCCCCTGCTCCGTCGCCGGG---------GCCAACGACCTGCGCT
TTCACCAGCTGCACGGCACCAACGCCGTGATCACCAACGGGGGGCGCACGGCGCTGAGAC
ACAACTGCAGGAGCGAGTTCAACGACGCCATCGTCATCTCCAACCGGTGCCTTCGAGACG
GAGAGCTGTTCGAGATCGTCATTCAGAAGATGGTGGACCGCTGGTCGGGGTCGATAGAAG
CAGGGGTCACCGCAATAAGGCCAGAGGAGTTGGAGTTTCCCAACACCATGACGGATATCG
ACTATGACACCTGGATGCTCAGCGGCACTGCCATAATGCAGGATGGGAACACCATGCGGA
ATAACTACGGCTGTGACCTGGACTCGCTGACGACGGGCtcccggatcGGGATGATGCGCT
CGGCCACCGGTGACCTGCACTACTATATCAACGGGGTGGACCAGGGCGTCGCCTGCACGG
GCCTGCCCCTGGGGAAAGACGTGTATGCGGTTATTGACCTGTATGGTCAGTGTGTTCAGG
TGTCCATCACCAACTCCTCCGGGCCGCTGGACAACAGCCTGTGCACCAGCAATGTGACGG
AGAAGAGCTACCCCATCCACTCTCCCGTGGCGGGAGTGGCCCATCGCCTCCACAGTAAGC
ATGGGAAGAACGTGGTGCTGCTGGCGGAGGGCTGCCAGGCCGTACGGGTGGGGGGCTACG
CCCACGGCATTGTCTTCAGTGCCAAGGAGCTGAAGAACGACGAGCTG-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Melanotaenia_praecox_viscera_mixture_8|000361|C397282|m.24891
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------CACAACCCTGCTTACCTGCAGCTGCCCTCCACCATGACGAACTTGC
GCTCAGGGACATGGATGATGACAGGGAATGGTGTGATGCACAATGGAACCACAATCCTAG
ATGAGTATGGCCACAACTTGGACCGACTCAAAGCAGGTGACACAGTTGGAGTTGTGCGGA
AAGAAGACGGCAGTCTACATTTTTTTGTGAACGGTGTGGCACAGGGCCCAGCTGCCTGGA
ACGTCCCCCCCAGCGTCTACGCTGTTGTCGATCTCTACGGGCAAGCTGCCCAGGCCACTA
TCATGGATGACATGGTGGACCTCCCCCCTCTTCCA-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Pantodon_buncholzi_mixed|012576|scaffold15457|m.20427
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------ATAAAT--------------------------
---------GAGCAGCAGCTCTTTGACGTTTTTAACAATGCCATAGTGTCCCTGTACCGG
TCTGAGGATGAGGCTGGAGATGGCACAGCGGGTGGGGCCCT-----------------GA
TGTCTGAGG-----------------------TCTCCACGCGAGGAATCTCTGGAAGCAC
TAATGGATT------GGCTGGGGGCAGCGAGGGCGGGGTGAGCAGCAGCAGTGGAGGCGG
ACCGGGTAGTGGCGGCAGCACCCCA-GCTGGAGGAGGAGGAGGGGGCTTGCTGGCCCCAG
CCTCCGCCTATGGGCCTGTAACCACCAATGATGCATTGCTGTTTCATGAAAAGTGCGGGA
CGCTGATCAAGCTGAGCAACAACAACAAGACGGCAGAGCGGCGGCGGCCCCTTGATGAGT
TCAACAATGGGGTGGTGATGACAAACCGCCCGCTGCGGCACAATGAGATGTTTGAGATCC
GCATTGATAAGCTTGTGGATAAATGGTCAGGATCCATTGAAATTGGAGTCACAACTCACA
ATCCTAACAACCTGGATTATCCTGCAACCATGACTAACCTTCGCTCAGGCACCATTATGA
TGAGTGGCTGTGGGATCCTCACTAATGGGAAAGGAACACGTAGGGAGTACTGTGAATTCA
GTCTAGACGAGTTGCAGGAGGGAGACCACATAGGCCTGATGCGCAAGGCCAGTGGCGCCC
TGCATTTCTACATCAATGGCATTGATCAAGGTGTGGCCGCTGCCCAGACTCCGGGTGTGG
TGTATGGGGTGGTGGACCTGTATGGGATGGCGGTGAAGGTCACAATCGTTCACAACCACA
ACCACAGTGACCGCCTGCAACGCAACAACGCCATAATGCGTGCCCTGTCCCCGGACGTTG
GCCGTCCTCGTCCAGCGCTTACACTAACTCCCGACCCAGATGCTGCAGACCGTCTGCTTT
TCCACCCTAACTGTGGACAGAAAGCAGCCATCATTGGGGATGGGCGCACAGCCCTGAGGC
CACATGCCACAGACGACTTCAACCATGGTGTAGTTCTCAGCAACCGTCCCCTGCGCTCTA
ATGAGGTGTTCCAGGTGCGCATTGACAAAATGGTGGACAAGTGGGCCGGGTCCATAGAAA
TAGGCGTGACCACGCACAACCCTGCCTACCTGCAGCTGCCTTCCACCATGACCAACCTGC
GCTCAGGTACCTGGATGATGACTGGAAATGGAGTCATGCACAATGGAACTACAATCCTGG
ATGAGTACGGGCACAACCTAGACAGGCTGAAGGCGGGTGACACAGTAGGTGTGGTCCGCA
AGGACGATGGTAGCCTGCATTTCTTTGTCAATGGGGTTCCTCAAGGTCCAGCTGCATGGA
ATGTCCCTCAGAGTGTCTATGCCGTGGTGGACTTGTATGGCCAGGCAGCGCAGGCCACTA
TCATGGATGATATGGCTGACCTTCCCCCGCTTCCAGACGACTGCTCAGATGGCCCTGCAG
CCTTGTCCCCTAGCAGCCCCTGCTCACCGGGAGGTGGAGGGGGCGGCAATGACCTGCGAT
TCCACCAGCTACACGGCACTAACGCAATAATTACCAACGGGGGGCGGACTGCCTTGCGCC
AAAATTGCCGCAGCGAGTTTAATGATGCCATCGTAATGTCCAACAGGTGCCTGCGGGATG
GAGAGCTCTTTGAAATTGTGATTCAGAAGATGGTGGATCGCTGGTCTGGCTCGATAGAAG
CAGGGGTCACCGCTATCAGACCGGACGAGCTGGAGTTCCCCAACACTATGACTGACATTG
ACTATGATACCTGGATGCTCAGT-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Sargocentron_rubrum_gill_6|018006|scaffold26749|m.35085
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------ATGAGGGTGGAGGGGACGTTGGAGGAG-------------------GAGGAGG
CGGCGGAGGGGGAGGAGCCACAGGGACAGACTCCTCTTCTAGAAATGACAGAGGGAGCAG
CAGCGGA---------------------GGGGGTGCGGCCAACGGCGACGGCGGAAGAGG
GCCGGGAGACGGAGGCGCGGGNNNNNNNCGCCGGTAACGGAGGGG------CGGGACTAG
GGGCCATGATGGGCGGCATGACCACCAACGACGCGCTGCTGTTCCACGAGAAGTGCGGCA
CTCTGATCAAGCTGAGCAACAACAACAAGACGGCGGAGCGGAGGAGGCCGCTGGACGAGT
TCAACAACGGCGTGGTCATGACCAACAGGCCGCTGCGCCACAACGAGATGTTCGAGATCC
GCATCGATAAGCTGGTGGACAAGTGGTCAGGCTCCATAGAGATCGGCGTGACCACACACA
ACCCCAACAACCTGGACTATCCTGCTACTATGACCAATCTGCGCTCAGGTACAATCATGA
TGAGTGGCTGTGGGATTCTGACCAACGGGAAAGGGACCCGCCGGGAATACTGTGAATTCA
GCCTGGACGAGCTGCAGGAGGGAGATCACATAGGCTTGATGCGCAAGGCCAGTGGAGCGC
TGCACTTCTACATCAATGGCATCGACCAAGGTGTGGCGGCGGCCCAGACCCCCGGCGTGG
TTTACGGCGTGGTCGACCTCTACGGCATGGCGGTCAAAGTCACCATCGTCCACAACCACA
ACCACAGCGACCGCCTCAGACGCAACAACGCCATCATGCGGGCCCTGTCTCCCGACGTGG
GCCGGCCCCGGCCAGCGCTCTCCCTCACCCCGGACCCCGAAGGGCCCGACCGCCTGCTCT
TCCACCCCAACTGTGGTCAGAAGGCCGCCATCATCAGCGACGGCAGGACGGCGCTGCGGC
CACACGCGACGGACGACTTCAACCACGGCGTGGTCCTGAGCAGCCGGCCGCTGCGCTCCA
ACGAGGTGTTCCAGGTCCGCATTGACAAGATGGTGGACAAGTGGGCGGGCTCCATCGAGA
TCGGCGTGACGACACACAACCCGGCCTACCTGCAGCTGCCCTCCACCATGACCAACCTGC
GCTCAGGGACGTGGATGATGACGGGGAACGGCGTGATGCACAACGGAACGACGATACTGG
ACGAGTACGGGCACAACCTGGACCGACTCAAAGCGGGTGACACAGTGGGCGTGGTGCGGA
AAGAGGACGGCAGCCTCCACTTCTTC----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------
>Scleropages_formosus_red_gill|007053|C1332958|m.80855
GAAGCGCGCCGCCCAGCGAAGATGGCGGCCGAGCTGCATCCCCGCAGCGGAAAGCTCATC
GGCCTGTCGAACTCGAACCGAACGGCGCAGCGCAACCAGCCCGTGCAGGAGTTCAACCAC
GGGCTCGTGCTGAGCCGCGAGCCGCTGCGGGACCGCGATGTGTTCACGGTGCGAATCGAC
AAGAAGGTCAACTCGTGGAGCGGCTCCATCGAGATCGGTGTGACAGCACTTGACCCGGCA
GCCTTGGACTTCCCAAGCAGCGCCACGGGCCTCAAGGGCGGCTCTTGGATCGTGTCGGGC
TGCTCTGTGCTCATGGACGGTCGCTCTGTGCTGGAGGAGTATGGTCGCGACCTGGACCAG
CTGGCCGAGGGCGACTGCGTCGGCATCCAGAGGAACAGCCAGGGCGAGCTGCACCTGTGG
GTCAACGGCCAGGACTGCGGCGCAGCCGCCAGCGGCCTCCCCGCCCGCCTTTGGGCCGTC
GTGGACCTCTACGGCAAGTGCACGCAGATCACGGTAGTCAGCTGCGAGCCGCCGCC---C
CCCGGGACCGAAGCTGAGGGGCCGTGTGAAGAGGAGC-----------------------
CCTCCAGG-------------------ACCCACGGCGAGGACATGGCGAGCGGAGCA---
------------GCGGCCATACAGCCTGCGGTGGTCAACGGCACCGTGGACGAAGTGCCT
GAGCTCCCCGTCAGCCAGAACCGACCCGACAAGTTCCCCAACACGCTGGAACCTGAGGCA
GCGCTCACGGAGCAGCAGCTCTTCGACGTCTTCAACAACGCCATCGTGTCCCTGTACCGC
GCCGAGGACGACGGTGCCGGGGACGCAGGGGGCGCTCTCTCTGATGTGTCCACCAGGGGG
TGCGTGGGGGGGATGAG----------------------------------------CAG
CAGCGGCGT------GCTTGCGGGCAGCAGTGACTTGGCGAGTAGCGGCGGGGGCGCCGG
C---GACAGCTCCGGCAGCAGTCCG----GCCGGAGGGGGCGGGGCCACGCTGGGGCCCG
CGCTCGCCTCCGGGGGCGTGACCACCAACGACGCGCTGCTCTTCCACGAGAAATGCGGCA
CCCTCATCAAGCTGAGCAACAACAACAAGACGGCGGAGCGGCGCCGACCGCTGGACGAGT
TCAACAATGGCGTGGTGATGACCAACCGGCCGCTGCGGCACAACGAGATGTTTGAGATTC
GCATCGACAAGCTGGTGGACAAGTGGTCGGGGTCCATCGAGATCGGCGTGACCACACACA
ACCCCAACAACCTGGACTACCCAGCCACCATGACCAACCTCCGCTCGGGCACTATCATGA
TGAGCGGCTGCGGCATTCTGACCAACGGAAAGGGCACCAGGAGGGAGTACTGTGAGTTCA
GTCTGGATGAGCTGCAGGAGGGCGACCACATCGGGCTGATGCGCAAGTCCAGCGGAGCCC
TTCATTTCTACATCAACGGCATCGACCAGGGCGTGGCCGCTTCCCAGACTCCCGCCGTGG
TGTACGGCGTCGTGGACCTGTACGGCATGGCCGTCAAAGTCACCATCGTGCACAATCACA
ACCACAGCGACCGGCTGCGGCGGAACAACGCCATCATGAGGGCGCTCTCCCCCGACGTGG
GCCGCCCTCGGCCCGCCCTTTCGCTGACCCCGGACCCCGAGGTGCCCGACCGCCTGCTCT
TCCACCCCAACTGCGGACAGAAGGCGGCTATAATCGGCGACGGCCGGACGGCTCTGCGGC
CGCACGCCACCGACGACTTCAACCACGGCGTGGTCCTGAGTAGCCGCCCTCTGCGCTCCA
ACGAGGTGTTCCAGGTGCGCATCGACAAGATGGTGGACAAATGGGCGGGGTCCATAGAGA
TCGGCGTGACGACACACAACCCCGCTTACCTGCAGCTGCCCTCCACCATGACCAACCTCC
GCTCTGGCACCTGGATGATGACGGGGAACGGCGTCATGCACAACGGCACCACCATCCTGG
ACGAGTACGGCCACAACCTGGACCGGCTAAAGGCAGGCGACACGGTCGGGGTGGTGCGCA
AAGACGATGGCAGCCTGCACTTCTTTGTGAACGGGGTGCCCCAGGGGCCGGCTGCGTGGA
ACGTGCCGCCCAGCGTCTACGCCGTGGTGGACCTGTACGGTCAGGCAGCCCAGGCCACCA
TCATGGATGACATGGCTGACCTCCCCCCGCTGCCAGATGACAGCTCGGAGGGGCCCGCAG
CCACGTCCCCCAGCAGCCCCTGCTCGGTGGGTGGGGCCAGTGCTGTCAACGACCTGCGCT
TCCACCAGCTCCACGGCACCAATGCTGTCATCACCAACGGGGGGCGCACCGCCCTGAGAC
AGAACTGCCGCAGCGAGTTCAACGATGCCATTGTCATCTCCAACAGATGCCTTCGAGATG
GCGAGTTGTTTGAGATTGTCATTCAGAAGATGGTGGACCGCTGGTCAGGGTCTATAGAAG
CAGGTGTGACTGCAATCCGGCCGGAAGAGCTGGAGTTTCCCAACACCATGACGGACATAG
ACTATGATACCTGGATGCTCAGCGGCACAGCAATCATGCAGGATGGAAACACCATGCGCA
ACAACTACGGCTGCGATCTGGACTCGCTCACCACGGGTTCCCGCATCGGCATGATGCGCA
CGGCCAGCGGGGACCTGCACTACTACATCAATGGGGTGGACCAGGGCATGGCTTGTGCCG
GCCTGCCGCC------AGAGGTGTACGCAGTCATCGACCTGTATGGCCAGTGTGTCCAGG
TGTCCATCACCAGTTCGTCGGGACCGCTGGACAACAGCCTGTGTACGAGCAACATCACAG
AGAAGAGCTTTCCCATTCAGTCCCCAGTGGCTGGGGTCGCTCACCGCCTGCACAGTAAAC
ATGGCAAGAATGTTGTGCTGCTTGGGGAGGGCAGCCAGGCAGTGAGGATGGGAGGATACA
CACATGGCATCGTCTTCAGCGCCAAGGAGCTCAAGACCGACGAGCTCTTTGAGGTGAAGA
TAGACGAGGTGGACGAGCAGTGGTCCGGCTCCCTCCACGTGGGCCTGACCACACTGCCGC
CTGCGGAGCTGCCCTCCTGCCCCACGGGGGCGCTCTGCCCCTCGCTGCCCCAGCTGCGCG
GTCGTGTCACCTGGCTCCTGGCCGGGACCGAGGTGAGGCGTAACGGCGTGCTGCAGAGGC
AGAACTACGGCTGCTCGCTGGACCGGCTGATGGTGGGGAACCGCGTGGGTGTCAAACGCT
GCAGCGACGACACCATGCATATCTTCATTGACGGAGAGGACATGGGTCCAGCAGCCACTG
CTGTAGCCAAGAACGTGTACGCCGTGTTAGACCTGTACGGGCGCGTCACGGCCATGTCCA
TCGTGAGCTCCACGGTGCTGGAGGACACGGAGAGCAGCAAGGCGCCCTCGCTCTCCTCTG
ACAGCTGCAGTGAGGGCGAGGAGGAGCACAGCCTGTGTGAAAACGAGGCGGCTCCGGTGC
CCACGGTCATGACATTCCTGGAGAACCATGGCAAGAACATCCAGCTGTCTAATCAGAACC
TGACGGCATCACGTGTGTCCAGTTACAACCAGGGCCTCCTGGTCACTGTGCAACCCCTTC
CGCGCCAGCAGCTCTTCCAGTTCCAGATTGACCGCCTGAACCTCTCCTGGACCTCGTCCC
TTTCCCTGGGCGTCATCGGCCACTCGCCCGACCGCCTCAACTTCCCCTCAACCGCTTGCT
GCCTGAAGCGCTCTGCCTGGCTGCTGCAGCGTGACTCTGTCTTCCACAACTCGCTCAAGA
TTTGTGAGAACTATGGACCCAACCTGGACACGTGTCCTGAAGGCACCATTTTGGGACTGC
TGGTGGACGCCAACGGCTGCTTGCACCTCTATGTGAACGGGATAGACCAGGGTGTGGCGG
CGCAGGACATCCCCAACCCCTGCTACCCCCTCATCGACCTGTATGGCCAGTGCGAGCAGG
T-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------CTGTGTCCCAGGGG
TTGTT-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------TGA
