>Amblygaster_clupeoides|002201|TR11325|c0_g1_i1|m.22995
------------------------------------------------------------
------------------------------------------ATGAGTCGTAAAAGGAGC
CACGGATTCCCTGAATCAAGTCCTTCATCGACCCCGCATAACACTTTCATGGATATGACG
GAGTCTGCTCCTCGAGTTGAGGAGGATTTTTCCGAATATGAGTCCGACGAAGAGTTGCTG
TGCTCGGTGAGCGAGATCACGGAGCATCTTGGTAGGAACATCACAGTTGTTCTTGAGACG
GCGTTGTCGGAAATCCGAAAAATGGTGAGTGTCAGGATTCGGGTTCTCAAAATGGAACTT
CGTGAGAAAACAGATGAAATAGAGCTGTTGAAAGCCAGACTGGAAGGCGTAGATAGAGAC
GGGAGAGATGCTGTTTTTCCTGGTTCAGTAACGACAGAGTCTGGTGCGACGAGCGTTACC
AGGAAAACAGACTGCAATTCGAGCTACAAATGTACCAGTGATCCAAAGAAAGCCAAGCCG
GGCGTAACGGGGGTAAAAAAGGAGAAAATAAATGCTATTTGTGACTACCTTATGAAGGAC
AAGAACTCAAGAAATGGT---GCTGAACCTGACATTGATCAGAACAATGCGCCCACGTCC
GGTTGCGACAGGGAGGTTCGTCACGATTCTCAGCAGGTTTCCCTTCATCCATGGACGGAC
AGCGGCATTAGTAGCGGAGGCCCTGGTGATGGGGAG------ACAGATTCCGCACCTGAG
GACATCTTTAACATGTTGCCATCGGGCAGTAAACGGATGTACGAATACGAGTGGATAACA
GGAGAGGA---CTACCCAGC------AGATATCAAAAGTTTTAGTGATGCCAAGTATGAT
GGTGACCCCTCATCAGAGGAGTTGAAGGAAGAGCAGGGTGATGTAGCCAAGGA-------
-----------CGCCTCCCACGCACGCACACCTGAGTTTGCGCTTGACACAAAAGGTTCA
CCAACAGAGGAGGGAGAAAGTCCACTGGCTGACCATGGTGATCCTATGGACCCTACCCAG
CACTTCACATCGGAATCCTACATATGTTCCTTCTGCGGAACCCTCTGCCCCGATGCACTG
TTTCTGGAGGAGCACTTAAAGCTG---CACCACAACGAAACGTCCCCGTCACTGCACCTT
AGCTCCGGTGGCTCTTCGTCTCAGGCTGAGGGCAGCGGCAGCAACAGCAGTGGCAGTGGC
AGTGACGCTATACGGCAGGGATCATCGGGTCACGGCGGAGGGCTGGTCGGCCTCCGCCAG
GGGGGCCCTCGAGAGCGGAAGGTGGAGGGCGGCTTTGAGTGCGGGGACTGCGGCCGCCAC
TTCAACTACCTGGGCAACCTGCGCCAGCACCTCCGCATCCACACGGGCGAGAAGCCCTTT
GAGTGCCCCGAGTGTGGAGAGCGCTTCCGGCACGCTGCCCGCCTCAAGAGCCACCGTCTG
GGCCACAGCGGCGCCCAGAGCCCCTTCCCCTGTCCTCAGTGTGGCAAGGGCTTCCCTGTG
CTGTCCGGTCTCAAACGACACCTACGGGTGCACACAGGTGAAAGCCCCTATGCCTGTCCC
CAGTGCGGCCGTCGCTTCAAGGAGCTGGGCAACCTCTACACGCACCAGCGCA------TC
CACAGCGGTGCCACCCCCTACTGCTGCCAGCAGTGCGGACGCAGCTTCCGCCACCTGGGC
ACCTATAAGAGCCACCGCTGCATGCCGGCACACCTGGGGGCTGGTGGAGGTGGCAGCGGT
GGGGGCAGCGGGCCCATGCCCTCAGGTCATGACGTGCCCCCGGGCACGGACATGCTGTGG
GGGACGAGTGGACCTCACGGCCTCAGGGAGGGCAGCAGCAGCCCCCCCACCCTCGGCCCG
GACGACAAGACGAGCAAAGACGAGCAGACAGCCGGGGAGTTCTGA
>Corydoras_julii_viscera_mixture_8|015057|scaffold24885|m.20804
AGCGGAAGTAGTGTCAGAGCGTCGCTGGTGTTAGACAATCGCTCGTCCCAAACAGTCGGT
CGGTCGGTCGGTTGTGTGCAGGAAGGCGCTGCTGGATTCGGGATGAGCCGCAGGAGAAAC
GCGGGCTTTGTGGAAGCGGGGCAGTCAGCGGAGCTCCCGCCGGCGCTGATGGAAGGCCCG
GGGGCGGGCGGGCGCGCTGCGGAGGCGCTGCTGGAGCTGGAGGCGGATGAGGAGCTGATG
TGCTCGGTCGGGGAGATCACGCAGCTGCTGGGCAGGAACATCACGGCGGCCATGGAGGCG
GCTTTGTCCGAGATCCGGAAGGTGGTGAGCGCCCGCACGCGGCTCCTCCACAGCGAGCTG
CGCCAGAAGAGCGAGGAGATCGAGCTGCTGAGAGCCAGGCTGGAGCCGCCGGTCCCGGCC
CGGAGGA--GCGAACTCCCGCAGC-------------CCGCTCCCAAACCCGC-------
--------------------------------TGCCGCCGAGCAGAGGAGAAGCAAGCCG
CTCGCTCCCGCCGTCAAGAAGGAGAACATCGACGCCATCTGCCATTACCTGATGAAAGAC
AAGAACCTGCGCGGGGGC---CCCG------ACAGCGAACAGCAG---------------
------------------------------CAGCAGCAGGCCCTCAGCCCCTGGACCGAG
AGC------------------------------------------------------GAG
GACATCTTCAGTATGTTACCGTCCGGCAGCAAGAGAATCTACGACTACGAGTGGATGAGT
GGAGTGGAGCTCAACCCAGCACCCAACGAGTTCAAAGCTGAGACTGATTCTCAGTGTGAG
AATTCCATGGCTGCAAGAGACACCGATGATGAGAATTCAGCAG--------------AAA
GAACTGGGGC-TGTGTCCGATGTTTCAGAAGCTCCCTTTCCCCTCGATCCTCATGGTTCC
CCAATTCAGGACAGGAGCAGTCCACTAAATGACAGCATGGACAGATTAGAACAAGATGAG
GACTTTTCCTCCACAAGCTTTATTTGCCCCTTTTGTGGAACTCTGTGTCCTGACTCTTTA
TACCTGGAGGAGCACCTAAAGCTGATGCACCAGGATGAAAACATAGACGCTCATCAGTCT
GGCCCCTCCTCCAGTGGTGGTCTGGCTGCTGAGGGCTGTAA-------------------
--------------------------------------------------------TGAA
CCGTCTACGCGGGAGAGGAAAGTGGAGGGGGGCTATGAATGCGGCGACTGCGGACGCCAT
TTTAACTATCTCGGAAACCTTCGACAGCACCGGCGCATCCACACGGGTGAAAAACCGTTC
GCGTGCCCAGACTGCGGAGAGCGTTTCCGGCATGCTGCCCGCCTCAAGAGTCATCGACTT
ACACACAGTGGCAACCTGAGCCCGTTTCCCTGCCCGCAGTGTGGTAAGGGCTTCCCAGTG
CTGTCTGGTCTTAAGCGGCACCAACGTGTTCACACGGGTGAAAGTCCATATGCATGTCCT
CAGTGTGGGCGCCGTTTTAAAGAACTGGGTAACCTGTACACACACATGCGCA------TT
CACAGTGGTGCCACCCCATATACTTGTTACCAGTGTGGACGGAGCTTCAGACATTTAGGA
ACCTACAAAAGTCATCGATGCACACCTGCCACACAGGTACCCAGCGGTCACAG-------
---------------------------------------TCCAGCATGGCT---------
--------------------------------------------------------TCAA
GAAGACAATGT----------------ACAGACTGA-----CTAA
>Distichodus_sexfasciatus_gill_4|011628|scaffold17250|m.18962
------------------------------------------------------------
------------------------------------------------------------
------TTTATTGAAACGGGGCAGTCGTCCGAATCTCAGAACACATTAATGGATACTAGC
GGAGTCTCCGCCCGGTCCGAGGAGAATTTCTGCGAGCTGGAAGCCGACGAGGAGCTGGTT
TGCTCGGTGAGCGAAATAACGGAGCACCTCGGCAGAAACATCACGGTGGTGCTCGAGGCG
GCGCTTTCGGAAATCCGAAAAATAGTCAGCGTGCGGATCAGGGTGCTTAAAATGGAACTG
AGGGAGAAAACGGACGAGATCGAGCTTCTGAAAGCCAGACTGGAGACGGTGGAGAAAGAC
GGGAGGGAGCCGAGCTTACTCAC---------------AGCGGCGGAGTCCGTGTTTGGA
AGGAAATCGGACTTTCAGGCAGGACAAAAATACGGTGTAGATCCGCGGAAAACGAAGGCG
GGTGCTCCGGTTGTCAAGAAGGAGAACATCAACGCGATCTGCGACTATCTGATGAAGGAC
AAGAACTCGCGAGGTGGT---GCTGAAGTGGAGAGCGACCATCAGGCCTTTAACGCGGAC
CGCGTCGGCCGTCACGAGATGCCGCACGCGCCGCCTCCGCCGCTCAGCatgtggaccgac
gccgcgatcggtggCGGAGGAGGCGGCGGTGGGGACGCGGTTACCGACACGGCTGCCGAG
GACATCTTTAGTATGCTGCCTTCCGGGAGTAAACGCCTTTACGACTATGAGTGGATGGCA
GGAGTGGAGCTGAATACTGG------CGAGTTCAAGGGTGAGCCGGAGTCAAAGCGGGAA
AATGTCACAGCTACAAGAGAGGTAGCTGAAGAAGACGAGGATGAGTGTGAAGAGACCAGA
GGCCTGGGACAGGTCCCTGGTTCCTCCCCGTCCCCATTTCCTCTAGACACACACGGATCA
CCTGGGGAGGACAGGAAAAGCCCTGCAGAGGACAGCATGGACAGATTAGATCCAGGCCAG
CACTTCTCTGCCCCCACCTTTATTTGCCCCTTTTGCGGAACCCTCTGCCCTGATTCCACA
TTCCTAGAAGAACACATAAAGCTTATCCACCGAGACGAGAGCATCCACGCTCTTCAGTCC
ACCCCTGGCAGCTCCTCCTCTTCCCACGCCGATGGCGGCGACATCAGCGAGGCGGGAAG-
---------------------------------ATCCGCAGATGCTCCAG-----GAATT
CGTGGGCCCCGCGAGAAGAAAGTGGACCGAGGCTACGAGTGCGGCGACTGCGGGCGGCAC
TTCAACTACCTGGGCAACCTCCGTCAGCACCAGCGCATCCACACTGGGGAGAAGCCCTTC
GTCTGCCCAGAGTGCGGCGAGCGTTTTCGCCATGCCGCACGCCTCAAGAGCCACCGGCTC
AGTCACAGCGGTGCCCAAAGCCCCTTCCCATGCCCGCAGTGTGGCAAGGGCTTCCCGGTG
CTGTCTGGACTCAAACGGCACCAGCGCGTCCACACGGGTGAGAGTCCCTACGCCTGTCCC
CAATGCGGGCGCCGCTTTAAAGAGCTGGGCAACCTTTACACTCATATGCGAANNNNNNNN
NNNNNNNNNGCGACGCCATACTCCTGTTACCAGTGTGGACGAAGCTTCCGCCATTTAGGA
ACTTACAAAAGTCACCGCTGCACTCCCGCGACCCAGCTGCCCAGTGGCCACAG-------
---------------------------------------TCCGGCGTGGGC---------
--------------------------------------------------------TCAG
GAGGACAAGGT----------------ACAGACAGG-----gtAA
>Gasteropelecus_sp._gill_3|004861|C949082|m.49811
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------CTCTGTGAGCTGGAGTCCGACGAGGAGCTGGTG
TGCTCGGTCAGCGAGATCACCGAGCACCTCGGCAGGAACATCACCGTGGTACTGGAGGCG
GCCCTGACCGAGATACGGAAAATAGTCAGCGTGCGAATCCGGGTCCTGAAGATGGAGCTG
CGGGAGAAAGGCGACGAGATCGAGCTCCTGAAGGCGCGGCTGGAGTGTGTGGAGAGAGAC
GCCCGGGAGGCGACTCTGCCCGG---------------GATGGACCCGACAGCTTTCTCC
AGGAGAGCGGAGCT---GCTGGGCCAGAAATATGGCTCGGAGCAGAAGAAGGCGAAGCCC
GGGGCGCCCGTGGTCAAGAAGGAAAACATCAACGCCATCTGCGACTATCTGATGAAGGAC
AAGAACTCGCGGGGCAGCGGAGCCGAGGTGGAGGGTGAGCAGATGGGT------------
---------------------CAGGGCGCACCGGAGCCCGAGAGGAACCTGTGGACGGAC
AGCGGGATGGGTCCCGGAGGGCCC------GGGGAGCCCGGCCCCGACCCCGGGGCAGAA
GACATCTTCAGCATGCTGCCATCGGGCAGTAAACGCCTGTATGACTACGAGTGGATGTCG
GGAGTGGAGCTCAATTCAGC------CGACTTTAAAGGTGAGTCTGAGTCAAAATGTGAG
AATGTCACAGCAGCAAGAGAGACTGAAGAGGAGGAAGAAGAATCTGAAGAAGGGAGAGGA
GAGCTGGGGCTGGTCTCTGACACACCCTCGGCCTCATTTCCTCTGGATAGTCACGCTTCC
TCAGGAGAGGACCGGAGCAGCCCTGTGGGGGACAGTATGGACAGATTAGATCCAGGCCAG
CACTTCTCCACTCACACATTCATTTGCCCCTTCTGTGGAACCCTTTGCCCTGACTCCACA
TACCTGGAGGAGCACATGAAGCTGATGCATCGAGACGAGAGCATCCAGGCCATGCAGTCC
ACCTCGACCACGTCCCGGGGGGAGGGCACTGAAGGAGATGCTGGAAGGGCTGCTGGTAG-
---------------------------------CTCAGAGACTCCAGCTG-----GCATT
CGGCAGCCCCGGGAGAGGAAGGTTGAGGGGGGCTATGAGTGTGGTGACTGTGGACGTCAT
TTCAACTACCTAGGCAACCTGCGGCAGCACCAGCGCATCCACACTGGTGAGAAGCCCTTT
GTTTGCCCTGAATGTGGCGAGCGCTTCCGGCATGCTGCCCGCCTCAAGAGTCACCGACTG
AGCCACAGCGGGGCCCAAAGCCCCTTCCCTTGCCCTCAGTGTGGTAAAGGCTTCCCTGTT
CTATCTGGCCTCAAGCGGCACCAGCGTGTCCACACTGGTGAAAGCCCATATGCCTGCCCC
CAGTGTGGCCGCCGCTTTAAGGAACTGGGCAACCTGTACACGCACATGCGGA------TT
CACAGCGGTGCCACACCTTACTCCTGTTACCAGTGTGGCCGAAGCTTCCGTCATTTAGGC
ACTTACAAAAGCCACCGTTGCACACCTGCTACGCAGCTGCCCAGCGGACATAG-------
---------------------------------------TCCAGCATGGGC---------
--------------------------------------------------------TCAG
GAGGACAAGGT----------------ACAGACGGG-----TTAA
>Lepidogalaxias_salamandroides_Head_2|028827|scaffold8817|m.11523
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------CGGCAGCACCAGCGCATCCACACCGGCGAGAAGCCCTTC
ACCTGCCCCGAGTGCGGGGAGCGCTTCCGCCACGCCGCCCGCCTCAAGAGCCACCGGCTG
GGCCACAGCGGCGCCCAGAGCCCCTTCCCCTGCCCGCAGTGCGGCAAGGGCTTCCCCGTG
CTGTCGGGCCTGAAGAGGCACCAGCGCGTGCACACGGGCGAGagcccctacgcctgcccg
cagtgcggccgccgcttcaaggAGCTGGGCAACCTGTACACACACCAGCGCA------TC
CACAGCGGGGCCACGCCCTACTGCTGCCAGCAGTGCGGGCGGAGCTTCCGTCACCTGGGC
ACGTACAAGAGCCACCGCTGCACGCCCGCCCAGTGA------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>Pantodon_buncholzi_mixed|001399|C598829|m.31428
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------GTGCTGCT----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------GAAACCCTTC
ACCTGTCAGGACTGCGGCGAGCGCTTTCGTCACGCCGCCCGCCTCAAGAGTCACCGGCTG
GGTCACAGCGGCGTGGAGAGTCCCTTCACCTGTCCGCAGTGCGGGAAGGGCTTCCCCGTG
CTGTCGGGGCTGAAGCGACACCAGCGCGTGCACACGGGCGAGAGCCCCTACGCGTGCCCG
CAGTGCGGTCGGCGCTTTAAGGAGCTGGGTAACCTGTACACGCACCAGCGCA------TC
CACAGCGGGGCCACACCCTACAGCTGCCAGCAGTGCGGCCGTCGCTTCCGCCACCTCGGC
ACGTACAAGAGCCACCGCTGCACGCCCAGCCAGCCGTGGGACGG----------------
---------------------------------------GCCGGCACACAC---------
--------------------------------------------------------CCTG
GGG------------------------------------------
>Sargocentron_rubrum_gill_6|002330|C677223|m.45097
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------AAAATCGAGGGTGGGTACGAGTGCGGGGACTGCGGCCGCCAC
TTTAATTACCTGGGCAACCTACGACAGCACCAGCGCATCCACACCGGAGAGAAGCCCTTC
ATCTGCCCGGAGTGTGGGGAGCGCTTTCGTCATGCAGCCCGCCTAAAGAGCCACCGGCTG
GGGCACAGCGGAGCCCAGAGTCCATTCCCCTGCCCCCAGTGTGGGAAGGGCTTCTCAGTG
CTCTCCGGCCTGAAGAGGCACCAACGGGTGCACACCGGCGAGAGTCCGTATGCTTGTCCA
CAGTGTGGCCGGCGTTTCAAGGAGCTGGGAAACCTGTACACCCACCAGAGGA------TC
CACAGTGGGGCAACACCTTACTGCTGCCAGCAGTGTGGACGCAGCTTCCGCCATCTAGGC
ACCTACAAGAGTCACCGCTGCACCCCAGCACAGTAA------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>Scleropages_formosus_red_gill|029848|scaffold46331|m.62653
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------ATGTTGGCCCC-------------------------------------
------------------------------------------------------------
-----------------------------------------------------------A
CCGCCGGGCCCCTCCTCTCACACCAGCAACCAGGAGTTCCCCACAGAAACACAGGGCCTT
TCGGGAGCGGCAGGGGGtactgctgtggacgaccacctggacagATTAGACTCAAGTCAG
CAGTACCCTGCACACACTTACCTCTGTCCCCTCTGTGGAACCTTCTGTCCCGATACCTTG
TTTTTGGAGGAACACTTAAAATTGATACACAGAGACAGCAGCGCGCAGATGCTGCAATCT
GCTTCTAACCTTCCTGCTACGTTGCCAGGAGAAGAGCGTGGCGATCACAGAAGGGGTAA-
---------------------------------AGGAGAGGACAGGGCAG-----CTGGG
AGAGGGGCCAGGGAGAAGAAGGTGGGAGGAGGTTATGAGTGTGCAGACTGTGGCCGGCAC
TTCAACTACTTGGGAAACTTGCGCCAGCACCAACGCATCCATACTGGGGAGAAGCCCTTC
ATCTGTCCTGAGTGCGGGGAGCGCTTTCGTCATGCCGCCCGCCTCAAGAGTCACCGACTG
AGCCACAGTGGTGCTCAGAGTCCCTTTCCTTGTCCCCAGTGTGGCAAGGGCTTTCCAGTG
TTGTCAGGGCTAAAACGCCACCAACGCGTGCACACAGGTGAGAGCCCTTATGCCTGCCCA
CAATGTGGTCGACGCTTTAAGGAGCTGGGAAATTTATACACCCACCAGCGCA------TT
CACAGTGGGGCCACACCCTACTGCTGCCAACATTGTGGGCGCAGTTTCCGCCACCTGGGC
ACTTACAAGAGCCACCGCTGTACACCTACTCTGTGA------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------
>Synodus_sp._gill_5|014591|scaffold1956|m.2100
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------GGGGAGAAGCCCTTC
ATCTGTCCTGAATGTGGGGAGAGGTTCCGCCACGCCGCCCGGCTCAAGAGCCACCGTCTG
GGCCACAGCGGCGCCCAGAGTCCCTTCCCCTGCCCACAGTGTGGCAAGGGCTTCCCCGTG
CTGTCCGGCCTTAAACGGCACCAGCGGGTGCACACGGGTGAAAGCCCATATGCCTGCCCG
CAGTGCGGTCGGCGCTTCAAGGAGCTGGGGAACCTGTACACCCACCAGAGGA------TC
CACAGTGGAGCCACGCCCTACTGCTGCCAGCAGTGCGGACGCAGCTTCCGACATCTCGGC
ACCTACAAGAGCCACCGCTGCACCCCTGCTGTG---------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------ACTAACTAG---------
