>Corydoras_julii_viscera_mixture_8|019364|scaffold8576|m.5741
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------TTCCTTTC
TCCAATGCTGGTGTTGGGCATTTTGATCTCGAGCATTATTCAGTACACTCCTGCAAGGTA
TGGGAAATCCTACACCTACCCGCTGTGGGCCGAGGTGCTGGGCTGGTTCATCTCCCTCGT
TTCTATAATCTGGATTCCACTGGGTGCTGTCCACGAACTCTGGAAAAATGAAGGATCGTT
GTTAGAGAGACTGAAAGTGGCACTAATCCCCACACTGGATCTGGAGCCTGAC--------
-CTGGTGGAAGAGAAACTCGGG---CATCAGACTGTGGCACTAACCCGCACTGACGAACA
ATTAGTCTTAAAAACATCCAATTTATAA
>Distichodus_sexfasciatus_gill_4|027167|scaffold7758|m.8263
---------------------------ATGAACATGGGGCAGGGAG--------------
-CCGAGAATAAAGCCGCATCTCCTAAGCTTGCTGGAGGTTGTATGAATAGGTTGAGGATC
TCCGATGTGGAGACGGAAGACGCGGACGGAGCTCCTCCGCCGCGGAGGGAAACGTGGAGT
CGGCGGCTCGAGTTCGTCCTCGCCTCCGTGGGCTATGCGGTGGGGCTCGGTAACGTGTGG
CGCTTCCCGTACCTCTGCTACCGGAGCGGCGGAGGTGCCTTCCTCATCCCTTACACAATC
ATGCTTTTTCTGTGTGGAATCCCCTTGCTCTTTCTGGAATATGCCGTGGGGCAGTACACT
CGCTTGGGGCCAGTTCATGGATTGG----CCAAAATTTGTCCCCTCCTTAAAGGTGTGGG
CCTAGCTACAGTGGTCATTTCTTTTGTACTCGCCACCTACTACAATGTCCTGATGACCTG
GGCTCTCTATTACCTCTTCAACTCCTTCGACTACACGTTGCCCTGGCAGTCGTGCAATAA
CACCTGGAACGTCCGCGAAAACTGCTCTACCGGTTTT---GGCAATGGCAGTCACGTCAA
GTCAGCCAGCCAGCAGTTCTTTGATCATAAGCTACTAGAGATGACAGGCGGTATCGAGGA
TGCCGGAGGCATTCGCTGGGAACTCTTTGGCCTCCTTATACTGGCTTGGGCCTTCATCTA
CCTCTGCATCTTTAAAGGAGTCAAATCCACTGGAAAGGTTGTGTATTTCACTGCCACGTT
CCCCTACTTCATGTTGTTTGCGTTACTGATTAACAACGTCCGTCTACCTGGAGCCAAAGA
TGGCATCCTCTACTTCCTCATGCCCAACTGGGGCAAGCTGCTGGAAGTGCAGGTGTGGGT
AAATGCAGCTGCCCAGATATTCAACTCTATTGGAATTGCTTTTGGGTCCATGATATCCAT
GGCCAGCTACAATAAGTATAACAACAACATACTCAGGGACACATTTATTGTCTCTTTAGC
CAACTCTGCTACCAGCATCCTAGCGGGTTTTGTGATCTTCTCTGCTATTGGGTACATGGC
ACATATCCATAACTTGCCAGTGGATGACATAGCAACAGATGGTCCAGGTTTGGTGTTTGT
GGTGTATCCAGAGGCCTTCTCCACCATGCCTGTGTCGCGACTGTGGGCTCCACTTTTCTT
CTTCATGCTACTCTGTCTAGGTCTGGATAGTGAGTTTGCAATGGTAGAAGTGGCGGTGAC
GTGCATCATGGATGGTTTCGGGCCAAAGGTTTTGCGTGTGTTTAAGAAAAAAGAGTTCCT
TGTGCTGGCTGTGTGTTCTGTGGGCTTTTTGCTGGGAATCCCACACATCACTAGGGGTGG
TATATATGTGTTCCAGCTGATGGATCACTACACAGCAGTTGTGTCGCTCATGTTTCTGGC
CTTCTTTGAAGTCCTGGCTGTCACAACGATCTTCGGAGTGCCACGCATCTGCATGATGGT
GGAGAACATGCTGGGCAAGAGGCCAAACCTGTATTTTCGAGTCTGTTGGAAGTTCTTATC
TCCTATGTTGGTGCTGGGGATTTTGATTTCCAGCATAGTCCAGTACACTCCAGCACGATA
TGGCAAATCCTACACATACCCGCTGTGGGCAGAAGTGCTGGGCTGGTTTATCTCCCTCAT
CTCCATCATCTGGATACCATTAGGAGCTGCTCACGAAATCTGGAGGAATAAAGGGTCCTT
GTTACAGAGGCTGAAGGTGGCGCTAACCCCCACAGTGAATCTGGATCCTGGGTCTGTCAT
GTCGGACAAGCAGGGAGTTCAG---CCTGAGTCTGTGGTCTTGTTTCATGCTTCTTTGTA
A---------------------------
>Gasteropelecus_sp._gill_3|024622|scaffold4970|m.4747
ACCCTCTCAGGTACCCGGATCACAGGCTTGCGCATGGGGAAGGGGACTCGCTCCTCCCCT
CCCGGCAGGGCGGCCGGGTTCGATGCTGTCTCCGGAGGGGACGCCGGTGTCGTGGAGAGC
CTGCAGCTGGAGGATGTGGAGCCGGA---------TCCTCCGCAGAGGGAGACCTGGAGC
CGCCGGCTCGAGTTCGTCCTGGCTTCGGTCGGATACGCCGTGGGCCTCGGGAACGTGTGG
AGGTTCCCCTACCTGTGCTACCGGAGCGGGGGAGGTGCCTTCCTCATACCTTATTTAATC
ATGCTGTTTGTGTGTGGGATCCCGTTGCTCTTTATGGAGTATGCCATTGGACAGTACACA
CGCTTGGGCCCAGTTCATGGGATGG----CCAAAATCTGCCCCCTTCTCAAAGGTGTAGG
ACTCGCCACAGTGGTCATTTCGTTCGTGCTGGCCTCCTACTATAACGTTCTGATGACCTG
GGCCCTGTACTACCTCTTCAACTCTTTCAGACCCACCTTGCCATGGAAGTCTTGCAATAA
CACCTGGAATGCAGTCGGCAACTGCTCCACCGGCTTTCCCGGCAACGCCACTCACCTACA
GTCAGCCAGTCAGCAGTTCTTCGACCATAAGCTCCTGGAGATGACCAGTGGCATTGAGGA
CGCTGGAGGGGTTCGCTGGGAACTGTTTGGCCTCCTTGCCCTGGCCTGGCTCATCATCTA
TTTCTGCATATTCAAAGGAGTCAAATCCACAGGAAAGGTTGTGTATTTCACGGCCACATT
CCCGTACTTCATGCTGTTTGCCTTGTTGATCAACAACGTCCAGCTGCCCGGAGCAAAAGA
CGGCATCCTATTCTTCCTCATGCCCAACTGGAGCAAGCTCCAGGAGGTGCAGGTGTGGGT
GAATGCAGCTGCACAGGTATTCAACTCCATTGGAATTGCTTTTGGGTCCATGATATCAAT
GGCCAGCTACAACAAATACAACAACAACATCCTGAGGGACACGTTTGTCGTCTCTCTTGC
AAACTCAGCCACCAGTATCCTCGCCGGGTTTGTGATCTTCTCTGCTATTGGATATATGGC
ACATATTCATAACCTGCCTGTGGAAGACATAGCTACTGACGGTCCAGGTTTGGTGTTTGT
TGTGTATCCAGAGGCATTCTCCACCATGCCAGTATCACAGCTGTGGGCTCCTCTTTTCTT
CTTTATGCTGCTGTGCCTCGGACTGGACAGTGAGTTTGCCATGGTGGAGGTAGCCATAAC
CTGCATCATGGACGGGTTTGGTGTGAAGGTGTTGCGCGTGTTTAAAAGGAAGGAGCTACT
GGTGCTGGCTGTGTGCGCCGTGGGCTTTTTGCTGGGGATTCCTCACGTCACCAGGGGTGG
TATCTATGTGTTTCAGCTGATGGATCACTATACAGCAGTTGTATCCCTCATGTTTCTGGC
CTTCTTCGAGGTGCTGGCCGTCACGCTGATCTTTGGAGTGAAGAGGATATGCCTGATGGT
GGAAAACATGTTGGGAAAGAAGCCTAATTTATACTTTCGTGTCTGCTGGCAGTTTCTCTC
TCCAATGCTCGTGCTGGGTATTCTGATTTCCAGTATAATCCAGTACACACCTGCACGCTA
TGGCAAGTCCTATGTGTACCCACTGTGGGCTGAAGTGCTTGGCTGGTTCATTTCTCTGAT
CTCCATCATTTGGATCCCCCTGGGAGCTGCACATGAAATCTATAGAAACAAAGGCTCATT
ATTGCAGAGGCTGAAGGTGGCGCTGACCCCGACAGTGGACTTTGAGCCTATCCATGCCTT
ACCAGAGAAACAGAGGGTGAAC---TCGGAGTCTGTTACCTTCTTCAGCTCCTCCCAGTG
A---------------------------
>Lepidogalaxias_salamandroides_Head_2|014632|scaffold12151|m.15980
---------------------------ATGACCAGAGGAGAAGGCA--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------GTTACTACTGCAGAGGCATCACCTTCCC----------------
------------------------------------------------------------
------AGAAGAGGTTGTGACTTTGGCCCCCTGGTCCCCCTGTTCCTCTGCAGGCGTGGG
CCTCGCTACGGTGGTCATCTCCTTCGTGCTCTGCACCTACTACAACGTGCTCATGACCTG
GGCTCTCTATTACCTGTTCCACTCCTTTGGCTCCTCTCTCCCCTGGGAGTCCTGCAACAA
CACCTGGAACGCCGTGGGCAACTGCTCTAGCGGCTTCCCTGGCAACATCTCGCACCTGCA
GTCGGCCAGCCAGCAGTTTTTTGATCATAAGCTCCTGGAAATGACCAAGGGGATCGAGGA
GGCTGGAGGTGTTCGCTGGGAGCTCTTTGGTATCCTCGTCCTCGCCTGGACCATCGTGTA
TCTTTGCATCTTCAAAGGGGTCAAGTCTACTGGAAAGGTCGTTTACTTCACGGCCACGTT
TCCCTATCTCATTCTGTTTGCCTTGCTGATAAACAACATCCAGCTTCCTGGAGCCAGGGA
TGGCATCCACTACTTTCTGACCCCGAATTGGAGCAAGTTGCTTGAAGTCCAGGTTTGGGT
CAACGCTGCTGCGCAAATCTTTAATTCCATTGGAATTGGATTTGGCAGCATGATCTCCAT
GGCCAGCTACAATAAGTTCAATAACAACTTTCTGAGGGACACCTTGATTGTCTCCATTGC
AAATTCAGCCACCAGTATCCTTGCTGGCTTCGTGATATTCTCAGCTATTGGATACATGGC
TTACATTCACAACCTACCTGTGGACAACATAGCCACAGACGGTCCTGGTTTGGTCTTTGT
TGTCTATCCCGAGGTCTTTGCCACAATGCCTGTAGCCCGGCTGTGGGCCCCCTTATTCTT
CATCATGCTGTTATGCCTTGGCCTGGACAGTCAGTTTGCCATGGTGGAGGTCGCTGTGAC
CTTCATCATGGACGGCTTCGGCCCAAAGGTCCGGCGCTTCCTGAAGAGGCAGGAGGTGCT
CGTCCTGATTGTGTGCCTTCTGGGATTTCTTCTGGGGATTCCCCACATCACCAGGGGGGG
GATCTACGTGTTCCAGCTGATGGACCACTACACAGCTGTGGTGTCTCTCATGTTCCTGGC
CTTCTTTGAGGTCCTGGCTGTGTGCTGGATCTTTGGAGAACGGCGCATATCTAGAATGGT
GAAGCAGATGTTGGGAAAAGCGCCCAACCTCTATTTCCGTCTCTGTTGGTGGGTGCTCTC
GCCTGTCCTGGTGCTGGTCATCCTCATCTCCAGCGTTATCCAGTACACTCCAGCTCGCTA
TGGGAAGAGCTACACCTACCCTGTGTGGGCCGAGGTGGTGGGCTGGTTCATCTCGCTGGT
CTCCATAGTGTGGATCCCCTTGGGTGCCATCCAAGAGCTTTGCTACAACAAGGGTACCCT
AATGGAGAGGCTGAGAAAAGCCATGACACCCACAGTGGAGCTGGGCCCCATCGAGTCCCT
GCCAGAAAAAGAAAGAAGTGGC---ATGGCGTCCATAGCCCTCTTCAGTGCCCCTTAG--
----------------------------
>Pantodon_buncholzi_mixed|000976|C593727|m.30811
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------ATGGGAAAACCTCCCAACCTGTTTTTCCAGTGCTGTTGGCTGGTTCTCTC
TCCTCTGCTCGTCCTGTGCATCCTGATCTCTAGTATCATTCAGTATACCCCGGCACGCTA
TGGAAATAACTACACTTACCCTATCTGGGCCGAGGTGCTGGGCTGGTTCATCTCTCTGGT
GTCCATTGTGTGGATTCCCATTGGGGCTGCACATGAGCTGTGCAGCAAAAAGGGCAATCT
GATTCAGAGATTAAAGAGTGCCCTTACTCCCACTGTGGATCTGGATGGCCTTGATAAGCC
TGTGAACAAAAATCTAATGAAC---ATACAACCTTTGCTTCCCCTCTGCATCCTGGAGGA
G---------------------------
>Sargocentron_rubrum_gill_6|012998|scaffold20746|m.25359
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------ATGCTCGGAAAACCTGCTAACATCTACTTCCGTGTCTGTTGGCTGGTTTGTGC
TCCCATGCTGGTGCTGTGCATACTGATCTCCAGCGTCGCCCAGTACAGTCCTGCTCGCTA
TGGAGAT---TACACGTACCCGGtgtgggcagaggtggtgggctggggcgtCTCACTGGT
CTCTATTGTGTGGATCCCGCTTGGAGCCATTCAGGAGATCTGGAAAAATGAAGGCTCGCT
CATTGAGAGAGTCAAAACAGCTGTGACCCCCACGATAGACTTGGATTTCAAGGATCATCT
GCCAGAGAAACAGAAAATAAACAGCCCAGAGTCTGAAGCCTTGTTCACGTCAGTGGCATG
A---------------------------
>Synodus_sp._gill_5|021628|scaffold26919|m.39192
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------AGGGGAGG
CATGTATGTGTTCCAACTCATGGATCATTACACAGCCGTGGTCTCTCTCATGTTCCTGGC
CTTCTTTGAAGTTCTCGCCACCTGCTGGATATTCGGTCTTCGTCGGATCTGCATCATGAT
AGAGAGGATGCTGGGAAATAGACCAAACCTGTACTTCCGTCTGTGCTGGTTGGTGTTCAC
TCCTCTGCTGGTGCTGTCCATCCTGTTGTCCAGCATCGCCCAATACACCCCAGCGAGCTA
CGGGAAG---TACCAGTACCCAGTCTGGGCTGAGGTCCTGGGCTGGATCATCTCCCTGGT
CTCCATCATCTGGATCCCCCTGGGAGCCATCCAAGAGATCTGCCAAAACAAAGGCTCTTT
TGTTGAGAGAGTCAAAATGGCGATCACCCCAACCATAGACCTGGATTTCAAGGCTGAACT
GCAACTGAAAGAGAAAGCCAACATCCAAGAGTCAGAAACCTTGTTTAACTCCATGGCATA
G---------------------------
