>Amblygaster_clupeoides|008842|TR18477|c2_g1_i1|m.36885
CAGGTTGATGCCCAAGTTGGCCAGGTCATCCGGCAAGTCACAGCTGTAGATGCTGACATT
GGTAACAATGCAGAAATCTTTTATCACCTGCAGGAGGAAAATGACTATGTCCAGGTCAGC
CATATTGGCGAAATTGTCCTGAAAAGACAACTTGAAAAGGAGTTCCTGAACACTGAATTT
GTAGTAACTGTTGTAGCAAGAGATGAGGGTAAGCCATCGCTTTCTGCATCAGTGGAAGTG
CCAGTTTCTGTGGTGAACAAAGCGATCCCATTGTTTGAGAAGCCCTTCTACAGCCTGGAG
ATTCCAGAGAACATACAGTTGCTTACTCCAGTTGTGCATGTTCAGGCTAATGAATCAGAG
GGTCCTCGTATTGTGTACACTATCTCAGAAGGAGACCCTCTCAGTCAATTCACCATCAAC
TTTAACACTGGAGTAATTCAGGTGGTTCAGCCATTGGACTTTGAAACACACCCAGCTTAC
AAGTTGAGTGTTTCTGCAACAGACTCTCTGACCGGGGCACAGTCAAGTGTGTTTGTCGAT
ATTATTTTGGAAGATGTCAATGACAATTCACCTGTATTCCAAGAGAAGTTCTACGAGACA
AGCCTCTCGGAAGCCTCGGTTATTGGAACATCTGTGTTGCAGGTCATGGCCACTGATGCA
GACACTGGTAACAATAAAGAAATCTTCTACCAGATAATAGAGGACAAGAAAAAGAGTTCA
GATTACTTCACTATTGACCGTGACACTGGTATAATTTTGACATCCCGGACCCTTGACCAT
GAGGAAATGGCCGAGCACAAGCTGACTGTAAGAGCTGTCGACGGAGGAGTACCCGCTCTG
TCGAGTGAGGTTGTTGTCACAGTGCATGTCACAGACCTGAATGATAACACACCTGTTTTC
TCACAGAAATTGTATGAGGCCAGTGTCAGTGAACTGGCCCCCCGTGAACACTTTGTCACC
CAAGTGCAGGCATCAGATCCTGACAGCTCAGACGCTGGGAAGTTGGAGTTCTCTATTATC
TCGGGCAACGAAGCACAGAACTTTGCCATGGACAAGAGCACTGGTGCCATAATCATCTCC
AACCACAGGAAACCACACCTCGAACCCCTCTACAACCTCAATATGTCGGTTTCTGATGGC
GTTTTTAGGAGCTGGGCCCTTGTGAAAGTGACAGTTGTTGGGGCCAACTTCCATAACCCA
ACTTTCCCTCAAGTTGATTATGTTGTGGAATTAATTGAGAATACCCCAGCAGGCACCTTG
GTTGCAGAGGTTGAGGCAAATGATGACGATTCAGGAACCTATGGACAGCTGACCTACCAC
ATTCTAAATGACTTTGCTAAAGACAAGTTCTCTGTCAGTGAGAAAGGGCAGATTTTCACT
TTGGAGAGCTTGGATCGTGAGAATCCTCTTGAGAGAGTCATCCCAATCTCGCTGATGGCC
AAAGACGGTGGTGGAAAGGTGGGTTTCTGCACCATTAACGTCATCCTTACAGATATCAAT
GACAACACTCCGCAGTTCAGAGCTGCAGAGTACAGGGTCAATGTGGCCTCAGATGTTCCC
AGAGGAACCACTGTGGTTAAAATCATGGCATCGGATACAGACGAAGGAAGCAATGCTGAC
ATCACCTATGCTATAGAGGCTGATTCGGAGAATGTGCAAGAGAACTTTGAGATCTATCCA
CTCACTGGAATCATTGTGACCAAAGAGAGTCTCATTGGATTGGAGAATGACCTCTACACC
TTCTATGTGAGGGCAAAAGATGCAGGAAACCCCTCAAGACAATCTCTTGTCCCAGTCTAC
ATCAGAGTTCTGGCTCCAGAGGTGCCTGTGCCAAAATTCGTTGAACCTCACTACCGATTT
GCTATTGATGAGGATCTTCCGATTGGTTCAGAAATTGATGTCATTCTGGCAGAGAGTGAA
CAGGCAGTCATTTATAGCCTGGTGAAGGGTAACACTGTGGAGAGTAATCAAGATGAGATT
TTTGCAATTGACAGAGAAACTGGATCCCTGAAATTGGAGAAAAGCCTAGATCATGAAACA
ACCAAATGGTATCAGCTTACACTGCAGGCACAAAGTGAGAATGAAGTTGGAGAAGTTGTA
TCTTCTGTGGATATCAACATTCAAGTCAAGGATGTCAATGACAACCAGCCACTTTTTGAA
GCCAACCCCTATGAAGCAGTTGTGGTTGAGAACCTTCCAAGTGGCACCTCTGTGATCCAA
GTGAAGGCCACAGATTTTGATTCTGGCACCAATGGCCAGGTCGTGTACAGCCTGAACCCC
ACCCAGGAGTCAGCGGAGATCGCTGAACTGTTTGCTGTCAACAGCGAAACGGGATGGGTG
ACAACACTAAAAGAGCTGGACCGTGAGAAAAAGAGCATGTACACCGTGGCCATCCTGGCC
ACTGACCGTGGAGAGAAAGTGCAGCTGGTGGCCAGCACAAAGGTGGACGTGATGGTGGCA
GATGTGAACGACAACCCACCCCGCTTCACGGCTGAGATCTACAAGGGCACCGTGAGTGAA
GATGACCCACCACCAAGCGGTGTGATAGCCATCCTTAGCACAACTGATGCTGATGCAGAG
GACATCAATAAACAAGTCAACTACTTCATCACAGGAGGTGATCCCCTGGGACAGTTTGCC
ATTGAGCATATCCAGAATGAGTGGAAGGTTTCTGTCAGGAAGGCCCTGGATCGCGAGGAG
AGAGACAATTACTTGCTGAACATCACCGCCACTGATGGCACCTTTGTGGCCAAGGCTGTG
GTAGAGGTCAAAGTGTTGGATGCCAATGACAATAGTCCTGTGTGTGAGCAGTCATTCTAC
ACGGAGTCGGTGCCAGAAAACGCTTCACCAGGAAGGCTGGTTCTGCAAGTATCAGCCACA
GATGCGGATATTCGCTCTAATGCCCAGATATCCTATGAGCTGGTGGGACCCGGGGCACAG
CACTTCACTATCGACCCAGACACAGGTGAGCTGAAGACGATGCAGCCTCTGGACCGAGAG
GAAGAGGCCGTGCATCGCATGAAGGTGCGAGCCCTTGATGGCGGGGGGAGGTACTGTGAG
GCTGACGTGGAGATTACGGTTGAGGATGCGAACGACAACGCTCCACAGTGCTCATCCAAC
CCCTACACCATCACCGTCTTTGAGAACACCGAGATCCACACCATTGTGGGAAGACTTCAG
GCCACTGACGCTGATGCTGGCTCCAACGCTGAGGTGGTGTTCTCTTTGGCCGACTCCGCC
GACGGCACCTTCTCCGTGGACGAGCGGAGCGGGCTGCTGCGGCTGGAGCAGCCGCTGGAC
CGCGAGCTGCGCTCCACGTACGCGCTGCGGGCGCGCGCCACTGACCTGGGCTCGCCGCGT
CGCCTCTCCGCGCTTTGCGACGTAAGCGTCTCTGTGCTGGACATCAACGACGACCCGCCT
GTCTTTGAGCGCCGCGAGTACGCCGCCACGCTGGCCGAAGATGTGGCGGTGGGCGCCCAG
GTGCTGCGCGTGCACGCGACCAGCCGGGAGCGGGAGGGTTCCAACGAGATCACCTACGCC
ATTGTCAGCGGCAACGAGCGTGGGGCCTTCCGTGTTGATCCATCAACCGGCGACATCTTT
GTGATTGAGAGTCTGGACTATGAGACCTGCCATGAGTTCTACCTGACAGTGGAGGCCACG
GACGGCGGCGCCCCACCGCTAAGTGACATGGCCACTGTCAACGTCAATCTGACAGACGTC
AATGACAACAGCCCTCTCTTCAGCCAGGGCGTCTACTCTGCTGTGGTCAGCGAGGACTCC
GAGCTTGGGAAGACTGTTGTATTGGTCATGGCAGACGATGCCGACGGCCCCTCCTTCAAC
CAAGTCCGCTACTCCATCATCGACGGTAACCAGGGCAACCCCTTCACCATCGACGCGGTG
CGAGGAGAGGTGAAGGTGGCGCGCACGCTGGACAGAGAGAAGACCTCTGGCTACACTCTG
ACGGTTTTGGCATCAGACAGCGGAAATCCACCCAGATCCAGCAGCGCCACAGTCAACGTG
GACGTGTCGGATGTAAACGACAACCCCCCTCTCTTCTCTGAAGCCAACTACACGCTCATC
ATCCAGGAGAACCGACCAGTGGGCACCAGTGTTCTTCAGCTCACCGTGACGGACCGCGAC
GCCACGCACAACGGCCCGCCCTTCACCTTCTCCATCGTTGGCGGTAACGAGGACAGCGCC
TTCCAGGTCAACCCCCAGGGGGAGCTGCTCGCTGCTACTCCGCTGAGCCGTCAGGCTAAA
GACCACTACCTGCTGCAGATACGGGTGTCGGACAGTGGCCGGCCCCAGCTTCACTCTTTT
GCTCTGGTGAGCGTGCGGGTGATCGAAGAGAGCGTGCATCCTCC----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------G
>Corydoras_julii_viscera_mixture_8|015244|scaffold25084|m.21086
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------AGATCTTCGGTTGTACCTGTTTAT
GTCAGGATCCTTTCCCCGGAGGTCAAAACTCCAAAGTTTTCAGAGCCTTACTACAGGTTT
GCTATAGAGGAAGATCGTCCTCTTGGCTCAGAGCTTGATATAATTCAGGCAGAAAGTGAG
CAGCCTGTGTTGTACAGCTTAGTAAAAGGAAACACTCTGGAGAGCAACAGGGATGAGGTT
TTTGAGCTAGACCGAGACACAGGCGCTCTGAAGCTGGTGAAGAAACTGGACCATGAAGCA
ACCAAATGGTATCAACTTACTCTGCAGGCACAAAGTAATCACGAGGGAACTGATGTTGTC
TCTTCTGTTGATATTAGCATTCAAGTCAAAGATGTGAATGACAACCAtccgctcttTGAA
TCAGATCCTTATGAGGCTGTTGTAGTAGAAAACCTCCCAGGAGGCACCTCGGTAATACAA
GTGAAAGCCATAGACCTGGACTCGAGCACAAATGGACAGGTAATCTATAGTCTGAATCCC
ATTCAGGACTCGGAGGACATAGCAGAATTGTTTGCTGTCAACAGTGAGTCAGGTTGGGTG
ACTACTCTCAAGGAGCTGGACCGTGAACAGAGAGAGAAGTTCACTGTGGCAGTCTTGGCT
ACTGACCGTGGCGACAAGGTACAACTTACATCAAGCACCAAGGTGGAAGTAACCGTGGCG
GACGTAAACGACAACCCTCCTCGCTTCACAGCAGAGATCTACAAAGGCACAGTCAGCGAA
GACGATCCT---CCCAGCGGAGTCATTGCCATTCTCAGTACAAGTGATGCGGATTCTGAT
GACCTCAATAAGCAAGTCGAGTACTTCATCACAGGTGGTGACCCTCTAGGCCAGTTTGGC
ATTGAACACACTCAAGGTGAGTGGAAGGTGTTAGTGCAAAAGCCACTGGACAGGGAGAAG
ACGGACAACTACCACCTCAACATCACTGCTACTGACGGAACCTTCACAACCCGGGCTGTT
GTAGAGGTCAAGGTGCTGGATGCCAATGACAACAGTCCCATATGTGAGAAGACATTTTAC
ACCGCACGTGTCCCAGAGGACGCCGTCTCTGGACATTTTATTCTCCAAGTCTCTGCCACA
GACGCCGACATCCGGTCCAATGCTCATATCAGCTACCAGCTCCTGGGACCAGGATCAAAA
CATTTCAGCGTCGACCCTGACACAGGTGATGTGAAGACCCTGATTGCACTGGACTATGAG
GAGGAACCGTTTTACAGGATGAAGGTGCGAGCTGTGGATGGAGGAGGACGATACTGCGAG
TCTGAAATCGAGGTCGTGGTGGAGGACGTGAATGACAACATGCCACGTTTTATCTCCGAC
CCCTTTTCCATTACTGTGTTCGAGAACACTGAGCTGCACACACCCATCGCCCGGCTGCAG
GCTTCAGACCTGGACACTGGTTCAAACAGCGAGCTCTCATACTCCCTGCTGGACTCAGCA
GGAGGAACCTTCACCATTGACGAAGAATCTGGTATCGTGCGATTGGCCGTTCCACTTGAC
CGCGAACTCCATGCCACATACAGCCTTCGAGCTCGCGCTGTAGACCATGGCTGGCCACGT
TCCTTGTCTGCCTTCTGCACAGTCACAGTGGTGGTGCTGGATCTAAACGATGACCCACCC
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Lepidogalaxias_salamandroides_Head_2|008705|C535964|m.47676
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------AAAATTGCAGCGTCCGACACAGACGAGGGGAGCAACGCCGAC
GTCGCTTACTCCATCGAGGCAGACGTGGAGAACGTGGAGGAGAACTTTGAGATCTACCCC
TTCAGCGGCGTCATCATCACCAAGGAGAGCCTTGTCGGGCTGGAGAACGACCTCTACGCC
TTCTACGTGAGAGCCAAGGATGGCGGGAGCCCCTCCAGGCAGGCCCTGGTGCCTGTGTAC
ATCAGGATCCTGGCCCCTGAAGTCCAGATACCCAAGTTCCCGGAGCCACACTACCGCTTC
AACGTCGCCGAAGACCTGGCTGTGGGTTCCGCCATCGAGGTCATCCAGGCGGAGAGCGAG
CACCCATTGTTCTATAGCCTCGTCAGGGGCAACACCCCCGAGAGCAACCAGGAAGAGGTG
TTTGCAGTGGAACGTGAGACCGGCCTTCTCAAACTAGAGAAGAGTCTGGACCACGAGACC
ACCAAGTGGTACCAGCTCATCCTGCAGGCCCGGAGTGGGGAAGAGGGCAGCGAGCTCATG
GCCTCCGTCGACGTCAGCGTCCAGGTCAAGGACGTCAACGACAACCGACCCGCGTTTGAG
TCAGACCCGTACCGTGCCGTCGTGGCGGAGAACCTCCCCGCGGGGACACCTGTGATCCAG
GTGAGGGCCAACGACCTGGACTCGGGCAGCAACGGTCAGGTGCGGTACAGCCTGGACCCC
GTCCAGGAGTCGGCGGAGGTGGCCGAGCTGTTCGCCGTGAATGGCGAGACGGGCTGGGTA
AGCACGCTCAGGGAGCTGGACCGCGAGGTCCAAGCTGCCTACACCCTGGCCGTGCTGGCC
AGTGACCGGGGGGAGAGGGCCCAGCTGGTCGCCAGGGGCATCGTGGAGGTGACGGTTGCC
GACAGCAACGACAGCCCGCCACGCTTCACTGCCGAGGTCTACAAGGGCACGGTGAGCGAG
GACGACCCGCCTCCCAGCGGGGTCATCGCCATCCTGAGCACAACCGAC------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Melanotaenia_praecox_viscera_mixture_8|006475|C463645|m.34277
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------TATGCT
AATATTTCTGAGGCCTCTGTAATTGGTACATCAGTTCTGCAGGTGGATGCTATGGATTCT
GACAAAGGCAATAACAAGGAAGTATTCTTTCAGCTGGTTGAGGAAAGAGAGAAGAGCTCT
GATTATTTTACCATTGACCGGTACACAGGAATCATTTCTACAGCTGTTGTTCTCGATCAC
GAAGAGATCCAGCAACACAAACTGAGAGTCCGTGCGGTGGACGGAGGCGTTCCAGCCCTC
TCGAGTGACGTCATTGTGACAATAGATGTCACTGACCTGAATGACAATGCTCCCATATTT
ACTGAGCATACTTACAAAACAACCATCAGCGAATTAGCCCCACGTGGTCACTTCATCAGC
CAAGTCCAGGCATCTGACGCTGACAGTTCAGACATAAACAAGTTGGAGTTCTCAATTATA
TCTGGAAATGAAGAGCAGAACTTTGCCATCAACAAAAAAACCGGTGCCATCATTGTTTCT
AACCACCGCCGGTCACATATGCAGCCATTTTACAATCTTAACGTATCAGTTTCAGATGGT
GTATTCAGAGGTTCAGCCCTTGTCATGGTAACAGTTACTGGTGCCAACTTCCACACCCCC
ACTTTCTCTCAGATGGAGTATTTGGTTGAGCTTGTTGAGAACTCACCTGTTGGGACCCTG
GTAGCAGAAGCACAGGCCACAGATGATGACGAAGGCATTTATGGCCAGATAACATACCAG
ATTGTAAATGACTTTGCTAAAGAAAAGTTCTCTATTAATGAAAAAGGAGAGATTTTTACT
CTTGAAAGCCTTGATCGTGAAAATACAGAGGAGAAAGTTATCCCTATCTCTTTGCGAGCT
CAAGATGGAGGAGGAAATGTAGGCTTCTGTACTGTCAATGTCATTGTCACAGACACCAAT
GATAATGCCCCGCAATTCAGAGCAATTGAGTACAAAGCCACTATTGCATCAAATGTCCCA
AGAGGAACCTCTGTGCTTAAAATTGCTGCTTCAGACATGGATGAGGGGAGTAATGCTGAC
ATTGAGTATTCACTGGAAGCAGATGTTGAAAATGTTGCAGAGAATTTTGAAATTCACAAA
ACCTCTGGGGTCATTGTTACCAAAGAAAGCCTCATTGGACTTGAAAATGAACTCTATGCA
TTTTTTGTGAAGGCAAAGGATACTGGGAATCCACCCAAGCATTCAGTTGTCCAGGTTTAC
ATCAGGATTGTCTCATCTGAAACGCCAATTCCCAAATTTGCTGAACCGCATTATCGTTAC
ACTGTTGCAGAGGACCTTCCCATTGGAACAGAGATAGATGTGATTCAGGCTGAGGGCGAG
CAGCCACTCTTCTACAGCCTTGTGAAAGGCAACACTCCTGAGAGCAATGAGGATGATGTG
TTTGTTGTAGATAGAGACAACGGAGCCTTGAAGCTTCAGAAGAGCCTTGACCATGAGACG
ACCAAATGGTATCAACTCACTTTGTTTGCCCAAAGCAAATATGAAGATAATGAGATAGTT
GCATCTGTAAATGTGAACATCCAGGTGAAAGATGTCAATGATAACAAGCCAATCTTTGAG
GCAGACCCCTATGAGGCTGTCACTGCTGAAAACCTTCCAAGTGGGACTCAAGTTATTCAA
GTCAAAGCAACCGACCTCGACTCTGGAACCAACGGCCATGTCGTCTACAGTCTCGACCCC
AAGCAGAACTCGAAGGAGATCTCTGAGCTGTTTGCTGTTAATAGTGAAACTGGATGGGTG
ACCACCTTAAAAGAGCTGGACCGGGAAAACATGGACAAATACACCATTGCCGTCCTAGCC
ACAGACCAAGGCAGCACAGTTCAACACGTTACTGGAACCAAGGTGGAGGTAACGGTGGCC
GATGTGAATGACAACGCGCCGCGCTTCACTGCAGAGATCTACAAGGGAACAGTCAGTGAA
GATGATCCTCCACCCAGTGGGGTGATTGCTATCCTCAGCACCACAGACGATGATTCTGAA
GACATTAATAAACAAGTGAACTATTTCATAACAGGAGGGGACCCGCTCGGCCAATTTGCC
ATCGAACACGTTCAGAATGAATGGAAGGTCTCTGTCAGGAAGCCCTTGGACCGAGAAGTA
ACGGACAATTATCTCCTCAACATTACTGCCAGCGATGGCATCTTCATTGCCAAAGCAGTT
GTGGAAGTCAAGGTGCTGGATGCCAATGACAATGACCCAGTTTGCGAAAAGTCTGTCTAT
AGTGAAAGTGTCCCCGAGGACTCCCCAGCTGGCAGGCTCATCTTGCAGGTCTCTGCCACA
GATGCTGACATCCGCTCAAATGCCCAAATCTTTTACGAGCTTCAAGGCATTGGATCCGAA
TTGTTTATCATTGACTCGAATACAGGGGAATTGAGGACCTTGCAACCCCTGGACCGAGAG
GAGCAAGACGAGCACAGGTTTAAAGTGCGAGCGCTGGATGGAGGAGGTCGCTACTGTGAA
TCTGACATCCACATCACGGTGGAGGACATAAATGACAACTCGCCGCAGTTCTCATCGGAT
CCCTACACCATCACAGTCTTTGAGAACACAGAGACGGGCACGTTTGTTGCAAAACTGCTG
GCAAATGATGTTGATACCGGTCTGAACAGTGACATCCTCTACTCGTTGGATGACTCTGCT
GAGGGATTTTTCTCAATTGACGAGCACACTGGTGTAATAACCCTGGAGCGTCCTCTGGAC
CGCGAGGTGCAGTCAGTATATGAGCTGAAGGCCCGTGCCAGTGACCAGGGTTCCCTACGT
---CTTTCCTCTCTCTGCCAAGTGGTGGTCTCTGTCCTGGACATCAACGACAATCCACCA
GTGTTTGAGCACCGTGAATACACAGCCACCGTGTCTGAGGATGTGGCCGTGGGCACTCAG
TTGCTCAGAGTGCAGGCAGCCAGCCGTGACGCAGATGCTAACGGAGAGATCTCCTACAGC
ATCATCAGCGGGAATGAGCATGGCATGTTCAGCGTCGACTCACGTACTGGTGATATCTTT
GTGATTGAGCCATTGGACTATGAGGTCTCCCATGGATACTATATTACCATAGAGGCTACA
GATGGTGGTTCCCCACCCCTGAGTGACATGGCCACTGTCAACATCAACCTGACTGATGTC
AATGACAACAGGCCCATTTTTAGCCAAGACGTCTACACGACTGTCATCAGCGAGGACACT
GAGCTTGGGAGGACTGTGCTGACTGTGATGGCTGAGGATGCTGACGGGCCTTCCCACAAT
CACATCCGCTACTCCATTGTGGATGGTAACCAAGGCAGCCCGTTCACCATTGATCTGCTG
CGAGGGGAGCTTAAAGTTGCTCGCCAGCTGGACAGAGAAAGAACATCAGGGTACACTTTG
ATGGTGGTCGCCTCAGACAACGGAGTGCCCCCCCTCTCCAGCAGTGCCATGATCAACATC
GACATCTCGGACGTCAACGATAACCCGCCTCTTTTCTCCCAGGCCAACTACAGCCTCATC
ATCCAGGAGAATCGACCAAAAGGCACAAATGTTCTTCAGCTCACTGTAAGCGACCGTGAT
GCTTCTCACAACGGCCCACCTTTCACATTTACCATTGTGGACGGGAACGAGGGCAATGCT
TTCCACATCAATCAGCAGGGAGCTCTGGTGACTGTGGGGGCGCTGAATAGGAAGAGTAAA
GAACACTATCTGCTGCAAGCCCAGGTGTTAGACGGTGGCAAACCCCAGCTGTTCTCTTCC
ACCTTCATCAGTGTGCGTATAATTGAAGAGAGTGTCTACCCTCCAGCAGTACTACCACTA
GACATTTTTGTCTCTGTTGCTGGTGATGAATACCCTGGAGGTGTCCTGGGAAAGATCCAT
GCCACCGACCAAGACATCTATGACACTCTCACCTACAGCCTCGCCCCTTCAGCCTCCTCA
T---------CCGCAGACAAGAGCAGTGCCTTGTTTTCAGTTTCAGCCTCCGATGGTAAA
GTTATTGCCCTGCAGCCGCTCGATGTGGGCCACTATCCTCTCAATGTGACAGTGACCGAC
GGACGCTTCACAACACCCGCCGACGTCACTGTGCACGTTCGTCAAGCGACTCGCCAGGCC
CTGGACAACTCTATTGCAGTACGCTTTGCAAACATTGCCCCTGAGGAGTTTATCGGGGAC
TACTGGCGCAACTTCCAGCGAGCGCTGAGAAACATTGCCGGGGTTAGGAGGAGTGAGGTT
CAGTTGGTGAGCCTGCAGCCTTCAGA---GCAAGGAGATCTGGATGTCCTGCTGACACTA
GAAAGATCTGGCAGCCCATATCAATCTCAGGAGGTTGTCTTCCGCAAGCTGAACTCCTCT
GCAGCTGTGATCGAAGAGATGACGGGCGTAGGCATCGTGCGGGTGGTGCAGAAGCTCTGT
GCTGGTCTTGACTGCCCGTTGCACTTCTGCGATGAGGTCATCTCCTTGGATAAAACTGTT
ATGTCCACACACAGCACGTCCCGCCTCAGTTTCGTCACCCCAAAACACCAGAGAACCGCA
ACCTGCCAGTGTGACGGTGGTAAATGTCCTGTGTTGAACAACCTGTGTGAGAACAGCCCC
TGCCCAGAGGGCATGGACTGTGTAGCAGATCCTGTAGATACTGTGTACAGCTGTGTGTGT
CCTGAAGGCAAAAAGGGCAAATGTTCAGATGGCCACTCATTGACATTTAGCGGAAGTGGT
TATGTGAAGTACCGCCTGATGGAGAATGAGAACAAGGAGCTAATGAAACTATCTCTGAGG
CTCAGGACTTTCTCCAGCCATGCTACTGTCATGTATGCAAAAGGGACTGACTACAGCATC
CTTGAGATAGTAAACGGCCGTCTTCAGTACAAGTTTGACTGCGGCAGTGGTCCTGGCCTA
GTGTCTGTCCACAGCGCTCAAGTTAACGATGGGGAGTGGCATTCTGTCTCTCTGGAGGTA
GATGGTAACTATGCTAAACTGGTTCTAGACCGGGTGCACGCCGCCTCTGGTACAGCACCG
GGCACTCTGCGTACCTTAAACCTCGACAACAGCATTTACTTTGGTGGTCACGTACGCCAG
CACAGCTCCCCTCGCCTTGGTCGCAGCCTACCTATTACTAATGGGCTCCGTGGCTGCATG
GAGGCCATCGCACTGAATGGCCAGGAGCTACCACTCAACACCAAAGCTCACCGGGCCCA-
-----------------CGCTGTGCTGGAGGACATTGTGGATGTGGCACCAGGCTGTGCA
CTCACACCTGATGAGAGTTGTTCGAGCAACCCCTGCACCAACGGAGGAAGCTGCACCTCA
CTGCCTAATGGAGGCTACTTCTGCAAGTGTCCTGCCTCTTTCATGGGCACACACTGTGAG
ATTGCCATAAGTCCTTGTGCATCCAACCCCTGCCTGTACGGTGGCACCTGTGTTCCTCGT
GCAGATGACTTCTACTGCCAGTGCAGAGGGCAGTACTCAGGACAGAGGTGCCAGTTAGGG
CCATACTGCAGAGACAATCCCTGTAAAAACAGTGGAAAGTGTATCGACAGTCTGGATGGT
CCTGTATGTGAATGTGAACCTGGTTTCCAGGGAGACAGGTGTTTGAGTGATGTAGATGAG
TGCATCAAGAACCCCTGCGCCAACGGAGGACTGTGCCAGAACACGTACGGCTCCTTCAAG
TGTAACTGTTCGCTGGGTTTCAGCGGGCACTTGTGTGAACAACGTGCAGCTGTCCGAAAT
GACTTTGTCTCCACCTCCTGGAACATCGGCTTGGAAGAGGTGATCGGCATTGTGGTCTTT
GTGTCTAGCATCTTCATCCTGGTCCTCCTCTTCATCATAATCCGCAAGAAAGCCTGCCG-
--CAGCAAGTCAAAGATAGATGACGATGACAAACATCCTGGAAGTTCCAGCATGCCTCAC
TCCTTTCTCCAGCGACCTTACTTTGACTCCAAAATAAACAAGAACATCTACTCAGACATC
CCTCCTCAGGTGCCCGTGCGTCCCATCTCCTATACTCCTAGCATTCCAAGTGACTCACGG
AACAACTTGGACAGAAACTCATTTGAGGGCTCAGCCATCCCAGAGCACCCTGAGTTCACC
ACCTTCAACCCAGAATCTGTGCATGGACATCGCAAGACCGTGGCTGTGTGCAGCGTGGCG
CCCAATCTCCCGCCTCCACCTCCATCCAACTCTGTCTCTGACAGCGACTCCATCCAGAAG
CCAAACTGGGACTATGATTATGACACTAAAGTGGTGGACTTGGATCCATGCCTGACCAAG
AAGTCTGTGGAAGACACCGCCTGTCAGCCCTACAACACCAGAGGCAGCATGTCTGAGGTC
CAGTCCCTCAGCTCCTTTCAATCCGAGTCCTGTGATGACAACGGATATCACTGGGACACA
TCTGATTGGATGCCAAGTGTTCAACTTCCTGGAATACAGGAGTTTCCACATTATGAGGTT
GTGGAGTCACCCGCCCCTCTGTACAATGACCCGAGTGCCATCGACACAGATTACTATCCT
GGTGGCTTAGACATAGAGAGTGATTTCCCGCCACCGCCAGAGGACTTCCCTGCAAACGAT
GACCTGCCGCCGCCGCCTCTGCCAGAGTACAGCGACCGATGCGACACACTGCGACCCGTC
GGCAGAGATTTGGA------CACGTCTGG--------TTCAGGCAACTCCAGCGCAGTCC
GCCAGCGTCCGGCGCTGCCCCAGCTCTACAGCCTTAACCAGTATCTGCCGCATCACTCCT
ACCCAAGTGAAGGGGGCGACACTGAGGGACAGGGTGCTAACTCCACCTCTGCAAC-----
-CATTACCCCTGCTTCCACCATGGGCACTAGTGATTACAGAGGAGGCTATCCTTTAGGTT
GTAGTCGGGACTTTGACTCCTCAGCTCTGGACAACATGTCCATGTCTCTGTACACATCCA
CAGCCTCTTGCTCGGACATGTCGGCGTGCTGCGAGGAGTCTGAGGTGATGATAAGCGACT
ACGAGAGCGGTGATGAGGGCCACTTCGAACGGCTGGCCATCCCGGCGCTGGACTCCCAAC
AGCACACTGAAGTCTGA
>Sargocentron_rubrum_gill_6|017272|scaffold25959|m.33637
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------CCCAAATTTGTCGAACCACATTACCGGTTT
ACAGTTCCTGAAGACCTGCCTATTGGCACAGAGATTGATGTCATCCAAGCAGAGAGTGAA
CAACCAGTGGTTTACATCCTTGTTAAAGGCAACACTCCTGAGAGCAATGAGGATGAGGTT
TTTGTTGTGGACAGAGACACTGGGACTTTGAAGCTGGAGAAAAGCCTTGACCATGAAACT
ACCAAATGGTACCAGCTCACACTGCAAGCCCAGAGCAAATATGAGAATCATGAGATATTG
GCATCTGTGTATGTAAACATCCAGGTGAAAGACCTTAATGACAACAAGCCTGTCTTTGAG
TCAGACCCTTATGAAGCAGTCATTGTGGAAAACCTTCCAAGTGGCACAACGATGATTCAA
GTCAAAGCCACTGACCAAGACTCTGGCACCAATGGTCAAGTAGTTTACAGCCTTGATCCT
AAACAGACCTCAAACGACATCTTTGAGCTGTTTGCCATCAATAGTGAAACTGGATGGGTG
ACCACCTTGAAAGAGCTAGACCGTGAGAAGATGAGCGAATATACAATTGCCATCCTGGCA
ACAGACCAGGGAGACGGAGTCCAACATGTTACTGGCACCAAAGTGGAGGTAACAGTTGCT
GATGTGAATGACAACCCACCCCGCTTCACTGCAGAGATCTATAAGGGCACTGTTAGTGAG
GATGACCCTCCACCTAGTGGGGTCATTGCTATCCTGAGCACCACGGATGCTGATTCTGAG
GACATCAATAAACAAGTGAACTACTTCATCACAGGAGGAGACCCACTCGGCCAATTTGCT
ATTGAGCACATTCAGAACGAGTGGAAAGTCTCTGTCAGGAAGCCTTTGGACCGTGAGGAG
AAGGACAATTACCTCCTTAACATTACTGCCACTGATGGCATCTTTGCTGCCAAAGCCATT
GTGGAGGTCAAGGTTCTCGATGCCAACGACAACAACCCTGTATGCGAAAAGTCCCTATAT
AGTGAAAGTGTTCCAGAAGATTCCCCTGCTGGCAGGCTGATCTTGCAGGTCTCTGCCACG
GATGCCGACATCCGCTCGAATGCTCAAATCTCCTATGAGCTCCAGGGAGCTGGAGCAGAG
TTGTTCACCATCGACTCAGATACAGGAGAATTGAAAACCCTGCAACCCCTGGACCGAGAA
GAGCGAGATGAGTACAGGTTCAAAGTGCGAGCAGTGGATGGAGGTGGGCGGTATTGCGAG
GCTGACATCCAGATCACAGTGGAGGACGTCAATGACAACGTGCCACAGTTCACCTCTGAT
CCCTACACCATCACAGTCTTTGAGAACACAGAGATCGGCACATTTGTGGCAAAACTGCTG
GCAAATGATGTTGACACTGGTCTTAACAGCGACATTCTTTACTCGCTGGCCGACTCTGCC
GATGGGTATTTCTCAGTGGACGAGCACACCGGCGTAATCAGCCTGGAGCGGCCCCTCGAC
CGCGAGGTGCAGGCGGTGTACGAGCTGAAGGCCCGCGCCACCGACCAGGGCTCGCCGCGT
---CTCTCCTCGCTGTGCCAGGTCGTGGTGTCGGTGCTGGACATCAACGACAACCCACCA
GTGTTTGAGCACCGTGAATACATGGCCACCGTGCCCGAGGATGTGGGCGTCGGGACACAA
GTGCTCAGTGTGCAGGCGGCCAGCAGGGACATAGAGGCCAACGGAGAGATCTCCTACAGC
ATCATCAGTGGGAACGAGCACGGCATGTTCAGCGTGGACCACCGCACTGGTGACATCTTC
GTGATTGAACCCCTGGACTACGAGGTGTCCCATGAGTACTACCTAACGGTAGAGGCCACA
GATGGTGGCTCTCCACCGCTCAGTGACATGGCAACTGTGAACATCAACCTGACCGACGTC
AACGACAACAGACCCGTCTTCAGCCAGGAGACCTACACAGCTGTAGTCAGTGAGGACGCC
GAGCTGGGCAAGACCGTGCTGGCGGTCATGGCCGAGGACGCCGATGGGCCGTCTTACAAT
CATGTGCGGTACTCCATAGTGGATGGTAACCAAGGCAGCCCCTTCACCATCGATCCGGTC
AGAGGAGAGCTCAAAGTCGCTCGCCAGCTGGACAGAGAGAGAACATCAGGGTACACGCTG
ATGGTGGTAGCCTCAGACAACGGGACACCTCCGCATTCCAGCAGCGCCACGGTCAACATC
GACGTGTCGGACGTCAACGACAACCCGCCGCTTTTCTCCCAGGCCAACTACAGCCTTATC
ATCCAGGAGAATCGACCAGCAGGCACCAGTGTCCTTCAGCTCACTGTGACTGATAGAGAT
GCTACCCATAATGGCCCGCCCTTCACCTTTGCCATTGTGGATGGGAATGAGGGTGACGCT
TTCCAGATCGATCAACAGGGGGTGCTCGTGGCAGTGGGGCTGCTGTATAGGAAAAGTAAA
GAACACTACCTACTTGAAGCACAGGTGTCAGACAGCGGAAAACCTCCCCTCCTCTCCACC
GCCTTCATCAGCGTGCGTATCATCGAGGAGAGCGTCTACCCTCCCGCCATCCTTCCTCTG
GACATCTTCATCTCCACTTCTGGTGACGAATACCCCGGAGGCGTCGTGGGCAAGATCCAC
GCCACCGACCAAGACATCTACGACACTCTGAGCTACAGCCTCGCCCCCTCTTCCTCCTCG
TCCTCCTCCACCGCCGACGGAAGCGACGCCTTGTTTACGGTCTCGGCCTCCGATGGTAAA
GTGATCGCCCAGCGGCCGCTCGACGTGGGCCACTATCCCCTCAACGTGACGGTGACCGAC
GGGCGCTTCATCACGGCCGCCGACGTCACCGTGCACGTTCGGCAGGCAGCTCAGCAGGCC
CTGGACAACTCCATCGCTGTGCGCTTCGCCAATATCGCACCTGAGGAGTTTATCGGAGAC
TACTGGCGTAACTTCCAGCGGGCGCTGAGAAACATTGCGGGGGTCCGGAGGAGTGAGGTT
CAGCTGGTGAGCCTGCAGCCATCTGA---GCAAGGAGATCTGGACGTCCTGCTGGCACTA
GAGAGATCTGGCAGCCCATACCAACCCCAGGAGGTTGTCTTCCGTAAGTTGAACTCCTCT
GCAGCCGTCATCGAGGAGATGACAGGGGTCCGGATTGTGCGAGTGGTCAAGAAGCTGTGT
GCCGGCCTGGACTGCCCGCTGCGCTTCTGCGATGAGGTCATCTCCCTGGACAAGACCGCC
ATGTCCACGTACAGCACGGCCCGCCTCAGCTTTGTTACCCCACGACACGTGAGAACTGCC
ACCTGCCAGTGTGAAGGTGGCAGATGTCCTCTGTTGAACAAGCTGTGTGAAAACAACCCC
TGTCCTGAGGGAATGGAGTGTGTTGCAGACCTGAAAGATGCCATGTATAGGTGTGTGTGT
CCAGAGGGCGCAAAGGGCAAGTGCACAGATGGCCACTCGTTGACATTCGGCGGCAGCGGC
TACGTGAAATACCGTCTGATGGAGAATGAGAACAAGGAGCTGATGAAACTGTCTCTGAGA
CTCAGGACTTTCTCCAGCCATGCTACTGTCATGTATGCTAAAGGAACAGACTACAGTATC
CTCGAGATTGTGAACGGTCGTCTGCAGTACAAATTTGACTGTGGCAGCGGCCCCGGCCTC
GTGTCGGTCCACAGCACGCAGGTCAACGACGGCGAGTGGCACACCGTCTCACTGGAGGTG
GACGGCAACTACGCTAAGCTGGTGCTGGACCGGGTGCACGCCGCCTCGGGTACAGCGCCG
GGCACCCTGCGTACCCTCAACCTCGACAACAGCATCTACTTCGGCGGCCACGTACGGCAG
CACGCCTCTGCGCGCCTCGGCCGCAGCCTGCCCGTCACCAACGGGCTCCGCGGCTGCGTG
GAGGCCATCAACCTCAATGGCCAAGAGCTGCCTCTCAACACCAAGGCTCACCGAGTCCA-
-----------------TGCTGTGCTGGAGGACATGGTGGACGTGGCTCCAGGCTGCGCC
CTCATGCCTGCTGAGAGCTGCTCCAGCAACCCCTGCATGAATGGAGGGAGCTGCTCCTCT
CTGCCTAATGGAGGCTACTTCTGTAAGTGCAGCGCCTCCTTCATGGGCACACACTGTGAG
ATTGGCATCAGCCCTTGTGCCTCCAACCCCTGCCTGTACGGGGGGACCTGTGTGCCCCGG
GCCGACGACTTCTACTGCCAGTGCAGAGGGCAGTACTCAGGACAAAGGTGCCAGCTGGGG
CCGTACTGCAGAGACAACCCCTGTAAAAACAGCGGGAAGTGTATTGACAGTCTGGACGGT
CCAGTATGCGAGTGTGAAGCCGGCTTTCAGGGAGACAGGTGCCTCAGTGATGTTGATGAG
TGTGTCAAGAACCCCTGTGCCAACGGCGGCCTGTGCCAGAACACATACGGCTCCTACAAG
TGTAACTGCTCTCTGGGCTTCAGTGGACAGATGTGTGAACTCCGCGCTGAGGTTCGCAAT
GAATTCGTCTCCACCTCTTGGAACATCGGCCTGGAGGAGGTGATTGGAATTGTGGTCTTC
GTATCCAGCATCTTCTTCCTGGTCCTCCTCTTCATCATCATCCGCAAGAGGGTGTGTC--
----GCAAGTCGAAGGCTGACAACGAAGACAAACACCCCGGAGGCTCAAATGTGCCGCAC
TCCTTCCTCCAGAGGCCTTACTTTGACGCCAAGCTCAGCAAGAACATTTATTCAGACATC
CCGCCTCAGGTCCCCGTGCGGCCCATCTCCTACACCCCCAGCATTCCGAGCGACTCACGG
AACAACCTGGATCGAAACTCCTTTGAGGGCTCAGCCATCCCGGAGCACCCGGAGTTCAGC
ACCTTCAACCCCGACTCTGTGCACGGGCACCGCAAAACTGTCGCCGTGTGTAGCGTAGCG
CCCAATCTCCCGCCTCCCCCTCCTTCCAACTCGGTCTCGGATAGCGACTCCATCCAGAAG
CCCAACTGGGACTATGATTATGACGCTAAAGTCGTGGACTTGGACCCGTGTCTGACCAAG
AAGCCTGTTGAGGACAGCGCCTGCCACCCCTACAACACCAGGGGGAGCATGTCTGAGGTC
CAGTCCCTCAGCTCCTTCCAGTCAGAGTCCTGTGATGATAACGGATATCACTGGGACACA
TCTGATTGGATGCCAAGTGTTCAACTTCCTGGAATCCAGGAATTCCCACAGTATGAGGTT
GTGGAGTCCCCCACCCCCCTGTACAGCGACCCGAGCGCCATCGATACCGACTACTATCCC
GGTGGCTTTGACATCGAGAGCGATTTCCCACCGCCGCCAGAAGACTTCCCCGCAAACGAG
GACCTGCCGCCACCGCCTCTGCCAGAGTACGCTGACCGCTACGACACCCTGCGGCCCCTG
GGCAGGGACTTGGATCCCGCCCCCGCCAG--------TCCAGGGGGCTCGGCGGGGGTGC
GCCAGCGCCCGGCCCTGCCCCAGCTCTACAGCCTTAACCAGTATCTCCCGCAGCACTCCT
ACCCTGGCGAGGGGGGCGACGCCGAGGGCCAGGGCGCTAGTGCCACTTCCACCACCGCCA
ACACCACCCCGGCTTCCACCATGGGCACCAGCGGCTACAGAGGGGGCTTCCCCTTAGGTT
ACAGCCGGGACTTTGACACCCCCGCTCTGGACAACATGTCTATGTCTCTGTACACGTCCA
CAGCCTCTTGCTCGGACATGTCGGCGTGCTGTGAGGAGTCCGAGGTGATGATGAGCGACT
ACGAGAGCGGCGACGAGGGTCACTTTGAGCGGCTGGCCATACCAGCGCTGGACTCCCAAC
AGCACACTGAAGTCTGA
>Scleropages_formosus_red_gill|021209|scaffold33572|m.43515
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------GAGTTCTCCATCGTC
ACTGGAAACGAGGACCAAAACTTTGCCATTGACCGGGAAACTGGTGCAATTTTTATTTCA
AATCATCGCAAGGTGCAAATGGAATCGAGTTATGATCTGGAAGTGTCTGTGTCTGACGGA
GTGTTCAGAAGCTCAGTTGTGGTCACGATTGTAGTCACTGGTGCCAACTTTCACAGCCCT
TCTTTTACTCAGATGGAATATGTGGTAGAACTTGTGGAGAATTCCCCAGTTGGCACACTG
ATTGCAGAAACCAAAGCCATTGACCCCGACTCGGGCACCTATGGACAGGTGTCATACTAC
ATTGTGAATGACTTTGCCAGAGACAAATTTTCTGTTAACGACAACGGAGAGGTTTATGCT
CTTGAGGTCCTAGACCGCGAGAACCTAAAAGAGAAGGTTATCTCTGTAAGTTTGATGGCT
AAAGATGGGGGTGGAAAGGTGGGATTTTGCATTGTTAATGTCGTCCTAACTGACATCAAC
GATAATGCCCCACAATTTAGGGCAGCAGAATACAGAGCAAACGTTGCATCAGATGTTCTA
AGGGGAACCACAGTGTTGAGGGTCGCAGCATCTGACATGGATGAAGGCAGCAATGCTGAC
ATTACCTACACCATTGAGGCCGAGGTAGAAAATGTAGTGGAAAACTTTGAGATCCATCCC
TACAGCGGTGCCATTGTAACGAGGGAAAGCCTCATTGGACTTGAAAATGACCTTTACACA
TTCTATGTCAGGGCGAAGGATGCAGGGAATCCACCAAAACAGTCTGTTGTACCTGTGTAC
ATCCAAATACTGGCTCCTGAAGTTCCTGTGCCAAAGTTTGTTGAACCTCACTATAGGTTT
GCATTAGCTGAAGACCTGTCAGTGGGGTCAGAGATTGATGTTATTCAAGCAGAGAGTGAA
CAACCTGTTGTGTATAGCCTTGTCAGAGGAAACACTCCTGAGAGCAATCAGGATGAGGTT
TTTGTTGTTGACCGAGACACTGGCAGTCTGAAACTGGAGAAGAACCTTGACCATGAAACG
ACCAAGTGGTACCAGCTCACATTGCTGGCACAAAGCATCCACGAAGGCATTGAAACTGTG
TCCTCTGTGGACATTAGCATTCAGGTGAAGGACATCAATGACAATACCCCCTTCTTTGAG
TCCAACCCTTACAAGGCAATTGTGGTGGAGAACCTGCCAGGGGGCACCCCAGTGATCCAG
GTGAAGGCCAACGATCGGGACTCTGGTACAAACGGACAAGTTGTTTACAGCCTGGACCAG
AAACAGGAGACTGAAGAAATCGCAGAGCTGTTTGCCATTAATGGCGAGAATGGCTGGCTG
ACCACCCTGAAAGAGCTGGACCGGGAGAGGCGGAGCACATACACCGTGGCCCTAATAGCC
ACCGACAGAGGAGAGAAGAGACAGCTGATTGCCAGCACCAAAGTGGAGGTGACTGTGGCT
GACGTTAATGACAACCCACCGCGTTTTACAGCCAAGGTCTATAAAGGTACCGTGAGTGAA
GATGATCCCCCACCCAGCGGAGTCATTGCCATTCTCAGCACCACTGATGACGATACAGAG
GACATGAACAAGCAAGTTAGTTACTTTATAACAGGAGGGGATCCGCTGGGACAGTTTGCC
GTCGAGCATGTCCAGAGGGAGTGGAAGGTGTCTGTCAGGAAGCCCCTGGACCGGGAGCAG
AAGGACCATTATCTGCTGAACATCACTGCCTCTGATGGCACTTTCATGGCCAAGGCTGTG
GTGGAAGTGAAGGTACTGGACGCCAATGATAACAGCCCTGTTTGTAAGAAGATGCGGTAT
GAGGAGTCCGTCTCTGAGGATGCCTCAGCAGGCAGGCTGGTGCTGCAAGTATCTGCCACA
GATGCAGACATTCGCTCCAATGGACAGATCTCCTATGAGCTCAGCGGATCTGGGTCTGAG
AAATTCAGCATGGACTCGGAAACAGGCGAGCTGAGGACTCTGCTGCCCCTGGACCGTGAA
CAAGAGGAGGACTACCGTCTTGAGGTGCGGGCACTGGACGGCGGGGGCCGCTACTGCCAG
GCCAGTGTACACATAACGGTGGAAGATGTGAACGATAACGCTCCGCAGTTTGCCTCTGAG
TCCTACAGTGTCACAGTCTTCGAAAACACGGAGGTGGGCACACCGGTGGCACGGCTACAG
GCCTCAGACCTTGACCTGGGTGTGAACGGAGACGTCCTGTACATGTTAGAGGACTCCGCC
AATGGCTACTTCTCCATTGATGAGCGCTCAGGCCTTGTCCGACTCCAGAAGTCACTGGAC
AGGGAGCTGCAGGCAGAGTATGAGTTGACGGCCCGGGCCACCGACCAGGGGACTCCACAG
AGGATGTCCTCAGTCTGCCGGGTAGCAGTGTCCGTACTGGACATCAATGACAACCCACCG
GTGTTTGAACGTCATGAGTACGTTGCCACCGTGCCAGAAAACATTGCCGTGGGAACCCAG
ATCCTGCGTGTCTTTGCTGCTAGCAGGGATGTTGAGGCCAATGGCGAGATCTCCTATTCC
ATCGTTAGTGGCAACGAGCACGGGATGTTCCGAGTAGACTCCCAGACTGGAGACTTATTT
GTGATCGAACCATTGGACTACGAGATCTCCCATGAATACTACTTGACTGTGGAAGCCACA
GATGGTGGTGTGCCTCCTCTGAGTGACCTGGCTACCATCAGCATCAACCTGACAGATATT
AACGACAACAGCCCTGTGTTCAGTCAGGATGTCTACTCGACTGTGGTCAGCGAAGACTCC
GAGCTGGGAAAGACCATAATGGCACTTGTAGCAGAGGACATCGATGGACCGTCACACAAC
CGCGTCCGGTACGCCATCATGGGTGGAAACGAGGGTAGCCCCTTCACTGTGGACGCTGCC
ACCGGTGTGCTGAAAGTGGCTCGACACTTGGATAGAGAGAAGATATCTGGATACACACTG
ACTGTGCAGGCCACCGACAATGGGAGTCCACCTAAATCCAGCAGCGCCACCATCAACATT
GACGTGTCTGATGTGAACGACAATGCCCCGGTATTCTCCCATGCCAACTACAGCATTATC
ATACAGGAGAACTGCCCCCTGGGAACCAGCGTGCTTCAGCTCAGCGTGACAGACAAGGAT
GCCTCCCACAACGGACCTCCCTTCTCTTTCGATATCATTGATGGAAATACTGGGAGCACC
TTCCAGATCGACCCACAGGGGTCGCTGATAGTGGTTGGCCACTTGAACCGTTGGGCTAAA
GAGCACTATCTGCTTCACGCCCAGGTCTCTGACAGCGGGAGACCCCAGCTGCAGTCGTCC
ACCTTCATTAGTGTCAGGTTGATCGAGGAGAGCATCCATCCACCATCCGTACTTCCTCTG
GATGTTTTCATCACCACTCCTGGCGAGGAATATGCTGGTGGGGTCTTGGGAAAGGTCCAT
GCCACTGACCAGGATGTATACGACACGCTGACCTACAACCTGGCATCTCAGCCCAC----
-----------------------TGGCGCCACTTTCTCTGTGTCTCCTGGCGACGGCAAG
CTGGTGGCTCGCGGGCCACTGGACCCCGGCCACTACCAGCTCAACGTGACCGTCACAGAC
GGCCGCTTCACGGCCGTTGTTGATGTGGGCGTGCACGTGCGGCAGGTGGGACGAGTGGCA
CTAGATGACTCGGTTGCTGTGCGCTTCACCACAATCACACCTGAGGAGTTTATTGGCGAC
TACTGGCGCAACTTTCAGCGTGCATTGCGCAACATGGCTGGTGTCCGGCGTGCAGATGTA
CAGATGGTCAGCCTTCAGCCATCAGAGACGCCAGGGGACCTGGACGTGCTGCTGACCCTG
GAGAAGTCAGGTGGACCCTACCCCTCGCCTGAAGCCCTTTTCCGCAAGCTCAACACCTCG
GTGGCTACCATTGAGGAGATGATTGGTGTGCGAATTGCAAGAGTCTACAGAAAGCTGTGT
GCTGGGCTAGACTGCCCACTTCGTTTCTGCCAGGAGACTGTCACCCTGGACCGAGCTGCC
GTCTCCACCTACAGCACAGCCCGGCTCAGCTTCATAACGCCTCGGCACAAGCGCTCACCC
ATGTGCCTCTGCAAAGGTGAAGAGTGTCCCACCTGGAACACGGTGTGTGAAGGAGACCCC
TGTCCACAAGGTACCGAGTGTGTGGCTGACCCCAAGAGGGTGGTATACACCTGCATGTGC
CCAAATGGCGAACAAGGCGGGTGCTCAGAGGGACCTTCACTGACTTTCAGCGGGAATGGC
TACATGAAGTACCGCCTGCTAGAGAATGAGAACAAAGAGGAAATGAAGCTGTCGCTTCGC
CTCAGGACCTTCTCCAGCCACGGCACCATCATGTATGCTAAAGGGACTGACTACAGCATC
CTGGAGATTGTGAACGGCCGCCTGCAGTACAAGTTTGACTGTGGCAGTGGCCCTGGCATG
GTGTCTGTGCACAGTGCCCAGGTGAACGATGGCGAGTGGCACAGTGTTTCGCTTGAGGTG
GACGGCAACTATGCCCGGCTCATGCTGGACCGGCTGCATGCAGCCTCAGGCACTGCTCCA
GGCACACTGCGCACTCTCAACCTTGACAGTCGCTTGTTTCTGGGTGGCCATGCCCGCCAG
CACGCTCGGGTACTCCCAGGAC---------------CTGGAGCGTTCCGGGGCTGTTTG
GCTGCCGTTCGCCTCAATGGACAGGAACTGCCACT---------GGTCCACCAGGTCCAG
GCTCGAACTCACGGTCCCGCCATCGTGGAGGAGGCAGTGGATGTGACTCCTGGCTGTGCA
GTCCTGGAGGCTCAGGCCTGCTCCAGCAACCCCTGCACCAATGGGGGCATTTGCTCCTCT
CTGCCTGGAGGTGGTTTCTTCTGCAAGTGCAGCGGTTCCTTCAGTGGGACCCGCTGTGAG
CTGAGCACCAACCCCTGTGCCTCCAACCCCTGCCTCTATGGTGGGACCTGTCTGTCTCGG
GGCCACGACTTCCACTGCCAGTGCCGGGGCCAGTACTCAGGGCAGCGGTGTCAGCTGGGT
CCCTACTGCAAGGACAACCCTTGCCAGAATAGTGGCAGGTGCATCGACAGCCTGGATGGA
CCTGTTTGCGAGTGCGAGCCCGGCTTCCAAGGGGACAGATGCCTGGCTGACGTGGATGAG
TGCGTACAGAACCCTTGCACCAACGGGGCACGCTGCCACAATTCTTACGGCTCTTATAGC
TGCAATTGCACTGCAGGCTTTGGCGGGCAACTCTGTGAGCTGGGGTCAGAGGTCCGCAAT
GAGCTGGTGTCCACGCCTTGGAACATTGGCCTGGAAGAAGTAGTGGGCATCGTCGTCTTC
CTGGCAGGTGTCTTCCTCCTCGCTCTGCTGTTTGTGGCTGTGCGGCGGCGGGTCTGTAGG
CACAGGAAGCAGGAGCCTGAAGATGCTGGAAAGC---------GTTGCGGTGCCAGCCAG
CCTTTCCTGCACAGGCCCTAC---------------------------TACCCGGACGTG
CCTCCGCAGGTGCCCGTACGGCCCGTATCCTACACTCCCAGCATCCCCAGTGACTCACGG
AACAACCTGGACCGTAACTCTTTTGAGGGCTCAGCCATCCCCGAGCACCCCGAGTTCAGC
ACGTTCAATCCCGAGCCGGTTCACGGACACCGCAAGGCCGTGGCAGTGTGCAGTGTGGCA
CCCAACCTGCCGCCCCCGCCACCATCCAACTCCGTCTCGGACAGTGACTCCATCCAGAAG
CCCACCTGGGACTATGACTATGATGCCAAAGTGGTGGACCTGGACCCTTGCCTTGCTAAG
GAGGCAGTACAGGAAAGTGCCTGCCACCCCTACAATACCCGCGGCAGCCTTTCTGAGGTT
CAGTCGCTGAGCTCCTTCCAGTCCGAGTCCTGTGACGATAACGGCTACCACTGGGACACA
TCGGATTGGATGCCAAGTGTTCAACTTCCTGGAATCCAGGAATACCCACAGTATGAGATA
GTGGAGGCCCCCGTACCGCTGTACAGCGACCTCGACGCCATTGACACCGACTACTACCCC
GGAGGCTATGACATTGAAAGCGACTTCCCACCACCACCTGACGATTTTCCTGTCCAAGAG
GAGCTGCCCCCACTGCCTGAGCTGCAGCACAGTGACGGTTACGGGACATCACGGGCCA--
-----------------CTCCCCCACCAGCATCCAGCCCCGGATCATCTTCACGCGGCCG
ACCACCGCACGACACC-------TACTACAGCCTCGGGGAGTACCTGCCACGGCACCGCT
ACCC--------------------------------------------------------
----------------------------------------AACGGACCTTCCCGAGGGTT
AC---------------------------GGCAGCATGCCGCTGTCGCTGTACACCTCGG
CGGCCTCCTGCTCCGATGTGTCGGCCTGCTGCGAGGAGTCTGAGGTCATGATGAGCGAGT
ATGAAAGTGGTGATGAGG-----------CAGCCCGCT-TCCATGCCCTGGACTGCCAGC
AGCACACAGAAGTCTGA
>Synodus_sp._gill_5|020202|scaffold25662|m.36028
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------ATGATAACCCCCCTGTGTTCCTGTCAAAGTCATACAATGCC
ACCATTTCTGAGGCTGCAGTCATTGGAACGTCTGTTCTGCAAGTGGAAGCCAAAGATTCT
GACACTGGAAACAATAAAGCCTTGTTCTATCAGCTG------------------------
--NNNNNNCACAATTGACCGTGACACAGGGATCATTTGGACCGCTCAAGTGCTAGATCAC
GAGGAAACCCAACAGCACGATTTAAAGATCTCTGTTGTGGATGGAGGAGTACCAGCCCTG
TCAAGTGACATTACAGTTACCATAGCGATCACTGACCTGAATGATAATGCCCCAGTGTTT
ACAGAGAATGTTTATGAGGCTACAGTCGGTGAATTAGCCCCTCGGGGCTACTTTCTGATT
CAAGTACAGGCATCTGACGCTGATAGTTCGGACTCAGAGAAGTTACAGTTTTCCATTCTC
TCAGGCAATGACGACCAGAATTTTGCTATGGACAAAAACACTGGTGCTATTGTAATCTCC
AACCACCGCAGGCCACAAATGCAACCTCAGTACAACCTCACTGTTTCAGTTTCAGACGGT
GTGTTTAGGAGCTCAGCCCTTGTCAAAGTTACAGTAATCGGTGCCAATTTCCACAACCCC
ACCTTTCCTCAGATGGACTATGTAGTGGAGCTTGTTGAGAACTCACCTGTTGGCACCTTG
ATTGCAGAGGCTCAAGCCACTGATGACGATGAGGGGATGTATGGGCAGCTAACATACCAT
ATTATCAATGACTTTGCAAGAGACAAGTTCTCTGTGAATGAAAATGGACAGATTTACACT
CTAGAGAGTCTTGATCGTGAAAATGCCATTGAAAAGGTTATCCCCATTTCTCTAATTGCA
AAAGATGGCGGTGGAAAAGTAGGCTTCTGTATAATTAATGTAATTCTAACAGATGTAAAT
GACAATGCCCCACAGTTCAAAGCTGTTGAGTACAAAGTCACTATTGCATCTGATGCACCA
AGGGGAACAAGCGTTGTGAAAGTCGCTGCCTCAGATATGGATGAAGGAAGCAATGCTGAC
ATCACATATGCTTTTGAGACAGATGTTGACAACGTGGAAGAGAACTTTGAAATTCATCCC
CTCACTGGGGTCATTGTCACCAAAGAAAGTCTCATCGGTCTGGAAAATGAGTTGTATGCC
TTCTATGTTAGGGCAATGGATGGTGGAAACCCATCCAAACAGTCTGTTGTCCAGGTTTAC
ATTCGGATCGTGGCACCAGAAGTACCTATTCCTAAATTTGTGGAGCCACAGTATCGCTAT
GCCATCGCTGAAGATCTGCCAATTGGCACAGAGATCGATGTCATCCAGGCAGACAGTGAG
CAGCCAGTAATTTACACCCTTGTGAAGGGAGACACTCCTGAAAGCAACCAGGATGAGATG
TTTGTTGTGGACAGGGATACAGGGGCCTTGAAACTGGAGAAAAGCCTTGATCACGAAACC
ACAAAATGGTACCAGCTCATACTGCTTGCCCAGACCCAGCATGAGAATTTTGAAATAGTG
GCATCTGTGCCTGTCAACATCCAGGTGAAGGACATCAATGATAACAAGCCTGTTTTTGAA
GCAGATCCCTATGAAGCTGTTGTGGTAGAGAATCTTCCAGGCGGTACATCAGTTATTCAA
GTCAAAGCCACCGACCAGGACTCTGGCACCAATGGACAAGTCATTTACAGCCTCGATCCA
AAGCAGACATCACAAGAGATCTCCGAATTGTTCGCCATCAATAGAGAAACTGGATGGGTT
ACCACCTTAAAGGAGCTCGACCGTGAGAAAATGGAAAGGTACACTATTTCAGTCCTTGCC
ACAGACAGAGGGGATGGGGTCCAACTTGTAACTGGCACCACCGTGGAGGTCACAGTGGCA
GATGTAAATGACAATCCACCTCGATTCACCGCCGAAATCTACAAGGGCACCGTGAGCGAG
GATGACCCCCCGCCGAGTGGCGTCATCGCCATCCTGAGCACGACTGACGCAGATTCCGAG
GACATTAACAAACAAGTGAACTACTTCATCACAGGAGGGGACCCGTTGGGGCAATTTGCC
ATCGAGCACATTCAGAACGAGTGGAAGGTCTCTGTCAGGAAGCCCTTGGACCGTGAGGAG
AGGGACAATTACCTGCTTACCATCACTGCCACCGACGGCATATTTGCTGCCAAAGCCACA
GTAGAGGTCAAGGTCCTGGACGCCAATGACAATAGCCCCGTGTGCGAGAAGTCCCTGTAC
AGCGAGAGCGTCCCTGAAAACTCTCCTGCCGGCAGGCTTATCCTGCAGGTCTCCGCCACA
GATGCTGACATCCGCTCAAATGCCCAGATCTCCTATGAGCTCCAGGGAACAGGAGCTGAG
CTGTTCACCATCAATACCGATACAGGGGAACTGAAGACCCTGCAGCCATTGGACAGGGAG
GAGCAGGAGGTGCACAGGTTCAAAGTGCGTGCGTTGGACGGGGGCGGGCGCTACTGCGAG
GCAGACGTCCACATCACGGTGGAAGATGTCAACGACAACGCGCCGCAGTTCACCTCCGAC
CCCTACACCATAACCGTCTTCGAGAACACGGAGATCGGCACCTACGTAGCGAAGCTGCTG
GCAACTGACTCAGACATCGGTTTAAACAGCAACGTCCTCTACACCCTCGCTGACTCGGCC
GACGGCTATTTCTCCGTGGACGAGCACACCGGCGTCGTGAGCCTGGAGCGACCCCTGGAC
CGCGAGGTGCAAGCGGTGTACGAGCTGAGGGCCCGCGCCACCGACCAGGGCTCACCGCGC
CGCCTGTCCTCCCTGTGCTCGGTGGTGATCTCGGTGCTGGACATCAACGACAACCCACCG
GTGTTCGAGCACCGGGAGTACGTGGCCACCGTGCCCGAGGACGTGGGCGTGGGGACGCAG
GTGCTGAGGGTGCAGGCGACCAGCAGGGACAGCGAGGCCAGCGGGGAAATCTCGTACGCC
ATCGTCAGCGGCAACGAGCACGGGATGTTCAGCGTTGACCCTCACACCGGTGACGTGTTT
GTGATCGAGGCGCTGGACTACGAGGTGTCACATGAGTACTACCTGACGCTGGAGGCCACA
GACGGGGGATCCCCGCCACTCAGCGACATGGCCACCGTCAACATCAACCTGACCGACGTC
AACGACAACAGCCCCGTCTTCAGCCAGGAGACCTTCACCGCCGTCGTGAGCGAGGATGCC
GAGCCGGGGAAGACTGTGCTGGTGGTCATCGCCGAGGATGCTGACGGGCCGTCCTACAAC
CACGTACGCTACTCCATCGTGGACGGTAACCAAGGCAGCCCGTTCGTCATCGATCCGCTG
AGGGGCGAGCTGAAAGTGGCCCGGCAGCTGGACAGGGAGCGGACCTCGGGCTACACTCTG
ATGGTGGTGGCCTCCGACAACGGGGTGCCTGGGCGTTCCAGCAGTGCCACCGTCAACATC
GATGTGTCGGATGTCAACGACAACCCGCCCCTGTTTTCCCAGGCTAATTACAGCCTCATC
ATCCAGGAGAACCGTCCTCCAGGAACCAGCATCCTCCAGCTTACCGTCACCGACCGGGAT
GCCACCCACAACGGGCCCCCTTTTGCCTTCGCCATTGTGGATGGGAACGAGGGCGACGCC
TTCCAGATCAACCAGCAGGGGGCTCTGGTGGCGGTGGGGGAACTGAGGAGGAGAGCCAAG
GAGCACTACATACTGCAGGCACAGGTGTCAGATAATGGGAAACCCCAGCTCCTCTCCACC
GCCTTCATCAGTGTCCGCATCATTGAGGAGAGCGTCTACCCACCGGCCATACTCCCCCTG
GACATCTTCGTCTCCACCACCGGGGACGAATATTCTGGAGGGGTCCTGGGCAAGATCCAT
GCCACCGACCAGGACATCTACGACACTTTGACCTACAGCCTCGCCCCTTCATCCTCCTCA
T---------CTGCGGAGGGCGACGACGCCTCCTTCACCGTCTCTGCCTCCGACGGAAAA
GTCATCGCTCAGCGCCCTCTGGACGTGGGCCACTACTTCCTCAATGTGACGGTGACGGAT
GGGCGCTTCACCACAGCGGCTGACGTTACCGTGCACGTCCGACAGGTGGCCCAGCAGGCA
CTGGACAACTCGATCGCGGTGCGTTTTGCCAGCATTGCGCCTGAGGAGTTCATCGGGGAA
CACTGGCGCAACTTCCAGCGGGCGCTGCGGAACATTGCCGGGGTGAGGAGGAGCGAGGTG
CAGCTGGTGAGCCTCCAGCCCGTGGA---GCAGGGGGACCTGGACGTGCTGCTGGCGTTG
GAGAGATCTGGCAGTCCCTACCAGCCCCAGGAGGTGGTTTTCCGCAAACTCAACTCctcc
acggcggtgattgaggagatgtCTGGAGTGAGGATTGTACAGGTGGTGAAGAAGCTGTGC
ACTGGCCTGGAATGCCCGCTACGCTACTGCGATGAGGTCATTACCCTGGATAAGGCGACC
ATGTCCACCTACAGCACTGCCCGCCTCAGCTTTGTCACACCACGTCACCTGCGCAACGCC
ACCTGCCAATGTGAAGGTGGCAAATGTCCCATGTTGAACAAGCTGTGTGAGACCAACCCC
TGTCCCGAGGGAATGGAGTGTGTGGCAGACAAGACCGATGCCAAGTATAACTGTGTGTGT
CCTGAGAGCAGGAAGACCAAGTGTTCCGATGGCCACTCATTGACCTTCAGCGGAAGCGGC
TATATACGATACAGGCTTATGGAGAATGAGAACAAGGAAGAGATGAAGCTGTCTCTGCGG
CTCAGGACCTTCTCCAGTCATGCGACCGTTATGTACGCCAAAGGCACTGACTACAGCATC
CTTGAGATCGTGAATGGTCGGCTTCAATACAAGTTTGACTGCGGCAGCGGGCCGGGCATC
GTGTCAGTGCACAGCACCCAGGTGAACGATGGCGAGTGGCACAGCATCTCGCTGGAGGTG
GACGGTAACTACGCCAAGCTGGTGCTGGACCGGTTGCACGCAGCGTCCGGAACAGCGCCG
GGGACTCTGCGGACCCTCAACCTGGACAACAGCATCTACTTCGGTGGACATGTGCGCCAG
CACCCCTCCCCTCGCCACGGGCGCAGCCTGCCCATCACCAATGGGCTGCGCGGGTGCCTA
GAGGCCATAACCTTCAACGGCCAGGAGCTGCCGCTCAACACCAAGGCCCGTCGAGCCCA-
-----------------CGCCGCGCTGGAGGAGATGGTGGATGTCAGCCCAGGCTGCGCC
CTGACGCTCGTGGAGAGCTGCTCCAGTAACCCTTGCACCAACGGAGGGAGCTGCTCCTCT
CTGCCCAACGGAGGCTATTTCTGCAAGTGCACAGCCTCATTCATGGGCACTCACTGTGAA
ATTGGCATCAGTCCCTGTGCCTCTAACCCTTGCCTTTATGGTGGTACCTGTGTGACCCGT
GGGGATGAGTTCTACTGCCAGTGCAGAGGGCAGTACTCAGGACAGAGGTGCCAGCTGGGA
CCATACTGTAGAGATAATCCCTGTAAAAACAGTGGCAAGTGCATTGACAGCCTGGATGGC
CCTGTATGCGAGTGTGACACAGGCTTCCAGGGAGACAGGTGCCTGAGTGATGTGGATGAG
TGTGTGAAGAACCCATGTGAAAACGGAGGCCAGTGCCAGAACACCTATGGTTCCTACAAA
TGTAACTGCTCCCTGGGCTTCAGTGGGCAGATCTGTGAGCTCCACGCCGGGGTGGAAAAC
GCCTTTGTCTCCACCTCCTGGAACATCGGCCTGGAGGAGGTTATCGGCATCGTGGTCTTC
GTGTCCAGCATTTTCCTCATGGTCCTTGTGTTCATCATCATCCGTAAGAGGGCGTGCCG-
--CAGTAAGGCCAAAGCTAACCGAGAAGACAAACAGCAGGGTGGTTCCAATGCTCCCCAC
TCCTTCCTCCAGAGGCCTTACTTCGATGCCAAGCTCAGTAAGAACATCTACTCGGACATC
CCACCCCAGGTCCCCGTGCGGCCCATCTCCTACACCCCGAGCATTCCCAGCGACTCGCGC
AACAACCTGGATCGAAATTCATTTGAGGGCTCTGCTATCCCTGAGCACCCTGAGTTCAGC
ACCTTTATCCCAGACTCTCTGCATGGGCACCGCAAGACTGTGGCCGTGTGCAGCGTAGCA
CCCAACCTGCCCCCTCCCCCGCCCTCCAACTCAGTCTCAGACAGTGATTCCATCCAGAAA
CCCAACTGGGACTATGACTATGATGCTAAGGTTGTGGACTTGGATCCATGCCTGACCAAG
AAGCCTGTCGAAGACAGTGCCTGCCACCCCTACAACACCAGAGGCAGCATGTCTGAGGTC
CAGTCCCTCAGCTCTTTCCAGTCAGAGTCCTGCGATGATAACGGATATCATTGGGACACA
TCTGATTGGATGCCAAGTGTTCAACTTCCTGGAATCCAGGAGTTCCCACAGTATGAGGTT
GTGGAGTCCCCGCCCCCCCTGTACAGTGACCCGAGCGCCATTGATACAGACTACTACCCT
GGTGGCTTCGACATTGAGAGTGATTTCCCACCACCCCCGGAAGACTTCCCGGCCAGTGAG
GACCTCCCCCCGCCACCGGTGCCAGAGTACGGTGATCGCTACGATACCCTGCGCCCTGTG
GGCAGGGATTTGGCAGCCGCTCCTGGGAG--------CCCGGTGAGCTCGCTCGGGGTGC
GCCAACGTCCGGCCTTGCCACAGCTCTTCAGCCTTAACCAGTATCTACCGCAGCACCCGT
ACCCAAGTGACGGGGGCGACACAGAGGGTCAGGGCACAAGCGTTGCCTCCAACACGCCAA
CCACCACCCCAGCCTCCACTATGGGCACCAGCGGCTATAGAGGGGCCTACCCTATGGGCT
ACAGTCGGGACTTTGAGGCCCCCGCCCTGGACAACATGTCAATGTCGCTATACACGTCCA
CAGCCTCCTGCTCTGACATGTCAGCGTGCTGCGAGGAGTCGGAGGTGATGATAAGTGATT
ATGAGAGCGGCGATGAAGGCCACTTTGAGCGGTTGGCAATACCGGCGCTGGACTCCCAAC
AACACACTGAAGTCTGA
