>Amblygaster_clupeoides|009832|TR20455|c0_g1_i1|m.38720
GGGGCAGATGGCTTTTGGGTTGGATCGGTACCAGAATGCCGCCCTTGCGTCTGCACCCCA
CCAGTTCTGAAGTCAGGAGCTGTGCTGGGTCGGGACCACAACTGCGGTGATCGAGTGCGG
TACCTTTGCGATGACGGGTATAGGACTCTGGGGCCCGTCGAGGCCATGTGTGAGAAAGGT
GGGATCTGGAACCCCGGGGTGCCCGTCTGCTCACGGGGCAGATGCCCACCGACGCCACCC
AATGTCCCAAACACAGTCATACAGGGCGGCAGTGCCATTCCTCCAGAGACTCTCACCTAC
GCGTGCATGCCAGGGTTTCAGCTCCAAGGCTATCCTCACATTACGTGTGAACGGGGCAAG
TGGACAGAGCCTCAGCTTACGTGTGAGCCAGTGTCCTGTGGAGCTCCCCCATACATCCCG
AACACCATAACTGTGGGAGATGCATTGACTTTTGGAAGCCATGTTCAATACAGGTGTTTG
GAGGGCTTCGAGTTGGCCACTCAGACCAACACGCTCTTCTGCCAGAGCGATGCCACCTGG
TCCAAGCACAGCGTGCGCTGTCGGCCAAAGCCCTGCCACCTCCCTGCCAACCTCACCCAC
CTGGTAGCCACAGGGGAACACCCAACGCCCTTAGGGAGCACCGTCACCCTGTCCTGCAAG
ACTGGATTCTACCTGGAGGGACCAAAGATTGCCAAATGTGAACTTGGAGGGATTTGGTCT
CCTGTTTTCTCCTCTAACTCCTGTCTGCCCATCACCTGCGGAGAGCCCCCCGCTATTCTC
CACGGCAGCATAGAGGGCAAAGGTCATGACTATGGCGATATGGTTATATACAGCTGTCTC
CCTGGTTTCATACTTAAGGGAGATTCTGTTTTGACGTGCCAGCGGGACCAAGTGTGGAGC
GGGACCTCTCCTCAGTGTCTCACCATCTCTTGTGGAAAGCCCCCAGAGGTTGAGGATGCC
GTTGCACATGTGATAGACAACACA------------GTCAGCTATGAATGCCATTCAGGG
CTGCGGTTAGTTGGCCCAAAGAATCTAACTTGTTTATCTGGTGGCCAATGGAGCTCCCCT
ATACCATCATGTGAAGCGAGCTCTGAAGGCTGTGAGGGTCCCGAGGAGCTGTTGAATGGG
AAGGTGCTGGATCACAGCCTGGCTAGTGGCCGTGCTCTGGGCTTCCGCTGCGATAAGGGC
TATGACCTACAGGGGGAGCCACTGGTCGTCTGCATGGGCAACGGCTCCTGGAGTGCGCCC
CTCCCTGTCTGCACACCCAAGTCCTGTCCCCCTCCCCCGGGCTGGTCTGAAATTAGTCCC
---AACGCCTCACAGGGTGACTTCCTGGTGGGGCAGACTGTGCCAGTCACCTGTCCTAAG
GGCCAACAAGCCAAGGGTA---------------CGGCCACCCTGACCTGCAGAACGGAC
CAGACATGGAGCCCCATCAATGCTGTCTGTGAAAGGGTGTCGTGTGGCCCCCCTCTCCAC
GTGGCCAACGGGGTGGTGCGGGGGGCGGTCTTCCAGTTTGGCGACTTGGCGGTGTACACG
TGCTTCTCTGGCTACGCCATGGAGGGTCGCAGCCGGAGCAGGTGCCTGGAGAACGGAACC
TGGACCCCTCCCCCCACCTGTCGAGCT
>Corydoras_julii_viscera_mixture_8|000405|C1187892|m.24142
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------GAAGTTT---CTAAAGGTTGTAATCGACCGGCTGGAATATTGAACGGG
AGGATGCAGGAACACAGTCTGTTTAGTGGAAAAGCATTGGAGTTTTTCTGTGATAAGGGA
TTTACTCTGCAGGGGGAGGCTGTTGTGATCTGCTCTGGAAATGGATCTTGGGGTTCAGCT
TTTCCAACCTGTACACCCAAGTCCTGCCCACCTCCTCCAGGATGGATAGGGAACAGCATC
---AACACCACCA------TGTTCCTAGTGGGTCAGACAGCACAGGTCAGCTGTCCTAAA
GGTCAGCAGGTCAAAGGTAATCAAGGAAAAGGCTCGGCT---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------
>Distichodus_sexfasciatus_gill_4|001319|C833621|m.46240
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------CCT
GTACCTTCCTGTCAGGCTC---CTGAAAGTTGCTTAAGACCTGAAGGACTGTTAAACGGG
AAGGTGCTGGAGCACGCTCTGGCCAGCGGGAGGGCGATGGAGTTTTTCTGTGATAAGGGC
TACTCTCTGCAGGGGGAGTCTCTTCTCATGTGCCTGGAAAACAACTCCTGGAGCTCATCT
TTTCCCACATGCACACCAAAGTCATGCCCACCTCCTCAGAGCTGGGCCAGGAACACTGCC
---AACACCGCAC------TCTTCCTCGTTGGGCAGACAGTCATGATCCGTTGTCCCAAA
GGACAGCAGGTCAAAGGTCAACCAGGCAAATACACTGCCACCATAACCTGCAGAAGTGAC
CAGACCTGGAGTCCAATCAGCACAGTCTGTGAGACGGTGTGTTCCACGCCATGTCTG---
------------------------------------------------------------
------------------------------------------------------------
---------------------------
>Lepidogalaxias_salamandroides_Head_2|009436|C542192|m.48958
GG----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----TGAGATGCGCTTCTCATGTGAGCCGGTCTCCTGTGGGACCCCCCCGGATGTTCCC
AACACTCGGATAAGTGGGGATACGTTCACCTTTGAGAGCCAAGTCCAATACAGGTGTGCG
GAAGGCTTTGAGTTGGCCACTGCGGCTGACTCGCTCACCTGCCTGAGCGACGGCACCTGG
TCCACGCGCGGCATCAGGTGCCAGCCCAGACCGTGCCGAGTCCCGGGCAACCTCACTCGC
GTCCTTGTGGCGGGGGGCAAATTAACCCTCGTGGGCGGCACCGTCACGCTCTCCTGCCAG
CCCGGCTTCCTCCTCCAGGGGGCATCGCTCTCGACGTGTGAGGTTGGTGGCAAATGGTTG
CCCCAGTTTACCTCAGACTCCTGTTTACCAGTCGTCTGTGTAAAGCCCCTTCCTCTTCTC
CATGGCAACGAGGAGATTGACAGTTCCAATTATGGGGGCATGGTGATGTACTCTTGTCTC
CCTGGATATGAAATGCAGGGAGATTCTGTACAGACATGTCAGGGCGATGGAACATGGAGT
GGTTCTCAACCCGTTTGTGTTGCTACGTCCTGTGGCCCACCTCCACCAGTCAAAAATGCA
GTCACTCAGGCAACGGGCGAAACGTACCACAGTAACGTCACCTATGTGTGCAACTCCGGG
TTACATTTGGTTGGCCCACAAAACCTCACTTGCCTGTCCAATGGGACGTGGAGCTTGCCC
ACACCAACTTGTGAAGCTG---CTGGAGGCTGTGACAGCCTGAAAGTCCTGCCTAATGGG
CGCGTGCAGGAGCACAGCCTGAACACCGGGCGAGCCCTTGCGTTCCAGTGTGATAAGGGC
CACACCCTGCTGGGGGACCCTCTGGTTGTGTGCATGGGAGACGGCTCCTGGAGTTCTCCC
TTCCCCGTTTGTGAGCCCAAGCCGTGCCCTCCTCCGCCCGGGTGGAGTGAGGGCGCC---
---AATGCTTCCCGGGCGCGGTTCGTCGTGGGGCAGGCAGTGCGGGTTGTCTGTCCCAAG
GGTCACCAGGCCAAGAGCT---------------CGGCCACCATCACCTGCAGGGCTGAC
CAGACATGGAGCTCCAGCAGCAGCGTGTGTGAGAGGGTCTCCTGCGGCCCTCCGCTCCAC
GTGACCAATGGGGTGGTGCGAGGCGCCGTCTTCCAGTTTGGCGATGTG------------
------------------------------------------------------------
---------------------------
>Melanotaenia_praecox_viscera_mixture_8|001346|C410380|m.26249
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------TGGAGCCTGCCA
GCACCTACATGTGAAGTGG---CCAGAGGCTGCGACAGCCTAAAACAGCTGTTGCATGGT
AAGGTGCTGGAGCACAGCCGGCACACTGGGCATGCTCTGGAGTTTCAGTGTGATAAAGGC
TACAGGCTGGTGGGAGATCAACTGGTGGTGTGTATGGGGGGCAACACCTGGAGCTCCACT
TTCCCCACCTGCCAACCGAAGTCGTGTCCACCTCCTCCAGGATGGAAGGTAGACAGTAGT
GGGAGTAGATCCCAGCAGGATTTTCATGTTGGACAGTCAGCTCGTGTTACCTGCCCAAAA
GGGCAGCAAATGAAAGGTA---------------GCGGCACCATCACCTGCAGGCCGGAC
CAGACCTGGAGCCCACTCAGCTCTGTGTGTGAA---------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------
>Pantodon_buncholzi_mixed|004032|C627424|m.35283
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------GTTGTTTACAGGTGTCTA
CCCGGGTACGAAATACAGGGTGATCCCGTACGCATTTGCCAGGCTGATAAGTCATGGAGC
GGTACTCACGCAGTGTGTGATGCTATTTCATGCGGGCCGCCCCCGCTGGTGGAGGGTGCA
GTTGCCGTGGCGACTGGTGATAAATACCAAAGCGTTGTAAGCTATGAGTGCAATACTGAC
CTCCAACTAACTGGTCCCCAGAACTTGACATGCTTGTCCCATGGATCATGGAGCCTACCG
ATACCAAAGTGCGAAGCTGTGCAGGCAAGCTGTGAAAACCCCAGCGAGCTTCTGAACGGG
AGGCTCCTGGTGCACAGCTTCTCCAATGGGCGCAGCATTGAGTTCCAGTGTGATAAAGGC
TACAGTCTACAAGGGGAACAACTGGTCCTCTGTTTGGCCAACGGATCGTGGGACGCTCCA
TTCCCCACGTGTGCACCCAAACCGTGCCCAACACCTGCGGGCCTGCTGGAGATCAGCGGC
---AACTCTTCCCAGCACAGTTATTTTGTGGGGCAGGCCGTGTCGGTCAACTGTCCGAAA
GGTTACCGGACACAGAGGA---------------GTGTGACCATCACCTGCCAGAGCGAC
CAGACGTGGAGCCCCCCGGGGGCCTTGTGTGAGAGGGTCTCCTGTGGGCCGCCCCTCCAC
GTGGCCAACGGAGTGGTGCGGGGC------------------------------------
------------------------------------------------------------
---------------------------
>Scleropages_formosus_red_gill|001983|C1236708|m.70367
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------CATCCTCTCTGTGAAGCTGTTTTCTGTGGGCCACCTCCGCTGGTGCAGGGGGCC
ATTGTCATAGAAACCAGCCAAACATACCAGAGCAATGTGACTTATGTGTGTGAGTCTGGA
CTCCGTCTGGTCGGCCCACAGAACCTCACTTGCCTGTCCAATGGAACGTGGAGCCTCCCA
GCCCCTGAGTGCAAGGCTG---TTCAGGGTTGCGAAGACCCAACGGAGCTGCAGAACGGG
CGCCTGCTGCTGCACAACTTTACGGCCGGACGCAGTGTGGAGTTCCAGTGTGACACGGGC
TACAATCTGCAGGGGGCAGCGCTCGTGCTCTGCCTTCCCAATGGCTCCTGGGACTCCCCG
TTCCCTACTTGCGCACCAAAACCCTGTCCTCCACCTCCTGGTCTGATCCACACTGGCACT
---GACACCGCCTCCCAG------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------
>Synodus_sp._gill_5|001395|C524113|m.41827
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------ACCTGGAGTCTGCCC
ACGCCTGCGTGTGAAGTGG---GCCAGAGCTGTGACAGTCCCAAGGAGGTGCAGAATGGG
AAAGTGTTGGAGCACAGCCTGAACTCAGGGCTGGCGGTGGAGTTCCAGTGCAGCAAAGGT
TTCACCTTGCTGGGGGATCCACTGGTGGTCTGTCTGGGAAACAATACCTGGAGCTCCTCC
TTCCCAACCTGCCAACCTAAATGGTGTCCAACTCCCCCGGGGTGGAGGCAAGGCAGTGGG
GGGAATGGTTCCCAGCAAGTCTTCTACGTGGGCCAGTCTGTCCCAGTCACCTGCCCCAAG
GGTCAACAGACCAAAGGCA---------------GTGGGACCATCACCTGTGGGCCAGAC
CTGACCTGGACCCCCATCAGCTCAGTGTGTGAG---------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------
