>Amblygaster_clupeoides|035966|TR63856|c4_g3_i2|m.85951
ATGGACCGACTTGGCAGCAAACTGTTGACAAAATTGAAACTGACAGATTCAGGGAGTGTA
AAATTTTCTAGTTCCAAAAAGAAGAATGAATTGGCAAACGCAAACAATAACAGCAACCGC
TGTAACA------------------------CCCCCTCTGGCATAGCCACTCATGGCACC
ACCACCACAAGTTCCAGTGATGTGGCC-------ACACAGACGGGCGGCCTGAGCGGGCG
G--------------------------CCCTCGCCCCGAGTCTCCCCCTCGCCCACAGCA
GCCTCTAGCGCTGGTCCTGTGGCGGCGCCCACAGAATGCAGCACGCTGACCGAGCTCCAC
CCAGCAGCCCTGGCACCACTGAGGCGCCCGGCGTCCCAGCTCCGCGCCTCGTGCTACATG
TCAGAGGGCGT-GTCCGACGGTAGGGCTGGGGGCCCCTGCGAGGGGCCCGGGCGGGGCGA
CGGCGAAACGCAGATGTCGTGTGGGCTGAGCCCACGGGCATCGCTCAACCAGCGCCGCTA
CTCCCTGGAGCTCCAGCAGCTTGTGCGGCGACAGCAGCTCCTCTCTCAGCCCCCACC---
CTCCATGCCCCCTCTGTACCCTTCCACCCACCCGTCGTGCCCGCGCTCGGCC--------
--GCAGAGCCAGGCTTCATGCCTGAGCCGGAGCGCCACAAGCGCTTCTCCCTGCAGGAGG
CGCTCTTCTACAAGCGGCTGAGCTCCGGCGGCGAGCTGTGGGACTGCGTGCAGAGGCCCG
CCTCGCTCTCGCACCCGCCCCAGCGGGTTCTGGATGGTGCCGGGGGCATGGGCATGGGCC
TGGGCGGTGGTGGTGGCATTTGCATCAGTGGAGGCTTTTTCCCCCCTGGTGGCACGGCGT
TGAGCCCGTGCTCGTCTTTCAGCCTGCAGGAGTCGCTGCTGGCCAGCCCTCGCTCAAGCT
TCGCCAGTAGCACAGCGAGCGGGGGTGGCGGTGGAGGCGGAGGAGGGGTCAGTCCCATGG
GCAGCCGCTGCAGCAGCAACCGTACCAGTGGCATCAGCCTGGGCTACGACTCGCGGCACA
CCCCATCTGGACCCCCTCTGCCGCCGCAGTTCTCCTCCAGCCAGTTTGCAGGAATCGCCG
GTGGCCAGTGTTACCCTCACCATGGAGCAGGCAGGCCTTGCTCTCACGCCTCCATGGAGG
CGTGGGACTACCTGGAGGGAGCC---ACGGCCGGC------------GAGAACCGGCACT
CCTACCCGCCAGCCAC---------------------CACCGGAGGCAGGTCGGCAGAGG
TCGGCTGGGCCGACCACCGGTCGGGGCCGTCGGCGG--CTGCGAGCGACGCCGAACGGTT
GTCGTCGTCATCGCGGCTCTCCGACCTCCCCGGCGTGCGCTACCAGCAGGAGCTGACGCG
CCTCCTCCTGCGAGATGCCGCCATGGAGGGCGAG--------------------------
-GAGCTGATGGGCGGACTGACGCTCCAGGATCTCCACATCACGGCCCCCAAACCCACGTC
CACACCCACCGCTGGCACCGCCGCTGCCAGTCACCTCATCTCAGCAGGGTCCCACAAAGC
C---CAGGAGGAGCCTGGA------GCGGGCAGAGAG------TCTGTGGAGAACCGGCA
GGAGTTCTTTGGTCCGTGTGTGAAGTGTGGGAAGGGGGTGTATGGGGCCGACAACGCCTG
CCAGGCCCTGGACAGCCTGTACCATACACGATGCTTCACCTGCGTCTCTTGTGGTCGCAC
CCTGCGGAACAAGGACTTCTACAATGTCAACGGCTCGGTGTACTGCAAAGAGGACTATAT
GTTCTCTGGCTTCCAGGCTGCAGCTGAGAAGTGCAGTGTGTGTGGCCATCTTATCCTAGA
GCAGATTCTGCAGGCTCTCGGAAACTCCTACCACCCCGGCTGTTTCAGGTGCATCGTGTG
CTCCAAAGCCCTGGATGGAGTTCCCTTCACAGTGGACTACCTCAACAATGTCTACTGTGT
GTCTGACTACAACAGGACGTTTGCTCCTAAATGTGCTGCCTGTCTACAACCTATTTTACC
TGCTGAGGGCAGTGAAGATATTCTTCGGGTCGTGTCCATGAACAAAGACTATCACTTTGA
GTGCTACCAGTGTGAGGAATGTGGGATGCAGCTCTCTGATAAGCCCGGATCCCAGTGCTA
CCCACTGGACGGCCACCTGCTGTGTCATGACTGCCACATGACGCGGATTGCGCACTGCAC
GTAA--------------------------------------------------------
------------------------------------------------------------
---------
>Distichodus_sexfasciatus_gill_4|023753|scaffold33249|m.41864
TCGTGCTACCTGCCCGA----------------------------GACTGTGGAAGGCCG
AGGTACTTGTGACCCAGTGAGAAGA-----------------------------------
------------------------------------------------------GGCGAC
TTGCCC------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------CAT-GTCGAACAAGGCGACCGGG-----------------------------
-----------AAGGCGCTTGCAGCCCGAACACCCGTGCTGCCATGAACCGGCGCCGCTA
CTCACTGGAGCTTCAACAACTGGTGCGAAGGCAACAACTCCTCTCCCAGCCTCCGTTGTC
TTCCATGCCACCTCCTTACCCT-------AGCCATGGCCCAGTTGCCCGCTCG---GGCT
CTACAGAGCCAAACTTCCTTCACGAACAAGAGCGCCACAAGCGGCTATCCCTGCAGGAGG
CACTGTTCTACAAGCGGTGGAGCTCAGGAGGTGAACCTTGGGACAGCG---GCAGGCCGG
CGTCGCTCTCCCACCCTCCACAGAGAACGCAAGATGGTGCC-------------------
--------------------------------AGTTACCTCTTCCCTCATGGGCCCACGC
TGAGTCCAAGGTCCTCCTTCAGCCTTCAAGAATCTGTGGTTGCCAGTCCTCGCTCAAGCT
TCGCCAGCAGCACGGCTAGCGGAGGAGGGGGTGCAGGC---------AGCAGCCCTATGG
CGAGCCCCTGCAGTAGCAACCGTACCAGTGGAATCAGTTTGGGCTATGACACCCGTCTCA
CACC---CGGCCCTCCCCAGCAGTTGCAGTTTTCCTCCACACAGCTAGGAGGCACCAGCC
CGGGCCAGGCCTACACAGCCTCTGGCCCAGGGAAAGCGGGAGCGTCCACCATGGAGGTTT
GGAGAGACTATCTGGAGAGGGTACCAGGGATCGGAGGAGGCTTCCAGGAGGCTTTCAGCC
CCCAGCCAGCCACGAT---------------------TTGCAAAGCCGAACCAGAGTGGT
GGAGCAGTACAGACCA--ACGAGGACCCCGGGGCG----------AGAGACCAGGAGAGC
G--------GGTCAGACACTCTGACCTTCCAGGCACACAGTACCAGGCGGAGTTGACCCG
ACTGTTGCT------------TCAGGAGGGAGAG--------------------------
-GACCTGATGCGGGATCTGACCTTAAAGGAGC------------------AGCCCGTGCC
CACTTCTGCCTCTCTTCCGGCCCCTGCCACA---------CCAGCTGGG------AAACC
C---CAAGATGAACACGTA------CCAGGGAGAGAGCCAACATCAGCCCTGGACCGACA
GGAGTTTTTTGGAACATGTGTGAAGTGTGGGAAGGGGGTTTATGGTGCGGATAACGCTTG
CCAGGCTCTGAACAGTCTCTATCACACACGCTGTTTCACATGTGTGTCCTGTGGCCGCAC
ACTCAGAAATAAAGACTTCTACAATGTCAGTGGATCGGTGTACTGTACGGAGGACTACAT
GTTTTCAGGCTTCCAGGCCGCAGCTGAGAAGTGCAGTGTGTGTGGTCATCTGATCCTAGA
GCAGATTCTACAGGCCCTGGGGAACTCGTATCACCCCGGGTGTTTCCGCTGTACAGTCTG
TTCCAAGACTCTGGACGGTGTGCCTTTCACAGTGGACTACCTCAACAACGTCTACTGCGT
CTCAGACTACAACAGGACATTCGCTCCGAAATGTGCTGCCTGTTTACAACCCATTTTACC
TGCTGAGGGCAGTGAGGAGATTCTCAGGGTGGTGTCCATGAATAAAGACTATCACTTTGA
GTGCTATCACTGTGAGGAGTGTGGGAAGCAGCTCTCCGATAAGCCTGGCTCTCAGTGCTT
CCCCCTGGACTCCCACCTCCTCTGCCACTCCTGCCACATGAG-CAGGGTTTGTGCCACCC
ACAA-CTTGCCCCCGCTGA-----------------------------------------
-----------------------------------ACACCCAGTGA--------------
---------
>Gasteropelecus_sp._gill_3|007344|scaffold12207|m.11315
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------ATGGCACT-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------GGACGGGGAC--------------------------
-GAGCTCAAAGGAGGCCTGACGCTGAAAGAGC------------------AGCCGGTGTC
GACTTCCGCGCCTCCTTCGGCTCCTGCAGTG---------CTCGCAGGG------AAGCC
CCAACAAGAGGAGCACCCA------CCAGTGAGGGAACCATCAACAGCCTTGGACCGCCA
AGAGTTCTTTGGAACGTGTGTGAAGTGTGGCAAAGGTGTATATGGTGCGGATAATGCTTG
CCAGGCTCTGGACAGTCTCTATCACACACGCTGTTTCACCTGTGTGTCCTGCGGTCGTAC
ACTTAGAAACAAGGATTTCTACAATGTCAGTGGATCAGTGTACTGTAAGGAGGACTACAT
GTTTTCAGGCTTCCAGGCTGCTGCTGAGAAATGCAATGTGTGTGGTCATCTGATCCTGGA
GCAGATTCTGCAGGCCTTGGGGAACTCCTACCATCCAGGTTGTTTCCGCTGTACAGTCTG
TTCAAAGACCCTGGATGGTGTACCCTTCACAGTGGACTACCTCAATAACGTCTACTGCGT
CTCGGACTACAACAGGACATTTGCTCCTAAATGTGCTGCCTGTTTACAACCAATTTTACC
TACTGAGGGCAGTGAGGAGATTCTCAGGGTGGTGTCCATGAACAAAGACTATCACTTTGA
GTGCTATCACTGTGAGGAGTGCGGAAAGCAGTTGTCTGATAAGCCCGGCTCTCAGTGCTT
CCCTCTGGACTCCCACCTCCTCTGCCACTGCTGCCACATGAG-CAGAGTGTGCGTCTCCC
ACAA-CCTCCCCCAGCACA-----------------------------------------
-----------------------------------ACAAACACTGA--------------
---------
>Lepidogalaxias_salamandroides_Head_2|012849|C563492|m.55548
ATGGATCGACTTGGTAGTAAGTTGTTGTGGAAATTAAAGTTGACTGACTCCGGTAGCGTG
AAATTCTCCAGCACCAAAAAGAAAAACGAGTTGGTCAATGCCAACAACAACAGCAACAGT
AGCAGCGGCGGCAGCAGCGTTGGGTTACAGTCACCTCTAAACGTAGCG------AGCGGC
TTGCCCGCGAAACCCGGCCAATTTGCCCTTCCCAACTCAGACGAGATGTCTGTGCCGGCT
ATTGGAAGAGAGGGAAATGGACTACTTTCGACGCACCTACTGTCTCCCCCGGC-------
--------GGCTACCTCTGTACCCGCGGCGGCCGAAAGCGAC------------CATAAC
CCGGTGACAGTAGCGCCCTTAAGGCACCGGGCACCGCAACAGCGCGCCTCGTTCTACCTG
CAGGATGGCGTCGACGCGCGAGCCGTCTGCGAGCAGACGCAACGGGATTCGACG------
-------CTGGGAGAGACCGATGGACTGTCCTCCAGAGCCTCGCTGAACCAGCGGCGCTA
CTCCCTGGAGCTCCAGCAACTGGTTCGCCGCCAGAAGCTCCTCTCTCAGCCACCCCCCCA
CTCGGTCCCGCCCTCATACCCCGGTGCA-GCTCATGGCGCTGGCCCTCGCCCTGGTGGCG
CGGCCGAGCCCGGCTTTCTCCCGGAGCCCGAGCGCCACAAGCGCCTCTCCCTCCAGGAGT
CGCTCTTCTACAAGCGGCTGAGCGCCAGCGGGGAGCTGTGGGAGAGCA---AGAGACCCG
CCTCCCTTTCGCACCCACCACAGCGCCCCCTGGAGG------------------------
TGGGTGGTGGTGGC------------------GGCTTTTACCTGCCCCAGGGCTTGGGCT
TGAGCCCTTGCTCCTCGTTCAGCTTGCAGGAGTCAGTGCTGGCCAGCCCCCGCTCCAGCT
TCGCCAGCAGCACCGCCAGCGGG------------------------GGGAGCCCCATTG
GCAGCCGCTGCAGCAGCAACCGCACCAGCGGCATCAGCCTGGGCTACGACACACGCCACG
CCAG------------CCCCCAGCAGCAGTTCCCCTCCGT---GCTGGCAGGGGGCGGCG
GCGGGCAGGGCCACGCGCACTCTGGGGCCGGGAGAGCCGGGGCCCCGTCGGCTGAGGCGT
GGAGGAACTACCTGGACGGGCCGTG------CGGTGGGGCTGTGCAGGAGAGCCGTCACT
CATACCCCCCCGCGGTGGGGAGCCCCGCGGCCGCCTGTTACCAAGGCGAACCGAGGTGGT
------------------GGGAGGAGCCACAGGCAGGGCGTCCAGAAGGGCCGGGGGAGC
G--------GGCCCGGTACTCGGACCTCCCAGGGACTTGGTACCAGGAGGAGCTGACCCG
CCTCCTCTTGAGGGACGTCAAACTGGGGGAGAAG--------------------------
-GGGCTACTGGGGGGACTAATGCTCAAAGAGC---AAACCGTGCCCACCAAGGCTTTGGC
CAGCCTGTCTGCTAGCCCGGTCCCTGCTGGC---------------GGACCAGTCAAGGG
C---CAGGAGGAACCTCCCATG---CCCAGGAGAGAG------GAGACAGAGAGCCGGCA
GGAGTTCTTTGGTACCTGTGTGAAGTGTGGGAAAGGTGTGTACGGGGCCGATAACGCTTG
CCAAGCGCTGGACAGCCTCTATCACACGCGCTGCTTCACGTGTGTGTCCTGTGGACGCAC
CCTCCGAAACAAGGACTTTTATAACGTCAACGACTCTGTGTACTGTAAAGAAGACTACAT
GTTCTCAGGCTTTCAAGCTGCAGCAGAGAAGTGCAGTGTGTGTGGGCACCTTATTCTGGA
ACAGATCCTGCCGGCCCTGGGGAACTCCTACCACCCGGGCTGCTTCCGGTGCGTGGTGTG
CTCCAAAGCCCTGGACGGGGTGCCCTTTACGGTGGACTACCTCAACCAGGTCTACTGCGT
GGCCGACTACAACAGAACATTTGCTCCGAGGTGCGCCGCATGTTTACAGCCCATCCTACC
TACTGAGGGCAGTGAAGAGATCTTAAGAGTGGTGTCCATGAACAAAGACTATCACTTTGA
GTGTTACCACTGTGAGGAGTGTGGGAAGCAGCTCTCGGACCAGCCCGGGTCGCAGTGCTT
TCCACTGGGCTCACACCTGCTGTGCCACTCGTGTCACATGAT-CAAGGTGTGCGACGTCC
GCCA-CGGTCCCCAAAACG-----------------------------------------
-----------------------------------ACGGGCGCTGA--------------
---------
>Melanotaenia_praecox_viscera_mixture_8|000035|C392318|m.24440
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------CGATGCTTCACCTGTGTGTCTTGTGGACGTAC
CCTGAGAAACAAGGACTTCTACAATGTCAACGGCTCTGCTTACTGTAAAGAAGATTATAT
GTTTTCAGGATTCCAGGCAGCTGCTGAGAAGTGTAGTGTGTGTGGCCACCTTATTCTCGA
ACAGATCTTGCAGGCCCTTGGGAACTCGTACCATCCCGGCTGTTTTCGCTGCGTGGTGTG
CTCCAAGGCTCTGGATGGGGTGCCTTTCACCGTGGACCAACACAGCAACATATACTGCGT
GACCGATTACAACAAGACTTTTGCC-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------
>Pantodon_buncholzi_mixed|022437|scaffold9273|m.11107
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------ATGCGG
GNTGTCACTGCTG-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------T----------------------CCT
CGAGCTCCTGGAAAGCCTGGCACTGAAAGAGC------------------------AAGC
CAACCCAACTGCCCCTTCTGTGGCC------------------------------AAACC
C---CCAGAGGAGCCGGGT------GCTGCCAGGGAG------TCTACAGAGAGCAGGCA
GGAGTACTTTGGCACCTGTGTGAAGTGCAGTAAAGGCGTGTACGGGGCAGAGAACGCATG
CCAGGCGCTGGAGAGCCTCTACCACACGCACTGCTTCACCTGTGTGGCCTGCGGCCGGAC
CCTCCGCAACAAGGCTTTCTACAACGTCAACGGCTC-----------NNNNNNNNNNNNN
NNTCTCAGGGTTTCAGGCAGCAGCAGAGAAGTGCAGCGTGTGTGGACACCTCATCTTAGA
GAAGATTCTGCAGGCCGTGGGAAATTCCTACCATCCAGGCTGTTTCCGCTGCGTGGTGTG
TGCAAAGCCTCTGGAcggcGTGCCCTTCACGGTGGACTACCTCAACAATGTCTACTGCGT
CTCTGA------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------
>Sargocentron_rubrum_gill_6|017118|scaffold25787|m.33291
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------TCTTCCGGG
CCGATC------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------AAAAC
A---CAGGAGGGTCAAGGAGCCGGAGCTGGAAGGGAG------GCCACGGAGAACCGACA
GGAGTTCTTTGGAACCTGCGTGAAGTGTGGGAAAGGCGTGTACGGGGCGGACAACGCCTG
CCAGGCTCTGGACAGCCTCTATCACACCCGCTGCTTCACCTGTGTGTCCTGTGGACGCAC
CCTGAGAAACAAGGACTTTTACAATGTTAACGGCTCTGTGTACTGTAAAGAGGATTACAT
GTTCTCAGGTTTCCAGGCTGCTGCTGAGAAGTGTAGCGTGTGTGGTCACCTTATCCTGGA
ACAGATCCTGCAGGCTCTCGGGAACTCGTACCACCCAGGCTGTTTCCGCTGTGTGGTGTG
CTCCAAGGCTCTGGATGGGGTGCCTTTCACCGTCGACCACCACAGCAACATCTACTGCGT
GGCGGACTACAACAAGACTTTTGCCCCAAAGTGCGCTGCCTGTTTACAACCCATCTTACC
TGCTGAGGGCAGTGAGGAGATCCTCAGGGTCGTGTCCATGAACAAGGACTATCACTTTGA
GTGCTACCACTGCGAGGAGTGTGGGAAGCAGCTGTCTGATAAGCCGGGCTCCCAGTGCTT
CCCTCTGGACTCTCATCTCCTCTGCCACTCCTGTCACATGAC-CCGAGTGTGCGCCACAC
ATAA-CATTCCCCCCCNNNNNNNNNNNNNNNNNNNNNNNNNNCAAACGCAGTCATTCTCT
CTCTGCCTTGCTCTTGCGCTTCTACTCAGTCACACACACACATTTGTAATTCAGATTTTC
CTCACATGA
>Scleropages_formosus_red_gill|029346|scaffold45765|m.61556
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------GTTA
CTCA--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------GGATAGCCGTCACTCATATC
C----------------------------------------------TCCAGCTTTAGGA
ACCCCCGCTGCGG-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------ATTGGGGAGAGCAGCGGGCAG---CTCGAGGGGGTCCTGGGGATC
G--------GCTGCGATACTCGGACCTGTTGGGGACCCAGTACCAGGAGGAGCTAATCTG
CCTACTCCGGAAGGAGGTTGGGCTGCCCAGGGAGGCACAAGGAGATGCGGCTGGGGTCCT
TGAGTTATTGGAGGGCCTGAGTCTGAAAGAAC----------------------------
--------------------------------AGCCTCCCTCTGTTGGGAATCCCAAACC
T---AAGGAGGAGTTTGGT------GTTGTAAGGGAC------AGCACCGACAGCAGACA
GGAATACTTTGGTACCTGTGTGAAGTGCGGAAAAGGAGTATATGGAGCGGATAACGCCTG
TCAAGCTCTGGAGAGCCTCTATCACACACGCTGCTTTACTTGCTTCTCCTGCGGCCGCAC
TCTCAGAAACAAAGACTTCTACAACGTTAGTGGCTCAGTGTACTGCAAGGAGGATTATAT
GTTCTCAGGGTTTCAGGCAGCGGCGGAAAAGTGCAGTGTGTGTGGACACCTGATCTTGGA
AAAAATCCTGCAGGccctggggaaCTCGTACCATCCTGGCTGTTTTCGCTGCGTTGTGTG
TTCCAAAGCTCTGGATGGAGTTCCCTTTACGGTGGACTACCTCAACAATGTCTACTGCGT
CTCTGATTACAACAAAACCTTTGCTCCAAAGTGTGCTGCCTGTCTTCAGCCCATTCTGCC
TGCTGAGGGCAGTGAAGAAATTCTAAGGGTGGTATCCATGCAGAAGGATTATCACTTTGA
GTGTTACCACTGTGAGGACTGTGGAAAGCAGCTGTCTGATCAGCCAGGCGCTCAGTGCTT
CCCTCTGGACTCCCACCTCCTCTGCCATTCCTGTCACATGAC-CAGGGTGTGCGCTGCCC
ACAGTCACCCCCCCACACACA---------------------------------------
-----------------------------------ACGTGCACTGA--------------
---------
>Synodus_sp._gill_5|021996|scaffold3080|m.3337
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------TCAGTCGCAGGG
ACGGCC------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------AAACC
C---CAGGAAGAACCCGGGGTCAGCGCGGGCAGAGAT------GTCGGCGAAAATCGTCA
GGAATTCTTTGGAACATGTGTCAAGTGTGGGAAAGGTGTGTATGGGGCGGACAATGCCTG
TCAGGCCCTGGATAACCTTTATCACACACGCTGCTTCACCTGCGTGTCCTGTGGACGCAC
CCTGAGGAACAAGGACTTCTACAATGTCAACGGCTCTGTGTACTGTAAAGAGGATTATAT
GTTCTCAGGCTTCCAAGCTGCTGCTGAGAAATGCAGCGTTTGTGGTCATCTGATCTTGGA
ACAGATCCTGCAAGCCCTTGGGAACTCCTACCACCCCAGCTGTTTCCGCTGTGTGTCCTG
CTCCAAAGCCCTGGACGGGGTGCCCTTCACTGTCGACCAGCACAGCAACATTTACTGTGT
GGCAGACTACAACAAGACATTCGCTCCAAAATGTGCTTCCTGTTTACAACCTATTTTACC
TGCTGAGGGCAGCGAGGAGATACTCAGGGTGGTGTCTATGAACAAAGACTATCACTTTGA
GTGCTACCACTGCGAGGAGTGCGGGAAACAGCTCTCAGACAAGCCTGGCTCCCAGTGCTT
CCCACTCGACTCCCATCTCCTTTGCCATTCCTGTCACATGAT-CCGAGTGTGCGCCACAC
ATAA-CGTTCCCCCTCACA-----------------------------------------
-----------------------------------ACACGCACTGA--------------
---------
