>Amblygaster_clupeoides|023288|TR40771|c0_g1_i1|m.62575
---------AAGACCCTGTGTGTTGACCATGGGAATTCTGATTCTG---CATCTGAAACC
TTTGCGTACCATGATGAAGATTCAGTGGATATTTATGCTGGCCTTCAGGATAGTCCAGAG
AAAAATGCAAATACAGAAAAGGTATGCAGATCCTTACTGTCTCCAAGGCAGAGTGAATCC
ATGGACTTGTTTGAAGAAATTATTGTAGAGGAACATCTAAAGAAAGAGGCATCATACAAT
GAGATGAAGACTAAATTTGAAGAATCTAGAAGTCAGCTCCAAGAATTGATCCAGAAGTTG
CAGCAGCTAGAAACACAGAATGTGAGCCTGCAAACGGAGAATACACTTCTGAAGAAGAAC
ATATGCGCACTAATCAAAACAGCCAGAAGCGAGATTGGTCGCAAGGATGCAGAGATAAAT
AGACTCAGTGAAAGAAC---------TGGCAGGGGTAGCTGTGGTCCCATACA---TCAT
CGACCTCAGTCC----AACCAACACATGAGTCAAGCTGCTACCAGTGGAAGTTGTACAG-
---------GAGATGACCGTCCAGCGTCTTTCTGCGAACCACATCATGAAAGGCCGAACC
GCAATGAGAAGATTTTTGCAAAGAA-------CCCTCCATTCAC----------------
----------------------------------------------------AGCAGGGC
AGACATCATCATCACTATCG----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------TCAACACAG-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Distichodus_sexfasciatus_gill_4|014025|scaffold21097|m.23511
ATGGACGTGGGAGCCATGGATGATCTTTATGGTGATTTTGGGCAGGAGTCTTATGATCCT
GTCCTAAATCATGATGAAGACTCAGTGGATATCTACTCAGGGCTTGGAAACAGTCCCACA
GCTGATGGAGACAGAGGTAAACAAGGCACTTTCCTCTCACCACAGAGGCTGAAAGAGTCT
ATGGATCTGTATGAGGAGCTTGTCACAGAAGAGCAAGAACAAAAGCAGGCAACTTACAAT
GAGATTAAAAGTCAGTTAGAGGCTGCACAAAACCAAGTAAAAGAATTGCTTGCAAAAGTG
GAGCAGATGCAAACACAGAACTCAAATTTACACAGGGAAAACACCTCACTGAAGAAAAAC
ATCTGTGCACTCATCAAGACTGCTAGAATGGAGATTGTTAGGAAGGACGAGGAGATAAAC
AAACTATTGAATAGAAG---------TAGTCGAGGGAGTTTCCCATCTTCTCGTCCTGAA
AGAAGTGAAGAAGGCTGGCTGAGGAGCAAGGCCAGCACTGGGCACAGTTCGCACAGCACT
GTTGATACCGTAAGGAAGTTACAGGACCTTAAGGCGAACCG----GGAATTAACAGAGAC
GCCACAGCAGAAGCATGAAAACAGA-------CCTTCTAGCCAGTCGGTTTGCCGAGAAA
CGGCAAAAGACATTGCTCtgttaagccagactaa----------gccccaaagaTCCATA
AGAAACCTTAACGCTCCTCT---------CCCTCCCCAACACACCCAAAGCCATAAACAT
GTGTCCTCTGATGGAATGT---CTGTCAACAGTGAAAAGAAATGTGCAGACTCTGAAGCT
GAAGTGGCATCATCCCAAAGTAGCAGTACGGCTAGAGAGAAAAACATGGACGAAAAAGCG
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------CTGAGGCGG-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------GTAGCT---------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Gasteropelecus_sp._gill_3|018563|scaffold29894|m.31592
ATGGAGGACAGTGTTATGGATGAGCTTTTTGGCGATCTTGGTCAGGGGCAACGTGGGTCT
GCATTGATTCATGATGAAGACTCTGTGGATATTTACTCCGGGCTGGATGACAGTCCTAAA
AGTGATGGAGGCAGCGGtgaagagagcaCTTATGTGTCACCCAAGAGGCTAAAAGAGTCT
ATGGATTTGTATGAGGAACTCATCACTGAAGAGCAAAATGAGAAGGACACAACATACAAT
GAGTTGAAAAGTAAATTTGACGCTGCTCAATGCCAGATCCAGGAATTGCTTGGAAATTTG
CAACAGATTCAAACAAAGAACTCGTGCTTGCACAAGGAAAACACTCTCTTGAAGAAAAAC
ATCTGTGCACTAATTAAGACAGCAAGACTGGAGATTGTTAGGAAGGACGAGGAAATAAGC
AAACTATCCAGCAGACA---------TGGCCAGAGTAGATTCTGTCCACCTAGAACTGAC
AGAGGCCAAGAACACTGCTTGAGAGGCCAGACCAA-------------------------
-----------------------GAATTGCAAGGGAAGTTG----GGGAGTTGCAGAGTC
---------TAAGGATGATGGTAGA-------CTTTTCAGTCAGCCTGCTCGTCTGATTA
CACAGGCAGACGCTAAACCAACGTCATTCACAGA----------GCAACAAAGACATACC
AGAAACGATCATCATTGTCAGAGTAAAGGCACTGATGAAAAAGTGCAAGGTCACCAACGT
GGGCAGTTCGATAAAGCAT---CCAATGCAAAAGAGAGACAAAATGCATGCTCTGAGAGT
GATGTGATGAAAACTCGGAGTATTTTTAATGCAGGCCAGAAAGTT---AATGAAACAGCT
GGAAGACCGCTGGACTGCAGGGAAGGAGTTAAGGAGCGTGTTGTGAAACAGCCAATTGAT
CAGAAAATGGAATCGAAAGCAAAGGATATCGCAGAAAAATCTCAGCGGGACTCAACAAAA
ATGACAAG--------------------TTTGTCTAACCAATGCCTTCAGCAGCAGCATG
AGGATTCTGTAGTGCTTAGGAAGTCTAGCCATTCAAAGGGTCCATTCTCTCAAACACGGC
ACGTCTCCCCAT------------------CTCGTTTACACTCGCAGACAACCAGAGAAA
CACCCAGGGTAACTGCAGACATGCAGGCACAGGGTCCTAGCCAAGAAGTTAGGCATAATC
AAGGAGAAGGCAGACACGGTAGGAGTGGTGCACATTCTGTAAGTGAGGTGAGCAGCTTTG
AGAAGCCAGCTACTTCCCTTGACCGAAAAATAGACAAAAGAGAGACCAGAGAGCATCACA
GAAAAGAGGAGAAGAG----GCAAGACAGTGTTGGCAGTTCAGAAAGGAGATACACCAGG
AGCGATGGCAGCAAAGAATGTGAGCAGAAGAAGACAAGAGAAAATGACGAGAGAAACAGA
CAACAAAGAAACAGTAG--CACTAGTAGTAGAGGAGAGAGAAGAAGCACTAGGTCTGAAG
CCAGCAAGACTGAGCGAAGGAGTGCGAAAGAGAGCGGTGGATGCGCTGCAAGAGAGACAA
CTAATAAAGCTGAGAAACATGTCAAGGATGGGAGGGATGGAAGCCAAAGTGATGTCCGAA
ACACCAGACAACTAAGTTCTACAACAAAACGTGGTGATTCTGATCGTGAACACACTCGGC
AAAAAGATCAAGA----------GGAT---------------------------------
---------------------------------
>Melanotaenia_praecox_viscera_mixture_8|002015|C419778|m.27191
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------CAAGCAGCTCAACATCAAATTAAAGAGTTGCACCGCAGACTG
GAGCAGATGGAGATCCAGAACTCAGGGCTGAGCTCGGAGAACCAGCGCCTCAAGAAGAAC
ATCTCAGCACTTCTACGAACTGCGAGGCAGGAACTGACGAGGAAAGATGCTGAGATTCAA
AGGCTCAACCAGAGGAC---------TGAAAAAGGTCACCATCATCACAAGTTTCACTTC
AATAATCTCCAG----------------GATCCAGTTTCGTCCTGTCGCACCTCTACAGT
--TGGTTCCGTCAGTAAGGTGC-------------------------------CGGTGCC
GC------------------------------CTCCACCACCATCTGGTCTTCCT-----
-------------------------CCACCTCG---------------------------
----ACCAGCTTCACCCTCCAGGGACGATCATCCTCCACAGCATCCA-------------
------------------------------------------------------------
--------------------CCTCAACCATCCAGGATAGAAAGTTTG-ACCAGGACATC-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------AAAC
ATATCTCCTCGC------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------AACCGTCCCA
GAAGAGATGCTGAAGTAGACTGCAGGCGG-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Pantodon_buncholzi_mixed|001305|C597633|m.31291
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------CATAAGCTGAAAGACTCA
ATGGATCTGTATGAAGAACTTATAACTGAAGAGCAACAGGAGAAAGAAGCCACCTACAAT
GAGCTGAAGGTCAAATTGGAAGAGGCGCAGAATCAAATGAAAGAATTAATTGTGAAGCTG
CAGCAAATGCAGACGCAGAACACGCATTTACACACTCAAAACACTCACCTCAAGAAGAAC
ATTTGTGCGCTCATGAAGACGGCCAGGACAGAGATTTTGCGTAAAGACGAGGAGATCAGC
CGCCTCAGCAAGAGGGGAGGACAATTTACAAGAGGCCATACTGTCACAAAATGGTACAAC
AACTCTCCGGGG----GATCAAAATTTGAGGCAGAATGTTTTAGGACCTTCTGGA-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Sargocentron_rubrum_gill_6|000966|C643423|m.42929
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------CAGAGTAGAGATTCATCTTATGAT
GAGTTAAAGAAGAGATTCCAAGCAGCGCAAAAACAAATTGAGGAGTTGCGCAGAAGACTG
CAGCAAATGGAGACGCAGAACACGGGGTTAAATACTGAGAACTACCGTCTCAAAAAGAAC
ATCTCTGCACTTTTAAGAACTGCTAGACAGGAGGTGACACGAAAAGATGAGGAGATTCAG
AGGTTGAACCAGCGGTC---------TGGCAGACGTCATTCCCATTATCACTCTCACATA
AATGGTCTGCGG----------------GAGTCAGATTCAACCAGACGAACTGCCTCAAG
--TAGCTCCATGAGGAAACCAC--------------------------------------
--------------------------------CTCCCCCACCAACTGATCTTCCT-----
-------------------------CCCCCTCC---------------------------
----ACCATCGTCTTCAGTCCAG-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Scleropages_formosus_red_gill|026002|scaffold41159|m.54254
---------------------------------GGCCTCGGAGGAAGTCACTGTGACTCT
CCTGTTGTTCATGATGAGAACTCAGTGGATATTTACTCCGGATTAGACTCTAGTCCTGGA
AATGGTGAACATACAGACAAAGTGAATACCCACATCTCTCCTGGGAAGCTAAAGGATTCA
ATGGATTTATATGAAGAAATCATCAAAGAAGAGCAACAGGAAAGAGAAGCTTCGTACAAT
GAGCTCAAGACCAAGTTGGATGCAGCAGAAAATAAGGTTAAGGAATTGTTGTGTAAGCTA
CAGCAAGTACAAGAAAAGAACACCACCTTGCACACGGAGAACATACGTCTCAAGAAAAAC
ATATGTGCACTTATTAAAACGGCCAAAATGGAAATACTGCGTAAGGACGAGGAGATCAGC
AGGCTGAATCAAAGGTT---------TGGTTGTGGCCCTCCTCGAACACAGCACTATG--
----CTCAGAGA----CGTCAGAGTACCAGACTGGATCCTTCAGGGACCTGCGCTTCATC
GGCAGTGGTACAAA-----TGCAGGAACCAAAAGTTACCTT----TCCCTCAAAGGAGCT
ACATGAACACCACTCCGAGGACAGAAATAGTTTTGTTCAGCACCCTAGCCTTTCATGTAT
AGACAGCTCACCTGTAACTGCTACACCACTTCATAAAGGCAGGTGCATTAGAACTCACCC
TGAAACAAGAATGTTGCTCC---------CTGTTTCCAGGGAG-----------GAACCA
GCACAGTCTGGCAAAGTATGCACAGGAAGCACTGACAGAcagcagaatagtactgtaatg
caaGAAGAGGTTTCCCAAAACGTCAAAGATGGGAAACAGCAGGCTACGACTAGAAAAGAC
---------------------------------------------------CAACTTAAT
C--ATATTGAATTTGGTGGAAACGAGCAAAAACAAAAGGATCAAGAGGAACTGAACAGAG
ACCATAAGGAGCTGGCTAAGGATTGTACTGAACCTAACAGAAGTAATCGCCAGCATCCTG
CAAGTAACTTA---CCTGGAAAGTTAGAGAGGAGTAACAGTCCATCTCATCAGAAAAAAT
GGAGCCCAACGTCAGATGCTTTGCATCGCACAAGTTGTGGTTCTCATTCGACAAATGAAC
GGCACAAGGACTCAAGAGAAAAAAGACAGAGAAGCAGCAGTCAGGAGAGACGGTATGGCA
AAGATCGGCACATGGGCGACAGAAGTGTTCCAGGACCAAAGTGCAAGG---------ATG
GGAAGCGGTCTAGTTC---TAACCATGGTAGTTGCGAGAGTGGGGCACGACACTCATCCA
GCCACAGGGGGCAAAGAAGTCCTACGTGGGACCTGCAAAAGAAGGAGAGGTGGCGCAGGG
AGGAGGAAAACAGGAGTAGATTGGAAAGAAGCAGTAAGGCAGAGAAGCGTGATGAATATG
AGAGAAGAAAATGGAAGGAGAGTAGCAAGAGTGGAAAGGACAGGCATGGAAAGACTGACG
GCGATAAAAAGGTCAGAGAGTCAGCGAGTCGGGGCAGTTTGAGGGATGAAAAGCGAAACA
CTCCTTGCAATGAGCACAGCACCGGGACTGAGAGCTTCAGCAGCT---------------
-------CCAGGAAAGATTTAGCAGAAGGCTTAACGTCACTCAATGAGAAGGACCATGGG
AAGAGGAGCGGGGCTCTGGAGGCGGATGTTGTTGAACATGAAACTGACAAAGANNNNNNN
NNNNNNNNNNNNNNNNNCAGAATAAAAAGCTGA
