>Corydoras_julii_viscera_mixture_8|001379|C1202997|m.25520
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------ATGACGAAGCTGGACATGTTGAACTCGTTTTTAATGGAGCGCCTGGCCGCG
GCGGCCCGTGAGATTTTGGAGGTGGTTGAGGCCACAGTGTCGGAGTATCGAGCGGAGAGC
GAGCAGAAGCAGGTCGAGAACGAGAAACTAAAACAACAGCTGCGAGAGCTCCTGCACCCC
GCCGCT----------------------CCAGAC---------------CCAGCTCACAA
TGCAACTAATCATGTTTCAGAAGAAACACCTCGGTGTGAGC---------AGAAAGAGTG
GAATTCAGCCCCTGAA---GAACA------------------------AGTAGAAAAAGA
AGGCAGCCACCAGAACCAGAGACTTGATGAAG-----------------------GTTTG
TTTAGGG-----------------------------------------------------
------------------------------------------------------------
-------------------------------AAAATCAGCC-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----A
>Gasteropelecus_sp._gill_3|025775|scaffold7224|m.6659
GAAAGCCCGGAAGTGCTGGGAATCCTGTTTATAAACAGATTGAGCGTGAAAGAGGCCGCG
GAGCCTCTGGCGCCCCCTCGCGGCTCCTCGGTGTCGCTGCCTCTGACTCCGCTTTACGCC
AGAGCTCCAGCCTGCTGGCGACCGGAAGGCGGTCAGCGGAGCTGCTCGTTTGTCCCTTCC
TCCGCTTCTGGGGCTCCGGCGTCGCAGCGCTTCGCTTCCACCGCGGCGCGCGGCTCTCCC
GCGGCCGACATGTCTAAGATGGAGCTGCTGAACTCCTATCTGACCGAGCGCCTGTCCGCC
GCCGTGAGGGAGATTCTGGAGGCGGTGGAAGCCACGGTGACGGAGTACCGCCAGGAAACC
GAGCAGACCCGGGGCGAGAACGAGCAGCTCCGGGAGCAGCTGAGGGGCGC---GCTGTGC
AGGGCCGAGGCAGCG-GAGCGCGCTAAACGAGAA---------------ACAGTCCGCAG
TGTCTCGACGTCCGTCTCGGTCGAGATCCCTCCCCGTGAGC---------CTCAGACGTG
GAGCTCCTGCCTGGAG---AAGC---------------------------TGGAAgaGGT
GCAGGAGGACCAGAAACAAGGCCACGGATGGA-----------------------GTAAT
TGTACAAAAATAAATGAGGAGAGCCCAAATTCGC--------------------------
-------------------TGGTACCAGTTTGCA----------AAATAGAGAGAAATTC
TT---------------------TGA-----AAGAGGGATCCCACGCAGAG---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>Lepidogalaxias_salamandroides_Head_2|005747|C508544|m.42681
-------------------------CGTTTCCAGACAA----------------------
-----------------------------------------------------------C
AAAACACCAAACTATTTTCA----------------------TTTTAATTTATTC-----
--------------------------------------------------CAGTTTGTTA
ATTATAAAAATGACTAAACTCCAGCTCTTAAATGCTTACCTGACCGAACGCTTAACGGTG
GTAGTGCGGGAAATTCTGGATGTGGTCGAGGACACGGTGATAGACTACCAACAGGAAACA
GTCCGTACTCGGAAAGAGAACGAGAGTCTTCGGCGACAGCTCCAGGATATCTTGCTTTTA
GAGACCGAAACAGATTGG----------CTAGGC---------------GGGGGCCGCAC
CATCATGCTGCCCACTTCTGAAACGAGGTCTCCGTCCGAGCAGCATTGTGAGCAGGAGTG
GAGCTCCGGTCTAGTGCCAGACCCCGAGCCCACGCTCA-------CCCAGCCCATCCAAG
TGCTCACCAGACCCAACCATGCATCCAAAGGGCAG-------------------TACCAG
GACGTTTTGAGACCGGACCACTCCCTGACCAGGCATAACC--------------------
-------------------AGGTGCCCTCTGAGACCAC----ACAGCGGAAAGAAACAGT
TG---GACGGCTCGAGATGGACCCGAAGACAAAATTGGACCTGGGGCCCGTTGCTTTTCA
AGACGTCTCACCCCT---------------------------------------------
------------------------------------------------------------
---------------------------------------------------AGGACACGC
TGCC--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>Melanotaenia_praecox_viscera_mixture_8|020459|scaffold9511|m.8416
GT----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------TTGTGTTTCT
AGCTTCAAAATGACCAAGCTGCAGCTGCTCAGCGTCTACCTTACGGAGCGGCTGACGGCG
GTGGTGAAGGAGGTCCTGGACGTGGTGGAGGACACGGTGGCCGAGTACCGCGAGGAGACC
GCCAGAACCCGTCGCGAGAACGAGAGCCTGCGGAGGCAGCTGCGGGACATCCTGCTGCTG
GAGGCCGAGACAGAGTGGCTGAGGTCCACCAGGT---------------CCAGTCTGGGA
T-------------TTGAGGCTCCAGATCAACAGTCTGGTG---------ATGTGGAGCG
AAGGTCCAGCTCAGAG---GAGCCAGACTCCACCCCGA-------ACCAGCCCAGATCGC
CACCATCCAACACAGCCCAGTTGTCGCATGAGCAGCTGGTTTCAGTAAAACTGTTGTCGG
TTCAGAGGGAGACGCCACCAGTACCGGTACCAGCACCAGTA-------------------
------------CTTGTACCAGCACCAGTACCGATTCT-AGAGCAGGAGGAAAAGAAGCC
CACAGAGTCCTGGGATCCGGTCCTG------AAAGCTGATCCTCCACAGGAGGTGTTGAG
GAGAGCGTCATCTCCCTCTTCTCACTCCTCCCTGGATCCTCCTCCCTCCTTGGCTCCCAA
AGTCCTGGTGGACGTTCCAGA------GGTGACGGAGGAGCCGCAGGCCTCGCTACCTGC
TTGGATCAAAACCGAGCCCGAGGA------------CGTGAGCAAAGCTGAAGGTAACGT
GGACTGTGTGACGGCGAGCGCACGCGTTGTGGTGGAAGANNNNNNNTGGAGGCTGACCGG
ACGGTG----------GTGGTGCTCGCAGATGGAAACAGGAAGTCGGCTGATGATGGCGC
TACCAATGCTGCTGCCTTCTCCCCCGAGCTCG--------TGCATCGCTGCCCCCGCTGT
GGCGAGGCGTTCGGCCAGGCCGCCAGCCTC------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----C
>Pantodon_buncholzi_mixed|012294|scaffold15150|m.19921
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------ATGGCCAAGCTGCAGCTTATAAATACCTACATGACGGAGCGTCTGTCTGCA
GCTGTGAGGGAGATAGTGGAGGTGGTGGAGGGAGCGCTGGTGGAGTTTCAGGAG------
---------------GAAAATGAGAGTCTGCGGCGGAAACTGAGAGAGCTCGGCCTGCAG
GAAG--GGGCCTGCATGGGAGATGTCCAGCTGTTAAGCCTCCCANNNNNNNNNNNNNNNN
N-------------NNNNNNGACCGGAGCATGTGTCCCAC----------ACCGGGCACC
CAAGTCCAGCCTAGTG---ATGCAAAGCCAGAGCTCTACGTTGTTGACAGTGATGACTTA
TACCGTCCAGCAAGGCCAGGTTATGA----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------AGAGCTGA---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>Sargocentron_rubrum_gill_6|003006|C691937|m.46145
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------GCTTACCTGACAGAGCGGCTGGCGGTG
GTGGTGAGGGAGATCCTGGACGTTGTGGGAGACACGGTAACCGAGTACCGGGAGGAGACG
GCTCGAGCTAAACGGGAGAACGAGAGTCTGCGGAGACAGCTGCGGGACATCCTGCTGTTA
GAGGCCGAGACAGACTGGCTAAGGTCCACCAGGT---------------CCAGTCTTCCT
T-------------TTGCAGCTCCAGAGCAGCAGTCCAGCG---------AGCAGGAGCT
GAGGTCCTGTTCAGAA---GAGCCAGACTCAACGCTGA-------GTCAGCCTAAACAGG
CTCCAGCCAGAGCAGCCAGCCGGCGACATGAGCAGACTGTGTCTGCACAGTTACTGTCCG
TCCAGAGTGACACTCCACCTGCACAGCCGCCG----------------------------
-------------------CAGGACCAGCTGGAAGCACCAGAAAAAGTGGACAAGAAATC
CA---GACTTCAAGAGTCTGTACTGAAGCCTGAGCCTGACCCTCAGCAGGAGCCCTTTAG
AAATGCCCTGCCCCTCACCTCTCAGTCCAGCCTGAACGCTTCCTCTGCCTCAGGCCCCAA
CATCCACAACGACACTCCGGC------TCACAGAGAGGAGCCTCTTGCCCCTGTTCAAAC
GCTAATCAAAACTGAACCCACGGAATACGAAGTCATGGTGACTGACACTGAAAGTCACAC
CAGCTCGGTCTTCTCAGACTCTCTGGCAGCACCCGGCCACACTCGCGTTGCACTGGACGA
ATCAAGTTTTAGAAATGTGCCAGATGTGGATAGAACGGGG--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>Synodus_sp._gill_5|008671|scaffold11672|m.13277
--------------------------ATTAAAAGAGGA----------------------
------------------------------------------------------------
--------------------------------------------------TACCC-----
--------------------------------------------------TCGCATTCAT
GGTTTCAACATGACAAAATTACAACTCTTGAACGCGTATCTAACAGAGCGATTGGCGGTG
ATGGTGAGGGAGATTCTGGATGTTGTTGATGACACAGTGTCGGAATACCGCGAGGAGACG
GCACGAGCCAAACGGGAGAACGAGAATTTACGTAGACAGCTGCAGGACCTTCTCCTCCTG
GAGGCCGGGACTGAGTGGCTGAGAACAGCCCGTT---------------CCAACCTCCTG
A-------------GCCCGAGGCCCGAATGGCCATCCAGTG---------AGCGGAGGTC
CAGGAGCGGTTCGGAG---GAGAGTGACCCACCC--------GTTCCCAGCAGAGCGGTG
GACCAGGAGGAGCAGGAAGAGAGTGAAAGCAGTGTGC--CCCCTGTCCAGCAGCCCCCCC
CCAGTCCCCGCACCAAACCTGAGCCTGAGGAGCCCATCTCAGAGCTGCCCTGGGATGCCC
CCTCCCTGCTGGCCCATGCTGGCTTCACCCCCGTGTGC----AGAGAGGTAGCAGACATG
TC---GCNGGGAGACCTCCATC---------AAGAAGGAGCCC---CAGGAGCTCCTGCT
GGCTCCGCCGCACCCAGACTGTCCCCCCGAGGCACCTGCCGAGCCCCCTGTGGGCTACCA
CACGGTCGCACACCCTCCGGCCAACCAGCGCATGGGGGAGCC--------CTCCAGGGGT
GTGGGGGAGAGCCTGACTCGAGCA------------ACTGGCCAGGATGCAGGGTTCGGG
TGTTCGCGCTGCGGGGAGGCCTTCTCCCAGGCCAGCAGCCTGCGtctgcacatggagcag
AAACGG------AAACCCTACGCCTGCACCTGGTGCTGCAAGTCCTTCACGCAGTCAGCC
GACCTGCGGCGACACCTGCGCACGCACACTGGGGAGCGGCCACACGCCTGCACCTGGTGC
TCCAAGAGCTTCAGCCAGAGGGGCAACCTGCGGCGGCACATGCGCATCCACACCGGGGAG
AGACCCTACAGCTGCCCTTTCTGCTACCGCACCTTCAGCGACGGAGACACCATGAAGAAG
CACAAACGAACACATTCAGGAGAGAAACCCTACCAATGCTTGCGCTGCACAAAAACCTTC
AATCTTGCCAGCGCGCTACAGATACACTCCAAGAAAGACTGCTGCGTGTCCAAAGCCTNN
NTACCTATGGGGACATGTGGCTGGATGATACGATAGCATCAGCCTCGCTCAGCCTGTGGG
TGTGA
