>Amblygaster_clupeoides|018374|TR32050|c3_g2_i1|m.53557
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------TGTGAC
CTGGGCTACCATGCCAGTCTGAACCGGGCCATTCGGACCTACTTGTCGGCCGAGTTCAAC
GTGGAGTCGTCCAAACATGGCGGCCTGGAGACCATCGAGAACGCAGCCGACAACCTGGAG
GCCAACGCAGACAAGCAGAGACTCATGGAGACCTACAACACCGTCTTCTGTCCACCCATG
CGCTTCGACTTCCAGTCCCATATGGGAGACATGATGGATCAGCTGTGTGCTCAGGAGCCG
GTGCAGGTGGAGTTGTTGCAGAGGTGTCAGCAGCTCCAGTCTCGCCTGTCCACACTGCGC
ATCGAGAATGAGGAGGTGAAGAAGACCATGGAGGCCACTCTGCAGACCATCCAGGACATG
GTGACCATTGAGGACTTTGACGTCACAGACTGTTTCCACCACAGCAACTCCATGGAGTCG
GTCAAGTCCACCATCTCTGAGTCCTACATGAGTAAACCTAGCCTGGCCAAGAGACGTGCC
AACCAGCAGGAGACTGAGCAGTTCTACTTCACGAAGCTGAAGGAGTTCCTGGAGGGACGA
AACCTGATCACCAAACTACAGGCCAAGCATGACCTGATCCAGAAGACCCTGGGAGAAAGT
CAGAAGACGGACTACTGCCTTGCCAGTGGGAGAAGGAGTTCCACGGTGCGAAAGCAGGAC
TCCAGCCAGCTGATCCCCCTGATGGTTGAGAGCTGTATTCGCTTCATCAGTCGCCATGGT
TTGCATCATGAGGGCATCTTCAGAGTGTCCGGCTCTCAGGTGGAAGTCAATGACATCAAG
AATGCCTTTGAGAGAGGTGAGGACCCCCTGGCTGGCGATCAGAATGACCATGACATGGAC
TCCATTGCTGGCGTACTCAAGCTGTACTTCAGGGGCCTAGAACACGCCCTTTTCCCAAAG
GAAGTCTTCCATGATCTCATTTCCTGTGTCTCCATGGAGTCACTCCAGGAGAGGGCGGTC
CACATCCGTAAGGTGCTCATTCAGCTGCCCAGCAACACCCTGGTCATCATGAGATATCTG
TTTGCTTTCCTCAACCATCTGTCCCAGTACAGTGAGGACAACATGATGGACCCCTATAAT
CTGGCCATCTGTTTCGGCCCGACACTCATGTCGGTGCCCGAGGGTCAAGACCAGGTGTCC
TGCCAGGCCCATGTCAACGAGCTCATCAAGACCATCATCATCCACCATGACGCCATCTTC
CCTGGCCCCCGCGACCTCCAGGGGCCCGTCTATGACCGTGGAGGGGCCCCCGAAGAGTAC
TGTGAGAGTCCACACAGTGAGCCCCCCCTAGTGGATGAACCTGCTCCTGACACCGTCTCG
GAGATCCACAACAGTGACGAT------------------GAGTCAGACCCCATTGAGGCG
ATCGCGCGCTATGACTACTCGGGACGTACCAATCGCGAGCTCTCCTTTAAGAAGGGGGCG
TCACTTCTGCTCTATAACCGCGCCTCTGACGACTGGTGGGAGGGGCGTCACAACGGAGCC
AGCGGATTGGTTCCGCACCAGTACATAACGCTACAGGACACCCCTGATGGCTACACTGGC
CGAGGCAGTCCCAAAGCGGACCTGGAGAGCTCCCATGAGTCTGGG--CCGCAGGAAGAGA
AGGTGGCCACTAGGGGCAGCGCAAGCTCCCCCACAGGAGCTCATGTGGCTGACATCTACC
TGGCCAACCTCAACAAGATGAGGAAGCAATCTG---CTGGCAGTATCAGAAGAACCTTCC
GGACCTCCGAGGGACTGAGTGAGGTTGCGCCTACGCCCTCATCTCCAGGAGCGACAGGGG
GTCTGCGCGCCCCTTCCATGCCCGTGGCGGGCCTGGCAAAGGAGGGCGGGGCAGACAAGC
GCCCGCTGAGCGCCCACAGCGTGCTGAACTCAGTCACGCGCCACTCCTCCCTCAAGACCA
AGGTGGAGAGCCCGCAGATACGCAAGACCACCACCGCGGGGCGCTCCAAGAGCTTCAGCA
ACCACAGGCCTATCGACCACGAGGTCTTCGCCCAGGTGGAGCACAGCTCACAGGACATTG
AGGCCACCATGAACTCGGCGTTGAGTGAGCTGCGTGAGTTGGAGAGGCAGAGTTCGGCCA
AGCACGCG------CCCGACGTCGTCCTGGATACGCTGGAGCAGCTCAAG---------T
CTGGGGGTGTGGCCGGAGGCGGGGTCTCTGAGCCGTCCAGCCCCCTGCACTCCCGCCTGC
TGCGTGAGGTCGA---------CGCCCCCCAACACCCGCTCCAGCGCAGCGCCAGCTCGG
CGTCCGACATGCCCAGCACCTTCCGCCCGGGCAAAGGCGCCAGCCCCAAGAGCCCGCTGC
TGGCCTCCTCCTCCTCGCCTCTGTCCTCTTCCTCCTCCTCCGGCCTCTCCTCCTCCTCCT
CCTTCAGGGAAAACCGCCCCCCTGCCACGCGCCCCAAGCCTGTGGTGTTCCCCAAAACTG
GGGCCTCCTCCGGCAGCAGCGGAGCTATGGGATCCCCCACCACACCCATCCCCCCGACCC
CTCCGCCACCACCACCA-------------------------------------------
--------CCTACTGACAAATCCTGTCCTGTGTGA
>Corydoras_julii_viscera_mixture_8|003439|C1232376|m.28428
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------CTCTTTCCAAAA
GAAGTCTTCCATGACCTCATGTCCTGTGTGTCCATGGAGAACCTCCAGGATCGAGCCACA
CACATCCACAAGGTCCTGCTGAGTCTTCCCAATAACACTCTGGTCATCATGAGATACCTC
TTTGCTTTCCTCAGCCACCTTTCTCAGTACAGTGATGACAACATGATGGACCCCTATAAC
CTGGCCATCTGCTTTGGCCCCACGCTCATGTCGGTGCCTGAGGGTCATGACCAGGTCTCC
TGTCAGGCTCACGTGAACGAGCTGATCAAGACCATCATCATCCACCATGAGCTCATCTTT
CCTGGCTCTCGTGAGCTTGAGGGCCCCGTCTATGAGTTTGCAGGGGCCACTGAGGAATTC
TGTGATGGTCCACACAATGAGCCCCCTCTGGTGGACGAACCAGCACCTGAAACCATCTCA
AACATCCAGAACAGTGACGAC------------------GAGTCGGAACCCATCGAGGCC
ATTGCGAGATTTGACTACTCGGGCCGTACCAACCGCGAGCTGTCCTTCAAGAAGGGGGCC
TCCCTGCTGCTCTATCAGCGGGCATCTGACGACTGGTGGAAGGGGCGGCACAATGGCGTC
GAGGGCCTGGTGCCCCATCAGTACATCATTCTACAGGACGGGGCGGATG------CTGGC
AGAGGAAGTCCTAAAGCCGATCTGGAG---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------
>Distichodus_sexfasciatus_gill_4|016278|scaffold24432|m.27779
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------TCTCGTCTCTCCACGCTCAAG
ATAGAGAATGATGAGGTGAAGAAGACCATGGAGGCCACCCTGCAGACCATTCAGGACATG
GTGACCATCGAGGACTTCGACGTGACCGACTGCTTCCACCACAGCAACTCCATGGAGTCG
GTTAAATCCACTGTGTCTGAGTCGTTCATGAGCAAACCCAGTCTGGCCAAGAGACGCGCC
AACCAGCAGGAGACCGAGCAGTTCTACTTCACGAAACTGAAGGAGTTCTTGGAAGGCAGG
AATCTCATCACCAAACTGCAGGCCAAGCAGGACCTGATCCAGAAAACCCTGGGAGAGAGT
CAAAAGACGGACTACTGTCTTGCCAGTGGACGAAGGAACTCGACTGTGCGAAAACAGGAC
TCCAGCCAAGTCATTCCACTGATGGTGGAGAGCTGCATTCGCTTTATCAGTCGACATGGC
CTGCACCATGAGGGCATCTTCAGGGTGTCCGGCTCACAGGTGGAGGTCAATGACATAAAG
AACGCATTTGAGAGAGGTGAGGACCCGCTGGCTGGAGATCAGAACGATCATGACATGGAC
TCGATTGCCGGCGTCCTCAAACTCTACTTCAGAGGCCTGGAGAACGCCCTCTTTCCTAAG
GAAGTCTTCCATGACCTCATGTCCTGTGTCTCCATGGAGAATCTCCAGGACAGGGCCGCC
CACATCCGCAAGGTCTTGCTTTCTCTACCCAGTAACACCTTGGTCATCATGAGATACCTG
TTTGCTTTCCTCAACCATCTGTCCCAGTACAGTGAGGACAACATGATGGACCCCTATAAC
CTGGCCATCTGTTTCGGCCCCACCCTCATGTCAGTTCCTGAGGGCCATGACCAAGTGTCT
TGCCAGGCTCACATCAACGAGCTGATCAAAACCATCATTATCCACCATGAAAGCATCTTC
CCTGGTCCCCGCGAACTCGAGGGGCCCATTTATGAGCACGGAGGAGCCACAGAGGAGTCC
TGTGATAGCCCACACAATGAGCCCCCTCTAGTGGACGAACCTGCACCTGACACGGTCTCC
GAGATCCAAAACAGCGACGAT------------------GAGTCGGACCCCATCGAGGCC
GTGGCTCGTTTTGACTACTCAGGCCGCACCGGCCGCGAGCTGTCCTTTAAGAAGGGGGCC
TCGCTGCTGCTGTACCGCCGCGCCTCTGACGACTGGTGGCTGGGACGCCACAACGGCACC
GAGGGCCTGGTGCCTCATCAGTACATCGTAGTCCAAGACACGGCGGATGGCTACACAGGT
CGAGGCAGTCCCAAATCCGACCACGAGGCATCCCATGAGCTAGGG-----------GAGA
aaGTGTCCACTAGAGGAAGTGCGGGATCTCCTACTGGAGGCCACGTGGCCGACATCTACC
TGGCCAACCTCAACAAGATGAGGAAGCGCCCGGAGGCAACAGGCATCCGTAGATCGTTCC
GACCTGTGGAGAGTCCCGGCGAGGGCTCGTCC---------------GGGGCCACGGGGG
GTCTGAGGGCCGCGTCTGTACCTGTCGGCGGGCTTCC----CNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNGAACTCCGTCACACGACACTCGTCCCTCAAGAGCA
AGGTGGAGAGCCCTCAGTTCCGCAAAGCCGCTCCAGCCGGACGCTCCAAAAGCTTCAGCA
ACCACCGACCCCTCGATCCGGAGGTCATCGCCCAGGTGGAGCACAGCTCACAGGACATTG
AGACCGGCATGA------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------
>Melanotaenia_praecox_viscera_mixture_8|014838|scaffold20322|m.21977
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------GAGGACCCGCTGGCAGGGGACCAGAATGACCATGACATGGAC
TCTATTGCTGGTGTACTGAAGCTCTACTTCAGAGGACTGGAGCATGGTCTTTTTCCTAAA
GAAGTCTTTCATGACCTCATATCCTGTGTCTCTATGGAAAGCCTCCAGGAGCGGGCAGTC
CACATTAAGAAAGTTCTGCAAACCCTTCCTAGTAAAACACTCATCATCATGAGATACCTG
TTTGCCTTCCTTAACCACCTGTCTCAGTACAGCGAGGAAAACATGATGGACCCCTATAAT
TTGGCCATCTGTTTCGGCCCCACCCTGATGTCTGTCCCTGAGGGCCATGACCAGGTCTCC
TGCCAGGCTCATGTCAACGAACTCATTAAAACTATCATCATCCACCATGACACCATCTTT
CCTGGGCAGCAGGACCTGCAGGGCCCCATATACACCATCCCTGGAGCAGAAGATGACTTT
GGGGACAGTCCGCTCTGTGAGCCGCCCCCTGTGGAGGAG-----GTNNNNNNNNNNNNNT
GGCTGTTTCA-----------------------------GAGTCTGAACCAATTGAAGCC
ATCGCTCGGTTTGACTACACTGGCCGGACCAGTCGGGAGCTGTCATTCAAAAAGGGCGCC
TCTCTGCTTTTGTACCAGCGAGCCTCTGACGACTGGTGGGAGGGAAGACACAACGGAGTG
GATGGACTGGTGCCGCACCAGTACATTGTTGTTCAAGACACAACTGATG------TGGGA
CGAGGAAGTCCAAAGCCTGATGTTGAC-----------AGCAGGGACCTGCTGGAAGAGC
GGGTGTCCACTAGAGGCAGTGCCGCCTCTCCCACTGGAGCTCACGTGGCTGACATCTATC
TGGCAAACCTGA------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------
>Pantodon_buncholzi_mixed|002717|C613505|m.33324
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------ATGGAGAACCTTCACGACAGAGCCATA
CACATCCGCAAGGTCCTGCTGAGCCTTCCTAGCAACACCCTTGTGGTCATGAGATACCTG
TTTGCTTTCCTCTACCACCTCTCCCAGTACAGTGAGGACAACATGATGGACCCATACAAC
CTGGCCATCTGCTTCGGCCCCACTCTTATGTCGGTTCCTGAGGGTCATGACCAGGTGTCC
TGCCAAGCCCACGTCAACGAGCTCATCAAAACCATCATCATCCACCATGAGGCCATTTTC
CCTGGACCTCGTGAGCTAGAGGGACCCGTCTATGATCGTGGTGGGGCCACGGAGGAGTAC
TGTGACAGCCCACACAGCGAGCCCCCCTTAGTGGATGAGCCGGCGCCTGACACGGTATCT
GAGCCCCCTAACAGTGATGATGGCTGCTTGGCCGTTTCAGACTCCGATCCCATTGAGGCC
ATCGCCCGCTACGATTACGTGGGACGCACGGACCGCGAGCTG------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------
>Sargocentron_rubrum_gill_6|014100|scaffold22153|m.27507
ATGACGTCTCCGGCCAAATTCCGAAAGGACAAGGAGATAGTGGCCGAATATGAAACCCAA
GTTAAAGAGATCCGTGCCCAGCTGGTGGAGCAGCTCAAGTGTCTGGACCAGCAGTGTGAG
CTGCGGGTCCAGCTGCTCCAGGACCTGCAGGATTTCTTCAGGAAGAAGGCCGAGATCGAG
ATGGACTACAGCCGCAACCTGGAGAAGCTGGCCGAGCGGTTCCTCACCAAGACACGCAGC
ACCAAGGAACACCTGCTCAAGAAGGAGCAGAGTATTTTATCTCCGGTGAACTGCTGGAAC
CTGTTGCTGGTGCAGGTGAAGAGGGAGAGCCGCGACCACGCCACTCTGTCTGACCTCTAC
CTCAACAACATCATCCCTCGCTTCGCACAGGTCAGCGAGGACTCAGGACGCCTCTTCAAG
AAGAGCAAAGAGGTCGGCATACAGCTGCAAGAGGATCTGATGAAAGTTCTTAATGAGCTT
TACACGGTGATGAAGACGTACCACATGTACAACACCGACAGCATCAACGCCGAGTCCAAG
CTGAAGGAGGCGGAGAAGCAGGAGGAGAAGCAGATGGGGCGCTCCGGTCGGCAGGACGAC
CGACAGACGCCGCGCTCCCCGGACACCCTGGCCAGCGTCAAGTCCGAGGAGAAACACGTC
CGGCGCTCCAGCGTCAAGAAAATTGAGAAGATGAAGGAGAAGAGGCAGGCTAAGTACACA
GAGAACAAGCTGAAGGCCATCAAGGCCAGGAACGAGTACCTGCTCGCTCTGGAGGCCACC
AACAGCTGCGTCTTCAAATATTACATCCACGACCTCTCCGACATCATCGACTGCTGTGAC
CTGGGCTACCACGCCAGCCTGCACCGCGCCTTGAGGACCTACCTGTCTGCCGAGCTGAAC
GTAGAGGCGTCCAAACACACGGGCCTGGAGACGCTGGAGGGAGCGGCGGAGAGCCTGGAG
CCCAACGGGGACAAACAGAAGCTGATGGAGACCTACAACAACGTCTTCTGCCCTCCTGTC
CGCTTCGACTTCCAGTCCCACATGGGAGACACGATGGGTGTGGTGTGTGCCCAGCAGCCG
TTGGAGGGCGAGCTGCTCCAGAGGTGTCAGCAGCTCCAGTCCCGCCTCTCCACCCTCAAG
ATCGAAAACGAAGAGGTGAAGAAGACCATGGAGGCCACCCTGTCCACCATCCAAGACATG
GTGACGGTGGAGGACTACGACGTCTCCGAGTGCTTCCATCACAGCAACAGCATGGAGTCG
GTCAAGTCCACCGTCAGCGAGTCCTATCTCAGCAAACCCAGCCTGGCCAAGCGACGGGCC
AATCAGCAGGAGACCGAGCAGTTCTACTTCACGAAGCTGAAGGAGTTTCTGGAAGGCAGG
AACCTGATCACCAAGCTGGAGGCCAAACATGACCTCATCCAGAAGACCCTGGGAGAGAGT
CAGAAGACTGACTGTTGCCTTGCCAGTGGACGGAGAAACTCTGCAGTACGGAAGCAGGAC
TCGGGTCAGGGCATTCCTCTGATGGTTGAGAGCTGCATCCGCTTTATCAGTCGCCATGGT
CTGCAGCATGAGGGTATTTTCAGAGTGTCAGGTTCTCAGGTTGAAGTCAACGACATCAAG
AACGCCTTCGAGAGAGGCGAGGACCCATTGGCAGGAGACCAGAATGACCACGACATGGAC
TCCATCGCTGGCGTCCTGAAGCTCTATTTTAGAGGACTGGACCACGCCCTCTTTCCTAAG
GAAGTCTTCCATGACCTCATATCCTGTGTCTCGATGGAGAGTCTCCAGGAGAGGGCAGTC
CACATTAAGAAAGTTCTGCAGTCTCTGCCAAGCAAAACCCTCATCATCATGAGATACCTG
TTTGCCTTCCTCAACCACCTGTCCCAGTACAGCGAGGAGAACATGATGGACCCCTACAAC
CTGGCCATCTGCTTCGGCCCCACCCTCATGTCGGTCCCCGAGGGCCACGACCAGGTCTCC
TGCCAGGCCCATGTCAACGAGCTCATCAAGACCATCATCATCCACCACGACACCATCTTC
CCCGGCCCGCAGGACCTGCAGGGCCCCGTCTACACCATCCCCGGGGCGGGAGACGACTTC
TGTGACAGTCCTCACTGTGAGCCCCCCCTAGTGGAAGAGCCTGCGCCTGACACCGTCTCT
GTCAGCCACATCAGCGATGAT------------------GAGTCTGACCCGATTGAGGCC
ATCGCCCGGTTCGACTACTCTGGCCGGACCAATCGGGAGCTGTCGTTTAAGAAGGGCGCT
TCTCTCCTCCTGTACCAGCGAGCCTCTGATGACTGGTGGGAGGGACGACACAATGGAGTG
GATGGACTTGTGCCGCATCAGTACATTGTGGTCCAAGACGCGTCTGACG------GGGGC
CGGGGCAGTCCGAAGCCTGATGTGGAC-----------TCCAGGGACATGCTGGAGGAGA
GAGTGTCCACTAGGGGCAGCGCTGCCTCCCCTACTGGAGCCCACGTGGCTGACATTTACC
TAGCCAACCTCAACAAGATGAGGAAGCGTCCAGAGTCTGGCAGCATCCGAAGAACATTCC
GGGGCTCGGAG------AGTGAAAGCACAAGTCCG---GGAGCCAGCGGTGGCGGAGGGG
GGGTGAGAACGGCCTCTCTTCCTGTTGGGTCAGCCCTGGTGAAAGAGACCGGAGACAAAC
GACCTGTCAGCGCTCACAGCATCCTGAACTCAGTCACTCGCCACTCCTCACTCAAGACCA
AGGTGGAGAGTCCACAGTTACGGAAGACAACCACAGCAGGGCGCTCCAAGAGCTTCAGCA
ACCACAGACCACTGGACCCTGAGGTCATAGCCCAGGTGGAGCCCAGCTCACAGGACATTG
AGGCAGCGATGAGCTCGGCCCTGAGCGAACTGAGGGAGCTGGAGCGACAGAGCACCTCCA
AACACACACACGCACCTGACGTGGTCCTGGACACGCTGGAGCAGCTGAAAGGTGTGTGTG
GTGGTGGAGGAGGAGGAGGAGGAGCCTCGGAGCCCTCCAGCCCGCTCCACTCCCGTCTGC
TGCGGGATGGCGAGGGGGGCTCCACGCACGCCCACCCTCTTCAACGCAGCGCCTCCTCCG
CCAGCGACGTGCCCTCCTCCTTCCGGCCCGCCAAGAGCCA---GCCGCGGAGCCCGCTGC
CCTCCGCCACCTCCCCCTCCCTCTCCTCCTCCTCCCTCTC------CTCCTCTGTGCCCT
CCTTCAGAGAGTCGCGCCCCCCCGCCACCAGGCCCAAGCCAGTGGTGTTCCCAAAGAGCG
GAG------GGGGAGGCAGCCCCGCCATGGGCTCCCCGACCTCCACCGTACCCCCCACGC
CTCCTCCTCCACCTTCAGCCCACACGCACTCTCTCCCGCACACCCCTCCTCCCCCACCCC
CACCTCAGTCTAACGACAAGTCCTGTCCGGCTTAG
>Synodus_sp._gill_5|015947|scaffold21234|m.27550
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------AGGAGGGCC
AACCAGCAGGAGACGGAGCAGTTCTACTTCATGAAGCTGAAGGAGTTTCTGGAGGGGAGG
AGCCTGATCACCAAGCTGGAGGCCAAGCACGACCTCATCGAGAAGACGCTGGGAGAAAGT
CAGAAGACTGACTGTTGCCTTGCCAGCGGACGGAGGAACTCTGCGGTACGGAAGCAGGAC
TCAGAGCAGGGCATCCCTCTGATAGTGGAGAGCTGCATCAGATTCATCAGTCGCCATGGA
TTGCAGCATGAAGGGATCTTCAGAGTGTCTGGCTCTCAGGTGGAGGTCAATGACATCAAG
AATGCATTTGAGAGAGGTGAAGACCTCCTGGCAGGAGACCAGAATGACCACGACATGGAC
TCCATTGCCGGTGTGCTCAAGCTGTACTTCAGAGGCCTGGACCAGGCGCTGTTCCCACGG
GAGGTCTTTCACGACCTCATTTCCTGTGTCTCGATGGAGAGCCTTCCAGAGAGGGCGGTC
CACATCCGGAAGATTCTTCAGGCTCTTCCCAGCAAAACCCTGATCATCATGAGATACCTG
TTCGCCTTCCTCAACCACCTGTCCCAGCACAGCGAGGAGAACATGATGGACCCGTACAAC
CTGGCCATCTGCTTCGGACCCACCCTCATGTCGGTGCCCGAGGGTCACGACCAGGTGTCC
TGCCAGGCCCACGTCAACGAGCTGATCAAGACCATCATCATCCATCACAACGCCATCTTC
CCCACGCCACCAGACCTGCAGGGACCTGTCTACACCCCCCCCAGCTCCGCACATGA---C
TGTGACAGTCCTCACTGTGAGCCCCCCCTGGTGGATGAACCTGCTCCAGACACCATCTCA
GTCAACCGCACCAGCGATGAT------------------GAGTCGGACCCAATCGAAGCC
ATAGCCCGCTTTGACTACTCCGGACGGACCAATCGGGAGCTCTCTTTCAAAAAGGGGGCG
TCGCTGCTGCTGTACCAGCGCGCGTCAGAGGACTGGTGGGAGGGTCGTCATGGCGGCGTG
GACGGCCTGGTGCCACATCAGTACATCATCCTGCAGGACCAGACGGACG------GTGGC
CAGGGGAGTCCCAAGCCGGACATGGAC-----------CCCAGGGACTTCCTGGAGGGGC
GTGTGTCCACCAGGGGAAGCCCTGCATCCCCCACTGGAGCCCATGTAGCTGACATCTACC
TTGCCAACCTCAACAAGATGAGGAAGCGTCCTGAGCCCGGTAATATCCGCAGAACATTCC
GGGGCTCTGAG------AGCGACGGCTCCTCCCCG---GGGGCCGGCGGTGCAGGAGGGG
GGGGGGGGGNNNC-----TCCCGGTGGGGGGCGCTGTGGTGAAGGACAGCTCCGACAAAC
GGCCCGTCAGCGCCCACAGCATCCTCAACTCGGTCACCCGCCATGCCTCCCTCAAGACCA
AGGTGGAGAGCCCACAACTCCGCAAAACAACCTCTGCAGGTCGCTCCAAGAGCTTCAGCA
ACCACAGACCACTGGACCCAGAGGTCTTCGCCCAGATAGACCAAGGATCACAGGAGGTGG
AGGCGTCCCTGAGCTGTGGGCTGGGCGAGCTGAGGGGGCTGGAGAG---GGGCTCGTCCA
AACACACACACACCCCCGACGTGGTGCTGGACACCCTGGAGCAGCTGAAGGGGGTGT---
---GTGGAGGAGGAGGAGGAGGTGTCTCCGAGCCATCCAGCCCCCTTCACTCCCGCCTCC
TGCGGGACAGCGAGGGGGGGCCAGGCCACGCCCACCCCCTGCAGCGCAGCGCCTCCTCGG
CCAGCGACGTGCCCTCCTCCTTCAGGCCCTCCAGGAGCAC---GCCCCGGAGCCCCCTGC
CCTGCGCCACCTCCCCCTCGCTCTCCTCCTCCGCCCTGTC------CTCCTCCGTGCCCT
CCTTCAGGGAGCCCCGCCCCCC--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------
