>Amblygaster_clupeoides|008609|TR18406|c0_g1_i1|m.36408
G-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------AGAACCATGG---------------------
------------------------------------------------------------
------------------------------------------------TCGAGAAGATCT
TCTTAAAGTGCA------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------ACTTCGCTGCAAAATTTGCGGAAG
AGAATT------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------TGATTCACAAAGAGCACTGTCACGA
CACAGGAATAGCCAACATGGTGAAAAATCCCCCCAAAT----------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------TAATTCTTGTGAAATCTGCGCCAAATCCTTCCGCTTTCCAT
CTGATTTGGAAGCTCACAAGTCATGCCATGATCCCAGTCGACCTTTCTGCTGCTCTACTT
GCAGTTTGAGATTCTGGTCTCAGAAGGCCTTAAATCTACATGTTACAATGTCCCATCCGA
AGGTCGAAAGT-------------------------------------------------
-----TTCACCTGCCAACTCTGCAACAAAACCTACTTAACCAGAAAGTCATATGTTAGGC
ATAAAAAGGAAAAGCATAGTAAAGGCTTTGCAGCAAA------TTCTGACC---ATGACG
AAGGAAATGGTTCCTCAGCAGATCAGTT------CGATGTTCAAGATTACATTAATGAAG
AGAGTGACGTGAGTGTTAAGGA---CGAAAATGAGGCAAGT---GAAGACGACTCCGATT
CTGCTCCTTATTTTCCTTGTCATGTGTGCGGCAAGACTTTTTCAACTTCAGAGAGCCTCG
AGGATCATCAGCGTTGCCACCTGGGCGAGAAACCACACGAGTGCGAAGAATGTGGGAAAT
GTTTCTTCCAACTTGTGAACCTGCAGCAGCATCAGCGAAGCCACAAGTCAGAATTCCAGT
GTCAGACTTGTGGAAGAGGCTTTGTCTCGCTCTTTGCCTTGAGGAAACACAAACACTCAC
ATGGCAAGAACCGCCCTCATCGTTGTTCAAAGTGTCATCTGAGCTTCACAGGACCCTCCC
AACTTGCTGAACACATGGCCACGCATCGTGATGAAAATTTTCCCTGCGATCTCTGTGACT
GCACTTTCTCATGTAAAATCACCAGGGCAGAACATCGCAAAACTCACACTGAACAGGAGG
AAGA--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------GCT
TCCCCCATTGATTCCACC------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------ATCAAGTACTCCTCCTTTGACATCG-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>Corydoras_julii_viscera_mixture_8|009054|scaffold16094|m.11462
G-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------GAACAGGCTGGCAAACGGGGGAA----
------ACACTGCAGCATGAC--GAGCTGGAGTGCAAAACCTGCTTGATGAAGTTCTCTA
ATCACGATCAGTTGTCCAGACACGCTGCCATGATGCACTCCACCATCAGGAGGTtcttct
GCAAGACTTGTGGTAAAAAGTTTAGCTCTCTAAAAACTTTAAAAAAACACAACCTGTTTG
TGAAGTGCAAGG--------------TCTCCTACAGACAGAACGATCAGT----------
-----CCACCTCGTCACCAAGGAGTCCCACAGCGCAGCCAACCAGGGAACCCTCCGAACT
GCTGGAACAGATGAAGAACAGAAGCTTAAATCAGTGGAAACACAAGTGTCGCTATTGCCC
CCGGCGCTTTAAGGAGGCGTGTCAATTAACAAGTCATATGCGGCTTCACACGGGAGAAAA
GCCTTACACGTGCACTAAATGTGATGAGCGATTTATCAGGAAAGATTATTTGCAGCGCCA
CATCAGTAAGTGCAGTGGGACATCAGAACGGTCC------GCAGTCCGCTGTGAACACTG
TGCTGAAACCTTTACACAAGAAGCTCTTCAAAAGCATCAAAAAACCTGCGGCACTGTCTC
------------------------------------------CCCTCGGAGGTTGAGAGG
GTCTGGAAGT-----------------CCTCCCGAAGATTCC------TCCTCAACAATT
TCTC--------------------------------------------------------
--------------------TGGACCACAAGGCGGAACCAAAGACCAAGGAGCGTCGAGC
AGCTGTAATCTCTAAGAGTCAGTTA---------------------------------GT
TATAGAAAGGCCGTTTGAGTGTCAGTACTGCAAAATGAGGTTTATCTCGAAATGCGGCAT
GGTGATACACGTTCGGACTCACTCAACAAAATACCTGCTGCTTTGCAAAAAGTGCAAGCA
AGGGTTCTGGAATAAAGCCTTGTATAAAAAACATGTGAAAAAGTGTAAGGGCTTGGAAGC
AGTCGTGCAACCTAAAGAAGAATCGGA-TAAGAAGAGCTCT-------------------
-------------GACAGGGTGATCGTCTTTAATAAGGGCTCCAACACGACTGGAACAGG
GGTTCTACAAACAAAGTTCTCATGCAAGGATCAGACTCAAATAGAAGCCAAGGTTCAGCC
AG---------------------------------TTGTCCATAA---------------
-GTACCAGTGTTCAGAGTGCGATCAGAGTTTTACCGATGGGCTCCGCCTCATAAGCCACC
TTGAGGCTCACGGCCGTGAGGACCAGCTCAGTCAGTCGGTGTCAAAGACGCACAACTGCA
CCCACTGTGAGGAGACGTTTAAAAATGCAGGGTTACTGCAGAGACACCTGAAAAGGCAGC
---ACCAAGAGACAGTTGTTAACATGTGCCCCCTCTGCAAAAAGAAGTTCCGCTATCCCT
CGGATCTGGAACTTCACAAATCTCTTCATGACCCTAATCGACCATTTGTATGCAGCGTCT
GTAAGCTGAGGTACTGGACTGATAAAGCGTTGAACGTTCATCAAAGAAATGCACATTTTA
CAAAAGAACCCCCCAAAACAAGTGAATCTGTGAGTCCAGAAGCTGACCCAGGGCCCAGTA
AATCATTTGCCTGCAGTCTGTGTCATAGAACGTACTCCAGCAGGTCCACGTACCTGAAGC
ATTACCGCCTCAAACACAAAAATACTCCCATGACT-------------------------
-----AGTAACGAGCTTCAGAATGAATC------AAAGGAGCAGGAAACAAAGAGGAGCG
AATCCGATGGGGGTGATGGCGC---CCAGGAAGATCTGAGT---GACAATGACTCTGACT
CTGCCCCTTACTTTCCCTGCCACGTCTGTGGGAAAACGTTCCGTACCTCAGAAAGTCTTG
AAGATCACCAGAAATGCCATCTTGGAGAAAAACCCCATGAGTGTGAGGAATGCGGCAAGT
GCTTCTTTCAGCTGAACAACCTGCAGCAACATCAGCGCAGCCACAAATCTGAGTTCCAGT
GCCAGAAGTGCGGCAAAGGCTTTGTCTCTGGGTTCGCGTTGCGCAAGCACAAGAACACGC
ATCTTAAAACGAAATCTCATCGCTGCACAAAGTGCCAGTTGTGCTTCACGAAGTCTTCAC
AGCTGGCGGAACACCTCCTCACTCATCAGGAGGAAAACTTCCCCTGCGACGTTTGCCAAA
AGACGTTTTCCTGCAAGGAAAGTCGAGAGGAGCACAGGAAGAGCCACGCCGACATGGAAG
AAGAGCTTCCCCCCCTGATCCCGCCCACAAAGC------AGACGCCGG------------
-------------------------------TAACGAGTGCTCCCCAAGTTCCA--CGGC
AGATCGTGCACCAGTGCGAAGCCTGTAAAATGAAATTCCAGGATTTGGAGCAGCTTGCAG
AGCATGTCTGTAACCCAACCGAGGAGAAGCCGTACCCCTGTACCGACTGTGATCAGCATT
TTGTGCACGGCTCCCACCTCAAGAAACATCAGCTAACCCATCAGTTATCTGGAACACGTT
CCTTCCAGTGCAACACCTGCCACCTGAAGTTCAATCATCGCACACACTTCTTGAGCCATT
TGCAAACACACGATCATAAAGA-----------ACCCCCCGAGTCACCGCTGGATGAAGA
CACCAAGCCCCCAAATGCTGCAAAATTTTATCAAGCCAAAA-------------------
-TATACCAGTGCCCCATATGCCCTGAGAGTTTTGCCCAAGCTTTAGAGTTGGCAAGTCAC
CTTTCTGTTCACGCC------------CATATGTGCAACGTTTGCGGCAAGACCTTCCCA
ACCCAGCAACAACTGGAGGCTCACGAGCAGTCCCACCTGTCTGTGGCGACGCAGTACGAG
TGCACTGAATGTGGCAAGAGCTTCCTTGGAAGCGAAGCCTTTCGGCAACATCGCTGGGCG
CACCAGAGGCGCTCTTTTCCCGAA------------------TCCTCTCCATCACCGCTG
CACAAAAAGAGGACCTTGGAGACCTCGTCTCAGGTAATAAACATTGTGGAGGAGGATGAG
GAGGTGGACGT---TGGTGAAGACTTTTTCCACTGCCCCATCTGTAACAAACGCTTCTCC
TCCAGCATCACTTTGCAAGAGCACC---AGAGGCAGCACCACGATGACCGTCCCTTCAAG
TGCCCTGTCTGTGCAAAGGGATTCACCAAGAAGAAGTACCTCGCCCAGCATCAGCTAACC
CACAACAGTCGGCTCTATCCCTGTGGACTGTGTTCCAACACCTTCAAAACCGAGATGGCA
CTTGCAACTCACCAGAAAAACAACCATTCGAAGA---------------------AACAC
CCCTGTGCTCTGTGCAACAAAACCTTCCAAACCTCACAAGATCTCGCCCAGCACGAGTCC
TCACATGCCCAGCTGCAGAGGTCCACTGCCCAGGCGGAACTCAAGCATGCGTGCGACCTG
TGCTACAAGTcgtttaaggaactccatcagctccaaaagcaccaggagacccgcgtggcc
CAGGTGGTGTACGAGTGCACGGAGTGTGACAAAGCCTTTGCCAATTTTAAACTTCTCGAA
GAACATCAGAAAACTCACCTGGTGTCTCTGACTTCTCTGCAGCTCCAGGCCACACCTATC
TTTGTGATTGAGGACTCTGTGTTTGATTAG
>Distichodus_sexfasciatus_gill_4|022134|scaffold31725|m.38774
ATGGCTTATGATGCATGGAATACATTTGATCATTCCAAGACACCACCTGATTT-------
-----AGAGGCTTTAGAGATTTCTTTAGAACCTGGAGATAGTTTTGAAAATCAAATTGAT
CAGCTCGTCCAAGAGAATCTTTCAAGCATGATGGTTTCAGAAGAAATATCCTCATCAGAT
TTGAACTTTTTAAATTCAGATTCTCTGCAGGACCCATGTCATGAACCACTGTGGCAAGGT
GACGTGAAACAAGTAGAGCCAAAAGAGATGCCACCAGAACCTTTGACTTTCTCAGATGAA
ACCTCGGTGCTGAAAATACAACCATGTGAGATAAGCATAGAACCTTCTTTGTTAAATACA
TCTAGTCTTGCAGTTTATTCCGATGTTAGCAGTTGCTCTGAAACAGACCTTGACTGCATT
TCAAATACTTTGTTAGAAGAAACC------CTTGATGCCAACCCGTCATTTCAAGATCAG
AAGATATTAGATATCAGTAATGTGGAAACAAAAGAAATGGTAAAAAGTTTGTCTCCTTTT
TCTAATGGTGACACCCTGGAAGAATTGGACAAAGAGTCGTTGGGAGAGCAAGAAGAAAGT
CTAAAACAAGAAGAGTGTCAAAAAACACCTGAAGAACTTCTCAGGAGTCAAAGTTGTTTG
CATGGCATGGACTGTAGTGATAAAGAAAATGAAAGTAGCACAGAATGTGGTAATGGATGC
ATGTTGGAAAATGAGGAAACCATGGACAGGACGGCAATAACCACCCAAAACTCAGATACT
TGTTTTGAAGAGACAAATAAGGAAAATACAGATACTGTACCAAATCCAACTTCTATGTGT
CAATTGGATTTGAATAATGGTGGGAAGGAAATTGGTCATGAAAATAATGATAATGTTGAA
GATATGGATGGACAAGATGACTGCCAGTTGAAACAGATCAGAAAAACATATACTTCTGAA
AGTTACTCTCAAAACGAATCAGCAACTGAATTTAAAAATGCTGTCTCTGAAAATGACCTA
CAGTGTGACAAA--------GCAGAGGACACATTTTTTGTTACTGAACGCAGCAGTTTTG
AGTTTTTGCAATCTTGTTTTGGCTTAAATAGAGATCAAAAGCTACCATTAATGAACAGCT
TGAATAACAAAAAACTAGACAATGGGAACACACCTTCATTGTCTGGAGATTTATTGGAGA
ATTTGCCTTCCCAATCTTGTGAGGGTGATTCTGTGCAGCCTGCAGTTCTCGTAAAACCTG
CATTTGGATCTATAGAAGCTCAAG--TCCCATGTGGCTCAGTAAGAACTGAAAGTGCACA
TCAAGAAACGGTTAC--AAGTAGAGTTGTGTTGTCATCTCAGAATTTAATGAAAAAACTG
CAGCCTGTTGTACTCTTACGGACAACTGGTTGGGACCAGGGACTT-----GGAAACGGAT
ATCATTGTGCTGTGTGCCAGCATAGCACACAAAGTGTAGATGAGCTTGTTGAACATTACC
ACTCTCAACACTCTACGCATCACTTCCAGTATTGCCTCACCTGTAGATGTTATTTTTCTA
GGTCAC-AATTGGCAGAGCAACATTTCTGTGACAAGTTCATACCGAAAGACCACAACTTA
CTTGAGTCTTTGCc----aagcagtgaggagcAGACCGTGAAGGGTGGTGCAGTGTACAC
ATGTAGGTACTGTAGAAAAGCATTTATCAAACAGCATTACTTTCTTGAACATGAGAGAAA
GCATACAGAAGTTACACAACATAGATGCGCTTGTTGTGGGCTGTACTTTCCTAATGAAGT
TAAACTGTTAAGTCACAGTCGAAAGGTGAAATGCCTACCCATGATTGCAGAACCAGA---
-TAAACTGGCTAAAATGACTTCGGAAACTATCCTTAAAAAGAC---AACAGAACCATTGA
TTGTTTATGGAAGAGACAGAGGCATGATCAAGCTCTATGACTGTTTTGTGAAACTTGAAA
AAATAAAAAAGGAGGAACAGAATTCACTAAACATAAAATGTCCAG--TTTGTGAAAAGAT
TTTCAAATTTAGAGCAGAATTGAAGGCACACCTCAGATCACACTTGCATGAGAAACCATT
TCAGAGTGATAACTGTAAACAGAAATATAAATGGAATCTCAAAAACCACAAAAGTGAACA
GTGTGTTCCACAAAAAAGGCAACCTTGTGGAACCTTGGCACCTCAAAACCTTCCTAAAAG
ATATAAGTGCCCACTCTGTGAAAGGATGTTTAAACATTTTTACATTAGAAATCGGCATTT
ACGTCTGCAGTGCCTGAAAGAATATACACGACTAAGCAAAGGAAAGATTGGAAGCAGGTT
CAAATGTCCTTTGTGTCGCGATACGTTTTCCAATGCTACCAATCGCAGAAGACATATAAA
AAATACCTGCTTTAAGCAGTTTAAACTTAGGAGTCTCA--------TCAAAGAGAAAGAG
TTCAAGGATATAAAGGAAGATGCTAAAC----AACCCAAAAAGAACCAACTACTGC--CC
TTGCGAGGTGCAGAAGGTTATACATGTATAATGTGTCCAATTGTGCTTACACACAAATCC
AGTTTCTATAGACACCTGAAAAAAGTGCATCAAAAGCCTCAAATCCAAAACGA------C
AAAGACACCAACCCATGTGATCAGAAACCATCTACCCCTGAACATCAGAGACCTCAAAAC
GAAGAGTCTA------------------------CTGTTGAGGCTGAGAGTGATCCTTTG
T---CTTGTCACTTCTGTGAGAAAATTTTCCTTTCAGATATCTCACTGAAGAAACATCTA
AAGTTGCATAAGGGAAACAAACCTTTCCGCTGCTTGGTCTGTGGCAAGAGCTTTCAGAGA
CGTGGGCATTTACAAGCTCACAAAACCATTCACAAGCGACGGATACAGTGTTCTGTCTGT
AAGAAGACTCTGCTCTCCATTGGAGACTTGTTGAAACACAGGCAGACCCACCTAACAAAG
GGTTTGCTTAAGTGCCCTGACTGCCCGATGCAGTTCAAGTCACCTGCGTTATTCCTTCGA
CATGTTAAAATCCATCAGCA------------------GGAAGTCAAAGTGAAGTCAGCC
TTAACTCCATATGAGAACCAATCTAAGCACGTGAATGAGGAGGAGCAAAAAGACCACAAA
TTTAAATGTGAAATATGCCAGAAAGCATTTAATGATTCCAAATCATTGAGTGAGCATTTT
TTAAGTCACATACCACCAGAATCATCAGTATCCACATGTCCATTTTGTAAACGTGAATTT
CAGAGTCGAGCTGTGCTGATCCGACATATTCGCCTTCACACTGGTGAAAAATCTTTTTCT
TGTTCGAGGTGTGCAATGCATTTTCACCAAAAAGAAATCCTCAGTGCACATCAGGAGGAA
TGCAGAGGATTGCAAGAACAGCCTCCACCTCCAGTGCCAAAGAC-CAGTCCAGTGCCTGA
CAAAAATGACAAAATAAATAAAGACAAAAGTTTTAATTGCTCTTACTGCCCCCGAGTTTT
CTCAGTTTCACATTGTTTGAAACTACATGAAGGAGCCCACATGGCTAACAGCGTTTTGCC
ATGTTCAAGCTGTGGGAAGTTTTACAGGAAAAGGATAATAAGGAAGCATGAGAAAAACTG
CAGC--AACAATGAATCTCAAACTGACGCTACAGATAACTCAACAAATTCATGTAAGAGT
CAGTCACAAGACTTTAATTCTGATTTTACA-AACAAGGCACACAAAGACATTGGGAATAA
TATCAGCGATCCGTATGAACAGTGGTGCCCGCACTGCTTAAAATGCTTCAGGTACAGAAG
CCAGTTCCTGAGACACCTTAAAACTCACTTAAATAACAAACAATTTAAGTGTGTTCATTG
TGGTCAGGAGTTTGCAAGTGAACAATACTATTTAGAGCATAAGGTCTTATGTGATGGT--
----GAATTAGGGCGATTAACTGACAAGCTACATGAATCTGGAAAGAAACAAATCTTATC
ATTGGATAAATCAAATCTTGACAGTATTGACA-------TACAACTGGGAAATACTCATG
AGCTTAGGTGCAAATTTTGCACAAAGACTTTTACCAAACCACGGAATCTGAGACGCCACA
TTCTTACACACACAGAAGTCAAGCCGTATCGTTGTAAGACATGTGAGAGTTGCTTTTCCC
GACATGATCATCTGAAAGTGCACCAGACACGTTGTAAAGGAAGGAAACAACGACTGGAGG
TCCGCATTGAAAAGATTTCTCTTGACATTGTTGGAACGAGTTGGCAAACTACGATG----
------CAGCCTCAGAATGGT--ATGTTTAAATGTGATACTTGCTCAAAGCAGTTCTTTA
CCCACAGCAGTTTAACACGGCACATTTCAATGCAACATACTGCCTTGAAACCTTTCCTCT
GTACAAAATGTGGTATCAGATATAGCTCTAAAAGGACCATGAAGAGGCACAGTCTCATGG
AAGACTGCAG--------------------------------------------------
------GAAACCAGCAGGCTCAAGTCCGCCAGTCTCATACTGCAGAGAAACATCTAAACT
CTTGCAAGGTATTGATGGACACTACGCAAGTAAATGGAAATTCCAATGTGAATACTGCCC
CCGCCGCTTTAAACATCAAGCGCAGCTCCAGGTTCATACTCGTCTTCATACAGGCGAAAA
ACCGTTTGGATGTTCTAATTGTGGTGAGCATTTCATCAGACGAGACTACCTGCAGCGACA
CTTGACCAAATGTAAGAAAGCAAAAGGAGATGCCCCTGAAAAAGTGCTTTGTGACAGGTG
TGGTGGATTGTTTGTTCAGGATTTTCTTCATGTACATCAAAAGAACTGTGCCATCAACTT
GAAGTCAGCTGATGGTTTCAAGGGTGTAGCCAAGACCTGCAGCCCTTCTAAGATCAAGGG
ATTCTCCTGTGACCGTTGTAGTGAACGCTTCCTGTTGTTCTCACAGCTTCAAGAACACTT
TCTGACAAAACACAGG---------TCTCTGCAGCCA---------GTTAATCTGGAGCA
CCAGCCCCTATTTAGTCCTTTAAGCATAAAGCAAGAGCCAGTGGATGTAAAGTGTGCAGA
GAACCTGCCAAGCAAGAGTGATATGCATACTAATAACAGCAGTAAAAATACAGGTGATGA
AAAAGAGAGACCATATGAGTGTCAGCAATGCAACATGAGATTCCTCACTTCCTGTGGTCT
TACAAGTCATTTGCGTGCTCATTCATTACAATACTCATTTTTTTGCAAAAAATGTAACAA
AGGATTTTGGAACAAGAATGTCTGTCACAAACACACCAGAAGGTGTAAA------CAAAT
TAACACAAAAACTGAGTCAAGCCTGGA---TGCAGATTCAT---------CGGAAATAGA
GTATACTTTGAATGAGACTGTCCTGGTTATTAATAAGGGTGCTCAAACAACAGGAACTGG
AGTACTGCAGACTAAATTTTCATGTAAGGATCAGGATAAAGGAAATGCCGAAAATGACGT
G---------------------------------------CGCAA---------------
-GTATCATTGCTCTGAGTGTGATCAAACATTCACAGATGGACTCAGGCTTATAAGTCATC
TGGAAGACCATGGGCGTGAAGACCAGGCACATAGAC---TGGGCAAAGGGCATCGGTGCC
ATGTATGTGGTCAAATGTTTGACCAAGCTGGAATCCTGCAAAGACATTTGAAAAGGAAAC
---ATCAGGAATCCACCAAGAACACCTGCCCTGAATGCTTTAAAAGCTTTCGTTGCCCTT
CTGATTTGGAATTCCATAGGACTCGTCATGATCCCAATCGGCCGTTTGTTTGTGACCAGT
GTCAACTGAGGTTCTGGACAGCAAAATCTTTGTGTCTTCATCAGAGACAAGTTCATTCAA
GTACTGATCCCCAAAAAACAAAGGAGACTAA------------------------TCTGA
AATTATTTTCTTGTCATCCTTGCAATAAGAGTTACGCAGTTAAAGGGTCGTATTTAAGAC
ATTGCAGACTTAAACATCCAGAAGGCATAAACAGA---------------------CTTA
ATAGCAAAGAGACACC------------------TGAGAAACAGCAGTTGGACAACAGTG
AACCTGACACAGATGATGCTGA---TGAGGAAGGTTCAAGT---GATGATGACTCTGACT
CTGCCCCTTATTTTCCTTGTCATGTCTGTGGTAAAACATTCCTGACATCAGAAAGTCTTG
AGGATCATCAAAGATGTCACCTTGGGGAAAAACCATTTGAATGTGACGAATGTGGCAAGT
GCTTTTTTCAGCTTATCAACTTGCAGCAGCATCAGCGTAGCCACAAATCTGAGTTTCAGT
GCAGGATGTGTGGAAAAGGTTTTATTTCACTCTTTGCTCTGCGCAAACATAAGCAGTCCC
ATGTTAAGAAACGTCCCCATCGTTGTACAAAGTGTCATCTAAGTTTCACAGGATCATCAC
AGCTGGCAGAACACATGATCACTCATCGTGGTGAAAATTTTCCCTGTGATCTGTGCAATG
AAACATTTACTTGTAAATTAAGCAGAGCAGAACACCGCAAAAGCCACACTGATCAAGAGG
AGGAGCTTCCTCCCTTGATTTCACCCATAAACC------AGACTTCAC------------
------------------------CTGAGGCTGATGGTCCTTCAAAAAGTGCTGTTCAGC
ATTACAAGCATCACTGTGGAATATGTCAGGTGCTGTTTCCAAATGCAGATCAGCTTCTAG
AACATGGTTGTAATCCATCAAAAGAGCGTCCATATTCCTGCCCAGAATGTAACAAGCATT
TCTTGCGTGGTTCACACCTCAAAAAGCATCAGCTCAGTCATCAGTTATCTGGACCACGTT
CGTTTCAGTGTAATAGGTGCCACATGAGCTTTAATCACCGGCATCATTTCTTGACCCATT
TGCGAACCCACAGAGAAGAAG--------------CTCCAGACACCCAGATCGACAAAAA
GACTGAGACAGTAAGCACCAATAATCTAAACAAAGACAAAA-------------------
-TTTATAGATGCCCAATTTGTCCTGAGAGTTTCTCCCAAGCCTTGGAGCTAGCCAATCAC
CTTTCTGTCCATGCC------------CACATGTGCAATGTTTGTAACAAGACTTTTGCT
ACAAAGAGCGAACTTGAGGAACACGAACAGAATCACTTATCTGCTGCTACACAGTATGAG
TGCACAGAGTGTGGGAACAGTTTTCTTGGTAGTGAGACATTCCGCCAGCATCACTGTGCT
AGAAAGAAACGTTTGGCCTCAGACAAAAC---TCTTGGACATTCATCTCTGTCTCCACCT
TATAAGAAAAGATGTTCTGAAACGTCATTGAAAATAATCAATAATGAGGAAGAAGAAGAA
GAGGTTGATGT---CGGAGAAGACTTTTACAATTGCTCGATTTGTAGCAAACGTTTCACT
TCCAGCACAAGTTTACAGGAGCAC------AAAAAGCTACATGATGCCCGTCCTTATAAA
TGTCTGGTTTGTGGCAAAGGTTTTACAAAAAAGAAATATCTTTCAAATCACCAACAGTTA
CACAGTGAGCGACCTTATCAGTGTGACTTTTGCTCTGAATCCTTCAAAACGGAACACACT
CTTTTTACCCACCATAAAA---------------------------------CCCAACAT
CAGTGCTCGGTGTGTAAAAAAATGTTTCATTCATCGCGCGATCTTTCAATGCATGAACAA
AAACATGCAGAATTGCAAAGA------CAGAAGGAAATTGGGGAACATAGATGTGATATG
TGCTATAAATCCTTCAGTCAGCTTTCTCAGCTGCAAAAACATCAGGAAAGTCATGTTGGA
CAAGTGGTCTATGAATGCACAGAATGTGAGAAAGCCTTTGCTTTTCCAGATCTTTTAGAA
GAACATCAGCAAAGTCATGCAGCTTCTACTGATTCTTTGTAG------------------
------------------------------
>Gasteropelecus_sp._gill_3|005501|C955773|m.50981
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------GA
GAGCCTGTTGAGCAGCAGTGAAGTG---------AATGTGCATCAGATCACGAATGGTGA
AAAGGAAAAAAACCATCAATGTCCTCATTGCAAAATGAGGTTCATCAACAGAGGTGGACT
TTCGATGCATATACGCACTCATACAGCAGAATACCTGCTTTTTTGTAGTAAATGCTCCAA
AGGATTTTGGAGCAAAAACATAATGCTGAAACACATGCGAAGGTGTAAGGGCCTCAAAAT
CATTCCAAAAAAGGAACCCGATCCGGAATGTGCAGCTTCAT---------CAGAATCGGA
G------CTTAATGATACAGTTCTTGTGATTAAGAAGGGATCTAAAACAACAGGGACTGG
GGTGTTGCAAACTAATTTTTTATGCAAGGATCACAAAAAAGATGTGGACAAAGAGGACGC
AG---------------------------------TTGTCCATAA---------------
-GTATCAGTGTTCGGAGTGTGATCAAAGTTTCACAGATGGCCTTAGACTTATAAGTCATC
TGGAGGATCATGGCCGTGAAGACCTGGAACGCAGAT---TGGGCAAAAAGCACCAATGCC
AAGTTTGTGGTAAGCCTTTTGATCAAGCTGGGCTGCTGCAAAGGCATATGAAGACCCAAC
---ATTCGCAAATACTTCCGAATACGTGTCCTCAATGCTTCAAAAACTTCCGCTCTCCAT
CAGATATGGAACTCCATAGGTTGTGTCATGATCCTAATCGGCCAGCTGTCTGCAACACAT
GCCAATTGAGGTTTTGGACACCAAAAGCCTTGAGAGTTCATCGAAGGTTTGCTCATCAAG
CTACTGACCCTGTCAAGGCAAGTGAGTCTAG------------TGAAGTAGGGCCTCCTA
AAATGTTTGCATGCCATCCCTGTAATAAAACATATTCAACAAGAAAGTCGTACATGAGAC
ACTGCAAAAATAAACATCAGGGAAGATCAGAAAGC---------------------CGTG
AGGATAAAATTGCTCCCAAGGATCAACCCTTGGACAAGGATCAACCCTTGGACAAAAACG
AATCTGACGTCAGTGATGCAGG---TGAAGCTGG---AAGC---GGTGACGATTCTGACT
CTGCACCCTATTTCCCTTGTCATGTCTGCGGTAAAACGTTTGTGACGTCAGAAAGACTCG
AGGACCACCAAAGATGCCACCTTGGTGAGAAGCCTTATGAATGTGAGGAATGTGGTAAAT
GCTTTTTCCAGCTGTTAAACCTGCAGCAGCACCAGCGTAGCCACAAGACCGAGTTTCAGT
GTCATTTGTGTGGTAAAGGTTTTATTTCACTCTTTGCCCTTCGCAAGCATAAGCACACTC
ATGTTACCAAACGGCCCCATCGCTGCACAAAGTGCCACCTGTGTTTCACAGGATCTTCAC
AGCTGGCAGAACATATGATCACTCATCGTGACGAAAATTTTCCCTGTGATCTTTGCAACA
AAACATTTACCTCCAAATCCAGCAGAGCAGAGCACCGCAAGACCCACGATGA------GG
AGGAGATCCCTCCCTTGATTCCACCCTCGAAGC------AACCTTCACCACCACCTCCAT
CTCCATCAGAACCGCAACCACAGACTGTTTCAAGTACTTCACCAAATAATTCTCATCATC
ACTTCAGGTATCGCTGTGGAATTTGTCAGCTGCGATTCCGAGATCCAGAACAGCTTTCGG
AGCACGGCTGCAGGCCGGCAAAAGAGCGTCCGTATTCGTGTCCTGAATGCAATAAGCATT
TCTTGCACAGCTCTCACTTGAAAAAGCATCAGCTTAGTCATCAGGTGTCCGGCCCGTGTT
CTTTTCAGTGTAAAGATTGCCACATACAGTTCAAGCAGCGTAGTCAGTACTTGAACCATT
TGCGGAGGCATTGTAAGAAAT--------------CTCCCAACTCTGAGCTCCAAGAAGA
AGTGCTGTTGTCGGACACCAATGATTTAAATGAGGACAAAA-------------------
-TTTACAAATGCCCGATTTGTCCTGAAAGTTTTGCTCAAGCGTTGGAGCTAGCAGATCAC
CTGTCTGTCCACTCG------------CACATGTGCAAAGTTTGTAAAAAGACTTTCTCC
ACCAAGCAGCAGCTAGAGGAACATGAACACTGCCATGTATCACCAGCTACTCAGTATGAG
TGCACGGAGTGTGGAAAGAGTTTCCTTGGCAGCGATTCCTTTCGCCAGCACAACTGTGCT
CGCCAAAAGCGCTCTCTTTCAGACGCACA---GCTTGGACATTCATCCAAATCACCTCCT
CGCAAAAAGAGCTCTTCGGGAGCTTCATTTGAAATCGTGGTGGAGGAGGTTCAGGAGGAG
GAGG--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------AGGAGGAAGTGGAGAAT---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>Lepidogalaxias_salamandroides_Head_2|019981|scaffold18650|m.25493
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------TAAGTCTTGACCACGTGGGTAGGGGCTGGCAAAATAAGTTGGAGA
AATCTAAAACGGGAGAACAAC---TGATTAACTGCAGCTCCTGCACAAAAAGTTTCACCA
GAGAGATCAATTTGGCTAGACACGTAGCTTTGAGACATACAACTGTGAAGCCCTTCAGCT
GTAAGCGTTGTGGCACTTCTTTTACCCATGAATGCTCTCTGAGAAAACACAACAACTTGA
TTAAGTGCCAGAAGAAAACCCAACAATTTGGTACAAGTTCAATGATTAAT----------
-AGATCAAACTC---AAAAGAAAGTTTCACAAATGAATCGTGCAGAGAAACATCTAGAAT
TCTACATCGGAGCCAGTGGCATTACAAAGACAAGAGGAAATTTCATTGCATTTATTGCCC
TCGTTTATTCAAAAATGAAGAACAACTGAAGGTGCACACTCGTCTGCACACTGGAGAAAA
GCCTTTTGGGTGTGCTAGTTGCGGTGAACGATTTATCCGTCGTGACTATTTGAAGCGGCA
TTTGACTAAGTGCAATTTGAAGGGTGAAAATA---TTACTAAGGTGCTTTGCAACAGTTG
CGGTGAGTTATTTTCTAAATATGAACTTCAGAACCACAAGAGGAGATGTG---TTCTCTC
TAAACCATCCATCTGTAACCCAACGGTTTCTACTGCTCGCAGTCCTCAAAAGATCAGGGG
ATTTTCCTGTGCAAATTGCAGCGATCGATTCCTACTGTTTTCACAGCTACAACAACATTT
TCTTAATAAACACAGAGAAGACACAATTCAGAAATCACCAATACAAGCGCCACCATTTCA
GCATCAGTTATCTAACATAGTGAACATTAAGGAAGAGCCTTTGGATGATGAGTATGAGG-
-----------------------------CTCTGGGCAGGGATAACATCTTGAAGGAAGA
GGTTAAAAAAGCCTTTGTTTGTCCGCACTGTAATCTGCGGTTCATAAATACGAGTGGGTT
AGGAATGCACATGCGTACCCACTCGGGAAAGTTCCCCTTTTCTTGCCAAAGATGCAAAAA
GGGCTTCTGGAGCAAGAGCAGTCATCGGAAACATCTGAGGATATGTAGA---------AA
TGTTGTGGATTTCAATGAAGCTGCAAA---TATGGAATCTGTTATCGCTCCTGACGTGGA
TTTTCCACTCAAAGATACAGTCCTCATTTTTAACAAGGGTTCTGAAGCAACAGGCACTGG
TGTACTGCAGACAAAATTTTCTTGTAAAGAGGACATCAAGGAT---TCAATTGAGAATCC
AGAGAAGGAGCAAACTTCTAACAAAGCAAGCAACTCAGTCCACAA---------------
-GTACCAGTGCTCAGAGTGTGATGAGAGTTTCACTGATGGTCTTTTGCTTATTAGTCATT
TAGAGGACCACGGTCGGGAAGAGCAAG------------TGCGGAAACGGGGACAATGCC
CTCATTGTTTCAGATGTTTTAATCAGGCGGAATTGTTAGCACAACATATAAGAACACACA
---TTGATGTGAATGCAACTTACCCTTGTCCAGAGTGCCCTTTGACCTTTTCTTATCCTT
CTGAACTGGATATACATCGAACCTGTCATGACCAAAACCGACCATATGTCTGTAGTTTTT
GTAAACAAAGATTTTGGACAAACGTTTCTTTAAGCAAACACATCAGTTCTCTACATACAG
AACAAGAAACC---------------------------------------------CCTC
CATTGTTTGCTTGCCAGCTCTGTGACAAAAGCTATGTACACAAAAAATCCTATACGAGAC
ATTGCAAGTCCAAGCATAGCAACGCACAGAGGCAA---------------------ACAA
AAGGTAACATGTCATCGATGCAAGAATT------TGATTTTGAGGTGGATTTCCAAGATG
ACAGCGACGAAGACAGAGGAGAAAGTGAAAGCGATGGTAGCGAGGAAAATGATTCAGACT
CTGCGCCTTACTTCCCGTGTCACGTGTGCGGCAAGTCCTTCCCCACCTTCGAAAGTCTTG
AGGATCATCAGCGTTGCCATCTGGGTGAGAAGCCTCATGAGTGTTCCGAGTGCGGTAAAT
GTTTTTTCCAGCGGGCACAGCTGCAACAGCACGAGCGTAGCCATAAGTCTGAGTTCCAGT
GTCAAACGTGCTGCAGAGGGTTTGTGTCGCTATTTGCCTTACGCAAGCACAAGCACACTC
ATGGGAAGAGCCGTCCCTACCGCTGCGCTAAGTGCCAGCTAAGCTTTACCGGGCCTTCGC
AACTTGCGGAGCACATGGCTACTCACCGGGATGAAAATTTTCCATGCGATCTCTGCAACC
AAACGTTCTCTTGCAAAATAGATCGGGCTCAGCATCGGAAGGTCCACACAGAACTGGAGG
ATGCCATACCCCCTTTGCTTTCATCCGACGACACCACAGAGCCCCTTTCTCCCCACTCAT
------------------------CCACTTCATCTAAATC---------------GGAGC
AGTTGAAATATCGTTGTGGGATTTGCCACGAGCGCTACAGAGACCCAGAGCAACTGTCTG
AGCATGGTTGTTTAGCCGCCAGGGAGCGCCCTTATTCGTGTCCTGAATGCAGCAAGCACT
TCCTGCATGGTTCTCATCTCGTGAAGCACCAGCTCAGCCACCAATTATCATGTTCCAAAA
CCTACCAGTGTAATCGGTGTCAAATGAGTTTCAACAACCAAAATCACTTTCTCATCCACT
TAAAGGGACACGGTGATGATGACACTGGAGAGGATTCCCAGTTTCTGCGGGGAAAGGAGG
------------AGATCCTAA-----CCAACCAAGAGAAGA-------------------
-TGTATAAATGCCCAATTTGTCCACAGAGTTTTTCCCATGCTATGGAGCTGGCTGCTCAC
CTTTCCATACATTCTG---AAAACTCTCACACATGCAACGTTTGTAAATTGACTTTTTCT
TCCAAAAGCAAACTCACGGATCACGAGAAGTATCATCTAGCTGCTTCCCCTCAATATGAG
TGCACTGAATGTGGTGAGAGCTTCTTGGGCAGTGATGCTTTCCACCAGCACAACTGCTCC
CATATGCAGTGTGCGACCACAGACCCTAAAATTCATAAACAATCATCTCCCTGTCCTTC-
-----AAGTAGGTCTCCAGCTTCTTCAACGAAGGCAATGG---ATAAAGAGGACGAGGAC
GACGTCGACGT---AAGGGAAGACTTCCATAACTGTCTTGTCTGTTATAAAATCTTCTCC
TCTGACCAGAGTCTCAAGGAGCATCAACTACGGCAGCATCCAGAAGGAAATCCATTCTCA
TGCCGGGTTTGTGGAAAAGGCTTCACGAAGAAGAAATACCTCAAAGACCATGAGAGACGT
CACAAG---------TGTTTCTGTGACATGTGCCCTGCCTCCTTTAACAACAAGAAGTTG
TTGTGGTTACATAAAAGACTACACAGTGAAAATC------------------ACCAACAC
CAGTGCCCAGTGTGCAACTCCAATTTTGTCACGAAAGAAGAACTGTGTCATCACATGAAA
AGACACACAGAGT---------------TTAAATCTGCTGGTGACTACCGCTGTGACATG
TGCTACAAATCTTTCAGTCAGTTGGCACTTCTTAGGCAGCACCAGGAAACACATGTAGGG
CAGGTAGTGTATGAATGTACGGAATGTGACAAAGCATTTGCTTTTTTCCATCTCTTGGAA
GAACATCAAAGTACTCATGCTCCCACTGCACCATCTCCACCC---------ATACC----
--------------------------CTAG
>Sargocentron_rubrum_gill_6|020891|scaffold29349|m.41324
A-----------------------------ACTTCCAGAAGACCACTGTAGTTGCTTCAT
ATAACATGGCTGCTAATGACAGTATTAGA----GAAGATGACTTAGAAGATCAA------
------GTCCAGGA------------------------AAGGGAAAGGAACGAATCAAG-
---------------------------------------CGAAAATCAAGACAAAAAAGA
GGCTTGTGATAAGCTGA------------------AAAACTCAAGTCTTGTCCCCATGGA
TGGTCAA-GATAAAAATGTGAACAAAGATGATCAAGACAAAG-----------AAATGCA
---------GCAATCTGCCCTTGAATGTGCAGAT--------------------------
------------TCAGAGGGTATCAAGGTGTTCGATTCCCAAGATTGTCCTCATGAACAG
AAGGAAT---ATACATGTACCATGGCTGCAGCCGGCACTGCAGAAGGTGAAAAT------
---GACAGTCATACTTTAGAA---------------------------------------
----------AGCAGCAACCAAGATCATC-----AACCTTTTA------AAAGTAGATCT
GAGTACATTACCTGTAGTGGTTCTGTTGAGGACAGCAAC------TGCGATACTGTTTGT
ATGAGTGAAGATAATGAGAACAGTGTTTGTA-GTCAATTAGTATCCTGTTTACAGCCAAT
TAACTC----------------------------CAGCATCAACATAAATCCCTGTCTCG
AAATGGAATGTA------------------------------------------------
------------------------CAAGTCCAGCAGAGAACACAAATGCATATTTTC---
--------------CAGATGAGGAACTG-------------------------------T
CAGTGCAACAAAGTCATATGGCAGTAGAACCACCAGGTCTTACTGAA---GATGTTTCTG
AAATAAGACAATCACTTCAGGAGTTGCATGCATCTGAAGAACCATCAATGGTTGGCATGT
TGTTTGGTGA---------------------ACCTCTGTCAAGAGCAGATTC--------
-------------TCCCTGTGAAGCTGAT------------------------GAAACAA
AATGTGGAACTAATCAGGTTCAAGAAACCTCTGTAGCTGGACATGAA---AACGAAAGCA
TGAAGGAACAAGCACCTCAGCTGAAATGCTCTGT-------ACAAATGAGGAAACGTCTG
CAGCCAGTTGTCATTTTGACGAC-----CTTAGAACCAAGAAATTCCACAAATAAGGCAT
ATCACTGTTCAGATTGCCAACACACAACTGAAACTGTAGATAATCTAATTGAACACCACC
ACTCTTGCCACTCCTTGCACAAATTCCAATTTTGCCAGACCTGTA-ATATCTCCTTGATG
AGTAATGAACAAGCAGAAAAACATTTGTGTGGT--GTAACTGATGAAGCCCATCAGCTCT
CTTTTGATTCTAACTTAAAGAAGAAAAGAAACAGAC-----------ATAACCTTTACAA
GTGTAACAAGTGCAGGATGACATTCTCGAAATTATATCATTACATCAAGCATATGCGGAC
TCACACAGGCAAAACACCATTTAAGTGTAATGGATGTGGCGTGTATTTTGCACAGAGTAG
TAGCCTGCACAGACACCAGCG----------TGCACCTGGTCGATGCCAGGGCAAGAAAC
TTCCAGTTTCAAAGACAAACTCTGATGCCATTATCAATAAAACTGAAATGGCAACACAAA
AGGGCTTGGTACAAAACGGCCCATATGCCAGTATGCCTGAATGTTACGTGAAGCTTG---
-----------------TAGATGTCTGTAAGACTAATGTATGTAGTTTTTGTGGAAAAGG
CTTCGTAACTGCAGAGAAACTCAAAAAGCAC---------------CATTACAATGTACA
CAAGGGCAAGAGTGGGACAGTTGCACTTAATCAGTGTACCAAAAATTTC-AGTGCCAGCA
AAATTCAGCAAAACAGAAGCAAAGAGGCAAGA-----------------------GGAAA
ACATAAATGCCCGCTCTGTCCACGGGTTTTCAAGTACTCCTACAACAGAGCTCGACATCT
ACGT---GACTGTATTAGAGATTTAACCTATGGTGGCAAAGGAAAAATTGGCAAAAAATA
TAAATGTCCCTTGTGTCATGCTACCTTCACGTTATCATCTAACAGACGTAGACATATTAA
AAACACTTGCCTGAAAGAAT------------ATCTCAGTCAGCTTTCAAAGAAGAAGAC
T----GGGTGT-GAGGAAAATGATGAACAGAAAAAACAAACACGTCCAACCTCAACAGCC
CCTCAGACTGTGCCACGCTACAAATGCAATCTCTGTCCAGCCATTTTTTGCCATGCCTCT
GGTAAATACAGACATATGAAGAAA---CATGAGTTGTTTAAAATCACTGGCAAATTGTTC
AAGTACAGGGATTCAAGTTTT------TTTCCTGTCTCTACGCAAACAAAATTCAGTAGT
AAAAAGATTGAAGAGTGTAAGGATACCTCAACTTCAAATGAAACCAGTAGCAGCCTTTCC
TTTACCTGTCGCTTTTGTGGAAAATGTTTCAGCACTGCATTGTCACAGAAGAAACATGAA
CGCAATCACAAAGGTGAAAGACCTTATCGCTGTTTGGAATGTGGAAAGGGGTTTAAGAAA
CACGCCTATCTGATTGCTCATAAAATGGTTCACCAGCGAAGAATACAATGCACTGTTTGC
AGAAAGATCCTTCCAACTATTGGGGAATTGATTCAGCACAGAAAAACACATCTTAAAAGG
GGGATGCTACAATGCCCAGATTGTCCAATGCAGTTCCAGTTCCCTGTGTATCTACTTAGA
CACATTGTCTCCCACAAACATGGGGAAAAGAAAGAACTGAAGATGGAAGAGAGACCAAAA
TTAAAGCCA---GAGCTGTCCTCAAAATCTTCGACTGAGCAGGAGGAGGAAAAGC---AG
CTACAGTGTTCCTTATGCAAAGAGGTATTCAGCGATTCCCAGACACTACGAAAGCACTGT
CTCAAACATAT---ATCTGGGTCCTCTTCGCGCCAGTGTCCGTTTTGCCAACGTCATTTC
AATTGTCGGCGCTATTTACTTCGTCACATGAATAGACACACTGGAGACAAACCTTTTCCA
TGCACTATCTGTGGGAAACAATTTCACCGCAAGGTGTACCTTCAACTTCACCGTGAGAAA
TG--------------------TTCAGCTACCCAACCCAGACATGCAGTCGTTAGTCAGA
C----------AGATAAGCGTAGAAAAACATTTCAG-TGTTCCTACTGTCCACGGGTGTT
TTCTAGGAGAAACCGCTTGAAAAAACATCATAATGACCACAAGTCAAATTCATTGGTTGT
CTGCACAAAATGTGGGCAGTTCTTTGGATATACAAAATTAACACAACATGAGAGAGACTG
CCGTGGAACATCAGAGCTAAACATTGGTTTATCTTCTCCTAATGGTCATTGTGGGAAAAT
TAATCAAAAGGTTCAAGAAATGCCTCTGCAGAACAATGCA---ACAGGAACTAAGAA---
------------GCTTCAGCATAACTGCCCTCACTGTCCGCAGAAGTTCAAGTACAGATC
AATTCTCTTGAGACATCTTGTTTCCCATACTGGTGAGCAACCCTACGCATGTATGCACTG
TGGCCATAAATATGGCAGTCAGTCAATGTGTTTACAACACGAAGCTTTCTGTGATGGTAT
TTACAGAGAAGCGCAATCAAAGGTCAAG--ACTGGTATCTCAACAAA----------ATT
GTTGAATGCATCCAGTGTCAG-AGAAGTAGCAGAGAAGCAACAAGCAGAAGTTGAAGGTG
AATACAAGTGCAAATTCTGCACTAAGACTTTTATGAAGTCGCGAAACTTGAGACGCCACA
TCTTGACACACACTGAAGTCAAGCCTTATCGCTGCAAAACCTGTGACAGTTGCTTTTCCA
GGTATGATCATCTTAAAGTACATCAGACTCGTTGTAAAGGGAAAAGACATCGACTGGAAG
TCTGTATACCCAAAATCAGTTTAGATGATGTTGGGAGGGGTTGGCAAAATAAATTGGATA
AACTGACGATTGAAAAGCAGCAGACATTTGAGTGCAACATCTGTCCAAGAAGCTTCTCAG
CTCAGTCTAAATTGTCCCGACACTTCACTATGTTCCATGCTAC---AAAGTCATTTAGTT
GC---TGCTGTGGTGCGTCATTTGTTCATGAGAAGTCTCTGAAAAGACATAGGCGGATCT
TTAAATGCAGCA--------------GTGTCTACACTGAAACAAGTGGTACTCTTCCGGT
GAACACTAATCCACAAACAGAAAATGTGACAAAAAAATTTCATGGAGTGACAAATAAAAT
TCTACAGAGGATCCAGCCTTACTTTAACAAAAAGCATAAATATTCCTGTAATTACTGCCC
TCGATCTTTTGGAAACAACTGGCAGTTGAGAGTGCATACCCGCTTGCACACAGGTGAGAA
GCCCTTTGGCTGTGAATATTGTGGTGAGAGATTTATACGGAGGGATTATTTGCAacgtca
ttcagcaaagtgcagcaagaGAGAAGAGCAAA---TTAACCTAGTACTTTGTGATCGATG
TGGAGGATTTTTCTCTAAAGGCAGTCTTGAAAACCACAGAAAAAGCTGCACCTCCACCCC
ATGCCGCTCTGGCCACAACCAACA---CTCCAAGCCTCAAAGTCCACCT------AAGGG
ATTTTCATGTGCATACTGCAGTTCCCGTTTCTTGATATTTTCACAGCTTCAAGAACATTT
TTTAAATGCACACAAACAATATACAGTTTTGAAGCCACCTGGATCTACTGCTCCTCTGCA
GCAGCATCTGTCAAATATAGTGAGCATCAAGGAAGAGCCTTTGGATGTGAGAGACAGTGA
TAAACAGCTGCGTGGTGATGGAAACCTATTGTTTGAACAAGGTAACTGTTTTGATGTTGA
CATGGACAAACCTTTTGCCTGCCCATACTGCAGCATGTCCTTTATAAATAAATCTGGGCT
GAGTGGCCATGTACGTGTACATTCAAAAGAGCATCCTTTCACCTGTAAAAGATGCAAGAA
AGGCTTCTGGAATAAAAACCTACACCGTAATCACACCAGGAGATGTAGAAGACTTGGAAA
TGTTGATAAGATGAATTCTAACCTGGA---TTCAGACATCTCTTTGACTACAGAGATGGA
TTTAGCACTGAGTGACTCTGTTCTAGTGTTAAAACAAGAATCTCAAACGACTGGCAAAGG
GGTTTTACTGACCGACTT---------AGGTGACTTAAAAGACATACCACTACAGAATTC
AGGAGGAAACCA----------GGAGCAGAGCAGCTCATCTAGAGAGAAGAAAGCTGTGC
AGTACCAATGTTCAGAATGTGATCAGAGCTTCACAGATGGTTTAATGCTCATTAGTCACC
TAGAGGACCATGGAAGAATGGAACAAG------------AGAAAAAACGCAATACATGTT
CTAAGTGTGGGCGGGTATGTGCCAGTCAAGGAAATCTTGAAAAACACATGAGAATGCATG
GGATTCATAAGAC------ACATTCTTGCCCTGACTGCTTTAAGGCATTCCCCTCCTCAT
CTGAGCTTGAAACCCACAGAGCAAGTCATGACACAAATAAACCATTTGTTTGCAAAGTAT
GTAAACAGAGGTTTTGGACAAGACCATCTTTGTGTAATCATTACAGTGAAAGCCATCCCA
ATGATG------------------------------------------------------
---TATACAGTTGTCGTTTCTGCAATAAGAGCTATTCAATCAGAAAATCACTTGTTAGAC
ACTATAGGATGAGGCATCAAAACAGTCGAATGGATGGATATGTTGATGGTT---CTGTGA
AGGAAAAGAGGAGTTCTGAACAACAATC------CAGCATTCAAGTCAATGTCACTGATG
AAAGTGATAAAGACAGCAAAGA---TGAAGATAATAGTAACGAGGACAGTGACTCAGATA
CGGCACCCTACTTCCCCTGCCATGTCTGTGGCAAGACATTCCTTACATCAGAAAGCCTTG
AGGATCACCAACGATGTCACCTCGGTGAAAAGCCACATGAATGTGCAGAGTGTGGAAAAT
GTTTTTTTCAGGCATCCCAATTGCAACAGCATCAGCGAATGCACAAATCTGAATTTCAAT
GTCAGACATGTGGCAGGGGCTTTGTTTCTCTTTTTGCATTGCGCAAACACAAACATACCC
ATGGCAAGAGCCGTCCTTATCGCTGCTCCAAATGTCTCCTCAGTTTCACAGGACCCTCAC
AACTGGCAGAACACATGGCCACCCACCGTGAAGACAATTTTCCATGTGACATATGCAATC
GCACATTTTCCTCAAAGAGTAGTAGAGCTGAGCATCGAAAAAGTCACTCTGATTCAGGTG
AATGTTTCCCATCTTTAATTTCACCTGAAGAACAGAGAAAGTCTCCAT------------
------------------------CTCTTTCAGAATGCTCCTTGACAGTTGCAA---AAG
AACTTAAATATCGATGTGGAATTTGTAATGAGCGTTTCAAAGACCCAGAGGAGCTCTCAG
AACATGGTTGCAGGGCATCCAAAGAACGAACATATTCATGTCCAGATTGCAATAAACATT
TCCTGCATGGATCTCACCTGAATAAGCACATGGCCACCCATCA---------ACTCAGTG
CATATCAGTGTAGTCAATGCAATAATACTTTTTCCTCTTCTCAGCATTTCCTCAGCCATT
TGAAGAATCATGGTGATAAGA--------------ATAGTGCAGCAGAAATGAAAGG---
------------------TGGCAGTGTCGGAAATGAGAGAGGAGGGCATTCCCA-----T
GTTTTCAAATGCCCAATATGCCAACAGCATTTTGCCAATGCCACTGAACTGATAAATCAT
TTTCCAGTGCATTCTG---ATGATATTTATGAATGCAAGATCTGCAAATTGCGTTGTTTC
TCTAAAAATAAGCTTGAGGAACATCAGCGCTGTCATCTGACTGCAGCTACTCAGTTTGAA
TGCACTGAGTGCTCCCAAAGCTTTTTGGGAAGTGATGCCTTCCGCCAGCATCACTGTTCC
CGTCGCCAGCATGCAGGA---GAGTT---------GGAATATTCAGATCCATCA------
---AACAAAAAGTCCCCTGTCACTAGCAATCAAGCGATGA---------CAGAGGAGGAA
GAGGTTGATGTTACTGGGGAGGACTTGTATAATTGTCCTGTCTGCTCAAAGTGTTTCATC
TCCAAAAGTAGTCTCTTGGAGCATCAAAATAAAGAGCATCCAAATGAAAAGCCATTCAAG
TGTGAGCTTTGTGGAAAAACATTCACCCTGAGGCGGTATCTTAGGGACCACGAGCGAAGG
CATCG-------------------------------------------------------
-----------TCAGAAAATGGACAATGAAAAGAAAGTCCAGTTTGTTGAAAAACAGTTT
AAATGTTCTCAGTGCCCCATTATAGTCGACACAGCGCAAGATCTGTCATTGCACATGAGA
ATGCACGCTGAAC------------------AAGAGGTTGGGGAGCACCGTTGTGATATG
TGCTACAAGTCATTTAGCCAGCTGTGTCTGCTTAGACAGCACCAGGAAAGTCATGTTGGT
CAAGTTGTATATGAATGCACAGAATGTGACAAAGCATTTGCTTTTCCTCACCTCCTGGAG
GAACATCAACAGACTCATG------CTGGGCCCTCTCTGTAA------------------
------------------------------
>Synodus_sp._gill_5|018013|scaffold23521|m.31555
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------ATGACTCATACAAAGAAGAAAGCATTTAATT
GCACCCAATGTGGTAGTTCATTCTCTCAAGAAAAGACTCTGAAAATCCACAAAAAGCTAA
AAAACTGCAAAG--------------GTTCATCCATCATAAAAAATCAGCCTCTGCTAAA
AGAATCTCTTTCACAGGGAGAAAATCTGGCAAAGCCATCACACAAAGTGTTGAATCCAAA
TTTG---AGGATTCAGACTTACTCTGGGAAAAAGTGGAGATATGCCTGTAAATATTGCCC
TCGATTTTTCAAAAGTAGTGAGCAACTTAGAGTGCATACCCGTCTACATACAGGTGAGAA
GCCATTCCAGTGTTCCTGCTGTGGAGAGAGGTTTATCCGGAAAGATTATTTGCGACGCCA
CTCAGCCAAGTGTCAACCTAGTGAAGA---------TGATCTCGAGCTTTGTGACAAATG
TGGAAGTTCTTTTTCCAAGGAAAACTTGAAAAACCATCAACAGAGTTGCTCTGTCTCACC
AAATTTGTTGGATCAGAATCAACA---AAAGAAAATTCAAAACCCACCA------AAAGG
TTTCCGTTGTGCTTACTGCAACTCCAGATTCTTGTTGTTTTCACTGCTTCAGCAACACTT
TATTGACTGTCACAAAGAGGATTCTCTTTCGAAGCCACCAGTCTCTGCTCCTCCACTACA
GCAGCAACTGTCAAGAATGGTGAACATCAAAGAGGAACCTTTGGAAGATGAGTATTGTGA
AAGACAGCTGACCGGTGATGGAAATCCCTTATTTGAACAAGATGATGGTTCA---CTTAA
CACTGACAGGCCTGTAGCATGCCCACACTGTGACATGCGCTTTTTAAATAGAGGAGGTCT
AGCAGGCCACATGCGTACACACTCTCTTGATTTTCCTTTTCCCTGCAAGAAATGTAAAAG
AGGGTTCTGGAACAAAAATCAACAGCGCAATCATTTCAGAAAATGCAGATTC------AA
AGTAGTCAACACCAGTGCCAAGGCACA---ATCAGTTGCAACAAGCACCACAGTAGTGGA
CAGCGCACTGAA------TATTCTAGTGTTCGACCAAAGCTCTAAAACAACTGGCACTGG
GGTGTTGCAGACCAACTTCTCATGCAAAGATGACCCAAAAGACACACCAACTCACAATTC
CACTGAAAACCA----------GGAGCACAAAAGCTCATCTACAGAAATGAAAGTAGTGC
AGTACCAGTGTTCAGAGTGTGATAAAAGTTTCACAGATGGCTTATTGCTCATCAGTCACT
TAGAAGACCATGGACGAGTGGATCTTG------------AGAAAAAGGGAAATACATGTC
CTAAATGTGGAAAGATATGCACCAGCCCTGGGTTTCTGAAAAAGCATATGAAGATGCATG
---------------------------------------------------CCTCCTCAA
CTGAGGCTAATGTAGAAGGAGTGTGTTATGACCAAATTAGACAGTTTATCTGCAAGATAT
GCAAACATAAATGTGGGAATAGTCAAGCTTTAAATAATCATTACACTGAAGCTCATCCTG
GAGATG------------------------------------------------------
---TATATACTTGTCAAATCTGTAACAAAAGCTACACACTCAAAAAGTCACTGAGTAGAC
ATTACAGGATGAGACACAAAAACTCCCGGATCAGTAAAAGATTTCATTACCATACTTCAC
CAGAAGAGGATGATGCTGATCAAGAAAC------TAGTACACATGTTTTTGCAAATGAAG
GAAGTGACACAGACAATGAAAA---TGAAAGTTAT---------GATACTGACTCGGACT
CGGCACCCTACTTCCCGTGCCATGTCTGTGGCAAGACATTCCTAACATCAGAGAGCTTAG
AAGATCATCAACGTTATCATCTTGGAGAAAAACCCCATGAGTGTGCTGAATGTGGAAAAT
GTTTTTTCCATGCATCGCAGCTGCAACAACATCAGCGGGCACACAAATCTGAATTTCAGT
GTCAGATATGTGGCAGAGGTTTTGTCACACTTTTTGCTTTGCGTAAACACAAACATAGTC
ACAGCAAAATTCGCCCACATCGCTGCTCTAAGTGCACCCTCAGTTTCAAAGGTCCTTCAC
AACTGGCAGACCATATGGCAACACACCTCGAAGATAATTTTCCATGTGACATATGTGATC
GTACATTCTCTGATAAGGGCAGTCGAGCTGAGCATCGGAAAACGCATGTTGAGGCCAGTG
GAAATTTCCCTACCTGGACTGAGTCAGAAGAAAATAGAAAGTCTCCAT------------
------------------------CAACTTCATCTGAATCCTCTTCAACTTCAA---AAA
ATCTGAAATACCGATGTGGGGTTTGTGCAGAGTATTTCATAGATCAAGAGGAGCTTTCAG
AACATGGCTGCCATTCCTCTAAAGAACGACCACACATGTGCTTGGACTGCAATAAATATT
TTTTCCATGAACATCACCTAGCTAAGCACAGGGCCACTCATCATGCATCGCAACCATATG
TCTATCGATGTCATAAATGCAGCGTGAGCTTTGCCTATCGTCAACATTACATCAACCATT
TAAAGAGACATGGAGATAGTG--------------ATCTAGAAGCAGAAATTAAACG---
-----------------------GACTCAAGAAAGAGAAGAACACGGGCCTCCAAGTGTT
TTTTATAAATGCTCTTTTTGCCCTGAACAATTTGCAATGGCAATGGATTTGATAAAACAC
ATGTCGGCACATTCTGAAAAAAATCACCATGAATGCAAAATTTGCAAGTCAATTTATCCC
TCCCAAAGCAAGCTGGAAGAACATGAGCGATGTCACCTAACTGCAGCAACTGAGTATGAG
TGCACTGAATGTGGCCAAAGTTTCTTGGGTAGTGATGCTTTCCGCCAACACCATTGTTCC
AGTAGGCAGCATGGGAAAACTGAGAC---------TAAACATTCACAACTGTCA------
---AGCACAACTTCCCCGGAAGCTTTAAAACGAGCTGTCG------------AAGAAGAG
GAAGTTGATGTTACTGGAGAGGACTTCTTTAATTGCCACGTTTGCTCAAAGCGATTCTCT
TCAAAACGTGGCCTCCTGGAGCATCAAAATAAAAACCATCCCAATGAACAGCCATTCAGA
TGTGAGCTTTGTGGAAAAAACTTCGCTCTTAGAAAATATCTCTTGAAACATTTACAAAGG
CACAAT------------------------------------------------------
---------------AAAATCGATATTACAAAAT---------------------CTTTC
AAGTGCTCTCAGTGTCCTGTCACATTAGAAACCGCAAAAGCACTCACTGTGCATATGAGA
AACCATGCTGAAG------------------AAGCAGTTGGCGATCACCGTTGCGATATG
TGCTACAAATCATTTGGCCAGTTATCTCATCTTCGGCAGCATCAGGAAAGTCATGTTGGG
CAAGTTGTATATGAATGCACAGAATGTGACAAAGCATTTGCTTTCCCTCACCTTCTTGAG
AAACATCAACAGACTCATT------CTGGGCCCTCTCTATAA------------------
------------------------------
