>Amblygaster_clupeoides|041713|TR694|c15_g1_i1|m.979
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------GGGGAGGAGGAGGAG------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------GAGGAGGAGGAAG-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----AGGAACCATCTG---------------------------------CAGAGACGCCA
CAAAACAAAAAACTGAAGACCTCCACTCCCCACTCGTTCCCCAAAGCTAATAAGAAGAAT
GTCAGTGTTCCTTTCCGAAGAATAAGAGAGGAGGAGATTGAAGTGGACCCTCGATTGGCA
AACAACTCCTTTGAAGCAAAGAAAGGAGCAGATGGGGACTGGGGCCAGAAGGCCAATAAC
ATGCTCAAGTTCACCAAGGGCAAGTCGTTCCGCCACGAGAAGACCAAGAAGAAGCGCGGC
AGCTACGTGGGCGGTGCCATCTCCACCACCGTCAACTCCATCAAATTTGACAGTGACTGA
>Gasteropelecus_sp._gill_3|003660|C932748|m.47808
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------GCAACTGCTCGTTTTGAAA----------------------------------
-----------------CATCACTATTA--------------------------------
----AGCACGTTTT----------------------------------------------
-------------TTTTTTTGTCTGTCCCGTGTTCTCT----------AAAGAAAAG---
--CAATGATCCTTTCCGTAGAATAAGAGAAAATGATGTTGAGGTGGACCCCCGGCTAGCA
GACAACTCCTTCTCTGCCAAGATGGGATCCAGTGGAGACTGGGGTGAGCGAGCCAACGAC
GTCCTGAAGTTCACCAAAGGGAAGTCCTTTCGTCATGAGAAAACTAAGAAGAAGCGTGGC
AGTTACAGAGGAGGTGCCATCTCCACCTCCGTGAACTCCATTAAGTTTGACAGTGAATAG
>Melanotaenia_praecox_viscera_mixture_8|005717|C459020|m.32726
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------GCATCTAAAGCAGCTACCCCAGCTAAAACTGCT
GTT---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------AAACCTGCTGCTGGAAA----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----AGCAGAAAGCAGCTCAGACTCTGACTCTTCC---TCTGAGGAAGAAGAGCCAGCT
AAG---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------GCTAAGCCAACAACAGCAAAGAAAGCTATC
CCACCATCAAAGCCCA--------------------------------------------
-------CCACACCTGCAGCTAAACCATCTGCTG--------------------------
-CAGCAGAAAGCAGCTCTGACTCGGAC---TCCTCCTCTGAAGAGGAAGAAACAG-----
-CCACGGCTAAACCAACAGCGGCCAAAC--------------------------------
-------------------------------------------CGACAGCTGCTAAAC--
------------------------------------------------------------
-------------------------------------------------------CAACA
GCAGCTAAAACAGCTACACCAACTTCAAAGCC------------------TGCTACTCCT
GCTGGAAAAGCTGGAGCAGTACCACAAAGCAGCTCTGA---ATCTGACAGCTCAGACTCT
GAGGATGAAG------------TAGCCAAGCCTGCAGTGAAGAAACAAGCCACAGCAGCG
GTCAAGAAGCCTGCAGCTGCCAAGACTAACA------CAGCAAAGGTTGCAGCGAAGCCA
ACACAGTCTTCATCCAGCGACGACAGCTCTGATGAGGAGGAAGAGACTAGTAAAAGTAAA
ATAAAACCTGCTACCCCAGTTGTAGCAGCCAAGACAACCCCAGCAGTTAAACCTAAA---
GAGAAAAGTAGCAGCTCTTCAGACAGTTCATCAGATGAGGAAGACGCACCAAG---TAAA
GCAGCCACTGCACCCACCACCCCCACAATAA---ATACCAATGGAAAGAGAAAAAGAGAT
G---AAGAATCATC---------CGACAGTGAAGAGGAAGAAACGCAATCAAAAACTCCA
AAAAGCAAAAAA---GTAACAACCACGCCACAAACTTTTCCAAAAGCGAATAAGAAGTCT
TCAAACGTACCCTTCCGTAGAATTGTGGAGGATCACGTTGAAGTGGATCCTCGTCTGACA
GACAATTCTTTTGAAGCCAAGCGTGGAGCCAACGGAGACTGGGGCCAAAAAGCTAATGAA
GTGCTGAAGTTCACTAAAGGCAAGTCATTCCGCCATGAAAAGACAAAGAAAAAGAGGGGG
AGCTACCGAGGTGGAGCCATTTCCACTACAGTCAACTCCATTAAGTTTGACAGTGACTGA
>Pantodon_buncholzi_mixed|016471|scaffold19126|m.27524
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------ATGGGAAGGGCACAAC-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----ACCCAAAACAGCAGCAAAGCCAGCAGCAG--------------------------
-------------ACTCTTCCTCCAGTGACAGCAGCTCTGAAGATGAGAAGCCGGCGAAA
GCTGCAGTCAAACCTGCTCCGAAGAAAC--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------CTACAGCAAAGCCTGCTGCTGAGGAGAG-------------
------------------------------------------------------------
--------CTCATC------------TTCAGAGGAGGAGGAGGAGGCTAAGCAGAA----
--------------------------------------------------AGTTAAA---
------------------------------------------------------------
---------------------CCTGCAA------GTAACGACAATAAGAGGAAGCGGGAT
A---AAGAGTCTTCAGAGGAAGAGGAGGATGAAGAGGAAGCTGACCAAACGAAGACCCCC
AAGGGTCATAAATTGGCACCGGCTGCACCCCACtccttccccaagtccaagcaaaAG---
--------------------AATAAGAGAAGAGGAGATTGATGTGGACCATCGGCTTGCG
GACAACTCCTTTGAAGCCAAGTACGGGGCGAGCGGAGACTGGGGAGAGCGGGCCAACGAC
GTACTCAAGTTCACCAAGGGCAAGTCCTTCCGCCATGAGAAGACCAAGAAGAAGCGAGGA
AGCTACCGGGGCGGCTGCATCTCCACCTCTGTCAACTCTATCAAGTTTGAAAGTGACTGA
>Sargocentron_rubrum_gill_6|004149|C712401|m.47982
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------GCTGC----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----AGCAGAGAGCAGCTCTGACTCCGACTCCTCT---GAGGATGAGGAAGAACCAGCC
AAG---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------GCCAAGT---CAGCAGCTAAGCCGTCTGTT
TCAGCGTCAAAGCCTG--------------------------------------------
-------CCACCCCTGTAGCAAAGCCTGCTGCAG--------------------------
-CTGCAGAGAGCAGCTCTGACTCTGACAGTGACAGCTCTGATTCTGAGAATGAGG-----
-CCTCTGCCAAACCCGCAGCCAAGAAAC--------------------------------
-------------------------------AAGCTCCAGCTGCAGCGACGGCCAAGCGC
CCTGC------CCCTGCTGCTCCTGTCACCAAGGCTCCTGCAGACTCAAGCCGTGTTGTG
TCCGATAGCTCCAGTGATGATAGCTCCAGTGACGAGGAGGAATCTAAGAAGGCAGTGCCA
GCACCCAAGAAGGCAGTGCCAGCACCCAAGCTAGCAGCTGTGAAGGCACCTTCGGCCCCA
ACAAAGAAGGCAGAAG---------AGAGCAGCTCTGAGTCTTCAGACAGCTCTGACTCT
GAGACGGAGGCCAAGACCACACCTGCAAAGCCTGCTGTCACCAA----------------
--TGGCAAGGCAGCAACACCCAAGGCAGCCACCCCAGCAGCCAAAGCCCCAGCCAAGCCA
GCTGAGTCCTCATCTAGTGACAGCAGCTCTGAAGAAGAGGAAGAGGTCAGTAAAAAGACT
GTAAAACCTGCTACCCCAGCTGCAAAAACCAAGACCCCCCCAGCAACAACAGCTAAACCT
AAGGAGAGCAGCAGCTCCTCAGAAAGTTCGTCAGATGAGGATGAAGGGACCAC---TAAA
GCAGCCACAGCACCCACCACCCCTGCAGCAAATGGTATCAATGGAAAGAGAAAAAGAACT
G---GAGACTCACC---------TGAAGGTGAAGAGGAAGAAGCTGAAATTAAGACTCCA
AAAACCAAGAAA---GTAACAACCACACCGCAGACCTTTCCTAAAGCCAAGCAGAAGTCT
GCCAATGTACCTTTCCGTCGAATAAGAGAAGAGGAAGTAGATGTAGATCACCGTCTTGCA
GACAACTCTTTTGATGCAAAGCTTGGATCCAATGGTGACTGGGGCCAGAAAGCCAACGAT
GTGCTCAGGTTCACCAAAGGCAAGTCCTTCCGTCACGAAAAGACGAAAAAGAAGAGGGGT
AGCTATCGTGGAGGAGCCATCTCCACCTCAGTCAACTCCATCAAGTTTGACAGTGACTGA
>Scleropages_formosus_red_gill|031490|scaffold5146|m.6578
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------ATGAAGGCTACT
GCTCTG------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------TGTTGCT---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------CAGTGCAGCCTGCACTT---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------CCCACAG--------------------------------
------------------------------------------------------------
-------------TCCTGATCCCTGCGCTCTCATTTTCGCCCAG----------------
--------------CTGGGGTCTAATGGCGACTGGNNNNNNNNTGGATCCCAGGCTGCTG
GACAACTCCTTTGACGCCAAGCTGGGGTCTAATGGCGACTGGGGCCAGAAAGCCAATGAA
ATGCTGAAGTTCACAAAGGGCAAGTCCTTCCGCCACGAGAAGACCAAGAAGAAGCGCGGA
AGCTACAAAGGCGGGACGATCTCCACTGCTGTTAACTCCATCAAGTTTGAGAGTGACTGA
>Synodus_sp._gill_5|024502|scaffold7317|m.8064
ATGAAGAACGTCTCGTTGACATCTACAACTTTTGGGCAAAGTCCCCAGAGGCAAAGAAAC
GTAAGGCTGTGCAGAGCGAAGCTGACGACAGCAGCGTTCCAACCGCTAAAAAGGCCAAGG
CAGACAGCTCGAGCAGTGAGGAGTCGAGCAGCGAGGATGAGGCTGCAGCCGCCCCAGCAA
AGCCCACTCCAGCAGCTGTTAAGGTTGCACCTGCCAAAGCAGAGAGTAGCAGCAGCGAGG
ACTCCAGTGACTCTGAGGATGAAGCAGCAACAGCCAAAACTCCAGCAAAGACACCTCCAG
CTAAGAAAGCAGCGCCTGCCATGGCTGGCACAAGGAAGAAGGACACCAGCTCTAGCAGCG
AGGAGTCNNNCACAAGGCCAAGCACCTGCAGCCATTGCTGCTGTTCCCACTAAAGCTGCA
GCTCCAAAGAAGCAGGAAAGCAGCAGCGAGGAGAGCTCAGACTCTGAGGAGGAGCCAGTG
AAGCCTGCTGCCCCACCAAAGGCCTCTCCTGCTCCCGTTAAAGCTCCTCCTGCAGCAGAG
TCGAGCAGCGAAGACTCCTCCTCCGAGGACGAGGCTCCTCCGAGCAAAAAACCCAGAGCT
GGATCATACAGCGCAGTTCCACCCCCATCTCAAGGTCAGAAGGCCaccagcaCCCCACCT
GTCCCTGCTGCCGCCAAGGCTAAGGAGTCTTCAGACAGCAGTGAAGACAGTAGTGATGAC
AGCAGTGATGAGGAGGCAGCAGCTAAACCCAACAAACAACCAGTGAAGACCACCCCTGCC
AAGCCTGTGGCTCCTACATCCAAAACAAAGAAGCAAGACTCCAGCTCTGAGAGCACAGAT
TCAAGTTCGGACGAAGAGGAGGAGAAGAAACCTGCTGCTAAAAAGGCTCCAGTAAAAGCG
GCACCAGCAAAGGCTACCCCTGCAGCAGAGGAAGACTCTTCCTCCAGCTCGGAGGAGGAG
ACAAAGAAACCTTCGGTGAAGGTGACTCCCGCTAAGGCTACCACTCCNAAGCAGGCCTCT
TCTTCAGATGAGGACTCCAGTTCTTCAGAGGAAGAAGAGGCAGCAGTGAAAAAGCCTGCT
GTTACTCCAACAAAAGCAGTCCCCGTCAAGACTCTTGCAGCCAAAAAGGATGAATCCTCT
AGCTCAGAATCTGACAGCAGCTCTGAAGATGAGGCTCCTGCAAAACCTGCGACTAAAGCT
TCAGCTGCAGCCGTATCTGTCCCAGCTGCCAGTACTGTTTCAACACAGAAAGCCCCTGGA
AAGGTAGCTGAAAGCAGCTCTGAATCTGACTCTTCCTCAGATGATGAGGAGGAGACGGCT
AAGCCAGCAGCTGTGAAAACTGCTGCGAAAACTGTTGTGAAAACGACTGCTCCAGCCAAA
CCCTCTACCCCTGTAGCAAAGCCTGCAGAGAGCAGCTCGGATTCAGATTCTTCCTCAGAG
GATGAGGCGGCGGCGGCGAAGCCCATTGCTCCAGCTAAGCCAGCAGCTAAANAACCGTCT
ACACCAGTGGCTAAGCCGGCAGCAGAGAGCAGCTCCGATACAGATTCATCTTCAGAGGAT
GAGGAGGAAGTAGCTAAACCAGCTGCCCCAGTTAAACCAACAGCGgctaaaccgtctaca
ccagtggctaagcctgcagagagcagctccgattcagacTCTTCAGAGGATGAGGAAGCA
GCTAAACCAGCTGCCCCAGCTAAACCAGCAGCTGCTAAACCGTCTACACCAGTGGCTAAG
CCTGCAGAGAGCAGCTCAGATTCAGAC---TCTTCTTCAGAGGATGAGGAGGAAGCAGCT
ACCACAGCTAAACCGGTAGCTGCTAAACTGCCTACACCATCGGCTAAACCTGCAGAGAGC
AGCTCTGAGAGTAGCTCCGATTCAGAGGATGAGACCACAGTAGCAACAACCTCCAAACCT
CCAGCCAAGAGCCCAGCCCCTACCCCAGCGAAAACTCCTGCTGACTCCAGCAGTGAGGAC
TCGgatagctccagtGAGGA------------------------GGAGGAGGTGGTGCCA
GTGTCTAAGCCTGCCACG-----ACCAAAGCC-------------GCTGCTCCAGTTCCA
GCCAAGAAGGCAGAGG---------AGAGC---------TCATCAGACAGCTCAGATTCA
GAGGTAGACTCCAAGGCCACTGCAGTCAGCCCTGCTGTCACCAA----------------
--CGGCAAAGCTGCTACATCGAAG------------------------GCCTCCAAGCCA
GAGTCCTCATCTTCAAGTGACAGTAGTTCAGAGGAGGATGAACAGCCTTGTAAAAAGACT
GTGAACTTGACCACCCCAGTAGCAACCCCCAAGACTACCCCAGCAACCTCAGCTAAAGCA
AAGGACAGCAGCAGCTCATCTGAAAGCTCGTCTGATGAAGAAGAGACGTCGAAACCTAGA
GCAGCCACTGCACCCACCACCCCAACTACAAATGGGTCTAATGGAAAGATGAAAAACTGT
GAACAAGACTCTTC---------TGAAAGCCAAGACGAGGAAACTGAAGTGAAGACTCCG
ATCAATAAGAAA---ATAACATCCACACCACATTCTTTTCCCAAAGCAAAAAAGAA---T
GCAAACGTACCTTTTCGTCGAGTAAGAGAGGAAGAGGTTGAAGTGGATAATCGCCTGGCT
GACAACTCTTTTGATGCTAAGCGGGGGGCCAACGGTGACTGGGGCGAGAAAGCCAACCAA
GTGCTTCGGCACACCAAGGGCAAGTCGTTCCGCCACGAGAAGACGAAGAAGAAGCGTGGC
AGCTATCGCGGGGGAGCTATCTCCACCACTGTCAATTCCATCAAGTTTGACAGTGACTAG
