>Amblygaster_clupeoides|030754|TR56044|c0_g1_i1|m.75485
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------GAGGTGGATAAAGCTGAATTGAAAAAGCATAAGGATTCTATGGCATTGAAAAG
CAATCTGCTGCAACTCAACCTGCGAGAGAGACGGTACAAATGTGATCAGTGTGAGAAGAG
TTTCTTTCAGTTGTGTCACCTGAAAAAACACAAGTTCACTCACTCAGACTTGAAACCCTA
CCTCTGCACAGAGTGTGGAAAGAACTATAGCTCCCAAGAGAGTTTCCGGGCACACATCTT
GATGCACCGAGGAGAAAGGCCTTATAAATGCCAACAGTGTGACAAGAGGTATGGGTTAAA
ACGAGACCTAAAGGAACATGAGGTGCTGCACACAGGGGAGAAGCCCTTTGTCTGTGATGT
GTGTGGGAAGGCCTTCGCCCGCCGGCCTTCTCTCCGCATCCACAGAGAGGCGCACAGGGC
AAAGGAGGCTAACT------ACCAGCCTCCCAAGATCAAGTGTCCTGAATGTGGCAAAGA
GCTGGCAAACTCGGGCTCCCTGAGGAACCATATGCGTCTGCACACAGGTGAACGTCCCTA
CCCTTGCCCTCACTGTGGGAAGACGTTTCGCCAGCGAGGCAACCTGCTTGGGCATTTGCG
CATCCACACTGGAGAAAAGCCCTACAAGTGTGACTACTGTGACCAGCACTTCTCCCAAGT
GCCTGAACTGCGGCGGCACCTTATCTCCCACACGGGAGAGGTGTACCTTTGCACTGTCTG
TGGGAAGGCTCTGCGTGACCCTCACACACTCAGGGCCCATGAGCGTTTGCACACTGGTGA
AAGACCTCACAAGTGCAACGTTTGTGGAAAGGCCTACACAATGGCCACAAAACTGAGGAG
GCACATGAAGT---CCCATTTGGAGGACAAGCCATATAAATGTGAGAAATGTGGTGCTGG
TTACACTCTCATGCAGAGCCTCATTCGGCACCAGCTTTCTCACAAGAAGAAGC-------
--------TGAATGAAGCCATGGCCACTCATGAGACAAGTCATCCAGCCCCAGTAAGAGG
ACGTCCCCGAAAGACAGGACAGAGGTGTCTAACAAACACGTGGCCTGTTGAAACAGAG--
----------------
>Distichodus_sexfasciatus_gill_4|026333|scaffold6349|m.6779
ATGTGTTTTCTTTTGAAGCAGAAAAATGAAATGGAAACGTGCCAAATATTATCCCGAAAC
TACTGGATGAGGTATGCTTGTAGTGCTCTGAGTGAAGATGAGAGGAATGTTGTTATGCAT
GAGGTGGATGGGAAGCTCTGTCTTAGGACCTGTAGGAACATCAGTCCAGGAACAGAGCTA
CTGGTCTGGGCAGAGCAGCAGAAAGCTCCATCTGAAACTGTGGAGCTTAATGACAGTGAG
TTGACAGTCCTTCCCAAAGTAACCAAACAAAATTCATCGGAAAACAAGGCCGAGGAGACT
GCTTCTGTGGAACAGGTGTCTAAAGTGGCAGCACATACACTGAAGGATAATTATCTATTC
AACAACGGAGAAGAACGGGAGACAAGGCCTCAAACATGTAAAAGCAGTCATCTGGAAAGG
AAGGATTTGAATAAAGAGTGTGAAGGAGAAGCAATTGAAACAGCTGGCATTTCTGAGTTG
AGTAACATTACTGGAGCCTCAGTGCTTGAGATTAACAGATCTGAAACATTTAA-------
-----------AGGAGCTGTGAGAGTCAGCTCTCGACTAGCAGCCAAACCTCGCAAGGTC
CACTCACTATGCAGCCGTATTCACAAGCGAATGCGTGGTAGGCCAGACATGTGTGATACA
AATGAGAACCCAACCAAAGAGGCTAAAACTGAAAATGCACAA-GCACAGGAAGAGGATTT
TAATTC---TGAGGAGGACGTCCGAGAAGGGCCCTGCAAAAATCGGAGAGTAAGGGTGGG
GTCTCCAGACATGCTTAGCCTAAGAAAAAGGAAGTACAAATGCGAAGAGTGTGGCAAAAG
CTTCTTCCAACTATGTCACTTAAAGAAGCACAAGTTCACACACTCAGAGCTGAAGCCATA
CACTTGTGCAGAGTGTGGCAAGACCTACAGCTCCCAGGAGAGCTACCACGCTCACTTGCT
CATGCACCGTGGCCAGCGGCCCTACAAATGCCAGCAGTGTGACAAGAGCTACGGTCTCAA
ACGTGACCTCAAGGAGCACCAGGTGCTTCACACAGGCGAGAAGCCGTTTGTCTGCGATGT
ATGTGGCAAAGCCTTCGCGCGGCGACCCTCACTGCGTGTCCATCGGGAATCCCACAGGGT
CAAAGCGGCAGATCTTGGAACCCAGCCTTCTCAGATCAGATGCTCCGTgtgcaacaaaga
gTTAGCGAACTTGGGCTCCCTTAGAAACCACATGCGGCTACACACGGGCGAGCGACCCTA
TGCCTGCCCACACTGTGACAAGAGCTTCCGCCAGCGCGGCAACCTACAG-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------
>Lepidogalaxias_salamandroides_Head_2|017917|scaffold16169|m.21677
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-ATGCATCGGGGCGAGAGGCCCTTTAAATGTCAGCAGTGTGACAAGAGCTATGGCCTGAA
GCGGGACCTTAAAGAGCACGAGGTTCTCCATACGGGGGAGAAGCCCTTTGTCTGTGATAT
CTGTGGGAAAGCCTTTGCCCGCCGGCCATCACTGCGTATTCACAGGGAGGCCCACCGTGC
AAAGGAGGCCAATT------ATCAACCACCCAAGATCAAGTGCCCAGAATGTGGCAAAGA
ACTGGCCAACTCAGGCTCACTGAGGAACCACATGCGCCTACATACAGGTGAGCGGCCTTA
TCCCTGCCCCCACTGCGGCAAAACATTCAGGCAACGAGGTAACCTTTTGGGCCACTTGCG
CATTCACACTGGGGAGAAGCCATACAAGTGCAACCACTGCGATCAATACTTTTCCCAGGT
ACCTGAACTCCGGAGGCATCTTATTTCGCATACTGGTGAGGTCTATCTCTGCCCCATCTG
TGGCAAAGCCTTGCGGGACCCTCATACGCTACGGGCCCATGAGCGTTTGCACACGGGTGA
GCGGCCCCATGTATGTGAGGTTTGCGGGAAGGCCTACACCATGGCCACCAAGCTCCGTCG
ACACATGAAGT---CTCATCTTGATGATAAGCCCTACAAATGCCAGACATGCGGTGCTGG
TTACACTCTGATGCAGAGCCTGGTACGTCATCAGTTGTCCCACAGAAAGAAAG-------
--------AGGAGAAAGCTGCTGGAGAGCTAGCAAACGCTCTAGCAGCTCTGG-------
-------------------------AGTCTGGC---------------------------
----------------
>Pantodon_buncholzi_mixed|021386|scaffold7924|m.9338
A-----------------------------ATGAACACACAC------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------AGCA
GCTTCCA---------------------------------------------------TC
ACATACTAAAAGGGGGAAAAAACAAGTGTGTGAAGTTGAAAGAAAATCCTTGCAGAGCTG
GAAGGTTGGA--GACCTAAGGAAATCAAGTGAAAGTGATATGTGTGTCATTAAAGAGAAG
TGCCCCATCCAGGAAGGAGCTTCACCTGTCAAAAGGAAGCTTGAGGAGGTCAATGCGGGT
GCTGTGGCTTCAGGAACCTTCAGGAACAGTGCTCGTCTGGCTGCTAAACCCAGAAAGCAC
CATGTACTGATAAGCCGCATTCAGAAGCGTCTACA----------------GGAGCGCAA
ACTGAAGGTCCTACATGAGAGGGAACAAAGAAATGAAAAAGTAGGTGAAAAAGAACCTGA
GGAACTGCATGAGGCTTCAGAGCAGGGAGTCTCAGGAGAGAATGTTCCAGTAGAACAGGA
TGTTTCACAC---TTGGACACAAGAGAAAGACGCTATAGCTGTAATGAGTGCCACAAGAG
CTTCTTCCAGCTGTGCCACCTGAAAAAGCACAAGTTCACGCacgcAGACTTTAAACCATT
CCTGTGCACAGAGTGTGGCAAGAGTTACAGCTCACAGGAGAGCTTCCATGCACACCTGCT
CATGCACCAAGGCCAAAGACCCTTCAAATGTCAACAGTGTGACAAAAGCTATGGCCTCAA
GCGAGACCTGAAGGAGCATGAGGTTCTGCACACAGGGGAGCGACCATATGTCTGTGACAT
ATGTGGGAAGGCCTTTGCCCGGCGCCCATCACTCCGCATCCACCGCCATTGCCACCTGTC
CAGGGAGGGTGCTG------CCCGGGCAGCCAGGTGCACTTGCAGTGTGTGCGGGAAGGA
GCTGGCCAACACAGGCTCACTGCACAACCATATGCGAGTACACACAGGTGAACGGCCACA
CATCTGTCCCCACTGCAGCAAAGCATTCCGCCAGCGGAGCAACCTACTGGGTCACCTACG
GCTCcacACGGGGGAGAAGCCCTACCGCTGCCAGCATTGCCCACAGGGCTTCTCACAGGC
AGCTGAGCTGCGCAGGCATCTCATCTCACACACGGGTGAGGCCTACCTGTGCCCTGTATG
TGGCAAAGCTCTTCGCGATCCCCATACATTGCGT--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------
>Sargocentron_rubrum_gill_6|000399|C629635|m.42007
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------CAAACCCCCAAGCTGCAGTGCACAGTGTGCTCCAAGCT
GCTGGCCAACTCAGGCTCTCTGAGGAACCACATGAAGCTCCACACAGGGGAGAAACCCCA
CATCTGTCAGCACTGTGGGAAGGCGTTCAGACAGAGAGGGAACCTCCAGGGCCATCTGCG
AATTCATAGTGGAGAGAAGCCCTACCCTTGCACCCAGTGTGATCAGAGTTTCTCCCAGAA
ACCAGAGCTACGCCGCCACCTGCTTTCCCACACAGGGGAGGTCTTCCTCTGTAGCTACTG
TGGAAAAGCGCTGAGGGACCCACACACCCTGAGGGCTCACGAG-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------
>Scleropages_formosus_red_gill|025360|scaffold40103|m.52799
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------AGTGAGGGAGGAGCACCGGCGCACGGAGCTGAGAG------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------TGGAAAACAAAGCTCAGACATTCCCG-------------------GAGGTGAA
AACGAAGATCGTCCACCTCCGCATTCAGCCACACAGGAAATT-GCAGAGGAAGTGCTCCA
GGACTT---TGAGGTGAGGACGCAGGAAGCCGTGCGAAGCGGCATCGCGACACTCCTGGA
CATCTTCAGC---TTTGACGCCAGGGAAAGGAGGTACAAATGCGATGAGTGTGACAAGAG
CTTCTTCCAGCTGTGccacttaaagaagcacaAGTTTACACACTCAGACTTCAAGCCGTA
CCTGTGCACAGAGTGTGGGAAGAACTACAGCTCCCAGGAGAGCTTCCGTGCACATCTCCT
CATGCACAAGGGCGAGAGGCCGTTCAAGTGCCAGCAGTGCGACAAGAGCTATGGCCTGAA
GCGGGACTTGAAGGAGCACGAGGTCCTCCACACGGGGCAGCGGCCATTTGTCTGCGACGT
CTGCGGCAAGGCCTTCGTCCGGCGACCGTCTCTGCGTATCCACCGAGAGGCCNNNNNNNN
NNNNNNNNNNNNNN------NNNNNNNNNNNNNNNNNNNNNNNNNNNNNTGCGGGAAGGA
GCTGGCGAATTCGGGCTCGCTCAGGAATCACATGCGGCTGCACACGGGCGAGCGGCCCTA
CCCCTGTCCCCACTGTGGCAAAACCTTCCGGCAGCGGGGGAACCTGCTCGGCCACTTGCG
AATCCACACCGGAGAGAAGCCCTACAAATGCGACCATTGCGACCAGCACTTCTCGCAGGT
ACCCGAGCTGCGGCGCCACCTCATCTCGCACACCGGAGAAGCCTACCTGTGTCCCGTGTG
CGGAAAGGCATTGCGCGACCCCCACACGCTTCGGGCGCACGAGCGCCTCCACACCGGAGA
GCGGCCATACAAATGCGATGTGTGTGGCAAGGGCTACACATTAGCCACCAAGCTGCGGCG
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------
>Synodus_sp._gill_5|010419|scaffold14178|m.16575
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------CCAGTGTGCTCCAGATT
GCTGGCAAACTCGGGTTCTCTAAAGAACCACTTAAAACTTCACACAGGAGAGAAGTCCCA
TGTGTGCCAGGACTGTGGCAAGGCCTTCAGGCAGAGAGGTAATCTGCTTGGTCACCTGAG
GACTCACAGCGGAGAGAAGCCTTTCCGATGCTCTCACTGTGAGCGAGGCTTCACCCAGAA
GCAGGAGCTTCAGAGGCACCTGGTGACTCACACTGGGGAGGCCTTCCTCTGCAGCTACTG
TGGGAAGATCCTGCGCGACCCGCACACCCTGAGGGCCCATGAGCACCTGCATAGCGGGGA
GAAACCCCACCACTGCCATCTGTGTGGGAAAGGTTATATCTTGGCAACAAAGCTGAGGAG
ACACATCAAGTCGACTCACCTGGTGGAGAAAGCCTTTAGCTGCCA---CTGTGGAGCTTC
CTACAGCCTGAGGCAGAGCCTCCAGCGCCACCAGGCCCAGCACCGACGGGACGGCCCgCC
GAGCAGCCAGGGTGGGGCGACAGGCGGCTCAGCATCTCCTCATGCCAGACCAGCCAGAGG
GAGGCCTAGGAAGAAGCAAGCTGCCGGAGCGGGGAGGGGGGGGCTGGAGGAAGGAGAGCC
GGGCCCAGGGGGAGCG
