>Amblygaster_clupeoides|025463|TR43500|c0_g1_i1|m.66893
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------GAGGAAGGCTGGACAGGCCCTCAGTGTGACGTGAAGGCCTGCCAC
CCCCGCTGTACTGAGAACGGAGTGTGTAAGGACGGCAAGTGTGAGTGCAACCAGGGCTGG
TCTGGAGAGCATTGCACACT---------------------------CGAGGGTTGTCCC
GGCCTGTGCAACAACAACGGACGCTGCACGCTGGACATGAACGTGTGGTTCTGCGTCTGC
CAGCCAGGCTGGAGGGGCGCTGGCTGCGACGTTGCCATGGAAACCCTCTGTGGAGACAAC
AAGGACAACGAAGGAGATGGCCTGGTGGACTGCATGGACCCAGACTGCTGTGTGCAACCC
TCATGCCAGAACCAGCCGTACTGCCGTGGCTCACCCAACCCCAGCAGTGTCATCAGCATG
AGCCAATCAGCACCCACACAGCAGGCCGCTCTGTCCTTCTATCAGCGAATCAGCTTCCTC
GTGGGCACAGAGAGCACCCACATCATCCTGGGAGAGAACCCCTTCAACAAGAGCCTGGTG
TCCATCATCCGAGGACAGGTGTTGACAGCTGATGGAACTCCCCTCATCGGAGTCAACGTC
TCCTTTGTCCACTACCCAGATCATGGCTACACCATCACACGGCAGGATGGCATGTTTGAC
ATCCTGGCCAATGGCGGAGCGTCACTGACCCTGAGCTTCGAGCGGGCGCCATTCCTGACT
CAGTACCGGACGGTGTGGATCCCGTGGAACATGTTCTACGTGATGGACACGCTAGTCATG
AAGAAGGAGGAGAACGACATCCCCAGCTGTGACCTGAGTGGCTTCGTGCGGCCCAGCCCC
CTCATTGTGGCCACCCCTCTGTCCACCTTCTACAGGGCCTCATCTCACGATGGCCCCATC
ATCCCCGAGACACAGGTGCTGCAGGAGGAGACACCCATCCCGGGCAGCGACCTGAAACTC
ACGTACCTGAGCTCGCGGGCGTCCGGCTACAAGCCCGTGCTGAAGGTGACCATGACACAG
GCCACCGTGCCCTTCAACCTGATGAAGGTGCACCTGATGGTGGCCGTGGTGGGGCGCCTC
TTCCAGAAGTGGTTCCCGGCCCAGCCCAACCTGTCCTACACCTTCATCTGGGACAAGACG
GACGCCTACAACCAGAAGGTCTACGGCTTGTCGGAGGCCGTCGTGTCGGTGGGCTTTGAG
TATGAGTCCTGCCTGGATCTGATCCTGTGGGAGAAGAGGACGGCCCTGCTGCAGGGCTAC
GAGCTGGACGCGTCCAACATGGGCGGCTGGACGCTGGACAAACACCACGTGCTGGACGTG
CAGAACGCAACAACCCGGCGCACAGGTATTATCTGGCCACCGACCCGGTGA
>Corydoras_julii_viscera_mixture_8|001292|C1201605|m.25400
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------GCCGTTTGTCCAGAACAATGCTCA
GGTCATGGGAAGTACCAAAGCGAGAGCGCCACCTGTACCTGCGATGCCAACTGGACTGGT
CCAGACTGTTCCATCGAGGTGTGTGAGGTGGACTGTGGGGCTCATGGTGTGTGTATGGGA
GGTAGTTGTCGATGTGAGGAGGGCTGGACCGGGGCAGTGTGTGATGTGAAGGCGTGTCAC
CCGCGCTGCACCGAACACGGAACCTGCAAAGCCGGAAAATGTGAATGTCACCAGGGCTGG
ACCGGAGAGCACTGCACTGT---------------------------GGAGGGATGCCCA
GGTCTATGTAATAGCAATGGGCGATGCACACTAGATCAAAATGGCTGGCACTGTGTCTGC
CAACCCGGC---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Distichodus_sexfasciatus_gill_4|017748|scaffold26510|m.30615
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------TGTGATGTTAAAGCGTGTCAC
CCGCGCTGCACCGAACATGGAACCTGCAAGGACGGCAAGTGTGAGTGTCACCAGGGCTGG
ACCGGAGAGCACTGCACCGT---------------------------CGAGGGCTGTCCG
GGCCTGTGTAACAGTAATGGCCGCTGCACACTGGATCAGAACGGCTGGCACTGCGTCTGC
CAACCGGGCTGGAGGGGGGCAGGATGCGACGTCGCCATGGAAACCCTCTGCGGAGACGGc
aaggacAACGAAGGGGATGGTCTTATAGACTGCATGGATCCTGACTGCTGTCTCCAGACC
TCGTGTCAGACTCAGCCGTTCTGCCGCGGCTCTCCCGACCCCGCCGACATCATTAGTCAG
GGCCAATCGGCTTCCTCCCAGCAGGCTGCGCAGTCCTTCTACCGGCGAATCAGCTTCCTG
GTTGGTCCTGAGAACACGCACGTGATTACTGGAGAGAGTCCCTTTAACAAGAGTCTGGTA
TCTATAATCAGAGGACAGGTGCTCACCGCAGATGGGACCCCCCTCATCGGAGTAAATGTC
TCTTTCGTCCATTACCCAGAGTACGGATACACCATCACCCGACAGGATGGCATGTTCGAC
ATCCTGGCTAACGGCGGGGCGTCCCTGACGCTGAGTTTCGAGCGA---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Pantodon_buncholzi_mixed|012335|scaffold15198|m.20008
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------TGGACTGGA
CCTGACTGCTCTGTGGAGTTGTGCACGGAGGACTGCGGAGCACATGGTGTGTGTGTGGGC
TCCGGTTGTCGCTGCAGTGAAGGCTGGACGGGCCCCACCTGTGAGCAGCGCACCTGCCAC
CCACGCTGTACTCACAATGGTACCTGCCGCGATGGGAAGTGTGTGTGTAACCAGGGCTGG
AACGGGGAGCAGTGCAGCGTGGCAGACTCTCTGGATAATGCTGTACAAGAGGGCTGCCCC
GGCCTGTGTAACAGCAATGGGAGGTGCGCACTGGAGCCAGGCGGCTGGCGCTGTATGTGT
CAGGATGGCTGGCGAGGCACAGGGTGTGACGTTGCCATGGAGACCATCTGCACCGATGCC
AAGGACAACGAGGGAGATGGGCTCACAGACTGCATGGACCCCGACTGCTGCTTACAGAGT
GCCTGTCATGACCAGCCGTACTGCAGTGGCTCCCCTGACCCTATAGTGATCATAGGTCAC
TTCTCTGCCACGCCCACACAGC------CACCATCATTCTACGATCGCGTCAGCTTCCTA
TTGGGGTCACAGAGCAGCCACGTTGTTCACGGGGAGAGTCCTTTCAACCACAGCAGGGTG
TCGGTCCTGCGGGGACAGGTGCTAACGGCTGACGGGACGCCCCTAATCGGGGTCAACGTG
TCCTTCCTTCACTACCCCACTCACGGATACACCATCACCCGGCAGGATGGGATGTTTGAC
CTTCTGGCCAACGGTGGAGGGTCACTGACCCTGAGCTTTGAGCGGCCGCCCTTCCTCACA
CAGCTGCGCACCACCTGGGTACCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNTGTGACC---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------TGA
>Sargocentron_rubrum_gill_6|024549|scaffold8998|m.10155
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------TCA
GGCCACGGCACGTTCAACGCCGAGACCAGCACCTGCGCCTGCGACCAGAACTGGACCGGG
CCCGACTGCTCTCTAGAGGTGTGTGCAGTGGACTGCGGCAGCCACGGCGTGTGTTACGGC
GGTGTGTGTCGGTGTGAGGAGGGCTGGACGGGAGCTGTGTGTGACCAGAAGGCCTGTCAC
CCGCTGTGCACCAAGAACGGAGTGTGTAAGGAAGGGAAGTGTGAGTGTGACCAAGGATGG
ACCGGGGAGCACTGCAATAT---------------------------AGAGGGCTGCCCA
GGTCTCTGCAACAACAACGGGCGCTGCACCCTGGAGGCCAGCGGCTGGCACTGTGTCTGC
CAATCAGGCTGG------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Scleropages_formosus_red_gill|032290|scaffold6430|m.8350
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------GGCTCCCACGGCGTGTGCATTGGG
GGCAGCTGCCGCTGTGAAGAAGGCTGGAGCGGCACGGTGTGTGACCAGCGGGCATGCCAT
CCGCGCTGCACCGAGCACGGCACCTGCAGGGACGGAAAGTGCGAGTGCAACCAGGGCTGG
GCTGGCGAACACTGCACCAT---------------------------TGAGGGCTGTCCC
GGTTTGTGCAACAGCAACGGGAGATGTACCCTGgaccagaacggctggcactgCCTCTGC
CAGTCCGGGTGGCGGGGTGCGGGGTGCGACGTCGCCATGGAGACGCTCTGCACGGACAGC
AAGGACAACGAGGGAGACGGTTTGGCGGACTGCATG------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
>Synodus_sp._gill_5|013368|scaffold18060|m.22373
CGGGCTTCATCCAGTACCTCGACACGGGGATCTGGCACCTGGCGTTCTACAACGATGGCC
GAAACACGGAGCAAGTTTCCTACAACACCATTGTTATCGAGTCAATTATGGAGTGTCCAC
AGAATTGCCATGGCAACGGCGACTGTCTATCGGGAACGTGTCACTGCTTTCCCGGCTTCC
TTGGCCCAGACTGCTCCAGAGCGTCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNGGCACG
GAGTGCGACGTCCCCACCAACCAGTGTGTGGACATCCACTGTGGGGGCCACGGCGTCTGC
ATCATGGGGGCCTGCATCTGCAACACGGGCTACAAGGGGGAGAACTGTGAGGAGGTGGAC
TGCATCGACCCCAGTTGCTCCGCCCACGGCGTCTGTATCCATGGCGAATGTCACTGCCAG
CCGGGATGGGGCGGGGCCAGTTGCGAGGTGGCCAAGGCCATGTGCCCGGACCAGTGCTCG
GGGCATGGCACCCACAACCCCGAGAGCGGCACCTGCACCTGCGACCCCAACTGGACGGGA
CCCGACTGCTCGCTGGAGGTGTGCGCGGTGGACTGTGGCACCCACGGGGTGTGTTTCGGG
GGCGTGTGTCGGTGCGAGGACGGCTGGACCGGGACGGTGTGTGAGCAGAGGGCCTGTCAC
CCCCTGTGCACCAAGAACGGGGTCTGCAAGGAGGGCAAGTGTGAATGTGACCAGGGATGG
ACCGGGGAGCACTGCAATAT---------------------------A------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------
