>Amblygaster_clupeoides|030459|TR54805|c0_g1_i1|m.74956
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------GCCGAGGTGTACACTGAC
AGCCAAGAGAAACTGAGGGAGGCCCAATATCTGCGGGACAACCGGGA----------GGA
GCTGATCGAGGAACTGGCCACAACCATCGTGCACAAAATTATCCGCAGGAGAAGAGATCT
CTCGGA---CATGCAGCCAGATTATAACCTGGAATGGCCTCCTGATGAGGGCGGCGAGCT
GCTGACATCCGCGCCCGAGGCCCACAGCTCGCTGCTTGCCTCCA----------------
----------------------------------CCAGCCTCAAGTCCTCT---------
------------------CTCTGGAGGTCTCGTTCAGCTTTCTCCCTCCTCACTGACGGA
AACGCAGACCCCTA------CACCCAGGCGGAGAACATTGAGGACGCAGCACCTCAGCCA
CCTCTACAT--GGCTTGAAGAAAGACGG------CATGCCGATCTTACCCACCTGGAAGA
GCGTGGACCGTCTAGACAA-----------------------------------------
----------CTCTATGCTGCAGAGCCCCGACGGAAACTGGATCGCCCTGCA--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------CCTTCATCTT-------------------------------
------------------------------------------------------------
---------------------------------------GCGGCGGAACTC---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
>Distichodus_sexfasciatus_gill_4|007289|scaffold10083|m.10836
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------AAGACTCTCTATAGG
AGGCACATCGCAGAACAGGGCAATCTGGCTGAACTCACAGAAGAAAGTACATATGAAGA-
-----------AAGTATTGGCAACGAGGGCAGCGTCTATGAGAGCGACTCCACATTCTAC
AGGCACAGTGAAGAGCata---------------gcatggccgacaccatcaacgtggCA
CTACGTGTGGCAGAGGAGGCTATAGATGAGGCCATTGCCAAGGCTGAGAGGCAACCAACC
AACCAAGAAAAGCAGAAAGAGGCCTGTTACTTACGAGAAAACAGAGG----------AGA
GCTGGTAGAAGAGCTGACCACCACAATTGTACAGAATATTATTGGGAGGA----------
-----A---AATGCAGACCGACCGTAATGCTCAGT------CTGAAAGGACCAGTGATGT
GAGCACTGCcgcttcacccgttcaccgttcccagaGTGCTCTGGC---------------
CTCTCAG--------------------------CCCAGATTCAAGGCCCCT---------
------------------ATATGGAGATCCAGGTCAGCCTTTTCTCTCCTTACTGATGAC
G-----------TA------CAGCAGGGCAAAGCTGAACAAAAATCAGCCGTCTCAAAAG
ACTCTACACAGGGCCTGAAGAAGGATGGAGCTCCTGTCCCAACACTGCCAAGNNNNNNNN
NNNNNNNNNNNNNNNNNNNN----------------------------------------
------NNTCTTCAGTGTTGCAGAGTCCAGACGGTAACTGGATCGCCCTGCAGAGCAACC
AGCTGTCACGGCCCAGCCTGCTGA------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
>Gasteropelecus_sp._gill_3|019681|scaffold31365|m.33699
ATGATGAGACG------------------------------------------------C
ATGCTGGACCTGTCTACTCTGACGGAGGAGGAGGCAGAGCATGTTCTACAGGTGGTGCAG
AGAGACATGCGGCTCCGCAAAACAGAAGAGGAGCGACTGAGTGACTTGATGCAGGAGCTG
GATGAGGAGGATAGCCGGTGTGTTTTGCTCTCTCGTCAGCAGGGCTTCAACCAGCGCTGC
TGCATTCGTTGCTGCTCGCCCTTCACTTTTCTCCTCAAACCACGGCGTCGCTGCCTAGAT
TGCAACTACAACATCTGCAAACGCTGCTGCTCCTACTCCAGCACTGACAAAGGCTGGCTC
TGCTCCTCCTGTGAGAAGGGCAGACTGCTGAAGACTCAGTCTCTGGAGTGGTTCTATAGT
AATGTGAGGAGACGGTTCAATAGATTTGGGAGTGCTAAAGTACTGAGGACACTCTACAGG
AGGCACATTACAGAGCAAGGCAACCTTGCTGAGCTCACAGAAGAAAGTACTTACGATGA-
-----------AAGTTTGGGCAATGATGACAGTATGTATGAGAGTGATTCTACATTCTTC
AAGCAAACTCAAGCGCACA---------------GCATGGCAGAAACCATAAGTGTGGCA
CTTCGTGTGGCAGAAGAGGCCATAGATGAAGCCATTGCCAAAGCTGAGAGTCAAAAAGAC
AACCAAGAGAAGCAGAACGAAGCTTGTTACCTGAGGGACAACAGAGG----------GGA
ATTGATTGAAGAGCTGACCACTACGATTTTGCAAAAAATTATCCACAGGAAGAAACAACA
GTGTGA---GATGCATCCAGAGTGTAATGTAGACTGGCCTCCTGATCACAAGAGAGATGT
AAACTCCTCTTCTTCTCCTACTAATCGACCTCGGAGTGCCATGGC---------------
CTCCCAG--------------------------TCCAGCCCCAAGACCTCT---------
------------------CTATGGAGGTCACGATCAGCCCTCTCTCTCCTCACAGATGAA
A-----------TATGGCACCAACATGACAATGGCCAGCAGAAACCTGTGCTTTGTAAAG
ACTGTACACAAGGACTAAAGAAGGATGGAGTCTCTGCCTCAATCCTTCCTAGCTGGAAAA
GTGTGGATCGAATGGATAA-----------------------------------------
----------TTCTATATTGCAGAGTCCAGATGGTAATTGGATTGCCCTGCAGAGCACCC
AGCTGTCTCGACCCAGCCTACTTACTAAGCGTAAGAGTCTGGTGTTCAGTGTCTTAGAGA
AGGAATCTGGTGTGATCTCTGCATATGATGGTATGGGCTCTGACACCGAAACAGACACTG
ATGGAACCTGCGGCTCAGCCCTGTTGGAGATTCGGCAAAAAATTTCCTCCAACAATGTTC
CTAATGACCTTCAGTCCAGCAGCCAACAGCCAACCCTGACATCAAACACACAGACTACTG
CTTACCAACCCCAAACTCACTCCAGCCAAGATACCCCAGTGCCCAAATTCCACAAATCTC
CTTTTCCTTTCCTGAAAAGGAAGGTACCACTGGACTGTAAGCGTTCATCTTCTCAACGCC
TAAGCATCAAGGACATTAACTTTCATCCTCAGGGTGCAGAAAGCAGTGAAGATGGCTTGG
AGGATATTAGGACCAAAAGAACACGACGGAGGAGAAGAACCAAAAGAGAAGATGCAGAAA
AGCAAGACTTTACAACTTTGTCTTCAGTTGAACCAGACAACAGCAGGATTCTACTGGATA
TTGTGGTGAAATACAAGAGTCAAAGTGCCTCAGACATCCTGAGTGACCAGATAATGGATG
GTACAACATCAGATATTCAAAGCTCAGAGGTTGGGTCTCCCGAGGTTTTTGTGCCTGAGT
TGGAAAATGATAGTCTTCTGGCTGGCTCAGAAGCAAACCAGCTTACATCTGCATTGAGAG
AATTGACCAAACAAGTTAGTAAAACAAAATTCTCCTCCACAGAAGATGAACTTGGTAAAC
TGGATGAGACTGTTGGAGAGGGAAATGACAATGTAAAGAGAGAGGCTGGAAGAGTGGAAA
CTTTATGGGAAATGGAAGTGGACATGAAGAAGGAAGAGGTAATGGCAAATAGAACTGAGC
TTCAGCAAGTACGGGAAAGTGATAAGTGTCCAGTGAAAAATGAAGATATATTTGTGTCAG
CTGTAGAGGAAGGGAAGAAAGCTAGTAAGATGGATAATTCAGAAAAGTTGATTGATCATT
TACATGAGATACAAAAGACAATAGACACAGTAAGTGAAACTACAGAAAATCTACAGGATA
AGTGCTTTGATTTTAAAAGACTTGTGACAGGAGAGCCTACTGAGCTTGAGGAAATTGAGG
TGGATAGCATAAATAATACTGACTCTGAGGGACAAATTAAAACTACTGAAGACACCGTGA
GTTGTCGAGGTTACAGAAGCAACAAAGTTGAGGAACGATCAGAAAGAAATCTTAACAATT
TTGAGCCAGAGCAAGTGAAAAAATGCAACACTACTGATGAGGCGATGTACCAAGAGCCAG
ACAACCAAAGTCTTTTGGAAACAGAGAAACAAAGAGACGTGGATGGAGAAGAAAATGGGG
AAACTGAGAATCAAAAGGATGGAAAGCAAATGAAAGAGACTGAACGCACAACCAAGAGTG
AAGACAGCATAGATGGGGCAATAAAAGAAATGACAGATGAAACAGAGCAAGACATTTGTG
ATTATCAGGAGATAACTGGATGTCTAGGGGAAGATGTGGCATACGAAAGAATGATTGACA
GTGCAATCAGGGTTTTTGATAACATGGAAAAGGACACTGAAGCACTAGACAGCAATACGA
GAATTGGCAGATCAGGTGACACTGACAGGAGTGAGCAAGAGGTAGAAATTTTAGCAGGAG
AGAAAAATGAAAAAGAGATTATGAAGTGTGAAGAGATAGAAGACAGAGAGAGAATGCATG
GGAACAAACTACCAGAGGAGAGGTTTGTGGAAGAAGAGAGCAAACATGACCTGGCTGAGG
AAACAGAACTTCACAATTGTGTGGGAAATGAAGTGGACTGTGACCAAATATTCAAGGAAG
ATCTGAATGGCACCCTCTATGGTCAACAGCTGTTTCTTACTCCAGAAGAAATCTACAAAG
TGAGTTGTGCTAAATGTACTAGATCTTCTCTCTTGCAACCATCAAATTGA
>Lepidogalaxias_salamandroides_Head_2|003111|C482449|m.38293
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------TCCCTTTCCAG
GAACGGGATCCTGAACACATCC--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------AGTGTTGAGCAAGTGGAACCTGCCGTGGCTCCAAA----------------
------------------------GATCTACCTGACTACCACAA----------------
------------------------------------------------------------
------------AACTGACCCTGGAGAGAAGGGAAGGCTTTTCAGATGATAATCCAAAGC
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------TCGCTTCAGTGGTGCAGAGC----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------TGTCTGAGC
TTGA--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------GGATAAAGTGGCGCTAGCTGCAGCCAGTGTCCTGAACA
------------------------------------------------CAGAAAGTGAGG
TGTCGGATATAGAGAACA------------------------------------------
------------------------------------------------------------
--------------------------------------GGATTGCTGCCCTAAGTGCT--
------------------------------------------------------------
-----------------GCTGGGATGGCTGTGGAAAAGTCCAA-----------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------AGTGAAGGCACCTATCGTACCCCA----AAGAAGA
AGACTCCCCCAAGACCTTCCGTTAA-----------ACCAGGCAGAACTGTTTGCAAGGA
ATTCGCTCTACAGGGGTTCCCTGACCC---------------------------------
------------------------------------AGAGGAA---CCACCCGGTTGCC-
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
>Pantodon_buncholzi_mixed|006735|C648922|m.39798
CACGTCAGCAGATATTACTGTGGAGTGGACATAATAATGCCTTCTGCCACTGCGGGGGGG
AAGCTGGACCTCTCCAAGCTCACGGATGAGGAAGCTAAACATGTATGGGATGTTGTCCAG
AGGGACTTTGACCTGAGGAAGAAAGAGGAAGACAGACTAGGAGATTTGAAGACCAAGGTT
GAGAAGGAAGATACAAAGCGTGACCTACTGAAGGACAAGTCCAGCCTGACTGAGTCTCAC
TGCATTCACTGCCTGCAGCCTTTTAAGTTTCTGGTGAACACCAAGCACCAGTGCTTAGAC
TGCAAGCTGTACACATGCAAGAACTGCAGCCTCTACAATAAGAAAGAATGTGGTTGGGTT
TGTGATCCGTGTCGCATGTCCAGAATGCTAGAGATTGGTACACTGGAGTGGTTTCACAAA
AACATTCGTGCTCGCTTCAAACGTTTTGGCAGTGCCAAGGTGATGCGCTCCCTTTTCAGA
CGGCTCAGTGGAGAGCACGACAACCAGACAGATCCCGATGAGGATGACACACGCAGCAAT
CCACAAGTCCGCAATATTTATAATG------------------------------TCCAA
GAAGAAGACCATGTGGATG-----------CGTCGGATGATCCAGTCAACAGACCGGACA
C------CGGCCTGGAGGACGAT--------TTATACCATGAGCCGATTGTGAAGGAAGA
GTACAGGAAAAGCAGGACGCCACGGTTCAGCTCCAAGA----------------------
-----------------------------TGCATCTTCCCATCGGGCGCACAAGGAGCCC
GGAGTATTCCACACAGTCTGACGATGATCCAGAACAGAGG--------------------
------ACACACCTCACACACCCAGACACACCTGATAGCCTGGAC---------------
ATTTCAG-------------AGGAAGATGAGATGCTGGTGTACAGCCCGTA---------
------------------------------TCAGCGACACTCATACTCCCTCTTGGAGAG
A-------------------CAACACCACAGTA----------------CTCCTATGCTG
CTCTCAGACATGGATTTAGAGGAACAGAAG-----------------CTGAGACAGAAGC
TAGGAGAGCTGACAGACAACATCAGTGATAAGGGAGTGTCCTCGGATGAGGATGAAGC-T
CAGACACCGTTTGTGTCCTACAGCGCTCACGGGGCGGCTCGGGTGCAC-GCAGAACCACC
TCCACTCACCTCCC----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------CAA--------------
------------------------------------------------------------
-------------------CTCACAGCCTC------------------------TCCAAG
GGGGTCTTTG---------------------------------AAGCAAACACTCAAAAG
CAGACAC--------------------------------ACAGCAGGGCTTT--------
------------------------------------------------------------
--------------------------TACCGTGCGCTCACTGGAGGA---GAGTGTGAAA
-------------------------------------------AACCGCTACAATGG---
-------------------------------CTCCACCACAGACTCGGAGCTGTCGGAGC
TGGA--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------GGACAAGGTGGCTAAAGCAGCAGCTAATGTGCAGAACA
------------------------------------------------CTGAAAGCGAGG
TATCGGACATTGAGAGCA------------------------------------------
------------------------------------------------------------
--------------------------------------GGATCGCTGCTTTAAACGCT--
------------------------------------------------------------
-----------------GCCGGCATGGCTTTGGCCAAGTCTAA-----------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------GAAGAAGGCACCTGCGGCACCACA----GAGACGA
AAGCCAGTGGAAGACAAGCCTGTCA-----------GCCATGCTGAGCTGTTTGCACGAA
ATGCCAATTACCGCGGGTCTCTAACGC---------------------------------
------------------------------------AGCGCAA------TCCCACTGCAA
AGACAAAGTTT-------------------------------------------------
--------------------------------------------------------AAGC
CGGCTTCTGCGAAACCTGTTATGATGTACCATTCG------------TGA
>Sargocentron_rubrum_gill_6|011783|scaffold19148|m.23039
AGTGTCGACCG-------------------------------------------------
--GCTGGACAACTCTATGCTCAAGA-----------------------------GTCCAG
ACGGGAACTGGATTG---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------CCCTGCAGA
GTGCCCAGC---------------------------------------------------
----------------------------------TGTCGCGTCCCGGCCTGCTCACCAAA
AGGAAGAGCCTGGTCTACA-----------------------------------------
----------------------------------------------------------GC
GCCTTGGAGAAGGAGTCCGGGGTGGTCTCCGCCTATGAAGGCATGGGCTCCGACAACGAG
GGTAAGCCCGAGCCCGACAACCCCTGGGGTGCTGCCCTGCAGGAGTTCCAGAAGAAGAT-
---------GGCAGACTCCAACTTCAACCTCCAGGACACCCAGGACACCCACAGTGA---
-----CGACCCTACGATCCCCTCACCTCCGACGGGCCGCCACGACAACATGGATGCTCTG
CTCTCAG-------ATTCTGAGGGGGA----ACTCAAGTCTAATAAGCCCCTGCTGGCTG
TTTTTAAGAAGAAGTTGCCCCAGGAGAT--CAGACGGCCTTCATCATCCTGCCGGACCAG
TAT-----------------CATTGATGTGA--------------------ACTTTAATC
CAGAAGGACCAGGAGAGAAGAACAGTGCGGC--------------TGCTGAGCTGGAAGT
GGGAAAAGTCAGGAGATTGA---GGAAGAAAAGGAGT-------AAAAAGGAGAAAGTGC
CAGCTTCCTCTTCTGTGTCGGATTACAACAGTATCCCTCTAGACGAACTGGTGAACAA--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------GTGCA-----------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------ATGTGAAAA
ACGACAACC--------------------------GATCCCAGCATGCCTCT--------
------------------------------------------------------------
--------------------------GATGCTGCGACCCCTGACACATTGACCTCTGGG-
------------------------------------------------------------
-----------------------------------GCTACGACCCCTGAACCCTCTGACC
TTGA--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------GGGTTACGTCACTGGAGGTGCAGCCAA-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------TCAAATG----
------------------------------------------------------------
-------------------------------GACCAGGACC-------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------TCGCACTCAA----ACTACGA
CAGCTAGCGAGCGAAGTT------------------------------------------
-------------GGCATCTCCCAC-----------------------------------
-----------------------------------------------AGCTCCACT----
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
>Scleropages_formosus_red_gill|019170|scaffold30216|m.39041
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------GCAGAGGGCAGTGTGTATGACGA-
-----------CAGTATCTACAATGAAGGGAGC------GGCACCGAGTCGCCGTTCCGG
AGGAACAGCGAAGTGCCCGTGTGTCCAGATCACAGCATGGCTGAGACGCTCAACGTTGCT
CTCCAGGTGGCCGAGGAGGCGGTNNNNNNNNNNNNNNCCAGGACCGAGGAACACTGTGAC
AACTTGGAGAAGCAGGACGAAGTGCGTTACTTGCAGGACAACAAGGA----------TGA
GCTGATCGAGGAACTCGCCACATCGATCGTGCAGAAGATTGTCCGCCGTAGGAGGAAGCT
GTCGCA---GATGCAGCCCCAGTACGAGATGGATCTGCCC------CAGCAGTGCGGTGA
GGGCACCTCCTCCCCTTCCACCCTGTCTCGACAGAACACCATCCC---------------
CTCCCAG--------------------------GCGAGCCTGAAGGGCGCCAAC------
---------------TCGCTCTGGGTA----AGACAGCCCCCCCACTTGCTCTGGGTAAG
A-------------------CACC---------------------------CCCCCCCTC
GCTCTGGGTAA-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
>Synodus_sp._gill_5|024989|scaffold8078|m.8989
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------ATTGAC
AGCCAGGAGAAACAGGGCGAGGCAAAGTACCTGAGGGAGCACCGAGA----------GGA
GCTCATTGAAGAGCTGGCCAAGACAATAATGCAAAAGATTATGAACAGGAGGAGGAGTAC
GGCTGA---GATGAGGCCTGGCTCTGGCCTGGACTGGCCTGGTGACATTGGCCCCTA---
-----CCCACACCCGCCCCAGCACCTGCCCCCTGCCTGCAACCTC---------------
CCCCcagcCAGCCTGGCCCATGGAAAAC---ACCTCAGCCCCCTCAACCCT---C-----
----------CAGCCAGCCTCTGGAGATCCCGATCTGCCTTCTCAATATTGGACAATGAC
C--------------------------------------------------TTCCTGAGC
CCTCCGCACAA-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------
