>Corydoras_julii_viscera_mixture_8|017549|scaffold4571|m.2979
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------ATGCACCAGGTTTCTCANNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNG----------------------------AAGATGCCGGTTTGCTCA
TACTTTCTAAAGGGAATTTGTAATAACAGCAGTTGTCCATACAGTCACGTCTACGTCTCT
CGCAAAGCCGCCGTGTGTCAGGATTTCGTCCGAGGTTActgtcctcagggagagaagtgc
aaggGGAAGCACACGCTGCTCTGTCCAGATTTCTCCAGCGCCGGTGTCTGTCCCCGCGGC
TCCAAATGTAAACTGCAGCACCGACCCCGGGCCAAGCGCTCGGGATCCGGCCCGAACCCG
GGCTCGCTCAAGAAAGCCCACGGCAaag------aGTCCAAACAGAGTCCAGAACCAG--
-------------------------AGTCGAACCCAGCA---GTGGATGACACGCCCACT
AAAGGTCCTGCGAAGCTTCCCTCATTTATCTCTCTGTCCAGTTTGTCAGAGNNNNNNNNN
N-----------NCCCCCTCCCCCCCAGCAGTTAA-------------------------
------------------------------------------------------------
------------------
>Distichodus_sexfasciatus_gill_4|006147|C911171|m.54156
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--AAAGGGTCTGTTTATCATT---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------GGAC
TGCTGTGAAAGTGGAAAAAAAGA-------------------------------------
------------------------------------------------------------
-----------------------------------------------------------A
TTTAAGTTCAACATCTGCCGTTCAGCA---------------------------------
------------------------------------------------------------
-------------------CAACCCTTCAGCATCTCCA----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------CTCTCAAGTAGCGGGTTCAAGCTGAGGAGCAGGACCAAAATCATCAG
---GAGGTGCAGCAGCAGCAATCCAGCTGCT---ATGGAAAGGAGATCAGCTCTGGGTGT
TGTGACCATGAGGAGTCGCTATTCTCTGATGAGGAAGAATCCAG----------------
--------------CGAAAATTGTGTCCGGTGCCAAACGAAGTCCATCTAGAGTACCTCA
GCGGCTCAGCCCCTCCAGCCTTAATACCACATGGTCCCCTAAAACAGGTTCCTCCTCTCG
AATG------------GGGTCTCCAGGGGTCATCAAAACCAGATACAAGATTGACACCCG
C-----------------AGTGCCCGCCCCCTACACCACAGCCCTACACTCACCTACAGA
TTGAAGAGACTCCAGTCTGCCAGGAATGTGATGCAGAATCGTTTGCTGAC----------
--------------------------------------AGATCGGGCTATGAGGTGGATT
GGTGGGGCTCTTTACAAAGTCTCAGCCAACAAACTCTCTCGCACCA--------------
----------GCACACCGAGCAACCGAGCAGAAAAGTGGCTTCATCAGACAGAAACATCT
CCCAACAGTGC------AATGAAGTTGTGGAGCCCACGTTATGTGGCCAGCCGGGTGTTA
CAGAGGAGTCTGGCCACCATTCGTCAGGCTTGTCAGAGGAAGCAGCAACAGAAGGCCAAA
CAGTACTGCATGTACTACAACCGCTTTGGCAAGTGTAACCGTGGCAACGCCTGCCCCTAC
ATCCACGACCCAGACAAGGTGGCCGTTTGTACCAGGTTTCTCAAAGGCACGTGTAAGCAG
ACAGACGGAACATGTCCTTTCTCCCATAAAGTGTCCAAAGAGAAGATGCCTGTGTGTTCG
TACTTCTTGAAAGGGATTTGTAACAACAGTAACTGCCCCTACAGCCACGTCTATGTTTCT
CGCAATGCAGCCGTGTGTCAAGACTTTGTCAAAGGCTACTGTCCTCAGGGAGAGAAGTGC
AAGAAGAAACACACTCTTGTGTGTCCGGAGTTCTCCAGCACTGGGGTGTGTCCACGTGGG
TCCAAGTGTAAACTTCGGCACAGGCAGAAAGCCAGCCGCGCCGGAACCAGCTTTAACTCG
GTCCTGCTGAAGAAAAGCTGCACCACAG------AACTCACAAGCAGACCAGAAGACGCT
GTGACAG------------------GGGTCTCTGAGGCAAGTGAGGAGGGCAAACCCACT
TCAGGCCTCGCGAAGCAGCCCTCCTTCATTGCCCTGTCCACTTCTCCCGACCCCCCAGAG
A------------------GCCCCCCAGCAACAGGGGAAAAGACCA--------------
----------------------CAGCAACCAAACTGCGCATCAAACCTTGCTTTGACAGA
CTGAA---------CTGA
>Gasteropelecus_sp._gill_3|018353|scaffold29631|m.31211
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------GGCAACAACTGCCCCTTC
ATCCATGATCCTGATAAGGTGGCAGTTTGTACCAGGTTTCTCAGAGGCACATGTAAGCAG
ACAGATGGGACATGTCCTTTCTCACACAAAGTGTCCAAGGAAAAGATGCCTGTATGTTCG
TACTTCTTGAAAGGAATCTGTAACAACAGTAGCTGTCCCTACAGTCATGTTTATGTGTCC
CGCAAAGCAGCTGTGTGTCAAGACTTCATCAGAGGCTACTGTCCTCAGGGAGAGAAGTGT
AAGAAGAAACACACTCTTGTGTGTCCGGAGTTCTCCAGCACTGGTGTTTGTCCCAAAGGA
TCTAAGTGTAAACTGCAGCACCGACAGAGAGTTAAGCACAATGGATCTAGCCTCAGCTCA
GGCCCGGCCAAAAAAGCCCGCACCAGAG------ACTCTGCAAAGAGACCAGAAACAACC
TCTTCAG------------------AGTCCAGTGAGGCA---GACAAGAGCACCCctagc
tcgggtcttCCCAAACTGCCCTCCTTCATCTCTCTGTCCAGTTCCCCAGACACTCCGGAG
ACTGCTGACAGCCCCCCATGCCCCACTATAGCAGGAACAGAGGTCA--------------
----------------------CAGGAAAGAAACTACAGATCAAGCCTCGCTTCTAG---
------------------
>Pantodon_buncholzi_mixed|007399|C652578|m.41167
CCCAGGCTGATGACGTTACAGTGTTGCAATATAGTAATGGAGGACAGAGAATGGCTGAAG
AAGCAAATAGAGCAGCTACAAAACCTAATCAACAACCACAA-------GAGTATCCATGG
CGATGCCCCATCAAGCTCTGCCCAGTGGGCCTCCAGAAGACCTGCACATACCCGGGGCAG
AGGTGGCAGCACCAGGTTCTCCCCCATCTTTCCAAACCCATCCAAGACATATAGCACCAG
CAATGCAGGCCAGTGGAGGAGGAAGTACTCTCTAAGTAACAGACACACC-----------
--------------------AGTGCTCCCAGTAAGCCTAACC------------------
-----------------------------------------------------------G
GGAAGTGAC----------------------------AACACAGCCAATACCAGTGGCTG
CAGGAGAGCAGGATGATTATC-----------------GGACTAAAGACTGTGTGACAGA
ATTAGATCCCAGCACTACAGTCAGGACCCATCCTGGTGTTAGTGGTGCTATACCAGTTCA
GCATTCAAAA-------------------CCCATTCAGCCACAGAAATCGCCTCA----C
AGGATTACCAAATCTCACCCCAAACCAGGTCCATCCCAGCACAGCAAGT---CTAAATAC
TGCTGGGTGAAAGGCAGCGAGCG--------CTTGTTTGAA--------GCCCCGCCCAA
TTTATCTACTC-------AGCCAATCAGCATCAAGGAATCTTCTCTTTTACCCCCTCAGC
CAATCAGCAGCAAGGCCCCACACCCTAAATCTCCACGGCCAATCAGCAGCAGGGTCCCTC
TGCCTCTCTCTCCTCGGCCAATCAGCAGCAGGGTCAGTCCCACT----------------
----------------CTGTCTCCACAGCCAATCAACAGCAAGGCT--------------
----------------TCCTGCTTCTTGTCCACCACCAGATACACGTGGGTCTCA-----
-------------GCGCGGCCTACCAAGAAACCTCGCTCACCCAAACCAACAGACACACC
TCAGCGAAAGCCAAAGCAGGGCCCTTCCAGACCCCGCAAGGCCCCCAGTGGCATCGCCCA
GTCCCAAAGCAACCGATACCGATGGAAAGCATCCCAGTTACCGTTACCTGACATGACTCG
CCGAGCTTCGGTTTATCGATGG--------------------------------------
-------------TTCTCAAAAAAGGAATGTGGGCCGAACCGCCCGGTGAAGGTCAGCCG
TGTGAAGTCATCAAACAGCTCTTCCTCCTCT---------------CCCAGCTCAGGTTT
GGTG-------------------TCACAGCGTCGCAGAACCCA-----------------
----------------------ACCCCCAGCTCTGGTTCTGATAGGTCGACACAAACTCT
GCCGTCTGGCCCCGCCCACCT-----CACCTGGTCACAGCCGAACAGGATCTTCATCACC
------GCGCACTCCTGTGCTTCAGAGGGTCATTAAGACGCGCTACAAGATTGTGACCCG
CAGGGGTTCTGCTGGG--AGCACCTACGTACCCCACTTCAGTCCCTCTCACACCTGGAGG
GTAAAGAGAGTGCAGTCGGCCAGGGTGTTATTACAGAGTCGCCTGCATGC----------
----------------GGGCGCTGGCGTGGCA-TGGAGGGGGCGGAGCATGCGCTGGATC
GGCGGCTTGCTTTACCGTGTTTCTGCCAACAAACTGTGTCGCACTG--------------
-CTGTCACACCCACGCAGCGGAATAAACCCGGGCGAAGCTCCACTCCT------GTTTCC
CCTCACAGTGT------CATCAGAGGATCCAGCACCAGACACCTGGCCAGCCGAGCCCTG
CAGCGGAGCAGGTCCATCATGCGACACGCGCTGCAGCGACGGCAGCCCAG------CAGA
CAGTTCTGCATGTACTACAACCGCTTCGGCCGATGTAACCGCGGCAACGACTGCCAGTAT
GTACACGACCCAGACAAGGTGGCCGTCTGCACACGATTCCTGCGAGGCACCTGTAAACAA
ACTGATGGCAGCTGTCCTTTTTCACACAAAGTGGCCAAAGAGAAGATGCCAGTATGCTCC
TACTTCCTGAAAGGGATCTGCAGCAGTACCAGCTGCCCTTACAGCCATGTGTATGTGTCT
CGTAAAGCAGCTGTGTGCCAGGACTTCATCAGAGGCTACTGTCCTGCCGGAGAGAAGTGT
AAGAAGAAGCACACACTTGTGTGTCCTGACTTCTCTAAAACTGGCAGCTGTCCCCGAGGC
TCCAGATGTAAACAACAGCACCGTCTGCAG------------------------------
AAACCACCAGGAAACACTCGAACCAGAGCACGGCACAGCCCGGACAGGTGCAAGCCAGAC
GTGACCG------------------AGAGCTGTGTCACA---GAA------------GCG
TTGGATCCTAACAAGCTGCCATCCTTCATATCCCTCTCCAGCTCACCAGACA--------
-------------------AACCCTCTGCAACAGAGACAGAGGTCACAGAGGTCGCAGGC
CGTTCCTGTGGCTCGTCGGCACCAGAGAAGAAGTTTCAGATTAAGCCACGCTTCTAA---
------------------
>Sargocentron_rubrum_gill_6|011856|scaffold19244|m.23194
--CTAG------------------------------------------------------
-------------------------TCATTGGAACTCCCAAGACTTCCAAGTACACGTGG
GTTTCCTCCGCTG-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------CTGGAGGCCAAGCC-------AAGCTG-----
------------------------------------------------------------
--------------------------------TCTCGAAAACCGCCATCACC--------
--CAAATCCCTGGCCATTGCTCAGAGAGCTT----------------------TGGAGAA
GGGAGATGCCACCA-------AGAAGCTCAGACCAGCCTCAGCG--------------CA
ATACACCAAAATGA------------------------------GAAAGGTAACAGCAGC
CTCGTCCACCAGCAGCTCTCTTAGTAGCCGTTACCGCTGGAAGGCTGGTGGGCAGAGTCC
TTCTGGGGCACTGGCAGGAGGCG-------------TTGCAGTGGC--------------
------------------------------------------------------------
NNNNNNNNNNNNNNGGACCTCAGAAAAAAGCTCTAAAG--GAGTGAAAGGAGGGC----T
TCGTATTTCCCCGTCTACATCCCAGCG---------------------------------
------------------------------------------------------------
-------------------TGCCTCTGTCCAGCCGCCT----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------TCCTCCCCTGGTGCGTTCAAGCTCCGCAGCAGGATGAAAATCATCCG
---GAGGTCTGCTAGCAGCGAATCTGTATCA------GAGAGGGGGacCAGTCCACCAGC
GGTGATGGTGGGCAGCAAGTACTCCCT-CCGAGGGCGGATACACACGTTGACCAGGAGCC
CCATCGCTGTGAGGAAGACGCCATCCAAGGAGCTTGTTTCTTTTGGTCGCCACAAGTTGC
GCCGGCTCTCCCCCACTTCTTT-----------------CAGGACAGGTACCGCCACTCC
TTCGCACCGTAGCCCCGCCTCCCAGAGGGTGTTCAGGACATGCTACAAGATGGTGACCCG
CCCAGGTGCCGGT-----GCTGCACACACACTCCACTACAGCCCTTCTCTCTCCTGGAGA
GCTAAGAGGATCCAGTCCGCCAGGACTTTGCTCCAGAGTCGTCTGAGGGC-TTCTCAGGA
CAGACACCTGCCATCCCAGGACTGG--------AGAGGAAGGAGGAGCATGCGCTGGATT
GGAGGTTCCCTGTACAGGGTGTCAGCCAATAAGCTGTCCCGCACTG--------------
-TGGCACCCAGCACATCAATCAACCGTACAGCAAGGTGGTTCAGTCCTCACCAGGTCTCC
CTGACAAGTTCTCCATTGAACCGGCCCTCCAGCACTCGGCATGTGGCCAGTCGTGTAGTC
CAGCGGAGCCGTGCCATCATCAGAAATGCTCGTCAGAAGAAGCAGCA---------GAAG
CAGTACTGCATGTACTACAATCGCTTCGGCAAGTGTAACCGTGGCAGCAGCTGTCCCTAC
ATCCATGACCCGGACAAGGTGGCTGTCTGCACCAGGTTTCTACGAGGGACGTGCAAGCAG
GCAGACGGGACCTGCCCATTCTCCCATAAGGTTGCTAAGGAAAAGATGCCAGTGTGCTCC
TACTTCCTGAAGGGAATCTGTAACAACAGTAGCTGTCCCTACAGTCATGTCTATGTGTCC
CACAAGGCTGAAGTGTGTCAGGACTTCATCAAGGGTTACTGCCCTGAGGGAGAGAAGTGT
AAGAAGAAACACACCCTGGTGTGTCCAGAATTCTCAAAAACCGGCTCCTGCCCCCGTGGC
ACCCGGTGTAAGCTGCAGCACCGCCAAAGACCCAAACGACGGGCTCCGACTACCTCTGCC
ACCCCGGCCAAGAAAGCTCGCACCAAGG------ACACCACCAAGAGGCCCAGTCTGTCT
CTCATCATACCAGCGGAGCAGGCTCAGGGCTCTCAGGCA---GTTCCAGGGACGCCCACC
TCGGGTTCTCTGAATCTGCCGTCCTTCATCTCCCTCTCCAGCTCCCCAGAGGACGCAGAC
GCACCAGACA---------CACTGCCAGCCAGGACCTCACAGGTTA--------------
----------------------AAGAGAAAAAACTGCAGATCAAGCCACGACTTTAG---
------------------
>Scleropages_formosus_red_gill|006845|C1331082|m.80194
--CGGG-------------------GGAGGGGGGAAATGGAGGAGAGAGAATCTCTGACG
AGACAGATAGAACTACTCCAAAATCTCATCAACACACACAA-------AAGTATCCATGG
AGATGCTCCGTCGGGTCCCGGGGGGTGGCGTGCT------CCGACAGCCGCGCCGGTTAG
AGGTAGAGGGCTGCCGTTCTCCAGCACGTTCCCCCCCTGCTCAGGGCTCCATGGCCCCCG
GCCCTCAGCCCAGTGGAGGAAGTACTACTCTCTGAGCAACAGGAGCACTGTGTCTTCTGC
CACCCCCGACCTCTGCCGAGAGCGCCCCCTGCAGGCCCGGCCCTCCCTGAAGCAGGTGTC
TCTGCCTGCCTGTCGGACGGACCTCCCGGGGAACTCCTCTCTGCTGGTTCCCAGAAACAG
GGGGACGATCAGTTGCCTCCCAAAGGGTGAGTCCCCAGGAACAGCTGCTGCCAGTATCTT
GGGACAGACGGGGTCAGAGGTCATGGGCCGTGTCAGCAGGGCCACCGCTTCCATGAGGGG
GGCTGGCGTCAGCACTCAAGGGGGCGCTCGGACTGCAGGGGACAGCACTATGGTTATCCA
GCAGCTGAAGATGAGCACAGGAAGCAGGGCCAATCCAGCCTCCCGAAAGGCCACAGCTGG
GGCATTTCCCACAATCCCACTCAGCTGTCCCCCTCCTCAGAAACCAG---------ATTC
CTCAGTGAAGCTGGTAGAAAAAGGGATGCACCCTAGTCGGACTGGCTCCACCCCGCTCCC
CTCACTTCCCCCCTCTCTATCCGCGCAAACTCAAGACATCTCCATTCCT-----------
---------GAGGGGGCTCCCAGAAAAAATGCCAATG-----CCTCCAGCAGGGT-----
---ATGTCTCCTTGCTGCTGCCCAGAAGAGGTCCCAGTTCACCTGGGTGAAGAGCAGTGC
GCCGCAACCGGTCTTGTCGTCTCCGAGGGATGCTGGCTGTGGAGCTGTAGCCCTCGAGCG
GAAGGTAGCCCACAGGCCTGGCCTCTCTCTGACCACCAAGTACACGTGGGTGTCATGTGC
TGTCAGCCGCCACGGCAGGTTGTCCAGGAGGCCATCCTCCCCCAAAGTGCCGGACCCCTC
CCAGAAGAAG---------------ACCAAGCCCCGCAGGGCTGTCGGCGCTTCCCCCTC
ACCTCAGAGCAGTCGCTACCGCTGGAAAGCATCAGGTGTGACGGCAAAGGGCACGGCCCT
CAGCGGCTCCGTGTACCGCTGGACCTCGGAGAGGGAGAAGGGTCCGAGGGGGGCGGTGAG
CCCCAGGCTCACCCCCCAAGCCACTGGGTTTAAGCTGAAGAGCAGGATGAAGATCATCAG
AGGAAGGCCCTCCAGCAGCAGTCTAGGCTCTGGCTCAGAGCGGCGGCCTGGGTTCAGCTC
ACCGACCGTGAGCAGCCGCTACTCCTT-GCGTCAGCGCCCCCC-----------------
----------------------GGCCCGCGGCCTCATCTCCATCGGGCGGCACAAGCTGC
GGCGCTTATCCTCAGCCAACT-----CACCGGGATCTTCCAGGGCAGGCCCCTCCTCCCC
CGTCCTGCGTGGGTCCACGGCCCAGAGGGTCATCAGGACACGTTACAAGATCGTGACCCG
CAGGGGTTTTCCTGGACCGTCGTCCGCCTCCTTCA--GCAGCCCATCGCTTTCTTGGAGA
GCTAGGAAAGTCCAGTGTGCCAGGAATCTCCTGCAGAGCCGTCTCCGGAGCCCCCCAGGA
GCACCCCCTGATGAAGGGGTGCTGGCACATCCCTGGAGGGGGCGCAATGTGCGCTGGATT
GGTGGTGCCCTCTACAGAGTCTCTGCCAATAAGCTGTACCGCACGGCCTCCCCGAGTGCC
TCCGCCGCAGCTGCAGTGCGGCTTCGAGCAGGAAAGTGTTCCACCCCTCAGGACCCGGCA
GCTCACAG---------------GGCCTCCAGCACCAGACACCTGGCCAGCCGAGCGGTC
CAGCGCAGCCGCTCCATCATCAGACATGCCCTCCAGCGCCGGCAGCAGAG------CAAG
CAGTACTGCATGTACTACAACCGCTTTGGGCGCTGCAACCGTGGCCAGAACTGCCCGTAC
ATCCACGACCCAGACAAGGTGGCTGTCTGCACAAGGTTCCTGCGAGGCACCTGCAAGCAA
ACGGATGGCACCTGCCCCTTCTCACATAAGGTGTCCAAGGAAAAGATGCCCGTATGCTCG
TACTTCCTGAGGGGAGTGTGCAGCAACAGCAGCTGCCCTTACAGCCATGTGTACGTGTCC
CGCAAGGCAGCCATCTGCGAGGACTTTGTCAGGGGCTACTGTCCTCAGGGAGAGAAGTGT
AAGAAAAAACACACCCTGCTGTGCCCGGACTTCTCGAGTGCCGCTGGGTGTCCACGAGGC
TCCAGGTGCCATCTGCAGCACCGGTCGCGGACAAAGCGAGTTGCACCACGCCACTCCTCC
ATGCCAGCCAAGCGAGCCCGCAAACACA------GCAGCCCCGACAGACAGGAGTCAG--
-------------TAGAA-------GGCACCGCGCCCCA---GGACAGGACAC-----CT
CCGGGCCCCAGCAGGCTGCCCTCCTTCATTTCCCTGTGCAGCTCTCCAGAGGGAACGGAG
GCACTAGATA---------CCCCCCCAGCTGGTGGGCCACAGGTCACA------------
------------------GCTCCAGAGAAGAAGCTCCACATCAAGCCTCGCTTCTAA---
------------------
>Synodus_sp._gill_5|016184|scaffold21484|m.28010
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------AGCCGGGCAGTA
CAGAGGAGCCTTGCTATCATCAGACATGCCCGTCAGAGGAAGCCACA---------GAAG
CAGTACTGCATGTACTACAACCGCTTCGGCAAGTGTAACCGTGGCATCGCCTGCCCTTAC
ATCCATGACCCTGACAAGGTGGCTGTCTGCACCAGATTTTTGAGGGGAACTTGCAAACAG
ACAGATGGCACATGCCCGTTCTCCCATAAGGTGGCCAAGGAAAAGATGCCAGTGTGTTCC
TACTTCCTGAAAGGAATCTGTAACAACAGTAGCTGCCCCTACAGCCACGTCTACGTGTCC
CGCAAGGCTGCCGTGTGTCAGGACTTTGTCCGAGGATACTGCCCCCAGGGAGAGAAGTGT
AAGAAAAAGCACACCCTAGTGTGTCCGGACTTCTCCCGAACCGGGTCCTGCCCACAGGGG
TCCCAGTGTAAACTGCAGCATCGACCGAGCACCAAACGGACTGGCGCGGGACCCCCTGCC
ACCCCAGCCAAGCAAGGCCGCACCAGGG------ACTCTGCCAAGAGGCCCAGACTTTCC
CTCATCATACCACAAGAGCAGGCCCAGGGCtctcaggca---gatccagggacacctacC
ACAGGTCCTCAGAAGCTACCATCATTCATCTCCCTCTCCAGCTCCCCAGAGGATACTGAG
GTTCCGGACA---------CGCCCCCGGCTCCCATGACAGAGACCA--------------
----------------------CAGAGAGGAGGCTGCAGATCAAGCCACGCCTTGAAGGA
CAGAAGGTCCAATCCTGA
