>Corydoras_julii_viscera_mixture_8|000999|C1196589|m.24966
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------AACGATTCAGAATCAGGAGATGAGCTGAGCAGCAG
TTCCACTGAGCACGTCCAGACCGTGTCTCCTACGGGTCATGGGCATCTGGACTCCCCGGT
CTACACCAACCTCCGTGAGCTGAAGATCTCTCAGTCGTCTGTACCACCTGCCCCCTCCTC
CTCCCCCCTGCACGTGGTGGGGGACTGGGAGACGCATAAAGACCCCAGTGGAAGACATTA
TTACTTCAACCGCAACACCCAGGAGAGGACGTGGAAACCACCGCGCTCCAGAGACACCAC
CGGGGGCAGCAGAGGAGAGTCAGCC---ATCAGCACAGACATGGAGCCTCTGTCCTCTGA
GGATAACGGTCTG-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------
>Lepidogalaxias_salamandroides_Head_2|028417|scaffold8305|m.10840
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------TGTGCGCGAGGTGCGCCGTGCCCTCATGCCCCCCCCGAAGGCGCTTCT-
-------------------CAAGGGCGTGTCTGTCCGGGtcaagcccaccaTCCTGGACA
TCTGCCGGGCCTCCAACGAGAACCT-CAACCGGCCTCAGGAG-ATGTC--------CAGC
TTCGGGCGCCCGTCGCCGGCCTCCACGCCCTCCCCGTCGCCAGGGCACGAGCCCCCAGCC
ACCTCGCCCAGGGACGCCAACCAGAAC---------CCGGGCAGCCC---GCAGTACGAC
AAAGTGGTGGCCGATCTCCTCCTCCACAACAACAA-------------------------
--CAACCACCACCTTCACCACCACGCCAATTCC----------------------ACCCC
CCCGCCGGNNNNNNNNNNNNCGGCACGCCGATGGAACCCCCCC--GCCGGGCGAGCCACA
TCGGAACGGCTCGGAGAAGCTGCTGAACGACTCGGAGTCGGGGGACGACCTGAGCAGCAG
CTCCACGGAGCACATGCAGACTGCGTCCCCCACGGGGCAGGGCCGGCCCGAGTCCCCCGT
CTACACCAACCTCCAGGAGCTGAAGATCTCCCAGTCCAGCGTCCCCCCGGCACCTTCCGG
CTCCCCGCTGCACGTGCTGGGTGACTGGGAGACGCACAGGGACGCCAGTGGCAGACACTT
CTACTATAACCGCGCCTCCGGGGAGCGCACCTGGAAACCCCCCCGTGCGCGGGACACC--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------
>Melanotaenia_praecox_viscera_mixture_8|005477|C457368|m.32295
ATGGCAGAACTGTCTATTGCCCCGGGCAAGGTCTACATCGAGGTGGATTATGACTATGAG
TACAAGTCCAAGGACCGCCTCATTACCATCCGGCAGGGGGAATGTTACATGCTAGTCAAA
AAAACCAATGAGGACTGGTGGCAGGTGAGGAAAGACGAAGGGACGAAAGCTTTTTATGTA
CCTGCTCAATATGTCCGCGAAGTCCGCAAAGCCCTCATGCCGCCCTCTAAGCCAATCGCA
CATCCTCCACCCGCCACAGGAAGCACACCTCCACATGGTGGGGGTTCACTCTGGTTAAGA
CCAGCCAATCTGGAGCTGGGACTCCATGATCGGCCTGCTGAGAACCTTTACAGACACGAC
TCCAAAACCAGACGCTCTCCTTCAGCACAAACCGCCTCCGCAGGCCACTTCAGTCCTCCG
ATTCAGCGCAGGAACAGTAACCACCACCACCATGCTCCAAGCAGCCCCACCGATCACGAC
CGAGCCCTGGCTGATATTCTCGTCCACGGTGGTGGGCCTCCACCTTCACAAAAAGGATCG
TCCAGCACTCTTCCCCGCACCCGAGCCAGATCCC-------CAGAGATGGTCAGGACCCG
ATCCCCAGAGATGGTCAGGACCCCGCTGAACGTGGACAGCACCCAACACTGTGACTCTGC
AGGAGA------AGAGAGGCGCACCAATGACTCAGAGTCTGGTGATGAACTGAGCAGCTC
TTCCACTGAACATCTCCAGACTGTATCTACATCAGGCCACGGCCGGCCAGAATCACCGGT
CTACACCAACCTCCAGGAACTGAAAATCACCCAGACAAATCTGCCCCCTCAACCTTCAGG
GTCCCCCCTGCACATCCTCGGTGACTGGGAGACCTACAAGGACCATGGTGGCAGGCATTA
CTACTACAACCGCTCCACCCAGGAGAAGACCTGGAAGCCACCTAGAACCAAAGACATCAG
CACTGGAAACTCCAGAGGAGAGAGC---CACAGCACTGGAGAGAGCTCAGAGTGGTTAAA
ACATGTTGAT--------------------------------------------------
------------------------------------------------------------
---GAACAGGGCAGACCTTATTACTACAGTGCCGATGGCTCCAGGTCAGAATGGGAGCTG
CCAAAGTACAGCCTCCCCGTACCTCCGCTGCCTGGAGATGCTCAGAAGAGTCGCAGTCTG
GACAGAAAAAATGTGGAGCCCATCGTCCTGACGAAGTGGAGACACAGCACTTCCAACCTA
GATCCAACCGAAAAGCGGCTGTTAAAAACCAGGCGTTTACGCTCAGGCTCCGCCCGGCCA
CACCCGTACAAACACCAAGTCAGTAGTCCGGCCGATGGAGTAATCAGCACCTCGTCCCTA
AATCCAGACTCACAATCAGTTTGCATGGAAAAAAAATCA
>Pantodon_buncholzi_mixed|010120|scaffold12733|m.16120
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---TCCACTCTGCTCCACGGCCAGGCTGAGTCGC-------CAACGTTG----------A
GCCACAGGACTTTGCTCGACCCTGATGCAGACCGGACACCACC--GTCTTGTGAGCTTGC
TGGGGAGAGCTCAGAGAAGTTCCGAAATGACTCTGAGTCAGGTGATGACCTTAGCAGCAG
CTCCACTGAGCACTTGCAGGCTATATCCCCCGTGGCTCAGGGTAGGCCCGAGTCCCCAGT
TTACACCAACCTACAGGAGCTGAAGATCTCGCAGTCGAACCTGCCGCCGCAGCCCTCCAG
CTCCCCGCTGCACATGCTGGGCGACTGGGAGACTCACCGCGACGGCAGCGGCCGCCACTT
CtactACAACCGCACCACGCAGGAGCGCACGTGGAAACCGCCACGGGTGCGAGATGCCAG
CTGCAGCAGCCGCAGCGACGTGCTT---GGCATAGGAGACATAGAGCCTCTGTCATCGGA
GGAGAATTGTCACAGCGCGTACTCCAGCCAATCTGACAGTCAGTACGGTTCGCCGCCCAG
AGGCTGGTCTGAGGAGCTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTCAAGCATGTG
GACGAGCAAGGCCGACCGTATTACTACAGTGCCGATGGCTCCAGGTCAGAGTGGGAACTT
CCCAAGTACAACCTCACCCCACAT---CAGCATGGAGACCCACCCAAGAGTCGCAGCCTG
GACAGAAAAGCGCCCGAACCCATCGTTCTGA-----------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------
>Sargocentron_rubrum_gill_6|001817|C665300|m.44284
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------ATGCGTCGTACG
TTCAACCCGTTCAGAG-GTTACAGGAGAGCAGGCGAGGATGACGACGAGGTGTTTGTGTG
CAGCCCTGGAGCCCACAAGACAACATCACCCACAGGTCAGGGCCGGTCTGACTCGCCCGT
CTACACCAACCTGCAGGAGCTGAAGATCTCTCAGTCCAACCTGCCTCCCGTCCCCTCCAG
CTCCCCTCTCCACATCCTGGGCGACTGGGAGACCCACAAAGACCTGAGTGGCAGGCATTT
CTACTACAACCGGGCCACCGGAGAGCGAACCTGGAAGCCGCCCCGCACCCGGGACACCAG
CGGCAGCACCAGCAGTAGCCGGGGA---GACACCCAGGGCACAGGA--------------
------------------------------------------------------------
------------------------------------------------------------
-------GAGACTGAG--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------
>Scleropages_formosus_red_gill|014083|scaffold21557|m.28074
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------TGACCAGCTTCGGGCG------------------
-----------------------------------------------------GCCGGCG
TCCGGCCCCAGGGACGCCAACCAGAAC---------CTGAGCAGCCC-------------
-----------TGGGCACTTTCTCAACAACAACAA-------------------------
--CCATCATCACGGTGGCGGCACCCCTGACTCGCCCACCCACAGGGCTTTTGA-----TC
ACGGGAGGCACCCGTTGGACCCGGACAGGGACAGGACGACTCC--TCCCTGCGATTCGGT
CGGCGAGGGTTCGGAGAAGTTCCGGCACGACTCCGAGTCCGGTGACGACCTCAGCAGCAG
CTCCACGGAGCAGGTACAGGCTGCCTCTCCCCTGGGGCCGGGCAGGGCCGAGTCTCCGGT
CTACACCAACCTCGAGGAGCTGAAGATATACCAGGCCAGCCTGCCGCCGCAGCCCACCAA
CTTGCCCCTCCACGCCGTCGGCGAATGGGAGACGCACCAAGACGCCAGCGGTCGCCACTT
CTACTACAACCGCGCGACACAGGAGCGCACGTGGAAGCCGCCGCGCA-------------
-----GCGGTCGGGGCGATGCGGGG---GGCGCCGCGGATGCGGAG--------------
------------------------------------------------------------
------------------------------------------------------------
-------GTAACCGATTTCGTTGCTTC-GCggcAGCCGCATCGGGTGATGCTGGGTGCCG
TT------------------------------------CCCCCGCGGGGGTTGAGATCCA
AAC--------------CCTTATTTCCCTGCTGA--------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------
>Synodus_sp._gill_5|001335|C523077|m.41736
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------CTAAAACACGGAGACTGTC--CCAGCATGCTG-AGG
TTCAGTGTATTCCGGG-GGTACCGCAGGTCTGAGGAGGATGATGATGATGTCTTCATCTA
CAGCACTGG---CAAAAAGACGACGTCCCCCACAGGCCAGGGTCGCTCGGAGTCCCCGGT
CTACACCAACCTGCAGGAGCTGAAGATCTCCCAGTCCAGCTTGCCCCCGATCCCGTCCAG
CTCCCCTCTCCACATCCTGGGTGACTGGGAGACCCACAAAGACCTGAGCGGGCGTCACTT
CTACTACAACCGGGGCACCGGGGAACGCACCTGGAAGCCGCCTCGCAGCCGGGACACCAG
CGGCAGCACCAGCAGCAGCAGCAGGGCCGACTCCCACGGGACGGCA--------------
------------------------------------------------------------
------------------------------------------------------------
-------GAGACCGAG--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------
