>Amblygaster_clupeoides|016948|TR29727|c0_g1_i1|m.50762
A-----------------------------------------------------------
------------------------------------------------------------
----------------------------------TGGCTTTGGTTGCAAGTGATCGCAGT
AGCAAAGTGAACGGTTTGACGAGCAGTTGCAAGGCTGGCACCAAAAACGAAGGAAAACTG
ACTAAGACTGCGAGCTGTAAGATAAAC---ATGCAGCCGAAGGACGCGGAGTTTACCACT
GAAGGTTTGCCGAAAGCGTTTTTACAGAGTTTAAGGACTCTTTTTGACATCCTCGACGAC
GGGAGACGAGGATACGTGCACATATCGGAAATTGAAAGTCGTTGGCAGGGTGCGGAGACG
CAGGGTTTACCAAGCGGTGTTCTGGACTGCTTGAGACGGGTTACCCCACCGCACGGCTGC
CTGACTTTCGAGCGTTTCGTCGCGGGGCTTCGGAACTCCATGCTCAATCCAGAAAATGGT
AACATGAAGCATCAGCCTTCTACACAGGGGTCATACGCAACTGGACAGAAGTCGCAACTC
AACACTCATAAAACCGGTTCATCAATGGGGTGCTCGGTAGGATCTCGAGGCTATGAGAAC
AAAGTTCGGCCACTTGGCCCAAGTAATATGACCAATATGCACCATAATCGAGCGTCATCT
CTCCAAAGTAGACCAAGGCACCACGAAGACGGATACACGACCTCCGGTAAACAAGGGGAA
CACTCCCTTTACATTTCGGCCCCTGCTCCTCAGCGGTACGGGACTACCGGTTATGAGAGG
ACCGGCAGGAGTTTAGAGAGGATTCCGGTCGTACCCGAAAGCGGCACGTATCGGACCGAA
TCGGTTCGGGTTGGTAAAAAGACC------CATCATCAAAACCGCATGCGGTCTATTGAA
TCACTGGCACTCGAATCGCCACAGCTACAAAAGCAAAGTTCT---ATTGAGACTGCTGGT
CTTCCTCGATCACAGAGTGAGACGACCACAGG---CTTCAGTGGCTCCAGACGCCACTGC
CGGAGCCGCGACGAACAGAGGAGACACACCATCACTAATGGAGTCGATTATGGGATGCTG
AAGCAGATGAAGGAGCTAGAGCAGGAGAAGGACTCTCTGTTGGCAGGGCTGGAGGTGGTG
GAACGTGCTCGCGAGTGGTACCAGGCACAGATCCACAGCGTCACCGAGAGACAGAGACTC
GTCGGCCAAAGCAACCTCTGCGCGGATTTCTTGACCGAATCCAGTCAGAGTCGAATTAAT
GTTCTCCTACCCAAGCTACAGGAAGTCAACCGCTGCCTTAATGATCTCATATCCTGCTCC
GGAATGCAGCAGTCCTTCTCCCCCAATGCACAGCCCCCCACCATCTCTCCCACTGCCCAG
TCCTC------TGCCACGGCCGCCCCACAGGCCATCCAGAGACTGAAGGACCAGAACCGG
CTTCTTACTCAGGAGGTAACTGAGAAGAGTGAGCGCATCACCCAGCTGGAGCAGGAGAAG
TCTGCCCTCATCAAGCAGCTCTTTGAGGCCCGTGCCAGAAGCACCCACGACAGCAGCACC
CTGGACTCCACGTTCATCTGA
>Distichodus_sexfasciatus_gill_4|008982|scaffold12965|m.14009
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------AGACGACACACCATCACTAACGGAGTTGACTACGGAATGCTG
AAACAGATGAAAGAGCTGGAGCAGGAGAAGGACACCCTTCTGGCTGGGCTGGATGTGGTG
GACCGGGCCAAGGAGTGGTACCAGAGTCAAATCCACAACATCACAGAGAGACAGAGGCTC
ATTGGACAGAGCAGCCACTGCACGGATTTTCTGACCGATTCCAGCCAAAGTCGTCTGAAC
GTCCTGCTGCCCAAGCTACAGGAAGTTAACCGCTGCCTTAACGATCTCATATCGTGCTCT
GGAGTG---TCATTCCCCTCTCCAAGCACCCAGCCCTTCTCCATCTCCCCCGGTGGTCAG
CCT---------GTTCCAGCTCCTCCACAGGCCATCCAGAGGCTAAAAGACCAGAATCGC
CTTCTCACGCAGGAGGTGACCGAAAAGAGCGAACGCATAACCCAG---------------
------------------------------------------------------------
---------------------
>Gasteropelecus_sp._gill_3|018417|scaffold29723|m.31323
GGCTGGGACGGGAGCGGGGGGCTGGGACGGGAGCGGGGGGCTGGACCGGACCGGAGTGCC
GGGTGGAGGGACTGTAAACAAAGCAGCGTTCAGACCGCCGAGCTGAGATCTGAGCTCCGG
CTCCTCCTCCGAGCCGCCGAGCCGCCGAGCCCCATGGCTTTAGTGGCGGCGGACCCGAAC
TGCAGGCGGGACGGGCTCTCCAGCTCCCGCGGGGCCGCTGTCAGGAGGGCGGCCGAGCCG
TGCGAGCCCGGCGgggtgaagcgGAGCGGGATGCGGCCGCAGGGCGCGGAGCTCGGCACG
GAGGGTTTACCCAGAGCCTTCCTGCACAGCCTGCGGACCCTGTTCGACATCCTGGACGAC
GGCCGGCGGGGCTTCGTGCACATCTCGGAGATCGAGGGCCGCTGGCGGGGCGCGGAGGCG
CAGGGTCTGCCCGGCGGCGTGCTGGAGGGCCTGAGGCGGGCGAGCCCCGCGCACGGCTGC
CTGACGTTCGAGCGCTTCGTCGCGGGGCTCCGGTACTCGATGCTGAACCCGGAGACCGGC
ACCCAGGCGCGTCACCC----------GGACCCGCCGCCGCTCG----------------
-------------------------------------------CGCGCGCTTACGACGGG
AAGGTGCGGCCGCTGGG---GAGCAACGGAGCGCCCGCTCACCCCGCCCGGGCCTCCTCG
CTGCAGAGCCGGGCGAGAGCCGAGGAGAGCGGCTCCCTGTTCCCCGCCTCCGCTCCCAGG
TACCCC------------------------------GGGGGGGCTGCAGCATACGAGCGG
ACCGGTAGGAGCCTGGAGCGCGCGCAGGCCGGGCACGAGCCCGCCGCTCACAGGACGGAC
TCGGCGCGCGCTCCCAGAAAGGCTCCGCAGCAGCAGCGGAGTCGACTCCGATCAACCGAG
TCACTGGCGCTCGAGTCCTCCTCCTTCCAGAAGCCCAATCCTCACAGTGAAAGCAATGGT
CTTCCTCGATCACAGAGTGAGAGTACTACAGG---CTTCACAGGGTCCAGAAGGCATGGG
AGGACCCGAGACTCACAGAGACGACACACTATCACTAATGGAGTTGACTATGGAATGTTG
AAGCAGATGAAGGAGCTTGAGCAAGAAAAAGACTCTCTCCTGGCTGGGCTTGATGTGGTA
GAGAGAGCAAGAGAGTGGTACCAGAGTCAGATCCACAATGTCACTGAGAGACAGAGACTG
GTTGGACAAAACAGCCACTGCACTGATTTTATGACTGAAGCCAGTCAAAGTCGCCTGAAT
GTCCTTCTTCCGAAACTACAGGAAGTGAACCGCTGCCTTAATGATCTCATATCGTGCTCT
GGAATG---TCATTTCCTTCACCAAGTACACAGCCCTCTTCCATCTCTCCAAGTGTCCAG
ACT---------GGCCCAGTCCCTCCACAGGCCATCCAGAGACTGAAGGACCAAAACCGA
CTTCTCACACAGGAGGTGACGGAGAAGAGTGAGCGTATTACCCAGCTGGAGCAGGAGAAA
TCGGCTCTAATTAAGCAGCTGTTTGAGGCACGAGCTCGTAGTGCTCATGACAGCAGCGCC
CTTGACTCAACCTTCATATGA
>Lepidogalaxias_salamandroides_Head_2|006796|C518780|m.44434
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------GCAGC
CTG---------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------TACAGCAGC
AAGGCTCTGCAGTT----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------TTTCCTGTG-----------------
--------------------------------------------------------GCTG
AAGAAGATGAAGGAGCTGGAGCAGGAAAAAGACTCACTTTTGGCAGGTCTTGACATAGTA
GAACGGGCCCGGGACTGGTACCAGAACCAAATCCACAACGTGACGGAGAGACAGAGACAG
ATTGGTCAGAGTAATCAGTGCATGGACTATTTCACAGAATCCAGTCAAAGTCGCCTGAAT
GTTCTGCTTCCCAAATTACAGGAAGTCAACCGCTGCCTTGGTGACCTCATATCTTGTTCT
GGAACG---TCCTTCCCCTCATCTGGCACAGCGCCCCCAGTGGCCTCGTCCAATCCGCAG
CCTTC------AGGCCCTGTCCCCCCTCAGGCCGTTCAGAGACTGAAAGACCAGAACCGC
CTTCTCACCCAGGAGGTGACTGAGAAGTGTGAACGCATCTCTCAGTTGGAGCAGGAGAAG
TCGGCTCTCATCAAACAGCTGTTCGAGGCTCGATCTCGGAGCACGCACGACACCAGCGCC
ATGGACTCCACCTTTATCTGA
>Pantodon_buncholzi_mixed|001270|C597245|m.31241
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------GTG
GAGAGAGCTCGGCACTGGTACCAGAACCAGATCCACTGTGTGACGGAGAAGCAGAAGCAT
CTGGGTCAGGCTAACCATAGTGTGGATTTTCTACCAGATCCTAGTCAGAGTCGTCTAAAT
GTACTTTTACCCAAACTGCAAGAAGTAAACCACTGCCTCACTGAACTCGTATC---TTCT
GGAGTG---TCATTTACAATACACAATGCCTTGTCATCAAACATCTCCATGAACTCCCAG
CCTCT------GCCCCAGGTTCCTCCCAAAGCTGTTCAGAGGCTGAAGGATCAGAACCGC
CTTCTTACACAGGAGGTGACGGAAAAGAGTGAGCGGATCACCCAGCTGGAGCTGGAAAAG
TCAGCACTCATTAAG---------------------------------------------
---------------------
>Scleropages_formosus_red_gill|017724|scaffold27725|m.35967
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------ATGAAGGAGCTCGAGCAGGAGAAGGACTCCCTGCTTGCCGGGCTGGATGTGGTG
GAGCGGGCCCGCGAATGGTACCAGAACCAGATCCACGGCGTGGCCGAGAGACAGAAGCAC
GTGGGCCAGGCCAGCCGCTGCACGGATTTTTTTGCAGAATCCAGTCAGAGTCGCATGAAC
ATCCTCCTTCCTAAACTGCAGGAAGTGAACCGTTGCCTTGGTGACCTCATATCCAGTTCT
GGAATG---CCCTTCGCATCACACGGTGCTGCGCCTGCAGCTATTCCCTCGAACCCTCAG
CCGCCGCCGCCGCCACCCGTAGCACCGAAAGCCATTCAGAGACTGAAAGAGCAGAATCGT
CTGCTCACTCAGGAGGTGACAGAGAAGAGTGAGCGCATCACCCAGCTGGAGCAGGAGAAG
GCTGCGCTCATCAAGCAGCTGTTCGAGGCTCGCGCTCGCAGCGCTCACGACAGCAGCGCT
TTGGACTCCACCTTCATCTGA
>Synodus_sp._gill_5|016491|scaffold21843|m.28633
G-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
CTGGCACTCGGAT-----------------------------------------------
------------------------------------------------------------
-----------------------------------------------------TGAAAAC
AAAGTTCGGCCGTTGGGGCCAAGCAATGGAACCAACACGCAGC---ATCGCGCGTCCTCG
CTACAGAGCAGGACAAAGCCCGAGGATGGTAGCGGTTATGCCGCCTGTGGAGCAACAACC
CGCTAC------------------------------------AATGCGGGTTTCGAAAGG
ACTGGAAGGAGTTTGGAGCGGATCTCCATCGTCCCGGAGAGTGGCACTTATCGAGCAGAT
CCCGGCCGGGTTGGTAAACAAACG---CACCCGCAGCAAAGTCGTGTGAGGTCCATTGAA
TCCCTGGCACtGGAGTCTCCACAACTCCAAAAACCAAGTGTT----GTGGAGTCA--GGA
CTACCGAGATCTCAGAGCGAATCAGCGACAGGGTTTTCTGGCAGCTCCAGGCGACACGGG
CGAAACCGAGATGAGCAAAGACGGCACACCATCTCCAATGGAGTGGACTATGGAATGCTG
AAGCAGATGAAGGAGCTGGAGCAGGAGAAGGACTCTCTGCTGGCGGGCCTGGAGGTGGTG
GAGCGGGCCAGGGAGTGGTACCAGGGCCAGATCCACAACGTCACCGAGCGGCAGCGGCAG
GTCGGCCAGAGCAACCAGTGCACGGATTTCTTCACAGAAGTCAGTCAGAGTCGCATGAAT
GTCCTACTTCCCAAGCTACAGGAGGTCAACCGCTGCCTTAATGACCTCATTTCCTGCTCC
GGAATGCATTCGTTCCCTCCCCCTGGTGCTCAGACCACTGCCCTCTCCACGAGTTCACAG
CCC------------CCAGCCCCCCCGCAAGCCATGCAGCGACTCAAGGAGCAGAACAGG
CTCCTCACACAGGAGGTGACGGAGAAGAGTGAGCGCATCACACAGCTGGAGCAGGAGAAG
TCGGCTTTGATCAAGCAGCTGTTTGAGGCCCGTGCCCGCAGCGCACACGACACCAGCGCC
ATGGACTCCACTTTCATCTAA
