>Amblygaster_clupeoides|033103|TR58920|c0_g1_i1|m.80336
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------TATGAGAATGTG
CCCATTCCATGTGTAAATGCAGTAGATGATGAGGGCTGCCCATCAGACTACAAGTATATC
TCTGAGAACTGTGAAACCTCCGCCATGAACATCGACCGCAACATCACACATCTACAGCAT
TGCAGTTGCACAGATGACTGCTCCTCCAGTAACTGTCTGTGTGGCCAGCTCAGTATTCGA
TGTTGGTATGATAAGGATCAGCGGTTACTACAGGAATTTAATAAGATTGAGCCTCCACTG
ATCTTTGAGTGCAACCTGGCCTGCTCCTGTCACCGCACCTGCAAGAACAGAGTGGTGCAG
GCTGGCATCAAGGTGCGTTTACAGCTCTATCGGACAGAGAAGATGGGATGGGGTGTGAGA
GCTTTGCAAGACATCCCCCAAGGCAGCTTCATTTGCGAGTATGTAGGGGAGCTGATCTCT
GATGCTGAAGCTGATGTGAGGGAAGATGACTCCTACCTCTTTGACCTGGACAATAAGGAT
GGAGAGGTGTATTGCATAGATGCACGTTACTATGGCAACATCAGCCGATTTATCAACCAC
CTGTGCGATCCAAATATCATCCCAGTGCGTGTCTTCATGCTGCATCAGGACCTGCGTTTC
CCCCGCATTGCCTTCTTCAGTTCCAGAGATATCTTCACTGGACAAGAGCTGGGGTTTGAT
TACGGGGACCGTTTCTGGGACATCAAGAGCAAGTACTTTACCTGCCAGTGTGGCTCGGAG
AAGTGCAAGCACTCGGCTGAAGCTATCGCCCTGGAGCAGAGCCGCCTTGCTCGCCTCGAA
GCCTGCCCAGAGCAATGTGCCGATTCTGGACTGACCGTGTTGGGAAACTCATAG
>Corydoras_julii_viscera_mixture_8|019544|scaffold8920|m.6018
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------CTTCAGATCAACAGGAAGTTACGAAGAGGAATTGCCAAT
CGCATGGTTCGAACTGAAAGGATTATCTGCAGTGATGTGGCACAAGGCTATGAGAATGTG
CCAATCCCATGTGTAAATGCTGTCGATGATGAAGGCTATCCCTCAGATTACAAATATATA
GCTGAGAACTGTGAGACCTCGGCCATGAACATTGACCGCAACATTACACATTTGCAGCAC
TGTAACTGCACTGATGACTGCTCTTCCAGTAACTGTCTATGTGGAGAACTCAGCATCCgt
tgttggtatgacaaGGATCAGCGCCTTCTACAGGAGTTTAACAAGATTGAGCCTCCTCTG
ATCTTTGAGTGTAATCTCGCCTGCTCCTGTCACAGGTCTTGCAAGAACAGGGTGGTACAA
GCAGGcatcaaggtgaggctgCAGCTGTACCGTACAGAGAAGATGGGATGGGGCGTCCGA
GCTCTACAGGACATTCCTCAGGGGAGCTTTATCTGCGAATATGTGGGAGAGCTGATCTCT
GATGCGGAGGCGGATGTAAGAGAAGACGATTCATATTTGTTTGATCTTGACAATAAGGAT
GGAGAGGTGTACTGCATTGATGCCCGTTACTATGGTAACATCAGTCGTTTCATTAACCAC
TTGTGTGACCCGAACATCATTCCAGTGCGTGTGTTTATGCTGCATCAGGACCTGCGCTTC
CCTCGAATTGCTTTCTTCAGCTCCAGAGACATTCTTACAGGACAGGAGCTTGGCTTTGAT
TATGGAGATCGTTTTTGGGACATCAAGAGTAAATATTTCACGTGTCAGTGCGGCTCAGAG
AAGTGTAAACACTCAGCAGAAGCGATCGCATTGGAGCAGAACAGACTGGCCCGTCTGGAG
TCCTATCCG---------------------------------------------
>Lepidogalaxias_salamandroides_Head_2|008570|C534806|m.47434
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---TTTGAATGCAACCTGGCGTGCTCCTGCTACCGAACGTGCAAGAACCGGGTTGTCCAG
GCGGGCATCAAGGTGCGTCTCCAGCTGTACCGCACTGAGAAGATGGGCTGGGGAGTGCGG
GCCCTGCAGGACATCCCTCAGGGCAGCTTCATCTGCGAGTATGTGGGGGAGCTGATATCT
GACGCAGAGGCAGATGTGAGGGAAGACGACTCGTACCTCTTTGACTTGGACAATAAGGAT
GGGGAGGTGTACTGCATTGACGCCCGTTACTATGGCAACATCAGCCGCTTCATCAACCAC
CTGTGCGACCCCAACATCATCCCAGTGCGCGTCTTCATGCTGCACCAGGACTTGCGCTTT
CCCCGCATTGCCTTCTTCAGCTCCAGGGACATTCTCACAGGACAGGAGCTAGGGTTTGAC
TATGGAGATCGTTTTTGGGACATTAAGAGCAAGTACTTCACCTGTCAGTGTGGATCAGAG
AAGTGCAAACATTCAGCTGAAGCCATCGCTTTGGAGCAGAGCAGGCTCGCTCGACTGGAG
ACCTGTCCAGAATCGGGAGCTGATCCAGGGTTTGTGACATTAGGAAACTCCTAG
>Melanotaenia_praecox_viscera_mixture_8|009787|scaffold14576|m.13905
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------AACCACGCCTGCTCCTGCTGGAGAACCTGCAGAAACCGCGTGGTCCAG
AACGGACTCAGAGTCCGGCTGCAGCTCTATAGGACAGAGAAGATGGGCTGGGGAGTGAGG
GCCATGCAGGACGTCCCTCAGGGAACCTTCATCTGCGAGTATGTCGGGGAGATCATCACC
GACGGCGAGGCCGACAAAAGAGAGAACGACTCCTTCCTCTTCACCCTCGACAACAAGGTG
GGCGACGTCCACTGCATGGATGCCAGGCTCTTTGGCAACATCGGCCGCTTCATCAACCAT
CTGTGTGAGCCCAACCTGCTGGCTGTGAGGGTGTTCACCATGCACCAGGACCTCCGCTTC
CCCCGGGTAGCCTTCTTCTCCAGCAGGCCCATCAAGGCTGGAGACCAGATCGGGATGGAC
TACGGCGAAAACTACTGGAGGGTGAAGAAGAAGTACTTCGGCTGCCAGTGCGNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNCCGCCGGCAGA------
---------------------------------------------------TAG
>Pantodon_buncholzi_mixed|019256|scaffold494|m.548
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------CGGAGC
GATACTCCAGTCTGGGTGGCGCTGCAGATCAACAGCAAGCTGAGGAAGGGAATAGCCAAT
CGCGTGCTACGCACTGAGAGGATCATCTGCAGTGATGTAGCCCAAGGCTACGAGAACGTT
CCTATTCCTTGTGTGAACGGTGTTGATGAAGAAGGCTGCCCGTCCGACTACAAGTATGTC
TCTGAGAACTGCGAGACGTCCGCAATGAATATCGACCGCAACATCACGCACTTACAGCAC
TGCAGCTGCACCGATGACTGCTCCTCCGGTAACTGCCTGTGCGGCCAGCTCAGCATCCGC
TGCTGGTACGACAAGGATCGGAGGTTGTTGCAAGAGTTCAACAAGATCGAGCCTCCGCTT
ATCTTTGAATGTAACCTGGCCTGCTCCTGCTATCGCACTTGCAAGAACCGGGTGGTCCAA
GCAGGAATCAAAGTGCGCCTCCAGCTGTACCGCACAGAGAAGATGGGCTGGGGGGTCCGT
GCATTACAGGACATCCCACAGGGGAGCTTCATATGCGAGTATGTGGGTGAGCTGATTTCT
GATGCTGAAGCTGATGTC------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------
>Scleropages_formosus_red_gill|027576|scaffold43480|m.57647
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------GTCCAA
GAAGGCATTAAGGTGCGTCTCCAGCTGTATCGCACTGAGAAGATGGGATGGGGAGTGCGT
GCACTGCAGGATATCCCCCAGGGAAGCTTCATCTGCGAATATGTAGGAGAGTTGATTTCT
GATGCAGAGGCTGACGTGCGGGAGGATGATTCATACCTTTTTGACCTGGATAACAAAGAT
GGTGAAGTGTACTGCATTGATGCACGTTACTATGGCAACATCAGCCGCTTTATTAATCAC
CTGTGCGACCCCAACATCATCCCAGTCCGGGTTTTTATGCTGCATCAGGACCTGCGGTTT
CCNC-----GCCTTCTTCAGCTCAAGGGACATCTTGACCGGACAGGAGCTTGGGTTTGA-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------
>Synodus_sp._gill_5|019615|scaffold25116|m.34806
ATAGACAAATCCTTGAGGACCCCTCTCTTAGAAGCTATAGTCAACAACCATGTGGAAGTG
GCTCGCTACCTTGTCCAGAGTGGGGCCAGCGTGTACCATACGGAAGAGGATGGGTACACG
GGGCTTCACCACGCAGCCAAACTGGGCAACCTGGACATCGTCAACCTTCTGCTGGAGACC
GGACAGGTGGATGTGAACGCACAGGACAGTGGAGGCTGGACCCCCATCATTTGGGCAGCA
GAACACAAACACCTGGAGGTCATCAGAGCTCTGCTGAACCGAGGAGCTGACGTGACCATC
AAGGATAAGGAGATGAATGTGTGCATCCACTGGGCGTCCTTCTCAGGGTGCGCCAACATC
GCTGAGCTGGTGCTGAATGCAGGCTGCTCCCTGTCATCTGTCAACATGCACGGGGACACG
CCCCTGCACATCGCCGCCCGGGAGGGCTTCCACGACTGTGTGACGTTGTTCCTGTCCAGG
GGGGCTGACATCGACATCATGAACAGGGAGGGGGACACCCCCCTCACCCTGGCCCGTCCC
GACACCCCCGTCTGGGTCGCACTCCAGATCAACAGGAAGCTACGGAgGGGGATAGCCAAT
CGGATGCTCCGGACAGAGAGAATCATCTGCAGTGACGTGGCCCAGGGCTATGAGAACGTC
CCCATCCCGTGCGTGAATGCCGTGGACGACGAGGGCTGCCCGTCGGACTACAAATACGTG
TCAGAGAACTGCGAAACGTCGGCCATGAACATCGACCGCAACATCACACACTTACAACAC
TGTGGCTGTACGGATGACTGTTCCTCCAGTAACTGTCTGTGTGGACAGCTCAGCATTCGC
TGCTGGTATGACAAGGACCAGCGACTGCTGCAGGAGTTCAATAGGATTGAACCTCCCCTC
ATATTTGAGTGTAACCTGGCCTGTGGCTGCTACAGAACGTGCAAGAACAGGGTGGTACAA
GCAGGCATCAAGGTCCGTCTCCAGCTGTACCGGACGGAGAAGATGGGTTGGGGAGTGCGA
GCCCTTCAGGACATCCCCCAGGGAAGCTTCATCTGCGAATATGTTGGAGAGCTGATCTCG
GATGCAGAGGCGGACGTCAGGGAAGATGACTCCTACTTGTTTGATTTGGATAACAAGGAT
GGGGAGGTGTACTGCATCGATGCTCGTTACTATGGCAACATCAGCCGTTTCATCAACCAC
CTGTGCGACCCCAACCTCATCCCAGTGCGTGTCTTCCTGCTGCACCAGGACCTGAGGTTT
CCACGCATCGCCTTCTTCAGCTCCAGAGACATCTATACCGGGCAGGAGCTGGGATTTGAC
TATGGTGATCGTTTTTGGGACATCAAAAGCAAGTATTTCACTTGTCAGTGCGGATCGGAA
AAGTGCAAGCACTCGGCTGAGGCCATCGCCTTAGAGCAGAGCCGGCTGGCGCGACTGGAG
GCCTGCCCGGAATCAGGAACTGAACTTGGGATGACCATGCTAGGAAACTCCTAG
