>Corydoras_julii_viscera_mixture_8|010246|scaffold18149|m.13351
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------TACTGGTCCAACAAACAGAAATATGGCAAA
GACACCACGAGGGGGGGCTTCGACATGGCCATGTGGGAGATTGAAAATAACCCGGGGGTC
GGTTTCAGAGGTCAAAGGAGAGCTGACATGGAGAGGAGAGTCCGCGAGGGACG-------
-AAGAAAAGCCAAGAAAG-CTGAGAAAGtcagagcaaaAGAGCAGAGTAAAGAGAATGCA
---------------------------ACCCCTCGTAAGTCCTCATCTGCGTCTGA----
------------------------GACCCCAACACGAAAACCCTCGCTGAGC--------
------------------------AGGAGCACCCCGACGGCTTCACCCCCCAAAAA----
TACTGCAGC---------------------------------------------------
------------------------------------------------------------
-------------------------------------TGGTTCAAA-----------GCC
CAAAAAAGTAGCATCTGNNN----------------------------------------
-----------------NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNA
GGCATCCCGGTCCC-----------TCACTGTCCGCAGGAAGATCCTTAAAAAAGC----
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------CATTAAGAAAC
CTCCC----------------------------------------------------AAG
AAACTTCAGAAGATAAAG------------------------------------------
-CTGCAGTGCAAAACTTTAAGGTCCGGACACGTGGCTCTAAGATCAGGAGAGCATTTTT-
------------------------------------------------------------
----------CAAAGACTGAAGTTAGAACTCTAAGGTCTGGAGCTTCTGTGCCT------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------CAGTCCAGACACCCAACACTAAAGC----------------
------------------------------------------------------------
---------------------------------------------CCAGAAAAGCA----
------------------------------------------------------------
------------GGCACTCAGCCCATGGGCCAACGAGGTAGACCTAAA------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------A
GCTTGAGCACAAAA----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------CCTAGTAAATTATCTCTAAA
ATCCAAGGATTTCACTTCAAATCCCAGAATCCCAACTT----------------------
------------------------------------------------------------
-CAGAATCAAGCTTTTCC------------------------------------------
------------------------------------------------------------
---
>Distichodus_sexfasciatus_gill_4|013119|scaffold19680|m.21862
GCA---------------CAGCGGCGCGGCACGGCG---------CGGGGCAGCGGACCA
GCTCCAGAGTCCACGATGAAGTCTGCA---GCGCTCCAGCACGGCTTTACTCCGGGCGAT
ATCGTCTTCGCCAAGATGAAGGGATACCCGTTCTGGCCAGCCCGGATTGCTG----AAGG
AAAGACCCCA--------AGCAATAAACTCCCGATCTTCTTCTATGGAACACATCAAACG
ACACTCCTGACCCCTAAAGACGTCGTCCACTACTGGCCCAACAAAGAGATACACGGCCGC
TCGCTGAAACGCGGAGGATTCGACCGGGCCATGTGGGAGATCGAAAACGACCCCGGGGTC
GGCCTCAGAGGTCAAAAGAAAGCGGCGCTGCTGAAGAGGTTGGAGGAGAACCGGCCCTCG
AAGAAAAAGAGAAAAGCA---------GACGGAACTCCGAAAAAGGTCGAGCCACCCTCG
CCCAAAGACTCCCTACCAGCTCGCGCCTCTCCCTCTAAACTCACCTCTCCCGTTAAAAGA
CAAGCTCTCCCGAAACGCAGAGCGACCCCCGAGATCAAGGCGGCATCCGAGTCTCGAGGA
ACGAGAAGTACG------------AGCAGCACCGCGGGAATGACCCCCGCCAAAAC----
GGCTAAATC------------------------------GGGTCCATCGGAGAAGCTCAT
ACCCGCCAACGCGGCAACGCCATCCCCAAAAGCCATTCTGGCCAAGAAGGCCGTCCTGCT
GAGGAACAGGGAGGCTGCCGCCCCAAAGAAGAGGATCCTCTCCAAG-----------GCC
AAGCACAACACCGTCTCCAG------------------------AAGAGTGCCCACCAGA
AGGAGTTTGGGAAACAGACTCATCGTCAAGCTTCCTGCCATCGCAGC------CAAGCGG
AAAGTTTTGAGGTC---------------------CGGAGAGCCGCCGGTG---------
---CTGAAACGGAAGCTGCACCACGCCCCCTGTGGGCCGAACAAG---------------
---------------GCTCCTGCAGCCTCAAAACGGAAGACAGGagaag-----------
---------aGGAGGAGGAGGAAGAAGAAGAA----------------------------
---------------------------------------------------------GAA
AAAGGGAAGAGCAGAGG-------------------------------------------
-----------CAGAGTGAGAGAAGAGAGGGAGGAGTCTGTGAAGGAGACACCAGCG---
------------------------------------------------------------
-----------------------GATAACCCCACGGACGAGA------------------
------------------------------------------------------------
-----------GGAAGAGAAGGGGGAGAAAGAAGAAGAGAAGGAGGGGTAGACCCAGCGC
GGAGGAGAAGGAG-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------GGAGAAGCA----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>Gasteropelecus_sp._gill_3|015850|scaffold26211|m.26709
------------------------------------------------------------
---------------ATGAAACCCAAGTCTGAGTACAACCATGATTTTAATCCTGGAGAT
ATTGTGTTTGCTAAGATGAAGGGATACCCTTTCTGGCCTGCCAGGATAACGG----ATGG
AAAGGCTCCG--------AAAAACAAGATCCCAATTTTTTTCTATGGAACACACCAAACA
ACGACGTTGGTCTCCAAAGACATTGTCCACTACTGGCCAAATAAGGAGAAATATGGCAAA
GCCATCACACGTTGGGGTTTTGACAAGGCTATGTTGGAGATCGAAAATGACCCAGGGGTT
GGCCTCAGAGGTCAAAAGAAAGCAGCTTTGGTGAAGAAGGTAAAGGAGTGCCAGCAGTTA
CACAAAAAACAAAAAAGGACTAAAGATGGCCAAACACAGAAAAAGGGCGAAATGACACCT
GGAAAAATCTCCACATCA---------CATTCTTCTAAACCCATCACACCCACTAAAAAA
GAAGCATCTTTGAAG---AATGCAAGTCCAAAGACAAAATCGCTGTCTGAGACACAAAAC
CGAAAAAGAACACCTgtaggagttggtatcaaagatcagattgtggcagcaaagac----
gATTAAAACCTCCAGAAACATGACCAGTGGTTCAGCAGTGCACTCACCGAGGAAAGTGAT
CCCTGTGAATAAAATAATCCGGAACAAAAAGGTTATCCTCATCAAAAAAGCCATCCTCAC
CAAGAAAGTGAGCGCAGC-------AAGAAAAGTGGGTGTTTCAAGA-AAGAGCTCTGCC
AGGAGCAAAACCCTTTCTAAAGAAAGCAGAATTCAAATTGCCTCAAAAGTAGCAAGAAAT
ACGACGGCAGGAAATAAACTTAAGATAAAACTGCCACCTTTTACAGCGAACAACGAAACA
AAAGTTCTGAAGCCCTCTGTTGTGGTCACTCCGGTCACAGAGGCTCTAGTAAAAGCACAC
AGTCAGAAGATGAAGCTTGAGGAAGTTTCTTCTAATCTGAAGGAAAACACTCCAGCCATG
ATTGCTGCTATTTCCGGCCCAGGAGTCTCTAAGAAGGAGATACAAGAAGAAAAGTATGAA
AGAACAACAAGAAGGAGAGGGGAGAAGAAAAACAGAGATGAGGAAGGGCTGATAGAGGAC
CTTTTGGCTAAACCACAAGAGAATGATAAGCATGCTGTGTCACAGGTAGAAGAAAATGAA
AGAAGAAAGAGGAGAAGAGATGAAGAAGAATTGGATGAGAGTGAAAAGAAAAAGCATGGA
TGTAAACGACTGAGAATCANGAAAGAGAGAGAAGAGGTGGTGAAAAAGAGACAAGCAGTA
GAACAGCAAAAAATTAAGCAAACCGAAGAACGTACAAAGAAAGAAGAGGTGCAGAAGGAA
AAGGAAGTGATAAAGGAGGAAATGAGACTTACGCGGAAAAGAACACAGGAGGCTGGGAAA
GAGGAGGAACAGAATAAGAGAATTAAGCAAGACGATGTGCAGAAAAAGAAAGAAAAGGTG
GAGAAGTTGATGGAACAGAAGAGGAAAAAAGAGCAGGGAAAAGAGGAGATGAAGAAGCAC
CAAGAAGAAGAAGCAGCGCCAAAAAAGAAGGAACAGGTGGACAAACTGAAGGAGACAGAA
GAAAAGAGATGGACAAGAAAAGGAGTGCAGGAAGCCAAGAAAGAGGAGGAACAGAATAAC
AAAAGGAAAGAAGAAGCACTACAGAAGAGGAAAGAAGAGCAGGAGAAAGCAAGGAAGAAG
AAGCAGCAAGAGGAGGACGCTGTGCAGAAAAATGAAGGGGTGAATAAACTGGAGGTGATG
GAGGAAAAGAGACAGACGAGGAAAATGAGCAGAGGAAAAGAGGAGGAAGGGCAAATGATA
AAGCTGGAAGAAGCAGCAACAGCACAAAAAAAGAAAGTTGAAGCAGGTAAACTGCTGGAA
ATggagaaaaggggacaggaagctgtttggaaaaagaaagaagaggtGGATAAACTGAAG
GAACAGAGCAGGACTGGAGAACAGGAGACCCAGAAAGAAAAGGAACAGAAGAAGCAACAG
GACGAAGAGGCAGAGAAAGAAAAGGCTGCTGGAGAAAAAGACACACAGGACCAGAACAAG
GATCAGAGAAGTAAGGTATTGGCTGAGAGGAGGCTGAGTGTGCTAAAATCCCTTCAAGGA
TTTGTCACCTCCACCAGAGGAAAGCGGGAAATTCTGAAAAATGACAAACCCACTGTTGAC
ACCACAGATACGACGGTAGATAAACCCTCAGTCAAAAACATAATGGTGAATGAAGACTCC
AAACCAGTCACTCCAAAGCGCCTGGAAAGGAATCGTGCAGCGAAGGAAGAAGTGTCTGTT
AAAGCAGGGGAAGAGGGAAAAGAGGAGACGAGCAAGAAGACGTTGAGAGAGCGGAGTGGA
GAGAGGCCACAGAGAGAGGAGACCAGGGTATCGGAGCTGAGCAAGAAGAGCGAGGAGGAG
AAAGTGGACATTCGGAGAGCTTCTGCTCCATCAGTCACAGACTCTCTGCTGTACAGACTA
CACGGTGATATCCGAATCTCTATGACCCTTGACAATCCGGATGTGAGTAAGTGTTTATTG
GCACTTGATGAGTTGAGCACAGTCTCTGTCTCCTCTCGGCACATACAGAACCACAGTGAG
CTCATCGACACGCTCAGAAAGATGCGCTGGTTCCGGGGCAGTGAGGACATCATGTTTAAG
GCCTCTATGCTATACTATCGTTTCAAAAACATTTACCTCATCGGTGACTCGGATGAAACA
CTCAGTCAGGAGTACATAAACACTCTTCAGGAGGACGGGGAGAGAGTGGAGAGGGACAGA
ACAGAAGAAACTTTATCCCGTTCCTCCCAGCCTGATAAAGCTGAGGGGTCTGGAGCAGAG
AGACAGTCCACACAAAGCAGTAACCTGATAAGGCACAgtGCACGTGCAGAGGAGAGGAGC
TGA
>Lepidogalaxias_salamandroides_Head_2|007459|C525214|m.45528
------------------------------------------------------------
---------------ATGAGTGGAGAG------------------TTCAAAGCAGGGGAG
CTGGTCTTTGCTAAGATGAAGGGGTACCCTCACTGGCCAGCCAGGATTGGTGTGGTCCGC
AAAGGCGCCACTCCACCCAAAAACAAAGTCCCCATCTTCTTCTTCGGTACACACCAGACA
GCCTTCCTTATCACTAAGGACATCGTCCCGTACCTTGGCAACAAGAAGAAATATGGCAAG
CCAATCAAGAGAGGCGGCTTTATGGAGGCCATGCGGGAAATCGAGGATGAGCTGAAGGCT
GGCGT-------------------------------------------------------
---------------------------GACGGGACACAAGACAAAGTCAAG---------
------------------------------------------------------------
-------------------------GCCAAAAAGTGAGGCCGCTGGTTCAGTCCAGGAGC
AGAAACAGGA----------------------------------------GAAGGG----
GAAGAAGTC---------------------------------------------------
------------------------------------------------------------
-AGAAGAAAAAGAGC-------CAGAAGAAGAAGGGTCGGTTGAAA------CCCCAGCT
AAGCCTAAAGCCA-----------------------------------------------
---------------------------------------------------AGAAAAAGA
AAAAGGCTGA-------------------------CGAGGAG-----------------C
AGTCAAAGACAGATGCTTCCCCTGACCCTCTCT---------------------------
-------------------------------------------------------CCAGA
ACACCAACAGGGGGCAAGAGGAAGCAGCAGGCCA---------------CCACGGCGAAC
CCCGCCCCTGA----------------------------------------------GAG
GAAGAGAAAAAGACAGGA------------------------------------------
-----------------TGGAGGAGGAAAACAGGATTCAGAGCTGAAGAGCTCAGTAGT-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------GGATGAGGAGGAGAA----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------GAAGAAGCG----
------------------------------------------------------------
-----------------TCTGGCCGTGAGAAGGCAGAGTGTACTCAGGTCTCTGCAGGGT
TTACTGACCATAGACAGGAGACAT------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------C
GCAAGGACACAGAG----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>Melanotaenia_praecox_viscera_mixture_8|003559|C439710|m.29391
------------------------------------------------------------
------ATGCCCGGGAAAAATGGAGAC---------------CAGTTCAAACCTGGAGAC
CTAGTGTTCGCCAAGATGAAGGGCTTCCCCCACTGGCCTGCTAGGATCTGTAAGTCAGAC
GACGGGTAC---------AAGAAGCGAATCCCGGTCTTCTTTTTTGGAACCCATCAGATA
GGCAGCCTCCCGCCAGAGAACGTTGTTCCGTACGTCGGTAATAAGATGAAATATGGCAGC
GGCGTTCGCATCAGAGGCTTTGCTGAGGGAATGTGGGAGATTCAGAACACACCGGGGATT
GGGAGTAAA---------------------------------------------------
---------------------------CTCAAAGTTCCAGGAAAGACCAACGTCAGTGCG
---------------------------ACGCCTGCAAAACCGACTTCTGCTGCTAA----
------------------AGCTACACTCACAAAACCAGA---------------------
--------------------AACTACACACGATAAACGAACTCCAGCAGCTAAAACTGTT
GAGAAAGTT------------------------AAAGGTGTTCCTGCTG-----------
------------------------------------------------------------
----------------------CTGATGGTAAAGTTGCAGCTGAAAAAGAAACTCCCGCT
AGAAGCGCTACCA-----------------------------------------------
------------------------------------------------------------
-------------------------GAGCTTCATCCAGGTTAGCTCCAGACAAAACCACC
GACTCCAAACAGA-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------TTTCAG
AAACCACAGAACCCACCA------------------------------------------
----------CGACTACTAGAAGCAGGAGGG------CTGCGAGCGGGGGTCCGTCTGC-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------AGGACAGAGCAGGAG----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------TGAACGGAGCT----
------------------------------------------------------------
------------CCTCTGCAGACAGTAAGAGAACGA------------------------
------------------------------------------------------------
----------------------------------------------------------CC
AGATCA------------------------------------------------------
-----------------------------------------------------------A
ACAAAGCCTCCGAA----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------CAAGAATCTGCTCCT----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>Sargocentron_rubrum_gill_6|011550|scaffold18831|m.22578
GAAATTTTTACTCATTTTCAAAAGATTGTTGCTCCGTTTTCTCTCCGAGGAAAC------
------ATGCCACCGAAAAGCAGCGAG---------------TGCTTCAAACCAGGAGAT
CTGGTGTTCGCCAAGATGAAAGGCTTCCCGTACTGGCCTGCCAGGATCTGTAAGGCAGAG
GATGGGAAC---------AAGAAGAGAATCCCGGTCTTTTTCTTCGGGACCCATCAGATC
GGTCTCCTCCCCCCAGAAAACATCGTCTCGTTCCTCGGCAACAAGCAGAAGTTCGGCAGC
GGCGTTCGAATCCGAGGCTTCGCCGAGGGCATGTGGGAGATCCAGAACACACCgggagtg
ggaagtaaa---------------------------------------------------
---------------------------ctcaaactgcCGACAAAGACAGCAGAAACAAAA
---------------------------ACTTCACCCAAA---GCCTCCGCTGCTAA----
------------------AACGCCGCCCGCCAGACCAG----------------------
----------------------------------------CTGCAGCCGCTAAGAC----
-----------------------------------------GCCCGCCG-----------
------------------------------------------------------------
----------------------CCGCCGCT---------------------TCTGCCGCC
AAAACTGCTGCCA-----------------------------------------------
------------------------------------------------------------
-------------------------AAACTGCCGACAAGCCGTCGCCCGCGAGAGCCGGC
AGCGCT------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
>Synodus_sp._gill_5|001188|C520773|m.41522
------------------------------------------------------------
------------------------------------------------------------
CTGGTGTTTGCCAAGATGAAGGGCTTCCCGCATTGGCCTGCCAGGATCTGCAAGACAGAC
GAAGTCAAC---------AAGAAGAAAGTTGCTGTCTTCTTTTTTGGAACCCATCAAACC
GCCCTTGTGCCCCTGGGCAACGTGGTGCCCTTCGTGGGTAACAAGGGCCGGTATGGGGGC
AAGGTCCGCTTCCGCGGCTTTGCCGAAGGGATGTGGGAGATAGAGAACAAGCCCGGCTTA
GGAAG-------------------------------------------------------
-----------------------------CAAGACTCCCTCAAAGTCAGTCGAAAAGAAA
GT-----GCTCCCACTCAAAC----TTACTCCAACCAAA---ACTTCTGCTTCCAA----
------------------AACACCTCCAACTAAATC------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------CCTCCGGGGAAGACCGTC
CGCTCTGGACA-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------CTTCAGCTAGCAAACCA----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---
