>Amblygaster_clupeoides|009392|TR19384|c0_g1_i1|m.37937
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------CAGCAG--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------CAAAACCAGCAACCGA------------------------------A
TGTGGTGCCTGGCTCCACCACGGTTGCCCAGGCTTCATCTCCTGCTT---CAGCGTCTGC
TGTGCCACAGGTTGCTTCTTCTGTCAGCGCCAAGGCAGAGGTTCTAACAACCTTAACAAT
ATCATCAGAAAATCAGGCACCCTCAGAAGCAGTGACGCAGCCTGCTCAG---CCAGCAGC
AGTGAAAGTAGATATTGAGGGGGAGGAGACACAAACAGAAGTTGCTGGCAAATCTGGCAG
ACACAGGCAAAGAAAGGCAAAAGAAG---ACAACGAAGAAGGAGTGCCAACCAGCAGGCA
ACGGAGAAGACGGCGAGCTGTGCCTGTGACT---------------TCAAAGGAGGAGCC
AGACAC---CACAAACACAGGAACAAATGC------AGTAGGGATATTTCAAGAT---AA
ACAAAATAACGTCTTCGCTCCATATATACACGTGGAGAGGAAGATTGCAGAGCTTGGGGC
TGTGTGTACTATTGTTAATGCAGAGGAGGAGAAATTAAAGTCTGG------------AAA
AGGCAGTGGGGGTGGGAGT---------------------GGTACAGACACCCTCTCAAA
TCTTGCT---------CAGATGGTGAAGCGAGACAAAGACATGGCAAGAGTGAAAGAAAA
CCGGGTCAGCGAGCAGGTCGACTCAGCCCT------------TCAGTCCGGAAAAGCTCT
GCCCGCATCTGGGTATGTGCTCCCAGGACCTGTGATCTCTGAAACAGCGCACACTGGTCG
TCTGCTTTGTTGCCTTTGTCAAAAGTGGGCCAACTACAAACATCTTGGAGATCTGTATGG
CCCCTATTATCCCTCAGAGTATGTCTCTAAACTTCCCAAGAATCAACCCCAGGTTAAGCT
GATTCTCTCACATCCTGGATCCAGTGCAGCAGGAACAAATGTGATATCTAATTCAGCTGA
CACAAATGATGCACAGTTACTGGACTCATGTCACGCTAAT-------------GTCAAAT
CCTCAACAGACAGTGATTGTACAGCTAGTCATGCAACCAACCCAACATCCCCTGCTACCA
CAGTGGGCACAGCATCTCCAGCAGCTGGTGAGGAGATG---CCCTCCCTCTCCTACAAAA
CTGCCAGTGCCACCATC-------------------------------------------
--------------AACAGGAAAGTGCATAATTGGGAGCTGACCCATGAAAAGCCCACAG
TAACAGAACCACAGAAGCCACCAGAGCTGCAGAATGAGGTCACAGGCGAGCC------GA
AGCGGCAAAGCCAACACCAGCAGCCGGACGATGCCCAACAGTGGCCGCAACACAGAAAAC
TCACCTCGCATCCACGATTCAAACGACGACACAAATCCGGTGAAGATTTACCCAGGACCA
TCCCCAGCAACAACAAAGCCTCATTGCCATTCCAGCCCCCACCACC------------TA
GCCTGGACTCTCTTGGTCCTTTGGCTCAGCTTGCCCAGCTCCCTCAAGTGCCCCTTGACC
CCGAGGAGCTCTGGGTGCATGAAGGATGCATAACCTGGGCAAGCGGGGTGTTTCTGGTCA
GCGGAAAACTGTATGGCTTACAGGAGACACTAGAAGGTGCCAGAGAAACAAATTGTTCTC
ATTGTGAAATGGTTGGCGCAACCCTTGGTTGCCATAGCAAAGGCTGCACGCTAAGATACC
ACTACATCTGTGGCATAGAGGCAGACTGTTCTATGAATGAAGAAAACTTTTCACTTAGGT
GTCCAAAGCACAAGTTCTCCCAGAGCAGCAGACCA-------------------------
--------------------
>Distichodus_sexfasciatus_gill_4|008653|scaffold12465|m.13374
GCCATGCAGCAGCCCCAGCCCATCCTCCAGAGTCACGGGCAGCTCCTGCACCTGCGGGGG
CAACAGGGACACCCAGGACAGGTGTCCCATATCCATGCCTATGGATCCAGGCGAGGCGTG
GCAGACGTACCCCAGGCTGCTGCCCACAGTGGAAGCAGTAATAACTCTTACCGAAAAGAA
AATATGGATTATTATTATTCGTTGGGCGGCAGGGATCGGAACAGAAGAGGGGGCGCAGGG
TATGGAGCAGTATTTGGGTACTCAAATATGGACGGTCACTTACCTCACCAGTACAGACAC
ATGTCTGTGCCAGGGTCATCCTCTGGCTTGATGTCCCCATACCCTGTGGACTACAGCACA
AGTGCTGGTGGTGCTAGTGGTGGTGGAGCAGGTGGTGGTTCATTTTCACCATCACAGCAG
TTTACTCAAAGCGCCTCGATCCAGCCAGCCACCAGTGCTGAAATGCTTCAGCGTCAACAA
AAATACCCCTCGCATCAGGGTCTGCATCAGGGCCATCGAGCATATTCTCTAGCTGCACAC
AGAATATCTTCTCAGTTTGGCCAATACCCTCCTCTTGGCACGCCTGCAGTGTCTGCTGGT
ATGTATAACTCTCCACCACAGAGGTATGAGACTGGCAGCAGTGGTGGGAGCTTGGATTCA
AAAATCAACTCACCTACCCACTCCCATCCCAACTCCACTCCAGTTACTGCTGCTTCTCAC
AATTCTGGACACCAAGAACACATGGGACAGAGTTTCTCCTCTACGGCTCATCCTCCCTAC
TCACCCCAGTCTCACCCTGTTCATAAACTCGCCTCTCGTCGAACTCCTCAGCACAATCTT
GGGACGAGCTTTGATGCCTCCTTGAAGATGGCACACGTTCCTCCAGGTCATATGCACTCT
AAAAATTCCCAGTCCTCGGTGTCGTCGAGTCCTGCGGGGCCTCACCAAACCTCGCAAGAC
ATGTCCAAATCTCCCATGCATTCCCAAAACCAGCCCAGTCATCTGAACCAGAACTTTAGT
CCAATTTCAAATCCTTCTCCAGCTCCGTCTGCTGTCCACTCACCGAGCTGCAGTTCCTCC
TCCTCCCCGCTCATGGGTGTCTCCGATGGACTTGGTAACAACCTGCCACCCACACTGCAG
CCAGCAACTCACTCTTCTCTCCTAAATCCCCGCAACAGCCAGAGCCACGTTAGGCCTCCA
CCTACTATGCCTCAACTTAGTCCGACTCCCAGTTCCAACAGCAGCATCAGTAGTTGCAGT
AGCAGCACAGGTAGTAAAGCAGCTGGTGTAAACCAAAATGTGGTGGGTGCTGCTTTGACT
CAAAATCAAATGGGAGTAGGTCCCAGGGGTGGACAGCGGGAAGGTGGCTCATCCTCTCTT
TATCCACAAGACAAGCTTTCACAAGACGCTGGTCTGAATAGTCTCAACGCTCTGACGTCT
CAAGTTGCAAATTTACCCAACACGGTGCAGCATATGATGCTGACAGACACAGTTCTCTCT
CAGAGGAAGATCAGAGATGGTGCACATCAGTCTCACCCCCAGCAGCCATCTACTAACCAA
CAAAAACTTCGAAATGCTAATTCTGCGGGTCATACTTTGACAAATGAAGAAAGTAGTGAT
ATTTTGGCACCTGAGCTAGAGGAAAGAAGGAAGGAGCATGGTGATGCATTAGAAGCTGAG
AAAGTTAAACAAAAATGTGGAGCGGAACCTAAGCCGGTGAACAACTATCCAGCAACTCAG
AGTCAGAAACAAACCCAAATGGGACAGGTTCGCCCTGGGTTTAATCTGCAGACAGACAGC
AAAATCACTGAGTCCTCCCTTAAACCATTCAGTCAAAATAAAACCCCTGAAACCCAGACT
CCTTCATCGTCATCTCCACTGTCAGTTCCTCCCTTTGCAGAACAGAGTCCAAGTGCACCT
ACTGGCCATCCTGCACCGTCACCCTCCACCGCCTCTCCTACTCGCTCTATACGATCAAAC
AGTTTGGTGGAACCTGATCTTGCTCATGTTGATGATAAGAGTGCATTGAGAGACAAAAAG
AATCTGACTTTGAAAGATGAAAAGCCCACAGAACCACATGGACATAAAGAACCTTCCAAG
CTAGAGATGTTAGAcaaggcggaaagtctacagttgctcaATATAAAAGTGGAACATTCA
GGGCCAAGCAAAGAAAATAAGAATGAGAAAGATGAAAAGAAAGGCAGCACACAGCATTTT
CCCAGTAAGAACTTGAACACAGAACAGTCAAATATTGGAGCCGTTGGTGTGATTGTTTCT
GCACGTTCAGAACAAAATCCTGATACGAGTAAACAACCAGAGGCCACCTCTCATTATGGT
GCTTCTTGCCACCTGGGGAAACCCAATTATTCAGAGGAGAAACATTCCATAAACATGTTT
AAGGATTCTGGCAGTCACAATGGAGGTGGAGAAATGGGTGTTGAGACATTCACCGCACAC
TATGATGTTACCCCCAAAACTGAATTTCCACAAGGTATGCCATCAAATCACTGTCTCTCT
GGGTCGTATAAGTTTGGGACACCGGAAGTCCAGTACAATGCTTGTATGGGTTCGAAGAAC
AAGGGAAGGACTGAACCTGTAGGTGGAATGGGTGCAAACAGATACCAAGACTTCCACCAA
CCACAGTCCAACTTTGGTTCTGTGCACAGAAAGGATGCCAGTCTTTTAGCACAGGTGAGC
AGAGGTGGTGTAGGACCTGGAATGAGAAGCCAGGATAGTAGTTCTCATTTACAGCAACCA
TTTCCCAGTCTTTTGCAAGAGGTCCTCCAGGGTTATCACTTAGATCGGCCCTATGGCCGT
CCCGAACAAATTTCCGGCGCTCATCACCATGGTCCAAATTTGACCCATTACCACACAAGA
CTCCCTTATCGCATGATGGAAAACATGAGGCCTCATGGTGTGGCATCATCAGTAATGACC
GGTGCTGGTGTTCATCAGATGGCCCCCGGAAAGCCTCAGAGCCAGGCATTGGATCAAGAG
ATGCGACAGGGCCTTCTTCATCCAGCTTGGGATTTGGAAGCACAAAGGCCAAAAGGGGAA
CATGGTGTCTCATTAGAGAAGAACACATTAAATATGTCTCCTGGCCATTCCACCAATGTA
CAGCAGTCTTTAGATTCTTCTGTTGGAACTCCTACTAAGCACATTAACTTGGCAGACTAT
TCTTTACCTCAGAGGAAACCCCTTAGCATAGCTACCCCGTCTTCTGCTGTCCAGCAGTTG
CTTTTACAGGAAAATGACTCATTACCTGGCAGTGTGGAACCCTTGAATCAGACCCAACCA
CAGGCATCATCATCCTCAGGAAGGCGTTCTGTAATATGTGATGTGTCTCCGTCTCGACGG
ACCACTCCAGAACGAGAAAGAGGTCAGTGTGGTACCTCTGCACCTTCAGTCATTCAGCAG
CCCCACTCATCCTCTGGGCTCAGTGAGCAAGGATGCACTAGGGAGGATGAACTTGATAAA
AGAGGACAGGAAACAAAAGACACTTCCAAGGTTATGCCTAAAGATTCTGTGATGCAAGCT
GCAGACGGTCACGATTCTGTGCAGCTTAAGGAAGAGCCAGGTAAATCCCTACATGGCTCC
ATGGATTTGAACTCTGACTTGCATAGACAAAGTGGTGGTAAAGCAGAAGCAATCTCTAAA
CACCACTTGTCACCTAATACCCTGTCATCGCCGCCAAGACGCAAACCGTATTCCCATGGT
CTTGATGGAACGCCTGCTGGTTTTTCTGCGTATGTGTTGAGTGAAACAGTAGAAGGATCC
AAACTGAACACTCATCGCCACTCTCTTAATCCATTCCATACATTGTCATCTCCAAGTCAC
ATTCCAGCGTCAGCTAACAAAATACATGCCTACCCACACCCTCTCTCTTTTCAGCACCCA
AATAGCATGGATGATAGATTTGACTGGTCTGCTAACAGTAATAGACCTAAAGATATTCCC
ATCCACCACAACCCTG------------AGCAAAAGGTCAAAATCCAGTCCCCAACTGAT
GGCTTTCCCAGTCAGCATCAC---TTAAGACAACACTCTT------------------AT
TCTGACTCTCACTATGACATGAAAATGTGGGAATCTTATGCTGAAAGAGATGGAGCTGGG
AACCAACAGGTGCACTCTGCAGCTACTCATGACTCTGCAGGCTCGCAGCAAGTTCCAGCC
AGAGTTCCCAAG---GTGGAGGCAGATGTTTCCCGGGGTATTACAGAAGAATTTTCTAAA
TCATTCCAGTCACCTGCTGCTGCCAGTGCCGTTGGTCCAGGTAGCATCGGCGGCAGCAGT
GTAACACCGAGTATTCATCGTCCCACCAAAACTGGAAGCTCAGCAGAAACGAACCCACTG
ATGATGAGAAGAAGAGTTCGCTCCTTCATCTCTCCAATTCCTGCCAAGAGGCAGCATCAG
GATTTTTCCAGTCACAGGGTT---------GCTCATCAATCCCCTGCACCCCTCTGTGAA
TCTAAACAACTGAATGACAATGACTCTTCAAGCGTGGATACAC---ATTCCAAACTATCC
TCCCCC----------AGCACACCGTATCACCCACCCAGTGCTACATCTCCCCTGCAGGG
GAAGACAAAGATTCTGCCCCCAAGAAAGGGACGGGGCCTAAAACTGGAAGAAATAGTGCA
GAAAATTACCCCAAATA--AAAAAGGCAGTTACAACAATAGCCATGTTGACTCTGATT--
----------------------ATGCAGAATTATCACATTTTAGCAGTGATTTACCTGAA
CCAGAgACTGGAACGCCTTTTTTTAATGCGCCTCCCAGAGA----AGGAGGTTGTTTACC
TTATCTTGATGAAGCTCACTCCTTAGATGAGCTTTTGCCTTTCCGAGCAGATGAAG----
--------------------CATATTCTTGTGATTCtcaagttcTCAAACAGAGTTCAAT
TGCCTCTTCCAGTGGCATGCTTAGAAATGTACCAA------------------------C
AGACTTTGACTTTGGGTTAGGCACAGCTGGCTC---TTCAGGGACTGGTA---------C
TGGTGAAGATGATAAGGA------------------TGAATTTACGCTTTTGGGACCTTT
GCCCCCACCACCACCATTACCTCGTCCTGTACAAGGTTCCCCACCTCCGTCATCATCTGC
ATTGTCTGATATACAGCAGTTCACCAATACCTACCAGCAGCTGGAGACCAGACGAGGGGA
GCAGTCTGCTGCTAACCTCCTGAGACAGAAACTTCAGGAGACTGGCA------TGGGTTT
TGATGATTATTCAGGAGCAGACTTCTATGGAGAATCATCACCCCA---TAGCCAAAGTCC
AGGACACCACCTTCTTTCGAGA------------------CCATCACAGCACCAGTTAGC
TTCTG------GCAGAATGGCAGCTTCAGATTCCAAACCAT------CTGAGAGCATTGT
TCCTAAAGGTTATTTCCCTTCAGGTAAGAAGAAAGGGAGGCCAGTAGGAAGTGTGAACAA
ACAAAAACGTGCACAGGTTCAAGTTCAGA------------------------------G
TGCCACAACTGGCATACCTGCAGCTGCTCAAACCCCTCCCGCTGTCGTTTCTGCAGCAGC
CACTCCCCAGACTGCATCAAACTCTAGCCCTGCACAAGACATAACCCTAGCTTCAACACT
TTCTGAACAGAAACCTTCTCCCT------CTTTGGATCTTGATGCCCAA---ATCCAGGA
GGCCAAACCAGATGTAGAAAGTGAGGACAACCAGCCTGAGGTGGACCTGAAGCCAACAAA
GCTCAAGCAGAAAAAAGCTAAAGAGG---GTAATGAAGGAAGTAGCTCAAAAGGCAGACA
GTGGAGGAGACGGAGAGGACTTGCCTC---------------------CACAGAAGATTT
AGAAACACAAAGTAGAGGTGTAGAAAACACCAGTCTAAATGTGATTTTACATGAT---GC
TAGGAAAAATGCTTTTTCTCCCTACATCCATGTAGAAAGGAAGATTGCTGAGATAGGAGC
TGTGTGTACCATAATCAATTCTGAGGATGAAAAGTCAAAAGG---------------AGG
AGGCAAAGCCAGTAATTCT---------------------GGAAGTGACGTCCACTCCAG
TGTTTCATTGACTACACAGGTGGTCAGAAAAGAGCGGGAAACGGAGAGGATACAAGAAAA
AGGTATTGCTGAGCAAACCAATTCAGCCAT------------GCAATCAGGAAAGTCACT
TCCAACATCTGGATATGTCCTATCAGGGCCTGTAGTATCTGAGACTAGTCAAACTGGACG
TTTCTTATGTTGTCTTTGCCAGAAGTGGGCAAATTACAAGAATCTTGGGGATCTCTATGG
ACCTTTCTACCCAGCAGAGTACGCTGCCAAGTTTCCGAAAAACCAACCCCAAGTTCGTCA
GATCTTGTCAAACTCTGGGACGGCTACTTCGGGACCAAATCTGTCTTCTGTTCCAACAGA
ACCAAACGCCGTCGATGATCAATTAACGCATCCTGCAGAT-------------ATCAAA-
--ACAACAGACAGCACTAGCACAGTAGACCAGTCTATGAATCCAGCACCCCCTGCTACTG
CTGGTAGCACTGCATTCCCGACAGCACCTGAGGACTTG---TCCTGCTCCAGTGCTCAGT
TGAGCAGCACTGTCGTA-------------------------------------------
--------------GTGGCACCAGCAGAAAATTGGGATCCCACGCCAGAA------TTGG
CACCTAGTACACCCAAACCGCCCGACCTGGAGAACGAGGTGGC-----------------
----TCAGAGATGGCAGCAGAAGGCAGAAGAACTGCAGCAGCGACCGCAGCATCGGAAAC
TGACTTCCCATCCGCGGTTTAAAAGGCGACACAAGTCCAGCGAGGACGTGCCCCGCACTG
TTCCAATCAACAGCAAAGCTTCGCTGCCGTTCCAGCCTCCACCTCC------------CA
GCGTTGACTCTCTTGGACCTTTGGCTCAACTGGCTCAGCTTCCGTTGGTGCCCTTAGACC
CCCAGGAACTGTGGGTGCACGAGAGCTGCATCGTCTGGACCAGCGGCATTTACCTAGTTA
ATGGGAGACTCTATGGCCTACAGGAAGCACTAGATGGTGCCAGAGAAATGAGCTGTTCTC
ATTGTGAAATGGCCGGTTCCACTCTGGGATGCTACAGTAAAGGCTGCACGCTGAGGTATC
ATTACATGTGTGCCATTGAAGCAGACTGCTGTTTAAATGAAGATAATTTCTCGTTGAGAT
GTCCAAAGCACAAGTTTTCTCTGAACAGTAGACCAGCCAAGTCTACAGCGGCGTACCTGG
AGCAGTCTGAACGAGGCTGA
>Gasteropelecus_sp._gill_3|016423|scaffold27013|m.27736
AT----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------G
CCAGCA------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------TACCCACACTCCCTCTCTCTTCAGCATCCG
CACAGCGTGGATGAGAGGTTTGATTGGTCTGCTAACAGTAACAGGCCTAAAGATGGTTCC
ACTCATCACAACTCTGCCCAGAACTCCAACCAAAAATGTAAAATTCATTCCCCTGCTGAT
GTTTTGCCCTATCAGCATCACATGTCGAGACAGAATTCTTACCCCGGTGCTCACTATGAT
CCTGCTTCTCACTATGATGTGAAAATGTGGGATTTCTATGCTGAACAAGATGGAG-----
-GCCAGCAGGTACACTCTGGAGTTCCTCATGAGTCTTCTGGCTCACACACGGTACCATCC
AGTAGTTCTAAGCCTCTAGAGGCAGATGTCTCAAGAGGGATAACAGAAGAA---GCCAAA
CCGTTCCACCCACCCACAGCTGCCAGTGCTGCTGGCTCAGGTGCTCACAGCAGCAGTAAT
ATGGTACCAGGGGT---TCGCCCAACGAAAACTGGAGGTTCAGCAGAAACTAACCCTTTA
ATGATGAGGAGGAGAGTCCGCTCCTTTATTTCTCCAATTCCAGCAAAGCGGCAGCATCAG
GACTTTCCGAGCCAGAGGAGTG---GATTGTCCTACAGCTCTCCGGTTCCCCATTCTGAA
ACTAGACAACTCGCAGATACAGATTCTCCCAGTGTGGATCTCC---GTCCAAAGCTTGCA
TCCCCA----------AACATGCCATATCAAACACCTGGCACCCACTCTCCACCACAAGG
AAAAACAAAGATTCTACCACCAAGAAAGGGGCGTGGCTTAAAACTAGAAGCAATAGTGCA
AAAAATTACCCCAAACA--AAAAGTCCAGCAACAATAATAGCCATGTAGATGCTGACT--
----------------------ACCCTGATGTGTCGCACTACAGCTCTGATATATCAGAT
CCAGAGATTGGTGCACCTTTCTCTAGTGCTCTTCACCGGGA----AGGAGGCAGTTTACC
TTACCTTGATGAAGCTCACACTTTGGATGATCTCTTGCCATACAGAGCAGAAGATG----
--------------------CATATTCCTGTGACTCTCAAGTTCTACAGCAGAGCGCAAC
AGGCTCCACCAGTGGCACCCTGAGAAATTTGCCAA------------------------C
GGATTTTGACTTTGGCTTAGGCACTACTGGATCTAGTACAGGGTCTGGAC---------C
AGGTGATGATAATAAGGA------------------TGACTTTACCCTTTTAGGACCCCT
GCCCCCACCACCTCCTTTACCTCGTCCTGTACAAGGATCTCCTCCTCCATCCTCTTCTGT
ATTGTCAGACATACAGCAGTTCACCAATACTTACCAACAGCTCGAGACGCGAAGAGGGGA
ACAGTCTGCTGCTACCCTACTGAGGCAGAAGCTTCAGGAGAGTGGAA------TGGGTTT
TGATGATTATGGTGGAGGGGATTTCTATGGGGCAACTCCACCCCA---TAGCCAAAGCCC
AGGACACCACCACCTCTCAAG------------------------------------AGC
CTCTA------CCAGGATGGCATCCTCAGACCCCAAAGCAC------CTGATCCTGTTGT
TCCTAAAGGTTATTTTCCATCAGGCAAAAAAAAGGGGCGACCAGTAGGAAGTGTTAACAA
ACAAAAACGTGC------CCAAGTCCAGAAC---------------------------AC
CACGGCCAGCAGCATGCCTGCAACCCCTCAGACGCCTCCTGCTGCTGGTACTGCTGCTGT
CACTCCGTCGACTATACCAAGCTCAGGCATTGCGGGAGAGCTTGTCGCAACTTCAGAACT
TCTCGAACAGAAACCCTGTCCCT------CTGTGAATTTGGCTGCCCAG---GTCCTGCC
GGTGAAGGCGGAAATGGAAAGTGAGGATAACCAGCCTGAAGTAGATCTGAAGCCTGTGAA
ACACAGGCAGAGGAAGGGCAAAGAGA---TAAGTGAAGGAGCCAGTCCCAGAGGAAGGCA
GTGGAGGGCAAGAAGAGGACTGGCCTC---------------------TAAACAAGAGCT
GGATCCTCAGGCTGGCAGTGGAGGAAATGCAGGCCTGAGTGGAGTTTTACAAGAT---GG
CAGAAAAAACACGTTCTCTCCATATATACACGTGGAAAGGAAGGTGGCGGAAATAGGAGC
TGTGTGCACGATAGTCAATTCTGAGGAAGAGAAATCGAA------------------AGG
AGGCAGAGCGGCTGGCTCT---------------------GCAGTGGATGTTCTCTCAAA
TGTTCCTCTGACATCTCAGACAGTTCGAAAAGAGAGGGAAACTGAGAGGGTGCAAGAAAA
AGGGATTGTTGAGCAAACAGACTCGGGT---------------CAGTCAGGAAAGTCACT
TCCAACATCTGGATATGTCCTGCCTGGCCCTGTTGTGTCTGAGACGGGCCACACTGGTCG
TTTCCTGTGCTGCCTGTGTCAGAAATGGGCAAATTACAAAAACCTTGGGGATCTCTATGG
TCCCTTTTACCCAGCTGATTATGCTGCCAAAGTCCCGAAGAACCAACCGCAAGCTCGACA
GATCTTGTCAAATTCTGGGGCAGCTAATGCTGTGCCAAATTCAGCTTCTGTCTCTGCAGA
GTTCGCCACCACCGA---------GCTTCATCCTCCAAAT-------------GTTCAA-
--TCAGCCGACAGCAATTGCTCAGCAAGTCAAACCACAACCCCCAAATCTCCTGCTACAA
TCCCTGGTGCTGCAGCTCCTGCAGTAGAAGATGACGTG---TCATGTCTTGGTGCTAAGG
TGAGTGGTGATGACTCC-------------------------------------------
--------------AAGACACCAGCACAGTGTTTGGATTTGACTCCAGAT------GTGG
CACCCGTTGCATTGAATCCCCCTGACCTGGAGAATGAGCTCAT-----------------
----CCAGAAACAGCAGCAGAAGGTAGAAGACCTGCAGCAATGGCCACAGCACAGAAAAT
TAACTTCTCACCCCCGTTTCAAAAGGAGACACAAGTCCAGTGAAGATTTGCCTCGGACTG
TTCCCATCAACAGTAAAGCTTCACTGCCGTTCCAACCCCCTCCGCC------------CA
GCTTAGACTCTTTAGGTCCTTTGGCTCAACTAGCTCAGCTCCCTCTGGTGCCCTTAGACC
CTGAGGAGCTGTGGGTGCATGAGAGTTGCATCGTCTGGACTAGTGGTGTTTACCTGGTCA
ACGGCAGACTGTACGGTCTTCAGGAGGCACTAGATGGTGACAGAGAAACAAGCTGTTCTC
ATTGTGAAATGGCCGGTTCCACTCTGGGTTGCTACAGCAAAGGTTGCACACTGAGGTATC
ATTACCTGTGTGCTGTGGAAGCAGACTGCCACCTGAACGAAGACAACTTCTCTCTGAGGT
GTCCAAAGCACAAGTCTCCTCTGAACGGTCGACCAGGGAAGCCTGCAGCTGTATATCTGG
AGCAGTCCGAGAGAGGCTGA
>Lepidogalaxias_salamandroides_Head_2|005517|C506356|m.42324
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----AAAGGCTATTTCCCATCAGGCAAGAAGAAGGGAAGGCCTGTTGGAAGTGTTAATAA
GCAAAAACGCACCCAGGCCCAGTCACAGG-------------------------------
-----TCCCAGGCGCTCTGCCTGTTTCAGAAACCCCTTCTCCTGTGA---CAGTTGTAAC
CCCC---CAGGTTGTTCTGAGCAACAGCCCCACGCCTGAGACTCCTACAGATGAGCCACC
AATTGAATGCAAAGCATCTCCCA------CGTTGACTCCGGTTGCTCCGCCCCCCCAGAC
GGTAAAAGTGGATGCTGAAAGTGAGGATACCCAACAGGAGGTTGAGGTGAAACCCCTCAG
ACCAAAGCCGAGA------AAGGAGG---AAAATGAGGGGGCTGGATTGGGAGCCAGGCA
GAGGAGGAGAAGGAGGGCAGGAGTGACGGT------------------CACAGACGGGTT
GGAGGCAAGTCCAGTGTCTGGGGGAAACGGCAGTATCAGTGGAATGTTCCCTGAT---AA
CAGGAAGTGTGCTTTTTCTCCCTACATCCACGTAGAGAGAAAAAT---AGAGGTGGGAGC
CGTGTGCACGATTGTGAATGCTGAGGAAGAAAAATCGAA---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------AGGAGA----AAAT--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------GGTGGA
>Melanotaenia_praecox_viscera_mixture_8|016300|scaffold2471|m.2106
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----ATCACCCCAAATATTAAAAAGCCAGCA--------GGCCATGCTGATGATGAGTCC
AATCATTACCCTGGCTTCTCGCACTCAGAAATACCAACATTTAA---TGAGTCACAGGAC
CAAGA----------------CTTGGCACATTTCCCCAGGATTTCAGGAGGAGATGATAG
TTACATGGATGAAAGTCACTCATTAAACAACATGATTCCCTACAGAGGAGTTGATGAAAC
TGGGCCTTTACCTCCGCCTTCCTACCCGTGCGACCCCCATCA------------------
-------------GACATCGCAAACCATCAAACA--------------------------
GGATTTTGACTTTGGGTTAGGATCCGCTGTTGC---GTCAGCATCTGG------------
---------TGACAAGGA------------------AGATTTTGCTTTGCTTGGTCCTTT
ACCTCCTCCCCCACCTCTTCCTCGCCCAGTCCAAGGTTCTCCGCCTCCGTCTTCATCCGC
CCTGTCAGACATTCAGCACTTCACAAATACTTACCAGCAACTTGAGACACGCAGGGGAGA
ACAGTCTGCTGCTAACCTTCTCAGACAGAAACTGCAAGAATCTGGCA------TGGGATT
TGAAGACTACCCTGGCAGCGACTACTACGGGACACCCCCACCCCA------------TCA
AGGACA---CATGCTGAACCG------------------------ACAACATCAGATGTC
TTCTGGACGGTCCAGTCTGTCGCCACAAGATTCAAAGCCAC------TAGAGAATATCGT
GCCTAAAGGCTATTTCCCATCTGGCAAGAAAAAAGGCAGGCCTGTTGGGAGTGTGAATAA
GCAAAAACGGGCTCAGAACCAAGTCCAAACACAGGCCCAGCCTCAAGTCCAGACACAAAA
CACAACCCTAAGTGCCCCTCCGGCCCCACATATCCCAACTCCGGCAG---CTGCCACAAC
CCCA---CCAGTAGTACAGACTACCAGCTGCACAC------------------CGCCTCT
GTCAGAAAATAAAAACACTCCCT------CGCCAGCTCCACTCATTTTA---ACCCAGCC
AGTCAAAGCCGATATTGAAAGTGAGGACACACAGCTAGAGGTGGAGTTGAAACCTGTGCG
ACGCAGACGCAGAAGTATGAAAGATG---AAGAAGAGCCACTAGAAGGAAGGGGCCGGCA
GAGGAGGAGGAGGAGAGGAGCAGTAGCGTCAGCACCAT------CAGCACCAGATGACC-
--ATGCGCTTTTAGGGGCAGAAGGGAGTCTCGGCTCAAATAGAGTTTTCATGGATCTGAA
CAGAAAGGGCCTATTTGTTCCTCATATACATGTGGAGAAAAAAGTACCAGAAATCGGGGC
AGTGTGTACAATTGTTAATGCTGAGGAGGATAAGATGAAAGGGGAGCGTAGTGCAGTCGG
AGGGAAAGCTGGCgggagt---------------------GGGATTGATTCCTTCCTGAC
TTCAACTATTTCCTCCCAGTTATCTTGGAGAGACAGAGAAGC------------AGAGAA
AAGGGAGACAGACGAGGTGGAAAGTACACT------------TCAGTCAGGCAAAGCACT
CCCCTCATCTGGTTATGTTGTTTCAGGCTCCGTGATTACAGAGACTAATCACTCAGGCCG
ACTGCTATGTTGCCTGTGTCAGAAATGGGCAAATTACAAGCACCTCGGAGATCTGTATGG
GCCGTACTATCCAGCTGAATATGCCGCAAAGCTCCCCAAGAACCAGCCCCAGATCAGACA
ATGTCAGGCCCCCACAGGCACAAACAAAATCGGACCAAACTCGGACATGAGCTCAAATAC
TTTGAATGCCATCCAAGACACACAAACACACCATGCTCGGT----------TCACCAAGC
CTTCAACAGAGCACATCTGTGCCGCGGATGTAGATTCAAACCCAGAATCCTTCACCACCA
CAGTCAGAACTGCCTCCCCAGCTACAACAGAGGAGATG---ATGTATGTGGCTGCCAAGC
CAACTAACACAGCTTCA------------------------------------TCCTCTT
CATCCTCCTCCACTGTTAAGACACCTCTGACCCGAGACATGAATCCAGATATCCCACCTA
TCCCTGAGCTTAAGAGAGAGCCAGACCTCGAAAGTGACCAGCAGCATGC---------GG
CGCAGAAACATCCGCTGCAGCCGACAGACGAAACTCAGCAGCGACCTCAGCACAGAAAGC
TGACATCGCATCCTCGCTTTAAAAGGAGACACAAGTCCAGTGAAGATTCCCCCAGAATGG
TACCATCCAACAGTAAGGCATCCCTCCCCTTTCAGCCCCCTCCACC------------AA
CCTTGGACTCCCTGGGACCACTGGCCCAACTGGCAcaGCTGCCTCAGATGCCCATAGACC
CAGAGGAGCTGTGGGTGCATGAAGGATGTATTGTATGGACCAGTGGAGTTTACATCGTCA
ATGGGAGACTGTACGGCCTGCAGGAGGCACTAGATGGCGCCAGAGAGACAAGCTGTTCAT
ACTGTGAGATGGTGGGTTCAACCCTGGGCTGCTATAGTAAAGGCTGCACACTCCGCTATC
ACTACCTATGTGCTATTGAAGCAGATTGTTCTCTAAACGAAGATAACTTCTCACTGAGAT
GTCCGAAGCACAAGtttacccagagcgtccggccagcCAAGTCA------GTGTACCCAG
AGCAGTCAGAAAGAGGTTGA
>Pantodon_buncholzi_mixed|022681|scaffold9590|m.11503
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------GAACAAAAAC----------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------ATGACAATGCAGT
ACCAAAAGGATATTTTCCATCTGGAAAGAAAAAAGGACGGCCTGTTGGTAGCGTAAATAA
GCAGAAGCGATCTCAGGCACAGTCCCAAA------------------------------A
TGTATCCGTTCATCCTCTCCCTGTGGCTTCTAgctgtacacctgtac---ctacAACACC
ACCT---------ACAGAAGATAACACAGATGTAATTGCAATTTCTGCAGAATCTTCACA
GATAAACACAGTACCTTCTATAC------CTTCTTCCCCAACCTCTATT---TCTCAGAG
TGGAAAGGCTGATGCTGAGATTGAAGAAacggagcatgaaacagagttgaaaTCTTGTCA
ACAGAGAAGGAGAAAGAGGGAAGATG---ACTCAGAAGAAGAGGAGGTAGACATAACACG
ACAAAAAACAAAAGCTGTAATGGAGGCTGCT---------------GTTAAAGATGACAT
GAG---------------------------------GAGTGGATTTAACTTTTGT---CA
TAATAAGTCTGTTTTTTCCCCCTACATTCATGTAGAGCGAAAGGTGGAGGAGGTAGGCAA
TGTGTGCACCATTGTGAATGGAGAAGATGAAAGAAAGAGGGTTGAA---AACAATGTAGA
AGACA-------------------------------------------------------
--------------------------GGGGAAGCAGAGAAAATTATGTGGTAAAAGAA--
-------TCAGAGAAGCTGGACTCCAGCCTGATTCAGTCTAGTCCAACAGGCAAAACACT
TCCTTCATCTGGGTATGTTCTTCCAGGACCCGTGATTGCAGAGTCAAATGAATATGGCCG
CCTGCTTTGCTGCTTATGTAAAAAATGGGCTAACTATAAGGACCTTGGGGATCTCTATGG
GCCCTACTACCCTCCAGATTATTCTGCAAAAATTGCAAAAAATCCTCTAGTGAACAAGCA
AGGCCAAGGGACTGCCAGATTAAACCCC--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Sargocentron_rubrum_gill_6|016787|scaffold25398|m.32671
CC----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------TCCTCCTCCTCCTGCTCCTG
C-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------TCCTGCAACTTCACATGGCCCTGCTCCTCCACAGATTTCTCTAGCA
GGTGGTCCAAACACTGGGGAACCTGATGTCTCCAGAGCAGCTGTAGAGGAA---GCTAAA
CATCCCCGTCCAGGTCCTGCATCCAACTCCACTAAGCCCCCTGCTGACATTAACTCCACT
CTTCCACAGGGGCC---GCGTCAGACTAAAGCTGGGGGTTCGGGAGACACAAATCCACTG
ATATTGAGGAGGAGAGTTCGTTCTTTTATCTCCCCTATCCCTGCCAAGAGGCAGCTTCAG
GATGGTTCTCAGCAGAGGGGTGCCACAAATTCACATCACTCCCCTGGGGCCCAATCTGAG
TCTAGCCATCACAACGAAGATGACTCATCTAGTTCTGATATCCCATGTCCCAGGCTTTCT
TCCCCCTTACCTGGAGAGAATACTTATTCACAGTCTCTG-------TCTCCTTCAAGCGG
TAAAACCAAAGTTTTGCCTCCCAGGAAAGGTCGAGGTTTGAAACTGGAGGCGATAGTTCA
GAAAATCACCCCAAATGTTAAGAAGCCAACA--------GGCCATACTGATGTTGACTCA
AACCATTACCCGAGCTTCTCTCACTCAGACATGTCACAGTTTAG---TGATTCGCAGGAC
CAAGA----------------CTTAACACATTTCCCTAGAGTTGCAGGGGGGGATGATGG
ATACATGGATGAAACTCACTCCTTAAATGATATGATTCCCTTCAGAGGTGTTGACGAGAC
CGGGCCTTTACCTCCATCTGCCTTTCCCTGTGATCCTCATCA------------------
-------------GACATCCCAAATCCTCAAACAG-----------------------CA
AGACTTTGACTTTGGATTAGGGGCTGCTGTGGC---CTCAGCATCTGG------------
---------CGACAAAGA------------------GGACTTTACTTTGCTAGGACCTCT
ACCCCCTCCCCCACCTCTCCCTCGCCCAGTCCAGGGTTCCCCGCCTCCATCTTCATCTGT
CCTGTCTGATATCCAGCATTTTACCAACACTTATCAGCAGCTTGAGACACGAAGAGGAGA
GCAATCTGCTGCCACCCTTCTCAGACAGAAACTTCAAGAAACTGGCA------TGGGATT
TGATGATTATCCTGGCAGCGACTACTATGGAACCACCCCACCCCACCATAGCCAAGCCCA
GGGACA---CATGTTGAACAG---------------------ACAACAGCATCAAATGGC
CTCTGGAAGGTCCACTTTGTCACCACAAGATTCAAAAACGT------CAGACAGTATCGT
GCCTAAAGGCTATTTCCCATCTGGCAAGAAAAAGGGCAGGCCTGTTGGGAGCGTTAATAA
ACAAAAACGTGCCCAGAACCAAGCCCAAACCCAGGCACAGACCCAAGTCCAGGCTCAGAA
CACAACTCCGAGTACTCCTCCGGTCCAACCTGCTGCATCACCAGCTG---CTGCCACAAC
CCCACAGCCAGTGCAGCAAAATACCAGCAGCACACC---AACCTCCACAGCTCCTCCCCT
GCCAGAGCATAAACCCACTCCCC------CTCTGGCCCCGCCCGTTTTA---ACCCAGGT
GGTGAAAGTGGATGCTGAGAGTGAGGACACACAGCCAGACACTGAGGTTAAGCCTCTGCG
ACGGAGACGCAGAGGTGTAAAAGATG---AGAACGAGCCAGTGGGAGTAAGAGGAAGACA
GAGGAGGAGGAGGAGAGGAGGAGCAGCGGCAGCGTCACCATCAGTGGCCAAAGATGACCC
AGATACACCTTCAGGGGCAGGAGG------------AAGTGGGGGATTCCTAGACCCAAA
TAGAAAGGGTCTGTTTGTTCCACATATACATGTGGAGAAAAAAATACCAGAGATTGGGGC
AGTGTGCACCATAGTGAATGCTGAGGAGGAGAAGATGAAAGGAGAGCGTAGTACAGTCGG
AGGGAAAGCAGGCGGCAGT---------------------GGAATCGATTCTCTCCTGAC
CTCAGCTCTTTCCTCTCAGTTATCTAGAAGAGACAGAGAAGC------------AGAGAA
AAGGGAGTCAGACGAGGTGGAAACCACCCT------------TCAGTCAGGAAAAGCGCT
TCCCTCATCTGGCTATGTTGTTTCAGGCCCTGTGATTACAGAGACCAATCACTCCGGCCG
CCTGCTCTGCTGCCTGTGTCAGAAGTGGGCAAATTATAAACATCTCGGAGACCTCTACGG
CCCTTACTATCCAGCTGAATACGCTGCAAAGCTTCCCAAGAACCAGCCCCAGGTCAGACA
GTGTCAAGTAACCACCGGAACAAATAAAACGGGACCAAATTTAGACACCAACTCAAATGT
ATTGAGCACTATCCAAGAGACACCAACACAAGATGCTCAGT----------TTACCAAGC
TGTCAACTGAGAGCGACTACGCCATCAGCCTAGATAAAAACCCGGCATCTCCCACCACCA
CAGTTGGAACTGCCTCTCCAGCTGGCGGAGGAGAAATGATTATGTATATGGCCGACAAGC
TTGGCAACACCACCTCCTCCTCCACCACCACCTCCTCTACCACCACCACCACCTCCTCCT
CTACCACCACCAGTATAACAACATCTCTAACCTGGGATATGAATCTGGATATTAGACCTA
TCCCTGAGCTGAAGAGAGAACCAGACATCGAGAACGACCAGCAACAGACGcaaaagcagc
tGCAGCCGCAGCCGCCGCCACCGACAGATGAAACTCAGCAGCGGCCTCAGCACAGAAAGC
TGACCTCACATCCTCGCTTCAAAAGGAGGCACAAATCTAGCGAGGATTCCCCCAGAATGG
TGCCATCCAACAGTAAGGCCTCCCTGCCCTTCCAGCCCCCTCCCCC------------AG
CCCTGGACTCCCTGGGGCCCTTGGCACAACTGGCCCAGCTGCCTCAGATGCCCATGGACC
CAGAGGAGCTGTGGGTCCACGAAGGCTGTATAGTGTGGACCAGTGGAGTGTACCTTGTCA
ATGGGAGACTGTACGGCCTGCAGGAGGCACTAGATGGCACCAGAGACACATGC-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Scleropages_formosus_red_gill|006663|C1329318|m.79739
GC----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------TGAGGAGAC
AGGGCCTCAACCACCTACTGCGTATCCATGTGGTCCCCATCA--------AGATCAAAAC
ATGCTTAAAT-GTGATGTAATGGGAAACATGACAAGGAATGTTATCAAGGATTTGGAGTC
AGAATTAAACTTTGACTTAGGGGTGTCAGGAGT---TCCAAAAACAGAGAGAGAGTGCGC
TGGAGAGAGGATCAAGGATGATTTAAGGATGCCTCCTGATTTTCCTCTTCTAGGACCTTT
ACCCCCACCCCCACCATTACCTTGTCCTGTACAGGCCTCCCCACCTCCCTCATCCTCTGG
CTTGGCAGATATTCAGCATTTTGAAACTACTTATTTGCAGCTAGAGACACGAAAAGGTAA
GCACACAGCAGCTACGCTTTTGAAACAAAAACTTCAAGAGAGCGATATTGAATTAGGTAT
GGATAATTATACTAGAAGGGATTACATTGGTATCAAGTCACCCCACCATAACCAGAGCTT
AGGTCACTGCCTGCTAAACAGTCCCTCACACCCCCATTTGCCACATCATCATCAACATTC
TTCTACTGGCACCACAATGACAGACCAACAGTTTATAGAACCCAAGCTTGAGAATGCAGT
GCCAAAAGGCTATTTTCCATCTGGGAAGAAAAAGGGACGCCCAGTTGGAAGTGTGAATAA
ACAAAAGAGGACTCAAACCCAGTCTCAGA------------------------------A
TTTGTCTGTTAATGCTTTACCCGTATCCCACACATCTGTGCCAGCTC---------CTAC
ACCTCCAGTAGAGAATCAAAGCACTAACAACACAAGTTTAGTTCCTGCTGACTCATTGCA
ATTTCCAAAAATACCTCCTACCT------CAGTTTCTCCTCCTATTATA---TCACAAAC
AAAAAAAGAAGACACTGAAACTGAAGAGACCAAACCTGATCCAGAAGCAAAACCTCGAAG
ACAGAGACGAAGAAAGAAGGAAGATGGTCATATAGAAGATGCCGGGCTACAACAAAGACG
GAGAAAAAGAGGCATAGTAGGGGTTTTGAG------------------TAAGGAAGAAAT
TGATGCTGAGATAGGAAGTGGAAAATTCTGCAG---CCGTGGGGTTTTCTCTACA---TA
CAGAAAATCTGTTTTTACCCCTTATATTCATGTAGAAAGAAAGCTGGAGGAGATGGGGAA
TGTGTGTACCATTGTGAATGGAGAAGATGATAAGAAGAAGATTGAA---ATTGCTGTGGA
ATACAGCAGAGGTAGATGTGCAGGGAAGGATGTGGGTCAAGGAGCTGACACTCCACTGAG
CTCAGCCCTTTCTTCTCAACTTGTCAGGAGAGATGGAGAAAAGGATAAAGTGAAAGAGAA
GAGAAATGCAGAAAACTTAGCATCTGTCCTTGTTCAGTCCAGCCCAACGGGTAAGGCCCT
TCCTTCCTCTGGATTTGTGCTCTCTGGACCTGTGATGACTGAGTCAAGCACAAGTGACCA
TCTCCTCTGCTGCTTATGCAAAAAGTGGGCTAACTACAAAGATCTAGGAGATCTCTATGG
ACCTTACTATCCTCCTGATTATTTAACAAAGCTTCCCAAGAACTCTCCAGTGACCAGGCA
GAACCAGATAACTGTAAAGCTAAGCACTATAGGGGTAGATTTGGGAACAACCACAGCTGA
ATT-------------GTCAAAGCAACAGGTGTTGCTAACAGAGATCCAGACCCCTGTAT
CTGTAATAAATGGTAATTCTTCAGCAGAAAAAGATAGAGACCCTGCATCTGCTGCTACTC
CAACTGAAAAAGTGTCTCCAGTGGAAGGACTGAGTGTG---TCATGTAATACAGACAAAA
GTGGGAACA---------------------------------------------------
------------AAGAAATAACAAAGGACAGTTGGGACCTGACATCTGAACTGACCATCA
CAGATGTGAGGTTGAATCTGACAGGAGATGCATTTAACCCTGAACA------------AT
CACTGCAGAGTCCACAGCAACAGACGGAGGATGCTCAGAAAAGACCACAACTCAGGAAGC
TAACGTCACACCCACGTTTCAAAAGACGACATAAATCCAATGAGGATTTGCCCAAAACTG
GATCCATTAACAACAAAGCCTTATTGCCCTTTCAGCCCCCTCCACCTCTTCAGCTTGTTA
ACCAGGAACCCACTGATCCTTCAGCAGTCTTATCCCTGCTCCCTCAGGTGCCCATAGATG
CTGAAGAGTTGTGGGTACATGAGGGGTGTATAGTCTGGACCAGTGGGGTGTATTTGGTCA
ATGGAAGGCTGTATGGACTGCAGGAAGCCCTA----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Synodus_sp._gill_5|016279|scaffold21589|m.28201
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------GTCAAACCTCTGCG
ACGAAGGCGGAGGCCCGTTAAAGATG---AAGGTGAACCATCCGAAGTGAGGGGAAGACA
AAGGAGGAGGAGGAGGGGAGCAGTACCTGCAGCTGTGT------TGGCCAAAAATGACCT
TGACACACCTTCAGGAGCTGGAGGAGGTTT------GAGTGGAGGCTTTGTAGACCTTAA
CAGAAAAGGCTTATTTGTTCCACACATACATGTAGAAAGGAAGATACCAGAGATTGGTGC
AGTGTGCACCATTGTGAATGCCGAGGAGGAGAAGTTGAAAGGAGAGCGTAGTGCACTTGG
GGGGAAATCAGGCAGCAGT---------------------GGAATGGATTCTCTTTTGAC
CTCAGCTCTTACCTCCCAGCTATGTAGGAGAGATAGAGAGAC------------AGAAAA
AAGGGATTCGGATGAGGTAGAAGCCACCCT------------TCAGTCTGGAAAAGCACT
GCCTTCTTCTGGGTATGTTGTTTCAGGCCCTGTCATTACCGAAACCAATCACTCTGGGCG
TCTGCTCTGCTGCCTCTGTCAGAAATGGGCAAATTATAAACATCTTGGCGACCTCTATGG
CCCTTATTACCCAGCTGAATACGCTGCAAAACTTCCTAAGAATCAACCACAGATCCGTCA
ATGTCAAGCAACCTCTGGAATAAATAAAACGGGACCGTATATTGATACAAATTCAAACAT
GTTGAACACCATTCAAGA------AACTAATGAGACTCATA----------TCACTAAAT
CATCCATGGATAGTGACTATCCTGTCAGTGTAGTTACAAATCCAACTTCCCCTGCTACCA
CAGTTGAAACTGCTTCTCCAGTTGAGGGCGAGGAAATGATGACCTATTTGGCAGGCAAGC
TTGTTAACACCACCTCC------------------------------------GATCCAG
ccgtgacgacaagtgaaaccccgtctATAACATGGGATCATAATTTAGATTCTAGACCTA
TCCCCGAACTGAAGAGAGAACCAGAAATGCCTGATGACCAACAACA------------GG
AACAGAAGCCTCAACCACAGCAAACAGATGAAGTTCAGCAGCGGCCCCAACACAGAAAGC
TGACATCACACCCACGTTTCAAAAGAAGGCATAAATCCAGTGAAGATTCCCCCAGGATGG
TACCATCCAACAGCAAGGCCTCCCTGCCCTTCCAGCCCCCTCCGCC------------AG
CTCTGGACTCCCTTGGGCCTTTGGCACAACtggcCCAGCTGCCACAGATGCCCATGGATC
CGGAGGAGTTGTGGGTTCATGAGGGCTGTATAGTCTGGACCAGTGGAGTGTACCTGGTCA
ATGGGAGACTTTACGGTCTGCAGGAAGCACTAGATGGCGCCAGAGAAACAAGCTGCTCCT
ATTGTGAAATGGTGGGTTCTACCTTGGGCTGCTACAGTAAAGGCTGCACACTCCGTTACC
ATTACTTGTGTGCAATCGAAGCCGATTGCTCTATGAACGAAGATAACTTCTCTCTGCGGT
GTCCGAAGCACAAGTTTCCCCAGAGCAGTCGGCCAGCCAAGCCT------CTTTACCTGG
AGCAATCAGAAAGAGGCTGA
