>Corydoras_julii_viscera_mixture_8|011359|scaffold19965|m.15053
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------TTTTCTGACTCATTTGAGGAGCAGC
TTACTGAAATGATCAAAGCAGTTAAGGAGTTTAACAGCGTAAAGCGTGATGTTGTAAAGG
TTAACAGCTCTCTGAATCGTAAGAAGACCAGACTTCTGGATGCCAAGAATGAATTAATCA
GAAGTGAGACTGAGCTGGAAAAACTCCAGAAAGAGTACAATACGATGGATCAGAGGCTGA
AGGCTTTGACACAGGGCACTGCGTTCCTCACTAACCTAAAAGAACTGAACAGGAGCTACC
TGCAGCACCGCATTAATCATCCTAATGATCCCGAAACATATGGACCGTCCTGCATTCCAG
CAATGCTGCTCGAGGCCAGGAACATCAATGTACCTGAAAATCAATTGCATGTCATCGGTG
ACCAGCTTCAAGAAATTTTACAAACCAGAGCCCACAAATAG
>Distichodus_sexfasciatus_gill_4|016765|scaffold25123|m.28716
ATGAG------------TCGGATGAAGAAAATGCTACACAATCTTCAAACGGAACTCAAG
AAGAGGCAGGAGAAGAGTCAGAAACGTCCCGAGGAGCTTTCGCAGTCTTCAGAATGCCTG
GATGTTTCCTCAATAGAGAAGGCCAGTTTCTTCCAAGGAGAACATTACTCTTCACATGGC
AACCCTCTTCACAGCACTGCTCTGGAAGACGAAATTACTCCCGTTCCTGATGTTAGTAAA
AGC------------ACTGCTGGAGGGAAAAAGACAAATGGCAAAAAGAGAAATGTGAAA
GCTCAGGATCAGACAGAGACTGCAAAGACACCTGCACGCGGTGAGAAAGGTTCGGCTAAA
AAGAGACAGAAAGGTCATGTCGAAGTGCAGCGCAAAACCTCCAAATCTAAAGAAAATCAG
AGTCCAGCACAAGCGACGAAACAGAAACCCCCAAAACGGCATCTACAGACTGTCACAGAG
GTCAGAGAAG-AAGGCAGGAGAAAGAGTCGTGTCCTTCATCAGGATTCAGCAGATGATAG
CCAGCAGCAGTCAGCTTTGTCCTCTGAAGAGCTTACAGACGAGGATCAGAGTTTTCACCC
A-AGCAATGAAAAACGCAAATCTTCCAGTTTGAGACGGCAGAGGAAATCAAGTGACCAAC
AGAGAGGTCAGAAACAGAAGAGGAAATCTTCATC------TGGCTCTTCAGA--------
----CAATGGACACCTTTCTAAGAAGAGGAAACGTGGA------CCTTTACGGAGTAGGA
CTAACTTGGAGGTTGTTCTAGAAGCATTCCAGGAATTTGTCTTGGAGTACAAGGAGACGG
TGAACTCGGAGGCTGTGAAACGTGCTATAGATGCACTTTCTCGTTTATTTGAGGAGGAAC
TCACTGAGATTATCACAGCCActaaggagttcagcagTGCCAAGCGGAAAACTGCAAAGA
TAAATAACACTCTGAACCAGAAGATAAGGAGGCTGTTGGAAGCCAAGAATGAACTCATCA
AGAGCGAGGCCAAGTTGAGGAAGCTTCAGAAGGAACACGACGAGTTGGAGGCCAGACTGA
AAGCTGTTCAACAAGTTTCGAGTTTCCTCACAAACCTGAAGCAGCTGAACGCGGCGTACC
TGCAGCACCGCCACGCGCACCCTGATCAACCG----------------------------
------------------------------------------------------------
-----------------------------------------
>Lepidogalaxias_salamandroides_Head_2|003935|C490721|m.39635
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------AAGAAAAACGCCACGG
TGAACGTGAAAATAAACCGAAAGAGAGCCAGGCTGGTGGAGGTCAAGAACGAACTCATCA
AGGCCGAAGTGGAAATGAGAGCGCTGCAGAAGGAGCACGCCCGGCTGGACCAGAGACTGA
GCGACCTGACGAAGGGAACCAGCTTCCTCAGGGACCTGGGGAACCTCCGTCAGAGCTACC
AGGAGCACCAGAGGAGCCACCTCGAGGAGGTCCAAGAGTTCGGCCCCTCCAGTCTGCCGG
CGCTGCTGATGGAGGCCAGGGGTGCTTCGGGAGCGGAGGACCAGCTCAAGACCATCAACG
ACAAGCTGCAGCAGGCTCTGGACCGGGACCGCTCCAAGTGA
>Pantodon_buncholzi_mixed|012274|scaffold15131|m.19884
A---GCTCCAAGAAAAGCAAAATGGGGAAGGTGCTGGCGAAAGTTCAGCGTGAGCTGCAG
GAACCACAGCATGG--CCCAAAGAAATCTATGGCAGCTAACAGAG----CGTCTCCCCCA
GATGTTTCCTCCATTGAGAAAGCCAGCTTTTTAGAAGAGGAAGAGATTCTGAGCTACGGA
AACCCTCTTCACAGCACTGCCCTTGAGGAGGATTTCAGCCCCTT----------------
-----GTCCCAAATATCCACCAAGAAGGATGCGGCAAAACCCAGACGGAAAACCCCAGC-
------------------------------------------------------------
--------------------TAAAGTTGGTACCAAGACATCTAGA---AAGCCAAATCAG
---CCGGCTCGGGGGAAAAGTCTCACGCAGCCAAGCC---------------TGGGGAAG
GTGAAAAAGG-GAGGAAAACCAGTCAGCAGGCGTCTTCAGCGGCTTTCTGAAGAGACTGA
TGAAACGCAGA---CTGAAGCCCCTGTAGACCACTGTGATGAGGCTGCAGTGAGGAAGCC
ACAGAAGGGCAAGA-GAAGGTCGTCCCGTGCG------------CTTTCAGGTGACCGGA
GCTCAGCTGGAGGCAAGAAAAGGAAGTCTCC---------TAAAGCCACAGC--------
----CAGTGCTGGTTCTGACGGGAAGNNNNNNNNNNNNNN----NNNNNNNNNNNNNNCA
CTGACCTGGACGTCGTGA------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Sargocentron_rubrum_gill_6|001869|C666353|m.44377
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------GGCAGA---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------ACCAGGAAGTCATCATCAGCCAGTGGATCTTCAGAGCCAGAAG
AGACCAGTAGGGATCAGCAGAGGGAGAAGAGACATGGC---------CGACAGGGAGCAA
CAGAGTTAGAGGTGGTGCTGGACGCCTTCCTTGATTTCTGTGACCAGTACAGGGAGTCAG
TGGAGTCTAAAGCAGTAAGACATGCCATTGATTCTCTTTCCTCCTCTGTCAAGGAGCAAC
TAACTGAAAAAATTACAGCATCCAAGGAGCTCAGGGTCCTTACAAGAGACAAGGCCAAGG
TGGACTCGTTGATCCGTAAGAAGAGACAGAGACTGCTGGATGCCAAATATGAGCTGATGA
GAGCTGAACAGCAGGTGCAGTCACTGCAGAAAGAGGAAGCGAAGCTGGAGCAAAGATTGG
CTGATCTCAGACGAAGCCAAACCTTCCTCCGTGACATCAGAGATCTTAACAGACAATACC
TGAAACACCGACACACACACCCCAAA----------------------------------
------------------------------------------------------------
-----------------------------------------
>Scleropages_formosus_red_gill|005992|C1321830|m.78282
ATGAGCTCAAAAAAGTCTCGAGTGGTGAAGATGCTGAAGAAACTCCAGAGTGACCTTTTG
GCGGAAGACGGGGG---------------CGTGGAGAAAACGCAGACGTTGTCTTCATTA
AACGTCTCCTCTATTGAGAAGGCCAGCTTTTTCGAGGACGACGATGTTAGCATTCACGGC
AATCCACTTCATAGCACTGCGCTTGAGGATGTGCTCAGTCCTGCTCTGGGACAGAGAGAG
GGTCTGCCACAGCCATCTGTCAGCAAAGAGGAGACCAGAGGCAGAAGGAAGAGTGCTGG-
----------GAGATGCCATGCCAAAGGCAGCCACACGCTGGAAAGGCAAACAGGCACAA
GAGTGAAATCAAGGACTTTAGGAAGGGTTTCAGAGGGTGTGGAAACAGTGGAAACATCCG
GTACACAGAGTGGGTCTGCGGTGACTACATCCTCCAAGGTGCTTTCTGAAGATCATAGTG
TCCAACCCAGTGACTTGAGAGAGAGCACCGAG-----------------AAGGATGACCG
AAAAAGGCTGACATCTGTGTCCTCTGAAGAGCTCAGTGATGACGACACCAGCTGGCACAC
AGAACAGGGCAAGAAGAAGGCATTACCACGTGGGTCCGTGG----------TTAACAAGA
CGAAAGGCATGCACAAGAACAGGAACTTCCGGTG------TAGGACTTCGG---------
------------GTCCTCCCAAAAAAAAGATGCGCAAAGAAATGGATGTAAAAAATCCTA
TTGACTTGGACATAGCGCTGGAGTCATTTAAGGCATTTGTATCGGAGTATATAGAAACCG
TTGATTCTCAGTCAGTCAAACAGGCAATAAATGCCTTCTCAAACACATTTGAGGACAGAC
TAATGGAACTGATATCTGAGACAAAGGAGCTGAGCACCTTGAAAAAGCAAAATACCAAGA
TTGATGCTGCCATCAACCGAAAGAGAGCAAGGCTGGTAGAAGTGAAAAATGAACTGATAA
AGAGCGAGGTGCAGCTGAAGAAGATGGAGAAAGAACACGCTCAGCTACGGGAGAGACTGA
CTGACATTCAGAGCAGCACCTCTTTCCTTGCAGACCTAAGGGACCTTAACAAGGAGTACC
TGGCGTACCGGGAACGGCACCCGGGCGAGGTGGAAATGTATGGACCATCCAGCCTCCCAG
CCCTGCTGCTGGAGGCTCGCCGTGTGATGGGGGCAGAACAACAGCTGAAGATCATCAATG
AGAAGCTGCAGCAGGCTTTGGATCGTGCTGCGTACAGTTGA
>Synodus_sp._gill_5|024183|scaffold6838|m.7496
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------GTTGATGAGCTCAAGGTTCTCCGAAGGAACAACAGCAAGG
TTGCTGCTCAGATCCAGAAGACTCGACAGGACCTTCTGGGGGCAAAATACGAGCTGCTGA
GCAAAGAGC---------------------ANNNNNNNNCCAGACTTGAGCAGCGTTTGG
CTGATCTCAAACAAGGTTCTGCCCTCCTGAGTGGAATCACAGAGCTGAACAGGAAGTATA
GTAAACATTGTAAGAGTCACCCCAGCAAGGAACAGGAGTATGGTGTTTCTAGTCTTCCTG
CTCTGTTGTTGGAGACCAGATGCATTCTGGGAGCTGAGAAGCAACTACAAA---------
---------------------------------AGGAATGA
