>Amblygaster_clupeoides|038465|TR65057|c2_g1_i1|m.91770
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------ATGTACCTACAGCAGGCCGGACCAAAAAACTATC
CCTTTAACAACAAGCCTGCAGTCAGAGCAGTCTATGGGAAGCCTGTCCTTCCCCCCAGT-
--TCCACTCCTCCCTCTCCTCTCCCCTTCCACCCAGCCTCGGG---TCACTTCCCCGGTC
TC------TTGGGCGGTCCTGGCGAGGACTTGCCTGAGGGCTTCGGTGTCTTGGGCGAAC
CGGTCGAGTTCCCTCCCCTGGACCTCCCGCCGTGCCCCCCGCCCAGCGTGGACCACATCC
CTCGCCCGCTGAGCCCCACCAAGCTGACGCCCATGGTGCACTCGCCGCTGCGCTACCAGA
GCGACGTTGAGCTGGAGGCGCTGCGGAAGAAGCTGGCCAACGCGCCGCGGCCGCTGAAGA
AGCGCAGCTCCATCACCGAGCCCGAGGGACCCAGCGGGCCCAACATCCAGAAGCTTCTCT
ACCAGCGCTTCAACACGCTCGCTGGCGGCATGGAAGCCGGAGGTGTCGGGGTC------G
GAGTCGGACCCACCCCGCCCGGAGTCACGGCGTTCTACCAGCCTGGGGCCGTTGGAGCAG
CAGTGATTGGCCAGGGCGATGCAGACAACGGGAACCCTCCGTTGTCTGAAGTGTCCACTG
GCGGCGGAATGGCTGTTGCAGTCGCTGAGGGGATGTCGGGCGAGACGATAACCGCGACGC
CAGCGGCGCCAACGTTGCCAAAAGGAGATGCGAACGACAACCAGCCTGCGGTGGGGACAG
TGCCGCCACCTACTGGTGAA---------GTCCAGGTACAGCGGGTGCCGGCGCCGTCTG
AGGAGGACAGCACTAACAACAACACCCAGGTGCCCACCACCACCACCCTGCCCAGTCCTG
TGGTGGAGGCCACCT---CACCAGAGGAGGCTGCCACCTCCCCCTCCGCAACCACGGAGA
AGCGCAGTAACCTGAAGAAGCCCAACTCTGAGCGGGCGGGCCTGGGCCAGCGGGTCAAGT
TCCATCCCCTGGCCCTGCTGCTGGACGCCTCGCTGGAGGGAGAGTTTGACCTGGTCCAGA
GAATAATTTATGAGGTGGAGAACCCCAGCAAGCCTAACGACGAGGGAATCACGCCGTTAC
ACAACTCCGTTTGTGCTGGACACCACCATATAGTCAAGTTCCTGCTGGACTTTGGGGTTA
ATGTCAATGCAGCGGACAGCGACGGCTGGACGCCGCTGCACTGTGCTGCTTCGTGTAACA
GTGTCCACCTGTGCAAGCTGCTGGTGGAGTCGGGGGCGGCCATCTTTGCCACCACCATCA
GCGACGTGGAGACGGCAGCAGACAAGTGTGAGGAGATGGAGGAAGGCTACATCCAGTGTT
CCCAGTTCCTCTATGGCGTGCAGGAGAAACTTGGGGTGATGAACAAGGGCACGGTTTACG
GGCTCTGGGAGTACGAGGCGCAGAGCAGCGACGAGCTCTCCTTCCACGAGGGTGACGCCA
TCACCATCCTGCGGCGCAAGGACGACAACGAGACGGACTGGTGGTGGGCGCGCCTCAACG
ACAAAGAGGGCTACGTGCCCCGCAACCTGCTTGGGCTGTACCCCAGAATAAAGCCAAGGC
AGCGGTCCCTGGCTTAG
>Corydoras_julii_viscera_mixture_8|008299|scaffold14737|m.10320
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------ATG
GAGGTGACACTGATGGACAAACGCATAAGTGAGCTTCGGGAACGACTGTATAAGAAAAAA
GCTGAGGCACGTCAAAAAGAAAACCTGCCTCTGAATCGTGCAAATGGACCTCCTTCACCC
CAACCAGCTGCTGGCACTGCAGGACGCGTGGCAGCTGTAGGGCCCTACATCCAGGTCCCT
GTGCCATCCCGCTCTGAGAGTGGCTACATGGTCCCACCTGATCCTCTTAAACCTCAAACA
CTGGCCATGAACACTCCCGCTACTCATGGACGATCAAAGTCAGCTAATGATGCAGGATGG
TCAACGCTCAGTAAGGGCAACATATCTCTGAAGCCCCCAGACTGGAAGGAAACTGTTGGT
GAAACGCCAAGCAAA---------TCGGTTTCACCTGCAAGCAGCCCAGCAGAGAAGAAT
CAGGATTTAAGTAAGCTGGGCACGGCCCCACCTCCTCCATCTAAACCTCAACCTCCACCC
TATGGCACCCACACCAGCTCCCACCCACTCTCCTCTGCCAATTCGGGTTCCACCAGCTCA
CTGGACCGCCGTAAAGATGTACCTTTGCGTCCAGTTCCGGCCCACTTTAACAACCTTCCT
AACCCTAATGCTCCACCCCCACCCGCCTGGCCTCGTGGGGGCTCATCCTCTGGCTCCTCC
TCGCAGCAGATACAGCAGCGCATCTCGGTTCCTCCCAGTCCCACCTACCAGCCCAGCTCT
CCACTCTTCCCTCC------CGGAGAGAGACCCGACCCTCCTCTGGCTGCAGCAGTACGT
CCCTTTATCCCCGACAAAGGATCCAGACCACAGTCGCCCAGAAAAGGGCcagcaaccatg
cactccagctctatcta-----tcacATGTACCTACAGCATGGGGTTCCCAAGAACTACC
CTCATGGTGGCAAATCAGCTGTGAAAGCAGTGTATGGAAAACCAGTTTTGTCCTCAAGC-
--TCAACTCCCACCTCGCCCCTGCCCT---TCCCTGGTTCCAT---GGGGttCCCTGGGC
TA------CCAGTTGCCATGGGAGACATGGTAGATGGTGAACTGGAATTCGAGGGCCAAT
TGA---------------CCTCTTTTCCAGAATCTCCTGCCCCTAATGTAGACCACATTC
CCCGGCCCCTCAGTCCAACCAAGCTCACCCCAATGGCTCACTCGCCAATGCGTTACCAAA
GTGA---TGATCTCGAGGTTCTTCGAAAGAAATTGGCCAATGCACCACGCCCCCTCAAAA
AGCGCAGCTCTATCACTGAACCAGAAGGGCCAAGTGGACCAAACATCCAGAAGCTTCTCT
ACCAGCGCTTCAACACACTGGCTGGTGGCATGGAAGGAGGCATCGGAGTGGAA------G
GAGGTGGG------------GGCGTCATGCCGTTCTATCAGCCTGCA------ATAGTCG
TTGGAGAGGCGCTAGCCGATGCAGATAATGGGAACAGATCTACA---GAAACACTGACTG
------------TGACAACTGCCACAGAGCAAGTGTCCACTAA-----------------
----------TGACTCGCCTCAGATTGACGCCAATGATAACCCACCGCCACAGGAAGTC-
--------------AGTGAGCGAGCACCTTCACCGGCCCCACCAGAACCGGAGTCATCAG
AGGATGAT---------AACAACAACCCAGCAGGACCTCAGATCGATCTGACCAGCTCGG
TCCCAGAGGACAGTCCCACAGTAGAGGAAGAAAGCTCACCACCATCTCAGTCTACAGAGA
AACGCACAAACCTAAAGAAGCCAAACTCTGAGCGGACAGGCCATGGTTTCAGAGTGAAGT
TTAATCCTCTGGCTCTTCTGCTGGATGCTTCACTGGAGGGGGAGTTTGACTTGGTGCAGA
GGATTATATATGAGGTTGAAAATCCCAGCACGCCTAATGATGAGGGAATCACACCACTAC
ACAATGCAGTGTGTGCAGGACACCACCATATTGTTAAGTTTCTTCTGGACTTTGGAGTTA
ATGTCAATGCAGCAGACAGTGATGGCTGG-------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------TGTGCAGGAAAAGCTGGGCGT-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Distichodus_sexfasciatus_gill_4|021055|scaffold30566|m.36732
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------GGGGCGCCAAAGAGCTACC
CGATGAGTGGCAAACCCGCCGTCAAAGCAGTGTACGGAAAACCACTCTTGCCCTCCTGCT
CTTCTGCTCCCCCTTCCCCATTGCCCT---ACCCGGGCACCGT---CTCTTTCCC-----
----------GGGCATGCTGGGAGACATGGCAGATGGCGATCTGGATCACGAAGGCCTGC
TAG---------------TGTGTCTCCCCGAGGCCCCTCCACCTAGCGTGGATCACATTC
CCCGGCCTCTCAGCCCCACCAAACTCACTCCCATGGTGCACTCCCCCATGCGCTACCAGA
GCGACGCCGAGCTGGAGGCTCTGCGCAAGAAACTGGCAAATGCTCCTCGACCACTCAAGA
AACGCAGCTCCATCACCGAGCCTGAGGGTCCCAGCGGGCCCAACATTCAGAAGCTCCTCT
ACCAGCGCTTTAACACTCTGGCAGGTGGCATCGAAGGAGGCGTTGGAGGAGTAGTAGGGG
GTGGAGGA------------GGAGTGACTCCATTCTACCAGCCTGCG------GGCGCAT
CTGGGGAGGCTCTGGCTGATGCCGACAACGGGAACCCGCCCTCA---GAGATGCCCACTG
---------TCGTGCTGTCCGTAACTGAAGGCATGACCGCTGA-----------------
----------TGCTTTGCCACAAAGTGATGCAAATGACAACCAGCCCTCGCAGCAGGAA-
--------------GACGAA---------ACCCAAGCTGCACCAGATTTGGGGGTTTCGG
AGGACGAT------AATAACAATAATCCAGCGGAGGCCTCTACCACCCTGCCTAGTCCTG
TACCAGAGGCCAGCTCACCACAGGAAGTGGAAACCTCAACGTCCTCTCAGACTGTGGAAA
AGCGCACTAATCTAAAGAAGCCCAACTCAGAGCGAACTGGCCATAACTTCAGAGTGAAGT
TCAACCCTCTGGCACTGCTCTTGGATGCGTCTCTGGAGGGAGAGTTTGATCTTGTGCAGA
GGATCATTTATGAGGTGGAGAACCCCAGCACTCCTAATGATGAGGGCATCACACCACTTC
ACAATGCAGTGTGTGCTGGACATCACCACATTGTCAAGTTTTTGCTTGATTTTGGAGTCA
ATGTCAATGCAGCAGATAGTGATGGCTGGACGCCCCTGCATTGTGCCGCCTCCTGCAACA
GCGTTCACCTCTGCAAGCTGCTGGTGGAGTCTGGAGCCGCCATCTTTGCCACCACCATCA
GCGATGTGGAGACAGCAGCAGATAAGTGTGAGGAGATGGAAGAGGGTTACATCCAATGCT
CCCAGTTCCTCTATGGTGTGCAGGAGAAACTAGGAGTGATGAATAAGGGAGTGGTGTATG
CTCTCTGGGAGTATGAGAGTCAGAGTGCAGACGAGCTCTCCTTCCAGGAGGGAGACGCCA
TCACGATCCTGCACAGGAAAGACGACAACGAGACCGAGTGGTGGTGGGCCAGACTTAATG
ACAAGGATGGCTATGTGCCTCGCAACCTGCTTGGGCTGTATCCCAGAATAAAACCACGTC
AACGATCCCTGGCATAG
>Gasteropelecus_sp._gill_3|018561|scaffold29893|m.31590
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------ATGTACCTCCAC---GGGGTACCCAAGAACTATC
CTTTTGGGAACAAGCCTGCCGTTAAAGCTGTGTATGGAAAACCAGTCCTGCCCTCCAGC-
--TCCACTCCCCCCTCTCCCCTGCCCT---ACACAGGCTCTGG---GTCTTTCCCAGTGT
TC------CTGGGTGCTGCAGGGGACATGGTAGATGGTGATCTGGATCCTGAGGGCCAGA
TGG---------------TAGGTCTCCCAGAGGTGCCTCCACCCAATGTGGACCACATCC
CTCGGCCACTCAGCCCGACCAAGCTCACTCCCATGGTCCATTCTCCCATGCGCTACCAAA
GTGATGCAGAGCTGGAGGCACTGCGCAAGAAGCTAGCCAATGCTCCAAGACCTCTTAAGA
AGCGCAGCTCTATCACAGAGCCCGAGGGGCCAAGCGGGCCCAACATCCAGAAGCTCCTTT
ACCAGCGCTTTAACACCCTGGCTGGTGGCATTGAGGGAGGAGTTGTAGGTGTA------G
GAGGTGGA------------GGAGTGACTCCGTTCTACCAACCAGCA------GGAGCTG
CAAGCGAGGCTCTGTCTGACGCAGACAATGGAAACCCGCCCTCA---GAAATGCCAGATA
---------CACCTCTTACTGGGAGTGAGGGGATACCCTCAGG-----------------
----------TGCCCTGCCTCAGGGTGATGCGAATGATAACCAACACCTGCAGCCAGCC-
--------------ACTGAA---------ACACTAGTCCCACCAGCACTGGAGCCATCAG
AGGATGATGAC---AACAACAATAACCCCGCAGGGCTCTCTGTCACACTGCCTAGTCCTG
TGCCTGAGGCCAATTCAACACCAGAGGCAGCAGCCTCACTGTCCTTCCAGTCTACAGAAA
AGCGCACTAACCTTAAGAAGCCTGACTCAGACAGGACAGGTCATGGCTACAGGGTGAAGT
TCAACCCCCTGGCACTTCTCCTGGATGCCTCACTGGAGGGCGAGTTTGACTTGGTGCAGA
GGATCATTTATGAGGTGGAGAACCCGAGCACCCCTAATGATGAGGGCATCACACCCTTAC
ACAACTCTGTGTGTGCTGGACACCACCACATTGTCAAGTTCCTGCTTGATTTTGGAGTCA
ACGTAAATGCAGCAGATAGTGATGGGTGGACCCCCCTGCACTGTGCTGCCTCCTGCAACA
GCGTCCACCTCTGCAAGTTGCTGGTAGAGTCTGGAGCTGCCATCTTTGCCACCACCATCA
GTGATGTGGAGACAGCAGCAGATAAATGCGAGGAGATGGAGGAAGGATACATCCAGTGCT
CACAGTTCCTCTATGGTGTGCAGGAGAAGCTGGGTGTGATGAATAAGGGGGTTGTGTATG
CTCTGTGGGAGTATACAGGTCAGAGCTCAGATGAGCTTTCCTTCCAGGAAGGAGACGCCA
TCACCATCCTTCGCAGGAAAGATGACAATGAGACAGAGTGGTGGTGGGCCAGACTTAATG
ACAGTGAGGGCTATGTGCCTCGCAACCTGCTTGGGCTGTACCCCAGAATAAAGCCACGTC
AGAGGTCCCTGGCATAA
>Lepidogalaxias_salamandroides_Head_2|028839|scaffold8839|m.11546
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---CATGAGGATTCCCCGACTGAGAGTGGCCATCAGGGGAGCCAGCTTTCTCAGGATCAG
GCCAACAGGAGGGGCGGACCCAATACAGACAAGCCTTGTGAGAACGGGGTTGGGAACTCG
CGTGTTGATCTCACCCTGTCTGAGCTGCAGGAAATGGCCACTCGACAACAGCAACAGATT
GAGGCCCAACAGCAGATGCTTGTTGCCAAGGAGCAGCGCCTGAGGTACCTGAAGCAGCAG
GAGCACAGGCAGGTGCAGACGGTGTCGGAGAGCGAGAAGCTGCAGAGGCTCAAGGACAGG
GTCGATAGTCAGGAGGCCAAACTGAAGAAGATTCGTGCCATGAGAGGGCAGGTGGACTAC
AGCAAGGTCATCAACGGGAACCTGTCCGCAGAGATAGAGCACGTGAGTAGCCTGTTTCAG
GAGAAGCAGGCTGAGCTCCAGACAGCAGTGCTGAAGGTGGACCAGCTCACTCAGCAGCTG
GATGACCTCCGCAGGGGGAGGGTCAACGGCCTGCAGCC---TTTGGGTGGACCGCTGACG
GGCACGGCTGCGCTGGAGCTGCGCAAACTCTACCAGGAGCTGCAGATCCGGAACAAGCTG
AACCAGGAGCAGAGCAGCAAGCTGCAGCAGCACAAGGAGCTGCTGAACAAGCGCAACACG
GAGGTGACGCTGATGGACAAGCGCATCGGCGACCTGCGAGAACGCCTTCACAAGAAGAAG
GCCGAG------------------------CTGAATAAGAGCAGCGAGCCCCCGTCCCCC
CAGCCGGCCCTGAGCAGCTCGGGCCGCGTGGCCGCTGTGTGTCCATACATCCAAGTCCCC
GTTCCAGGGAGGCAGGAGGGCGGCTACACTCTGAGCCCAGACTCGCTGAAAGCCCAGTCC
CTCGCCGTGACTGCCACTGTCAACCACGCCCGCTCAAAATCAGCTAACGATGCTAACTGG
CCCACGCTGAGCAGAGGGGTTGCTTCTCTCAAGCCCTCTGACTGGAAGGACACAAGCCCT
GACCCAACAGGCCAGATGCC---------------------------CGGTGACAAGAGC
CTGGACTCTAGCTTGACCCA---GGGGTCAGTGTCGCCCCTGGCCAAACCTCCGCCCAGC
TATGG------------------------CACCTACCCCAGCACGGG------CCATCCT
CCGTCAGTCTG-----------CTCCACCAGC--TCCCTGCCTCGCTCCGCT--------
-----------CCCGCCA-CGCTGGCCTGGCAGAGGGCCATCGCCGTGCCTGGCTCCTCC
TCCCAGCAGATCCAGCAGCGCATATCTGTACCCCCCAGCCCCACCCCCCAGGCCAGCCC-
--------------------CGGGGAGCAGCCCGATCCCCCGCTGGCCGTGGCCGTGCGG
CCCTTCATCACGGACCGCGGATCGCGACCTCAGTCCCN----------------------
AACTCCAGCTCTATCTA-----CCACATGTATCTACAGCAGCCAGCGTCCAAGAGCTACC
CGCTCAACAGCAGGTCTGCCGTCAGAGCAGTTTATGGCAAACCGGTCCTACCCTCCAGC-
--TCCACGTCCCCTTCCCCAGTGCCTT---TCCTGTTTCCAGG-----------------
----GTGTCAGGGCGGCGGGGAGGATGTGGTGGACAGGGAGGGGGAACATGAGATCGGGC
TGT------------------------------ATCCCCCGCCCAGCGTAG---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Melanotaenia_praecox_viscera_mixture_8|010837|scaffold15919|m.15542
ATGATGCCGATGATATTGACGGTGTACCTCAGTGATGGGGAACAGGCTGTGACTGAGGTA
CCCATAACGCCCGAGACGACGTGCCGCGATGTCGTTGAGTTCTGCAAAGAGCCCGGTGAG
AGCGGCTGCCATCTGGCTGAGGTCTGGAGAGGCAATGAGCGAGCGATCCCCTTTGAGCAC
ATGATGTACGAACATCTGCAGAAGTGGGGGCCTCGGAAACAAGAAGTCAAGTTCTTCCTC
CGGCATGAAGATTCGCCAACTGAGAGCAGCGACCAAGGGAGTCAGCAATCTCAGGATCAA
ACAAGTCACAGAAGTGGAAATTCTGGAGAGAAGCACAATGAGAACGGGGTGGGGAATCAG
CGTGTGGAGCTCACGCTGTCAGAGCTGCAGGAGATGGCCACACGACAACAGCAGCAAATC
GAGGCTCAGCAGCAGATGCTTGTGGCAAAGGAGCAACGATTGCGTTACCTGAAGCAGCAG
GAGCGACGTCAACAACAAACTGTGTCGGAGAGCGAAAAGCTGCAGAGGCTGAAGGAACGT
GTGGAGAACCAGGAGGCAAAGCTCAAGAAGATTCGGGCAATGAGAGGTCAAGTGGACTAC
AGCAAGGTCATCAATGGCAATCTGTCAGCTGAAATCGAGCAAGTGAGCAGCTTGTTCCAA
GAAAAGCAGGCCGAGTTACAGGCAGCAGTTCTGAGGGTGGAGCAACTAAGCCTACAGTTG
GAGGACCTTCGAAGAGGAAAGCTCAATGGcataCAGACCGGCCTGGGTGGACAAGTAACT
GGTGCTGCAGCCCTAGAGCTCCGTAAACTGTACCAAGAACTTCAGATTCGGAACAAATTG
AACCAGGACCAAAACAACAAGCTGCAGCAGCAAAAGGAGCTTCTGAACAAGCGCAACATG
GAAGTGACGCTCATGGACAAGCGCATCAGCGAGCTGCGGGAACGCCTCTACAAGAAAAAA
GCTGAG------------------------CTAAATAGAGCCAATGGGCCTCCCTCTCCC
CAGCCAGCTCCTGGTACTATGGGTCGTGTTGCTGCTGTTGGGCCTTATATCCAAGTTCCT
GTACCCAATCGACAGGATGGGGGCTACACCATGCCACCTGATCCATTGAAGCCGCAAACA
TTAGGTGTTAATAACCAAGCCAACCAAGCCCGCCCCAAATCAGCCAATGATACTGGTTGG
CCTACTCTAGGCAAGACCAATACAACTCTAAAACTTCCTGAGAGAAGAGACTCAGGGACC
GATACCCAGGGCAAGAGCCCTCCCTCAGGCTCCCCTGTCACTCCAAGTGCAGAAAAGGTG
CTAGACTCAAAAACTGCTGG---GGCTTCCCCTGCAATAACCAAGCCACATCCACCACCG
TATGGATCCCAC---------------CTCACCTCCTCTAACACAGC------CAGTTCC
TTGGAACGCCGCAAAGATGCACCTCCCCCTCC--CCCTCGCCCCCTCCCACA--------
-----------CCCACCAGCTCCCGCGTGGCCCCGCGCCCCCCCCTCCACAGGCTCCTCC
TCCCAGCAGATACAGCAGCGCATCTCAGTGCCACCAAGCCCCACCTTTCAGCCTAATGCA
CCGCTTTTCTCCCCTGGAATGAGCGAGCGTTTGGATCCTCCACCGGCTGTGGCAGTGCGT
CCCTTTATCCCAGACAGAGGATCACGGNNNNNAGCTCC----------------------
ATTTA-----------------TCACATGTACCTCCAGCAGACGGCACCAAAAAGCCAGC
CACTCAA------GCCTGCTGTCAAAGCAGTGTACGGGAAGCCTGTTCTACCCTCCAGC-
--TCGACACCTCCCTCACCTCTGCCTT---TCAGTCAGGCAGGAGGGGCCTTCCCATTGC
TCCAAGGCCAGGCTGGCACTGAGGATACAGTAG---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
>Sargocentron_rubrum_gill_6|016335|scaffold24900|m.31822
ATGATGCCGATGATATTGACGGTGTACCTCAGTGATGGGGAACAGGCCGTGACTGAGGTG
CCCATCACCCCGGAGACGACGTGCCGCGATGTTGTCGAGTTCTGCAAAGAGCCCGGCGAG
AGCGGCTGCCACCTGGCTGAGGTCTGGCGAGGCAACGAGCGAGCGATCCCCTTCGAGCAC
ATGATGTACGAACATCTGCAGAAATGGGGCCCTCGGAAACAAGAAGTCAAGTTCTTCCTC
CGGCATGAAGATTCACCAAATGAGAGCAGTGATCAAGGGAGTCAGCAGTCGCAGGAACAG
ACCAGCCGTAGAAGTGGAGGCACTGGAGAGAAGCACAATGAGAATGGGGTGGGGAATCAA
CGTGTGGAGCTCACGCTTTCAGAGCTGCAAGAGATGGCCACAAGACAGCAGCAGCAAATA
GAGGCCCAGCAGCAGATGCTTGTTGCAAAGGAGCAGCGTTTACGCTACCTGAAGCAGCAG
GAACGGCGGCAGCAGCAGTCTGTTTCTGAGAGCGAGAAGCTGCAGAGGCTGAAGGAACGC
GTGGAAAGCCAGGAGGCAAAGCTCAAGAAGATCCGGGCAATGAGAGGCCAGGTGGACTAC
AGCAAGGTCATCAATGGCAACCTGTCGGCAGAGATTGAGCAAGTGAGCAGCCTGTTCCAG
GAGAAGCAGTCGGAGTTGCAGGCGGCCGTGCTGCGGGTGGAGCAGCTCAGCCTGCAGCTG
GAGGATCTGCGACGGGGCAAGCTCAATGGCATACAGGCGGCCCTGGGTGGCCAAGTCACC
GGCACTGCTGCCCTAGAGCTTCGCAAGCTCTACCAGGAGCTTCAGATTCGTAACAAGCTG
AACCAGGAGCAAAACAGCAAGCTGCAGCAACAGAAAGAGCTTCTGAACAAGCGCAACATG
GAGGTGACACTCATGGATAAGCGCATCAGCGAGCTGCGGGAGCGCCTCTACAAGAAAAAA
GCTGAGGCACGTCAAAAAGAGAACCTCCCTCTAAACAGAGCCAATGGGCCGCCTTCTCCC
CAGCCAGCTCCGGGGACTCTGGGACGGGTGGCAGCAGTTGGGCCTTATATCCAGGTCCCT
GTCCCGAGCAGACAGGAAGGGGGCTACTCTGTACCACCTGATCCTCTGAAGCCTCCGGCA
CTGGGTGTCAATAACCAGGCCAACCACGGCCGCTCCAAATCAGCTAATGATGCTGGCTGG
CCtgctgcaggcaagaacaacacatccctcaagCCCCCGGACAGAAGGGACCCAGGGACT
GACACCCAGGGCAAGAGCCCTCCTTCAGGCTCCCCTGTTGCGCCAAGTGTAGACAAGGTG
CTGGACTCCAAGATGGC------AGTCTCCCCTGCCATATCCAAGCCGCAGCCGCCTCCC
TATGGCTCCCAC---------------CTCACCTCTGCAACCTCAGG------CAGCTCC
ATCGAACGCCGTAAGGATGCA------CCGCC--TCCTCGCCCGCTCCCCAA--------
-----------CACGCCAGCTCCTGCTTGGCCCCGCGTCCCTCCTTCCACAGGCTCATCC
TCCCAGCAGATCCAGCAGCGAATCTCAGTTCCCCCAAGCCCGACCTTCCAGCCCAATTCG
CCGCTTTTCCCTCCTGGACTGAGCGAGCGATTGGATCCCCCATTGGCTGTGGCAGTGCGT
CCCTTCATTCCAGACAGAGGGTCACGGCCTCAGTCGCC----------------------
CCGCAAGGGCCCAGCAGCGAATCTCAGTTCCCCCANAACAGGCAGCACACAAGAGCCAGC
CACCCAA------GCCTACACTCAAAGCAGTGTATGGGAAGCCTGTGTTCCCCTCCAGT-
--TCGACACCTCCCTCGCCCCTGCCTT---TTATGCAGTTAGGGGGGGCGTTCCCCATGC
TCCAGGGCCACCCCAGTGGCGAGGACTCATTCGACGGAGAGGTGGATGA-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------
