>Amblygaster_clupeoides|023763|TR42677|c0_g2_i1|m.63340
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------ATGAGATTCCCCACCAAGCAGGAGAGC
CAGCTCAGAAACGAGGTGGCCATTTTACAGAGCCTGCACCACCCTGGCATTGTCAACCTG
GCGTGCATGTTCGAGACTCCGGAGCGCGTCTTTGTGGTCATGGAGAAACTTCATGGCGAC
ATGCTGGAGATGATCTTGTCTAGCGAGAAGAGTCGCCTTCCCGAGCGCCTCACCAAGTTC
CTGGTTACCCAGATTCTGGTGGCTCTGAGACACCTTCATTTCAAAAACATTGTCCACTGT
GACCTGAAACCAGAGAACGTGCTGTTAGCATCTGCAGAGCCCTTCCCACAGGTGAAGCTG
TGTGACTTTGGCTTTGCTCGCATCATTGGGGAAAAGTCTTTCCGGCGTTCTGTGGTGGGC
ACCCCCGCCTACCTTGCCCCTGAGGTCCTCCGTAGCAAAGGCTACAACCGCTCCCTGGAC
ATGTGGTCAGTGGGGGTCATCATCTACGTCAGCCTCAGCGGAACGTTCCCCTTTAACGAG
GACGAGGACATCAATGACCAGATCCAGAACGCTGCTTTCATGTACCCCCCCAACCCCTGG
AAGGAGATCTCCGGAGAAGCAATTGACTTGATAAACAACCTGCTTCAAGTGAAGATGAGG
AAGCGCTATAGTGTTGATAAATCACTCAGTCACCCATGGCTACAGGATTACCAGACCTGG
TTGGATCTCCGGGAGTTTGAGACTCGTCGAGGAGAGCGATACATCACCCATGAGAGCGAT
GACGCCCGCTGGGAGGAGTATGCAGATGAGAGGAGCCTTCCCTACCCCAAACACTTCATA
ATGGCTCCAAACCTAGATGACATGGAGGAGGACCCCTAG
>Distichodus_sexfasciatus_gill_4|020471|scaffold29944|m.35645
CAGAGACTGACGTCAGCTGAGGATATCCATGAGGGAGATCTGATTGAGGTGGTGCTTTCA
GCTCTAGCCACCGTTGAAGACTTTCAGATCCGGCCTCATGCCCTGTACGTTCACTCCTAC
AAGGCCCCGGCCTTCTGCGACGACTGCGGCGAGATGCTGTGGGGTCTGGTGCGGCAGGGC
CTCAAGTGTGAAGGATGTGGGCTTAATTACCACAAGCGATGTGCGTTTAAAATCCCCAAC
AACTGCACCGGCGTGAGGAAGAGACGCCTGTCCAATGTGTCCCTGCCCGGACCCTCGCTG
TCCATCTCTCGACCTCCGGGCCCTGAGACTGTTGTTATGACAACAGATGAGCAGAGGCCG
TTGCTGGAGGCAGGGAAGCGGATCCCGTCGTGGAGTGGCCGTCCGATCTGGATGGAAAAG
ATGGTTTTGGGCCGGGTCAAAGTGCCTCACACCTTCAACGTGCACACGTACACGCGGCCG
ACTATCTGCCAGTACTGCAAACGGCTGCTGAAGGGTCTCTTCCGCCAGGGCATGCAGTGC
AAAGATTGCAAATTCAACTGCCATAAGAGATGTGCATCGAAGGTACCAAGAGACTGCTTG
GGTGAGGTGGTGTTCAACGGAGAGCCTGCCAGTCCGGGGCCTGACACTGAGGCCACTATG
GAGGTGGACAACAGTGATGTAAACAGTGAGAACAGCCGCATCATGGACGATCCGGAGGAG
ATCTCCACACCTGAGGACAAAATCTTTTTCATGGACACAGCCTTCCT------------G
GATGATGAAACAATCAAGGTCAACAGTCCATCCACCAGCAGTAACATCCCGTTGATGCGT
GTGGTGCAGTCCATCAAGCACACAAAGAGACGAAGTTCCACCCTGGTGAAAGAGGGCTGG
ATGGTGCATTACACCAACAGAGACAACCTGAGGAAGAGACATTATTGGAGACTGGACAGC
AAGAGCCTGACCCTTTTCCAAAACGATACTGGAGCCAAGTACTACAAGGAGATCCCGCTC
TCTGAGATTCTTCAGCTGGAGTTGGCACGGGACTTCACCAACTTGGCCCAGGGAGGGAAT
CCTCACTGCTTTGAGATCATCACAGATACCATGGTCTACTACGTGGGGGAGAACACCGGC
AGCCACCAGCCCAACCCGGTCCTGGCAGCATCCGGCGTGGGCCTCGAGGTGGCACAGAGC
TGGGAGAAAGCCATCCGCCAGGCGCTGATGCCTGTCACCCCACAAGCCAGCGTCTGTAGC
GGCCACGGCCACGGCCACGGCCAGGGGAAGGACCACAAGGAGGTGTCGATCAGCATATCA
GTGTCCAACTCACAGATAAAGGAGAACGTGGATATCAGCTCTGTCTACCAGATCTTTGCG
GACGAGGTTCTGGGATCGGGCCAGTTTGGTGTTGTGTACGGAGGCAAGCACAGAAAAACC
AAGAGGGATGTGGCCATCAAGGTCATAGACAAGATGAGATTCCCCACCAAGCAGGAGAGC
CAACTGAGGAATGAAGTGGCCATTTTACAGAATCTGCACCACCCCGGCATCGTAAACCTC
GAGTGTATGTTTGAGACCCCGGAGCGTGTGTTTGTAGTGATGGAGAAGCTTCATGGAGAC
ATGCTGGAGATGATCTTATCGAGTGAAAAGAGTCGGCTTCCTGAGCGTCTCACCAAGTTT
CTGGTCACTCAGATTCTGGTGGCTCTGAGACACCTTCACTTTAAGAACATTGTTCATTGT
GACCTGAAGCCTGAGAACGTGCTGCTGGCGTCAGCAGAACCTTTTCCTCAGGTGAAACTG
TGCGACTTCGGCTTTGCCCGCATCATCGGCGAGAAGTCATTCCGGCGGTCGGTGGTGGGA
ACACCGGCATACCTGGCGCCCGAGGTGCTGCGCAGCAAAGGCtACAACCGCTCCCTGGAC
ATGTGGTCGGTGGGGGTCATCGTCTACGTCAGCCTGAGTGGCACCTTCCCCTTTAACGAG
GACGAGGACATCAACGACCAGATTCAGAACGCTGCGTTCATGTACCCTCCCAACCCCTGG
AAGGAGATCTCTGGGGAAGCCATCGACCTGATCAACAATCTGCTTCAAGTGAAGATGAGG
AAACGCTACAGCGTGGACAAATCACTCAGTCACCCCTGGCTTCAGGACTATCAGACATGG
CTGGACCTTCGCGAATTTGAGACTCGGCGAGGCGAGCGCTACATCACCCACGAAAGCGAC
GACGCTCGCTGGGAGGAATACGCCGACGAGAGGAACCTGCTCTATCCAAAGCACTTCATC
ATGGCTCCCAACCTGGACGACATGGAGGAGGACCCCTAG
>Gasteropelecus_sp._gill_3|004619|C946240|m.49385
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---ATCTGCCAGTACTGCAAACGCCTGCTCAAGGGCCTCTTCCGCCAGGGGATGCAGTGC
AAGGATTGCAAATTCAACTGTCACAAGCGATGTGCTTCGAAGGTTCCAAGAGACTGCTTG
GGTGAGGTTGTGTTCAATGGAGAGCCAGCAAGTCCGGGGCCTGACTCTGAGGTTACTATG
GAAGTGGACAGTAGTGATGTGAACAGCGAGAGCAGTCGTGTAATGGACGATGCTGAGGAG
GTCTCCACTCCAGAGGATAAAATCTTCTTCATGGATTCTTCATTCCTGGATGGGGAAAAG
GATGAGGAAACAGTGAAGGCTATCAGTCCAACCACCAGCACTAACATCCCTCTAATGCGT
GTGGTTCAGTCCATCAAACACACCAAGAGACGCAGCTCCACCTTGGTGAAGGAGGGGTGG
ATGGTGCACTACACCAGCCGAGACAACCTGAGGAAAAGACATTATTGGAGGCTGGACAGC
AAGAGTCTCACCCTTTTCCAGAATGATTCCGGAGCAAAATACTACAAGGAGATCCCCCTT
TCAGAGATTCTTCAGTTGGAGCTTGCACGGGACTTCATTAATCTGGCACAGGGGGGAAAT
CCTCACTGTTTTGAGATCATTACAGACAGCATGGTTTATTATGTCGGGGAGAACACAGGC
AACCTTCAACCCAATCCTGTCCTGGTGGCGAGCGGAGTGGGGCTGGAAGTGGCTCAGAGC
TGGGAGAAGGCCATCCGCCAGGCCTTGATGCCTGTAACCCCACAGCCCAGTGTCTGCAGT
GGACCAGGACATGGC------------AAGGACCACAAGGAGGTATCTATCAGCATATCA
GTCTCCAACTCGCAGATTAAGGAGAATGTGGATATCAGCTCAGTGTACCAGATCTTTGCT
GATGAGGTGCTGGGATCGGGACAATTTGGGATTGTGTATGGAGGCAAGCACAGAAAAACA
AAGAGGGATGTGGCCATTAAAGTTATAGACAAGATGAGGTTCCCCACCAAGCAGGAGAGC
CAACTGAGGAACGAGGTGGCCATTTTACAGAATCTTCACCACCCTGGCATTGTAAACCTC
GAGTGTATGTTTGAGACTCCGGAGAGGGTGTTTGTTGTCATGGAGAAGCTCCATGGTGAC
ATGCTAGAGATGATCCTGTCCAGTGAGAAGAGTCGGCTTCCTGAACGGCTGACCAAATTC
CTGGTGACCCAGATTCTGGTGGCATTAAGACATCTCCATTTCAAGAACATCGTTCATTGT
GATTTGAAGCCAGAGAATGTGCTTCTGGCTTCAGCAGAGCCATTTCCACAGGTGAAGCTG
TGTGATTTCGGCTTTGCCCGAATCATTGGGGAAAAGTCCTTTAGGCGGTCAGTTGTGGGC
ACTCCGGCGTATCTTGCCCCTGAGGTGCTGCGTAGTAAAGGCTATAACCGTTCCCTGGAC
ATGTGGTCAGTT------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------
>Lepidogalaxias_salamandroides_Head_2|017335|scaffold15475|m.20629
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------AGGGGTCTT---------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------GACAACTCTGAGGAA
TCATCCATACATGAAGATAAGATGTTTTATTTGGACTCCCCTTACCTTGATTGCGAGAAA
GATGAAGAGCCCATTAAAACCATTAGCCCCTCAACCAGCAACAACATTCCCTTAATGCGC
GTGGTGCAATCCATCAAACATACCAAGCGGAGGAGTTCCACCATGGTGAAGGAGGGCTGG
ATGGTACACTTTAGCAGCCGAGACAACCTGAGGAAGAGGCACTACTGGAGATTGGACACT
AAGAGCCTGACCCTGTTTCAGAACGAGACTGGAGCCAAGTTTTACAAGGAGATCCCCCTG
TCAGAGATCCTACAGCTGGAGTCGGCTCGGGACTTCAGCAGCTTGGCCCAAGGGAGCAAC
TCCCACTGTTTTGAGGTTATCACCTCCACCATGGTCTACTACGTAGGCGAGAACAATGGC
GGACTCTTCAACAACTCTGCGCTGGCCGCCTCTGGGGTGGGCATGGAGGTGGCCCAGGGC
TGGGAGAAGGCCATACGCCAGGCACTGATGCCGGTGACCCCCCAGCCCAGCGTGAGCGCT
GCAGCTGGACAGGGC------------AAGGAACACAAAGAGTTGTCCATCAGCATATCT
GTGTCTAACTGCCAAATACAGGAGAATGTCGATATTAGTGCTGTCTACCAGATTTTCTCT
GATGAGGTATTGGGATCTGGCCAGTTTGGTGTTGTGTATGGAGGGAAGCACAGAAAGACA
GGAAGAGATGTTGCCATCAAAGTGATTGACAAAATGAGATTTCCCACCAAACAAGAGAGC
CAGCTGAGAAACGAGGTGGCCATTTTACAGAACCTTCACCATCCTGGAATTGTCAACCTG
GAGTGCATGTTCGAGACACCCGAGAGGGTTTTTGTCGTCATGGAGAAGCTCCACGGTGAC
ATGCTTGAAATGATCCTGTCCAGTGAAAAAAGCAAGCTCCCAGAACGCATTACCAAGTTT
CTGGTAACGCAGATTTTGGTGGCTTTAAGACACCTGCATTTCAAGAACATTGTTCACTGT
GACCTGAAGCCAGAGAATGTGCTCCTAGCCTCAGCAGAACCCTTCCCTCAGGTCAAGCTG
TGCGACTTCGGCTTCGCTCGCATCATCGGCGAGAAGTCGTTTCGCCGCTCTGTGGTGGGA
ACGCCCGCCTACCTGGCGCCCGAGGTCCTTCGCAGCAAGGGCTACAACCGCTCGCTGGAC
ATgtggtcagtgggcgtcattgtgtacgtcagcctgagtggcaccttccccttcaaTGAG
GATGACGACATCAACGATCAGATTCAGAACGCCGCCTTTATGTACCCTGCCACGCCCTGG
AAGGATATCTCGGCGGAAGCTACCGATCTCATCAACAACCTTCTTCAGGTGAAGATGAGG
AAGCGATACAGTGTTGATAAGTCCCTCAGTCATCCGTGGCTACAGGACTACCAAACGTGG
TTGGACCTCAGGGAGTTCGAGACTCGGCGTGGGGAGCGCTACATCACCCACGAGAGCGac
gaTGCACACTGGGAAGAGTACGCGGATGAGCACGGCCTCACCTATCCCAAGCACTTCATC
ATGGCTCCCAACTTGGATGATATGGATGAGGACCCCTAG
>Pantodon_buncholzi_mixed|016164|scaffold18870|m.26905
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------GGAGAC
ATGTTGGAGATGATTCTTTCCAGTGAGAAGAGCAAATTACCGGAACGTATCACCAAGTTC
CTGGTTACACAGATCCTGGTAGCTCTCAGACACTTGCATTTCAAGAACATCGTGCACTGT
GACCTTAAGCCAGAAAATGTACTCCTCGCATCTGCTGAGCCTTTTCCTCAGGTGAAGCTG
TGTGACTTTGGTTTTGCCAGAATCATTGGTGAGAAATCATTCAGACGTTCCGTGGTGGGA
ACTCCAGCTTATCTGGCACCTGAAGTGCTACGCAGTAAGGGCTACAATCGCTCACTTGAC
ATGTGGTCAGTGGGTGTCATCATCTATGTCAGTCTGAGTGGCACCTTCCCCTTTAACGAG
GATGAGGATATCAATGACCAGATTCAGAATGCCGCCTTCATGTACCCACCGACACCCTGG
AAAGAGATTTCAGCTGAAGCAACAGATCTGATAAACAACCTTTTGCAAGTGAAGATGAGG
AAGCGGTACAGCGTGGACAAATCTCTTAGTCACCCTTGGCTGCAGGACTACCAGACCTGG
CTGGACCTCAGGGAATTTGAGACGCGGAGAGGAGAGCGCTACATCACCCACGAGAGCGAC
GATGCGCGATGGGAGGAGTACGCGGAGGAGCACAACCTCCCCTACCCTAAACATTTCATC
ATGGCTCCCAACCTGGATGACATGGAGGAAGACCCCTAG
>Scleropages_formosus_red_gill|013439|scaffold20493|m.26738
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------GAC
ATGCTGGAGATGATCCTGTCTAGCGAGAAGAGCAAGCTGCCCGAGCGCATCACCAAGTTC
CTGGTCACGCAGATCCTGGTGGCTTTGAGGCACTTGCATTTCAAGAACATTGTGCACTGT
GACCTGAAGCCGGAGAACGTCCTCCTGGCATCGGCAGAGCCTTTCCCTCAGGTGAAGCTG
TGTGACTTTGGCTttgcCCGCATCATCGGGGAGAAGTCGTTCCGCCGCTCGGTTGTTGGC
ACACCTGCCTACCTGGCTCCTGAGGTCCTGCGGAGCAAGGGTTACAACCGCTCGCTGGAC
ATGTGGTCCGTGGGTGTCAtcgtctacgtcagcctgagcggaactttccccttcaacgag
gatgaggacatcaatgaccaGATCCAGAATGCTGCCTTCATGTACCCGCCAACGCCCTGG
AAGGAGATCTCTGCAGAAGCCACAGATCTCATCAACAACCTTCTTCAGGTGAAGATGAGG
AAACGGTACAGCGTGGACAAGTCCCTTAGCCATCCCTGGCTGCAGGACTACCAGACATGG
CTGGACCTCAGGGAGTTTGAGACACGGAGGGGCGAGCGCTACATCACGCACGAGAGCGAT
GACGCACGCTGGGAGGCGTATGCCGACGCGCACAACCTGGTCTACCCAAAACACTTCATC
ATGGCGCCCAACTTGGAAGACATGGAGGAGGACCCCTAG
>Synodus_sp._gill_5|012125|scaffold16508|m.19925
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------GAGAAGCTCCATGGCGAC
ATGCTGGAGATGATCTTATCCAGCGAAAAGAGTCGTCTTCCCGAGAGGCTGACCAAGTTC
CTGGTAACCCAGATTCTAGTGGCCTTGAGGCACCTGCATTTTAAAAACATCGTCCACTGT
GACCTGAAACCTGAGAACGTTCTTCTGGCCTCGGCAGAACCATTTCCTCAGGTGAAGCTC
TGTGACTTTGGCTTTGCGCGTATCATCGGGGAGAAGTCATTCAGACGTtcggTGGTGGGC
ACGCCAGCCTACCTGGCACCGGAAGTGCTGCGGAGCAAAGGATACAACCGCTCCTTGGAC
ATGTGGTCCGTCGGTGTCATCATCTACGTCAGTTTGAGTGGAACCTTCCCTTTCAATGAG
GACGAGGACATTAATGAACAGATTCAGAATGCTGCCTTCATGTACCCTGCAAACCCATGG
AAAGGGATCTCTGGAGAGGCCACAGACCTGATCAATAACCTGCTCCAAGTCAAGATGAGG
AAGCGCTTCAGTGTGGACAAGTCTCTCAGTCACCCCTGGCTTCAGGATTACCAAACCTGG
CTGGATCTCAGAGAGTTTGAGACACGCGGGGGAGAGCGTTACATCACCCACGAGAGCGAT
GATGCACGCTGGGAGGAGTACGCCGACGAGAGGGGACTACACTACCCCAAGCACTTCATC
ATGGCACCCAACCTGGAGGACATGGAGGAAGACCCCTAA
