>Amblygaster_clupeoides|007010|TR17319|c9_g2_i1|m.32712
ATGCCAGCCTTACCTACTGGTGGTGTGTTTGGATTTTTTGTTTGTTTTTTTCGCTTGAAT
TCAGTTTTTTTTATTCACATAACCTTTTCCCCTACCCTACCCTTCCCTTCTCTACCCCTT
GTTTTTCCACTTCATTTTCTCCAGTCTCTCAATACTGATTTGACCTCCTCCAGGCAGGAG
GCTGAACGGCTCTCTGCAGAGATTGTGACTGTGAAGGCTGCATCTGAGCGCCTAACAGAG
GATATTAAAGATTTGCAGGCTCAAAGAGAAACCATAAAGAAACAGCTGTCTGACTCCTTG
GAGAAAGTCTCCTCCTTGGAGGTATCTCACAAACAGCTGTCTGCAAAGTATGATGATCTA
AACATCCTCAAAGAAAGGCTCCTCAATGAAAATAAAGATC----TGCTGTCAGGCAAAAC
TTCCCTGGACAAGGAGAAGTTGTCGATCACTTCAGAAAAAGAGCAGCTCTCGCAACAGCT
CCAAGAGCTTAGCATCACCTTGGAAAAGATAAAGGATGAGAATGCTGGTCTTAAGGACTT
GGAGGTGAAGCATCAGGCAGAAATCACAGAACTTCAGAAGGTAAATACTGAAAAGCAAGA
TGTTCTTCTAAAGTACCAGGAGGAGATGAAACAACAGGATGCCAACAAGAACCAGCTGTC
CAGTGATCTTCAAAAAGCCTGTAGTGACAAGGATAAGCTCAAAAGCAAGCTTGCTAAAAG
TCATGAAGAGTTGAAATCATTAAAGGACAATTTAGAAAAGGAACAGCACAAATATGAGAA
AGAAAAGAAGGCCCTAGATGCAAAGAATGCCGAACTACAGTCCATGATTCAGTCCCTTAC
ATCTGAAAAGGAAGACCTTTGTGCCAACAATAAACAGTTGCAGGTTGAAAAGGAGAATCT
AAATAAAGAGAACAATAAAATATCCACACAGTTGAAGGCTTCTTTGCAAGAGAAAGAGAC
CCTCTCTTCTGACAAAGTAGAGCTTGAAAATAAATTTAACACTAAAAACAAGGACCTTGA
GAAAGCTATGCGGGACATTACAGAGTTGGAAGCCTCCAAGAGCAGCTTAACTAAAATGCT
GGAGGAAATCAAGATGAGCAGTGAGGTAACAGACTCTGAGAAACTGAAGATATTGCAAGA
AAAGGAAGACTTGCTTTCAACATGGAGAAAGGTGAGCTCTGAAAAAGAGCAGCTCGCAAA
AGAGAAAATAGAGCTTACAGAGAGGTTACGCCAAACAGCAAATGAGGTCAAGGCTGCAAA
GGAGAAGATCCAGCAAGAAACCACTGCCTTCTCTGAAGAAAAAGATGCTCTATGTGTGAA
GCTCTCTGAAATGGAGAAGTCTTTACAGTCCCTTCAAAAGGAGAAGACCAACTTAGAATC
AGCCTTGGGAAGGCAGAAGACTGAGAAGGAGCATTTGAAAAAGGAGAAGGAAGAGTTGCT
GGAGAAGCATGAGAGGGAAGCCTCTGAGAAATCCTCCATTGCTGCCGAGAGAAATCAACT
TTCGGAAGAATTAAATAAAACTAAGGATCATCTCGAGAGTTTGTCCAAGGAGTGTGCTGA
CTTGGTCAAGGAAAAAACAAGTTTTATTGCTGAGTTGGAGGACACTAAACAAAAGAAACA
AGAAGTTGAAGGTCAGAAAACTACTTTAGTTCAAGATAAGGTAAACTTAGAAGCGCAACT
GCAGAAACTTCGCACGGAGATTGATTCTCTTAAGAAAGCCAAA-----------------
------------------------------------------------------------
-------------------------------TCACAGCTAACA-----------------
------------------------------------------------------------
----------------------------------------------------------GA
TGAGCTTAGTAAAGTGAAGGATAAC-------------------------AAAAAACACT
TG----------------------------------------------------------
------------------CAAGAAGAACACGGC---------------------------
------------------------------------------------------------
-----------------------------------CATCAGAGGGAG-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------GCTCTGTTGA-------
-AGGAACGGGATATTCTTCTCTC-------------------------------------
------AGAGAAAGCAGATCTTATAAAGACTC----------------------------
--TAGAGCAGCTTCAG-------ACAGACAGAGAG-------------------------
------------------------------------------------------------
----
>Corydoras_julii_viscera_mixture_8|010189|scaffold18047|m.13247
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------AAACTGTGTTCTGAAAAGCAGGACCTCACGAA
GCAAATTGAAGAGCTGGTTGAGAAGCTTCATACCAGTGCCGAAGAGGTCCAAACGGCCAA
CGAGAAGATCCAACGTGATTCAGCCTCATTCGCTCAGGAAAAAGAAAAGCTCGATTCCAA
ATGCATAGAACATGAGaacaTCCGTAAGGCTCTCGAAGACGAGAACAAGAACCTGAAGTC
TGAACTTGAGAAGCAAAATGGTGTTTGTAGCCACTTGGAGGAGCAGATCAGTGACTTTGT
AAAAAGACATAAACAGGAAAAGGATGAACATGCTTCCATTTTGGCCGATCAAACCCAATC
AGGAGCCAGATTACTGAGTGAGAAGATGCATCTGGAG-----------------------
----------------------------TCTGAGGTGGAG--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Distichodus_sexfasciatus_gill_4|007088|C918699|m.56049
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------TGTCTGAGTCCATG
AAGAAGGTTTCTAGTCTAGAGGTGGCACAGAAGGAGCTTTCTAAAGTAAATGATGAACTG
AAAGCTGACAGTGAACGGTTATTAAGCGAGATGAAGGAACTACGTACTGCAAGCCAGAAG
T----TGCATAATGAGAAGTCATCGCTCGAAACGGAGAAGGGAAATCTTTCCGAAGAAGT
GCAGAAATTAATGAAGACAGTTGAAGATATCAAAGGCGAAAATGTGTCTTTGAAGGAAGC
TGAGACAAAGCACCTGGCTCAAATTGGGGCTCTTGAGAGAAACAATGCTGAGAGACAAGA
AACCATTGTCAACCATCAGCAAGAGATTGAGCATCTGCAGACCAACGCTGCACAGTTAGC
TGAAAAACACACTAGGGTTTGTGAGGAAAGGGAAAAGGT---------------------
TCAGGAAGACTTAAGAT---------------------------------GTCATCAACT
GGAGATGCAGTGCCTTAGTGCAAAGTTTGAAGAGCTCCAGTCATCATTTAAGTCCCTTGA
AGACGAGAAAGAAGATCTCATTTCCAAGCATTTCAAGTTGGAATCAGATGCAGAGTCTCT
GCGCAATGAGAACGCAAAGGTGCATGGTGACCTAGATGCCGCTGTCTTGGAAAAAGAGTC
TCTGAAGAGTGAGAAAGCAGAGCTTCAGAAAGAGCTTTGTGACATGAAAGTAGAGCTCGA
GAAGTCCAGCAAAGACAATGCAGAGCTCCAGATCTCCAAAAGCAGGTTTGCCAAAATGCT
TGAGGAAATTAAGTCCAGCAGGGAGGTCACTGACTCTGAGAGACTGGTTTTACTGCAGGA
GAAGGAGAATCTGCTTGAAGTGCAGAGAAAACTGAGCTCAGAAAAGCAGGACCTTGAAAA
CAAAGTCACCGCACTGATTGATAAGCTGCGGCTCAGCACTGAAGAGGTCGAGGCTGCCAA
CGAGAAGATCCGAAACGATTCTGCAGCTTTTGTAGAAGAGAAAGGGACCATTACCACAAA
GCTTGCAGAGACTGAGAAGACCCTTCAGAACCTTGAAGAAGAGAAAAAGTCTCTGAAGTC
TGCTCTTAAGAAGCAGAAAGAAGAACGGGATCAGTTGGAACAAAGTATGACTAGCTTGAA
AGATACCCACGAGAAAGAAATGTCTGAAAAGGCATCTCTCTTAGCAGAGAACAATCAGCT
GGTTTCGGATATGAGCAGCGTGAAAGACCAGCTGCAGAAAAGTCTAACGGCAAATGCTGA
CTTGCTCAATGAAAAAACAAGTCTTGAATCGGAATTCGAGAAAATGAAGCAGGTGGAAGA
GGAGTTGTGCTCTGAGAAGGCGAAACTAATGCAGGACAAGGATGGTCTTGAGGTTCTTCT
GCAGAACAAGAGCACCAAAGTTGAGTCGCTCGAAAAAGACAAAGTTGATTTGATGGAACA
AAATCAGAAGTTGCAGCTCAGTTTAGACCAAGCGAATCAAGAAAATGCCCAGCACGTTGA
CGCCCTGTCAACTGTTAAAACATCCCTGCTTTCCCAGCAAACAGAGCTGAATACAACGAT
TGAGGACCTCAAGAAGACCAATGAGGACCTACTCAAGCAAGCCAAAGATCTTTCTGCTCA
GAACAGATCTTTGTCTGAGACCAAAGTTTGCTTGGAACAAATATTGGAAGCAGACAAGGA
AGAGTTTTCCATTGTGAAGGAAAATCTTTGCAAACAAGTTGAGGAACTCACAAAAACAGT
TACTAATTGTGCAGAAGAGAAAACTAGTCTCCTGGAGGAACAGGCCAAGCTTACTGCCCA
AATGGCGTCCATTGAGACCGAGAAGGATAAGGCAGAAAACGAGAAGCAGTTGCTGGTTAA
AGAAATGGAGCTATTAAAAACCCAACAGCAGAAGAGCGACAAGGTAGGTTCAGATATGGC
AGCTGCGAAAAACCTTCTCACTTCCAGAGTGGAAACATTAGAGAAGGAAACCGCAGATCT
AAGCAAGGAGAAGTCTGATCTCCTGGCTTTGCATCAATCTCTGGAGCAGGAACTTCTCTC
TGTTCGTCATGCTCTGGAAACCAGTGACCACAAGTGTTCCAAGTATCTGGCTGAAGTAGA
AGAGCTGAAGCGATCCCGACAAGAGTTGGAAGCTCAGTTGAGAACCCTTCAGCAGGGCCA
TGAAGCATCAGAGACCAAAAGGGCAGCTGCTGAATCTGAGGTTGCTCTGTTGACCAAGGT
GAGGGAAGAGATGTCCTCCAGTCTGACCGCAGCGCAGGCCGAGAGAGACACCTTGCGTGG
GGCAAAGGAGGACGCCGAATCAGTAGTGGCTCAACTCAAGGCCCAAAACCAAAGTGCTAT
CTCGAAGCAGCTTGAGGTACTCCACAAACATCAAGCACCTTCCAACCCACTGCAGAACCT
TCTAGACTTGCACTTGCAGCAGGGGTGGGTAATCCCGGTCCTGGAGGTCATCTGTCCTAC
TTGA
>Gasteropelecus_sp._gill_3|000697|C858469|m.43120
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------CTTGTTGAAAAACTTCGCCTCAGTACAGAAGAGACCAAGGCCTCCAA
CGAGAAAATTCAGCTTGATACTGAGGTTTTTGCTCAAGAAAAGAAAATTCTTCATGAGAA
GATTTCAGAGACTGAGAAGACCATTCAGACCTTTCAAGAGGACATAAAATGCCTGAAATC
TGACCTTGAGAAGCAAATTAGTGAACGGGAGCATTTGGAACAACAACTTAACAACTTAAA
GCAGACATATGAGAGAGAAATGTCAGAGAAGGCTTCTCTCATGGCAGAACAAAAGCAACT
AGGAGCAGACTTGTGTAGTATCAAAGATGACCTGAAGAACACTCTGATGGCAAAT-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Melanotaenia_praecox_viscera_mixture_8|002586|C427608|m.27988
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------CTTCTGCAGGA
GAAAGAAAACCTGCTTACAATCCAGAGAAAAGTCTCAAATGAAAAAGAAGAGCTTCTCAG
AGAAATTCAAGAAGTGAAAGAAACACTTCAGGTCTCAACAGAGCAATTGTGTCAGTCTAA
AGAGAAACTTAAAGAAGCATCTTCTTCTTTTGAGCATGAGAGGCAGGCGTTGCGCGTTCA
GAATTCTGAAACTGAGATGGCTCTACATGAACTGCGCAAAGAAAAGATGAGTCTGGATTC
AGCTCTAGAGCAGCAAAAAATGGATTATGAGCGTTTGACTGAGGAGAAGGCAGAGTTGGA
AAAAAAACACACAAAGGCAGTTTCTGAAAAAAATGCTGTCTCTCTTGAATGTGAGAAGCT
AGTTGGTGATATCCGAACAGCGAGAGACCAACTAGATGGTTTCACCAGAACAAATGCTGA
CATTACTCAAGACAAGGCTCATTTAACAGCAATGTTGGAGGAAACCAAACGGCAAAGAGA
TGAAGTTGAGGTTCAGATGACTTCGTTGAAACGAGAAATG--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Scleropages_formosus_red_gill|001650|C1226818|m.69672
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------AAAGAGCTG--------------------------------------------
-------------------------------GCTCAGGAAAAACAGACACTTATCCAGAA
GCTTGCAGGAGCAGATAAGGAACTTCATGACCTCCACATAGAGAATGCAGCCCTTAAACT
CACGGTACAGCAGCATGTCATTGAGAAGCAGTCTTTGGAAAGGGAGAAGGAAGATCTGAT
AGAAAAGTACAAAAGAGAACTTTCTGAAAAGGCAGCTATTGCCATGGAAAGGGACCGATT
GGCTGAAGATGTCAACAGAATTAGGGAACAGTTGGAAAATTCATGTAAGGTGAATGCTTC
CCTTGTGCAGGACAAGTCTAGTTTGGTGGCTGTGCTGGAGCAAGTGAAGCAGCAGATGGA
GGGGGTAGGCAAAGAGAAGGCCATTTTAGAAAGGGAGAATGCAGATATCAAAGTCCAG--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Synodus_sp._gill_5|016780|scaffold22215|m.29197
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------GTTATCAA
GGAAAGAGAAGAATTAAAGGAGATGCTTCGTGTTTCAACAGAGGAGTTGTCTGCATCCAA
ATTAAAAGTTAAACAAGTGACTCTATCTTTTGAGCAGGAAAAGGACTTACTTTGCCTTCA
AAAGGTTGACTCTGAGAACACACTTCATGCTTTACGGAAGGAGAAAATGACCGTAGAATC
AATTCTAGAGCGGCAAAAGATGGATAACGAGCATTTAATACAGGAGAAGAAAGAAATAGA
AGATAGGCACTCAAAAGCCGTATCTGAAAAAGATGCTCTTGCTAATGAGCG---------
--------------AGATNATGAAGGATCAGTTGGGCCTCTCGGCAAAGGCATACACTGA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
