>Amblygaster_clupeoides|047169|TR9791|c1_g1_i1|m.18179
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------CGCCGCTT
CAGCTGCTCGGTGTGCAGCCGGAGCTACAAGGACCCGGCCACGCTGCGCCAGCACGAGAA
GACCCACTGGCTCACAAGGCCCTTCCCCTGCAACATCTGCGGCAAAATGTTCACGCAGCG
CGGCACCATGACGCGCCACATGCGCAGCCACCTGGGCCTCAAGCCGTTTGCCTGCGAGGA
GTGCGGCATGCGCTTCACCCGCCAGTACCGGCTGACGGAGCACATGCGCGTGCACTCGGG
CGAGAAGCCATACGAATGTCAGCTGTGCGGCGGCAAGTTCACGCAGCAGCGCAACCTCAT
CAGCCACCTCCGAATGCACACC--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------TCCCCGTCA---------
----------------------------------TAA
>Corydoras_julii_viscera_mixture_8|002851|C1224890|m.27604
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------CCGGCTCTTGGCGATAACCTGTACGTCTGTATCCCTTGCGG
TAAAGGTTTCCCCAGCTCGGAGGAGCTCAATGCCCACGTGGAAACGCACACCGAAGAGGA
GCTTTATATCAAAGAGGAGGAGGACGACGCCGCCTATCCAAAGGAAGACGAGGCAGAAGC
CGAGAACTTGTCATCTC------AACCGGTCCAAAGACATGGCAACGACGCGCGCCGCTT
TAGCTGCAGCGTGTGCAACAAAAGCTACAAGGATCCTGCCACCCTCCGGCAGCACGAGAA
GACGCACTGGCTCACGAGGCCATTCCCGTGCAACATCTGTGGCAAGATGTTTACGCAGCG
TGGCACCATGACACGACATATGCGAAGCCACTTGGTCCTGAAGCCGTTCGCCTGCGACGA
GTGCGGCATGCGCTTCACGCGCCAGTACCGACTGACCGAGCACATGCGGGTCCACTCAGG
AGAGAAGCCTTATGAATGTCAGCTCTGTGGGGGGAAATTTACCCAGCAGCGCAACCTCAT
AAGCCACCTGCGAATGCATTCC--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------TCCCCAACA---------
----------------------------------TAA
>Distichodus_sexfasciatus_gill_4|015383|scaffold23094|m.26065
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------CTGAAGGACGAGCTGTCGGAGGACGAAGTTTTCACAGGG
AACACCCATGGCTCAGCCTCCGTCAACTCGCTCAGCCCCTCCACCAGCAAGAACGGAAGC
AACGGCCTCGCCAACAGCATCGGTGGGTGCGGCGGCCTCTTGGAGCTCGGTCTGGACCTT
TCCAAGAAAAGCCCTTCAGGGAGCACGGCCACCGAAGAAGTAAGTCCCAGCAGCATCCCG
CAGGAATCACCTCAGTCTGCCTCAGAATCCACAGCCAACAGTGCCTCGTTTGATGAGATC
GCCCCCAACCCTCAGAACCTC------GGAGAGCCCATGGAGCTTGGAGAGGGTGGAGAG
TGTGAGGAGGTCCAGCATCCTCCCGAATCCAAGCCACTCAGAAGCACCCGTCATGCCGCG
CGGCCGAGGCGACAGGCCAAGTGTGACATT------CTGAAATGCGAAGACGCTGAGCGC
GCCGCCTTGCCCAATGGCGTGGCC----------AAGAGGCTGAACGCTGTGACGGCTGG
GGAACGTCTACCGGACGGAGGTAATGCCACCTCAGACATCTACCAGTGCAAGGAGGAAGA
CGAAGCCCTGGAGAACGGCCAGAATGAGCAGAGCGAGGAGAGCGGCCAGAGCGAGAG---
---------------------------CGAAGGCGGCCGCAACAGCGCCAACTATGTGTA
CCGACAGGAGGGTTTTGAACCAGCACTGGGTGACAACCTCTATGTCTGCATCCCCTGCGG
TAAGGGCTTTCCTAGCTCGGAGGAGCTCAATGCCCACGTGGAGACCCACACTGAGGAAGA
GCTGTACATCAAAGAGGAAGAAGATGAC---GGTTATCCAAAGGAAGACGAGGCGGGGGC
AGAGGATCTCTCGTCAC------AGGCGGcgcaggcgcagggcggcgagctgcggCGCTT
CTGCTGTGCGGTGTGCAACAAGAGCTACAAGGACCCCGCCACCCTGCGGCAGCACGAGAA
GACCCACTGGCTGACCAGGCCCTTCCCCTGCAACATCTGTGGTAAGATGTTCACCCAGCG
GGGCACCATGACCCGACACATGCGCAGCCACCTGGGTCTCAAGCCCTTCGCCTGCGAGGA
GTGCGGCATGCgcttcacccgccagtaccgcctcaccgaGCACATGCGGGTCCACTCGGG
GGAGAAGCCCTACGAATGCCAGCTCTGTGGGGGCAAGTTTACCCAACAGCGCAACCTCAT
CAGCCACCTGCGAATGCATACC--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------TCCCCATCG---------
----------------------------------TAA
>Gasteropelecus_sp._gill_3|018101|scaffold29273|m.30732
ATGGAGTTGCCAAATCATGCCAAACAATTGCTGCTGCAGCTGAACCAACAAAGAGCCAAA
GGTTATCTGTGTGATGTGATTATAGTAGTAGAAAATGCCCTCTTCCGGGCACACAAGAAC
ATCCTGGCAGCCAGCAGTATCTACTTCAAGTCCCTCATCCTTCACGACAACTTGATAAAC
CTCGATACAGATATGGTCAACCCGTCAATATTTCGACAAGTGTTGGACTTTATTTACACT
GGCAAACTTTTGTCCTCAGACCAGGTCAGTGACCACAATTTTAATGCCCTTCTAACAGCA
GCAAGCTACCTCCAACTCCACGACCTGGCCGCCCTCTGCAGAAAGAAGCTGAAACGCAAT
GGACGATCCCTCCACAACAAACCTTCAACGCCTACCAATGGAAGAACTTCCAGGAACCAA
AGGTTGTCCTCTACGCCCGTCACCCCAAACCAAATTTCAGGGTTTAAAGACAGTGAAAAA
ACAAAGAGACAGGAAGAGTTACTTAAAGATGAGTTGTCGGAAGAAGAGGTTTTTGTTGGG
AATGCCCATTGCGCAGC------TAATTCTCTCAGTCCTTCTACCAGTAAGAATGGGAGC
AATGGACCTGTTAACAATA---------GTGGTGGCCTCCTGGAGCTTGGCCTGGACCTC
TCCAAGAAAAGCCCGTCAGGAAGCACAGCCACTGAAGAAGTAAGTCCCAGCAGCATCCCA
CAAGAATCACCTCAGTCTGCCTCAGAATCCACAGCCAACAGTGCCTCTTTCGATGAGATC
ACCTCCAACCCACAGAACCTCACTGGGGGAGAGCCTATGGAATTAGGTGAAGGGGGAGAA
TGTGAGGAAAGCCAGCATCCTCTGGACTCTGACCAGCATAAAGGCTCTCGCCACACAGCA
CGGTCAAGGCGACAAGCCAAGGGCGAGAGC------CACAAAGGTGAAGATGCAGAACGA
GCCACTTTGCCCAATGGAGTCTCC----------AAAAGGTTGAATGTGGCGAGCGGGGG
AAA---------------------------CTCTGATTGCTTCCAGTGTAAGGACGAAGG
GGAAGGCCTGGAGAATGGCCAG---GAACAAAGTGAGGAGAGTGGTCAGAGCGAGGG---
---------------------------TGAAGGTGGCCGCAACAGCACCAACTACGTGTA
CCGCCAGGAAGGCTTTGAGCCTGCCCTCGGAGACAACCTATATGTCTGCATTCCCTGCGG
TAAAGGCTTTCCCAGCTCAGAGGAGTTGAACGCTCACGTAGAGACCCACACTGAGGAAGA
ACTTTACATTAAAGAGGAGGAGGATGAT---GGCTTTCCAA---AAGATGAGGCAGAAGT
TGAGGACCTATCATCCC------AGACAGTGCAAGTGCATGGTGTGGAGACGCGCCGCTT
CTGCTGTACGGTGTGCAATAAGAGCTACAAGGATCCAGCCACGCTGCGGCAACACGAGAA
GACCCACTGGCTCACGCGACCGTTCCCCTGCAACATCTGTGGAAAGATGTTCACCCAGCG
CGGCACCATGACACGCCACATGCGCAGCCACCTGGGCCTGAAGCCCTTTGCCTGTGAGGA
GTGCGGGATGCGCTTTACGCGGCAGTACCGCCTCACGGAGCACATGCGAGTCCACTCGGG
GGAGAAGCCCTACGAATGTCAGCTCTGTGGAGGCAAGTTCACCCAGCAGAGGAACCTCAT
CAGCCACCTCCGAATGCATACC--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------TCCCCATCA---------
----------------------------------TAA
>Pantodon_buncholzi_mixed|008898|scaffold11278|m.14014
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------GCACCGGTAGCTTTCGGTGGTGAATCCCGTCCCTT
CAAATGCACTGTGTGCAGCAAGAGCTACAAGGACCCGGCCACCCTGCGGCAACACGAGAA
GACCCACTGGCTCACGCGGCCCTTCCCGTGCAACATCTGCGGCAAGATGTTTACACAGCG
TGGCACCATGACGCGCCACATGCG------NNNNNNNNNNNNGCCCTTTGCCTGCGAAGA
GTGTGGTATGCGCTTCACGCGCCAATACCGCCTGACCGAGCACATGCGGGTGCACTCGGG
CGAGAAGCCCTACGAATGTCAGCTGTGTGGGGGCAAGTTCACACAACAGCGTAACCTCAT
CAGCCACCTGCGTATGCACACG--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------TCCCCCTCA---------
----------------------------------TAG
>Sargocentron_rubrum_gill_6|007950|scaffold13783|m.15702
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------GGGACC---TTCGTGAAAGAGGAAGATGAAGAGGAGGC
AGAGGACCTCTCTGCCCCTGTGGGTCCCTCCAGCTTTGGTGGCTCTGAAACGCGTCCATT
CAAGTGTACAGTCTGCAGTAAGAGCTACAAAGACccagcaaCGCTGAGACAACATGAAAA
GAGCCACTGGCTGACCAGGCCCTTCCCCTGCAACATCTGTGGCAAGATGTTCACCCAGAG
GGGCACCATGACACGCCACATGCGTAGCCACTTGGGCCTTAAGCCTTTTGCCTGCGACGC
CTGCGGCATGCGCTTCACCCGCCAGTACCGTCTCACCGAGCACATGCGCATCCATTCCGG
GGAGAAGCCTTATGAATGCCAGGTATGTGGAGGAAAGTTTGCCCAGCAGCGCAACCTCAT
CAGCCACATGAAGATGCACAGCAGTGGGGGGGCCGGAGGGGGCCTGTCTGCCGATGGGAA
GCTGAAGCTGGACTTTACAGAGGGCATCTATCCTCTGAGTAAATACACAGCAGAGCACCT
GGGGCTGAAGCAGGAAAAGGCCAATGAGCTTCTAATCCAAGCCCAGCAGCACTTGGCTGA
TGCCAAGGCCATGGAGAGCCTCTACCCACTGTCCAAACTGGCCGCAGAGCACCTTGGCCT
CACCCACGACAAGATGGATGTCCTGGGCCAGACCCTGTCCCATCCCCCACAGCCGATTTC
TGAAGCCCGCACCATTGACCGCTACTCACCCAGCTAA
>Synodus_sp._gill_5|025823|scaffold9390|m.10550
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------CGACAAGTTGCT
CGCAAGAAGGAGTGGCCTAAGAGAGAAGCTTTAGTGCTGAAGTCTGGAGATGTTGA---C
AGACCCTTGGTCAACGGAGTGATTGTAGTGCCCAAAGAGGGTCGCAGTGGCAAGGGTGGT
GGAGGGGGCAGTGG-CAGTAGCTTTGCCTCTGATCAGTCCTTCCAGTTCAAAGAAGAGGA
GGAAGGAGGTGAGAACGGCCAG---GAGCACAGCGAGGAGAGCGGGCAGAGCGACGGAGA
GAATGGCGGGACAGTGGGAGGAGGTGCTGGAGGGAGCCATCACAGCGCCAACTATGTGTA
CCGCCAGGAAGGTTTTGAGCCAGCATTTGGAGACAACCTCTACGTCTGCATCCCCTGTGG
AAAGGGCTTTCCCAGCTCAGAGCAGCTCAATGCGCACGTGGAAACGCACACTGAAGATGA
GCTCTACATCAAAGAAGAGGGGGGCACC---TTCGTCAAAGAAGAAGATGAGGAGGAGGC
AGAGGATCTTTCTGCGCCTGTGGGTCCATCTGGATTTAGCGGTACCGAGCCTCGTCCATT
CAAGTGTACTGTCTGCAGTAAGAGCTACAAAGACCCAGCCACACTGAGACAGCacGAGAA
GAGCCACTGGCTGACCAGGCCCTTCCCTTGCAATATATGCGGGAAGATGTTCACTCAGAG
GGGAACAATGACCCGCCACATGCGCAGCCATCTGGGCCTCAAGCCCTTCGCCTGCGAGGA
GTGTGGCATGCGTTTC--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------
