>Amblygaster_clupeoides|030983|TR56618|c0_g2_i1|m.75841
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------AGACGCGCAGCCAAA
CTACTCAGCAAGCTCACGTTGGGTTCTTTCCTGTTGTCTATGTCCCACAGTGGTCAGGAG
GTGTGGGCGGGGGATAACCAGGGCCGGATCCACACCTTCTCCCTGCGACACGGAGAGCTG
CGAGCACTCACACACTTCCACGTGGGACACACACACCTGGTCACCGGGATACACTACTCA
CCTGGGAGCCTGTATACCTGCTCGTCAGACCGGACAATACGGGTCCATCTCCCTAGTGCC
CCCCCAAGGACTCTGTGCACAATGCACAACC------CAACGCCAGTGAACGGGCTGAGT
GTGGAGGCAGGGGTGTTGGCTGTGGCATCTGGGAACATGGCAG---------------TG
GAGGTCTGGAGACCACCCCAG---------------------------------------
---------
>Distichodus_sexfasciatus_gill_4|025607|scaffold5104|m.5407
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------ATGTCCTATAGTGGACGTGAG
GTGTGGGCAGGAGACAACTGTGGACTTGTCCACACTTTCTCTATGAACGAAGGTTCCTTG
AAGTCCATAGGCCAGTTCAATGTGGGCCACAAATGGATGGTGTCTGGCATTCATCACTCG
CCCGGCGTGCTCTACACGTGCTCTTACGATCGCACGTTAAAGGTCCACCTTCCCTGTGCA
CCCCCAAAAACACTTTATACACATCAGCTCCCAGGAAGAGGAGGAGTCAATGGGTTGACT
GTGGAGGCTGGAGTGCTGGCCGTAGCGCCTGGTGATGAGAATA---------------TA
GAAGTGTGGAGACCCAGACAG---------------------------------------
------TGA
>Gasteropelecus_sp._gill_3|023977|scaffold3703|m.3622
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------ACATTTATGACACCAGAGCTGCGGAGCCT
TTGGTCAAGAGCCTTTGTCACCATGGTGATGCTGTACTGTGCCTGGCCTCTGATGAGCAG
TACATT-----------------CTGTCTNNNNNNNNNNNNNNNNNNNNNNGCTGGGCGG
CTACTGAAAAAAATCCAGCTGAAATCCTACTTGCTATCAATGTCATACAGTGAACGAGAA
GTGTGGGCAGGAGATAACCGTGGACTTGTCCACACGTTTTCCATGAATGAAGGCTCATTT
AAGCCTGTTGCCCagttcaatgttGGCCACAGTTCATTGGTGACAGGTGTCCATCACTCA
CCTGGCACTCTCTACACATGCTCTTCTGATCGCACTATTAAGGTTCATCTCCCGTGTGCT
CCCCCAAAGACTTTGTGTACACTTCACCGTC------AAGCAGGAGTGAACGGGTTAAGT
GTGGAGGCGGGAGTGTTGGCTATAGCCTCTGGTGATNNNCTTGCTTCTGACTTCTGTCTG
GAGAGCCGTCTGTCCAATCAGAGGGATCGCCTTTTCAGTGTGTTATCGTGTGATGATGTA
ATCAGATGA
>Lepidogalaxias_salamandroides_Head_2|028901|scaffold8911|m.11649
GTGAACCTGTGGGACCTGCGGGAGGGCCCCCGGGGCGCGCTGCTGCGCACACTGGGGGGG
CAGGGCCTCTTCAGCACGCACCGCGGGTGGGTGTGGTGCCTGGCCGCCTGCGGCCCTCTG
CTGGCCTCGGGCTCCTTTGACAGCAcCGTGCGCCTCTGGGACCTGGGGGCCGGGGGTGCA
GGTCGAGGGCTCATCCAGGGCCGGGCCGCCTTCCTCTGCCTCTCCTACCAGACGGACGTG
CTTCTGGCCGGCTCGTACGACAAGAAGGTCAACGTGTACGACACCAGGGCGGCGGAGCCC
CTGGTGAAGAGCCTTCGTCTCCACGGGAACGCCGTGCTGTCCCTGGCCGCAGACGAGCGC
TACATCCTGTCTGGGAGCAAAGACCACACCGTGGCCGTGTTCGACCGCAGGGCGGGGAAA
CTGCTGCAGAAGGTCCAGCTGAACTCCTACCTGCTGTCCATGTTCTACAGCGACAAGGAG
GTGTGGGCCGGGGACAACCGCGGCGCGCTCCACACTTTCTCCATGCAGGCCGGCGTCCTC
AAGCGCCTGCCCCAGTTTGACGTGGGCCACACCTCGCTGGTCACAGGCATCCACCGTTCG
CCGGGCTCCCTG------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------
>Melanotaenia_praecox_viscera_mixture_8|001968|C419132|m.27134
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------TCTAAACAA
CTGATTAAAAGCCTCCGTCTCCATAATAATGCTGTAATGTGCCTTGCTGCTGACGACAAC
TACATTGTCTCTGGGAGTAAAGACTGCACTGTGGCTGTCTATGACCGCAGAGCAGGCAAA
TGCTTGAAGAAACTCGGGCTGAGCTCTTATCTGCTGTCCATGAGCCACAGTGGTTATGAA
ATCTGGGCAGGAGACAACAGAGGCATGCTCCACTCCTTTTCCATGCAGGCAGGGTCTTTA
AAGCTTTTGTCCCAGTTTGATGTGGGACACACAGCTCTGGTCACTGGCATCCACAGGTCC
TTAGGAAGCCTTTACACCTGCTCGTCAGATTGCACTGTCAAGATGCATATCCCTTGTGCA
CCTCCGAGGACTTTATATAGTCTGCAATATC------AGTCTGGAGTCCACGGGCTGAGC
GTGGAGGCTGGAGTCCTCGCCGTG------------------------------------
------------------------------------------------------------
---------
>Sargocentron_rubrum_gill_6|001792|C664694|m.44243
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------AAAGACTGTACTGTGGCCCTCTACGACCGCAGGGCAGGCAAA
CCCCTGAAGAAACTCCGGCTGAGCTCTTACCTGCTGTCCATGAGCTACAGTGGCAGTGAG
ATCTGGGCAGGAGACAACAGGGGCATGCTGCACACCTTCTCCATGCAGGCGGGGGTCTTA
CAGCCCCTGTCCCAGTTTGATGTGGGACACACCTCTCTGGTCACCGGCATCCACAGGTCC
CCTGGCAGCCTCTACACCTGTTCATCTGACCGCACTGTTAAGGTACATATCCCTTGTGCG
CCTCCAAGGACGCTATGCACACTACATCACC------AAGCTGGAGTCAATGGGTTGAGT
GTGCAGGCTGGAGTGCTGGCTGTGGCGTCGGGGGACATGTGTG---------------TG
GAGGTGTGGCGGCCTCGCAAA---------------------------------------
------TGA
>Synodus_sp._gill_5|017445|scaffold22908|m.30460
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------ATCTCTGGGAGCAAAGACCACACAGTGGCCATCTATGACCGAAGGGCAGGGAAA
CCTCTGCAGAAGCTCAAGCTGAGCTCCTACCTGCTGTCCATGATGTACAGTGGCAGCGAG
GTGTGGGCCGGGGACGACATGGGGATGCTGCACACCTTCTCCCTCCGCAGCGGGGTCCTG
AAGCCCCTGTCCCAGTTCGACGTGGGACACACCTCCCTGGTCACGGGCATCCACCGCTCC
CCCGGCAGCTTGTACACCTGCTCCTCAGATCACTCCATCAAGGTGCATCTACCGTGCGCA
CCCCCCAGGACTCTGTGCACGCTGCGCCACC------AGGCAGGGGTCAACgggctgagc
gtggaagccggagtcttagccatagcctctggcgacatgTGCG---------------TG
GAGGTGTGGCGGGCCCGCAAG---------------------------------------
------TGA
