>Amblygaster_clupeoides|005166|TR15103|c4_g1_i4|m.28990
TCCTCCTCTTCCTCCTCCTCTCCAACCACCAGCCTTTCTTTCTGCTCCTCATCTGTACAC
CTGAGCTCTGCGCCTCTCCCTACTCCTCCCCTGTCCAGAGCTGGCCACGACGCCATCTCG
AATGGCCATTCGCAGCAGCCGGACTTTCATGGGTCGCTCCCAGTGGCTCTCAAGCAGGAG
CCGGGCGACGAGTTTCCTGCGTGCAACCAGGCGCTCTTTCACCTGAAGCACCAGGAGGAT
CGAGGGAGAGCGCATCTCAGCCAGGAGCCCCAGCGTCGGGCGCCATACACCTCCTTACCC
TCACCACACAAACGCCGCCATTCCCACCAGTGTACGCCCATAGACCTCAAGGACCACTGC
GCCATGACCTCCAGACACCCCCAGGAGCCCCAGGTCCAAGCCAAGATGGCCAGTGGTGGG
GAAGGGGGTGAGGGATGCGGCACGTCCCTGGGAGACGAACAAGCCTGCCAGTGGCTGGAC
TGCTGCGCCTCCTACAAGCAGACAGAGGAGCTGGTGAGGCACATTGAAAAGGTTCACGTA
GACCAGCGGAAAGGCGAAGACTTCACCTGCTTCTGGGCCGGCTGTGTGCGCCGCTACAAA
CCCTTCAATGCTCGCTACAAGCTCCTGATCCACATGAGGGTCCACTCGGGGGAAAAGCCC
AACAAGTGCATGTTCGAAGGCTGCAGTAAGGCTTTCTCTCGCCTGGAGAACCTGAAGATC
CACCTGCGGAGCCACACTGGGGAGAAGCCCTACCTATGCCAGCACGCTGGCTGCCTCAAG
GCCTTCAGTAACTCAAGCGACCGGGCCAAACACCAG---CGCACACACCTGGACACGAAG
CCTTATGCCTGTCAGCTGCCTGGATGCACCAAGCGTTACACAGATCCCAGCTCTCTGCGC
AAGCACATCAAAGCC---CACGCAGTCAAAACGCAGCAGCTCCGAGAC------------
------------------------------------------------------------
---CAGGCGCTGTTGTGCTCTGAGGTGGAGACAGACTGCATGAGCGAGTGTCTGGCACTG
CACTCCCTCCTCAGCGCCGCTCCCTCCCTTCTCGAACC------------------CGGC
TCCCCTGTGGCTGGGGGCGCCG-----CTGGGCCCCTCTCACAGCCTTGCCACAGCTCCT
TCCCAGGAGCGGAGAGTTTCTCTGATGCCAGCATCATCCCTTTATCTGAGGCCCTGGCCA
CACCCCCAGACCTGCCCCCCACACCATGTGACCTCCAGCCTCATAAACTAGCCCTCATGT
CTGCCGGCAGGAGCCTGCAGGACAGATTCCACTCTTCACTGATGCTTCGAGGCCAAGGGG
AGCCATTGGCCCATTCCGACAAGTTGGGGGTGTCGACGGGCCAGAGTAATCAGAAACACG
AGGGGCTCTATCCTGACATCCTAGGATCCTATCATGACTTCCATTCTGGAGATGTCAGTC
TTTTAGAGCATCTTGCCAGTGAAGGCTCCGGGGGGCTGCATCTGTTTGAGCCTGGTGGGT
ACCTACTTAACGCCACCTCAACAGCACCCTCTACAGGCTTCAGTGGGCAGGAAAACCAGG
CATCAGGAAGCCATGTGTTTCCCCCTTTTCAGAGGAGGGTGACGCCTCAGATATGTCTGT
GA
>Distichodus_sexfasciatus_gill_4|012355|scaffold18498|m.20385
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------GAGCACAT----------------
--CCATGGGGAGAAGAAGGAGTTTGTGTGCCGCTGGGAGGAGTGCTCCAGGGAACAGAAG
CCCTTCAAGGCCCAGTACATGCTGGTGGTGCACATGCGCAGACACACGGGGGAGAAGCCA
CACAAGTGCACGTTCGAGGGCTGCTCGAAGGCGTACTCCCGCTTGGAGAACTTAAAAACA
CACCTGCGCTCTCATACGGGTGAGAAACCCTACGTGTGTGAGCATGAGGGCTGCAACAAG
GCCTTCTCCAACGCCTCGGACCGGGCCAAACACCAGAACCGCACACACTccaaCGAGAAG
CCGTACGTGTGTAAGATCCCCGGCTGCACCAAGCGCTACACGGACCCCAGCTCCCTCCGC
AAACACGTCAAAACCGTCCACGGCCCCGAGGCCCACATCACCAAGAAGCAGCGCGGCGGC
GGAGCAGGAGGA------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------GGAG
GA----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--
>Lepidogalaxias_salamandroides_Head_2|016938|scaffold14988|m.19939
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------GTGAGGCACATCGAGAAGGTGCACATA
GACCAGCGAAAGGGGGAGGAGTTTGCCTGCCTGTGGGTGGGCTGCGTTCGCCGCTACAAG
CCATTCAACGCCCGCTACAAACTGCTCATCCACATGAGGGTCCACTCGGGAGAGAAACCC
AACAAGTGCATGTTTGAGGGGTGTCAAAAGGCATTTTCTCGTCTGGAGAACCTGAAAATT
CACCTGAGGAGTCACACAGGTGAGAAGCCCTACCTGTGCCAGCACCCGGGCTGCCTCAAG
GCTTTCAGCAACTCCAGCGATCGAGCCAAGCACCAG---CGCACACACCTGGACACGAAG
CCCTATGCTTGTCAACTGTCAGGATGCAGTAAGCGATACACAGACCCAAGCTCCTTGCGT
AAACATGTGAAGGCT---CACTCCACCAAGAGCCATAGGAACCAGGAGGACTACAGGGAC
CAGGAGAGACATAAAGACCAGGAAAGACATGAAGACCAAGAAAGACATGAGGACCAGGAG
AGTCAGGTGCACTCACAATCTCAATTGGCTCCCGACGCTCTCAGCGATTGTTTGGCCATT
CAGCACCTCCGTTGCTCCGCCCTTTCTCCACGGGAACCAATCTGTTGCAGTGGGGGCGGG
TCTCCCGACATGGGGCAGGACAATTCAGCAGGGAGTTACTCCAACTCCTCTATCCCACAG
AGGAACACTACTTCTGGGCTTCTGCCTCTCACTCTAGACCCCTGCTCCGGAG----GCTT
AGGCCTG---------------------AGTCACCTACTGACACAGCTGAGCC-------
CAGGGAGGAGCAG------AGAGAGGTTCCTCTCTCCGGTGACCAGCCCGAGCCCCAGGG
GGCC--------------------------------------------------------
------------------------------------------------------------
------------CGCCCAGCACG-------------------------------------
--CCACCTACCCCCACGGCAATGACCC-------------------------AAGCCAGG
-ACCAC------------------------------------------------------
--
>Pantodon_buncholzi_mixed|003886|C625990|m.35067
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------CC
AACAAAT-----TTTGATGGCTGCCAGAAGGCCTTCTCACGACTGGAGAATCTGAAGATC
CACCTTCGTAGCCACACTGGAGAGAAGCCTTACCTGTGCCAGCATCCAGGCTGCTTCAAG
GCCTTCAGCAACTCCAGCGACCGTGCCAAGCATCAG---CGCACGCACCTGGAGACGAAG
CCGTATGCATGCCAGATCCCAGGCTGTTGCAAGCGTTATACAGACCCCAGCTCTCTGCGT
AAACACGTCAAGGCT---CATTCTGCCAAGGAGAAGCAGGCCAGGAAA------------
------------------------------------------------------------
---AAGCTGCGCTCCAGCATGGATGTGGATCAGGAGGGGCTTTCAGAATGTCTAACCATC
CATCCCCTGC---AGCCCAGCCTTCCTCCACTGGACCCGGGCGATGGGACTACAGGCTCC
TCTTCTGGGGCAAGTTGTGACCTTTACACAGGCG-----TGCTGTCCGGCAGCCAGACTC
TTACAGCCCAGCCAGGGCACCTTTGTGCCAGCACCTCCTGTTTGCC--------------
AACTCTGGAGGACAGCAGCAGATTTGCCAACCTCTCCCCATATCATCTCAGTC-------
CTGGGCG------------GGATGATCTCCCCACTACAACTCTCAACCACCAATCCTCAG
CATC--------------------------------------------------------
------------------------------------------------------------
-------------TCCCAGTA---------------------------------------
--ATACCTGCCCACCCCTCAGCA-------------------------------------
---CATGTAGCGATGTGACTGCGTCTC--------------ACGCCCCA-----------
--
>Sargocentron_rubrum_gill_6|024587|scaffold9048|m.10216
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------GGCTGCGTGCGGCGCCACAAG
CCCTTCAACGCCCGCTACAAACTGCTCATCCACATGAGGGTCCATTCTGGGGAAAAGCCC
AATAAATGCATGTTCGAGGGCTGCTCCAAGGCGTTTTCGCGTCTGGAGAACCTGAAGATC
CACCTGAGGAGCcacacaggagagaaaccctacatctgccagcaccccggctgcctcaag
gccttCAGCAACTCCAGCGACCGGGCCAAACATCAG---CGCACCCACCTGGACACGAAG
CCGTACGCCTGTCAGATCCCAGGATGCACCAAACGCTACACGGACCCCAGCTCGCTACGC
AAGcacgtcaaggcc---cactccgccaagGGGCTGCAGGAGAGGGAC------------
----------------------------------------------ATG-----------
---AAGGTTCAAGTGCACTCCATGCTGGAATCTGACATGTTGACTGATTGTCTGGCGAGG
CAGCATCTCCACAGCTCGGCCGCCTCCCACCGAG------------------GAAGCGCC
TCGCCTGTCCCGGGCCTCGACGACTTtacaggcgcgtactgcaacaccggcaCCGTCCAC
AACAGGCTGGGTTCAGACTTTCTCCCTCCATCTGCGGACTCCTGCTCCAGGT----ACCC
GGGCTTAGAGGGAAACTTCAGCGCCAACAGCCCTCTGTCTTCACTAACGAGCC-------
CAGGGAGCATGAGAGAGGGGGACAGACTGGCATCGTCATTCGTGCCC-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--
>Scleropages_formosus_red_gill|012766|scaffold19375|m.25259
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------ATGCTGGTGGTGCACATGCGACGGCACACGGGTGAAAAGCCA
CACAAGTGCACCTTTGAGGGCTGCTCAAAGGCCTATTCCCGTCTCGAGAACCTGAAGACT
CACCTGAGGTCCCACACGGGCGAGAAGCCGTATGTGTGCGAACACGAGGGCTGCAACAAG
GCCTTTTCCAACGCGTCTGACCGAGCAAAGCACCAGAACCgtacccactccaacgagaaa
ccatatGTGTGTAAGGTTCCCGGGTGCACAAAGCGTTACACGGACCCCAGCTCTCTCAGG
AAGCACGTTAAAACCGTTCACGGCCCCGAGGCCCACGTGACCAAGAAGCAGCGCGGTGAC
GCGACCCCTCGGT-----------------------------------------------
-----------CCCAGCCTCCCAGGGAAGGCAGGGGCAATGAGGCCAGCATCGAGCGGAC
CGG---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
CAAAGGACGGGGGGAAAAATTAGAAGGCAACGGCGCCA--------CCAGAGGCACGGAG
GACTGCTTGC--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------AGGTCAAG
--------------------------TCGGTAAAGACGGAGAACTCTGGGATGTATCGGT
CC
>Synodus_sp._gill_5|001818|C531395|m.42510
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------CACAT----------------
--CCACGGGGAGAAGAAGGAGTTCGTGTGCCACTGGAGGGAGTGCTCCCGGGAGCAGCGG
CCTTTCAAAGCCCAGTACATGTTAGTGGTTCATATGCGGCGCCACACGGGGGAGAAACCG
CACAAGTGCACTTTCGAAGGCTGTAACAAAGCCTATTCTCGCTTGGAGAATTTAAAGACC
CATCTGCGCTCTCACACTGGGGAGAAACCCTACGTCTGTGAGCACGAAGGCTGTAACAAG
GCCTTCTCCAATGCTTCTGACCGGGCCAAACACCAGAACCGCACCCATTCCAACGAGAAA
CCCTACGTGTGCAAGATCCCAGGATGTACGAAGCGTTACACTGACCCCAGCTCCCTGCGT
AAGCATGTCAAGACCGTCCATGGCCCAGAGGCCCACATCACCAAGAAGCACCGCGGCGAC
ACTGGCCCA---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--
