>Amblygaster_clupeoides|001073|TR10889|c1_g1_i1|m.20480
------------------------------------------ATGGCAGATCCTAGTATG
ATGAGCCTTTTTGGAGATGATGGTAATCTATTCTCAGATGAAC---TAGAGAGTCTGGGG
GACTGTGGT------TACCCACCACAGGCCCAAGCCAACTCTATGGGCCCTGCCA-----
-------TGGGTCATGATCATCAAGCTTACGGATCACTCTCCTCCAACATTCACATGCCT
CCACAAGCTGTTCCTGGCCAGGCAAAGCTAGGACCACCTCCAACCCACCACTATGACCAT
TTCAGCCAATATGAGCAG---------------------CCACAGAGTGGCCGCATGCTG
GCC---------------------------------AATGGCCCTGTTAATGGCATGTCC
TCCCCTCAGTCCCGCTACCACTCTGCATCTACAGCACCT---------------GCACCA
CCTGGACACCATGGCTATCCAGC-CCCACAAGGTGATGCCCGAGCCCAGGCTTTTGGTGA
TGGGGGTGGCGGTACCTGGGGTCCCACACCTCAAGTAGTGCAGGTGACAGAACAGGGCCG
CCCCCCGTTCCAGTCTCAGCAGCAGCAACAACA--------AGCAGCCCA------GACT
CAACATGGAGGCTCTGGCG---------C------TCAAGGCCATGGAGGACATCAGATG
GGCCCATAT---ATGGGCCACAATGACTACACAATGCCAGCTCATGGACAGACACAGACT
CCTCCTCGGATGAACC------ACTTTCCCCAGAGCTTAC------------CACAGGAG
C------------------CCAGTCACTTCATGGGCCATGTTGGCCTCCAACAGAGTTC-
CAATATTGCTGGACCCCCAGGGGCACCCCCCATGAGACACCCTGCCCAG-----------
----CAGCCTTCAAGGCACCCACAG---CCCCCACAGCAATTCCTCCACAGACCCAGCCA
GGCTGGGCATCGGCCTGACACTGTACCTAGTGCTCATAACACTCAATATCCACCCAGTCC
CTCAAGGCAGCAGCAGC------------------------CACAGCAACAACAGGTGAT
TCCTGGAAGAGCCCATCCCAACATGGGCTATAACATGCACAGCCAGCCTGTGACTCCAAA
CACTGTAACCAGCTCAGGACCGTACCCTCCCTACCCTCCATACGGCAACCTTAATCAGGG
ATTAGCCAACCCTTCAGGGATGAGTCCCAGCATGAGCCTTAACACCAGCAG---CAGCTA
TCCTGCCCAGGGTGGCCCACCACCCCAGCAACCTAGATACCCGCCCACTGGCGGGG----
-----------------------CCCAGCAGGGACCAATACACCAGCAGCAGCAGTCTGC
TCTCCACCAGATTAACCAAATGAATGCTCAGCCTATGCACCCAGGCCAGAACTCCACTGC
AGCCCAGCAGAAGCAACAGCATCT---------GCCTCCACCTCAGGGATCCTACAGTTC
GCCCCCCTCAATGTCACCCATGAGGAACATGAGCACTCCTGCTGGCACACCTCCTCCCCC
TCAACATAGTCGCCCTTCCAGTGCAGGCCTCGGTCCAGACATGGTTGCTGCAGGTGGTTA
TGCTGGTGTCCCTCAGAGTGCAGCAGGCAACATGTCACTCCCTCAAAGGG----------
--------------TCCAGCAGATGCCCCACCCTCAGCAGCAGCAA------CTCCCCAC
ACAGGTGTACAACCCTCTGTCGCCCAACCACAGA---------GCTCAGGGCCGAACCGC
AAACCCCAGCCATGAGCTGCCTCCCCAACAGGGCCAATCAGACCAGCGACTGCTTTCTCA
GCAACCCCAGAGAGTGGGGCCACAGCTGCAGTCACCTCCAATGCCTTTCCAGCAGCAGCA
GCTGCAGCAGGTGTGCCCCCCTTCTGCTGCACTGCCCCCACCCCAGCAGACACACCTGGC
TGCCATCCATCAGAACTCTCCTCCCTCTCAGCAG---CCTTGGGCACAACCACATCAGTC
AGCTCCACCCAGCCAGAAAGTGCCTCTAATGCAGCATTCCCCATCAGAGCCTCCAGTAGA
GATGACCACACCCAGTGGGCCACCCACCTCTGGCTGTGGCCCTAGCCCTCAGCCAACCAA
CTGTGACCAGCAGCAGATGGAAAGCAACCAGAAGCCAAAAAAGAAAAAGAAGAAGAAAGC
CAAGGTGAGTGAGGAGGAGGACATAGAGAGTATGGAGAAGGACACTGAGGGTGTGGTGGG
CATAGATGCA------------TCCCAGCCCCACCCGGCACAGAAGAAGAGTAAGAAGAA
ACCAAAGGAG---------AAGGAACCCAAGGAGCCCAAGACTCCCAAAAC---------
---------------------------ACCCAAAGAGCCCAAGGAAAAGAAGGCTAAGGC
AACCACCACTCCTAAACCGAAGAGCTCCAAGAAGCAGAGCATGAAGAAGTCCGATTCTGA
CAGTGGTTTGGCCAGTAAGAAGGAGGCCAAGCGGAAGAGGGAGCCATCTGTCACCTCGGA
CGTGGAGAAGACCCCACCTCCCTCTCCT----------------TTGGTTTC--------
---------------------------------------T
>Corydoras_julii_viscera_mixture_8|002419|C1218968|m.27023
------------------------------------------ATGGCCGACCCCGGGATG
ATGAGCCTCTTCGGAGATGATGGGAATTTATTTTCCGACGGTC---TGGAAGGCCTCGGG
GATTGCGGC------TTCTCCTCCCAAGTCCCGGCGAATCCGATGAACCAGCAGA-----
-------TGTCCCACGAGCACCAAGCTTACGGCGGG------------ATCCACCTTTCC
AACCCGTCTGTCGCCACTCAGCCCAAAATGGG------------TCACCATTACGACCAC
TACACTCAGTACGAC------------------------CCCCAAGGCGGCCGGATGATG
GCC---------------------------------AACGGGCCGGTTAACGGGATCTCG
TCGCCCCACTCGCGCTACCACGGT---------------------GGAAACGGGACCAGC
GCGGGGCATCACGTGTACCCGGG-AGCGCAGGGAGACGCCAG----------------GG
GAGGAGCGGCG-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------
>Distichodus_sexfasciatus_gill_4|008336|scaffold11914|m.12752
------------------------------------------ATGGCTGACCCAGGAATG
ATGAGCCTCTTCGGAGACGATGCAAACCTGTTCTCCGACGGGCTCGTCGAAGGTCTTGGG
GACTGTGG---------CTATCCCCAAGGCCAGGCCAACCCCATGAACCAACAGA-----
-------TGCCCCACGAACACCAGGGCTACGGGCAGCTGCCCTCATCCCTCCAC------
---------GTCGCAGGGCAACCGAAGATGGG------------CCATCACTACGACCAC
TTTGGCCAGTACGAGCAGCACAAGATGCACCCAATGGAACAGCAGGGAGGCCGGATGATG
GCT---------------------------------AACGGCCCCGTCAACGGCATGTCT
TCCCCTCACTCGCGGTATCACGGCACGCCCGTGGCCCACTCCGGAGCAGGCGG------A
GGGGGGCACCACGTCTACCCTGG-GGCACAGGGAGATGGGCGAAGCCAACAGTTCGGAGA
CGGGGGAGGCC---CCTGGGCTTCC------CAGACCATGCAGGTGCCCGAGCAGGGCAG
ACCCGCCTTC------CAACAGCAAGGGCAGCC--------CCCAGCTTC---TGCCCCT
CACCAGCACGGCCCTGCCGGAGGACCACC------ACCAGGGCATG---GCCACCAGATG
GCACCCTAC---ATGGGCCGCGGCGAGTATGGCATGCAGGGACACAACCAGACGCAGACT
CCTCCCCGAATGAACC------ACTTCTCCCAAGGCATGCCA---------GCGCAAGAT
G------------------CCAACCATTTCATGGGCCACGTGGGCATGCCACAGAACCC-
GGGGATGGCCGGGGCGG------------GCATGCGCCACCCAGGGCAGGCCCCCCCACA
ACAACAGCAGCAGCAGCATCAGCAGCCTCCTGGCCAGCCCTTTCTTCACCGAGGAGCCCC
AGGCCCTGTGCACCCAGAATCCGTGGCCGG---CCACGGGTCGCCGTTCCCACAGAGCCC
GTCGaggcagcAGCAGC------------------------AGCAGCAGCAACAACAGAT
GGGTGGAAGGACCCACCAGAACATGGCATTTAACATGAACAGCCAGCCAGTCTCCAGCAA
CAACGTCAACAGCTCAGGGCAGTACCCGCCCTACGCTTCGTACGGCAACCTCAATCAGGG
ATTAGCCAACTCTTCAGGGATGAGTCCCAACATGAGCCTTACCACCACCAGCACCAACAG
CAACAACGCAGGCGCCTCCATCACTCAGGCGCAGCGGTACCCCGGCGCCGGGGGGGCCCC
ACAACGGTATCCGGCATCCGCCGGCCAGCCGGGAGCCATGCACCAGCAGCAGC------C
CTCTTTACACATCAACCAAATGCCCCCTCAGCCTATGCACCCGGGGCCAAACCAGCCTCC
AGCCCAGCCGAAGATGCAGCAGCAACACCTCGGCCCACCGCCTCAGGGATCCTACAGCTC
GCCCCCTTCCATGTCGCCCATGCGCAACCTGGCAACCCCCACGGGCA---CTCCTCCACC
CCAGCNNNNNNNNN----------------------------------NGTTGGTGGTTA
CGCCGGCGTTCC------------------CATGGCGCATTCGCAAAGGGGGCC------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------GGTGCCCATGA-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------
>Gasteropelecus_sp._gill_3|005626|C956939|m.51231
CACGTTCCCTGTCCTGACGCACAGCCGCTCCGGCGTGCCGCCATGGCCGACCCGGGCATG
ATGAGCCTCTTCGGAGACGA---GACCCTGTTCTCCGACGGGC---TCGAGAGTCTGGGG
GACTGTGG---------CTACCCCCAAGGCCAGGCAAACCCCATGAGCCAGCAGA-----
-------TGACCCACGAGCACCAAAGCTATGGGCAGCTCCCCTCGTCTCTTCACCTCTCC
ACACCGGCTGTGGCCAGCCAGCCCAAACTCGG------------ACACCACTTCGACCAT
TTCGGCCAGTATGAGCAACACAAGATGCATTCGATGGAGCAGCAAGGGGGTCGGATAATG
GGA---------------------------------AACGGCCCCGTGAACGGCATGTCG
TCCCCCCATTCGCGGTACCACGCCGCCCCGGTTACCCACAGCGGCGGACCCGGGACTCCG
GGAGGACACCACGTCTACCAAGG-CGCACAAGGAGATGGACGGGGCCCGTCGTTCCCAGA
CGGCGGCGGCG---CCTGGGGCCCG------CAGGCCATGCAGGTACCCGAGCAGGGCCG
ACCGCCTTTC------CAGCAACAG-----------------CCGGCTCAGCCGTCGCCT
CATCCGCACGGCCCTGCAGG------ACC------ACAGGGCCACG---CCCACCAAATG
GGCCCCTAC---ATGGGGCACGGAGACTACAACATGCAAGGCCACACCCAGACGCAAACC
CCCCCGAGAATGAACC------ACTTCCCCCAAGGCATGC------------CTCAGGAG
T------------------CGAACCGCTTCATGGGTCACGTGGGGCTGCCACAGAATCC-
CAACCTGGCCGGGTCTG------------CCATGCGCCACCCGGCACAGGC---------
------GCCGCAGCAGCATCAGCAG---CCCGGCCAGCAGTTCCTCCACAGAGCGGCCCA
AGGCTCCGTCCACCCGGACGCCGTGGCCGG---CCATGGCTCGCCGTTCCCTCAGAGCCC
GTCTCGACAGCAGCAGCCGGGGCAGCAGCCGGGCCAGCCGGGGCAGCAGCAGCAGGTCAT
GGGTGCCAGACCCCACCAGAACATGGGATTTAATATGAACAGCCAGCCAGTCTCCAGCAA
CACTGTAAACAGCTCAGGGCAGTATCCTCCCTATCCTCCCTACGGCAGCCTTAATCAGGG
ATTAGCCAGCGCTTCAGGGATGAGTCCCAACATGAGCCTTACCACCAGCAG------CAA
CAGCAACCCCGGTGCTCCTGTGGCCCAGGTGCAGCGCTACCCGGGCCCTGGGGGGC---C
GCAGCGGTACCCCGCACCTGGGGCCCAACAGGGACCAATGCACCAGCAAC----------
--CCCATCATGTGAACCAAATGCCCCCCCAGCCTATGCATCCAGCGCAGAACCAACCCTC
GACCCAGCCGAAACTGCAGCAG---CACCTCGCCCCTCCGCCTCAGGGATCTTACGGCTC
TCCGCCTTCCATGTCGCCAATGAGGAACATGGCCACCCCTGCGGGCA---CTCCGCCACC
CCAGCAGGGGCGCCCTCCCAGCGCGGGCCTGGGGCCG---------GATGTGGGTGGCTA
CCCCGGCGTTCCACACCAACCCCAGGGTCCAATGGCCCACCCGCAGAGGGGGCCAGCTCA
GCAGCACCCGCACCCCCAGCAGCTCTCCCACCCCCAGCAGCACCCGCACCCTCCTCCCAC
ACAGATGTACGCGGCCTTGTCGCCCAACCACAGGGGCGCGGGCGCTCAAGGAAGACCCAG
CAGCCACGCGGACGCGCCGGCC---------------------------CTGCTCTCGCA
GCAAGCGCCGCGGCCCCCGCAGCAGCTGCAGGCGCCCGCCATGCCTTTC------CAGCA
GCTGCAGCAGGTGCGGACGCCTCCGGCTCCGCCCGCCGCA------CAGGTGCACCTGGC
GCCGCACCACCAGGGCTCCCCGCCGCCGCAGCCGGGCAGCTGGGTGCCCGCGCACCAGTC
ACCTCCAGCCAGCCACCAAGTGCCTCACATACAGCATTCCCCATCAGACCCCTCTTCAGA
GATGACCGAATCCAGCAAGACAC------CTGGCTCGGGACAGGACCCTCAGCCCGGCAG
CTGTGACGCACAACAGATGGAGAGCGAGCAGAAGCCAAAAAAGAAGAAGAAGAAGAAAGC
TAAGGTGAGCGAGGACCAGGAAGGGGAACACAAGGTCACCCAGCCGGACGCCGCAGGAGG
CGGAGAGGCAGGGCTGTGCCCCCCTGACCAGCCTCCTGTTCAGAAGAAGAGCAAGAAGAG
ACCAAAGGAGAAGGAGGCTAAGGAACCGAAGGAGCCCAAGACTCCCAAAACGCCCAAGAC
TCCCAAAACGCCCAAAACACCCAAAGAACCTAAGGAACCTAAAGAGAAGAAGGCCAAGG-
--CTGCCACTCCGAAGCCCAAGAGCGCCAAGAAGCCCAGTGCTAAGAAGGCAGAGTCGGA
GAGC------ACCGCCAAGAAAGACGGCAAGCGCAAGAGGGAGTCCTCAGTCACCTCGGA
CACGGAGAAAACTCCTCCCCCATCGCCTGAGGAAGAGGATGATGATGGTGTCCAGAAAAG
GCGCTCGAGCCGGCAGGTGAAGAGGAAGCGCTACACGGAA
>Melanotaenia_praecox_viscera_mixture_8|007720|scaffold11790|m.10728
------------------------------------------ATGGCGGACCCAGGGatg
ttgagcTTATTTGGGGATGATGCAGGGCTGTTCTCAGATGGAT---TAGATGGTTTAGGA
GACTGCTTTCCTCAACAACCAAACCCTGGCCAAGCCAACCCTCTGGCCCAGCAGACCAAT
CCCTCTCTGAACCATGAGCACCAGGGAAATCGGGGTTACCATCAGGGGATGATCCATGGT
GCTGGGCCTGGCCCCGGACAGCCTAAATTGGGA------CAAATGTACGACCCTGGCCCC
TTCACAGGATATGATCAGtCT---------------GGTGCTCCTGGAGGACGAATGATG
GCCCAGAATGGTCCTAGCCAAGGGCCTGCAAATGTGAACACGGCCATGAATGGCATGGCT
TCCCACTACCATAATAACCCAGCTAACCCTAGTAACCCT---------------------
------CACCTTGGGTACCAGAGTGATGCTGGGGGAGGAGGG-------------GCAGG
TGGAGGTGGAG---TTTGGGGCCAA-----------------------------------
----------------CAACAGCAG-----------------------------------
-AGTAGATCAGCATATCAGCAG--GCACC------ACCAGGTGGCAGCCCTAACCAGATG
GGTGGCTACCAAATGTCTCAAGGCAATTATGGTGGAATGCAAGGTCCACCTACATCCAGT
GCAGCTCGCATGAACCAACACTACCCTCAACAGAGCATGGCTCCCCCTCCTGCTCAGGAC
C------------------CATCTCACTACTTGGGACATGTTGGGATG------------
GGAGGATCCCAG-------------------------------------AT---------
GAGACACCCCCAGCCTCAGTCACAACC------CCAGGGCTTCCCCAACATGAC------
---------------------------------TCACACACCCCGATACCCACACTCCCC
TTCCAGACAGCCTCCAC------------------ACCCCCACCAGCATCAACAGGGC--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------
>Pantodon_buncholzi_mixed|016075|scaffold18788|m.26714
------------------------------------------ATG---------------
----------------------------------CATGTGAGC-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------GCCTCCCCAGGTAACGGCATGTCC
TCCCCACACTCCCAGTATCACAAC------------------------------------
------CCTAGTGTCTACCCAGG-AATGCAGGCAGACCGTCATGGCCAGCCTTTCATGGA
TGGTGGCTCCA---TGTGGGAGCCC------CGTGCCGTGCAAGTGCCCGACCAGGTCCG
GCCTCCATTT------CAGCAGCAG-----------------------------------
--------------------------CCC------TCAGGTCCAT---------------
-------AC---TTGCCCCGGGGTGACTACTCCATGCAGCCGCACAACCAAGCGCCCACT
CCTCCCAGGATAAACC------ACTTTCCCCAGGTGTTGC------------CACAGGAA
GGTGGCCGAGGGCCCTCCAGCAACCATTTTATGGCTCACATGGGCACCCAGCAGAATGCA
GGAGAATGCTGGCGACA----------------ACATCCCCCAACTCAGCA---------
GCAGCAGGCTCAGCAGCAACAGCAACC------GCAGCAATTCCACCACCGCCC------
---CCCCATGCACCCGGAGGCGGTCGT------GCACAGTCCACGCTTCTCACCGAGCCC
CTCGCAGCAGCAGCAGC------------------CTCCCTCGCAGCAGCAGCC------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------ACCGCAACAGC-------------------------------------
--------------------------------------------------------CACC
ACAGC-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------AAACGGCAGGGAGGCCC---------------
------------------------------------------------------------
----------------------------------------
>Sargocentron_rubrum_gill_6|017605|scaffold26331|m.34302
------------------------------------------ATGGCGGACCCAGGGATG
CTGAGTTTGTTTGGGGACGACGCAGGGCTGTTCTCAGATGGTT---TAGATGGTTTAGGA
GACTGTTTTCCTCAGCAGCCTGCCCCAGGCCAGCCCAACCCTCTAGCCCAGCAGACTAAT
CCCTCTCTGGGCCATGAGCACCAGGGTGCAGGGGGTTACCACCAGGGGCTGCTCCACGGC
GCCGGACCCGGCCCGGGGCAGCCTAAACTGGGG------CAGCTCTACGATCATGGCCCG
TACACGGGCTACGATCAACCT---------------GGGGCGTCCGGGGGAAGAATGATG
GCCCAGAACGGCCCCAGCCAGGGGCAGCCAAACGTTAACGCGGCCATGAATGGCATGTCC
GCCCGCTACCACAACAACCCCGCTAACCCGGGCAACCCT---------------------
------CACCATGGTTACCCGGGTGATGCCGGGGGAGGAGGG----------------GG
TGGGGGTGGTG---TTTGGGGCCAG-----------------------------------
----------------CAGCAGCAGCAGCAACAGCAGcagcaacagcagcagccgcatca
gtcCCGAGCGGCCTATCCGCAG--CCTCCGTCGCAGCCAGGGGGCGGACCCAACCAGATG
GGAGCCTATCAGATGTCACGGGGCGACTACGGCGGGATGCAAGGGCCGCCCGCTCCCAAC
GCAGCTCGTATGAACCAACACTACCCTCCACAGAGCATGGCGCCCCCTCCTGCTCAAGAC
C------------------CAGCTCACTACCTGGGGCATGTTGGGATG------------
GGGGGGTCCCAG-------------------------------------AT---------
GAGACATCCCCAGCCACAGCCGCAACC------ACAGGGCTACCCTAACATGGG------
---------------------------------CCACACCCCCCGATACCCACACTCCCC
CTCCCGGCAGCCTGCAC------------------ACACCCACCAGCACCAACAGGGCAT
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------GGGGGGG----
-----------------------TTCGGGGGTGGCCAGTACCCC----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------
