>Amblygaster_clupeoides|029781|TR5294|c0_g1_i1|m.9933
ATGATAAGGAGTAAGAGGCGTTCAGCTCTAGTAGCACCTCAAAGCAGAACACTCACGCGT
GGGACCACAGGTGTTGCAATGGCAGGACTGCTGGAGGCTGCCCTTACCACATGTGTGTGC
AAAGTGTGCCTTAGCATCGTCGGCGTCCGCGTGGTCCGAGGAGGATCCCTGGGCTCGGTG
GGGCTGTGCTCCAGCAGTCTCCTGCTCCTCACCGACTTCACTATCACGCTGTTCCTGGCC
TTCCTACGGCTGGCGGACTACTGGCAAGTGGCCTTTCCAGTCTCTGGCGACATCATTGCT
CTCCGATTCCTCCTCTTCCTCACTCACACCTATGGGAGCGTGATGCTGCTCACCATCCCT
CTGGTCACCGTGGAGATGGCTTTTCTTCTCCGCTGGCCCCACCTTGGAGGGACAGAGGGA
GAGGGCCATGGAGGGAA---GGGCACGCGCATGAGGGGAGACGAGAGCCGCGTTCCTCTG
TGCTCTGACCCAGGGGAGGCAGAGAGCGGAGAGGCCTCTCTTGAAAGAGCAAAGCAGCAA
GAGAGGCACACTTCCTCGG--------CTGCCGTTCTGGCTCACGCTGCGTGCGT-CCTG
AGCTGCCTGCTGGCATGGTGCATCTCAGGGCTTCGCGCCGA--------------ACGCC
GCTGGGCCCGGGACTTACCCACAGTCGAGCTTTGCCTGGAGAGATACGCCATTGATGGTG
ATGGAGGCAGAAGCATCGGGGTCTCTCTCTGGCACTGTCTCCCCAGCTTGCTCTCCGTGG
CCTGGACGGACCTCAGTGAGCCCTGCTGGGGTTTCCTGGCTGTCATGGTTCTCCTGG-GC
CACTAT--------GTGAGCCTGCGTCTCAGCCTCAGGTCTGACCCCCAGCATGTACGCT
CAGAGAGGGACAAATCTTCACTCGTGAAGGAAAAGGACAAAGGAAAGCACCCCCACGTGG
ATACCCATGAGCAAATGGCAACAGCCAGCATGGGCTTAGAGAATGTTGCCGTTTCCCTGG
AGGAAGAGGAGGAGAAAGAACCGGAGCACATGACGAATATGGACGTCCGAGTGCAAATGC
AAACACAACCTTCTCTCTGCGTAATTGTTAATCCCTCAGATGGCATCTGGACACAAAGCC
TCACTGTTGACACGGAAACAACAGCCAGCAAGAGCCAAGTCCTCGACACGGGCACGCCTT
GCAGCGCTGAGAGACGTCAAGCGCCCTGTCCTCATGGAAAAGGCTGCCTTTCATCTCGCA
GCTTTGCATCCATGCCCGACAGGTGCAGGTCCCTGGTCAAAGTCAAGGGTGCGGATAGGC
AAATGCAAGATAAACAGCCGCCAACATCTGGACAGCAGCCACTGCGAAAGGGCAGTGACA
TGGCAGAGAATATGTGTTTTGTGTGGGTGTCACCACAGTCAGACTGCAGTGGGGTGTGGG
AGGGCCCACAGGAC-------CCGCTGCAGTGCCCTAGGCGCTGTTGCCAGAGGTGGGGT
TTCCCTGG--------GGGATCCCCCTGCCC-----GAGAGGCCTGCTGATAGCAGTGCT
TAT--------------------GTGGGGGATATTTATCTGCCTTTTCCC-CGTGCCTGT
GGGCTTTTGTGTCTTAGTCATCCAACATACAGAGACCCTTGTTTTGTTTGGG
>Distichodus_sexfasciatus_gill_4|020094|scaffold29510|m.34957
------------------------------------------------------------
------GGAGGCACTAGAATGGATGGTGTTCTGGAGGTCATTGTTGCTCTGTGTGGCTGC
AAAGTGCTGTGCAACTTTTCATGTCTGCCGTTGTTCA---AACGCCCTCTGTCCATCGTC
ACCCTCTGTTGCAGCTGTCTCTTATTCTTCACCGACCTCTCCATTTTTCTGTTTCTGGCC
TACCTCTGGTACACCGCTACTGGACCTATGTCCTCTAACCCATCTTCCGACATCATCTCT
CTGCGTTTCCTGCTGTTCCTCAGCGACACCTATCGGCCAGTGCTGATGCTGACGCCTCCG
CTGGTTGCTGTAGAGGTTCTTATCAgtcttctgggtcctaaTGAGAATCTGATGGAACTG
AC-TGTGAAGAGAGGGACCTTTAAAGAGACAAAAGGGTCTCAAAA---------------
-----TGGTGCAACTGAGACCAGGGAGGTCAGATCAGATCTAAACAAAGCGAAGAAGAAA
GGGTCTGAAGTACCATCGCTGGTTTCCATGGAAGTTTGCAATGACCTAGCGG--------
-----------GGTCTGAAAAGTCACCAACGAGACCGGAGGTGAACATCAAGACCATGGA
AGAAAAAATGAGGTCTCAAAGTGGAGCAACCAAGACTGGGGTGGTCAGATTATTACAGAA
GGGGGAGAAGAGCGAGGAGAAT--------------------------------------
-------GGGTCTGATGTAGTCCGGTTGG------------------TTGCTGTAGAGGT
TCTTAATGATCTACCGGGGCCTGAAGAGACACTGACGAGACTAAAGTTGAATGGCAAGAC
CC----------------------------------------------------------
------------------------------------------------------------
---------------------------------------TGGAAG---------------
------------------------------------------------------------
---------AGTCTGAAAGTGGATCAACCAAGATT-------------------------
------------------------------------------------------------
----------------------GGGGAGATCA---------------GATGTTTACAGAC
AAGGGAGAAGGGAGGCTCCGATTTC-----------------------------------
-------------------------------------------------AGACCTGTGGG
CTGCCTCATCTGTC----------------------------------------------
-----------------------------------------------TTCTGTTATGGGT
CAT--------------------ATGTGGGACATGCGCCAGATCTAGCT-----------
--------------------------------------------------GG
>Lepidogalaxias_salamandroides_Head_2|010020|C546926|m.50017
GT----------------------------------------------------------
--TCCTGTGAGCACAGCGATGGATGGTGTGTTGGAGGCTGCAGCTGCTCTCTGTGCATGT
AAGCTGGCGTTCAGTTGGCTCTTCCTCTCCACCCTCA---CGTCCTCCCATAGCGCGGTC
AGCTTCTGCTGCGGGTGTCTGCTGCTTGTGACAGACCTCGTGGTCACAGCCTTCCTGCTC
CTCCTCTGGTTGGCCGAGCCCTGGCTACCTCCGTTTCCCACCTCCAGCGACGTCGTTGCC
CTGCGCTTCCTGCTCTTCCTCGGCCACACCTACTGGACGGCACTGCTGCTGAGTGCGCCC
CTGGTCGCCGTGGAGACCGCGGCGAGGCTGCGCTGGCCCCGGCCGAGCGGGGAGGAGGGG
G-----------------------------------------------------------
-----------------------GGGAGTCAGCGCTGGACGCGGCGG-------------
---------------------------------------------------GCTT-CCTG
GGCTGCCTCGCCGTGTGGATCCTGAGCGGTCTCTACGCGGG--------------GCAGG
AGCGGAGGACAGA------------------------GGAGCTGTGGGCGGAGGCATGTC
TGAGGACGAGCGCC---------TCCCTCCCCCCGTGCCTCCCCGGGCCTCTCGGTGCCG
CCCCGCCCGCTCTGGCTCGGGCCTGGTGGGTCCTGCCCGCCGTGACGGTGCTGTTGGCGC
TG------------GTGGAGGCGCTGAGCGGACGCCCGGCCCACCACACACATGCGAGGA
CGGACGTGGAGGCACAGCGGCTCACG----------------------------------
------------------------------------------------------------
---------------------------------------TGCACG---------------
-----------------------------------------------------------C
TCGCTGTTGACTCAGAGAAAACACTCCCCAGGTGT---GCCTTTCACACCGTGGCATCTC
TCAGCAGCAAGCAGCTGCCACTCCACCCCCCCGCCAGCATCCCCCGCCTTTCA--GCAGA
GCTTCGCCCGGGTGACCAGCAAGAAGAGACCC---------------------------C
GTGTGCAGGGCGAGCCCACCCCAGC-CCGGAGCAGCAGC---------------------
--------AGGGCCCCCTGAGGCTCAGCGCCCCCGCCTCTGCTCCTCCTCGGCTTTCGGG
GGCCCCCACCCGTGGACACACGCGCTGGGGTTCACCACGCGTGTTTGGTGGACTGGTGTG
TGTCCTGGTGGCGTGTGTGTTCCCCATGCTCCTCGGGGTGAACGTCCTCCTGGTCAGGAC
CGTGGAGCTGGTCACACGCTGGAGCGTGAAGAGCCTACTGGCTCCACCCCGCAGGACGAT
GGAC--------------AGTCAGAACCACGGGGACTCGT----------GA
>Melanotaenia_praecox_viscera_mixture_8|002175|C421900|m.27408
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------CTCAGCCACACCTATGGGGCCGTGCTGCTCTTGAGTACATTT
CTGATTGCTGTGGAGAAACTGATCAGACTGTTGTGGCCTCACACTGTTGTCAGTCACAGG
GC----------GGTGA---GTCAAACTGGTGCACAGCAGTG------------------
-----TCATGTTGGGGAGGAAAAAGTCGAAGAGGAGGAGGACATCAACGGCTTGGATAAT
GA--------------------------CATGAGCTTGCAACAAGTTGGCGGCTT-CCTC
TGTTGCTTGTCGGTGTGGATCGTTGTCGCCCTGAATGTCAG--------------ATGGC
GTTGGAAAGTGGA------------------------GGAAAAGTGGGCTGCGGACTGTT
TGTACACAACCGAC---------TCACTTGTCAGATGTCTGCCTAACCTGCTTGCAT---
CCATGCCCAGTGCAATGAATCCCTTTTGGAGCATGGCTTTCCTCTTCCTCCTCCTACTGC
TGCTGACCATCAGCCCAGGCCTGCAGAGACAACACCAGACCCCTGCACAGGCAGAGAGCA
CA----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------
>Sargocentron_rubrum_gill_6|001159|C647827|m.43240
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------GGCGCTCTGGACCTGCACTGTCATGATTTA----
------------------------------------------------------------
------GAGGTCGCGGAGGAAAGGAATCATGGGAATGACACAGAGAGTGACCCCAAAAAA
GA--------------------------TACTAGGCTGTTCCAAGTCATCGGCTA-CCTT
TGCTGCCTGTCAGTGTGGATTGGCGTTGGCCTCAGTGTCAG--------------GTGTG
GATGGAAGCTGGA------------------------AGAGGTGTGGGCCGCTGCTTGCA
TGCACACAACTGGC---------TCCCTCATCGGATGTTTACCCCGTC------------
CCATGCCCAGCACCCTGGATCCCTGCTGGGTCGTGGCGTTCCTCTCCCTCCTCCTGCTAC
TAACGATGGTTA---TGGGCCTGCACAGGCGGCACCAGGCCCAGGCACACACTGTGAGCA
CACACACGGAGAAACATGGAACT-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------AACAGTAAC---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------
>Scleropages_formosus_red_gill|000422|C1185361|m.67056
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------AGCGACGCCATTGCC
CTGCGCTTCCTGCTCTTCCTCGGCCACACCTACGGCGAGGTGCTGCTGCTGACGATTCCG
TTCGTCGCCGTGGAGACGGCGTGCAGACTGCAGTGGCCCCTGTCAGGTGGAAGAGAGGCA
G---------------------------GCTGCGTGGCGCTGCAA---------------
-----GGGCGAAACAGAGCCACGGGAAGCTGGAGA-------------------------
------------------------------------------------------------
GGCTGTGAAGAGACGGAGAGACTGCAGGGCGCCTGCACTCA--------------CGATG
GACAAAACCCGGGTC-----------GCGGCGGATGTGGAGCATGGGACGGGGAGATGGA
CGCGGTGCACTGGCAGCGGG----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
AAGGGCAGAGAGAGTCC-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------
>Synodus_sp._gill_5|003340|C558105|m.45028
------------------------------------------------------------
------------------ATGGAAGGTGTGTTGGAGGGGGCAGTTGTGTTTTGTCTGTTG
AAGCAGGCATCCAACCTCTTGTTCCTGCCTTTCGTCC---CTGCTTCTCTCAGCCCCATT
AGTCTATGCTGCTGCTGTCTGCTCATCTTCACAGACTTCTTCGTAACAACATTCCTAGTT
TTCTTGTGGGTTGCTGCCTCCTGGTTATCATATCTGTCCCCTTCCACTGATGTCATCGCT
CTGCGCTTCCTGCTCTTCCTTGGTCATACATATGGGACAGTTCTACTATTGATAACACCT
CTGCTCGCTGTAGACACTGTGTTGAGGCTGCAGTGGGCCAAAGTGGAACGCAGTGAGGTA
AC-CACCGAAGAGGGGA---GTAAGGACACTCAGAGGCAATGGAA---------------
------------AGAGAAAGAGGAGGAGAAGAATACAGACACAGAGGAAAGTCAAAGTAA
AG--------------------------GGAAGATTGGCTCCCAGTTACCTGCTTATCTC
TGCTGTCTGTCTGTATGGGTTCTCTCAGGCCTCCAGGCCGG--------------GTTTG
GGAGGAAACTGGA------------------------GGAACAGCAAGCTACTGCCTGTG
TGCAAAACACCAGC---------TCCCTGGTCGTGTGCCTGCCCAGCCTGCTTCCAGGGC
TTGGGCCAGATGTGGTGGAGCCATGCTGGAGTCTGGCGCTGCTCTATCTC----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------
