>Amblygaster_clupeoides|009442|TR19555|c0_g1_i1|m.38028
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------AATAGTGAGATG
CCTAAACCTCCCAATGCAGACTGGAGATACTCGGCCTCCCTGAGGGCAGGAATGCAA---
AGAGAGGTGCATATGGAGGAGTCCTCA---GTGATGCAGGGAGCCCAGGGGGTTCTGGTC
CAGAACTGGCCGACCGTGTCCAGCGCCGCCGACCCTGAGGGTGGAG---AGGTGTCTCCA
CCCGTGG---------GCGCCGGCGTCGACTCCAACAGCTGGCACTTCCGTTATGGAGGC
CCGCCGGG---------GCCGCAGCACCTGAAGCCGGGCGAGATGCCGCCAGAGGCCTTT
ATCATCCCGGGCTCGCCGGCCATCATCTCCATCCGCCAGGGCCAGGA---GGGCGACGAC
AAGAGCGACTTCATCACCTTCGGCAAGAAGGAGGAGGCCAAGAAGAAGAAGAAGAAGAAG
AAGGAGAAGAAAGACAAGCGGGAGAAAGGGAAGGATGACGACGAGTAG------
>Distichodus_sexfasciatus_gill_4|013991|scaffold21054|m.23439
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------ACAAAG
CCTAAGGGGCCGAATGCTGACTGGCGGTACTCTGCATCTCTGAGGGCAGGGGTGCAA---
AGCTCTGTTCACATGGAAGAGTCCTCAGCAGTGATGCAAGGGGCCCAGGGTGTGCTGGTG
CAAAACTGGCCGACTGTCTCTAGTGCAGCAGATGGAGAGGGCGAAGGGCAGCTTTCCCCC
CCTGTTGNNNNNNNNNNNNNNNNNNNNNNNNNNAACAGCTGGAGCTTCCGCTATGGGGCT
GGCCCAGGCTACGCCCCACCACCGGCTTTGAAACCAGGCGAGATCCCTCCTGAAGCCTTC
ATCATCCCTGGATCACCTGCCATCATCTCCATTCGTCAAGAACCAGGTGCAATGGATGAT
AAGGGCGACTTCATCACCTTTGGCAAGAAAGAGGAGGCCAAGAAGAAGAAGAAGAAGAag
aaggaaaagAAAGACAAGAAAGACAAAGGAAAGGAGGATGGGGAAGAGTAG---
>Gasteropelecus_sp._gill_3|005027|C951058|m.50104
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------GTTCACATGGAGGAGTCCTCTGCCATGATGCAGGGGGCACAGGGCATGCTGGTG
CAGAACTGGCCCACTGTGTCCAGTGCTGCAGATGGTGAAGGCGAAGGACAACTCTCTCCA
CCTGTCG---------GAGCTGGGATCAACAGCAATAGCTGGAGCTTCCGTTATGGTGCG
GGCCCAGGTTACGGCCCCCCACAGGCCCTGAAGCCAGGCGAGATCCCTCCTGAAGCCTTC
ATCATCCCAGGCTCCCCAGCCATCATCTCCATCCGTCAAGACCCAGGGGCCTTGGATGAT
AAAGGCGACTTCATCACCTTCGGCAAGAAGGAGGAGGCTAAAAAGAAGAAAAAGAAGAAG
AAGGACAAGAAGGACAAGAAGGACAAGGGAAAGGAGGACGGAGAGGAGTAG---
>Lepidogalaxias_salamandroides_Head_2|022346|scaffold21199|m.29915
AATAAGCAGGTGAGCCTGGAGATCCCGCCCGGACTCCCTTTCAAGATCAAGTCCTTCCGC
AACTACTACACCTTGGTGACCTCCGCCTTCCTGGACCGGGAAACAATGGCAGCCTACAAC
GTGACGCTCAGCGCCACCGACGCTGGGACCCCACCCCTCTCTTCCCAGAAGTCCTTCCAG
GTGGATGTGGCGGACGTGAACGACAACCCGCCACGCTTCGAGCAGACGTCCTACACGGTG
TACGTGACGGAGAACAACGCCCCTGGGGCTTCACTGTGCACTGTCCGCGCTCAAGACGCC
GACGTCGGCGAGAACGCCCGTATCACTTACACCGTCCTGAACGACAATAACCACGGCATC
CCCGTCACCTCCTACGTGTCGGTGAAGGCCGACACCGGCGAGGCCTACGCCCTGCGCGCC
TTCGACTACGAGGCACTCCAGGAGTTTCACTTCCAGGTCAAGGCGCAGGACGGGGGGATA
CCACCGCTCAGTCGCGTGGCCACCGTCTACATCTACGTGATGGATCAGAACGACCACGTC
CCCGAGATCCAGAATCCCCCGGGCAATGGCACGCGCTCAATGGAGACGGTGCTGAAGAAC
GCCGAACCCGGTGCCCTGGTGACCAGGGTGGTGGCCTACGACGCAGACGCGGGTCAGAAT
GCCTGGCTGGTGTACGTCCTGGACCAGGCCAACGAGCTGGACCTTTTCAAGGTACATGAG
CACACTGGGGAGATCCGCACCACTCGGCGGGTCTTGGAGGAGAACTCCACATCCTTCAGC
CTTACGGTGCTGGTGCGGGACCACGGCCAGCCTGCCCTCTCCTCCACCGCCACCGTCAAC
GTGGCGGTCATGGAGGTGCCGCCCAAAGTGACCCCCGACCCTAAACGTATCATCCGGCCA
CACAGCACTCTGCTGTTCTCCAACGTGACGCTGTACCTGATTGTGGCCCTCAGTGCCACC
ACCTTCGTGTTCCTCGTCACTGTGGTGGTGCTGGCCATCGTGCGTTGCCATGCCTACTGC
TCTCAGCCTGGCTCGTGCTCCTCTTGCTGTGTGTCCCAGAAGACTCCCCCGGACGGCGGC
ACCAACAGCGTCATCGGCAGTGCTGGGGGTGGGAGCTCACAGCCCAACAACAACGTGGTC
CTTCGGCGGGACCTGAAGGTGGAGCCTCACTACATCGAGGTGCGCGGCAACGGCTCCATG
ACAAAGACGTACTGCTACAAGACCTGCCTGACGGCCACGTCGGGCAGCGACACCTTCATG
TTCTACAACACGGGACGACCCATCAGCGGGACCTGGGGCTCGGAGCGCTTCTTCACCGGC
GGGAGCGGCTTTGTACGGAGACTGAGCATGCCCGATGCAGCGCTCCAGATGTGTCCTGAG
CCAAAGGCGCCAAACTCTGACTGGAGATACTCGGCATCCTTGAGGGCCGGCGTGCAAAGC
AGCTCCGTTCACATGGAGGAGTCCTCT---ATGATGCAGGGAGCCCAGGGGGTTCTTGTC
CAGAACTGGCCAACTGTGTCCAGTGCTGCAGATGGGGAGGGGGGTG---AGCTGTCCCCT
CCAGTTG---------GGGCTGGGATTGACAGTAACAGCTGGCACTTCCGTTATGGCTCG
GGGCCTGGCTACAGCCCCCCGCAGGCCCTGAGACCCGGAGAGATCCCCCCAGAGGCCTTC
ATCATCCCTGGCTCTCCCGCCATCATCTCCATCCGTCAAGATCCAGGAACGGGAGAAAGC
AAGGCGGACATGATCACTTTCGGCAAGAAGGAGGAAGCGAAGAAGAAAAAGAAGAAGAAG
AAGGAAAAGAAGGACAAGAAAGACAAGGGGAAGGAGGAAGAGGAGGAAGAGTAA
>Melanotaenia_praecox_viscera_mixture_8|016503|scaffold2831|m.2411
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------GCCCCGAATGCTGACTGGCGGTATTCTGCATCTTTGAGGGCAGGGGTGCAG---
AGTTCTGTCACCATGGAGGAGGCCTCG---GTGATGCAGGGAGCCCAGGGGATGCTGGTC
CAGAACTGGCCTACTGTATCCAgtgctgcAGATGGAGAAGGTGGTGGAGAACTATCCCCC
CCAGTGG---------GTGCTGGAGTCAACAGCAACAGCTGGCACTTCAGATACGGAGCT
GCACAAGGATATGGCCCTCCTCAGCCCCTGAAGCCTGGCGAGATTCCCCCAGAAGCCTTC
ATCATTCCTGGATCTCCAGCCATCATTTCTATCCGCCACGACCCAGGCCCTGTGGAT---
------------------------------------------------------------
------------------------------------------------------
>Pantodon_buncholzi_mixed|003293|C619681|m.34184
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
TTTAGCTCCGA-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------CACACTGAAGAGTGATGTTGTGGTT
TTCCCCGCACCG------------TGCGGGCCTGCAGACGCAGAACTCATCAGTATTAAC
GGGGGAGACACTTT------------TAAACGCAACCAAACACTGCCCAGCAGGGACAAG
CCGAAGCCTCCCAATGCAGACTGGCGATATTCAGCCTCCTTGAGGGCAGGAATGAAA---
AGCTCGGTGCACATGGAGGAGTCGTCA---GTGCTGCAGGGAGCCCAGGGGGTTCTGGTT
CAGAACTGGCCGACCGTATCCAGCGGCGCAGATGCTGAAGGGGGAG---AAGTGTCTCCC
CAAGTGG---------CCGCTGGGATGAACAGTAACAGCTGGCACTTTCGCTACGGCCCG
GGACCGGG------CCCCCCCCAACACCTGAAACCCGGCGAGGTC---CCCGAAGCCTTC
ATTATACCCGGCTCCCCTGCCATCATCTCCATACGCCCAGAGCAGG--------------
-------------------CTGACGCTAAGGATGAGGCCAAGAAGAAGAAAAAGAAAAAG
AAGGGC---AAGGACAAGAAGGAAAAGGGAAAGGATGAGAGTGAGCAATAA---
>Sargocentron_rubrum_gill_6|016248|scaffold24784|m.31634
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------ATGCTGGTT
CAGAACTGGCCCACCGTGTCCAGCGCTGCAGATGGAGAGGGCGGTGGGGAGCTGTCACCC
CCGGTAG---------GAGCCGGGATCAATAGCAACAGCTGGCACTTCCGATACGGGGCA
GGGCAAGGCTACGGCCCTCCTCAGCCCCTGAAGCCCGGAGAGATCCCCCCTGAAGCCTTC
ATCATCCCTGGATCCCCTGCCATCATTTCCATCCGCCACGAGCCAGGCCCCGTGGACGAC
AAGGGTGACTTCATAAGCTTTGGCAAGAAGGAGGAGGCCAAGAAGAAGAAAAAGAAGAAG
------------------------------------------------------
>Scleropages_formosus_red_gill|024244|scaffold38274|m.50249
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------CAGGGAGCCCAGGGGGTGCTAGTC
CAAAATTGGCCTACTGTGTCTAGTGCTGCTGGAGATGCTGAGGGGGGTGAAGTGTCTCCC
CCAGTGG---------GGGCTGGAATCAACAGTAACAGCTGGCACTTCCGTTATGGCCCG
GGACCTGGCTACGGCCCCCCGCAGCATCTGAAGCCTGGAGAGGTC---CCTGAAGCCTTC
CTCATCCCCGGCTCACCTGCCATCATATCCATCCGCCAAGATCAGGGTGGACCTGATGAC
AAGGGTGACTTCATCACCTTTGGCAAGAAGGATGAGAcaaagAAGAAAAAGAAGAAGAAG
AAGGGA---AAGGACAAGAAGGAGAAAGGCAAAGATGAAGGGGATGAATAG---
