>Amblygaster_clupeoides|014874|TR25793|c0_g1_i1|m.47403
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------AAAGCAGTAGACATAAACTCTGAGGAGTTCTCGCAG
TTACCTCCAGAAGTCAGACATGAAATTCTGAAAGAGATGAAGGACATTGCCAAGAGACGC
CGGACCATGTACTACAAGCCACCCGAGAGAGCAGGTGACTTCTCCCAGTTCCAGCTGGAT
GGGCTGCTGCAGAGGCGCCGTTTGAACCAGCGTCTCGAGGGGGTTG--------------
-------AGCAGGAAATGAGCCAACAGTCGTCCGCAGGTCTCGAGCTCCCTGAGGACTC-
-----GCAGCATAGTGTCGAGACGCGCCGCCTCATCTCTGAAGACTCTTCACACTATATC
CTCATCAAGGGGTCCAAGAAAAGCACCAGGGCTCCCGAGAGTCAGCCTGCAGCCACCTTC
TCAGACCCGCTGGCTAAACGCAAG-------AAACCCAGTGGGCAACATGGAACTCTCTG
GCGCCCGATATCAGAGGAGAGCTCTGAAGAGGA------CTCTCCCTCT-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------
>Corydoras_julii_viscera_mixture_8|002198|C1216014|m.26705
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------CCAGTCTTTGTATATGATGGTGATGCA
CCACTGCTTAAGAAACAGACCCTGGCGATCAGGAGACAGAGAAAGGAGGAGATGACTCAC
GAGTCCAAGCAAACCCATGAAAAACTACTGAAAACTTTTTTAAAAAGACATGCTATAAAT
GCTGCTTTGGGAAACAACAGTCAACAGCCAATTTTAAGTCTGTCTTCAGTACGAAGAGAT
GAAGTCGATGACATGTATGTTTTGCCAGCACTTGCCCCGGTAGAAGAAAATGAGAAAAGC
AGTTCAGATGAAGAGTCAGTCTCAGAAGAGGAACAGAAACCAGATGCATTCCTTGTTTAT
CAGGACGAATTTTATGAAAATCCTGATTCTATAGACATAAACTCCGAAGAATTTTCCCTT
CTGGCGCCAGAGATCAAACATGAAATCCTTAAAGACATGAAGGAGTTTAGCAAGAGAAGA
CGCACAATGCTTCAC---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------
>Distichodus_sexfasciatus_gill_4|018844|scaffold27958|m.32666
ATGGGAGTCCATGGACTTTGGAGACTGCTGGAGAGCACAGGGAAGCCCATCAACCCTGAA
ACACTGGAGGGGAAGATCCTAGCAGTCGATATCAGTATCTGGCTCAACCAAGCCATCAAG
GGCGTGCGAGATCGTGATGGCAACAGCGTTCAGAACGCCCACCTCCTCACGCTGTTCCAC
CGCCTGTGCAAGCTTCTCTTCTTCCGCATCAAGCCCGTCTTTGTCTATGATGGAGATGCA
CcactTCTTAAGAAACAGACTCTGGCCATCAGGAGACAAAGGAAGGAGGAGATGGCCCAT
GAGTCCAAACAGACCACTGAGAAACTCCTCAGGACCTTCCTGAAGAGGCAGGCCATCAAA
GCAGCGCTGGGGGACAGCAGTCAAGAGACCATTCCCAGTATCTCTTCGGTACATAGAGAT
GAGATGGATGACATGTATGTTTTGCCTGCACTGCCTCCTGTGGAGGAGAAAGAGAGGAGC
AGTTCTGATGAGGACATGGAAGGAGATGGAGAAGAGACATCAGGGGCTTATCATAGGTTT
CAGGAGGAGATCTACGACAATCCCAACTCTGTGGACATAAACTCAGAGGAGTTCTCCTTC
TTATCGCCGGAGATTAAGCACGAGATCTTGACCGAGATGAAGGAGTTTAGCAAGAGAAGA
CGCACAATGTACCACAAACCTCCTGAGAAATCGGGCGACTTCTCTAACTACCAGCTCGCT
GGGCTGCTACAGAGGAACAAACTGAACCAGCGTCTAGAGGGCGTGG--------------
-------AGAAGGAGATGAGCCAGCGAAACTGTGGGGCTGTAGAGCAGGAATTTGACCAA
GGCGAAGACCATAGCGTGGAGACCAGGCGACTCGTTTCTGAAGACTCCTCACACTACATA
CTCATCAAAGGATCCCAAAAACCTGCTAAAGCTCCCGAGAGCCAACCAGCTACAATCCCA
T-GGTCCAGTGGGCCGTGGGCTCGGAGAGGGAGACCCAAAGGAAGACCGGAGCCCCTGTG
GCGTCCAGTAACAGACGACATTCTAGAAGAAGACGAACCGTCTTCCTCCTCTTCTTCGTC
CACGACGCCAAAACCCGTCCTGAGTTGTGAGGAACGGCCTTTAGATGGAGCACCTCCTTC
CCCACGTACCCTGAAGGCCATCCAGGCAGCCATGATGGACTCCAGCTCTGACGAAGACGA
AAGCATCTTAAGAAAAGCAGTCCAAAGCAGGCGAGGAGAAGCCGGTTCTGAAGGCGAAAA
AGGAGACGTGTCTCCTCGCACTCTCCAGGCCATTCAGAGAGCCATGATGGAGGACGGTGA
GGTTTCAGAATATCACAGCAAAGTCGAAGAAACTGAAACACGGAAACACATCATCGTCAC
CAGCTCTGATGATGACGATGACGATCTTCAGGAAAGTGTGACGACCAACAAGAGCATCCT
GGTAGAGAGCGATGGACTTTCTCCCAGGACCTTGCTGGCCATTCAGAGTGCCTTGGGGGA
ACGTGAGAGTCTTCCCGGGGTTCAGCAGGTGAGATCAGATGTGGGGCAAGTCGGTGTGGT
GAGCAGCTCTGACGGGGCGCTCGTTTTCGCTGAAAGAAGTACTGGAGGAGAAGCAAA---
----------GAGAAGCAGTCTAGAGGATGAATGGAAAGCATCAAATCAAAGCCCAGAAA
AG---------GGAATGAACAGAGATTGTGCGCTTGGAACACCTCAAACTCAAGGCCAAG
ATGTTCCTGAGAAAGCTTCGCCAGAGGGAAGAAGTAACTTGGAAATGGACGCAATCCAAA
CGTCATCGGACGTTAACATGAGTGGGCAGAAAGAGAAGCAAATTGAGAAACTGGTAGTAA
AAAGTGAAGATGAAGAAAGCAGCTCTGAGGGTTTCATTGAGGTCTCCGAAGGGGAAGCGG
AATCTGAATCGGATGATTTGGAAGGCCAAGCAGATTTACCAAAACCAGATTCGCAGCTAC
TCATGAACAAGCAAGAGGAGAAAGAGGATGAAGGGAAAGATGAAGACTCAAGTGACCAAA
AGGAAGAGCCAAGTGACCAAAATCACAGCCAAGCAGAGCAACAAGAATCATCCCAAGAAG
CCACTGATGTACCTGTGCCTACCGAATGGGACAATGTTGACATGGGGGAGCTGGAGCAGA
TGGAGAGAGAGCTGCAGGTGGAGCAGAGCAGTCTACACGGACAACAGCAGCAGCAGCAGC
GCAGTGCCGCTACAGTTACCGGGCAGATGTGCC--------AGGAGAGCCAGGAACTCCT
GCGTCTCTTCGGCATTCCCTTCCTGGTGGCACCAATGGAGGCTGAAGCTCAGTGTGCAGC
TCTGGACCGAAGCGACCAGACCCACGGCACCATCACTGATGACAGCGACGTTTGGCTGTT
TGGCGGGCGTCACGTCTATAAAAACTTCTTTAGCCAAAACAAATATGTGGAGCACTACCA
GTATGTGGACATCCAGAATCAGCTGGGAATTGACAGGAGCAAGCTGATTAATCTGGCGTA
CCTGCTGGGCAGCGACTACACTGAGGGAATCCCAGGTGTTGGATATGTCACAGGGATGGA
GATACTGAACGAGTTCCCCGGCCCTGGTTTGGAACCTCTCACTATGTTCAGTGAGTGGTG
GAATGAAGTTCAAAACAACAAGAAGCTGGTGGCTAATCCCAAAGACACCAAAGTGAAGAA
AAAGCTGAGAAACCTGAAGCTGCACACTGGTTTCCCAAACCCCGCTGTCGCTCAGGCCTA
CCTTCAGCCCAGCGTGGACGAAACTGGGAGCCCCTTTAGCTGGGGCCGACCCCAAGTGGA
TCTCATCAAAGAATATCCTTTAAATACAATTTACTAA
>Gasteropelecus_sp._gill_3|017299|scaffold28190|m.29297
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------ATGGTTCGT
GAATCCAAGCAGACCAATGAGAAACTCCTGAGGACCTTTCTGAAGAGGCAGGCCATCAAA
GCTGCACTGGGAGAAAACAGTCAAGAGACAATTCCCAGCATCTCCTCAGTGCGAAAAAAT
GAAGAAGATGACTTGTATGTTTTGCCAGCGCTGCCTCCTGTAGAGGAGAAAGAGAGCAGT
AGTTCTGATGGAGAAACTGACAAAGAAAGGGAAGAAATGCCAGAATCTTAT---------
CAGGAGGAGTTCTATGCCAATCCCAATTCTGTAGACATAAACTCTGAGGAGTTTTCACTC
TTATCACCAGAGATTAAACATGAGATCCTGAGAGAGATGAAGGAGTTTGCCAAGAGAAGA
CGCACGATGTACCACAAACCCCCTGAGAGGTCAAAGGACTTTTCTCAGTACCAGCTGGCA
GGACTACTGCAGAGGAACAAACTGAACCAGCGTCTGGAGGGAGTAG--------------
-------AGAAGGAGATGAGCCAGAGGAGCTGTGGAGCTGTAGAGGAACAGTACAGTCAG
GGCGAGGAACACAGAGTAGAGAGCAAGCGCCTAGTCTCTGAGGAC---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------
>Melanotaenia_praecox_viscera_mixture_8|020213|scaffold9133|m.8031
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------TTGACCCGT
GAGTCCAAACAGACCAATGAGAAACTGCTCAAGACATTCCTGAAGAGACAGGCCATCAAA
GCTGCTCTTGGAGATAGCAGTAAAGATCCTCTACCCAGCCTCTCGAACGTGAGGAGAGAT
GAGGTGGATGACATGTACATTCTGCCTGCCCTTCCGCCTGCAGAGGAGAAAGAAAGAAGC
AGCTCAGAGGAAGAAGAGGAGGAGAAAGATTGTGTAGAGACGGTTGACAGTTACGCATAT
CAGGAAGAAATTTATGATGACCCCAACTCAGTGGACATCAACTCAGAAGACTTTGCCAGC
CTGCCTCCTGAGATGAAACACGAGATTCTCAAAGAAATGAAAGAGTTTTCCAAAAGACGA
CGGACCATGTATCAGAAACCTCCAGAGCGGTCAGGAGACTTTTCACAGTACCAGCTGGCT
GGTTTGCTGCAGAGGAATCGACTGAACCAGCGCCNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNTCAACACGATGAAGATCAGCA----------------------------------
-----GAGTCACAATGTCGAGTCAAATCGATTGGTTTCAGAAGACCACTCGCACTATATT
CTTATCAAAGGGCCAAAAAAGAATGAGATTACCCCAGAGAGCCAACCTGCAACTGCACCC
T-GGTCTGGAAGC-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------
>Pantodon_buncholzi_mixed|022337|scaffold916|m.1086
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------ATGTACGCTTTACCAGCGCT------------TGACATACAAAGGAAC
AGCTCTGATGAGGAAGAGGAGACTGAATGGGAAGAATCCGTGGAGAACCGCCGCGTGTTA
CAGGAGGAAGTCTTTCAGAACTTGAACTCTGTGGACATCGACTCTGAGGAGTTCGCCTCG
TTACCACCCGAAATGAAACACGAGATTTTAAAGGATATGAAGGAGTTCAACAAGAGACGG
CGTACTATGTTCCACAAGCCCCCTGAGAAATCTGGAGAGTTCTCCCAGTACCAGCTGGAA
GGGTTATTAAAGCGCCGCCAGTTAAACCAGCGTCTGGAGGGAGTGG--------------
-------AACGGGAAATGGCTCAGAGAGGAGCCGCGGTGTTGGAGGAAGAAGAAAG----
-----AGGACATGATGTGGAGACGCGACACCTTGCGTCTGAGGACAAGTCGCACTACATC
CTCATTAAAGGAACCAAAAATATTGAAAAACCCGTGGAGAAGCAGTTAGCTGTGATGCCG
T-GGTCTGAAGGCAATAAGGTCAA------------GAGAGAGAGACCAGAACCACTGTG
GAGACCCCTGTCCGAGTGTGTTGTGGAGAAGAAGCAA--GCCTCCCCTCC----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------AACATCT----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------CCACAACCAC----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------CTGCTGAGAGTTCCTACAGA---------------------
-----------------------------------------ACAGCAACGTGTC------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------CCCCTT--------------------
------------------------------------------------------------
------------------------------CACCCCGAACC-------------------
-----------CTACAGGCG----------------------------------------
-------------------------------------
>Scleropages_formosus_red_gill|024049|scaffold37967|m.49819
ATGGGAGTTCACGGGCTGTGGAAGCTGCTGGAAAGCACAGGGAAACCCATTAACCCCGAG
ACACTGGAGGGCAAGATCCTGGCTGTGGATATCAGCATCTGGTTGAACCAGGCCGTGAAG
GGGGTGAGGGACCGCGAGGGGAACAGCGTGCAGAATGCACATTTGCTCACTCTGTTTAAC
CGACTCTGCAAGCTCCTCTTCTTCCGAATCCGTCCGGTCTTCATCTTCGATGGTGAAGCA
CCGCTCCTCAAAAAGCAGACCCTGGCCAACAGGAGACAGAGGAAAGAGGAGATGAGTGTG
GCTTCCAGGCAGACCAACGAGAAACTCCTCAAGACCTTCCTTAAGAGACAAGCCATTAGA
GCTGCAATGGGCGGTGCCAGTCAAGAGCCACTGCCAAGCATATCCTCTGTTAGAAGAGAA
GAAGTGGATGATATTTACGTGCTACCTGCCCT------------GGAAAAAAATGAGCAA
AGCtctgaagatgaggcagaagcagAATGGGAGGAGAACATACAGAATCAACACGGGATA
CAGGATGAGATCTTTCAGAATTTGAACTCCATGGACATCGACTCAGAGGAATTTGCTCAG
TTGCCAGCAGAGATGAAACATGAGATCCTGAGGGACATGAAAGAGTTCAGCAAGAGGCGA
CGGACAATGTTCCAGAAACCCCCCGAGAAATCCAAGGAGTTCTCGCAGTACCAGCTAGCA
GGCCTTCTGAACAGGAACAAACTGAACCAACGCATGGAGGGGGTTG--------------
-------AACGGGAGATGGCTCAGCGGGGTCTGGGGGTGCTGCAGGAGGAAAACAG----
-----GGGACGCACGGTGGAGGCACGATCCTTGGTGTCCGAGGACACCGCCCACTACGTT
CTCATCAAAGGTTCTAAGAGTGAGGAGAAAACTTCGGAAAAGGAGGTGACTTCTGTGCCT
T-GGACCAGCTGTGATTGGGTTGG------------CAGACAAAAACCGGAGCCTCTGTG
GCACCCTCTGTCTGAGAAGAGCCCTGAGAAGAA------GCCTTCCTCCC----------
-----TGTCAAAGAACCCCATTGCCCAGGATGTAGCTCCTTCATCCTCACTCCCCCCTTC
CCCTCGCACCCTGAAGGCAATCCAGGCTGCCATGA---ACAGCAGTTCTGATGAGGA---
------------------------------------------------------------
--GAGCCATGTCTC----CAGTCCCGTGGCTGTCAGGA----------------------
-------------------------------------------------------GCCAG
CAGCCC------------------------------------------------------
-------AATGAGCAACTGTCTCCTCGTACGTTGCTTGCCATCCAGCGTGCCTTG-----
------------------------------------------------------------
----------------------------------------ACTGAGGAGGAAGCAGATCC
TTGTACTCCTGTGTATCAGTCCAGCACAAGAGTG-----------ACCCCACTCCAAAGA
AGTCCCATCCAGCAACTGACAGACTCTGTT-------AACAGCTCA-----GAGAGGGAG
ATG-------GACGACTCCACGGAAAAGAA------------------------------
-------GGATGTTCGCTCAGGCTCACTGTTGGACAG------CAAGGAGCTGAGTGTTA
ACTGTGGTAATG----TCGCAGTCTCAAATGTTGGATTGACTCC-----------ACCGG
ATTCTGAGTCATCT-----------------------------------CTCTCCTCTAC
TCCT----CAGCTGGAGGAGGAAGCAGAAAAAGAGTCAAAACCAGATACAAAT-------
----------------CCAGAATCGGAACCA-----------------------------
------------TTAAATTCTCCACACGGCCTGAT-----TCTGGAGAGATATGAGAGTG
AGGGGAGTGGGCTGCAGTTAGGGC------------------------------------
----CTCGGTTATTGCCTTCAGATCAGTGTTCTCCACCCAGTAGACAGCAAATGACTTGT
G------------------TTCCTGACAGTTCTCCTGAAGACAGTACCCAAGTG----GC
TGAGGAGGTAGCCACTGAGAGAGTGTGTGTGACCACAGATGATGATAATGACTC------
----------------TGAAGCAAATTTTATTGACGTGTCAG--ATCTAGAGGAAGAGGA
GAGTGAGGA-----------AGAAGGAAAAGAAGAAGAGCCAG-----------------
--TGCCAGAGGAAGTCTCTACGAAGGAAATGAGGAGTGAGGGCGGTTCC-----------
----CTGGCAGAACCACCCAGCCATGGC------CCTCCC---------------CAGTT
GGATGGTGCTGATGAGGAGAAAGAGAGGATCCAGTCTTCCCAGGAAACCTTGG-------
-------------CTGATGCTGCTGACAAGCAGTGGGAAC--------------------
-----------ATATGGACG----TGGTAATCACTGT---------------------GG
TACTGTTAAAGCATG-----TAAATACAG---GGTAA
>Synodus_sp._gill_5|003520|C561095|m.45324
------------------------------------------------------------
------------------------------------------------------------
------------CGGGAAGGAAACAGTGTTCAGAATGCCCACCTTCTCACTCTCTTCCAT
CGCATCTGCAAGCTGCTCTTCTTTCGTATCAGACCAGTCTTTGTGTTCGATGGAGAAGCA
CCTCTGTTGAAGAAGCAGACTCTGGCCCTGAGGCGGCAGAGGAAAGAGGAAATGGCTCGG
GAATCCAAACAGACCAATGAGAAACTCCTCAGGACCTTCTTAAAGAGACAAGCCATCAAA
GCTGCCCTGGGAGACCGCAGCAAGGAACCACTGCCCAGCATCTCTAGTGTGAGAAGAGAG
GAGGTGGATGACATCTACGTCCTTCCTGCCCTGCCGCCTGCAGAGGAGAGGGACAAGAGC
AGCTCAGAAGAGGAGGAGAACAACGCATGGGAAGAGGCCATTGAGAACCATGGCACTTAC
CAGCGGGAAGTGTATGATGATCCTAATTCTATGGACATCAACTCGGAGGACTTTGCCAGC
CTCCCTCCTGAGATGAAGCATGAAATCCTCAAGGATATGAAAGAGTTTAGCAAGAGGCGC
AGAACAATGTACCACAAGCCTCCAGAGTTGTCGAGAGACTTCTCCCAGTACCAGCTGGCT
GGACTACTGCAGAGGAGCCAGCTGAACCTGCGATTGGAGGGGGTGG--------------
-------AGCGAGAGATGAACCAGAGGAGTGCAG--------------------------
-----GCAGCGCCCCGCAG--------CTCTACGGCTCTGAAGACGGCGAACA-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------GCAGGACCGC----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------
