>Corydoras_julii_viscera_mixture_8|014883|scaffold24713|m.20514
ATGCTCAGCTTTGTGGATACCCGGATTCTGTTGCTGCTTGCAGTAACTTTGTATCTCGCA
TCATGTCAATCGAAAGGAGATAAAGGACCTAGAGGTGACAGGGGTCCTAAAGGTAGAGAT
GGCAAACCCGGCAAACCTGGAATTCCTGGCCTTCCTGGCCCACCCGGCCCCCCTGGTCTT
AGTGGAAACTTTGCTGCTCAATATGATGGCTCTAAAGGACCTGACCCTGGCCCCGGACCT
ATGGGTTTAATGGGACCCAGAGGCCCCTCTGGACCCCCTGGACCTCCTGGAGCCCAAGGA
TCATCAGGACATGCTGGTGAGCCTGGAGAGCCTGGACAGAGTGGCCCAATTGGACCTCGT
GGACCTCCTGGACCCCCTGGCAAATCTGGTGAAGATGGTAACAATGGCAGACCAGGTAAA
CCCGGAGACAGAGGAACTGTTGGACCCCAGGGTGCTNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNTGGTCTTGACGGACGTAAAGGAGAGCCTGGTGCAA
TGGGAACTAAGGGTGAGACTGGTGCTCATGGAGCTAATGGAACCCCTGGACAAAGAGGTG
GTCGTGGTCTGCCTGGTGAGAGAGGTCGTGCCGGTCCTGGTGGCCCAGCTGGTGCTCGTG
GTGCTGATGGTAACACTGGTCCTGCTGGTTCCGCTGGCCCACTTGGTTCTGCTGGACCTC
CAGGTTTCCCAGGAGCCCCTGGACCTAAAGGAGAGATTGGACCTGCTGGACCTTCTGGCC
CAGGTGGTCCTCAGGGACAAAGAGGAGAGCCAGGTCCCAATGGTGCTGTTGGCCCAGTT-
------NTGGTAA-----------------------------------------------
------------------------------------------------------------
---------------------------------------------------------
>Distichodus_sexfasciatus_gill_4|023114|scaffold32680|m.40639
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------ATGGACGCAAGGGAGAGCCTGGTGCAG
CTGGTGCAAAGGGTGAGAATGGTGCTCCTGGTTCTAACGGAACCCCAGGACAAAGAGGTT
CTCGTGGTCTGCCTGGTGAGAGAGGCCGTGCTGGCCCTGCTGGTCCAGCTGGTGCTCGTG
GAGCTGACGGTAACACTGGTCCTTCTGGGCCTGCTGGTCCTCTGGGATCTGCTGGCCCTC
CAGGTTTCCCTGGTGCTCCTGGACCTAAAGGAGAGATTGGAACTGCTGGACCCGCTGGCC
CATCTGGCCCTCAGGGACAGAGAGGAGAGCCTGGTTCCAATGGTGCTGTTGGTCCAGTTG
GCCCTCCTGGTAACCCCGGTGCTAATGGTATCGCCGGAGCCAAGGGAGCGTCTGGTACTC
CCGGAGTTGCTGGTGCTCCTGGTTTCCCCGGCCCCAGAGGAGGCCCCGGACCCCAGGGAG
CTGCTGGACCTTCTGGACCCAGAGGCCTTTCTGGTGACCCTGGACCTCTTGGAGTGA
>Gasteropelecus_sp._gill_3|017213|scaffold28082|m.29139
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------ATGGTCTCGATGGACGCAAAGGAGAGCCTGGTTCAG
CTGGTTCTAAGGGTGAGAATGGTGCTGCTGGTGCTAATGGAACCCCTGGACAAAGAGGTG
CTCGTGGTCTGCCTGGTGAGAGAGGTCGTGTTGGACCTGGTGGTCCAGCTGGTGCTCGTG
GTGCTGATGGTAACACTGGCCCTGCCGGCCCTGCTGGTCCTCTGGGAGCTGCTGGCGCTC
CAGGTTTCCCTGGTGCCCCAGGACCTAAAGGAGAGATTGGAGCTGCTGGTCCCACTGGCC
CATCTGGACCTCAGGGACAGAGAGGAGAGCCTGGACCCAATGGTGCTGTTGGCCCCGTTG
GTCCTGCTGGTAACCCTGGTGCCAATGGACTCAACGGAGCTAAGGGAGCTGCTGGCCTCC
CTGGAGTTGCTGGTGCTCCTGGTTTCCCCGGCCCTCGAGGAGGCCCTGGCCCCCAGGGAC
CAAGTGGTCCTTCTGGCCCCAGAGGCCTTGCTGGTGACCCTGGTGCCATTGGAATGA
>Lepidogalaxias_salamandroides_Head_2|017647|scaffold15845|m.21196
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------ATGGACGCAAAGGAGAGCCAGGTACAG
CCGGAGCTAAGGGCGAGAATGGTGCTCACGGTGCTAATGGAACCCCTGGTCAGATGGGTC
CTCGTGGCCTGCCTGGTGAGAGAGGACGTGCTGGCCCCCCTGGACCAGCTGGTGCTCGTG
GTGCCGACGGCAGCACTGGACCTTCCGGCCCTGCTGGCCCTCTGGGATCTGCTGGTCCTC
CAGGTTTCCCCGGTGCTCCAGGTCCCAAGGGAGAGCTCGGCCCCGCTGGTTCCACTGGTC
CATCTGGACCTCAGGGTTCGAGAGGTGAGCCCGGTACCAATGGCGCTGTTGGCCCAGTTG
GTCCCCCTGGTAACCCTGGTAACAATGGTCTGA---------------------------
------------------------------------------------------------
---------------------------------------------------------
>Melanotaenia_praecox_viscera_mixture_8|015325|scaffold20762|m.22839
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------atggacgtaaaggagagcctgggGCTG
CTGGCGCCAAGGGTGAGTCTGGTTCCCACGGAGCTCCTGGAAGTCCTGGACTGGCTGGAT
CACGTGGTCTGGCTGGTGAGAGAGGTCGTCCTGGCCCTGCTGGCCCTGCTGGTGCTCGTG
GTGCTGATGGTAACGTTGGACCTGCTGGTCCTGCTGGACCCTTGGGTGCTGCTGGTCCCC
CAGGCTTCCCCGGTGGCCCCGGCCCTAAGGGAGAGATTGGAACCGCTGGAGCCACTGGCC
CATCTGGACCTCAGGGAAGTAGAGGAGAGCCTGGACCCAATGGTGCTGTTGGCCCTGTTG
GACCCCCTGGTAACCCCGGTGCTAATGGTCTGA---------------------------
------------------------------------------------------------
---------------------------------------------------------
>Sargocentron_rubrum_gill_6|018470|scaffold27216|m.36028
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------ATGGACGCAAGGGAGAGCCTGGTGCTG
CTGGTGCCAAGGGTGAGAGTGGTGCCCATGGTGCTCCTGGAAGTTCTGGACTGGCTGGAG
CTCGTGGTCTGCCTGGTGAGAGAGGTCGTGTTGGCCCTGCTGGCCCTGCTGGTGCTCGTG
gtGCTGATGGCAACGTTGGACCCGCTGGTCCTGCTGGTCCTCTTGGCTCTGCTGGTCCCC
CAGGTTTCCCTGGTGGTCCCGGCCCCAAGGGAGAGGTTGGAGCTGCTGGAGCCAGTGGCC
CCGCTGGACCTCAGGGAGCAAGAGGAGAGCCTGGTCCCAATGGCGCTGTTGGCCCCGTTG
GTCCCGCTGGTAACCCTGGTGCTAATGGTCTGA---------------------------
------------------------------------------------------------
---------------------------------------------------------
>Synodus_sp._gill_5|005101|C583408|m.48126
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------ATGGACGCAAGGGAGAGGCTGGTGCTG
CTGGCGCCAAGGGTGAGACTGGTGCCCACGGTGCTGCCGGAACCCCTGGACTGGCTGGTT
CTCGCGGTCTGCCTGGTGAGAGAGGTCGCCCTGGTCCTGCTGGACCTGCTGGTGCCCGTG
GTGCTGATGGAAACGTTGGACCCGCTGGCCCTGCTGGTCCTCTTGGAGCTGCTGGTCCCC
CAGGTTTCCCTGGTGCTCCTGGCCCCAAGGGAGAGGTCGGACCTGCCGGAGCCTCAGGAC
CCACTGGAGCTCAGGGAGCAAGAGGAGAGCCCGGTCCCAATGGTGCCGTTGGACCCGTCG
GACCTGCCGGTAACCCCGGTGCCAATGGTCTGA---------------------------
------------------------------------------------------------
---------------------------------------------------------
