>Amblygaster_clupeoides|017271|TR29759|c1_g2_i1|m.51475
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------GCTAAGAAGGAAGGGGAATGGGACTGTCC
TACTTGTTGTGTCAGAAATCATGCCTCATCAAGTAGCTGTGCGTCATGTCAAACTCAGAA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------TCCATCAGGTGTTGGC----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--AAATTTGGCTCCCA---ATTTGCCAAGAAGGATGGACAGTGGGACTGTGATCAGTGCC
TTGTCAGAAATGAGCCAACGTCTTCAAAGTGTGTCTCTTGTCAAGCTCCTGGTCCT---G
TTCAACCACAGGATG---------------------------------------------
GATTAGCAGCTATGTTTGCGAAGAAAGATGGACAGTGGGACTGTGAGATCTGCTTGGTGA
GAAATGAG----------------------------------------------------
------------------------------------------------------------
-----GGCTCTGCCAGCCAGTGTGTCTCCTGCCAGACTCCCAACCCCAGTGCAAAAAACT
CAACTACTTCTGCACCATCAAGCTCCTCCTTCAGCTTTGGGACACAAACTAAAACC----
--AGCCAGGCCACTGGAACAGGAT------------TTGCAACTAGTGGCCACTTCCA-G
TTTGGTCAAAGTAAAGAGACTAGCTCCCAAGCACCCTTTAAATTTGAGC---------CC
CCT----------------------------------------GGCAGCAC-----AGGT
TTCTCTTTTTCA------ATCCCATCTGGTGGCTTTAAGTTTGGCACTCAGGAACCTGCT
TTGGAAACACAAGTCACAGAGAGTGAAACGGCTCCTCCTGGATCAGCATCAATGTTTCTG
AAAAATATTGCTGAACAACACAGAGAAAAAGAGAGAGAGAGTACCACATCCACAT-----
-------------TGACACCCTCTGTTGTGAAACCTGAACAAGAGGAAAACCCACTCTTC
CTCCCTAAGGCAGACTCATTCAGCTTTGCAGACCTGGCCAAATCTGGAGGAG---AGTTC
AAGTTTGGCCAAAAAGATCCATGTTTCAAAGGGTTTGCTGGGGCAGGTGAACAACTTTTC
TCTGCCCCTCAGATAAACC---AGAAAGCAGACATTTCTGTAGATCAAGATGATGAGGAC
ATGTACAAGACTGAAGAGAATGATGATATTCAGTTTGAGCCAGTGGTACAGATGCCCGAG
AAGGTAGAGCTGGTCACTGGTGAGGAAGACGAGGAGGTTCTTTACTGTCAACGTGTGAAA
CTCTTCAGATTTGACGCTGACACAAGTCAGTGGAAAGAGAGAGGGGTTGGCAACCTTAAG
ATTCTGAAGAACTCTGTGAATGGTAGGTTGAGGGTCCTAATGAGAAGAGAGCAAGTCCTG
AAGGTTTGCGCTAATCACTGGATCACCACAACGATGAATCTAAAGCCCCTCTCTGGGTCT
GAC---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>Distichodus_sexfasciatus_gill_4|024519|scaffold33895|m.43535
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------CAAATCCATCCC--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------TCTAATGCCTATGTTAATGGCAAGCTGGTGCAGCTCTAC
CGCTCTGATGGGCGCTTGGAGGATGCAGCAAGACACTGTCTCTCTGTGGAGAAGGATGAA
GTCTTGAAGCACAGCCTGGAATGGTACACCATCGCTGTTCACACTCTTCAGGAATACATG
GCTCAACCCAGCCTGGCATCTAACGAGAAGGCATGCCGCAAGTATAACAAGGAACTTCTG
TTGATGCGCTGTAATCTGCTGAGGCTTACACTTACAGAAAAAGGATGGCAAGAAAGCAAG
GATTTGCTTCTGAGTTTTGATCAGCAAATGCAGTCATTAAAGGACACTGCTACAAAGCAT
ATGGATGAGCTGTCTGAGACTTTCACCGAAATGAGAGGTCATCTGTATCTTTACGCTGGG
ACCCTGCTGCTGAAGATGGCTTTGGAAAAGGAGCAGCAGTGGAGAGCTGTGGTTCATTTG
GCTGCTCTTTGCTACCTTCTGGCTTATCAGGTTCCCAGGCCAATGTCGAAGCCTGAAAAG
GGTGACCTGGCTCCAGAAAATCCTCTGGAGTCTTTAGCTTGTTACCGCCAAAGCCAAGCA
GGACATATGCTACTGAACCTGAACAGCGATGCAGAAAGCTTTGTAAAGGAGGTTGTGGAG
CTGTTTGGCAACAGGAGCGGGCAGGGCAGTCTGTTTGAGATGCTCTACAACGTGCAGGTC
TCATCTGACCTCTCGTTCATTGGAAGTGAT---ACCTACAACATCAGCGCTCAGGTACCG
GGCGTGCATGATCTTGCCAAGTGGGATGACGGCTCCATTTCAAGTTTTGGAG---ATTTG
CAGCACCTGACATGGCTGGGCTTGCAGTGGGCTATGATGGGCCAGAGACCAGCTTTAAAA
GACTGGCTTAAGCAGCTTTTTCCTCGTCTAACTCTGGAGACCTTTAAAGTAGACACCAAT
GCACCAGAGTCCATTTGCCTGCTTGACCTTGAGGTATTTCTGTGTGGTGTAGTCTTCACC
AGTCATACTCAGCTACAGGAGACTGCAAAGATTTCTCCTAACTCACCGCTGG--------
-------ACCAGCCAAGATGTTTGCCTTTGCAGCTAATGAAGCTCCTGTACTCTACAAGA
CAAATAGAATGGTGGGACGCAGTCTACAGCCTCATTCACAAAAAAACAATACCAAATATG
TCTGGTAAACTGAGAATGATCGTCCAAAATGGGCTGAATACACTGCGAGCCAGAGAGAAA
CATGGTCTTCAGCCTGCATTACTCATCCACTGGGCCAGGCATCTCAGCGTAATGGGTGAT
GGAGTGAACTCCTACTATGACCAAAAAGAGTACGTAGGCCGCAGCGTCCACTACTGGAAT
GTCGTCCTTCCATTGCTGGAGAAAATCGAGAAGCGACGCTGCATCGCCGAACCTCTTGAT
CCGATGTTTATGCATTTTAAGAGTAAAGACATACAGATTTCTGACATCAAAGTCTATGAA
GAGGAGGCCATGATAGTTTTTGCAAACATCCTTGACATTGAGGGGAAAACTGACCAGGCT
ATCTCAAAACTAGAGAAACTCAATTCCATCTCTTCATACTGGCATCTTGCTCGGATCTAT
CAGAGGCTTTCTGAGGAGGCAGGGAATGGGGTTGAAGAAACTCAAGATATGTGCCTCAAC
TTTCTCCAACAGTTCAAGAAATACTTATCCAAGATCTACCATTCCAGTGCAGATGATGTG
GAGAAGCTGCCAGTGTCATTGGAGGAAGTCATGGACCTACTTAATGATGTCAATCAGCAG
CTTGGAGAGAACAGTGAGGCTGTGGATGGATGTG------------------AAGGACAT
CCTTTGACCTCTAGCCCAAGATCACTCGCAGAGCCGTCTGTAGCAAGTGCTCA---CAAC
TTTCCCATGCCATCCCCACCCAAAAGTGTACTTTCACCCTCCAAAAGACCGGTGATTTCT
CCCAAGAGTCCAAAAAATCCTCATTGGGTAGAGGATCAGAAGTCACTTTTGCAGTTGCTC
TGTCAACAAGTTGAGGCACTGAAGAATGAGGTTCATGACTTACGACACAACAGGTCAGAT
GCTGCCGAGTC---ATGTCATAGGTTATATGGAGCTAGTTATTCAGCAGAGACTCTTCAG
GAACCATTTCCAGCAACACAATCATTTCATGGAGCGCCTCTCACAGTTGCAACCACAGGT
CCCTCAATGTACCACAACCAGTCATCAGGGTATAATTCGCAGCACCTTCTCCGTCCTGCT
GCTAACGTGACCACAACAAAGGCACCAGTCTATGCAGTGACTCGT---CTCCCACCACAG
CAAATATATGCCTACCCTCAGCCAACGCATACCCCACCGCTTCAAACAACAT------GC
ATGTA---CACTCAAGAGCAGGTTTTTGGTACACCGCTTAGGTTTGAGTCACCAGCCACA
TCCCTGCTCTCCCCCTACACTGAAGAATATGGCAGCCATTCTGTTTCCCAACCATCAACG
AATCCGACATTGCCGGAACCCGGGTACTTCACCAAGCCACCCGTCATACCAGCACAATCC
TATAAGAGCACGGAAGGCAAGTCAGCCGATTT---GAAGATGAGCTTAGGCCAGCACATT
CCTGCTGAAACAACGAAGATTTCCACATTTGGAAGTGGACCTGCAGCCCACACCACCCCC
ACAGCAGCGGCTTTCAAGTTCAATTCAAATTTCAAATCTAATGATGGAGACTTCACCTTC
TCATCAGCACAAGTGAGAAACAACAGTGAAAGTCTTTTGGGTCTCCTCACCTCAGACATT
CCACCCAGAAGCGAAGT---------GCAAGCGCCGAAAGTTCAAGACCAGACAGCAAGT
CAGAGTGGAGGATTTAGTTTTGGAAATAAATCTGTGATAGGATTTTCCTTTACTGACGGT
GCCCAGGTCAAAGCAA------ACTTATTTGGAAAACCTGAACAGCCATTCAGTTTTGCA
AATGTGTCCAAGCCAGAA---TCTGGGGCATTAAACATGGTGGAAACTGATGATAAATGT
GTGGAAAGTG---ATGACAGCACGCATGTTGAAGAGGATGAGGATGGACCCCATTTTGAG
CCTATTGTGCCACTTCCTGACAAAGTTGACGTGAAAACTGGTGAAGAGGAAGAAGAAGAG
ATATTTTGTAACAGGGCAAAACTGTTTCGATTTGAGACAGAAGCGAAAGAATGGAAAGAA
AGAGGCATCGGAAGCATCAAAATTCTGAAACACAAAACATCAGGCAAATTCCGAGTATTG
ATGAGGAGGGAGCAAGTTCTGAAAATCTGTGCGAACCATTACATCACTCCAGACATGGTT
CTCAAACCAAATGCTGGCTCTGACAAGTCATGGGTGTGGTATGCTATTGACTATGCTGAC
GAAATGCCAAAGACAGAACAGCTAGCCATTCGCTTCAAAACTGCAGATGAAGCACTGGCG
TTCAAACGGAAATTTGAGGAGGCACAGAAAGAAACGGTTAAATCTTCACAAATGCCAGAT
CAA------CATGAAAAA----------CTGTCAAAGCCACCAGCTGTTGG---GGAACC
AAGCAAAAAAATAGATCTGAAAACACAGTTTGCTAAGAAGGAAGGTGAATGGGATTGTAG
TGTATGCTGCGTTAGAAATGCGTCTTCCTCCAAAGTGTGTGTTGCTTGTAGCAGTCCTGG
TCCTAGTGATGGTGTGAAGCCTGAAACTAAACCAGCAGAGCAATTCAGAAGTACTTCTGT
GGTGACTTCCTCTGCATCAGTCTTTACTTTTGGACTTAGTGAAAGCTCTATGAAGGATGC
CAGTCCAGATGCTAGCTTTAAGGGATTTGGGTCTC---------AGATTCCATTTTCTTT
TAAGTTTGG----AACACAGGAACCTGTTGCAGCCTTCAGCCAGCCTGACAAAAGGTCTG
GTCCAGGGGAGCCCTCGCAAGATAAATCTGTGTTGCCTCAGAGTTCTTCCATGCAAGTGG
CAAGCAGTACAACaactgctaaatcatctggtttttCATTTGGGTCTGGCTTTGGGTCTC
AGTTTTCTAAGAAACCAGGTCAGTGGGATTGTCCCACTTGTGCAGTGAGGAATGAGGCGT
CTGCACGCATTTGTGTTGCATGTCAGACTTCAGATCCCTCGGTTAAAACTTTTTCGGCTC
CAGAAGCTG---------------------TCAAAGTTCGTCCAAATTCCTCCTTGGACT
CTGGCCTTGATTTT------AGTGATAAGAAAAATGGACAGTGGGATTGCGATTCCTGTC
TAGTCAGGAACGATGCAGCGGCTACAGAGTGCGTTTCTTGCCAGGCCCCATGCAGCAGTG
GGAAATTTCAAGAACCCCCTCAAGGTG---------------------------------
---GCTTGGCAATGTTTGGTAAAAAAGAGGGGCAATGGGATTGTGATGCTTGTCTGGTGA
GGAATGAG----------------------------------------------------
------------------------------------------------------------
-----GCCACATCTACTCACTGTGTCTCCTGTCAGACACCTAATGCAAATCCAAAAAGTA
C---TTTGGCGGAACCAGCCCACTCCTCATTTAGCTTTAGTTTTGGAAATAAAGGT----
--AACCAACCTGCCACTGCAGGATTTAAAGCAACCTTTAGCACCCCTG---CTTTCCA-G
TTTGGCCAAAGTATAAACA---------------------------------------CA
CCTA------CTCAAGGGGAAGTGTCTTCA-------------AGTACTCC-----AAAT
TTTTCTTTTACA------ATACCTGCCAGTGGACTTAAGTTTGGCCTTAAGGGATCAGAA
TCAAAGCCTGCAGAGAGTCAAACACAAA---------GTCATTTTGCTTCAGCGTTTCTA
CAAAATATTGCTGAGCAACACAGAGAAGGAAGCATAGAGGAATCCTCTTCATCT------
------------------------------GCTCCTAGTGATGATGACAAACCATTTCTT
ACAGGACAAAGTAGCACATTCAGTTTTGCGGACTTGGCAAAGTCTTCAGAGGGTCAATTT
CAGTTTGGTCAAAGTGATCCCAGTTTCAGAGGATTTGCAGGGGCTGGCGAGCAACTTTTC
ATTTCGTTGACACAAAAGC---AAAATGCAGAAACCTCTGCCGATCAAGAGGAGGACGAG
GTGTACAAAACTGAGGAGAATGATGATATTCAGTTTGAACCTGTGGTTAAGATGCCTGAG
AAAGTCGACATTGTTACCGGCGAAGAGAATGAGGAATGCCTGTATACACATCGCGTTAAG
CTCTTCAGGTTTGACACAGAGGCTCAGCAGTGGAAAGAAAGAGGAGTTGGGAATCTTAAA
ATTCTTAAAAACAGTACAAATGGGAGACTTAGAGTTCTTATGAGGAGAGAGCAAGTGCTG
AAAGTTTGCGCTAATCACTGGATCACTACCACAATGAATTTAAAGCCCCTTTCTGGGTCA
GATCGGGCTTGGATGTGGCTAGCTAATGACTTCTCAGAGGGCGATGCCAAACTGGAACAG
CTGGCTGCCAAGTTCAAAACCCCAGAACTTGCAGAGGAGTTTAAGCAAAAGTTTGAGGAC
TGTCAACGTCTCCTTTTAGACATTCCTCTACAGACTCCTCATAAGCTTTCAAACTCGGAC
AGAACAGCGCATCTCATTCAGAAAGCTGAGGAAATGAAATCCGGCCTCAAAGACCTGAAG
ACGTTTTTAACTTATGATGGAATTATAACCAAGGATAGCGA---------AGGTACTTCA
GAAGCTGCTGATGACCGGTCCGAGATTATGACCAAAGCCCCTGCTAGAACTACTGAACCC
ACTTTGGAATGGGACAATTATGATTTACATGAAGG---TCACGATGAGAGTGCTGACTTG
TCTGTGTACGCCTCTCCTCTGGCTAGTAGTCCG------AAAAACTTGTTCCGCTTCGGA
GAATCGTCTACTGGCTTTAGTTTCCACTTCCAACCCGTTCTTAGTCCTTCAAAATCACCT
GCCAAACTTAACCAGAGTGGCATGTCTGCGGGCACAGACGACGAACAAGAACTGAGTCAA
---GAGGAAAGAGATGGCCAGTACTTTGAACCAGTTGTACCTTTACCAGACCTTGTTAAG
ATTTCGACTGGAGAGGAGAATGAACAGGTGGTGTTCAGTCACAGAGCCAAGTTATTTCGT
TATGACAAAAACCTTAGTCAGTGGAAGGAGAGAGGTATAGGAGACCTCAAAATTCTGCAA
AACTATGATACTAAACGTGCAAGACTTATCATGAGACGGGATCAGGTGCTCAAGTTGTGT
GCAAACCACTGGATAACCTCAGATATGAAACTCGAGGCAATGAAGGGAACTGAAAAAGCA
TGGATCTGGAGTGCCTATGACTTTGCCGAGGG---CGATGGAAAGGTGGAGCAGTTAGCC
GTGCGCTTCAAACTGCAGGACATGGCAAATTCCTTTAAAGAATTCTTTGAAAAAGCCAGG
GATGCTCAGGAACAAGGAATTCTTC---------------------TAGCCACACCTTCT
AAAAGTGAAACCCTGAGCCT---------------------GGACTCCACTTGTGGTAAA
GTTGCTATTGCAGTCTTCGAGGAGGCTACCAAAGAATGCACTGAACAGCTGGACGAAAGC
------ACAAACAGTGAAAAAGCTGGAGCAGCT------CAAACGCCAGAGAGCATTACA
AAAGCAGTGGTCTCTCCCCCTAAATTTGTCTTCGGAACAGACTCTGTGCAGAAAATATTT
GGAAGCCCCTTACACTGCAAAGATAGTGTTCCCGTCGGAGCTG--AGAGTTCCAGAGA-T
AATGCGTCAAGCGGTGTTTCCAGCTCCAAATCTTTTGGGAGCAG---TCCAGAGCCGACC
ACAGCT---------CTGTTCCAAGTACCTGAAAGAGCTCAAACCTCCACCCAGCAAGAT
GGAGAGG------------AGAGTGATTCTGATGTTGAAGTTGTGTTTGAACTC------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>Gasteropelecus_sp._gill_3|020436|scaffold32250|m.35103
GGGACGGCCATGTTTGTTAGGCTTGGCGGAGAGCGCGTTCACGACCAACGTTCAAACTCT
CCGGCGGCGTCTGTGGATTTAGTTGAGCCGAGGTCGCCGGCCGCCCCAGAGACCGGGGGC
AGCGCGTCCGCAGCCATGAGGCGCAGTAAAGCCGACGTCGAGCGCTACATTTCTTCAGTG
CAGAGCCTCTCTCCTTCTCAGACGGAGAAACCAGTAAAAGGATTTTTATTTGCAAAATTG
TACTATGAAGCCAAGGAGTATGAACTTGCTAAAAGGCATGTATCAGCTTATTTAACAGTA
CAGGTCAGAGATCCAAAGGCACACAGATTCCTTGGTCAGCTGTATGAAAGAGAAGGTGAA
GTTGAAAAAGCTGTTGGCTGTTACAAGCGTTCAGTGGATCTGAATCCATCCCAGAGAGAC
TTGGTCCTGAAAGTGGCTGAACTTTTGTGCAGTAAACCAGAACTTGACAGCAGGGCAGAA
TTCTGGGTGGAGAGAGCCGCTAAGCTTTTGCCTGGTCATCCTGCTGTCTTTGACCTCAGG
GAGAAATTGCTCAGTGCAAAGGGACAGCAAGGCTGGAACCAACTCTATGACCTTCTACAG
TCAGAGCTTCAACTGCGCCCCTCCGATGTCCTTGTTAACAGCAAACTGGTGCAGCTCTAC
TGCTCTGATAGCCGTCTAGAGGATGCAGTCAAGCATTGTCTGTCTGTGGAAAGATGTGGA
TTACTGAGACACAGCCTTAACTGGTATTCCACAGTTGTCCACACGATCCAGGAATACCTG
TCTCAACCCAGTGTGTGCTCCAATGAGAAAGTGTGCCGCAAATTTCAGAAGGAGCTTTTG
TTGGCTCACAACAATCTTTTGAGGCTCAAACTTTCAGAAAAAGGATGGCAGGAAAGTGTG
GCTGCATTTCAGATTTTTGACCGTGCTATGCAGTCCTTAAAACCCACTGCCACAAATGTG
TCTGATGAACTATCGGAGGTCTTCACAGAAATTAGAGGTCATCTGTATCTTTATGCTGGC
ACCCTTTTGCTGAAGATGGCCTTAGAAAAAAAGCACCACTGGAGAGCTGTTATTCATTTA
GCGGGGTTTTGTTACCTTTTAGCATATCAGGTTCCCAGACCAAAGAAAAAGCCTGAGAAA
GGAGACCAGACATCATCAAAACATCTAGAGTCATTGGCTTGTTATCGTCAAAGTCAAGCA
GGCCATATGTTGCTGAATCTGGACAAGGAGACGGAGCACTTTGTAAAGGAGGTGGTGGAA
ATCTTTGGGAACAGAAGTGGGCTGGAAAGTCTGACTGATATGCTGTTTGGATCACAAGGC
ACTTCTAGCTTTTCATTCATTGAAAACGATGTCATTGGTTTCATCACTGCAAAGGGACCA
GATATAAAAGAACTCTCCAAGTGGGACAATGATTCCATCTTGCACTATGGAG---ATTTG
CAGTACCTATCTTGGTTGGGCTTGCAGTGGTCAATGATGGGTGAGAGGCCAGCCTTGAAA
GAATGGCTTAAGCAGCTCTTTCCTCGTCTCACTCTGGAAACTTTTAAACTGGACACAAAC
ACACCAGAGTCAATCTGTCTGCTTGACCTTGAGGTCTTTTTGTGTGGTGTGGTGTTCACA
AGTCATACTCAACTGCAGGAAACTGCAAAGATTTCTGCTAACTCCCCACTGC--------
-------ATGAGCCAAGATGCTTGCCTTTGCAGCTCATTAAACTTTTGACCTCAGAGAGA
CAGAGAGAGTGGTGGGATGCAGTCTACAGCCTCATTCATAAAAAAACAGTTCCTAATATG
TCTGCGAAACTGCGAATGATTGTCCAGCATGGCTTGAACACACTGCGAGCAAGAGAGAAA
CATGGCCTTCAACCTGCACTGCTCATTCACTGGGCTAGGCATCTCAGCATAGCGGGTGAT
GGAGTGAACTCCTACTATGACCAGAAAGAGTATGTTGGCCGTAGTGTCCACTACTGGAAT
GTGGTGAAGCCCTTGCTGGAGAAAATTGAAAAGAGGCGCTGCATTGCTGAGCCCCTTGAT
CCAGTGTTCATGCATTTTAACAGTAAAGACATACAGATTTCTGAAGTTAAAATGTATGAA
GAGGAGGCCACAATTGCTTCTGCTACTTTACTTGACATTGAGGGCAAAACTGATCAGGCC
ATCTTCAAACTGGAGACCTTAGATTGCATCTCCTCCCACTGGCATCTTGCTCGGATCTAT
CGGAGGCTTTCTGAGGAGGCAGGAAATGGTGTTGAAGAAACCCAAGACAGGTGTATGAAC
TTTCTTCGGGAGTTTAAAAAATACTTATCAAAGATCTACCATGCCAGTGCAGATGATATG
GAAAAGCTGCCTGTTTCGATGGAGGAAATTATGGATTTGCTCAGTGATGTCAATAATCAG
CTTGGAGAGAGCGGAGAACCTTTGGACACAGTTC------------------ATGGACTG
CCAATAACCTCTAGCCCAAGATCATTTGCAGATTCAGCTGTGGCTAGTTCTCA---GAAA
TTTTCTATGACCTCTCCTGCCAAAAGCGTACTCTCCCCCTCCAAAAGATCAGTGTTTTCT
CCCAAAACACC------CCCCCATTGGGTGGAGGATCAGAAGTCTCTCTTGAAAATGCTC
TGCGACCAAGTTGAGGCTTTAAAGAACGAGGTTCATGACTTGAGGCACAATACATCCGAG
TCAACAGAGCCCC------------CATATAGTAGAGTCTATACAGGAGAATCCATGCAG
GAACCCTTTTCAGCAACACACCCATTCCATGCAGTTCCACTCACAGTTGCCACCACAGGT
CCTTCAGGTTACCACAATCAATCACCTGCATATAACTCACAGTATCTTCTTCGCCCTGCT
CCCAGTGTAACACCAACAAAGGCACCTGCCTATGCAGTGAATCGA---CTCCCTCATCAA
CATATGTATGCGTACCAACAGCAAACACACACCCCACCTCTTCAAACTACAT------GC
ATGTA---TCCACAAGACCAGGTCTTTCCTACTCCAATTAGATTTGAG------ACCACA
AGCTTACTCTCCCCTTACAATGAAGAATTCTGCAATGTTAATGCTTCTCAATGTTCTGCA
AATCCTGCCTTGCCAGAGCCTGGGTACTTCACAAAACCCCCTGTCATACCTGCCCAGTCC
TACAAAAGCAGTGAAGGCAAATC-------------------------------------
--------------------GTCTTTTGTTGGGGCTGAAA---------AGGCAACTCCA
CCATCAACTGCTTTCAAGTTCAATTCAAATTTCAAATCAAATGATGGGGACTTTACTTTC
TCGTCTGCTAATGTAAAAAATAACAGTGAAAGCCTTTTGGAGCTTCTGACCTCAGACATT
CCACCCAGAACTGAAGGACCTTTAGGTCTCAAGTCTCAGACACAAGAACAGCCACCTAGT
------GGAATCTTCACTTTTAAAACTGCATCCACCCCAGGATTTTCATTTACTGATGGA
TCCCAGGGCAAGAACA------TTTTCTTTGCTAAACCAGAGGAGCCATTTAACTTTGCA
AGTATGACCAAACTGGTG---CCTGGAACAGAAAAAGAG---GAAAACTGTGAGAAATGT
GTGGAAAGTG---AGGACAGCACCCATGGGGAAGAGGATGAGGATGGACCCCATTTTGAG
CCTATTGTGCCCCTACCTGACAAGGTTGATGTAAAAACAGGCGAAGAAGAGGAAGAGGAG
ATGTTCTGTAATAGAGCAAAATTGTTTCGATTTGAGGCTGAAACAAAAGAATGGAAAGAG
CGAGGAATCGGGAGCATCAAAATCCTGAAACACAAAACGTCTGGAAAATGTCGACTGTTA
ATGAGGAGGGAGCAAGTCCTGAAAATTTGTGCAAATCATTACATCACTTCAGAGATGGTT
TTAAAGCCAAATGCAGGATCTGATAAATCATGGGTGTGGTATGCTATTGACTATGCTGAT
GAAATGCCCAAGACGGAACAACTGGCTATTCGCTTCAAAACTGCAGATGAGGCTTTGTTA
TTTAAACTGAAATTTGAAGAGGCGCAGAGAGCTATGCCTAAATGTGTAGAAACACAAGAT
CAG------CAGAAGGAAAGTG------ATGCCAAGTTGTCTACACCACA----GGGATT
AGGCAAAAAAAAGGATCTGAAAACTCTTTTTGCCAAAAAGGAAGGTGAATGGGATTGCAG
TGTCTGCTGTGTAAGGAACAATCAGTCAGTTAAGACATGTGTGGCTTGTAATAATCCTGG
TCCGTTTGACCTTACAAAATCCGAATCTAAACCATCTGAGGGATTCCGAAATGCCCCTGC
TTCTACTCCCTCTTCATGTGCCTTTACTTTTGGAATTACTGG---------GAAAGATAC
CAGCTCTGATAGCATGTCCAAGGGATTTGGAGTTC---------ACATTCCGTTTTCGTT
TAAATTTGG----AACACA-----------------------------------------
------------------------------------------------------------
-ACCTGATGCCACATCCAGTAAAAA-----------------------------------
----TGAAAAAAAGCCAGATCAAT---------------------------TCGGACCTT
CTACAGAGACATCTGTGTCTGCACAGAGTTTAGCTCCCTCTGTGCAAGTAGGAAGCAAAT
CAAGTGTTGCACCG---------------------------TCAAATTTCTCCTTTGACT
TGGGATCTGGTCTTGATCGCTTTGCCAAAAAAGAGGGTCAATGGGATTGTGATGTTTGCT
TAGTTAGGAATGAAGCCTCTGCCTCAAAGTGCATCTCTTGTCAGACCCAGTGTAGCATTG
AAAAAAAACAAGTGCCACCTC---------------------------------------
---TTTTGGCCATGTTTGGTAAAAAGGAAGGACAGTGGGATTGTGACACTTGTCTAGTAA
GAAATGAA----------------------------------------------------
------------------------------------------------------------
-----GGCACATCTAGTCATTGTGTGTCATGCCAGCAACCTA------ATGCAAAAAGCT
C---TTCAGTGGCCCCAACATCTTCCTCATTTAGCTTCAGCATTCAGGAAAAACAC----
--ACCCAACCTGCCCCTACAGTATTTAAAACCAACTTTAATGCTAGCAGCACTTTTCA-G
TTCGGTCAGAGTCAGAAAGATACCAC---ATCAGCTTTTAAATTTGAGC---------CT
TCTGCAG---CAAAAGCTGAAACATCTTCA-------------AGCACTTC-----AAAT
TTTTCCTTTTCAATGTCTGTACCTTCGAACAGCTTCAAGTTCGATCCTATGGAACAAGAA
TCAAAAAAGTCAGTCAGTCAAGCACAAA---------GTTCATCTGCCTCAGGTTTTCTA
AAAAATATTGCTGAACAGCACAGAGAGAAGGGAAAAGAGATGAGCTCTTCATCTTCT---
------------GTTCAGTCACTGAATGCGGCTAGTACTGATGATGACAATCCCCTTTTT
AAAGAGAAGTTGAACACCTTTAGTTTTGCAGACTTGGCAAGCTCTACACAAGGTCACTTC
CAGTTTGGTCAAAAGGATCCCAGTTTCAAAGGCTTTGAAGGAGCTGGCGAGCAACTTTTT
ACTTCATCTC---CAGGCC---AAAAGGATGATACCTTT---------GATCAAGAAGAC
ATGTATAAAACTGAAGAGAATGACGATATCCAGTTTGAACCAGTAGTCAAGATGCCTGAG
AAAGTTGAACTTGTTACAGGGGAAGAAGATGAGAAATGTCTCCACTCAAACCGTGTTAAG
CTTTTCAGATTTGATCCTGAAACTCAACAGTGGAAGGAAAGGGGGGTTGGAAACCTTAAA
CTTCTTAAAAATAATACAAATGGTCGGCTTAGAGTTCTCATGAGAAGAGAGCAAGTGTTG
AAGGTTTGCGCGAATCACTGGATCACTACCACAATGAATTTGAAGCCCCTTTCTGGATCA
GATCGAGCATGGATGTGGATGGCTAATGATTTTTCAGATGGAGATGCCAGGTTGGAACAA
TTAGCTGCCAAATTTAAAACACCAGAACTTGCAGAAGAGTTCAAACAGAGGTTTGAGGAG
TGTCAGCGATTGCTGTTGGACATTCCTTTGCAGACCCCTCACAAGCTTACAAATTC---C
AGAACAGCCCATCTAATTAAGAAGGCTGAGGAAATGAAGTCTGGTCTCAAGGACCTCAAG
TCGTTCTTGACTTCTGATGTTAATAAAGCCGTGGCAGAAGA---------AAATATTGCT
ACAGTTGCAAACATT---TCTGAGTTCA-----ACAAGCCACACT-------------CT
ACTTTAGAATGGGACAATTATGATTTGCAAAAAGGCGTTCATGATGAAAGTTCAGACACC
TCCATGTATGCCTCTCTGCTGTCTAGTAGTCCGCTGCAAAAAAATCTGTTCCGTTTTGGA
GAGTCATCTGCAGGGTTTAGTTTCAGTTTCCAGCCCGTACTTAGTCCTTCAAAATCCCCA
ACCAAACTAAACCATAGCAGGACTTCTGTTGGCACAGATGATGAGCAAGAAACAACTCAA
GAAGAGGAAAGAGATGGCCAGTACTTTGAGCCAGTTGTACCTTTGCCCGATCTTATTGAG
ATTTCAACTGGAGAAGAGAATGAGCAGATAATTTTCAGTCACAGGGCAAAATTATATCGC
TATGATAAAGACCTTAGCCAGTGGAAGGAGAGAGGCATCGGAGACCTTAAGATTCTACAA
AATTATGATACTAAACGCGCAAGACTTGTGATGAGGCGGGACCAGGTCCTCAAACTGTGT
GCAAACCACTGGATATCTTCAGATATGAAGCTTGATGCAATGAAAGGAACTGAAAAAGCC
TGGATTTGGAGTGCTTATGATTTTGCTGAAGG---AGAAGGAACAGTAGAGCAGTTAGCT
GTGCGCTTCAAATTGCAAGAAACTGCTCATGCCTTCAAAGATTCATTTGAGAAAGCCAAA
GATGCTCAGGAAAGGGGTGTTCTTC---------------------TTGCATCTCCTAAA
GATACTGTGGCTTT---------------------------AGAGGCAATCTGTGGTAAA
GCTGCCATTGCGGTCCTTGAGGAAACAACGAGAGAACGGACTGAAGAGTCTTATGAATAT
AGTCATACACCTAGGGGCAAAATTGCAGAAGAT------GTCAGCCCACAAAGTTCCTCT
AAAAAAGTGGTGTCTCCCCCAAAGTTTGTCTTTGGTTCAGACTCTGTGCAGAAAATATTT
GGAAGCCCAGTGCTCTCTAAAGATGAGGCTCTGGAACAGCCTGCAGCAGTGCCAGCGACC
AAGGAATCAAGCAGTGCTTCTGACTCCAAAACCTGCAG---------TCCAGCATCAGTT
GTTTCT---------CCATTCAGAGTCCCAGAAAAAGTTCCTTCTCAAAGCCACCCAGAT
ACACAGGATCGCATAGACCAGAGTGACTTGGACATTGAAATCGTGTTTGAACGCCAGCCG
ACTAAAGAACAGGCAAAACTAGCCCAAAAGCTAATGCTACCACCTGCATTCTTTATTTTC
AAAAATGAGCCAGGATATGTGAGCGATG---AACCTGATGATGAAGACTATGAAACTGCA
GTAAGAAATCTGAAAGGAAAGTTGTACCAGGATTTGCCT---------------ATACGT
CACTGTGCTCTGGCTAGTGGATCTGCAAAGGACCCCGACTGTGTACTTGTCTGGGAGAAG
AAACCAACCCTGGAAGAGGAGAGAAGAGCCAAGAGTCTTCAGCTTCCCCCCACCTTCTTC
TGTGG---GGCTGGTAGTGATACAGATACCGAGTCTGACAAGACTGATGACTTTGGAACA
GAGCTTCGAAAAGTACAGCAAGCTCAGGATG---ATACGAGTACATCATCCCCTACAACC
AGCA-----GAGAGACCACTGAGGCATCCCCAGACCATAGA-------------------
-------GCCACAGCAGATGTATGCCCCATTGATCTCTCTACAAAGA--ACCATGAAGCT
GAAGCCCAA-------------------------ACAGGCTCAATTATCACCCAAGATAC
CACTCCAGGTTTTACTTTTGGCTCAAGGGGTGAATTTTCATTTGCCGACTTGGCAAAGAA
TTCGAATGAATTTGCTTTTGGGAAAACGGATTCTAACTTTACTTGGGCAAATGCTGGGGC
TGTACTCTTCGGTGGTTCTGCAG------CAACACACCAGAATCAGAATGATCATGAGGA
GGGAAGTGATGATGACGAGGCTTCCAACAATGCAGACATTCATTTTGAACCAGTTGTTTC
CCTCCCAGAGGTTGAAGTCAAGTCTGGTGAGGAGGATGAAGAGATTATCTTCAAAGGGAG
GACAAAGCTTTACAGATGGGACCGTGATTTGAACCAGTGGAAAGAGCGAGGGGTTGGTGA
CTTGAAGATCCTCTTCCATCCAATTAAAAATTGCTACCGTGTACTTATGAGGCGTGAGCA
GGTCTTGAAGGTCTGTGCCAACCACACAATCACCGAGGCTATGGAACTGAAGCCGATGAA
CACCTCTGCTAATGCGCTTGTTTGGACAGCTAATGACTATGCAGAAGGGGATGCAAAGGT
GGAACAGCTTGCGGCCAAGTTCAAGAACCCTGAACTTGCGGAGTCCTTCAGGAAAGCCTT
CAGAGAATGTCAGAGTCGCATGGGTCA----AGCAGATGTTTCCCAGTCT----------
----TCCAGGATCACAGAACTTTCTAGACCAAGCAACCCTTTGGTCTTCTTCACTGTCTC
TGCTGATGGGGATATTATTGGCAAGATTACCATTGACCTTTTTGCTCACATTGTTCCTAA
AACTGCAGAGAACTTCAGAGCTTTATGCACTGGGGAAAAAGGCTTTGGTTACCGTGATTC
AGTTTTTCACAGGATAATCCCTGACTTCATGTGTCAGGGTGGTGACATTACCAACCAGGA
CGGCTCCGGTGGAAAGTCCATCTATGGGGGAAAGTTTGAAGACGAAAACTTTGATGTTAG
GCACACTGGACCAGGCCTGCTGTCTATGGCCAATCGCGGCAGAGACACTAACAACTCCCA
GTTTTTCATCACCCTGAAAAAAGCAGAGCACTTAGACTTCAAGCATGTTGCTTTTGGTTT
TATCAAAGAAGGCATGAATGTTGTGAAACAGATGGGGGAGCTAGGTTCTAAAAGTGGTAA
GCCAATTAAAACGCTAAAGATTGTAGATTGTGGACAGCTGTAA
>Melanotaenia_praecox_viscera_mixture_8|019186|scaffold7516|m.6439
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------CCTGTTCAGCCA
CCAAAGAGTGTCGAGGGAAAGCCTGTAGACTTCGGGAAGCTCTCCTTCAACCAGCAGG--
----TTGAAGTCCCTAGATTGCCAAGTTTTGGCACAGGAGCCACTGCCCAGTCCACAC--
-CTTCGACCGCTTTTAAATTCAATTCCAACTTCAAATCCAATGATGGCGATTTCACTTTC
TCTGCTTCCCAAGCCAAG---CACAGCGAAAGTTTGCTTGGTTTACTCACATCAGACATT
CCCACAAAAACAGATGTTCT------AGAGAAGCATCCAGCCCAGGAGCAACCCCCTAGC
CAATCAAATATCTTCACCTTTGGCAATAAAAATATTACAAGCTTCTCCTTTGTTGATGGT
GCACAGAACACAGCCAGCGGAGGTATTTTTGGGAAGGTGGAGCAGCCATTTAAATTTGGG
GAAGTCTCCAAGCCAGTG---TTTGGTGTTGATATGCCTACAGCAGAGCAGGAGCGAGCT
GCTGAAAGTGACAATGACAGCACTCACGCTGAGGAAGATGAAGATGGGCCCCACTTTGAA
CCTATTGTACCTCTTCCTGATAAGGTAGATGTGAAAACAGGCGAGGAAGAGGAGGAGGAA
ATGTTTTGCAACAGGGCAAAGTTGTACAGATTTGATGCAGAGACAAAAGAGTGGAAAGAA
AGGGGCATTGGCAATGTTAAAATCCTCAGACACAACACTAAAGGGAAGGTCCGCCTCTTG
ATGAGAAGAGAACAAGTCCTGAAGATCTGTGCAAACCATTACATCACTGCTGATATGTTC
CTGAAACCAAATGCTGGCTCTGACAAATCCTGGGTGTGGAATGCCATTGATTATGCGGAT
GAAGAGCCGAAGCCCGAACAACTGGCCATCCGCTTTAAAACAGTGGATGAAGCTTCTCTA
TTTAAAGCCAAGTTTGAGGAAGCCCAAAAAGTAGAAACCAAATCCCCAGAAAAGCACACT
CAG------CAAGAGAGGAAAGAGGAGAGCTCAAAAGATTC-------------------
---------AGCTTCACTGGCAGCCCAGTTTGCACTTAAAGAAGGGGAATGGGAGTGCAC
TGTGTGCTGTGTGAGAAATAAACCCACAGATGTGCATTGTGTTGCATGTCAATCTCCTAA
TCCCCAATCTTCATCAAAACCAGACATTAAGACTGCTGGTGAAACCAAAA----------
--------------CTAGTCCATTTACTTTCAAGTTTGGTACTGATTCATCAAAACCGAG
CAGTTCTGGCTCTAAATTTACTGGTTTTGGTGCTTTTGGAGCCTCTGTACCCTCCACGTT
TACATTTGG------TATC-----------------------------------------
-----------------------------------------AGCTCCTCAAAACCAG---
---CCGACACAGCTACAA---------------ATCCATTTAGTTTTAGCTTTGGGTCAC
AGTCTGCCAAAAAGCCGGGACAGTGGGACTGCGACAAGTGTTCTGCAAAGAACGAGGCCT
CTGCAGACAGTTGTGTTTCTTGTAAAGCTCTTAAAACTGCAGGTAAAACAACTGTCACAG
CACAAGCACCACCAGCTACAGATGAGCCACCAACACAGCCCTCTGTTTCTTCTGTTGATG
GTGGGTTTGGTGCACT---GTTTAGCAAGAAGCCTGGACAGTGGGACTGTGATGTGTGTG
AAGTGAGAAATGAAGCATCTGCTGATAAATGTGTGGCGTGTAGCAGCCCAAACCCTGCTG
CAAAATCAAAAGACGGGGCCCAAGCAAAGTCGAA---------TCTAACAGCAGCATCAG
GATTTGGGGCTGATCTTTCCGAGAAAGGGGGGCAGTGGGACTGCAACGCCTGCCTGGTTA
GAAATGAAGCATCTGCAACCAAATGTGTTTCCTGCAATTCTTCCAACGACAATCAATCTT
TAG------------------------------AGNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNGCTTCTGCCAATAAATGTGTAGCATGTCAGACCCCAAATCCCAATGCTAAAGGCA
CAAGTAGTTCTGCCCCCTCAGCCTCTACCTTCAGTTTTACCTTTGGAACCAAGGGCTCAT
CAagccAGCCTGCTCCAACTGGATTTTCAGTGCCATTTGGAAGTGGCAGCACTTTTCA-G
TTTGGTCAAAAGGAAGATGAAAGCTC---AGCTTCATTTAAGTTTGAAG---------CT
CCTC---------AGTCTGCAGCAACTACAA----------CTAGTTCTTC-----AGGC
TTCTCTTTCACGATGCCTATTTCAGCTGGTGGCTTCAAATTTGGTATTCANNNNNNNNNN
NNNNNNNNNNNNNNN----------------------NNGGGTCAGCCTCCAGTTTTCTT
AAGAGCATTGCTGACAAACACAAGGAGAAAGAACATGCGCTGG-----------------
----------------CACCTTCAACAGCCCAAACAGACCAGGATCAGAATCCA------
------------------------TTAA--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>Pantodon_buncholzi_mixed|015095|scaffold17917|m.24819
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------TGGGATTGCAC
TACGTGTTTAGTAAGAAACGAGGGCACCGCCAGCGTTTGTGTCTCTTGTCAATCTGCAAA
ACCTGGTGAAC------------------------------------AAAGCACAACTGC
AGCTGCACCCTCAGCTTCAGCTTTCAACTTTAACTTCAGTAG-------TAAAAATGTAC
CATCTCAGCCTGCAA---------------------------------------------
-ACACTGGG---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------TTAGAAG
CGAGGTTTGATACC----------------------AGCAGTAAATTTATGGCAT-----
------------------------------------------------------TCAGTG
AAAAGGCTGAAAAGATCTCCCCAGCAAACTTCAG--------------------------
---TTTTGCCCAAATCGATGACAAAAGTTCAAAAG---------GAGCCTTTAGTTGTGG
CCAAGGAG----------------------------------------------------
------------------------------------------------------------
------------------------------------------------ATGCAAAGAATT
C------------ACCAGCATCCTTCACTTTTGGAAACAGTGGTGATAAAA---------
----------------------------------------CATCAACAGGATCATTCACA
TTTGGCCAAAGCAGTGAAAAGACCTCAAAAACACCCTTCTCCTTCGATGATAAAAATTGT
CCTACAAACTTCACATTTGGAATAGCTTCAGAGACTGATGTGAAACACTCCAGTGGAAGT
TTTTCCTTCTCAAAAATGGCAGCTACAGGTGGCTTCAAGTTTGGTACTTCTGAACCTGTA
AAACTAACTTCTCCTGAAGAGACACAAACAGCAG---AAGGATCAGCTTCCCAGTTCCTA
AAAAGTATTGCTCAACAACACCAAGAAAGAGAGAAGACACAAACCAGTAGTTCTTGTACA
CATGAACCAGATACTGTTATTGCCTTTGACAAAGCTGAGAAAGATGAAAATCCTACCTTT
TCAGCTAAGCCCAATATGTTTAGTTTTGCTGACTTGGCTAAATCATCATCCACTGAGTCC
CCATTTGCACAAAAAGATCCAAATTTTAAAGGCTTTTCTGGTGCAGGAGAAAAACTTTTC
---TCATCTCGGCCTGACC---AGAAGTTGGACACTTCTGCAGAGCATGATGAAGAAGGC
ATGTACAAAACGGAAGAAAATGATGACATTCAGTTTGAGCCAGTTGTTCAGATGCCTGAA
AAAGTAGATCTTATCACTGGGGAAGAGGAGGAAGAAGTGCTATATTCTCAGCGTGTGAAG
CTGTTCAGATTTGATGCAGCAACTAGTCAGTGGAAAGAACGTGGTGTCGGCAACCTGAAG
GTCCTGAAGAACACTGTAAATGGGAGGCTAAGGGTGCTCATGCGGAGAGAGCAGGTCCTT
AGGGTATGTGCTAACCACTGGATCACCACAACGATGAATCTGAAGCCACTTTCT------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>Sargocentron_rubrum_gill_6|020675|scaffold29196|m.40717
GTTACTCGGATTCTATGCAAGTGTAGTTTAGA--------------AATTTACAAACACT
TTGA--------------------------------------------------------
-----------AGCCATGCGGCGAAGTAAGGCTGAAGTGGATCGCTATATTTCCTCAGTG
CAGAGTTCGTCTCCTTCACTCAAAGAGAAGCCTGTCAAGGGGTTTCTATTTGCTAAACTC
TACTTTGAAGCCAAGGAGTACGAACTTGCAAAAAGACATGTGTCAGAATATCTCAAAGTC
CAAGAGAGAGATCCCAAAGCACACAAATTCCTCGGCCAGCTCTATGAGAGAGAGGGAGAA
GTCAGCAAGGCGGTAGGATGTTACAAGCGGTCAGTGGAATTGAACCCATCCCAGAGGGAC
CTGGTGCTGAAGGTGGCTGAGCTGTTGGTCAGTAAGGAGGAATGTGACAGCAGGGCAGAT
TTCTGGGTGGAGAAGGCTGCCAAGCTGCTGCCCGGAAACCCGGCCGTCTTCAACCTTAAG
GAGCGTTTGTTGAGTCGCCAGGGTCAGCCGGGCTGGAACCGGCTGTTTGACCTCCTCCAA
GCAGAACTGGCTGCGAGGCCGGCCGATGCCCACGTCAACGTGAAGCTGGTGCAGCTGTAC
TCTCAGGACGGCCGGCTGGATGAGGCCGTCAAACACTGTCTGGCTGCAGAGAGGAAGGGC
TTGCTGCGCCACAGCCTGGAATGGTACACCGTGGTGGTGCACACCCTGCAGGAGTACCTG
GCCCAGCCCAGCATCTCCAGCAATGAGAAGATGTGTCGGCGTCTTCAGCGAGAGCTGCTG
CTGGCCCACTGCAGCCTGCTGAGAATCACACTGTCTGCGAGCGGAGTGCAGCCCAGCCTC
GACGCCCTCACAAGTTTTGACCAGGCTCTGCAGGCGCTGAGCAGCGTAGCGGGCAGTCAG
ACAGATGATCTGTGCGAGGTGTTTGTGGAGATGCGAGGTCACCTCTACCTGCATGCCGCC
AACCTGCTGTTGAAGCTCGCCCAGGAACGCCAACAGACCTGGAGGGCTGTCGTCGATCTG
GCTGCTCTGTGCTACCTGCTGGCATACCAGGTCCCCAGACCAAAGGCTAAGGTGACCAAA
GGAGACCAGTTGGCCCCCCAGCTGATAGAGCTACTGGCCAATGATCGGCAGAGCCAGGCT
GGCCACATGCTGCTCAATCTCAGCGCCGACACGCACACATTCATCAGAGAGGTGGTAGAG
GTGTTTGGGAACCGTAGTGGTCAGGGCTCTCTGTTTGATCTCCTGTTCGGACCGCGGGCC
TCCACTGCAGCCTCCTTCATTGCCAATGATGACATTCGCTCCATCAGCACACTGGCCCCA
GAGCTCTCCCACCTGGCCAAGTGGGACAATGGCTCCATCCTGCTGCATGGAGGTGACCTA
CAGCACCTGAGCTGGCTGGGGCTGCAGTGGGCCCTGCTGCCCCAGAGGCCGGCCCTGCGG
GACTGGCTGAAGCAGCTCTTCCCCAGGCTGACTCTGGAAACCTCCAAGCTGGACACCAAT
GCTCCCGAATCCATCTGCCTGCTAGACTTGGAGGTGTTTGTGTGTGGTGTTGTGTTCTGC
AGCCACAGTCAGCTCCAGGAGACGATGAAGATCAGCAGTGGTGTCCAGCAGCAGCAGCAG
CAGCTCTATGAGCCTCGCTGCCTGCCTCTCCCGCTCCTGCGCCTCCTGTCCACTGACAGA
CAGAGGGAGTGGTGGGATGCCATCTACAGCCTCATCCACAAACGAGCTGCGCCTGGCACG
TCGGCCAAACTGCGGATGATTGTACAGCACGGACTGAACATGCTGAGAGCTGGAGAGAAA
CATGGCCTCCAACCAGCACTGCCCATCCACTGGGCTCAATATCTCAGCCAGACGGGTTTC
GGAGCGAACTCATACTATGACCAGAAGGAGTACATTGGCCGCAGTGTCCACTACTGGAAA
GTTGTCCTCCCGCTGTTGGACAAGATCAAAAACAGACGCAGTATCCCAGAACCCCTCGAC
CCCCTCTTCATACACTTCCCCTCCAAAGATATCCAGATCTCAGCAGTGAAGGGCTTTGAA
GAGGAAGCCATGATAGCATTTGCTGCTCTCCTGGACATTGAAGGCAAGACAGAGGAGGCC
ATCGCGACACTGGAAACTGTCAATAACATGTCATCCCACTGGCATCTGGCCCGGATCTAC
CAGCGGCTCTCAGAGGAGGCAGGCAATGGGGTTGAGGAGACCCAAGACAGGTGCATCATG
TTCCTCAGGAAGTTCAGAACCTACCTGTCCAAGATTTACAATGCCAATGCTGATGACATA
GAGAAGCTTCCTGTGTCTATGGAGGAGGTTATTGACCTCCTGAATGAGGTGAATCAGCAG
CTAGGGGAGGGCGGGGAGGCCATGGATGAAGAGGAGGAGGAGGAGGAGGGACGAGGAGGA
CCAGCCCACTCCAGTCCTGCTCGTCTCACTGAAACTAGTGCCACCATATCTCACATCAAG
TTCTCCACTCCCTCTCCAAACAAAAGCATTGTCTCTCCTTCCAAAAGACACCTGATTTCA
CCCAAGACACC------ACCCCACTGGGTAGAGGACCAGAAGACCCTCCTCCAGATGCTC
TGTCAGCAAGTAGAAGCCCTAAAGAATGAGGTTCATGATCTCAGGCACAACTCCACTGGG
AACACAGGCTCTCCGTACCACAGGATGTATGGGGAGAGTTACGGAGCTGAGGGCCTACAG
GAGCCCTACACCCCAGTCCAGTCTTTCCATGGGGCCCCACTAACAGTTGCCACTACAGGT
CCTTCTGTATATCACATCCCATCTCCAGCTTATAACTCTCAATATCTCCTTCGCACAGCA
GCGAATGTAACTCCTACCAAGGGCCCAATGTATGGCATGAACCGTATGCCACCACAGCAG
CATATATATACTTACCAACCACCCACTCATACACCTCCCTTGCAAACAGCCTCAGCCTGC
ATCTA---TCCTCAAGACCCAGTCTTTGGTGGTCCTCTCCGCTTTGAGTCACCAGCCACT
AGCCTCATTTCTCCCTACACTGAGGAACATTGTGGACATGGTGTCACCCAGCCAACCACC
AACCCTCCCCTTCCTGAGCCTGGTTATTTCACCAAGCCATCTGTAGTCCCCGTTCAGCCA
CCAAAGAGCATTGAGGGGAAGCCCATGGACTTTGGGAAGATCTCTTTTGGCCAACAAGCA
CCTCCTGAAGTCCCCAAAGTGCCTAGTTTTGGAGCAGGGACAGCTGCCCAGTCCACAC--
-CTTCAGCTGCTTTTAAATTCAATTCTAACTTCAAATCCAATGATGGAGACTTTACTTTC
TCGGCCTCTCAGGCAAAG---CACAGCGAGAGCTTGCTTGGTCTTCTGACGTCAGACATT
TCCACCAAAACAGATTTTGTTCCTGAGCAGAAGCCTCCAGCTCAGGAGCAGCCCGCCAGT
CAA---GGCATCTTTACATTTGGCAGTAAGAACGCTGCTGGCTTCTCTTTTGTTGATGCT
GCACAGAACACAAGCACTGGAGGCCTGTTTGGAAAAGCGGAACAACCGTTTAAATTTGGG
GATGTCCCCAAGCCTATA---TTTGGGATGGCCAAATCT---GCGGAAGAAGAAAGGGCA
ATGGAGAGTGACAACGACAGCACTCATGTGGAGGAAGATGAGGATGGCCCTCACTTTGAG
CCCATTGTACCCCTTCCTGATAAAGTAGATGTGAAAACAGGCGAGGAAGAGGAGGAGGAG
ATGTTTTGCAACAGAGCAAAGCTGTTTCGATTTGACACAGAGACAAAAGAGTGGAAGGAG
CGGGGAATAGGCAATGTTAAAATCTTAAAACACAGCACTTCAGGGAAGGTCCGCCTTTTG
ATGAGGAGGGAACAGGTCCTAAAAATCTGTGCCAACCACTACATCACTGCTGATATGCTA
CTGAAACCAAATGCTGGTTCAGACAAATCCTGGGTATGGAATGCCATTGATTATGCAGAC
GAGCAGCCTAAGCCTGAACAGCTGGCCATCCGCTTCAAAACAGCAGACGAGGCAGCACTT
TTCAAAACCAAGTTTGAGGAAGCCCAGAAAATTATGCCCAAGTCACCAGAGAAGCATGAC
CAG------CAGGAGAAAAAAGAATCAAGCCTCAAGCCCTCTGAACATCA----------
------AGCAACAGCATTTGAAACCCAGTTTGCAATTAAAGAAGGGGAGTGGGACTGTAA
TGTGTGCTTCGTAAGAAATAAGGCTATAGCTCTGCAGTGTGCTGCTTGTCAGAGTGCTAA
TCCTAATCCTTCAGCAAAGCCAGATACTATGGCTGCTGGTGAAAACAAAGGCCTTGCTGG
GGGGCCAAGTTCATCAGGTGGCTTTATGTTCAAATTTGGAACAGATTCGTCAAAACCAAG
TAATTCAGGCTCTAAATTTACAGGGTTTGGGGCTTTTGGGGCTTCTATACCCTCTTCATT
TACATTTGG------CACA-----------------------------------------
-----------------------------------------AGTACCTCAACAACACCTG
---CTGACACAGCATCCA---------------GTACATTTGGTTCTGGCTTTGGAACTC
AGTTTGGCAAGAAGCCAGGGCAGTGGAACTGTGACATATGTTATGTGATAAATGAGTCTT
CTGCAGACAGTTGTGTTTCTTGTCAAGCCCTTAACCCCTCAGCTAAAACAACTGCTCAAG
CACCAGCAGAAGCA------------------GAAAAGCCCCCAACCTCGGCTTTTGGCT
CTGGGTTGTCTTCCCA---ATTTGGCAAGAAGCCTGGGCAGTGGGACTGTGAAATTTGCT
GTGTAAGAAATGAAGCTTCTGCAAACAGTTGTGTCTCCTGTCAAAATCCTAACCCCATAG
CTAAATCAATAGTGGAAGCTCCAGCAACATCAAAACCATCAACCATGTCATCTGGGTCAA
GTTTTGGGGCTGCTTTTGCGAAGAAAGATGGGCAGTGGGACTGCAATACCTGCCTAGTCA
GAAACGATGCATCAGCCTCTAAATGTGTTTCCTGTCAGGCCCAGTGTCCCACCCCTTCCT
TGGGAGCCATGTTCGCCAAGAAGGATGGACAATGGGACTGTGACACTTGTCTGGTGAGGA
ACGATGCCTCTGCCAGTCAGTGTGCGTCCTGTCAGACACCAAATCCCAATGTTAAAAGTA
CAACCAGTATTGCTCCCTCTGTCTCCACCTTTAACTTTAGCTTTGGAACAAAGAGTTCAT
CAAGCCAACCAGCTGGAACTGGCTTTACAACAGCCTTTGGAACTGGCAGCACTTTTCA-G
TTTGGTCAAAACAAAGATAAAAACTCTGCTGCTTCCTTCAAGTTTGAGG---------CT
CCCC---------AGTCTGGATCTAATACCA----------CAAGTTCTTC-----AGGC
TTCTCGTTCTCAATGCCCATTCCAGCTGGTGGCTTCAAATTTGGTACTCAGGACACTGCA
AAAGAAACTCTTTCACCTGGTACTGAAGCACCTACATCGGGGTCTGCCTCAATGTTCCTG
AAAAGCATAGCTGACCAACACAGAGAGAAAGAAACTGAGCCTA-----------------
----------------CAGCAGAAGTGGTTGCACAAGAGCAAGATAAGAATCCTCTGTTT
ACTGGAAAACCCAATACATTCAGTTTTGCAGACTTGGCTAAGTCCTCTGGGGGAGACTTC
CACTTCGGCCAGAAAGACCCCAATTTCAGAGGTTTTTCTCGGGCTGGTGAACAGCTGTTT
TCATCATTCCAGGCAACCCCCAATAAGGCAGACACCTCAGCTGAACAGGAGGAAGAGGAT
ATGTACAAGACCGAGGAGAACGATGACATCCAGTTTGAGCCAGTGGTCCAGATGCCTGAG
AAGGTGGACTTGGTTACGGGGGAGGAGGATGAACAGGTTCTTTACTCCCAGCGTGTCAAG
CTGTTTAGATTTGACTCCAGCACCAGTCAGTGGAAAGAACGTGGGGTGGGAATCCTCAAA
TTCTTGAAAAACACCACCAATGGCAGGCTGAGGGTGCTGATGAGAAGAGAACAGGTTTTG
AAGGTATGCGCCAACCACTGGATCACCACCACCATGAACCTTAAGCCCCTGGCAGGCTCT
GACAAGGCATGGATGTGGCTGGCCAATGATTTCTCTGATGGAGATGCCAAACTGGAACAG
CTGGCTGCCAAGTTCAAAACCCCAGAGCTGGCTGAAGAGTTTAAACAGAAGTTTGAGGAG
TGCCAGAGGCTTCTCCTTGACATCCCTCTCCAAACCCCCCACAAGCTTGTTGACACAGGC
AGAACAGCCCAACTCATTCAGAAAGCTGAAGAAATGAAGTCTGGTTTGAAAGACCTGAAG
TCTTTTTTGACAGATGAGAAAACAAAGATCAAGGATAATGACAGCGAGTCAGACTTAACA
ACATCCAGCAACATT---TCCAGCCTGGTAATCAAACCGCATGCTGAGAGCACTGGTCCC
ACCTTAGAGTGGGATAACTATGACCTTAGAGAGGAGGCTTTAGATGATACTGCTGACACA
TCTGTCTCTGCTTCTCCCATTGCCAGTAGCCCCATTAGAAAGAACCTTTTCCGTTTTGGG
GAATCCACTGGTGGATTCAGCTTCAGCTTCCAGCCAGGCATCAGTCCCTCCAAGTCTCCT
GCTAAGCTTAACCAGAGCAGGGCCTCAGTGGGTGCTGATGATGAGCAGGACGTGACTCAG
GATGAGGAGAGGGATGGCCAGTACTTTGAGCCTGTGGTCCCCTTACCTGACCTGGTGGAG
ATTTCTACAGGGGAGGAAAATGAGCAGGTGGTCTTCAGTCACAGGGCCAAACTATATCGC
TATGATAAAGACCTAAGTCAGTGGAAGGAGAGGGGCATCGGTGACCTCAAGATCCTGCAG
AATTACGACACCAGGCGGGTCAGGTTGATCATGAGGAGGGACCAGGTACTCAAGATCTGT
GCCAACCACTGGATCACAGCAGCCATGAAGTTGGAACCCATGACGGGTGCTGAGAAGGCC
TGGGTCTGGAGCACCTGGGATTTTGCTGAAGGGAGAGAGGGCAAAGTTGAACAATTGGCT
GTGAGGTTCAAGCTGCAGGATGTAGCCAACACATTCAAAGAGGTCTTTGAAGAGGCCAAG
AATGCACAAGAAAAAGAGGTACTGTTGACCCCAGTAACATCTAGGGTGGCCACCCCTCAA
GATGCTGGAGCTGCAGGATCTGCAACAGCA------GGAGCCACCATAGCTTGTGGAAAG
GCAGCCATCACTGTTCTGGAGGAGACCACCAAAGAACGCACAGAGCTTTCCTCTGACATT
------------------AAGACCAATGCAGATGGGTCACATAGCCCAGCCAACCCTTCC
AAGGCAGTGGTGTCTCCCCCTAAGTTTGTCTTTGGCTCTGATAGCCTTCAGAAGATCTTT
GGTACTCCCAAATCTGCCTCTGATGGTG--------------------------------
-------AGGACTCTGCATCCAGTGTCAAAGCCAAAGATGGTGGACGTCCTGCTCAGACT
TCATCTGCAACACCTGCATTCAGAATCCCAGAGAAAGCACCCCTTCAGGCAGAGGAAGGC
AGTGCAGGCTCTG------ACCCAGACTCAGAGGTGGAGGTGGTGTACATCAGAGAGCCC
ACAGCTGAGCAGGCTGCTTTAGCCAGGGAACTGCTGCTGCCCCTCACCTTCTTCTGCTAC
AAGAATGAACCTGGTTACACCAGCGACGACCAAACTGATGATGAGGACTACGAGTCAGCG
GTGAAAGCCTTGAACGGAAAGCTCTACCCTGATCTTCCTCAGAGGAAGGGTGCAGCATGT
GGCGATGCCACAGCCCTCCAGGCGGAGGCAGCTTCAGACTGTGAGGTGGTCTGGGAAAAG
AAGCCTACGCCGGAGGAAGAAGAGAAGGCCAAAAGCCTCCAGCTGCCCCCCACCTTCTTC
TGTGGCCTGGGCACCAGCGACAGCGACCTGGACCGGGACAAGTCTGAAGACTTTGAGACA
GAGGTCCGCAAAGCACAACAGGACCTGGATGCTCAGTTAAGCACAACATCGAAAGCTTCC
AGCAGCCCTGACGAGGCTCCAGAGCAGGACCAGACTGTAGACCAGCCTTCAGAAGCCCAG
AGTGAGGGTCCTAGCAGCAGC-TCTCCCATTGACCTGACAACCAAGAAGAGCCCTGAGCC
TGATTCCAGTACCTTCATCACTGCTGCCACAGCTACAAGTACAACTACTAGTCAAGATA-
-GTCCCACGTTTGGC-TTCAACTCGCTTGGAGGCTTTTCATTTGCTGACTTGGCCAAAAA
TACAGGAGAATTTGCTTTTGGAAGGAAAGATTCTAACTTCTCATGGGCAAATGCTGGAGC
GACAGTGTT---TGGATCCACAGTGTCCTCAGCACCAAAGAACGAGGGAG---GAGAGGA
GGGCAGTGATGAAGAGGAGACTCCTAATAATGTTGATATTCACTTTGAGCCAATAGTGTC
ACTACCAGAGGTGGAGACCAAATCGGGCGAGGAGGATGAGGAAATCCTGTTTAAGGAACG
CACCAAGCTGTACCGCTGGGACCGAGACCTTGGCCAGTGGAAGGAGCGTGGTGTTGGCGA
CATCAAGATCCTCTACCACCCGGTCAAACACTTCTACCGCATCCTGATGAGGAGGGAGCA
GGTGCTGAGGGTTTGCGCGAACCACACCATCTCCCAGGCCATGGAGCTCAAACCCATGAA
CACCTCAGCTAACGCGCTGGTCTGGACCGCCACTGACTATGCAGAGGGCGAGGGCAGAGT
GGAGCAGCTGGCCGCTAAGTTCAAAACCCCCGAGCTAGCCGAAGCCTTCAGGAAGACCTT
CTGCGAGTGTCAAAGCCACATGGGCCAAAGCAGCAACGATTCCTCCGTCTCGTTACCACA
GATGTCCAGAGCTCAAGAGCACTCCAGAGACTCAAACCCCAGGGTTTTCCTCACCGTTGC
AGCCGACAGCGAAAGCCTAGGCACCATCACCATAGAGCTCTTCTCCCATATAGTCCCCAA
GACAGCGGAGAACTTCCGGGCCCTCTGCACCGGCGAGAAGGGcttcggacTGCGGGACTC
CATCTTCCACAGGGTTATACCGGACTTCATGTGTCAGGGCGGTGACATCACCAACCAGGA
CGGCACAGGAGGCAAGTCCATCTATGGTGGAAAGTTTGAGGACGAGAACTTTGACGTTCG
CCACACGGGCCCAGGCCTGCTGTCCATGGCTAACCGCGGGCGTGACAGCAACAACTCACA
ATTCTTCATCACACTGAAGAAGGCTGAGCACCTGGACTTCAAACACGTGGTCTTCGGCTG
GGTCCGGGACGGTATGGACGTGGTGCGACAGATGGGCGAGCTGGGCAGCAAGTCTGGCAC
GCCAAGCAAGAGGATCGTCATCACAGACTGTGGACAACTCTAG
>Scleropages_formosus_red_gill|030416|scaffold46945|m.63963
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------GATGTGATGGATCTG
GCTGCCCTCTGCTACTTGATAGCCTACCAGGTTCCAAAGCCGAAGGCTAAACCCTTCAAA
GGAGATAAGGCTGCACACCAGCTGTTGGATCTCCTGGCATACGATCGCAAGAGCCAGTCA
GGCCACATGCTGCTCAACCTGAGCTGGGACAGTGAACACTTTCTGAAGGATATTGTGGAG
AAACTTGGCAACCCAGTTGGGCAGGAGACCCTGGTGGAGGAACTCTTTGGACCCCAGTTG
ACCACTAGCCCTTCCTTCATCAGCAGTGATGACATCCGGAGCTTGGGCACCCAGGCTCCA
GAGCTGGATGATGTAGCAAAGTGGGACAGCGGTGCAATCATGCTATATGCGGGGAACTTG
CAGCACCTGGTCTGGCTCAGCCTGCAGTGGACACTCTTGGGCAACAGACCTGCCTTTAAG
GACTGGCTGAAGAAGCTGTTCCCCCGACTCCCCCTGGAGACCACAAAGCTGGACACCAGT
GCTCCCGAGTCAATCTGCCTTCTTGATCTTGAGGTATTCTTGTGTGGTGTTGCATTTACC
AGTCAAACTCAGCTGCAGGAAGCATCCAGTATTGCAGGCAGCTCCAGACTGC--------
-------AAGAGCCCAGGTGTTTGCCCTTACAAATCATTAAGCTGCTGTCCACAGAGAGA
CAGAGGGAGTGGTGGGATGCAATCTACAGCCTGATCTACAAAAAAGCAGCGCCAGGGACA
TCCGCAAAATTGCGGATGACAGTCCAGCATAGCTTGGGCACCCTCAGAGGAGGAGAGAAG
CATGGTCTGCAGGCAGCATTGATCGTACACTGGGCACAACACCTCACCGAAATGAGTGAT
AGGCTGAGCTCCTATTCTGAAAAGAAAGACTACATCAGTCGCAGCGCGCACTACTGGAAC
GTTGCTCTGCCCCTCCTTGAGAAAATTAAGAAAAGTCGGAGTATTCCTGCACCCCTTGAC
CCCTTATTCATGCACTTTCGTACGAAAGAACTAGAGATACCAGCTGTTGGAGCCTTGGAA
GAAGAGGCAAAAATAACTTTTGCAACACTGAAGGATATTGAAGGCAGCACAGAAGAGGCA
ATTGCTATACTTGAGACCCTTGACAGTGTTTCATCTAACTGGCATCTTGCACAGATATTT
CACAGGCTTTCTGAAGAAGTTAGCAGCGGCTTGGAAGAAACTGAAGATCGGTGTTTCACA
TTTCGTCAGAGGTTACGGAAACACTTAACCAAGGTCTATAGGGCCAATGCTGCTGACATC
GAGAAGCTGCCGGTATCGATGGAAGAGGTTATCGATCTGCTGAATGAGGTCAACCAGCTG
CTTGGGGACAGAGGAGAAAGCTTGGAAGAGGCTAATG---------------ATGGTCAG
CCTGCAGCCTTCGGCCCTGGTTCACACAT---------------------------CAAA
TTTTCCACCTCATCGCCAGTCAAAGGTGTTCTTTCACCTTCCAAAAAACCCATGTTCTCA
CCTAGAACACC------CCCATACTGGGCTGAGGACCAGAAGTCTGTACTACAGATGTTA
TGCCAAAAAATTGAGGCCCTTAAAGATGAGGTTCACCACTTAAGGCATAATTCATCTGGG
TCCTTGGCACCAGCTCACCACAATGTATATGGTGAAGGATATGCCGCGGAAGCACATCAG
GAGCCGTTTCCACCAGCTCAGAGCTTTCATGGTGCTCCGCTTACAGTGGCTACAACTGGT
CCCTCTGTGTATTACAGTCAATCTCCTACTTACAACTCACAGTATCTTCCTCGCACAACT
GCAAATGTAACCCCAACAAAGGCCTCAGTTTATGGGATCAGTCGTCTTCCCCCACCACAG
CACATCTACACTTACCAGCAGCCAGTGCATACACCACCCCTCCAGACCACACCGGCAGTC
ATGTA---TCCCCAAGATCAGGTGTATGGTGCTCCACTGCGTTTTGACCCTCCTGCAGCC
AACATGCTCTCACCATATAGTGAGGATTATTACACACATCCTGTTCCTCAGCCCCCTGCT
GCCCCTCATCTGCCTGAGCCTGGTTACTTTACCAAACCTTCCTCTGTTTCTGTGCAGCCA
CCAAAATCTGGTGAGGGGAAGCCTGTTGACTTTGGAAAGATTAGTTTTGGCCACCAAAGC
CCGGTTGAGCATCCCAAGGTTCCTAGCTTTGGAACTGGAGCGCTTGCCCAGTCCACAC--
-CAGCGGCTGGTTTCAAGTTTAATTCA------------ANNNNNGGGGATTTCACTTTC
TCTTCTGCTCAGGTGAAA---AATAGTGAGACCTTGCTAGGCCTTCTGACATCTGATATT
CCAGTGAGAGCTGAAGGATTTCTGGGAGAAAAGCCTCCAGCTCAAGATAAGACACCTGGT
CAAGGTGGAATCTTTAATTTTGGTGGCCAAAGTTCATCTGGGTTTATGTTGTCCGACATC
TCACAGAGTGAATACAAACCGAACATGACTGGCAGTAACGAACAGCCGTTTACTTTTTCA
AACATCAGCAAGCCAGTT---TTTCAGACTGTGGACACA---GGAAGTGCTGATAAAGGT
GTGGAAAGTG---ATGACAGCACTCGTGTTGAGGAAGATGAAGATGGCCCTCACTTTGAG
CCGATTGTTCCACTGCCTGACAAAGTGGATGTGAGAACTGGAGAAGAGGAGGAGGAGGAA
ATATTCTGTAGCAGGGCCAAGCTTTTCCGGTTTGAAGGTGAAAGCAAGGAGTGGAAAGAA
CGAGGCATCGGGAGTGTTAAAATTCTGAGACACAAGATGTCAGGGAAAGTTCGCTTGTTG
ATGAGGAGGGACCAAGTATTGAAAATCTGTGCCAATCATTATATTACTGCAGATATGGAG
CTCAGACCTAATGCTGGCTCTGATAAATCTTGGGTTTGGCATGCTATTGATTATGCAGAT
GAAATGCCAAAGTCGGAACAGCTGGCCATTCGTTTTAAAACGGCTGATGAAGCAGCCCTT
TTCAAGACCAAGTTTGATCAGGCCAAGAAAGAAGTGTCTAAATCTCCCCACAGGCAAGAC
CAA------CAAAAAGAGGAAGTTGCTTCTCCAAAAAGTACAGTCTCCCAGACTGTGAAC
AAG-AAGGACATAACATTTGGGGCCCAATTTGCAAAAAAAGATGGCGAATGGGACTGCAG
TGTGTGCTCCGTAAGAAATCCTCCTACAGCTGTGTTGTGTCTTGCCTGTCAGAATGCCAA
CCCAAATGCAAAAACAAAGTCAGAAAGTAAATCAGTTG---AATCCAAAGGATTTGTAGT
TCCAGCACCTGCAATGGGTGATTTTACATTTCAGTTTGGTAAGGATGTTCAGAAATCCCC
AAGCTCAGCTCCCAGTTCACAGGCATTTGCATCGTTCGGA---CAAATACCTACGCCTTT
CAAATTTGG---------------------------------------------------
------------------------------------------------------------
-AACCGACAGCACTCCAA---------------AACCCTCAGGCTTTGGC------ACTC
AGTTTGCTAAGAAGCCCGGTCAGTGGGATTGTACTGTGTGTGAAGTAAGAAATGAGGCCA
CTGCAACCCACTGTGCCTCCTGTCAGAATCCTAATCCTTCATGTAAACCTTCAACCAGTG
CTGTGGATAAAGC---------------------AAAATCAGCAACTAGTTCATCTAATG
GTAGCTTTGGTGCTCA---GTTTGCTAAGAAGGAAGGGCAGTGGGACTGCGATGTGTGCT
TAGTTAGGAACGATGCATCAGCTGTACAGTGCGTCTCGTGCCAGTCTCCTCGT-------
--AAAATCCAAATGCCCTCACAAAGTG---------------------------------
AATTGGAAGCTAAGTTTGGAAAGAAAGATGGACAATGGGATTGTGATTCCTGCCTTGTTA
GAAATGAA----------------------------------------------------
------------------------------------------------------------
-----TCCACATCAAGCCACTGCGTTTCATGTCGAAATCCTA------ATATAAAAGGGA
AAAGCAAAGCTGCGCCAGTAAGCTCTCTCTTTACCTTTGGCCTTAATGGTAAAAGCACAT
CAAAGCAGCCACCTAGTG------------------TGACCACTAACAGTATGTTTAA-A
TTTGGCCAAAGTGATGAAAAGGGTTCCTCGACAGCCTTTAAATTTGAAG---------CT
CCTT---------TATCTCAGCCCTCCTCCA----------GCAGT-----------AGC
TTTTCTTTTTCAATTCCAATACCTGCAGGTGGGTTTAAATTCGGGATTCCTACACCTGCA
GAAGAAAATGTTCCAATTAAGAGTCAGAAACCTG--------------------------
----------------AAGACAAAGAAAAGGAGACAAAAGCAGATACTGGTACCATTACA
C---------CATCTGTGCCATGTGGGGATAAGACTCAGCAAGATGAAACTCCAGGTTTT
CTCAGCAAACCTAACATGTTTAGTTTTGCTGATTTGGCCAAATCCTCTGGGG---AGTTC
CAGTTTGGACAAAAAGACCCTGATTTTAAAGGTTTCTCCCGAGCAGGAGAGCAAGTCTTT
GCTTTGAGTCAGCCAACGG---AAAAGGGAAATGCCTCCGGTGATCTGGATGAGGAAGAT
TTGTACAGAACT------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------
>Synodus_sp._gill_5|014280|scaffold1915|m.2037
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------TTT
CAGCGGCTGTCAGAAGAGGCTGGTAATGGAGTGGAAGAAACCCAAGATAGGTGCATCATG
TCCCTCAGGAGGTTCAGGACGCATCTATCCAAGATCTATAATGCCAATGCAGATGAAATA
GAAAAACTGCCTGTGTCCATGGAGCAAGTAATGGACCTCTTGAATGAGGTCAACCAGCAG
CTGGGTGAATGCGGTGAAGCTATGGATGAGGAAGAAGAGGAGGGCA------AAGGAGGC
AACACCCATTCTAGCCCAGCTCAACTCACTGAGACTGCTGCCACCATTTCCCATATTAAG
TTCTCAACTCCTTCACCCAGCAAGAGCATCATCTCTCCTTCTAAGAGACACCTGATTTCT
CCAAAGACACC------ACCCCATTGGGTGGAGGACCAGAAGAGCCTCCTCCAAATGCTC
TGCCAGCAAGTAGAAGCTCTTAAGAATGAAGTGCATGACCTGAGGCACAACTCCTCTGAG
AATACGGGGTCTCCCCACCACAGGATGTACGGGGAGAGCTATGGGGCTGAGGGCCTACAG
GAGCCTTATACCCCTGTACAGCCTTTTCATGGGGCCCCCCTAACAGTTTCAACTAGTGGC
CCCTCTGTGTTCTACAACCAATCTCCTGCTTATAACTCCCAATATCTACTTCGCACTGCT
GCAAATGTAACTCCTACAAAGGGTGCAATGTATGGTATGAACCGTATGCCACCTCAGCAA
CATATGTATGCCTACCAGCCAGCCACCCATACACCTCCCCTGCCTACAGCTCCTGCTTGC
ATGTACCCTCCTCAGGAACAAGTCTTTGGTGGTCCTCTTCGCTTTGACTCTCCAGCCACT
AGCCTCCTCTCCCCATATAGTGAAGAATACTATGGACATGGAGTAACCCAACCCACCACT
AACCCTTCACTCCCTGAACCGGGCTACTTCACAAAGCCATCTGTTGTTCCTGTCCAGCCA
CCTAAGAATGTTGAGGGGAAGCCTGTAGACTTTGGGAAGATCTCCTTCGGCCAACAAGCT
CCCGCTGAGGCTCCCAAAGTGCCTAATTTTGGAGCAGGTGTTATTAATCAGCCAATGC--
-CTTCAACTGCATTTAAATTTAACTCCAACTTTAAGTCAAATGATGGAGACTTCACCTTT
TCAGCCTCACAAGCCAAG---CACAGTGAGAGTCTGCTTGGTCTTCTGACATCAGATATT
CCCAGTAAAACGGACGGACCCCCAGAGCAGAAGCCCCAAGATCAGCAACAGCCTTCTGGC
CAACAGAACGTCTTCACCTTTGGCTCAAAAAATATCACAGGCTTTTCTTTCACTGACACT
GCACAGAACACAGGCACAACAGGGTTGTTTGGAAAAGTTGAACAGCCCTTTCAGTTTGGT
GATGTAAGCAAACCCATATCTTTTGGCATGGCAAAACCC---TCAGAGGAAGAGAATGTC
GCTGAGAGTGACAATGACAGTGTTCATGTGGAAGAGGATGAAGATGGCCCTCACTTCGAA
CCCATAGTCCCCCTGCCTGATAAGGTGGAAGTTAAAACAGGAGAGGAAGAAGAGGAAGAA
CTGTTCTGCAACAGGGCAAAGCTGTTCCGCTTTGACACAGAGGTAAAAGAGTGGAAAGAG
CGGGGCATTGGCAATGTCAAAATTTTAAAACACAACACTTCAGGGAAGGTTCGTCTATTG
ATGAGGAGGGAACAGGTTCTTAAAATCTGTGCCAACCACTACATGACTACTGATATGCTC
CTGAAACCAAATGCTGGCTCTGACAAATCATGGGTCTGGAATGCTATTGACTATGCTGAT
GAACAGCCAAAGCCTGAGCATTTGGCCATCCGCTTTAAGACAGCTGATGAGGCAGTGCTA
TTCAAAAGTAAATTTGAAGAAGCCCAAAAGCTGATCCCCAAGTCTCCAGAGAAACATGGT
CAGCAGAGCCAGGAGGCAGATGAACCATCTCCCAAACCTGCTGGACCCCC----------
------AGAAAATACATTAGCAGCCCAATTTGCACTCAAAGAAGGGGAATGGGACTGTGA
TGTGTGTTGTGTAAGAAATGCAGCAACTTCATCTCAGTGCATATCTTGTCAAGCTGCAAA
TCCTAATGCTT---CAAAGTCTGAAAACGAGATTGAAGGGGAAACAAAAGCTGCACCTGG
AGGGTCAGTTTCAACTGGGGGCTTTACCTTTAAATTTGGTACAGACTCATCAAATTCCAC
TAATTCAGGATCTACATTTAAAGGATTTGGGGCTTTTGGTACTTCTGTACCCTCTACATT
TACATTTGGTTCTAATAGT-----------------------------------------
-----------------------------------------AGCACCTTGGCACCAGCTG
AAACCAATGACAAGCCCT---------------CAACTTCTGTGTTTGGTTTTGGAGCTC
AGTTTGGCAAGAAGCCAGGGCAGTGGGACTGCAATACATGTGATGTGAGAAATGAGGCAT
CTTCAGACAGCTGTGTTTCCTGTCAAACTCCAAACCCTTCTGCTAAAAAACCTGTTACAC
CACCAATGGAAGC---------------------AAACCCCCCAAC------------TA
TTGGGTTTGGTACTCA---GTTTGCCAAGAAGCCCGGGCAGTGGGACTGTAACACATGTG
ATGTGAGAAATGAGGCCtcttcagacagctgtgtttcCTGTCAAACTCCAAACCCTTCTG
CTCATACACCAGTTGTTCCCCCTGCTGTTGAAAA------AAGTATGTCGGGGGCCTCAG
GTTTTGGGGCTGCTTTTGTGAGAAAGGATGGGCAGTGGGACTGTGAATCCTGCCTTGTCA
GAAATGATCCATCAGCTTCCAAATGTGTTTCCTGCTCCAATCCTTGTCCTAACCCCTCAC
TTGCGGCCATGTTTGCTAAGACGGAAGGACAGTGGGATTGTGACAGTTGCCTAGTAAGGA
ATGACTCCACAGTTAACCAGTGTGTGTCATGTCAGTCCCCCAAACCCAATGCTAAAAACC
CTGGTATTGCAGCCCCCTCCAGTTCCTCCTTTAGCTTTAGCTTTGGGAGCAAGTCTTCAT
CTGGTCAGCTTGATGGAACCGGCTTTACAGCAGCCTTTGGGAGCAGTGGCCCTTTTCA-A
TTTGGTCAAAGTAAAGATAAAAGCTCTGCTGCTTCTTTCAAATTTGAGG---------CT
CCAG---------CAGCTGGCTCCACTGCC-------------------TC-----AGGA
TTCACTTTCTCA------GTCCCATCCGGTGGTTTCCAGTTTGGCACCCAGGATACTCAA
AACGAAACTCTTGAAGCCAACACTCAAGGACCTGCGTCAGGGTCTGCCTCTATGTTTCTG
AAAAACATTGCTGACCAGCATCGGGAAAAAGAGAGAGAATCTAATATTCCCGCTC-----
----------------AAACATCAGCGAATCAGTGTGAAAATGATGAAAATCCACTGTTC
ACTGATAAGCCCAACACATTTAGTTTTGCAGATTTGGCACAGTCATCTGGGGGGAACTTC
CAGTTTGGCCAGAGTGATCCAGATTTCAAAGGCTTTTCTCGTGCTGGTGAACAGCTGTTT
TCATCATTCTCAACAGCTTCTAACATTGCCAACACCTCAGCTGACCAGGATGAAGAGGAG
ATGTACAAGACAGAGGAGAATGATGATATACAGTTTGAGCCTGTGGTTAAGATGCCTGAG
AAGGTTGACCTTGTGACAGGAGAGGAGGATGAACAGGTCCTCTACTCTCAGCGTGTTAAG
TTGTTCAGGTTTGACACAGGTACCAGCCAGTGGAAGGAGCGTGGGGTGGGAATCCTTAAA
TTTTTGAAAAATACCACCAATGGCAGATTAAGAGTTCTTATGAGAAGAGAGCAGGTATTG
AAAGTCTGTGCCAACCACTGGATAACCACCACTATGAACCTAAAGCCCTTAGCAGGGTCT
GACAAAGCTTGGATGTGGCTGGCCAATGACTTCTCTGATGGAGATGCCAAACTGGAACAG
CTGGCTGCTAAGTTCAAAACTCCAGAGCTGGCTGAGGAGTTCAAGCTTAAATTTGAGGAG
TGCCAGAGACTACTCTTAGACATCCCATTGCAGACACCCCATAAACTTGTTGACACAGGC
AGAACTGCACACCTAATTCAGAAAGCTGAGGAAATGAAATCTGGCTTGAAAGACCTTAAA
TCCTTCTTGACGGATGACAAAGCAAAGATCAAGGATGATGACAGTCAAGCAGATATTACA
ACAGTCAGCAATGTT---TCAGGACTGGTCATAAAGGCCCATGCTGAGAGTACTGGGCCA
ACCTTGGAGTGGGATAACTATGACCTTAGGGAGGATGCTCTAGATGACAGTACTGAAACA
TCCGCTTATGCCCCTCCTGTTTGCAGTAGCCCCATCAGAAAGAACCTTTTCCGCTTTGGA
GAATCTACTGGTGGTTTCAACTTTAGCTTTCAGCCCAAAATCAATCCTTCCAAGTCTCCA
ACTAAGCTTAACCAGAGCTCAGCATCAGTGGGCACTGATGATGAACAGGATGTTACCCAA
GATGAGGAGAGAGATAGTCAGCACTTTGAGCCTGTGGTGCCTTTACCTGACCTGGTGGAG
ATTTCCACAGGGGAGGAGAATGAACAGGTGGTGTTTGGCCATCGGGCCAAGCTCTACCGC
TATGACAAAAGCCTTGGCCAGTGGAAAGAGAGGGGCATTGGAGAGCTAAAGATACTGCAG
AATTATGACACCAAAAGGGTGAGGCTGATCATGAGGCGAGACCAGGTACTAAAAATCTGT
GCCAATCATTGGATCACATCAGCCATGAAGCTGGAGCCCATGAAAGGTGCCGAGAAGGCT
TGGGTTTGGTTTGCCATGGACTTTGCTGAAGGTACAGAAGCCAAAGTGGAACAGCTAGCA
GTGAGGTTCAAACTTCAGGAGGTGGCAAACACGTTCAAAGAGGTCTTTGAGGAGGCCAAG
GTTGCACAAGAAAAAGAAGTTCTCTTGACCCCTGTTACATCTAGAGTGGCTACTCCTCTT
GAGGTTGGAGCCTCAGGATCAACTACAGCAGCAACTGCAGCAACTACAGTGTGTGGAGAA
GCAGCAATAGCTGTCTTGGAGGAGACCACCAAGGAACGCACAGAGCTCTCTTCTGACACC
TGTCACACCCCTGATGGCAAGACAAGTGGAACTACATTTCACACTCCATCCAGCTCCTCA
AAAACTGTGGTTTCTCCACCTAAATTTGTCTTTGGGACAGAAAATGTGCAGAAAATCTTT
GGCCTGCCCACAATGTCCTCCAGTCAAG--------------------------------
-------AAGAGCATTCATCAAGCCCCAAAGCCAGAGAGAGTGGACCCCCTGTGCCATCT
GCTTCTGCGCAACCGGCATTCAAAATCCCAGAGCAG------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------GGGTT
GGATTTTAGGCTTTTCA------------------------------------AAGATA-
-ACCCAATGGCT------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------TTTTGGACCAGCA-----
------------------------------------------------------------
------------------------------------------------------------
---------CATCTACCACCC---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------AATTTGAG--------------------
------------------------------------------------------CCCCCA
GTGCTCTCTCAGGCAGAGGGAGGC------------------------------------
------------------------------------------------------------
-------------------------------------------
