>Amblygaster_clupeoides|036380|TR63888|c4_g1_i1|m.86898
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------GAGGAGGAGGAGG
AG--------------------------GAGGAGGTAGAGGAGGAGGAGGTTG---AGGA
GGCGGAGGA---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------GGCACTGGAGTTAGAGGAGGA------AGGGGGA
GGGGGAGGAGGAGGAGGAGATGGAGATGGT----GAGCTTGTGGATCTGGACG-------
-----------------------------------------------------TCCCAGA
GGAGATTCCCG-------------------------------------------------
------------------------------------------------------------
-----------------------------------------------AGTACGAGGACGC
GAGAGAGCGGAATCAGGTGGTCGGCGTGGAGACGCTGGAACCA------GTTAAAGTGGC
CACGCTGGACGACATGGCCAAGAGGATCCAGGTGGAGGAGATCACCCCTGCCTCTGGTCT
GGTCTCCATCCTGAAGAGGCGAGCATCCCTAGAGGGGACCAGCCCTTC------CCGGCC
CACGCCCAAACCCAA---------------AGCCCTCACCAAACGCAAGGTCCGCTTCAG
GGAGCCTGACGATGGCTTCGACCAAGACGAAGTAAGCGGAGATTCTTGGGTGCTCCTCCT
TCTCCTATGTCTGGCTACCGTGGTGATCAGTGTGGGCGGGACAGCGCTGTACTGCACGGT
GGGCGACGCCCAGTCCAGTGTCTGCACAGACTTTTCCCACAATATGGACTTCTACGTGGG
CCAGGTGCAGCGCGGCATGGCTGAACTCAAACACTGGTTCTCACCCAGCTCTTAG
>Corydoras_julii_viscera_mixture_8|004873|C1245938|m.30451
GTGGT------------------GGTGGAGGCGCCATGCAGCCAC---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------GACGAAAGG
ATGTTGAAACAGGATGATGATGATGATGATGAGGTTCCTCTCAG-------CACTGCCAG
----------------------------------------------------TGTAGAC-
-----------------CAGGAGAAGCC--------------------------------
-----------------------------------AGCACATATCTGTGACTCC------
------------------------------ACCCCCAGC-CAGTTTACTTCATCTCTA--
-------CAAGCCACAC--------------------------------CCACTGAAGCC
ATGACAAACAGCTGTACAGCTG---------------CAGGAGACA--------------
-------------GTGAG------------------------------------------
---------------------------------------------------AGAGAAGAG
AGTGGGGTGGAGC-----------------------------------------------
------CTGGAGGTGAAATGGAAGAGGA--------------------------------
------------------------------------------------------------
-----------------------------GCCAGGAGCACAGGT----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--CAGGGAGGTGGAG---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------CCTGGAGGTGTTGTGAAAGAGGAGG
AGCCAGGA--------------------AGAGAGGTTAAGGAGGTGGAGCCTGCATCAAA
AGTAATAGAACCATTA-------GCTGGTGTTGAT-------------------------
-------------------------------------------------GTCACAGAAAT
GAAGTCTTTGG-------------AATTTGATCTAAA--TGGGAAGCAGGTGATGCAGAC
GGTAGGAGAGTACGCGCCCCCACAGGAAGAGGACATGAAACAAGAAA------AGGAGGT
GGAACAGGAAGAAGAGGACATAGAGGAAGCCATTGAAGCTTTAG----------------
-----------------------------------------------------TTCTGGA
GGAGGAGCTTC-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------AGAGGTCAGAGGTCGAGAG---------------------------
---TCTGGATGACCTGGCCAGACGCATTGAGGTGGAAGAGGTGGTGCCAGCTGCAGGTCT
GGTCTCTATCCTGAAGAAAAGGTCATCTGCAGAAGGAGAAACCTTTGA---TGATCCATC
CTCTAATAAACCAT---------------------CCAGCAAACGTAGAGTTCGGTTCCA
CGTACCTGAAGATGACCTAGAGCATGATGAGGTGGGTGGAGACTCCTGGCTACTCCTGGT
ACTTCTTTGTCTGGTTACCGTGGTAATAAGTGTGGGTGGGACTGCCCTGTACTGTGCCTT
TGGCGACGCCCACTCAAGTGTGTGTACAGACTTTTCACACAACATGGAGTTTTATGTAGG
AAAGGTGCAGCGCAGCGTGGAGGAGCTCGCACACTTCTTCTCCTCTGGATCCTAG
>Distichodus_sexfasciatus_gill_4|020825|scaffold30312|m.36318
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------GAGGAGGAGGTGGAGGAGG
GT--------------------------GTGGAGGCTCTGCAGTTAGATGCGGG-TGGAG
AGGAGCAGCA--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
GGTGCCTGAGCT------------GGAGCTGGAGGTGTCGGAGGAGA------GCCCGGA
GCTGGAGGACGAGGAGGAGCAGGAGGAGG-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------AAGGCCAGGGTGTAGAGACACTGGAGGTG------GAGAAGGTCAG
CACGCTGGACGACCTGGCCAAACGCATACAGGTGGAGGAGATCACTCCAGCTGCAGGCCT
GGTTTCCATTCTGAAGAGGAGAGTGTCTCTGGAGGACCCAAGTGCAAC------CCCTGT
GACCCCCAAACCGG---------------------TCGGCAAGCGCAAGGTCCGGTTCCG
GGTGCCAGACGACGGCCTCGATCACGATGACGTTGGAGGAGACTCATGGCTGCtgctgCT
GCTCCTGTGCTTGGCGACGGTGGTGATCAGTTTGGGAGGAACTGCACTCTACTGCGCTTT
TGGTGACGCTCAGTCCAGTGTCTGCACCGACTTCTCCCACAACCTGGACTTCTACGTGGG
GCAGGTGCAGCGCGGCGTGGACGAGGTCCGCCACTGGTTCTCCCCCGGATCCTAA
>Gasteropelecus_sp._gill_3|004239|C941388|m.48733
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------GAGGAGGAGGAGGAGG
AG--------------------------CAGGAGGCTCTGGAGCTGGATCCTGC-AGGAG
GACAGCAGC---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------AGCAGGAGGTTCCTGAGCGGA------GAGTGGA
GGAGGGGCTGGAGGAGGGGCTGGAGG----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------AGGGGCACGGCGTGGAGACGCTGGAG------------AGAGCCGA
CACACTGGACGACCTGGCCAGGAGCATCCAGGTGGAGGAGGTGTCTCCGGCCACTGGGTT
GGTCTCCATCCTGAAGAGGAGGGTCTCTCTGGAGGGGGGCGG------------TTCCTC
CACCTCCAAACCCA---------------------CCAGCAAACGCAAGGTCCGCTTCAG
GGTTCCGGATGATGGCCTGGACCATGATGAGGTGGGCGGAGACTCGTGGCTGCTCCTCCT
CCTGCTGTGCGTGGCCACTGTGGTGATCAGTGTGGGCGGGACGGCGCTGTACTGCACCTT
CGGCGACGCCCAGTCCAGCGTCTGCACAGACTTTTCCCACAACATGGACTTCTATGTGGG
TCAGGTCCAGCAGGGGGTGGCGGAGCTGCGGCACTGGCTGACCCGCGGGTCGTAG
>Lepidogalaxias_salamandroides_Head_2|014614|scaffold12124|m.15946
-----------------------GAGAGGGCTCTCTGGTGTGTTCAGC------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------TGGAGAGTCT
ATACCACCAAAGGCTGCTGCAC------------AACCTCGCCG-------CCCTGC---
------------------------------------------------------------
------------------AGGAGCACTG--------------------------------
-----------------------------------GGCATCGAGGTGGAAGGC-------
----------------------------------------AGGCGGTCAGCGTCTGAGCC
ATGGCACTGACCCGGGT--------------------------------TCAGATCAGCT
GGAGAGACTGACTGAG-ATCTG---------------TAGGACACACCAGCGACCCATGC
TCCAAAGGAACAAGTGTGTTG---------------------------------------
------CTTTGGATCCTGTACGGCCTGGTAGCCCACA----------GCCAGCTCAACTG
AGTGAAGAACCGAGAC-----CAAGAGCTTCATGCAGCACAG------------------
-GTGCGCTGGCTGAGTCACAGCAGAGGATG------------------------------
-----GACCTCAGGGGCGTGGCCGACGGTATGACCCCAAA--------------------
------------------------TGACCTCCAGAAGGACAGCCCTC-------------
-------------------------------AAACAGACATGATGGACAACTCC------
---------------------------TCCTCCAGTAATCGGTTGGCTGTCGGCGGG---
------------------------------------------------ACAGTAGACTCT
TGCAGGGAGACTGGAGGTTTCCTTGGAAACAAGT--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------TGATGGACGGCTCCTCAAG------
----------TGAGGTTT---------------GGCTGGAGTGTGAGAGGCGGGACGATC
GG--------------------------GCGGAGACTTTGAGCGCAGCCGCGGG-ACGGC
TGGAGCAGTCCACTC---------------------------------------------
---------CGGGGGCCGGGGAGGGACAG--------------------GGCACTGAGGA
AACCTCACCGCGTGACTGGATGATGAGCCAACCCcagcccgaggagctgctggacGAGGA
GGCCCTGGAGCTGG---------AGGAGCTGCGGCCTGCAGAGAAGG------AGGGACA
AGTGGAGGAGGAGGGGCTTCTGGAGGAGGA---GGAGCTTGCGGATTTGAACC-------
-----------------------------------------------------TCTCAGA
AGAGA-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------AAGGGTTAATGGTAGAGCAGTTGGCTCCG------GTGCGACAGAT
TTCTCTGGACGACTTGGCCAAAAGCATTCAGGTGGAGGAGATAACCCCGGCCACGGGTCT
AGTATCTATCCTGAAGAAGCGTCCCTCCCTGGAGGGG-----------------------
--CCCGTGACCCTG-----------------GCGTTGCCCAAGCGCAGGGTCCGATTCAG
AGTTCCTGATGATGGGCTTGACCAAGATGAGGTGGTCGGAGACTCCTGCCTGCTGCTGCT
CCTCCTGTGTTTGGCTACCGTGGTGATCAGTGTGGGCGGGACCGCGCTCTACTGCGCCGT
GGGCGACGCCCACTCCGCCGTGTGCGCTGACTTTTCCCAAAACGTGGACTTCTGCCTGGC
CCAGGTGCAGCGTGGGATACATGAGCTCCAGCACTGGCTCTTCCCTGGCTCGTAG
>Melanotaenia_praecox_viscera_mixture_8|015522|scaffold20918|m.23185
ATGG--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------AGCAGAAAGCTGAAGAGTCCCATTG-------CCCTGTCAT
ACCTT-----------------------------------CTGTTAATATGCCTGAAAAG
CTAAA-------ATCCCCTGGAATATTT--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
CAAATGAACATGGAA---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------AACCCCAACAAAGTACCTGAGGGGA
GG----GACATTTTCTATGGATCT----CAGCTGACTGACAAGCAAGACGATGGCAGAGA
AGGAGGAGAG--------------------------------------------------
-------------GCAGAGGGAGGGGCTGGATGCACCATTTCAGCCATAGGAAAAGGGCT
ACACCCCTCTACAGCTGAGGGAATGGATCAGTCCAAACCTGCAGAGCAGC---------A
GAGACAAGATTTAGGCCCAGCACCAGAAAAGGAGGCAAAAGGGGAA------------GA
AGTGAGTGATGTAGAGGAGACAACAGAGCCTTTGGAAATGGAAGATGAAGAAGCTGAAGA
TGAGGGGGAAGAGAAGCAgaaggaaggagagtcttgttttggccagaACGCTGTCCTAGT
GGAGACTCTGGTCAGTGGGGTTGAGGTGGAGGTAGAACTGATACATCAGGATACTTTAGC
TCATGAAAAGCTGCACGATGAGACACAGCATCACCAAAACACCCAGGAGAGCTCTAAAAC
CTGCCTGCATAAGGAGGCACACCCTCCCCAAGAGACTCATATGAAGCAGCACGAGCAGTA
TACAGAGGAGGAGTGGGACTATGAGGTAGACCAAGCTGACATCATC---AGAGAAGCTTC
CTCACTGGACGACATGGCAAAACTCATCACTGTACAAGAGATCTCACCTGCCTCTGGCCT
TGTCTCCATATTGAAGAAGCGTAGTGTTTATGTGGACAGT---------------TATGT
GTCTGCCAGGTCAGAGCCTCGACCTAAAAAAGCTACTGCCAAAAGACGCGTCCGCTTCAA
AGTTCCTGATGACAATTATGAGCACGAAATTGGTGGTGGAGACTCCTGCCTGCTTCTCTT
CCTCCTTTGCCTGGTTACTGTAGTGATCAGTGTGGGTGGCACTGCCCTTTACTGTGCTTT
TGGTGATACACAATCCTCAGTCTGTCAGGACTTCTCCAGAAACGCAGACTTCTACATTGG
CCAGATACATCATGGGATATTGCAGATTCAGCATTGGTTCACCTCGGGGTCTTAG
>Pantodon_buncholzi_mixed|012641|scaffold15529|m.20519
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------GAGAGCAATT--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------TG
GGTGAGGAGGAG------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------CAGGAAA------AGCCAGA
GATTGTGGAGGTGGAGGTGGTGGAGGAGTCGACAGAGTATGAAG----------------
--------------------------------------------------------CGGA
GGAGG-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------ATGGGTTTGCCCCAGAGGTGGCTGAGGCTTTCGGCATCACGCAGGC
TTCTTTGGATGACTTGGCCAAGAGGATACAGGTGGAGGAGATCAGTCCTGCTTCTGGCCT
TGTGTCCATCCTGAAGAGGAGAGAAGGAGAAGGAGAACCTGCCCAGGC------TCCTGT
GATAGTTAAACAGG---------------------CTCCTAAACGCAAGGTTCGcttcag
agagcccgagGAGGGTCTTGATCACGATGAAGTGGGCGGAGACTCATGGCTCCTCCTCTT
TATACTCTGCATGGCCACGGTAGTCATCAGCGTGGGAGGCACCGCGCTGTACTGCACGCT
GGGTGACCCACAATCCAGCATCTGCACAGAGTTCTCGCACAATATGGACTTATATTTCAC
CCAGGTACAGCGTGGCTTGGAGGATCTCTGCCACTGGCTCTCTCCCGCCTCATAG
>Sargocentron_rubrum_gill_6|024833|scaffold9483|m.10654
ATGGATCATGGTGGTCAGCGTGAGAGGGAGGAACCAGTCATGTCACATGGTCAGGGGGAT
GCGGTCGACCTCTGCGATAACCTGCTTGACCCTGAAGCTCTCACCGCCCAGAACCGAAAC
CTCAACGAGACACAGGCGCTCACACAGACCCAAAGTTGCCCTCTCTCACATAATGAAGGA
ACAGAAGGGCACGAGCTCATCCAGAAACCCCCTGCCAACAACACTGGTGAAGGAGGGGAG
GAGGAGGAGGGATACAAAGGGAAGAGCAGAGAGGAGGATGAGGAGGAAGAAAATGATGAG
GTGATGAAGGATGAAGACGAGGAAGAATCTGAGGAATCAAGCAGTTTGATCCGCTGCCAG
TCACCAGACACTCCCATGACAGATTCTTCCTATTCTGAAACTGGCAGTTTGCTGGAGACT
CCATATCCCCTCAGCCCCGGGACCAGTCCAGAGCCTACATCCCCCATCATTCCAGTGGCC
TGTCCTGAAACAGCATATCCCATCAGTCCAGTGGAAGTAAGCCAGTCTGAGGCTGAGGTG
GACTCTCTTAACTCCAACACTGGATCTGTCACCTCCACCACAGGGCCCATTACCTGCACG
CCAGGACCCACCTGCACGACGGGACCTATAGATTCTGTTACATCATCTGTAACGTCAGCC
ACAAGGCCCGCTAGCACAGCTGCGCCTACACAGTTAACAGAAAGCACAGGTG--CAATAT
CAAAAACCACAGACTGTGCTACAGAGCCTCTTACCTCATCTGCAGAGTCTATCCTCACAC
ATCAATCTACAGGCACCAAAGGGTCGGTTAGCTTGTATGCCGGACCCTTCTCCTCAACTG
GTCAGGCTACAAGTACATCTGCAGTAACTGCCCGCACCACAAAGCTCTCCACTTCCATTA
CACGATCTGTTAGCTCAACAACAGAAACCGTTACCTTCACCACAGGCCCTGTAACTTCCA
GTGCAGAACCCAGCTCCATCGCAGGGCCTACAACCTCAAATCCAGAACCCATAACCTCCA
CTACAGCGCCCACTTCTGTCTCAGTGTTCACCTGCACCACAGGGCCCTTCTCCAGCCCCG
CCCTGCTGACATCTCTGGAGCAGCTGGCACAAAGAGGAGATGACACTCACCTGCCACAGT
ACCTTCACCAGATCGCTGAGGCCTTTGTCCTCCAACAA------GACTACCAGAGGGCGT
TATGGTGCATCCAACTAGAGAGACTCTATCACCAGAGACTATTGGACAACTTGAACATAC
TACAGGAACAGTGGGAGAGTCTCTGTAGACCGACGTCCGTCTCACACCTTGCAACCCAAG
AGCTGGACACACTTGCTCACATCTGCCAGACGCACAGTCGACCCAGAGCCAGAGATGCTG
TGTGTGCAACTCTGGACTTTCTGAGACCTTCTACATTTGAAGAGGAGACACTTGGTGCTG
CACTGCCTTCATGTACCTCAGGCCATCAGGCTGAAGGAGGGATGGAGCACAGCGCCACAG
ACTCCTCCCTCTCTCAGAACGGCGACCCATTCACATCCTCCACAGTTCTGCCAGACTCCG
TCCACTCCCCTGAGAACTCAGAGAAGGGCGGgatGGACGCAGACAGGGAATTGGAGGAGA
GG----GCTGGTTTCCATGGAAGC----CAGTTGACTGACATGGAGGGCGGTGAACAAGA
GGGAGCAGAG--------------------------------------------------
-------------GTGGGAGGAGGGATAGAACACATCACCTCAGCGGGGGGGACTGGACT
GCGCCCCCCTGCCGCCGGAGAAGTGGGCCGATCCAAACCTGCAGAGCTGC---------A
GGGAGGGGAGCTGGAGCCGACACAGGAAAAGGAGGTGATAAAAGAAGAAGGGCAGAGGGA
GAGGGAGGTGGAGGAGGAGGCGGCAGAGGCTGTGGAGATGGAGGATGATGGAG-------
--AAGAAGAGGAGAAGCAGGGGGAGACAGATTCTCCTGTTTGTCTCAAAGCTCTTCAAGA
GGAGAAACCAGTCAGAGAGCCAGGGGTGGAGGAACAACAGCTGCAGCAGG----------
--AGGACCACCTGAGGGAGGAGACCC---------------------AGAGTGTAGAAAC
TGGACCGCAGCAGGAGGCCCACCTGCCTCAGGAGCAGCAGGAGCAGAGCGAGGAGGAAGA
GGAGGAGGAGGaggaagagTATGGAGTGGAGAGAGTTGACATCATC---AGAGAAGCTGC
CTCACTGGACGACCAGGCCAAACTCATCACCATAGAGGAGATATCTCCTGCCTCTGGCCT
CATCTCCATATTGAAGAAACGGAGTGTGTGTAAGGACAGTGT------------GTGTGC
ATCACCCAGTTCAGAGCCACAACCCATCAAACCCCCTGCTAAGAGACGGGTCCGCTTCAA
AGTACCTGATGACGGCTATGAACACGACGTTGGCGGTGGGGACTCCTGCCTGCTTCTCTT
CCTGCTTTGTCTCGTCACCGTGGTGATCAGTGTGGGAGGCACCGCCCTCTACTGCACCCT
GGGTGACGCCCACTCCTCGGTATGTCAGGACTTCTCTCGGAACGCAGACTTCTACATCAC
CCAGATGCAGCGTGGGATTGCTCAGATACAGCACTGGTTCGCTCCTGGGTCGTAG
>Scleropages_formosus_red_gill|030445|scaffold46976|m.64026
A---T------------------GATGGAGCCGCTGGGTCTG------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------GACGAGGGC
TCCCCAGCAGAGGACGTCGTGCGCAGCG----GGGCCCTAGCAG-------CACAGCA--
------------------------------------------------------------
-----------------CAAGGACATTTCGGCACTT------------------------
----------------------------------GGCCACCAGGGGGCGGAGCT------
------------------------------GC-------ACGGCACTCTTCGCCTGG---
-----------CCACAC--------------------------------CCaCTTCAGCT
GACACAGTCGGCTGTT-GTCCG---------------GAGGCCG----------------
-------------GCGTG------------------------------------------
------------------------------------------------------CGTGTG
GGTGGGGAGGAGA---------AGGGCCTGTGCGAAGCA---------------------
--------------GCGGCAGCAGAGG---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------CACTCTGC
GATGCGGGAATGGAGAGTCCTCTTGGAGACACGC--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------TCCCTGGCAGCTCCTCC--------
-----------------------------------CCTGGTGACGAAGAGCAGGAGGAGG
GGC--GAACCGATCCAACAGTGGCCTTTCAGGAGTCTCTGGA--CAGATGCGAC-TCAGG
GAATGCAAGGCGGACAGAACCTGGCCGGGACAGATCCTTGGAGGAGGACGGTGCAGGAAG
TGTCGGAGGTGAAGATAAGGGAGGGACA---------------------GGCTCAGGGCT
GAGCCCCCTGGCTGAGGGTGAGATGAGCTCGCCCGAGCCCTGGGGGCAGGAGGATGGAGA
GGGAGGGGAGCAGG---------CCTGCCCTGGGGCAGATGAGGAGA------AGCCGGA
GATAGTGGAGGTAGAGGTGCTAGAGGAGTCCTTGGAGTACGAGG----------------
--------------------------------------------------------TGGA
GGAGG-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------ACAGCCTTGGAGTGGACGTTGTGGAGGAGGAACGTGTTTCACAGGC
TTTGCTGGATGACCTGGCCAAAAGGATACAAGTGGAGGAGATTACACCTGCCTCAGGTCT
GGTGTCGATCCTGAAGAGGAGGGCTTCCCTAGACAGCACCACTACCTGCACCGGACCCAC
CTCTCCCAAACAGG---------------------CTGCCAAGCGCAAGGTCCGATTCAG
AGAGCCAGATGAGATGCTGGACCAAGATGAAGTCGGCGGAGACTCCTGGCTGCTCCTCCT
CCTGCTGTGCTTGGCCACTGTGGTCATCAGTATTGGAGGGACTGCCCTCTACTGCACCCT
GGGTGATGTGCAGTCCAGCATTTGCACTGACTTCTCCCACAACATGGACTTCTACTTCGG
GCGGGTGCAGCGGGGGCTGGACGAGCTTGGACACTGGTTTTCCCCGAGATCGTAG
