>Amblygaster_clupeoides|027084|TR47136|c0_g1_i1|m.70005
CTGGGGAGGGTCAGTAGTTATGACAGCGATGCATGGTTGCATATGGCTTTAATTCCAAAT
CACTACTCTTATAGAGGAATACCGGAGCTTTCCTCCTCACCCAGGAGATATGTT-GAGTT
GGCCATGGACAAGGTCACCTTCCGCATGGACAC-AGTCCTGTCAGACGTGCACCTACTAC
TGCCCAACGCCCGCCACTTAATGACCCGCCTCAACGGTGTCGGCCAACCAGTCTTCATCT
CCAAGTTTAGGATCTTGTGGGATGTGGAAGAAAAGGAGGATGCCTGCAGTGGATCCTCCC
CTG---------------------------------------------------------
--GGAACACTGAGGATGACAG-------------------------CCCCTCCGGTGCAT
CCCAGGCGCCCCTGGATGTTGATGGAGATCTGGATGTAGCAATGAGGCCCAGGGATGCCT
CTC------------------CAGATCGGGAGAGGGTGTGTCCCACTATCCTCAGCCAGG
TCTTGGGGGATTTGGCCGATGACGATGAA---------GATGAG----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Corydoras_julii_viscera_mixture_8|019904|scaffold9699|m.6574
GTG---------------------------------------------------------
------------------------------TACTGCACAGATGTTGGAGAAGAC-CTCCT
TGCCATGTGTCAGAGAAATGTGCAGATGAACACACACTTTATTAAAGATTCAGAAAAACA
TGCTGTAAAAGTACGACAGCTGGACTGGACCT-CTGATGATTTCTTCACAGTGTTTTTGT
CCAAGTTCATAATTTTACAACAAGGAGAACAACAGGAAGAGAATCATGATCA--------
------------------------------------------------------------
----------------------------------------------CATCGAACAGCAGT
CCTGTGCTCTACTTGATGAAGATGGTGATATGGACGTCTTAAGAAGGCCTATAAACATTA
CTA------------------AGGATCGTAACCCAATTCACCCGGTGATCCTCAGCCAGG
GCGANNNNNNAGAAGAAAAAGAAGAGGAG---------GAGGTGGAGGAC---TGCGCTA
ATGACATCATAAAGATTGAACACACAATGGCTACGCCACTGGAGGATGTCGGCAAACAAA
TCTGGAGAGGAGCTTTTTTGCTGTCTGATTTTATCCT-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------T
>Distichodus_sexfasciatus_gill_4|001641|C841637|m.46785
------------------------------------------------------------
----------------------------------------------------------AT
GGACATGGATCAGGTCACCTTGCGGAGTGACAC-TGTGCTCTCAGACGTCCACCTGTTAA
TACCAAATGACCGTCATCTCATGACTCGCCTCAACGGTGTCGGACAGCCAGTGTTTGTGT
CCAAGTTAAAGATTCTCTGGGATGGCGGAAGTGACCCAAACTCTACTGAGCGAACTCCAC
CT----------------------------------------------------------
----CTTTCTCCTCCTTCTCC-------------------------TCCTCGTTGTGCTC
CCAATCCACTGCTGGACGAAGACGGCGATCTGAACGTTTTGAGAAGGCCTGCGGAGGAGA
CCA------------------GCTGTCGGGAGAGAGTTCACCCTGTCATCATCAGCCAGG
CATCCGGGACGAACGAAGAAGAAGAAGAA---------GAAGAGGAG-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------
>Gasteropelecus_sp._gill_3|021344|scaffold33261|m.36763
CCG-----AGTTCGGAGCTGCGCT--CTGAGTGTGGACGGGTTTCAGCGGAGCTTCGA--
-GCTGATTTTAATAAGGAA-----------CAGTGGTCGGGGAAAGGACATGCA-GGGGT
GGCCATGGATCAGGTCACCTTCCAGAGTGACAC-CGTGCTCTCGGATGTCCATATTTGGC
TGCCAAATGCTCGTCACCTCATGGTTCGACTCAACAGCGTAGGTCAGCCCGTCTTTGTGT
CAAAGTTCAGGATTCTGCGGGACAAGGAGCAGGAGGAAG---------------------
------------------------------------------------------------
---------------------------------------------TCCAGGAATCTCAGA
AGAGCACTTTGCTGGATGACGATGGAGATTTAGACGTGGTGAGGAAGCCCAAACACTTGC
CAT------------------GTGACCGCGAGAAGGTTCATCCGGTCATTCTCAGCCAGG
CCGGAGGGGCCGTCAGCGATGAAGAGGAG---------GTGGAGGAGGAAGAGTGTG---
-------------------------------------NCTGGACGATGTGGGAAAGCAGA
TCTGGAGGGGAGCGTTCCTCATGTCTGACTTCATCCTCTCACACACGGATGTTTTCCGAG
AAGCGACGGTCTTGGAGCTGGGAGCAGGAACCGGCCTG----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------A
>Lepidogalaxias_salamandroides_Head_2|011190|C554918|m.52182
--------GGTGCGGCGTTGCA--------------------------------------
--------------------------------------AAGCGGGGAGCATGCC-AGTGG
AGACATGGATCAGGTCACCTTCCACCACGACAC-GGTGCTGTCAGACGTCCACCTCCACC
TGCCCAACACTCGCCATCTCATGGCTCGCCTCAACCGCGTAGGACAACCAGTTTTCACGT
CAAAGTTCCAGATTCTGCGGAACACTGAGAATCCAGAGG-CGTGTGATGACGTTCCTCCT
CCG-GCGGGGGACGAGTTTGAGTG---TGACACACGTAAGACC-----------------
-CAGGATAGTGAGGAAGCTGA-------------------------TTGGTCACATGCTC
CCCGCCCCGCCCTGGATGAAGACGGGGATCTGGAGGTGAGAAGGGTCAGGCCGAGGCCAG
ACC------------------TGAACCGGGCCAAGGTGTGTCCAACAATTATCAGCCAAT
CAGAGAGGCCGGCTGAACTCGAGGAAGAG---------GAGGAGGATTAT---TGTTCCA
GAGATGTCATTCAAATCCAACATACAATGGCAACAACTTTAGAAGATGTCGGTAAACAGG
TGTGGCGTGGGGCTTTCCTATTGGCCGATTTTATCCTCTCTCAGCCAATCACATTCAAAG
GGGCTACGGTGCTCGAGCTTGGAGCCGGAACAGGAATCGCCAGCATTGTCATGGCAACCA
TGGCCAAGACGGTGTATTGCACAGATGTGGGGGAAGACCTACTCAGCATGTGTGAGACCA
ATGTGTCCTTAAATTGTCATCTCCTGGAGCCCACGGGTGGGCGAGTGTGTGTGAGACAGC
TGGACTGGCTGAGCGACTCCCTCTGCACAGACACTGATGCAGAGTTCACCTGGTCAGAGG
AGGAAGTGGCTGATCTCCATGACAACACTACGTTTGTCATCGCTGCGGATGTTTGCTATG
ACGATGACCTCACGGACGCTTTCTTCAGGACTCTGTACAGAATCACCAGCAACCTACGCC
ACAGCAGCGCCATCTACCTGTCACTGGAGAAAAGGTTGAACTTCACTCTTAGGCACTTGG
ATGTGTCCTGTGAAGCGTATGATCACTTCCGCCGCTGCCTGGCCAAGCTGGAGGGCGTGG
TGGGCAGGGTGAGCTTCAGGGTGGAGAGGATCCTTACAGTCTTCCCCCAGTACCTGCAGT
ACGAGCGCGTGGAGCAGCTGGAGCTGTGGAAGGTGATCGCTGAACCTGTCGAAACCCCAC
ACACACCTGACCCGATCCCCACACACACCTGA
>Melanotaenia_praecox_viscera_mixture_8|010910|scaffold16007|m.15659
------------------------------------------------------------
------------------------------------------------------------
-TCCATGGATCAGATCGTTTTTCAACATGACAC-GGTGCTGTCAGATGTTCATATGCATC
TACCCAATACACGCCACCTCATGACACGCCTCAACAGTGCTGGACAGCCTGTCTTCACGT
CCAGATTTAAGATCTTGGCTGAAAGACATGAACACAACGACCCTGGGAAACGTT------
-----CAGAGACAGAACGCAAGCatGACGACACACAGGAGGACACGGCGGCATCTTCTCA
TGGAGAGGATGAGAAGGAAGG-------------------------CGGTGAAAAATTTG
TGGAGCCTTTTCTGGATGAGGATGGAGACCTTGACATCACACATCGGCCACGAAAAAACC
CCTCAGATGG---------TGGCAGCCGAGCCCTGGTCTGTCCAGTCATCCTCAAACGGT
GCAGTCCCGTGCCGGAACAGGAAGAGGAGAACACAGACGATGAAGAGGACGACTGTAACA
AAGACACAATAAAGATCGAGCACACTATGGCTACACCTCTGGAGGATGTTGGCAAACAGG
TGTGGCGGGGGGCGCTCCTGCTGGCCGACTTCATCCTGTCCAAGCCAGAAATGTTCAGGG
GGGCTACAGTCCTGGAGCTGGGAGCTGGAACAGGCTTAACCAGCATCGTCATGGCAACCA
C-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------A
>Pantodon_buncholzi_mixed|003027|C616791|m.33779
------------------------------------------------------------
------------------------------------------------------------
----ATGGACCAGATCACCTTCAGTAGCGACAC-TGTACTGTCTGATGTACATCTCCTTC
TGCCAAATGCCAGCCACCTCATGGTGAGGCTGAACCAAGCCGGACAAGCAGTTTTTACAT
CTCACTTCAGGATACTGCGAGCTGCCGACTCAC----------------CCGTGTCTCTA
AAG-TTCGGGGAAGGTGAAAATTC---CGACACGTGTAGAGTAATTAAGGACTCC-----
-AAAGACAAAGAAGAAGGAGA----------------------------------ACAAA
AGGAAGTTCTGCTGGATGAAGATGGTGATTTAGAAGTGACCCGGAAACCCCACAGCTTCT
GTCAGTCAGA---------GGGGGAAAGGCAGAGAATCTATCCCACAATTCTCAGCAAAG
CAGAGGTGGATCTTGAAGATGAAGGCAGG-ACTCCAAAGACAAAGAAGAA----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------G
>Scleropages_formosus_red_gill|026450|scaffold41864|m.55213
TCA----TACTGGGCTATCGTA------------GGGTGTACGGTAAATGGGCTCTTA--
-CAAGTTTCTAACAA---------------TGTTTCTTGTTTTGCTGACTCACTGAGGGA
GTGCATGGATCAGATGGTCTTCCGCAGTGATAC-CGTGCTGTCCGACGTCCACCTGCTCT
TGCCCAACAGAGGCCACCTTATGGTCCACCTCAATGTGGCAGGACAGCCAGTTTTTGCTT
CACGGTTTAAGATTTTGCGGGACTGCAAGACTCAGGATTTTGGCCATGGTTCAACCACAG
CTGAACAGGAGGAAAAAACAAGCc---atgcttccggaGAGCTGGGAAGAGATGA-----
-AAAAAAGATGGAGAGGGGAGAGGAGGAGGAGGGGAACAACCTAGAAGCCCAGAGGTCAC
CAAAGGTTCCCTTGGATGAAGATGGTGATCTAGATGTGGTCAGGAGGCCCGCGGAGAGGG
TCCCAACAGAGCTATGCCTGAGAAACCGAGACATAATGTATCCCACAATCCTCAGCAGGA
CGGAGCCAGATGCCACAGAGGAGGAGCAG---------GTGGAAGAAGAAGAGTGCCCCA
GAGATGTCATTAAGATCGAGCATACCATGGCCACACCTTTGGAAGATGTTGGAAAGCAGG
T-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------G
