>Amblygaster_clupeoides|041714|TR694|c15_g2_i1|m.981
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------GAGGAGGAGGAGGAG------------
------------------------------------------------------------
---------------GAGGAGGAGGAGGAGGAGGAGGAAGAGGAACCATCTGCAGAGACG
CCACAAAACAAAAAACTGAAGACCTCCACTCCCCACTCGTTCCCCAAAGCTAATAAGAAG
AATGTCAGTGTTCCTTTCCGAAGAATAAGAGAGGAGGAGATTGAAGTGGACCCTCGATTG
GCAAACAACTCCTTTGAAGCAAAGAAAGGAGCAGATGGGGACTGGGGCCAGAAGGCCAAT
AACATGCTCAAGTTCACCAAGGGCAAGTCGTTCCGCCACGAGAAGACCAAGAAGAAGCGC
GGCAGCTACGTGGGCGGTGCCATCTCCACCACCGTCAACTCCATCAAATTTGACAGTGAC
TGA
>Gasteropelecus_sp._gill_3|003660|C932748|m.47808
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------GCAACTGCTC---------------GTTTTGAAACATCACT
ATTAAGCACGTTTTTTTTTTTGT-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------CTGTCCCGTG----TTCTCTAAAGAAAAG------
-----CAATGATCCTTTCCGTAGAATAAGAGAAAATGATGTTGAGGTGGACCCCCGGCTA
GCAGACAACTCCTTCTCTGCCAAGATGGGATCCAGTGGAGACTGGGGTGAGCGAGCCAAC
GACGTCCTGAAGTTCACCAAAGGGAAGTCCTTTCGTCATGAGAAAACTAAGAAGAAGCGT
GGCAGTTACAGAGGAGGTGCCATCTCCACCTCCGTGAACTCCATTAAGTTTGACAGTGAA
TAG
>Melanotaenia_praecox_viscera_mixture_8|005717|C459020|m.32726
G-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------CATCTAAAGCAGCTACCCCAGCTAAAACTGCT
GTT---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------AAACCTGCTGCTGGAA-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----AAGCAGAAAGCAGCTCAGACTCTGACTCTTCCTCTGAGGAAGAAGAG---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------CCAGCTAAGGC-------------------
------------------------------------------------------------
--------------------------------TAAGCCAACAACAGCAAAGAAAGCTATC
CCACCATCAAAGCCCA--------------------------------------------
-------CCACACCTGCAGCTAAACCATCTGCTG--------------------------
-CAGCAGAAAGCAGCTCTGACTCGGA---------CTCCTCCTCTGAAGAGGAAGA----
--AACAGCCACGGCTAAACCAACAGCGGCCAAAC--------------------------
-------------------------------------CGACAGCTGCTAAACCAA-----
------------------------------------------------------------
------------------------------------------------------------
----CAGCAGCTAAAACAGCTACACCAACTTCAAAG------------------CCTGCT
ACTCCTGCTGGAAAAGCTGGAGCAGTACCACAAAGCAGCTCTGAATCT---GACAGCTCA
GACTCTGAGGATGAAGT---AGCCAAGCCTGCAGTGAAGAAACAAGCCACAGCAGCGGTC
AAGAAGCCTGCAGCTGCCAAGACTAACAC------AGCAAAGGTTGCAGCGAAGC---CA
ACACAGTCTTCATCCAGCGACGACAGCTCTGATGAGGAGGAAGAGACTAGTAAAAGTAAA
ATAAAACCTGCTACCCCAGTTGTAGCAGCCAAGACAACCCCAGCAGTTAAACCTAAA---
GAGAAAAGTAGCAGCTCTTCAGACAGTTCATCAGATGAGGAAGACGCACCAAG---TAAA
GCAGCCACTGCACCCACCACCCCCACAATA---AATACCAATGGAAAGAGAAAAAGAGAT
G---AAGAATCATCCGACAGTGAAGAGGAAGAAACGCAA------------TCAAAAACT
CCAAAAAGCAAAAAAGTAACAA---CCACGCCACAAACTTTTCCAAAAGCGAATAAGAAG
TCTTCAAACGTACCCTTCCGTAGAATTGTGGAGGATCACGTTGAAGTGGATCCTCGTCTG
ACAGACAATTCTTTTGAAGCCAAGCGTGGAGCCAACGGAGACTGGGGCCAAAAAGCTAAT
GAAGTGCTGAAGTTCACTAAAGGCAAGTCATTCCGCCATGAAAAGACAAAGAAAAAGAGG
GGGAGCTACCGAGGTGGAGCCATTTCCACTACAGTCAACTCCATTAAGTTTGACAGTGAC
TGA
>Pantodon_buncholzi_mixed|016471|scaffold19126|m.27524
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------AT
GGGAAGGGCACAACACCCAAAACAG---------------------CAGCAAAGCCAGCA
GCAGACTCTTCCTCCAGTGACAGCAGCTCTGAAGATGAGAAGCCGGC---GAAAGCTGCA
GTCAAACCTGCT-------CCGAAGAAACCTA-----------CAGCAAAGCCTGCTGCT
GAGGAGAG---------CTCA------TCTTCAGAGGAGGAGGAGGAGGCTAA---GCAG
AAAGTTAAA------------CCTGCA------AGTAACGACAATAAGAGGAAGCGGGAT
A---AAGAGTCTTCAGAGGAAGAGGAGGATGAAGAGGAAGCTGACCAA---ACGAAGACC
CCCAAGGGTCATAAATTGGCACCGGCTGCACCCCACtccttccccaagtccaa-------
----------------gcaaaAGAATAAGAGAAGAGGAGATTGATGTGGACCATCGGCTT
GCGGACAACTCCTTTGAAGCCAAGTACGGGGCGAGCGGAGACTGGGGAGAGCGGGCCAAC
GACGTACTCAAGTTCACCAAGGGCAAGTCCTTCCGCCATGAGAAGACCAAGAAGAAGCGA
GGAAGCTACCGGGGCGGCTGCATCTCCACCTCTGTCAACTCTATCAAGTTTGAAAGTGAC
TGA
>Sargocentron_rubrum_gill_6|004149|C712401|m.47982
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------GCTGC----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----AGCAGAGAGCAGCTCTGACTCCGACTCCTCTGAGGATGAGGAAGAA---------
------------------------------------------------------------
------------------------------------------------------------
------------------------------CCAGCCAAGGC-------------------
------------------------------------------------------------
--------------------------------CAAGT---CAGCAGCTAAGCCGTCTGTT
TCAGCGTCAAAGCCTG--------------------------------------------
-------CCACCCCTGTAGCAAAGCCTGCTGCAG--------------------------
-CTGCAGAGAGCAGCTCTGACTCTGACAGTGACAGCTCTGATTCTGAGAATGAGG-----
-------CCTCTGCCAAACCCGCAGCCAAGAAAC--------------------------
-------------------------------------AAGCTCCAGCTGCAGCGACGGCC
AAGCGCCCTGC------CCCTGCTGCTCCTGTCACCAAGGCTCCTGCAGACTCAAGCCGT
GTTGTGTCCGATAGCTCCAGTGATGATAGCTCCAGTGACGAGGAGGAATCTAAGAAGGCA
GTGCCAGCACCCAAGAAGGCAGTGCCAGCACCCAAGCTAGCAGCTGTGAAGGCACCTTCG
GCCCCAACAAAGAAGGCAGAAG---------AGAGCAGCTCTGAGTCTTCAGACAGCTCT
GACTCTGAGACGGAGGCCAAGACCACACCTGCAA---------AGCCTGCTGTCACCAAT
GGCAAGGCAGCAACACCCAAGGCAGCCACCCCAGCAGCCAAAGCCCCAGCCAAGC---CA
GCTGAGTCCTCATCTAGTGACAGCAGCTCTGAAGAAGAGGAAGAGGTCAGTAAAAAGACT
GTAAAACCTGCTACCCCAGCTGCAAAAACCAAGACCCCCCCAGCAACAACAGCTAAACCT
AAGGAGAGCAGCAGCTCCTCAGAAAGTTCGTCAGATGAGGATGAAGGGACCAC---TAAA
GCAGCCACAGCACCCACCACCCCTGCAGCAAATGGTATCAATGGAAAGAGAAAAAGAACT
G---GAGACTCACCTGAAGGTGAAGAGGAAGAAGCTGAA------------ATTAAGACT
CCAAAAACCAAGAAAGTAACAA---CCACACCGCAGACCTTTCCTAAAGCCAAGCAGAAG
TCTGCCAATGTACCTTTCCGTCGAATAAGAGAAGAGGAAGTAGATGTAGATCACCGTCTT
GCAGACAACTCTTTTGATGCAAAGCTTGGATCCAATGGTGACTGGGGCCAGAAAGCCAAC
GATGTGCTCAGGTTCACCAAAGGCAAGTCCTTCCGTCACGAAAAGACGAAAAAGAAGAGG
GGTAGCTATCGTGGAGGAGCCATCTCCACCTCAGTCAACTCCATCAAGTTTGACAGTGAC
TGA
>Scleropages_formosus_red_gill|031490|scaffold5146|m.6578
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------ATGAAGGCTACT
GCTCT-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------G-----TGTTGC----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------TCAGTGCAG---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
CCTGCA------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------CTTCCCACAGTCCT
GATCC-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------CTGCGCTCTCATTTTCGCCCA--------------
----------------GCTGGGGTCTAATGGCGACTGGNNNNNNNNTGGATCCCAGGCTG
CTGGACAACTCCTTTGACGCCAAGCTGGGGTCTAATGGCGACTGGGGCCAGAAAGCCAAT
GAAATGCTGAAGTTCACAAAGGGCAAGTCCTTCCGCCACGAGAAGACCAAGAAGAAGCGC
GGAAGCTACAAAGGCGGGACGATCTCCACTGCTGTTAACTCCATCAAGTTTGAGAGTGAC
TGA
>Synodus_sp._gill_5|024502|scaffold7317|m.8064
ATGAAGAACGTCTCGTTGACATCTACAACTTTTGGGCAAAGTCCCCAGAGGCAAAGAAAC
GTAAGGCTGTGCAGAGCGAAGCTGACGACAGCAGCGTTCCAACCGCTAAAAAGGCCAAGG
CAGACAGCTCGAGCAGTGAGGAGTCGAGCAGCGAGGATGAGGCTGCAGCCGCCCCAGCAA
AGCCCACTCCAGCAGCTGTTAAGGTTGCACCTGCCAAAGCAGAGAGTAGCAGCAGCGAGG
ACTCCAGTGACTCTGAGGATGAAGCAGCAACAGCCAAAACTCCAGCAAAGACACCTCCAG
CTAAGAAAGCAGCGCCTGCCATGGCTGGCACAAGGAAGAAGGACACCAGCTCTAGCAGCG
AGGAGTCNNNCACAAGGCCAAGCACCTGCAGCCATTGCTGCTGTTCCCACTAAAGCTGCA
GCTCCAAAGAAGCAGGAAAGCAGCAGCGAGGAGAGCTCAGACTCTGAGGAGGAGCCAGTG
AAGCCTGCTGCCCCACCAAAGGCCTCTCCTGCTCCCGTTAAAGCTCCTCCTGCAGCAGAG
TCGAGCAGCGAAGACTCCTCCTCCGAGGACGAGGCTCCTCCGAGCAAAAAACCCAGAGCT
GGATCATACAGCGCAGTTCCACCCCCATCTCAAGGTCAGAAGGCCaccagcaCCCCACCT
GTCCCTGCTGCCGCCAAGGCTAAGGAGTCTTCAGACAGCAGTGAAGACAGTAGTGATGAC
AGCAGTGATGAGGAGGCAGCAGCTAAACCCAACAAACAACCAGTGAAGACCACCCCTGCC
AAGCCTGTGGCTCCTACATCCAAAACAAAGAAGCAAGACTCCAGCTCTGAGAGCACAGAT
TCAAGTTCGGACGAAGAGGAGGAGAAGAAACCTGCTGCTAAAAAGGCTCCAGTAAAAGCG
GCACCAGCAAAGGCTACCCCTGCAGCAGAGGAAGACTCTTCCTCCAGCTCGGAGGAGGAG
ACAAAGAAACCTTCGGTGAAGGTGACTCCCGCTAAGGCTACCACTCCNAAGCAGGCCTCT
TCTTCAGATGAGGACTCCAGTTCTTCAGAGGAAGAAGAGGCAGCAGTGAAAAAGCCTGCT
GTTACTCCAACAAAAGCAGTCCCCGTCAAGACTCTTGCAGCCAAAAAGGATGAATCCTCT
AGCTCAGAATCTGACAGCAGCTCTGAAGATGAGGCTCCTGCAAAACCTGCGACTAAAGCT
TCAGCTGCAGCCGTATCTGTCCCAGCTGCCAGTACTGTTTCAACACAGAAAGCCCCTGGA
AAGGTAGCTGAAAGCAGCTCTGAATCTGACTCTTCCTCAGATGATGAGGAGGAGACGGCT
AAGCCAGCAGCTGTGAAAACTGCTGCGAAAACTGTTGTGAAAACGACTGCTCCAGCCAAA
CCCTCTACCCCTGTAGCAAAGCCTGCAGAGAGCAGCTCGGATTCAGATTCTTCCTCAGAG
GATGAGGCGGCGGCGGCGAAGCCCATTGCTCCAGCTAAGCCAGCAGCTAAANAACCGTCT
ACACCAGTGGCTAAGCCGGCAGCAGAGAGCAGCTCCGATACAGATTCATCTTCAGAGGAT
GAGGAGGAAGTAGCTAAACCAGCTGCCCCAGTTAAACCAACAGCGgctaaaccgtctaca
ccagtggctaagcctgcagagagcagctccgattcagacTCTTCAGAGGATGAGGAAGCA
GCTAAACCAGCTGCCCCAGCTAAACCAGCAGCTGCTAAACCGTCTACACCAGTGGCTAAG
CCTGCAGAGAGCAGCTCAGATTCAGA---------CTCTTCTTCAGAGGATGAGGAGGAA
GCAGCTACCACAGCTAAACCGGTAGCTGCTAAACTGCCTACACCATCGGCTAAACCTGCA
GAGAGCAGCTCTGAGAGTAGCTCCGATTCAGAGGATGAGACCACAGTAGCAACAACCTCC
AAACCTCCAGCCAAGAGCCCAGCCCCTACCCCAGCGAAAACTCCTGCTGACTCCAGCAGT
GAGGACTCGgatagctccagtGAGGA------------------------GGAGGAGGTG
GTGCCAGTGTCTAAGCC-----TGCCACGACCAAAGCC-------------GCTGCTCCA
GTTCCAGCCAAGAAGGCAGAGG---------AGAGC---------TCATCAGACAGCTCA
GATTCAGAGGTAGACTCCAAGGCCA---CTGCAGTCA------GCCCTGCTGTCACCAAC
GGCAAAGCTGCTACATCGAAGGCCT------------------------CCAAGC---CA
GAGTCCTCATCTTCAAGTGACAGTAGTTCAGAGGAGGATGAACAGCCTTGTAAAAAGACT
GTGAACTTGACCACCCCAGTAGCAACCCCCAAGACTACCCCAGCAACCTCAGCTAAAGCA
AAGGACAGCAGCAGCTCATCTGAAAGCTCGTCTGATGAAGAAGAGACGTCGAAACCTAGA
GCAGCCACTGCACCCACCACCCCAACTACAAATGGGTCTAATGGAAAGATGAAAAACTGT
GAACAAGACTCTTCTGAAAGCCAAGACGAGGAAACTGAA------------GTGAAGACT
CCGATCAATAAGAAAATAACAT---CCACACCACATTCTTTTCCCAAAGCAAAAAAGAA-
--TGCAAACGTACCTTTTCGTCGAGTAAGAGAGGAAGAGGTTGAAGTGGATAATCGCCTG
GCTGACAACTCTTTTGATGCTAAGCGGGGGGCCAACGGTGACTGGGGCGAGAAAGCCAAC
CAAGTGCTTCGGCACACCAAGGGCAAGTCGTTCCGCCACGAGAAGACGAAGAAGAAGCGT
GGCAGCTATCGCGGGGGAGCTATCTCCACCACTGTCAATTCCATCAAGTTTGACAGTGAC
TAG
