>Amblygaster_clupeoides|017270|TR29759|c1_g1_i1|m.51470
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------AAGCCCCTCTCTGGGTCTGACCGTGCTTGGATGTGGCTTGCGAATGACTT
TGCTGATGGAGATGCAAAGTTGGAACAGCTTGCTGCCAAATTCAAAACACCAGAGCTGGC
AGAAGAGTTCAAGCTAAAGTTTGAGGAGTGTCAAAAGCTTCTGTTGAACATTCCTCTTCA
GACACCCCATAAACTAGTTGATACTGGTAGAACGGCACATTTGATTCAGAAAGCAGAGGA
AATGAAATCTGGTCTTAAAGACCTCAAGTCTTTTCTGACTGATGACAAAA---AGATCAA
AGATGAGAGTA------AAGACATTTCTTCAACTAGCAACACATCTGGCTTGATCATCAA
ACCTCATGCTGAAAGTACTGGTCCAACTTTGGAATGGGATAATTATGATTTACGGGAGGA
AGCTCTTGATGACAGTGCAGATACATCTGTTTATGCCTCCCCAATAGCTAGCAGTCCTAT
TCGTAAGAATTTGTTTCGATTTGGGGACCCTAGTAGTGGTTTTAGTTTCAGTTTCCAACC
TGTTCTTAGTCCTGCAAAGTCACCAGCCAAATTAAATCAGAGCAAAGTATCTGTTGGGAC
AGATGATGAACAAGACACCACTCAAGAGGAAGAGCGTGATGGGCAGTATTTTGAGCCTGT
TGTGCCATTACCTGACCTTGTGGAGATATCAACTGGAGAAGAAAACGAGCAAGTGATTTT
CAGCCACAGAGCTAAGTTGTACCGCTATGACAAAGACCTGAGCCAGTGGAAGGAGCGTGG
CATTGGAGACCTTAAAATTCTGCAGAATTATGACACCAAACGAGTAAGGCTTATAATGAG
ACGGGATCAGGTTCTTAAGCTGTGTGCAAACCATTGGATAACTAGCACAATGAACCTTGA
GCCAATGAAGGGTGCAGAAAAGGCTTGGGTCTGGAGTGCATTCGATTTTGCAGAAGG---
AGAAGGCAAAGTGGAGCAGTTGGCAGTCCGTTTCAAGCTACAAGAAACTGCCAAGACTTT
CAAAGAAATGTTTGATGAAGCAAAGTATGCGCAAGATAAAGAAACCCTTGTCGCATCAGT
GTCATCAACGGAAG----------------------------GCCAATTCCA--------
---AGAAACCACA---TGTGGTAAAGCTGCAATAGCTGTTCTTGAAGAGACCACCCGTGA
ACGCACAGACTTGTCTCCTGAGACATTCCATACACCAGAAAACAAAACTGCT---CCTGC
ACACAGTCCTCAGGCTGCTTCCAAAACAACTGTGGTTTCTCCCCCTAAGTTTGTCTTTGG
CTCAGATTCAGTCCAGAAAATATTTGGGAGCCCC---TCTGCTCAAGATGCATCACCAGT
CAAGCCCTCTCACCCCAAAGAAAAAGCACCAAGCA------------------------C
ATCGGCCTCCACCCAGCCAGCCA--------------------------TACCTGCATTC
AAGGTTCCAGAAGGAGCTGTTTCCCAAACAAAGAAAGATGAAGCCATTTCAAGTGCTGGC
ACTGGT-------------GTGGCGGTAGAGGCAGCCGACTCAGAGGAGGTTGAGATTGT
GTATGTGCGTGAGCCCACAAGCGAGCAGGCAGAGCTGGCCCGGCAGTTGATGCTTCCCTT
CACATTCTTCTGCTATAAGAATGAACCAGGCTATGTCAGTGATGACGATGAGGATGATGA
AGACTTTGAGACTGCTGTAAGAAATCTTAATGGAAAGTTGTATCCTGATCAACTGGAAGG
ACAGTCT-----------------------------------------------------
-------------GGTGCTGCAAACAGTGATGG---------------------------
---------TGCATCCAGGGATG-------TGAAGGAACCAGAGGTTAC--AATCATCTG
GGAGAAAAAACCAACCCCTGAGGAAGAAAGAAAAGCCAAGAGCTTGCAGCTCCCTCCAAC
CTTCTTCTGTGGAGTCGGCACTGACTCCGACACAGAGAAGGACAAGCATGAGGACTTTGA
AGCGGAGTTACAGAAAGTGCAAGAAGCTCTGAGTGAGCAGCTAAGTGGAGATGTGGATTC
CTCTGAGGCTACA------------------------------------GGGCCAAGCAC
AAGCGC------------------------------------------------------
------------------------------------GGTCAGGACTCCTGAGA-------
------------------------------------------------------------
---------------------------------------------------CAGTACCAC
AACCC--TCCTCCGAAGACCTAGCTCATGAAACAGTGCCAC-------------------
------------------------------------------------------------
--------------------------------------AACCCTCCTCCGGAGAACCAGC
TGATGGC---------ACTGGCAGTGGCAGCTGCCCTATTGACCTTTCTACAAAAAAGAA
CACAGAATCCGATTCC------------------------------------------AG
CGCCGGTCAAGATCCTCCACC---TATGTTTGGATTTACTTCTATGGGAGGATTTTCATT
TGCGGATTTGGCTAAAGGCTCTAGTGATTTTACTTTTGGGTCAAAAGATTCAACCTTCTC
ATGGGCAAATGCCGGAGCCACAGTGTTTGGCGCAG------TCGCAGAGCCTAAACATGA
CGGAGAAGTGGAGG---GAAGTGAGGATGAAGATGATGAGGCCACAAACAATGACGAAAT
CCACTTTGAGCCAATCGTGTCACTGCCAGAGGTTGAAGTCAAGTCTGGTGAAGAAGACGA
AGAGATCTTGTTTAAGGAGCGGACCAAATTGTACCGCTGGGATCGCGACCTGAACCAGTG
GAAAGAACGCGGAGTGGGTGACATCAAAATCCTCTTCCACCCTGTGAAGAATTACTACCG
TGTGCTCATGAGACGAGATCAGGTGCTGAAGGTGTGTGCAAACCACACCATCACACCAGC
TATTGAGCTGAAGCCCATGAACACCTCTCCGAATGCCTTGGTTTGGACTGCCACAGACCA
TGCAGAGGGAGAAGCTAAAGTTGAGCAACTCGCTGCCAAGTTTAAAACCTCAGACCTTGC
TGAAGCCTTCAAGAAAACATTCACAGATTGTCAGGCTCGCATGTCCACAGA------TGA
TGA---------ATCCTCTGTCCAACTATCTAGAGCCCAGGAGCTCTCAAAAAAGGGCAA
TCCACTGGTGTACTTCACTGTTGCTGTTGACGACCAGCCTCTTGGAAATATTACCATGGA
GTTGTTCTCCCACATTGTGCCGAAAACAGCAGAGAACTTCAGGGCCCTGTGCACAGGAGA
GAAAGGCTTTGGATTCCACAACTCAATTTTCCACAGGGTTGTCCCAGACTTCATGTGTCA
AGGTGGCGATATCACCAATCAGGATGGCACTGGAGGAAAATCCATTTATGGGGGGAAGTT
TGAGGATGAGAACTTTGATGTCAGACACACAGGACCAGGCCTGTTATCCATGGCAAATCG
AGGGAGAGACACCAACAATTCCCAGTTTTTTATCACGCTTAAGAAAGCAGAGCACTTGGA
TTTCAAGCATGTAGCATTTGGCTTTGTAAAAGATGGAATGGACATTGTGAAACAGATGGG
TGAACTTGGCACGAAGACTGGGAAACCCAGTAAAAAAATTGTCATTACTGATTGTGGACA
ACTTTAG------
>Corydoras_julii_viscera_mixture_8|016293|scaffold26077|m.22744
AACGAGGACTACAGCGCTCACAATGTTCCTCAACCTTCCGCTAATCCCCCACTACCAGAA
CCAGGGTACTTTACCAAGCCCCCGTTCATACCAGCCCCCACCAGCAAGGTGGCAGACTTA
AAAATAAGCTCTGGCCAGCAAGTTCCAAGCGAAACGGGGAAGGTCCCGGCTATGGGAGGC
GGTGTAGGCCAGCCAGCATTTAAATTCAATTCCAACTTCAAGTCCAACGACGGAGACTTC
ACCTTCTCGGCATCAGACTCCAAGGCTAAAAACGAAAGTCTCCTGGGCCTCCTGATTTCA
GACTTCCCGAGCAACTCTGCCCTAAAGTTTCCAACCATGAGCTCGACACCTGGTGGGGTC
ATAACAGAGGGTAAACCCTCATGTGGGTTTTCGTTTACCGATTTTGCGCACGGTAAATCC
GGCTTCGCAAATGTCTCATACGGTCTGGGGAGGGAGAGCGAGGAGAGATGCGAGAGTGAT
GAGGGCACCCAGCTGGAGGAGGATGAGGACGGACCTCACTTCGAGCCCATCGTACCGCTG
CCTGATAAGGTGGATGTCAAAACCGGGGAGGAAGAGGAGGAGGAGATGTTCTGCAATCGG
GCCAAGCTGTTCCGCTTTGAGGCCGAAACAAAGGAATGGAAAGAACGCGGCATCGGGTGC
ATCAAGATCCTAAAACACAGAACCTCTGGCAAACACCGCCTGTTGATGAGGAGGGAGCAG
GTTCTAAAAATCTGCGCCAATCATTACATCACTTCAGATATGGTTCTGAGACCAAACGCG
GGTTCCGATAAGTCCTGGGTGTGGCATGCTATCGACTATGCGGACGANNNNNNNNNNNNN
NNNNNNNNNNNNNAGACTGTGGACGAGGCTGCGTTGTTCAAACAGAAGTTTGAGGAGGCT
CAGAGATCCTTGAACGACTCGGTCCAGCATCAGCACGTCGTCAACAGCCCCCCCGCAATT
CAGGTGGTGTCCGTCAGGAAAACGGACCTGATGGCCAAGTTTGCCAAGAAGGAGGGTGAC
TGGGATTGTGATGTCTGCTGTGTACGGAATGCTTCCTCTTCTAGAGCATGTGTTTCCTGT
AACAGCCCCAATCCTAGTGCTCCAACACCGTCGCAGCCTAAACCCGACAAGAGCAGCGGC
TTTGTCATGCCGGTTCCCTCGGCGCAGACTTTCACGTTCGGACTTAGCGAAGGTTCTAAG
GCAGCTGGCGGATTCAAGGGATTCGGAACCCAGATTCCGTTCTCTTTCAAATTTGGCACC
GATGAGCTTTCTACACATTCCAGCCAGGCTGCACCGACCGCCATACCTCCGCCAAAGAAT
GTGTCTCCATCTATCCAAGTGGTGTCCAGTGTTCCACAAGATCTTTCCTTTGCCTCCAAG
TTTGCCAAGAAACCAGGCCAGTGGGATAGTCCCACTTGTGCAATAAGAAACGAGGCATCT
GTAGCTTCCTGCCCTGCATGCGATACTCCTAATCCCTCAGCTNCCCCACCCCCCGCCGTT
CCAGAACCCGCGAAGCAGCCAGTGACCACTGGATTCTCCTTTGGCTCCATATCTGG----
-----------------GTTTGGGAAACCCGCCTCTAAAGAGGGTCTCTGGGATTGTGAA
TCCTGCTTAGTTCGAAATGAGCCATCCAAAAACGCGTGTATTTCTTGCGGGGCTCCATGT
CCTGAAATAATAAACGCAAAATGGGATTGTGAATGTCTGGTCAGAAACGAAGGCGTGGCG
AATTTCTGTAAATCCTGTAAGAAACCCAACCCGAACACCGCACCTACATCCTCCACCCAG
CCAGTTTCAGGAGGTAAATCTAGCTTGGATGGTGGTTCTGGACTGCAGTTTGGGA---AG
CCTACGAAGAACGG------TCAAGTGGGTGCTGGACTGCTCGGGTCAGGAGGAGGCGGC
GCTGCCGATTCCTCAGGGAGCAGCTCAAAGTTTGTGTTTCCAAAGAACAGCTTCAGC---
---------------AGTGGGTTTAA-ATTCGGACTCAAAGCGCCAGAAACAAAGGCAAC
GGATGCAACAGACGACTGTCCCCTAATGACGGGCAAATCAGCGGGCTTTAGTTTTGCCGA
CCTGGCCAAGACAACACAAGGTGCATTTCAGTTCGGGATTAAGGATCCCAGCTTCAAAGG
CTTCGCAGGTGCAGGGGAGCAACTCTTCACCTCTAGTCCACAAACTCCAAAGGCGGCAGA
CTCCTCCTTTGGTCAAGAGGGGGATGACGTGTACAAAACGGAAGAAAATGACGACATTCA
GTTCGAACCGGTCGTGGCAATGCCTGATAAGGTGGACATCATAACGGGGGAAGAGGACGA
GAAATGTCTGTACATGAATCGGGTCAAACTGTTCCGCTTTGACCCCGACATTCACCAGTG
GAAGGAGCGAGGTGTTGGAAACCTGAAGCTGCTCCGGAATAATACGAACGGCCGTCTGAG
GGTCCTCATGAGGCGCGAGCAGGTGTTGAAGGTGTGTGCCAACCACTGGATCACTACCAC
GATGAACTTGAAGCCCCTTGCCGGTTCGGACCGGGCTTGGATGTGGCTGGCAAACGACTT
TTCGGAAGGGGACGCAAGGCCAGAACAATTGGCTGCCAAATTCAAAACCCCAGAGCTGGC
TGAAGAATTTCGGCAGAAGTTCGTGGAGTGTCAACAGCTCCTCCTGGAAATTCCACTGCA
GACGCCTCATAAGTTGTCTAGTTCAGACAGGACGGCCAATCTCATCCAGAAGGCCGAGGA
GATGAAGTCTGGCCTCATGGACCTTAAGTCGTTTCTGAGTCATGGCCGAC------TTGA
AGAGGAAGACCG------------TGCTGCTGCCGTCGAATTCTCGGATATTGTGATCCC
GTCCCACGCCGAGAGCACGGGACCAACTCTGGAGTGGGATAACTACGATCTGCATGAG--
----------GACAGCGCTGACACGTCGGTGTACGCCTCTCCCCTTGCAAGCAGCCCGCC
GCAGAAGACCCTGTTCCGATTCGGCGAGTCAACTGCAGGGTTCAGTTTCAGCTTCCAGCC
CAGCATTAGTCCTTCCAAATCCCAGGCCGCGGCAAACCAGAGCAGGACGTCGATTGGAAC
CGACGACGAGCTGGAAAGCACTCACGAAGAGGAACGGGATGGCCAGTACTTTGAGCCGGT
TGTCCCCATGCCGGATCTTGTGGAGATTTCGACTGGAGAGGAAAACGAGCAGCTGGTGTT
CAGCCACAGAGCGAAGCTGTATCGCTATGATAAAGATCTAAAGCAGTGGAAGGAGCGGGG
CATCGGCGAGCTCAAGATCCTGCAGAACTTTGACACCAAGCGCACAAGGCTCATCATGAG
GCGAGACCAAGTTCTAAAACTGTGCGCCAACCACTGGATCACCACCGACATGACTCTGGA
GCCCATGAAAGGCTCCGAAAAGGCCTGGATCTGGAGCGCCTATGACTTTGCCGAAGG---
AGCGGGGAAGGTGGAGCAGCTGGCCGTGCGCTTTAAATTGCAGGAGATGGCAAATTCCTT
CAAAAACTTTTTCGACAGAGCCAGAGAAGCTCAGAAAACTAAAACCCTAATTCTATCCAC
ACCTTCTAAAGATACC--------------------------TCCAACTCCCG-------
---GGAGACCATC---TGTGGGCAAGCGGCTATTGCAGTTTTGGAGGAAACCACTGCAGA
ACAAACGGCGCCTTTCTCCG-------------CCGAGGAGACAACGCCGAC--------
---TTACAGTCCACAAGGCACTCCCAAATCAGTGGTCTCGCCCCCTAAATTTGTCTTTGG
AACAGGCGCTATGGAGAAGTTCTTTGGAAGCCCTGTGTTGGCCCAACAGGTGGTGGCCAG
TCCAACTGCCGATGGGAAAATTAAGGGACCGAAGG---------GCACCCAGGC------
----GAGCGGTCCTGACTTGCCCA-------------------------AGCCTCGATTT
CAAGTGCCAGAACAAGTTTCTGTACGTAAGGATCAGGATGAC------------------
-------------------------------------GACTC---TGCGGTTGAAATCGT
ATTTGAACGGGTTCCCAGCGCTGAACAAGCAGAACTGGCTCGGCAGCTCCTGCTGCCCAA
AACCTTCTTCCTGTATAAGAGTGAACCGGGCTACGTGAGCGATGATGGAACCGACGATGA
AGATTATGAGACCGCAGTGAGGAACCTGAACGGACGCCTGTACCCTGACTCACC------
------------------------------------------------------------
-------------CACGCCCCGGACAGT--------------------------------
---------CCCACACAGAGGAGGTGCAGCTGA-AGACCCCGACTGTGT--GATCATCTG
GGAGAAGCAACCCACTCAGGAGGAGGAGCTGAGGGCCAGGACGCTCCAGCTCCCTCGTAC
CTTCTTCTGCGGCGCTGGGAGCGACACGGACAGTGAACCCAGCAGTCCAGAGGACTTTAC
TTCTGAAGTCCAGAAGGTGGGACAGTCTGAGGGGA-------------------------
------------------------------------------------TCAGTCAGGAAC
ATCCAC------------------------------------------------------
--------------------------------------------CCTCTGACGATGCA--
------------------------------------------------------------
----------------------------------GCAGCTCCGACTGACACCAACAGGAG
TCCTG-------------------------------------------------------
------------------------------------------------------------
------------------------------ATCCTGACCGGCCTTCCACAGCTGACCAA-
----------------------------GGACGTCCCGTTGATCTGTCTACCA-ATATCC
CACCGACGCAGTCCAC--------------------------------------CACGGA
TACGAGTAAAAAAGATGTTCC---ATCGTTCACATTCTGCTCACTGGGTGGATTTTCATT
CGCTGACCTCGCAAAAAATTCTGGAGAATTTGCCTTCGGAAAACAAGATACCAACTTTTC
GTGGGCCAATGCCGGTGCGGTTGTTTTCGGCAGCGGTGCAAGCGCTTCACAACAACACGA
CGAAGACGACGAC------GAGGAGGACGGTGGTGACGACGAGGCCAACAACGCGGATAT
TCACTTCGATCCCATAGTGTCATTGCCTGAGGTCGTGGTGAAGTCTGGTGAGGAGGACGA
GGAGATCCTCTTTAAGGAGAGGACGAAGCTCTACAGATGGGACCGCGATCTGAACCAGTG
GAAGGAACGCGGTGTGGGTGACCTTAAGATCCTCTTTCACCCGGAGAAGAAATTCTACCG
CCTGCTGATGAGGCGCGAGCAGGTTCTGAAGGTGTGCGCCAACCACACCATTACCAGAGA
CATGGAGCTGAAGCCCATGAACACCTCCACCAGCGCACTGGTGTGGACCGCCAACGACTG
TGCAGAGGGGGAACCGAAGGTGGAGCAGCTCGCTGCCAAGTTCAAGACGGCGGAACTCGC
CGAGGCCTTCAGGAAGACGTTCACACACTGTCAGAACTGCATGTCCCAGGT---------
------------GGATTCCTCCCCTTCTTCCAAAATGGCTGAGCTGACCAGGCCGAGCAA
CCCGCTGGTGTTTTTCTCCATTGCGTTCGACGGCGAGGTCATTGGACAGATCACCATGGA
GCTTTTTACGCACATTGTTCCCAAAACGGCGGAAAACTTCCGAGCTCTGTGCACCGGAGA
GAGAGGCTTCGGATACCAGAATTCCGTCTTTCACCGGATCGTCCCGGATTTTGTTTGTCA
GGGGGGCGATATAACCAAACAGGATGGAATGGGTGGGCAGTCCATCTACGGGGGGAAGTT
TGAGGATGAGAACTTTGAGGTGCGACACACTGGACCGGGTCTGCTGTCCATGGCTAACTC
AGGTCGGGACACAAACAGCTCTCAGTTCTTCATCACGCTGAAGAAGGCGGAGCATCTGGA
CTTTAAGCACGTGGCGTTTGGTTTTGTCAGGGACGGGATGGACGTGGTCAGACGCATGGG
GGAGCTGGGCTCCAAAACCGGCAAACCCAGCAGAACCGTCACAGTGGTGGACTGCGGCCA
GCTGTGA------
>Distichodus_sexfasciatus_gill_4|006485|C914149|m.54773
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------CCGTG
TACATTTTTTAATTACAAACATGTGCCTGGATATGTCAGTGATGA---AACTGATGATGA
AGATTACCAAACTGCAGTGGAGAGTTTGAATGGGAAGCTTTATCCTGATTCTGCAGA---
------------------------------------------------------------
------------------------------------------------------------
---------CCCAGCTCAAGCTACTGC-------GGACCCAGAGTGTGT--GCTTGTCTG
GGAGAAGAAACCAACGCTGGAGGAGGAGAGAAGAGCGACGAGTCTCCAGCTCCCTCCCAC
ATTCTTCTGTGGTTTGGAGAGCGGTGCTGATTCGGAG---------TCGGACGACTTTGG
GGCGGAGCTGCAAAAGGTACAGCAAGCTCAGAGAG-------------------------
-------------------------------------------------TAACAAAGAGC
GAGAAA------------------------------------------------------
-------------------------------------GACACGTCATCAGAGGA------
------------------------------------------------------------
---------------------------AAGCTCCCCGAAGCCAAGTAGTACCAGCCCTGA
AGCCA---------------------------------------------------CCCC
TG----------------------------------------------------------
-----------------------------------------CTTTCTCAGACCAGACTGC
CACAGCT---------------GATAGTGGCCAACCCATCGATCTTTCTTC---AAAGAA
CCTTGACGCTAAAACTCCTTCTGA------------------------------TACAAA
AACCACTCAAGATGCCCCTGA---CGGGTTTGGGTTTGCCACTCTAGGTGGATTCTCATT
TGCAGACCTGGCAAAAAACTCTGCTGACTTCTCTTTTGGAAAACAAGATGCTAACTTCAC
TTGGGAAAATGCGGGAGCAACAGTGTTCGGGGGTCCCG---CGGCCGCGCCTCGAAACAC
GGAGGACGAAGGGCACAGTGACGACGACGACGATGCTGGTGCTTCCAATAATGAGGACAT
TTACTTTGAACCAGTTGTTTCACTCCCAGAGGTGGAGGTGAAGTCTGGCGAGGAGGACGA
GGAGGTCTTCTTCAAAGAGAGGACCAAGCTTTACAGGTGGGATCGAGACCTGAACCAGTG
GAAAGAACGGGGCGTCGGTGACATCAAGATCCTCTACCACCCAACCAAAAAGCACTACCG
CATTCTGATGAGGCGCGAGCAGGTCCTAAAGGTCTGCGCCAACCACACCATCACCCAGGC
CATGGAGCTCAAACCCATGAACACCTCGGCCAACGCGCTGGTCTGGACGGCCAGTGACTA
CTCAGATGGAAGTGCAAGAGTGGAGCAGCTGGCAGCCAAGTTCAAGAACCCCGAGCTTGC
TGAGCGCTTTCGAAAAGCCTTTACAGACTGTCAGAATTTCATGTCCCGAG----------
--------------TCGACTCCCAGGCCTCCAGGATCCTGGAACTTTCCAGACCCAGTAA
CCCCGTAGTGTTCTTCACCGTGGCGGCAGACGGCGAGGTCATTGGCAAGATCACGATGGA
ACTTTTTGCTCACGTTGTGCCAAAAACAGCTGAAAACTTCCGGGCTCTGTGCACTGGAGA
GAAAGGATATGGCTACAAGAATTCCATTTTTCACAGAATAATCCCAGATTTCATGTGTCA
GGGTGGCGACATTACCAAACAGGACGGAACCGGAGGGAAATCCATTTATGGAGGCAAGTT
TGAGGACGAGAGCTTTGAGGTGCGACACACCGGCCCAGGCTTGCTGTCCATGGCCAGCCG
CGGCAGAGACACCAACAATTCACAGTTCTTCATCACACTGAAGAAAGCGGAGCATCTGGA
CTTCAAGCATGTGGCCTTTGGCTACATTAAAGACGGAATGGACGTGGTGAAACAGATGGG
GGAGCTGGGATGCAAGAGCGGCAAACCCAGCAAAAAGATCGAAATCGTTGAATGTGGCCA
GTTGTAA------
>Lepidogalaxias_salamandroides_Head_2|019448|scaffold18035|m.24512
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------TCTGCG
GAGGCC------------------------GACGGCGCCGTCGGTTCGAAAGCCAGGGAT
GACGGG------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------CATGCCACGCCTCCAGCTG-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------CTTCTACGTTC
AAAGTGCCAGAAAAAGCCCTCGGGAAAGAGGAGGCAGCCTGG------------------
----------------------------------GCGGACTTGGACGAAGTCCAGATAGT
TTGGGTTCGAGAGCCCACAGCAGAACAGGCCCGGCTCGCTCAGGAGCTCATGCTGCCTCA
CACCTTCTTCTGCTACCAGAACGAGCCTGGCTACGTCAGCGATGACCCGGACGATGACGA
GGACTTTGAGACTGTAGTGCAGAGACTCAACGGGAGGCTATACCCAGATCTCCCGGAGAA
AACGGCTTCAGCTCCAGTGGGAAGGACTACCACTCCTGTAGAACCTGGTGACACTCCTGT
TGAAACCGCTGTTACTCCTGCAGATACCAATGTTACTCCAGCTGCTGCGGC---------
---------CGGGTCTGTCGGGGAGG----AAAAGGAACCAGAGGTGGT--CGTGGTCTG
GGAGCAGAGACCCACGCCCGAGGAGGAGCGGAAGGCCAAGAGCCTCCAGCTTCCCCCGAC
GTTCTTCTGTGGCGTGGGCAGTGACACCGAGGCAGAGAAAGACAAGGCGGAGGACTTTGA
AACCGAAGTCCAAAAGGTTCAGGAGGCTCTGAAAA---------GCGAAGCCGCGGGAAC
CTTCGAAACT--------------------------------------TCAACAAGCGGC
GGGGAC------------------------------------------------------
----------------------ATCGCCGTAGCGACGAGCGCGACTCCAGACG-------
------------------------------------------------------------
-----------------------------------TGCGGCTCGTCACCGTCAAAACTGA
AACT--------------------------------------------------------
------------------------------------------------------------
-----------------------------------------CTTCCTCCCGCCGTCCAAT
CGGAATCTTCTGTC--------GCCACCAGCTGCCCTATTGACCTCTCGACTAAAAAAAG
CACTGAAGATGACTTG------------------------------------------AC
CACCCCTCAAGATGCTGCTCCTGTTGCGTTTGGGTTCAAGGCCTTAGGCGATTTCTCCTT
TGCGAGCCTAGCCAGCGCCAGCGGCGAATATGCGTTTGGTAAAAAAGATTCCAACTTCTC
CTGGGCCAACGCCGGCGCCTCTGTGTTCGGCTCCG------CGCCGACGCCTAAGAACGA
GGGAGAGGAGGGT---------GGGAGTGATGAAGAGGACACTACTAACGATTCAGACAT
TCACTTtgacccaATCGTGTCTCTACCCGAGGTGGAGACCAAGTCGGGCGAGGAGGACGA
GGAGATCCTGTTTAAGGAGCGCACCAAGCTGTACCGCTGGGACCGGGAGGCCGGGGAGTG
GAAGGAACGCGGGGTGGGCGACATCAAAATCCTCTACCACCCGCTGAAGAAGTACTACCG
CGTGCTGATGAGGAGGGAGCAGGTGCTCAAGGTGTGCGCCAACCACACCATCACGGAAGG
CATGGACCTCAAGCCCATGAACACCTCCAACCAGGCCCTGGTCTGGACCGCCACCGACTA
CACAGAAGGAGAAGGGAAGGTGGAGCAGCTGGCCGCCAAGTTCAAGACGCCCGAGCTGGC
CGAGTCCTTCCGGAAGTCGTTCACCGACTGCCAAGGCCGCCTCTCGCAGGC---------
------------AGACGCCGCCCAGCTGTCGCGCGTGCTGGACCTGTCCAAGGCCACCAA
CCCGCTGGTGTACTTCTCCGTCTCCGTGGAGGGCCGGGCACTGGGCAGGATCACTATGGA
GCTTTTCTCCCACATCGTCCCCAAGACAGCGGAGAACTTCAGGGCGCTGTGCACCGGGGA
GCGAGGCTTCGGCTTCCATGGCTCCATCTTCCATAGGGTCATCCCGGACTTCATGTGTCA
GGGTGGCGATATCACCAACCAGGACGGCACGGGGGGGAAGTCCATCTACGGGAGCAAGTT
TGAGGACGAGAACTTTGAAGTAAGGCACACGGGGCCCGGCCTGCTGTCCATGGCCAACCG
TGGCAGGGACACAAACAACTCCCAGTTCTTCATCACCCTGAAGAAGGCTGAGCATCTGGA
CTTTAAGCACGTCGCCTTTGGGTTTGTCAAGGACGGCTTGGACGTGGTCAAACTCATGGG
AGAGCTTGGCACAAAGACAGGGAAACCGAGTAAAACTATAACCATCTCTGATTGTGGACA
GCTGTAG------
>Melanotaenia_praecox_viscera_mixture_8|019188|scaffold7516|m.6440
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------ATGAGAAGGGATCAGGTGCTGAGGGTTTGTGCCAACCACACAATCTCACATAC
GATGGAGCTTAAACCCATGAACGCCTCGGCTAACGCGCTCATCTGGACTGCCACTGACTA
CTCAGATGGCGATGCTGTTGTGGAACAGCTGGCTGCCAAATTTAAAACCCCTGAAATAGC
TGAATCCTTCAAGAAGATTTTCTGTGAGTGTCAGAGCCGCATGGGTCAAACCAGCGTCGA
TGCTACTTGCGTCTTGTCACCACAGATGTCCAGAGTCCAGGAGCACTCCAGAGAGACTAA
CCCACAGGTGTTCCTTAAAGTGGCTGCTGATGACCAGCCACTGGGCACCATCACTATAGA
GCTTTTCTCCCATATTGTTCCTAAAACTGCAGAAAACTTCAGGGCTCTCTGCACCGGAGA
GCAAGGCTTTGGGCTGAGGGACTCCATCTTCCACAGGGtcataccaGATTTCATGTGTCA
GGGTGGTGATATCACCAATAACAATGGCACAGGAGGAAAATCCATCTACGGCAGAGCGTT
TGAGGATGAAAACTTTGATGTCCGGCACACAGGCCCTGGGATCCTATCGATGGCCAACCG
CGGACGTGACACCAACAACTCACAGTTCTTCATAACCCTAAAGAAAGCCGAGCACCTGGA
CTTCAAACACGTGGCTTTCGGCTGGGTACGAGACGGCATGGATGTGGTGCAGCAGATGGG
AGAGCTGGGCACAAAGGGAGGCACTCCCACCAAGAAGCTGGTCATTACAGACTGTGGACA
GTTGCACCTCTGA
>Pantodon_buncholzi_mixed|015130|scaffold17945|m.24896
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------ATGGAACAGCCTTCAAACTTTGGTTTTTCTTCAT
CT----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------GGATTTTCTTT
TGCTGACCTGGCAAAGACCTCTGGGGATTTTGCTTTTGGAAAGAAAGATTCTAATTTCTC
TTGGGCCAACGctggggcggctgtcttcagcT---------CTTCACCATCCAAGAATGA
AGCGGCGGATGAA------------AATGGCGACGACGAAGCTTCCAGCAATGTAGAAAT
TCACTTTGAACCTATAGTGTCTCTGCCTGAGGTGGAGACCAGGTCTGGTGAGGAAGACGA
GGAGATCCTGTTCAAAGAGCGCACCAAGCTGTACCGCTGGGACCGGGACGTGAACCAGTG
GAAAGAGCGTGGTGTAGGCGACCTGAAGATCCTTTACCACCCGCAGAAGAGATGCTACCG
CTTGTTGATGCGGAGGGATCAGGTGTTCAAAGTGTGTGCCAACCACACCATTTCCAAGAA
CATGGAGCTGAAGCCGATGAACACGTCGGCCAACGCACTTGTGTGGACCGCAACCGATTA
CACGGATGGAGAGGGTAGGGTGGAGCAACTGGCGGCCAAGTTTAAGACGGCCGAGGTGGC
CAGCGCCTTCAAGAAGAAGTTTGAAGAATGCCAGAACTTCATGTCCCAGTC---------
------------TGAGACAACCCAACAGTCCCGCTTGTGGGAGTTGTCCAGAGAGGATAA
CCCGGTGGTTTTTCTCGACATTGCTGCCGACAGCCAGCTTCTGGGCAGAATAACCATCCA
GCTCTTCTCACACATCGTCCCTAAAACCGCAGAGAACTTCAGAGCTCTGTGCACGGGAGA
GCAAGGCTTTGGTTATCGCAACTGCGTCTTTCACAGAGTCATCCCAGAGTTCATGTGCCA
GACTGGTGACATCACCAAACAGGATGGCACCGGGGGCAAATCCATCTACGGCGACAAATT
TGAAGACGAGAACTATGACGTGAGACACACAGGACCAGGCGTGGTCTCCATGGCCAACCG
CGGCCGGGACACCAACAACTCGCAGTTCTTCATCACCCTGAAAACTGCAGAACACCTCGA
CTTTGTGCACGTCGCTTTCGGCTTCGTCAAACACGGCATGGATGTGGTGAAGCAGATTGG
GGAGATGGGCACAACCAGCGGCAAGTCAAGCAAAAAGATAGTGATTGCTGACTGCGGGCA
GTTGTCG---TGA
>Scleropages_formosus_red_gill|027329|scaffold43121|m.57115
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
GGCATTGGAAATGTTGCATCT---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------ATATCTATGCCA-----------------------------------------
------------------------------------------------------------
---------------TCTCTAGATAAGGCTGAGCATCTG---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------GAAAATCCTCTAATTTCTGGGAAGCTTAACTTGTTCAGTTTTGCAGA
TTTGGCAAAATCCTCATCTGGTGACTTTCAGTTTGGACAGAAGGACCCTGATTTCAAAGG
CTTTTCTGGTGCTGGGGAGCAGCTCTTCTCCTCATTTC---AGGCTGACAAGAAGGCAGA
CACCTCTGCAGAACAGGATGAA---GGCATGTACAGAACAGAGGAGAATGATGATATCCA
GTTTGAACCTGTGGTTCAGATGCCTGACAAAGTGGACCTCATTACTGGGGAAGAAGATGA
GGAACCACTTTATTGTCAACGTCTCAAGCTTTTCAGGTTTGATCCTGTTACCAGCCAGTG
GAAAGAACGCGGAGTGGGAAATCTTAAGTTCCTGAAAAACAGTAAAAATGGAAGACTAAG
AGTACTCATGAGACGGGAACAAGTACTGAAGGTATGTGCTAACCATTGGATCACTACAAC
TATGAACCTGAAGCCCCTTTCTGGGTCAGATAAGGCCTGGATGTGGCTAGCCAATGACTT
CTCAGACGGTGAGGCTAAGCTAGAGCAACTTGCAGCAAAGTTTAAAACAGCAGAGCTGGC
AGAGGAATTCAAGCACAAGTTTGAAGAGTGTCAAAGATTGCTCTTAGACATACCCTTGCA
GACTCCTCACAAACTTGTTGACTCTGGGAGAACAGCACAGCTCATTCAAAAAgcagagga
gatgaaatctggcctgagAGATCTTAAATCCTTCCTATCTGATGACAAAACAAAAGTCAA
AGATGAAGAAAATCAA------ATCAGTACATCTGCTAATACTTCTGACATGATTGTTAA
ACCCAAAGCTGACATTACCGGGCCTGCTTTGGAGTGGGATAACTATGACTTGCGAGAAGA
TGCCCTCGATGACAGTGCACAGACTTCGGTGTATGCTTTTCCGTTAGCAAGCAGTCCAGT
TCAGTCAAATTTGTTCCGTTTTGGAGAATCAACTGCTGGCTTCAGCTTCAGTTTCCAGCC
CATTCTTAGTCCATCCAAATcTCCAGCTAAACTAAACCAGAGTAGAGCTTCTGTTGGCAC
TGATGAGGAATCAGAAGTAACTCAGGATGAAGAAAGAGATGTACAGTATTTTGAGCCTGT
GGTTCCTTTGCCTGATCTTGTGGAAACCGCAACTGGTGAGGAAAATGAGCAAGTGGTGTT
TAGTCACAGAGCTAAACTGTACCGCTATGATAAAAATCTGAATCAGTGGAAAGAGAGAGG
CATAGGTGAACTTAAAATCTTGCAGGATTATAACACTAAACGTGTTAGACTTGTCATGAG
GCGTGATCAGGTGTTGAAACTTTGTGCCAACCACTGGATTACCCCAAATATGAAGTTGGA
AGCCATGACTGGGGCTGAGAGGGCGTGGATTTGGAGTGCCATGGATTTTGCAGAACC---
TGAAGGGAAAGTGGAGCAACTGGCTGTCCGTTTCAAACTGCAAGAGGTAGCAAACACATT
TAAAGAGATCTTTGACAAGGCTAAGAATGCCCAAGAAAATGAGGATCTGGTTACTCCTGT
CTCGCCTAGAGAGGC-------------------------------------------AC
CATGTGACTCAAA--ATGCGGTGAAGCTGCAATTGCAGTTCTTGTGGAGACCACCAGAGA
AAGGACTGAATTGAGTCCTCAGAGCAACCAGACCCCAGATATTACAA-------------
-----------------GTTCTGCTGCAAAAATAGTTTCCCCACCCAAATTTGTTTTTGG
CTCGGATTCTGTTCAAAAAATCTTTGGAACCTCTCCCTCTTCCAAAGAGATTATACCCGC
CAC--------------AAAAATGGATACCAAGGCCACCATATCCTCCTCAAGCTCTAAG
ACTGATGTTGGCCCCATTAACCAAATTCCTACTGCAACACCTTCACAAATTCCTGCATTT
AAAGTCCCTGAAAGAGCTATCAGTCAGGTTGTGAAAGAAAAA-------CAAAAAGAAGC
ACCAGTAGATGCTGCAAAGGTGGCGGCAGAGTCGCAGGACTCAGATGAGGTTCAGATTGT
ATTCGTACGGGAACCTACCACTGAGCAGAGAGAACTGGCCCAGGAACTCATGCTGCCCCT
CACCTTCTTCTGTTATCAAAGCGAGGCTGGCGACAGCAGTGATGACCAGGAGGATGATGA
AGACTTTGAAACTGCTGTACGGAAGCTTAATGGTAAATTGTATCCTGATGCAGTACAGGG
AGGAGCTAA---------------------------------------------------
-------------TGGCCAGAGGATGTCAAT-----------------------------
---------GGAACCTCAAGTTGAGG----AGAGGGATCCAGAGTGCAT--AGTGATTTG
GGAGAAAAAACCAACCCCTGAAGAGGAGGAGAAGGCCAGGAGCCTCCAGCTTCCTCCCAC
CTTCTTCTGTGGAATCGGCAACGACAATGAGCCCGAGAAAGACAAGGCGGAAgactttga
aacggaagtcaaaaAAG-------------------------------------------
-------------------------------------------------AGATGAAGAAT
GATGCT------------------------------------------------------
----------------------------------------GTGTGCTCAGAAAATACACT
TTCCAGCGACGCTAT---------------------------------------------
---------------------------------------CCCAGCCAGGGCCTGCACCAC
AGCAG-------------------------------------------------------
-----------------------------------TTAAAGTAC----------------
--------------------------TTGAGTCTCAGCCGGACTCTTCCAGTGATACTGC
CCCTGTCCTCAGTC---------------------CCATCGATCTATCCACAAGGAAGGA
CAATGAGCCGGACTCG-----------------AGCACCT--------------CAGCAT
CATCGGC-----------------ATCCTTTGGGTTTCATTCCATGACTGGATTTTCATT
TGCAGACCTGGCTAAGAATTCTTCTGAATTTGCTTTTGGGGAAAACGATGCAAACTTCTC
TTGGGCGAATGCTGGAGCTGCTGTATTTGGG-GAA-----GCTGCAGTATCTCAAAATGA
AGTAGAAGAGGGT------------AGCGATGATGAAGAAACCACAAACAATGCGGATAT
TCATTTTGAACCTATTGTGTCTTTACCAGAGGTAGAGACTAAGTCTGGTGAGGAAGACGA
AGAGATCCTTTTCAAAGAGCGGACCAAGCTGTACCGTTGGGATAGGGACTTGGGCCAGTG
GAAGGAGCGTGGTGTGGGAGACATAAAGATTCTGTACCACCCCATGAGGAGGTACTACCG
GGTGCTAATGAGGCGGGATCAGGTATTGAAAGTGTGTGCCAACCACATAATCACCAAGGC
CATTGAACTCAAGCCCATGAACACCTCAGCCAATGCCTTGGTCTGGACTGCCACAGACCA
TGCAGAGGGAGATGCAAAGATCGAGCAGCTGGCTGCCAAGTTCAAGACAGCTGAGCTGGC
AGAGTGTTTCAAGAAGAAGTTTGAGGAGTGTCAAAGCCGCATGTCCCAGGC---------
------------GCAGTCCTCCCAGCTGTCCCGTGTCCAGGAGCTGTGCGAAGAAGGAAA
TCCCATGGTGTACTTTGACATCACTGTAGATGGACACCTGTTGGGTCGGATCACCATGGT
GCTCTTCTCACACATTGTCCCTAAAACTGCCGAGAACTTCCGAGCCCTGTGCACTGGAGA
GCAGGGCCTCAGTTTCCTCAACTGCATTTTTCACAGGGTCATTCCTGAGtTCATGTGCCA
GGGTGGAGATATCACCAAACAGGATGGCACTGGGGGAAGATCCATTTATGGAGACAAGTT
TGAGGATGAGAACTTTGACGTGAGACACACAGGACCAGGCATCCTCTCCATGGCGAACTG
GGGTCGAGACACTAATAATTCCCAGTTCTTCATCACTCTGAAGACAGCAGAGCATTTAGA
CTTCAAACACGTTGCCTTTGGCTTTGTCAAAGACGGCATGGACATAGTGTATCAGATGGG
GGAACTTGGCACAGCAAGTGGGAAACCAAGTAAAACCATAATTATTTCTAACTGTGGACA
GTGCTAG------
>Synodus_sp._gill_5|014288|scaffold1916|m.2043
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------TGTCGGGGGCC--
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------TCA
GGTTTTGGGGCTGCTT--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------TTGTGAGAAAGGATGGGCAGT-----------------------
------------------------------------------------------------
------------------------------------------------------------
-GGGACTGTGAATCCTGCCTTGTCAGAAATGATCCATCAGCTTCCAAATGTGTTTCCTGC
TCCAATCCTTGTCCTA--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------ACCCCTCACTTGCGGCCATG
TTTGCTAAGACGGAAGGACAGTGGGATTGTGACAGTTGCCTAGTAAGGAATGACTCCACA
GTTAACCAGTGTGTGTCATGTCAGTCCCCCAAACCCAATGCTA-----------------
--AAAACCCTGGTATTG--CAGCCCCCTCCAGTTCCTCCTTTAGCTTTAGCTTTGGGAGC
AAGTCTTCATCTGGTCAGCTTGATGGAACCGGCTTTACAG-CAGCCTTTGGGAGCAGTGG
CCCTTTTCAATTTG----------------------------------------------
----------------------------------GTCAAAGTAAAGATAAAAGCTCTGCT
GCTTCTTTCAAATT---TGAGGCTCCAGCAGCTGGCTCCACTGCCTCAGGATTCACTTTC
TCAGTCCCATCCGG------------------------TGGTTTCCAGTTTGGCACCCAG
GATACTCAAAACGAAACTCTTGAAGCCAACACTCAAGGACCTGCGTCAGGG---------
------------------------TCTGCCTCTATGTTTCTGAAAAACATTGCTGACCAG
CATCGGGAAAAAGAGAGAGAATCTAATATTCCCGCTCAAACATCAGCGAATCAGTGTGA-
------AAATGATGAAAATCCACTGTTCACTGATAAGCCCAACACATTTAGTTTTGCAGA
TTTGGCACAGTCATCTGGGGGGAACTTCCAGTTTGGCCAGAGTGATCCAGATTTCAAAGG
CTTTTCTCGTGCTGGTGAACAGCTGTTTTCATCATTCTCAACAGCTTCTAACATTGCCAA
CACCTCAGCTGACCAGGATGAAGAGGAGATGTACAAGACAGAGGAGAATGATGATATACA
GTTTGAGCCTGTGGTTAAGATGCCTGAGAAGGTTGACCTTGTGACAGGAGAGGAGGATGA
ACAGGTCCTCTACTCTCAGCGTGTTAAGTTGTTCAGGTTTGACACAGGTACCAGCCAGTG
GAAGGAGCGTGGGGTGGGAATCCTTAAATTTTTGAAAAATACCACCAATGGCAGATTAAG
AGTTCTTATGAGAAGAGAGCAGGTATTGAAAGTCTGTGCCAACCACTGGATAACCACCAC
TATGAACCTAAAGCCCTTAGCAGGGTCTGACAAAGCTTGGATGTGGCTGGCCAATGACTT
CTCTGATGGAGATGCCAAACTGGAACAGCTGGCTGCTAAGTTCAAAACTCCAGAGCTGGC
TGAGGAGTTCAAGCTTAAATTTGAGGAGTGCCAGAGACTACTCTTAGACATCCCATTGCA
GACACCCCATAAACTTGTTGACACAGGCAGAACTGCACACCTAATTCAGAAAGCTGAGGA
AATGAAATCTGGCTTGAAAGACCTTAAATCCTTCTTGACGGATGACAAAGCAAAGATCAA
GGATGATGACAGTCAAGCAGATATTACAACAGTCAGCAATGTTTCAGGACTGGTCATAAA
GGCCCATGCTGAGAGTACTGGGCCAACCTTGGAGTGGGATAACTATGACCTTAGGGAGGA
TGCTCTAGATGACAGTACTGAAACATCCGCTTATGCCCCTCCTGTTTGCAGTAGCCCCAT
CAGAAAGAACCTTTTCCGCTTTGGAGAATCTACTGGTGGTTTCAACTTTAGCTTTCAGCC
CAAAATCAATCCTTCCAAGTCTCCAACTAAGCTTAACCAGAGCTCAGCATCAGTGGGCAC
TGATGATGAACAGGATGTTACCCAAGATGAGGAGAGAGATAGTCAGCACTTTGAGCCTGT
GGTGCCTTTACCTGACCTGGTGGAGATTTCCACAGGGGAGGAGAATGAACAGGTGGTGTT
TGGCCATCGGGCCAAGCTCTACCGCTATGACAAAAGCCTTGGCCAGTGGAAAGAGAGGGG
CATTGGAGAGCTAAAGATACTGCAGAATTATGACACCAAAAGGGTGAGGCTGATCATGAG
GCGAGACCAGGTACTAAAAATCTGTGCCAATCATTGGATCACATCAGCCATGAAGCTGGA
GCCCATGAAAGGTGCCGAGAAGGCTTGGGTTTGGTTTGCCATGGACTTTGCTGAAGGTAC
AGAAGCCAAAGTGGAACAGCTAGCAGTGAGGTTCAAACTTCAGGAGGTGGCAAACACGTT
CAAAGAGGTCTTTGAGGAGGCCAAGGTTGCACAAGAAAAAGAAGTTCTCTTGACCCCTGT
TACATCTAGAGTGGCTACTCCTCTTGAGGTTGGAGCCTCAGGATCAACTACAGCAGCAAC
TGCAGCAACTACAGTGTGTGGAGAAGCAGCAATAGCTGTCTTGGAGGAGACCACCAAGGA
ACGCACAGAGCTCTCTTCTGACACCTGTCACACCCCTGATGGCAAGACAAGTGGAACTAC
ATTTCACACTCCATCCAGCTCCTCAAAAACTGTGGTTTCTCCACCTAAATTTGTCTTTGG
GACAGAAAATGTGCAGAAAATCTTTGG----------CCTGCCCACAATGT---------
-----CCTCCAGTCAAGAAGAGCATTCATCAAGCC------------CCAAAGC----CA
GAGAGAGTGGACCCCCTGTGCCAT-------------CTGCTTCTGCGCAACCGGCATTC
AAAATCCCAGAGCAGGTGCTCTCTCAGGCAGAGGGAGGCAGTGCAGAC------------
----------------------------------CTGGACTCCGATGTGGT---GGTGGT
GTACGTGAGAGAGCCCACTGCTGAACAGGCTGCTCTGGCCAGAAAGCTGCAGCTGCCCCT
CACTTTCTTCTGCTACCAGAGTGAACCTGGCTACGTCAGTGATGACCAGGCTGATGATGA
GGACTACGAGTCAGCTGTCAAAGCACTGAATGGAAAACTGTACCCCGATCCCCCAGAAAT
GGTGGCG-----------------------------------------------------
-------------GCCGCAGCATCTGGTGATGGCTCTCAAGCAGAGGTGATGGTGGAACA
GAGAGAGGTTGCATCCTTGGATGAAGGCACTGTGGAATCAGAAGATTGTCAGGTGGTGTG
GGAGAAGAAGCCCACCCCTGAGGAGGAGGAGAAGGCCAAGAGTCTGCAGCTCCCCCCGAC
TTTCTTCTGTGGCTTAGGCA---ACATCGATGGAGAGGCCGAGAAGCTTGAAGATTTTGA
GACCGAGGTCCGCAAAGCGCAGGACGCACTGGATGCCCAGCTGAACACAGAAGCTGCTCC
TGTTTGCACCACAACTGAGACTCTGGAAAAACCAGCCTCAGATCAACTCTCACCGAACAC
GGAAACCGATCTTGCCAGCATCACAACTGAAAGCCCTGAGGAACCACCTTCAGATCAACT
CTCACTCATCAGTGAAGTTGCTCCTGCCAGCACCACAACTGAAACCCCAGAAGAACCAAC
TTCAGATCAAGTTTCACTGAACATGGCAGAGGCTCCCTCTAGTGTCACAACTGAAACCCC
AGAAGAAGCAACTTCAGATCAAGTCTTAGTCATCACCGAACCCGCTCCTGCCAGCACCAC
AACTGAGACCCCGGAGGAACTAACCTTAGATAAGGTCTCACTGAACACAGTAGCAGCTCC
TGTCAGCACCACAACTGAGAACCCGGAGGAAGCAGCTGAGGCACCTGATGAGGTTTCCAG
CAGTACTGAAGCCACAGATGTTTCTGTTGAAGCAGACAAGCTCTCCTCAGTCAAGCCAGT
GGAAGTTCTTAGTTGGACCCCAAGCAGTAGCGCACCCATAGACCTGTCCACCAAGAAGAG
CTCTGAGCCAGACTCCCCTGCTGATACCGCTAGAACAACTGTTCCATTTACCACCACTGC
CACAGATAAAGATACTTCCTC---CGGTTTTGGATTCAATACACTCGGAGGATTTTCATT
TGCAGACCTGGCCAAAAACACAAGTGACTATGCATTTGGACAGAAAGATGCTAACTTCAT
GTGGGCGAACGCCGGAGCGACTGTGTTCGGCGGTGCCGGGCCGGCAGCACCAAAGAACAG
CGGGGACGGAAGC---------------GACGAGGAGGAAACTCCAAATAACGTGGACAT
CCACTTCGAGCCAATCGTTTCCCTGCCTGAGGTGGAGACCAAATCGGGTGAAGAGGATGA
AGAAATCCTCTTCAAGGAGCGCACCAAGCTGTACCGCTGGGACCGTGATCTCGGCCAGTG
GAAAGAGCGAGGTGTCGGTGACATCAAGATCCTCTACCACCCGGCTAAACACTGCTACCG
CATCCTCATGAGGCGGGAGCAAGTGCTGAGGGTGTGTGCCAACCACACCATCATCGCCGG
CATGGAGCTTAAACCCATGAACACATCGGCCAACGCGCTGGTCTGGACTGCCACGGACTA
TGCAGAGAGTGAGGCCAAAGTGGAACAGCTGGCAGCGAAGTTCAAGACACCAGAGCTGGC
CGAGTTGTTCAGGAAGACGTTCTACAATTGCCTAAGCCACATAAATGAGAC---GCCAGA
TGATCCGTCAGTCACTTCCCCCATGATGTCAAGGGTCCAGGAGCACTCGAGGGACACCAA
TCCCCGGGTCTACATGAAGGTTTCAGCAAACGACGAAATGCTGGGCACAATTACCTTAGA
GTTGTTCTCTCACCTGGTGCCCAAAACTGCAGAGAACTTCAGGGCTCTTTGCACAGGCGA
GAAGGGCTTTGGTTTTAAAAACTCTATCTTTCACCGCGTCATACCAGACTTCATGTGTCA
GGGTGGGGACATCACCAAGCAGGATGGCACCGGTGGCAAGTCCATTTATGGCGGCAAATT
TGAGGATGAGAACTTTGACGTACGCCACACAGGCCCCGGCATTCTGTCCATGGCCAACAG
AGGCCGCGACACAAACAACTCTCAGTTCTTCATCACCCTGAAGAAGGCTGAGCACCTGGA
TTTCAAACACGTTGCCTTTGGCTGGGTGCAAGACGGCACGGATGTGTTGAGGCAGATGGG
TGAGCTGGGCACCAAGACGGGCAAGCCTAGCAAGAAGATTGTCATTACAGAGTGTGGACA
GCTCTAA------
