>Amblygaster_clupeoides|032629|TR58619|c0_g1_i2|m.79300
ATGGAAGACTCACATACACGATACAGCAAGCGCCTGCGCACTGGTACACGTCGGCGATAC
CAAGATGATGGAATCTCCGATGATGAGATTGAAGGGAAGAGAACCTTTGATCTGGAGGAG
AAACTACATTGTGATAGATTCAATTGTAACCTGGTCCAATACATGGAGGGAGAAGACTTC
ACCTTTGAGTACATCCAGAGAGAAGGCCTACGAGATCCTCTTGTCTTTGTGAAGTCAGAC
GGTCTTGGAATCCAAATGCCAAATCCAGATTTCAGCGTGAGCGACGTGAAACTGTTTGTA
GGGAGCCGGAGAATGATCGATGTGATGGATGTGACGACTCAGAAGGGCATTGAGATGTCC
ATGGGCCAATGGAGGCGCTATTACGAGACACCGCCCTCCCAGCGGGAGAAACTCTACAAT
GTCATCAGTCTAGAGTTTAGTCACACCAAACTGGAAAACCTGGTCAAGAGGCCTGCATCG
GTGGACGTGATTGACTGGGTGGACAACATGTGGCCACGTCATTTGAAGGAGAAACAACGG
GATTCGACCAATGCCATCATAGACATGCAATATCCTAAAGTACAGAAGTATTGTCTAATG
AGTGTAGAAGGCTCCTTCACTGACTTTCACATTGATTTTGGTGGCACTTCTGTGTGGTAC
CACATCCTACGTGGAGGAAAGGTGTTTTGGCTGATCCCACCAACACCCCAAAACCTGGAG
TTGTACGAGAACTGGGTGTTGTCAGGGAAACAAGGGGACATTTTCCTGGGTGACAAAGCA
ACACAATGCCAGCGCATTGAGCTGAAACAGGGATACACTTTCATGATACCCTCAGGCTGG
ATTCATGCAGTGTATACACCAGTGGACACTCTGGTGTTTGGAGGGAACTTCCTTCACAGC
TTCAATATTCCCATGCAGCTCAACATCTATAATATTGAGGACAGGACAAGGGTGCCAGCT
AAGTTCCGTTACCCTTTCTACTATGAGATGTGCTGGTATGTGCTGGAGAGGTACCTATAC
TGCTTGACCAACGTCTCTCACCTCACCCCAGAGTTTCAGAAGCACTCGCTTGGTATTGGC
CTGAAACGAGAAGACTTCCGCCAGGAGCAGAAAGAGAACGGTCACACCAAAGAGGAAATT
GATGAGGAAAAAGATGAGGGAGCTGATATCAAAGAGGAAGAGGATCACAAAGAAGGAGAG
GAAAAGGAAGAAGAACATGATGACGATGACGAAGAGGAGGAGGCAGCGGCGTCCCCGGCC
AGTAAGCTGGGTGTTAAGGTGCACCTGACGCCCCTGGAGCTGGAGGGCCTCTGGCACCTG
CTGAGGAAGCTGGAGGAGCTGCCTGCCCACAAGAAGTGTGTGCCATCTGGCATCCGCAAC
GCCCCTGCCCTACTCAGCGACATACGGAGGTTGCTTGAAGAACATGCTGATGATGAACCT
ACATTGTCCTACACTGGAAAACCCATTGTGAAATGGCCCAGACGGCCATCATGGTACCGC
CCCCCCACCCCTCCCCCTCCGCTGCTGTACCGGCCGCGGCCCCCTGGGGCAGGGCCTAAG
CTGTCAGGGCCACGGGCCCCCAGGCGGCCCGCTGAGGCCCTGCGGCGACGGCGTGTGCGC
TGCAAGCGCTGCGAGGCCTGTCTGCGGAGTGAGTGCGGCGACTGCATCTTCTGCCGCGAC
ATGAAGAAGTTCGGCGGGCCTGGCCGCCTCAAGCAGACCTGCCTGCGACGCCAGTGTCTC
GCTCCGGGTTTGCCCAACTCAGCTGTGTGTGTTGTGTGTGGCGAGGGCAATCCCCTGGGT
GAGAATTCCACCCC---------TACACTCATGGAGTGCTCTTCCTGTGCCAAGATCACA
CACCCTGAGTGCCTCAAGGAACCTGCAGAGGGTGTAATTGACAAAGACCTGCCCAGTTAC
TGGAAATGTCCCAAATGTGTCCAGGAGAAAAAAACAGAGTCGGGCAGCAGCAGCAGTAGT
AGCGACGATGAAGACAAAAGCAGCGCTGTCCAGGGCGCCCGGGTCTCATCGGCGCCCCCA
GCCAAGCGTGCCCACCGGGAGGGCATCGGGGTGCGCGAGGGGCGTAGAGGAAGGCGCCCG
CTCACCCCCTCCAGGCGCC------TGCCACCCCCATCACAGAGGCTGCTGCTCCAGCAG
CAGCAGCAGAACAGGAAGAGGGCCGGTGCTCTGGAGCTACAGCTCAGGAAGAGGATTAAA
TTGGAACGAAATAAGATCTTA---------------------------------------
------CAGTCGCTCCTGCGGCAGCGCAGTATGGAGAGAGGGGGCGGGGACAAAACTGGG
CTTGGCAGGGGCGTGTCCAGAGGCAGAGGGGCGTCGTCCTTGCAGAGCT-----------
----CCGCCCACCCGGCCGTAGGCC-----------------------------------
-------GGGGAAGGGGGCGAGGTGTCCGTCTCAGGGGAGGAGGGAGAGGCGGAGGAG--
----------------------GCGTGGGGAGAGGGAGCGGAGACCTTCAGCGTAGCAGA
TCCGAGCGGGACGACACAGCCGACGACAGCGAGGATGAGGAAGACGAAG---------AG
GAGGAGAGGAAGGAGAATCGGCCGCAGCAGCAGGCCCGACGAGGGAAGGAACAGTCCCAG
TCTGAAGAGGAGGATGACAACGAGGATGACAGTGACGAGGGAGAGCAAAAGAATGGCGAT
GGGGAGAGAACCGACGGAGAGGAAGACAACGACAATGAGGATGAGGAGGAGGAGTCGAGT
GCAGGGAGGAGGTCGGGTCCCCCCAGCACAGCCATGCTACTGGGTGAGGAGGCGAGGAAG
C-------AGAACTCCTGCCTGACGGTGAAACTCCAGCCGGCAGCCCGCGGCCACCGTGA
TCCCAACGCTATTGTCCCCAAGCTGGAGGCGGCCATCACGCCCTG--------CTCGCCG
TCCTCCGCTCAGC-------------AGCGTGTCTGCCTGCTGCGGCCTCCACTCCGCAA
CGGCGCCTCCCACGCCAGC-------------------------------------GCTC
ATCCAGCCACGGCAGCGACGCGCATCGCCCGCT---------------------------
--CAGATAAGCCCTTAGCGACGAGCA--TGGCCCGCAACGGCAGAGGGCTCTCCCAC---
-----TCTGGTCGGGGTTCCCGAGGCCATTCG----------C------AAACCCGCACC
CACTCCTCCAGCAACACATCCTCCTCTTCCTCCACTCTCTTGTCGCTCCATCCCTCTGCC
CGAGATGGG---------------------------GGGAGCAGTCCGGGCTGTGAGAAG
GAGGTGTGGGTGTCTGTGTTCCGCTACCTGAGCCAGGCCGAGCTCTGTGTTTGCATGGCC
GTCTGCAAGAGCTGGTACAAGTGGGGCTGTGACAAGCGCTTATGGACAAAGATCGACCTG
AGCCGCTGCCGTTCCATCAGCCCTCAGGCTCTCTCAGGCATCATCAAACGCCAGCCTGTT
AACCTGGACCTTTCCTGGACGGCCATCTCAAAGAAGCAGCTCACCTGGCTCATTAACAGA
CTACCAGGACTTAAAGACTTGGTATTATCGGGCTGCTCCTGGATGTGTCTCTCTGCACTG
AGCTCCTCCACCTGTCCACTGCTACGTTCCTTGGACTTGCGCTGGGCTGATGGGGTCAAA
GATGCCCAGATTCGCGAGCTGCTGAGTCCCCCAGGCTCTGACAACCGCTCGCAGCTGCGG
AACCTGCAGTGCCTGCGTCTGTGTGGGCTGGAGATCAGCGAGGCAACGCTGCGGCTCATC
ATCCGACACATGCCACTCCTGACGCGCCTGGAGCTCTCCCACAGCCCC---GTCACCGAC
CAGGCCCTCAACCTGCTCACCGCAGTTGGCTCGTCCACCCGCAACACGCTCACACACCTT
AACCTCGCCGGATGCAGTAAGTTATCAGATCGCTGTCTGGCGTACCTGAAGCGTCTGTCG
TGTTTGCGACTGCTGGACCTCCGCAGCTGCAAGGGAGTGTCGCGTCAGGCCTGTGAGACC
TTTATCTCCGAACTGTCTGTCAACGCGCTCTACTGCCTATCAGATGACAAGCTCATCCAG
AGGATATCGTGA
>Corydoras_julii_viscera_mixture_8|015203|scaffold25041|m.21020
ATGGA-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------CAAGGAGGACAGTGAGGAAAAAGCTG-
---------------------AGCGACGGGAGGGAGGATTG-------------------
------------------------------------------------------------
---GGCGGAAAAGAGAACCGTCCACAGAGGTACG------AAGGAAGGT-----------
-----T-----------GAATGGAGACGAGAGTGGAGACGTCCAAGCAAA----------
-----------TGGAGCACAGGAA--CGA-GAGCGGGAGGAAGGTGGAGAACAGACTAGC
TCGGA---------------------CACTTCCACAGTGCTGCATGATGAGGTCAGAGGT
C-------ACAGACCACAGGTGACCGTGACTTTACAACCG---AGTCGAGGACGGCGGGA
CCCTAGTACCATTGTACCCAAGCTCGAGGCTAATGTGTCGTCATT---------------
---------------AAAAGACGTCAAAGACAAATCTCTACTCCGGCCCCCGATCCGAAA
TGACGGCCGCCGTCCAGATAAAATGC------------------------------GCTC
GCTCGTTCACGCCGGTGTCCCGCACCTTCACGCATCTCCCGCTCTGACCAGGAGCA--CT
GCCAAACATGCCCACATGGGCAGGACATTAAGATGCAATTCCAGAGAGTCTTACCATGAC
GCAGCACGCAGCAAAAATGGGAAGGTTGTTCGATCGGAAAAA----------GCAAAGCC
CTCTGCCAC--------TTTCTCCAGTCCTGCATCCCGAA---------GTTCCCCTGAA
CAGAATGGC---------------------------GCCAGCGATCCTGGCTGGGGCAGG
CTGGTATGGGTGTCTGTCTTCCGTTACCTAACCCGAACCGAGCTGTGCGTCTGCATGGCC
GTCTGCAAAAGCTGGTACAAGTGGGGCTGTGACAAGCGCCTGTGGACGCACATCAATTTG
AGCCGCTGCCAGTCCATCAGTCCACTGGCCCTGTCGGGCATCATCAAGCGCCAACCTGTC
AATCTGGATGTGTCCTGGGCCAACATAACAAAGAAACAGCTTACTTGGCTCATCAACCGA
TTACCAGGGCTGAGAGATCTGGTGTTATCAGGGTGTAGCTGGGCGTTAGTCTCTGCTTTG
AGCTCGCCTAGCTGTCCTTTACTACGCACATTGGATCTGCGCTGGGCTGTCGGTGTTGCA
GATGGACAAATCAGAGAGTTGCTTACCCCACCAGGGAGTAATAACCGGTCCCAGCTGAGA
AATCTGCAGTGTCTGAAGCTGTGTGGTTTGGAGGTGACTGAGGCAACTCTACGGCTGATA
ATCAGACACATGCCTCAGCTGACGAGGCTGGAGCTTTCACGCTGCCCT---TTGACGGAC
AACGCTCTTAATCTTCTCACCGCCGTGGGCTCGTCCACACGAAACACACTGACACACCTC
AACTTAGCAGGTTGCAGCCGGTTAACAGACAGCTGTCTGAGTTACCTGCAGCGTTTGTCC
TGTCTGTCTGTACTGGACCTACAGGACTGTAGAGGGATCTCCCGAAAGGCCTGCGAGAAC
TTCATTTCTCAGCTGTCCGTCAACGCTCTTTACTGCCTATCGGATGATAAACTCATACAG
AGGATATCCTAG
>Distichodus_sexfasciatus_gill_4|008732|scaffold12586|m.13520
ATGA--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------TCAGGGCTGGA
CTCAGCAGGGGCGGCTCCCGAGGCAGAGCGGCTTCGTCT---------------------
----TCGTCTTCGTCGCTGCCGTCCTTC--------------------------------
------------CGGGGAAGAGGAGTGCGCCTCCGAGGCGGAGGGAGGGGCGGA------
----------------------ACGCTGAGAGGAAGGACGGAAA----------------
-------GGGACGAAGAGAGGGACGCCACAGAGGAGGAGAGGAGAGAGAACGGT---CGG
GGAGGCGGCAAAGAAAACCGACCCCAGAGACGAG------GAGGCAGGCCCAAGACGACG
------------------GAAACGGAGGAGAACGGGGACGGACAGCAGAA----------
-----------CGGCGAGCAAGAC--CAA-GAGCAGGACGAGGACGGAGAGCAGACGCGC
TCGGC---------------------CTCTCCCGTCGCTCTCAGCGACGAGGCCAGGGAG
C-------AGAGGTCGTGTGTCACCGTCACCCTGCAGCCG---TCGAGAGGACGCCGGGA
CCCCAGCACCATCGTGCCCAAGTTAGAGGCCAACGTTTCGACCCG------------AAG
CCTTCCCCAAAACCACAGCGAAGTCCAGGGCAAGTCGCTACTCCGCCCTCCGCTCAGAAA
CGGGGCGCGGCGCTCGGATAAAGCGCCCCACCACCCTCACGCCCAGCACCCGCCCGGCGC
CCACCCTTACACCGACAAGCCGCACTTCCAC---TCCCCGACCCTGACCAGAAGCA--CT
TCCAAACAAGCCC---------------TGAGATGCAACTCCAGAGAGTCTCAACACCAA
CACCACAGAGACAGGAGCGGGAAGAAGGCACGAGCTGACAGG----------GGCAAGCT
GCCAGCCCCCTC-----GCTCCTCACCCCCGCCGCTCGCACATC------GCCCCCCCGG
CAGAATGGG---------------------------GGGAACGAACCCGGGTGGGAGAGG
CTGGTGTGGGTATCCGTCTTCTGCTACCTGACCCGGACTGAGCTGTGCGTCTGCATGGCC
GTGTGCAAGAACTGGTACAAATGGGCGTGTGACAAGCGACTGTGGACGCGAATTAGTTTG
AGCCGCTGCCAGTCCATCAGTCCACAAGGTCTCTCTGGGATCATCAAAAGGCAGCCGGTC
ACACTGGATCTCTCCTGGGCGAATATTTCCAAAAAACAGCTCACCTGGCTGGTTAACCGA
TTGCCAGGGTTGAAAGATCTGGTTTTGTCAGGGTGTAGCTGGGCTACCATATCTGCTCTC
AGCTCTCCTAGCTGTCCTTTACTACGCTCGTTAGACCTGCGATGGGCAGACAGTGTCAAG
GATCCTCAAATACGAGAGCTGCTCTCCCCACAAGGCAGTAACAACCACTCCCAGCTGCGG
AACATGCAGTGCTTGAGGTTGTGTGGTCTGGAGGTGACGGAGGCCACACTGAGGCTGATC
ATCAGACACATGCCGCAGCTGACCAGGCTGGAGCTCTCGCACTGCCCT---CTGACCGAC
AACGCACTCAACCTCCTCACCGCTGTGGGCTCGTCCACACGCAACACACTCGCACACCTC
AACCTGGCAGGTTGCAGCCGTCTGACGGATAACTGTCTGGCATACCTGCAGCGTTTGTCC
TGTCTGTCAGTTCTGGACCTGCGCGGCTGCAAAGGCGTCTCGCGCCAGGCCTGCGAGAGG
TTCATCTCCGAGCTTTCCGTCAACGCGCTCTACTGCCTATCGGATGACAAGCTCATCCAG
CGGATATCCTAG
>Gasteropelecus_sp._gill_3|019302|scaffold30863|m.32990
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------AGG
CTGGTGTGGGTGTCCGTTTTTCGCTATCTGACTCGAGCAGAGTTGTGCATCAGCATGGCT
GTTTGCAAAAACTGGTACAAATGGGGGTGTGATAAGCGATTGTGGACGCAGATTAGTTTA
AGTCGCTGCCAGTCCATCAGTCCACAGGCCCTCTCCAGCATCATCAAACGCCAGCCGGTC
ACACTGGATCTTTCTTGGGCTAGCATATCCAAGAAACAACTTGCATGGCTCATCAACCGG
CTACCAGGGCTGAAAGATTTGGTTTTGTCGGGGTGCAGCTGGACAACAATCTCTGCTCTG
AGCTCTCTTAGCTGTCCATTGTTGCGCTCATTAGACCTGCGTTGGGCAGACGGTGTCAAA
GAAGCTCAGATCCGAGAGCTCCTCAGCCCACCAGGGAGCAATAACCGATCCCAGCTGAGG
AACATGCAGTGTTTAAGGCTGTGTGGTCTGGATGTGACCGAGGCGACTCTGAGGCTGATC
ATCAGGCACATGCCCCAGCTGACAAGACTGGAGCTCTCGCACTGCCCT---CTCACTGAC
AACGCTCTCAACCTCCTTACTGCTGTGGGCTCCTCCACACGCAACACACTGGCACACCTC
AACCTAGCAGGCTGTAGTTGCTTGACGGACCACTGTCTGGCATACCTGCAGCGTCTGTCC
TGTCTCTCGGTGCTGGACCTGCGCGGCTGTAAGGGAGTCTCCCGGCAGGCCTGCGAGAAA
TTCATCTCCGAACTGTCAGTCACTGCTCTTTACTGCCTGTCAGACAACAAACTTATCCAG
AGGATATCTTAA
>Lepidogalaxias_salamandroides_Head_2|021036|scaffold19832|m.27446
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------GAGGTGGAGGAGGAGGAGGAGGAG--
---------------------AGCGCTCAGCGAGGTGGCCG-------------------
------------------------------------------------------------
--ACCGGACAAAGAAAACCGACCACGGAGACGAG------GAGGAAGA------------
------------------ACCAAAGAGGAGGATGAAGAGG---------A----------
-----------TGAAGAGGAGGAG------GATGAAGAGGAGGAAGAAGAGAGGATGAGC
CAGGGGGAGG------------------CTCCTGTGCTGCTG-GTGTCTGACCTAAGCAC
CGACCTTTTGACCTCTAACCAGACGGTGACTCTTCAGCCC---TCTCGGGCTAGAGGTGA
CCCTGGAGCCATTGTTCCCAAATTGG------CCATAGCACCCCGCCCTCTACCCCGCCC
CACCCCGCCCACCCAGAGATACATCCAGCGTAAGTCTCTGCTCCGCCCTCCTCTTCGGAA
CCACGCCCAGCCT----------------------------------------G-GCCCC
GCCCCTTCAACCCGTCAACCT--------------------------------------C
GCGAAAGACTACC---------------TGGG----------------------------
-----TCTGGACGGGGAAGGGCGGGGAAACCA--------------------GCCACACA
CACAtCCTCCTC-----TTCCTCCTCCTCTTCCTCCCCCTCGACACGCCTGGCTGCCCTG
CGCAATGGACGGAGCGATAGGGAAGTCTGGAGAGGAGGCAGTGAGCCGGGATTCGAGAGG
GAGGTGTGGGTGTCTGTGTTCCGCTACCTGAGCAGGTCTGAGCTGTGTGTCTGCATGGCC
GTCTGCAAGAACTGGTATAAATGGAGCTGTGATAAGCGGTTGTGGATGAAGATAGATCTG
AGTAAAAGTCGGTCCATGAGCACGCAGGCGTTTTCAGGCATCATCAAACGCCAGCCAGTC
TCACTGGATCTGTCCTGGACCACCATCTCCAAAAAACAACTTACCTGGCTCATCAATCGC
TTGCCAGGGCTGAAGGATCTGATGTTGTCAGGCTGCTCCTGGTCCTCCATCTCTGCTCTG
AGTTCTCCCTCCTGCCCTCTGTTGCGCTCCCTGGACCTGCGCTGGAGTGAAGGAGTCCGA
GACACTCAGATCAGAGACTTGCTCAACCCTCCAGGCTGTGATAACAGAAGTCAGCTAAAG
AACATGCAGTGTTTCCGATTGGCCGGGCTGGAGATCAGTGACAGCACCTTGAGACTGGTG
ATCAGACACATGCCTCTTCTGACCCGACTTGACCTTTCACACTGCCGAGGGGTCACCGAC
CAGTCCGTCAACCTGCTGACCGCTGTGGGCTCTTCTACACGCAACACACTCACAGACCTC
AACCTAGCAGGCTGTGTTAAGCTGACGGACGTGTGTGTGCAGTATCTGCGACGACTCTCC
TGCCTCTCCTTGCTGGACCTGCGGGGGTGTCGGGGTGTGTCCCGCGCTGCATGTGAAGCC
TTCATCTCCGAGCTGTCCGTTAACACTCTCTACTGCCTATCAGAGGACAAGCTCATCCAA
AGGATATCCTAA
>Melanotaenia_praecox_viscera_mixture_8|007627|scaffold11659|m.10591
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------AAGATAAATAAAGATTTGCCTAGCTGC
TGGGAATGTCCTAAATGTTACCAAGGCAAAGGCTCAGCATCAGAGTCTTCTAGCGATGAG
GAAAGTGAAGAG-----------------TCAGAGGGCTCAA----CTTCCATGTCACAG
CCCAAGCATGCATACCAAGAAGGT------------GAAGGAGCAAGACGAGGGAGACGC
AGCCGGCCTCCGGGGCGACCAACAGCACCACCTCCTTCGCAGAAGCTGCTACT---GCAG
CATCAACAAAATCGCAAAAGAGCAAGTGCACTCGAGCTCAGACTTAAGAAAAGGATAAAA
CTTGAGCGGAGCAAACTCTTGACAAAACAGTCTTCTCTAGATCGCTC-------------
--TTCCAGGGTGCTTACCCGTCTGCGCTCTCC--AGCAAGCAGACTACTTCAGGGCCGA-
---GGCCGGGGCTCCACATGGGCAAGCAGCTCACCACGC-AACAGTATTCCAGGAGAGAC
TGGGTCCTTCGAGCAGCAGCAGTGTTCTC--ATGGTCTGGTACTTGAGCCCAAAGGGGAG
CCCCGCAGAGGAAGAGGAAGAGGTGTGAGGCTGCGAGGAGGAGGAGCAGGACGAGGCATC
AGAGGTGGAAGAAGCC---GTGCAGAGTTGGAGGACGAGAGCGAGGACAGCAGCACCGGC
ACCAGCACCAACAGCAGTAGCAGTGATGATGAAGAAGAGAGCGATCTGAACAGTGGGAGG
GGTGGAGATAAAGAAAACCAGCCACAGTCAAGGC---AAGGAGGGCAGG--CAGCTAAAG
AACGA-------------GATGAAGATGGGAGTGATGTGGGTAATCAAAA----------
-----------TGGCGGGGACGAGGACGATGATGATGATGAGGAGATGGAGCAAGACATT
TCGAAAAGGGATAAAG--------------------------------------------
--------ATGGCTCATATCTTAAAGTGACTCTCCAAAGGCCAACTAGAGCTAAACAAGA
CCCATCAGCCATTGTCCCCAAATTAGAGG---CTATTGCCCCTCA------------AAC
TGCCACTAACTCC---GTACATACTCAGGGCAGAACTCTGATCAGACCCCCAATTAGGAA
TTGTGGCCCATGTCCTGATCAACACGC------------AAACAGGCACACAC---CACC
ACACACTGGGAGTGAACACACAGACTGTCACAC--TTCCCACCCAGAGAGACTGGA---C
Tcaaaa------------------------------------------------------
-------agaacgaaacttaGCAGACCAGCTAAACTGAGCAA---------TGGTGCTTC
CTCTTCTTCATCT-GAACTTCACCATCTCCGCGTACCTCT----------CTCCTCCCTT
CAGGAAGGAGGTGGTGAGGCAGATAAGGAGAGCATTGCAAGCAGCCCAAGCTGTGAGAGG
GAGGTGTGGGTGTCTGTCTTTCGCTATTTAAGTCGAGCAGATCTTTGTGTCTGCATGGCT
GTCTGCAAGAACTGGTACAAATGGTGTTTAGACAAGCGGCTTTGGGCTCGGATTGACCTG
AGCATCAAGCGCACAGTTACTCCTCAGGCCCTCACAGGCATCATAAAGAGACAGCCTGTC
ACACTCGACCTCTCCTGGACCAATATCTCAAAAAAACAGCTCAACTGGCTCGTTGGCCGA
CTACCTGGGTTGAAGGATCTGATGCTGGCAGGTTGTTCCTGGTCATCTATTTCAGCTCTC
TGCTCCTCTGGTTGCCCTCTCCTCCGCTCTCTGGACCTTCGGTATGCAGATGGTGTGAAA
GACTCGCAGATCAGGGATCTAGTCACACCTCCGGGCTGTGACAATCGCAGCCAGCTGCGT
AGTATGCAGTGTTTGCGGCTCGCAGGCCTGGACATCAGTGACTCGACTCTTCGTTTGGTG
ATTCGCCACATGCCCCATCTAACAAAACTGGATCTCTCCCACTGCAATGGCCTCACTGAC
CACTCCATCAACCTGCTGACTGCAGTAGGCTCATCCACCCGAAACACATTGATAGAGCTC
AACCTGGGAGGCTGCAGTAAACTGACAGATGTGTGTTTGAAGTATCTCCGCCGGCTTTCG
TGTATCTCACTGCTCGACCTGCGAGGCTGCAAAGGTGTTTCCAGAAAGGCCTGTGAGGCC
TTCATCTCTGAATTATCAGTCAATACACTCTACTGCCTATCAGATGAAAAACTGATCCAG
CGGATATCATAG
>Sargocentron_rubrum_gill_6|018091|scaffold26835|m.35245
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------ATGGAGGAGGAGAGCGAGGACAACAGCACCAGC
AGCACCAGCAGCAGCAGCGACGACGAGGAGGAAGAGGAGAGGAGGGAGAACGGAACGAGG
GGAGGGGACAAAGAGAACCAACCGCAGGCGAGGA---GAGGAGGAAGAA--CAGCCAAAG
AAAGA-------------GAAGAGGAAGCGAACGAGGTGGCCAACCAAAA----------
-----------CGGCACAGAGGAG------GATGAAGAGGAAGAGATGGAACAGGACAGT
CAGGCAGGGGACAGAGACAGCCTGGTGA--------------------------------
--------AAGGCTCGTATCTGAAAGTGACACTCCAGAAGCCATCCAGGGCCAAGCGGGA
CCCATCCGCCATCGTCCCCAAACTAGAAGCAGCCATTGCCCCCCG------------AAC
TGCTACTTCCACG---ATGCACAGCCAGTCCAGGGCACTCGCCCGCCCCCCCATCAGAAA
CCACAGCCCCCGCCCCGACCAACACCCCTCGCACTC---CGACAGACACACAC---CGCC
ACACACCCGCAGCAGACACACACACTCTCACAG--CTCCCACCCAGAAAGGCTGGCGGTC
GCAAAA------------------------------------------------------
-------AGAGCAAGGTCGGGCAGGCCAGCCAAAATGAACAAT------GGTGCGTCGTC
CTCTTCGTCCTCT-CAGGTTCCCCCGCTCCGCATCCCCCT----------GTCAGCCCTG
CAGGAAGGAGGCAGTGAAGCGGACAGGGAGAATGGAGGGAGCGGGCCGGGCTGTGAGAGG
GAGGTGTGGGTGTCTGTCTTCCGGTATTTGAGTCGAGCAGATCTCTGCGTCTGCATGGCG
GTCTGCAAGAACTGGTACAAATGGTGCTTAGACAAACGGCTGTGGGCGCGAATTGACTTG
AGCATCAAGCGTACCATCACTCCCCAGGCACTGACAGGCATCATAAAACGACAGCCGGTC
ACACTGGATCTCTCCTGGACCAACATCTCCAAAAAACAGCTCAGCTGGCTTATCGACCGC
CTGCCTGGGCTTAAAGATCTGATGCTGTCAGGTTGTTCCTGGTATTCCATTTCGGCTCTC
AGCTCCCCCAGTTGCCCTCTCCTCCGCTCTCTGGACCTGCGGTTTTCTGATGGGGTCAGA
GACTCTCAGATCAGGGACCTGGTCACCCCTCCAGGCTGTGACAACCGCAGCCAGTTGCGA
ACCATGCATTGCTTCCGCCTGGCAGGCCTGGACATCACCGACTCCACCCTGTACCTGGTG
ATCCGCCACATGCCCCAGCTGACGCGACTGGACCTTTCCCACTGCAACAACCTCACTGAC
CAGTCAATCAACCTGCTGACTGCCGTGGGCTCGTCCACCCGCAACACGCTCACAGAACTC
AACCTGGGAGGCTGCAGTAAGCTGACAGACGCTTGTCTGAAGTATCTGCGCCGCCTCTCT
TGCATCTCCCTGCTCGACCTGCGAGGCTGCAAAGGTGTCTCCCGCAAGGCCTGCGAGTCC
TTCATCTCCGAGCTGTCCGTCAACACCCTCTACTGCCTATCGGATGAAAAGCTGATCCAG
AGGATATCCTAA
>Synodus_sp._gill_5|020615|scaffold26057|m.36899
T-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-GCAAGCACTGCGCGGCCTGCCGCAGGAAGGAGTGTGGCGACTGCCAGTACTGCCACGAC
ATGAGGAAGTTCGGCGGGCCCGGACGCATGAAGAAGAGCTGCGTCATGAGGCAGTGCCTC
GCTCCGGCCCTGCCGAACACCGCACGCTGTGCCATATGCCGAGAAGGGGAACCC------
GAGGACTCCAACCCCGCTACGCACACGCTCATGGAGTGTTCCAACTGTGCAGAGATCGCC
CATCCTGGATGCATTAAGGAGCCTGGTGAAGGGAAGATCAACCCCGACCTGCCCAGCTGC
TGGGAGTGCCCCAAGTGCTGCCAGGCCAAGGGCTCGGCCTCCGAGTCTTCCAGCGATGAG
GGCAGCATGGCG-----------------TCCGAGGGCTCGG----TGTCCTCGCAGCCC
TCCAAGCGT---TACCGGGAGGGTATCGGCGTTGGCGAAGGGCTGAAGAGAGGGAGACGC
GGCAGACCTCCGTCCAGGCGCACAGCGCCCCCTCCCTCCCAGAGACTGTTACT---GCAG
CATCAGCAGAGCCGCAAGAGGGCGGGCGCTCTGGAGCTCCAGCTGAAGAAGAGGATAAAG
CTGGAGCGCAGCAAAATCTTGGCGAAGCATGCGTCGCTAGACCGATCCCCTCGGCTGTTG
GGCTCCAAGGCGCTGTCCCGCTTCCGCAGCTC--CACCGGCAGACTGTCCCAGGGCCGA-
---GGCCGGGGGGCATCCTGGAGCAGCC--------------------------------
----CCCCTCCTGCTGCCCCCGCCCTCCCCACCAGTGTGGCACGGGAGGCCGGGGCCGAG
CTGCGGAGAGGCAGGGGGAGAGGGGTCCGGCTCCGTGGGGGAGGGGCGGGGAGAGGGGTG
CCAGGGGGGAGGAGCCACGGAGACGCGGAGGAAGACGACAGCGAGGACGACAGCAGCAGC
AGCAGCAGCAGTAGCAGCAGCGAGGAGGACGAAGAGGGAAGGAGGGAGAACGGCGTCCGA
GGAGGAGATAAGGAGAACCAGCCTGAGGAGCGCC---AGGTGGGGAGGG--CAGCCAAAG
ACAGGAGGGGCGG----CGAGGAGGAGGGGGGCGCGGAGGCCAGCCAAAA----------
-----------CGGGGCCGAGGAC------GACGAAGAGGAAGAGATGGAGCAGGACGGG
CAGGGGGGGGACGG------CCCGGGGA--------------------------------
--------AAGGCCCCCAGCTCACGGTGACACTCCAGCGCCCCCCCAAGGCCAAACGCGA
CCCCTCGGCCATCGTGCCCCGACTGGAGGCAGCCATCGGGCCCCG------------GCC
TGCCCCCCCCAGC---AGGCACAGCCAGACCAAGGCGCTCCTTCGGCCCCCCATCAAAAA
CCACAGCCCGCACACGGACCAGCATCCCGCACGCCC---CGACCGACACGGCC---CTGC
GCACCCGGGCAGCGGAAACACGTGCCcCCGCTC--CCAGCCGCAGGACCGGATGGATGCC
GTCAAA------------------------------------------------------
-------CGGGCGCGGCTAGGCCGGCCCGACAAGCTGAATAACGGCGGTGCTGCCTCCTC
TTCCTCCACCTCT-CGGATTCCTCCTCTTCGCATCCCGCT----------GTCGGCCCTG
CAGGAGGGCGGCGGCGAGGGAGACAGGGAGAACGGAGGCAGCGAGCCGGGCTGCGAGAGG
GAGGTGTGGGTGTCCGTTTTCCGCTACCTGAGTCGCTCGGATCTCTGCGTCTGCATGGCC
GTCTGCAAGAGCTGGTACAAATGGTGCTTAGACAAGCGGTTGTGGTCTCGGATCGACCTG
AGCATCAAGCGTACTATCACACCACAAGCCTTGACGGGGATCGTCAAACGACAGCCCGTC
ACACTCGACCTCTCCTGGACAAACATCTCCAAGAAACAGCTCAGCTGGCTGGTCAACCGC
CTGCCAGGCCTGAAGGATCTGATGCTGTCCGGTTGTTCCTGGTCTTCCATTTCATCTCTC
TGCTCCCCAAGCTGCCCCCTCCTCCGCTCGCTGGACCTGCGATGGGCGGACGGAGTCCGA
GACGCACAGGTCAGGGACCTGATCACACCTCCAGGTTGTGATAACCGCAGCCAGCTGCGC
ACCATGCACTGTTTCCGGCTGGCAGGCCTGGACATCGGGGACTCCACCCTGCGCCTGGTG
ATCCGCCACATGCCCCAGCTTACGGTGCTGGACCTGTCCCACTGCAATAACCTGACGGAC
AACTCCATCAACCTGCTCACCGCCGTGGGCTCGTCCACACGCAACACTCTCACCGAGCTC
AACCTGGGAGGCTGTGGCAGACTGACAGACAACTGTCTGAAGTACCTGCGGCGTCTCTCC
TGCCTCTCCCTCCTGGACCTGCGGGGCTGCAAGGGGGTCTCGCGCAAGTCCTGCGAGGCC
TTCATCTCAGAGCTGTCTGTGAACGCGCTCTACTGCCTATCCGAGGACAATCTCATCCAG
AGGATATCTTAG
