>Amblygaster_clupeoides|023224|TR40444|c0_g1_i1|m.62463
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------AACGACCCCGGAGGCGGATCTTTCAGGGACGATGACGACATC
AACGACGTGGCCTCCATGGCCGGGGTGAACCTAAACGAGGAGAGCGCCCGTATCCTAGCA
ACGAACTCGGACCTGGTGGGCACGCAGATTCGCTCGTGTAAGGACGAGGCCTTCCTGCCC
ACAGGCCTGCTGCACAGACGCATTTTAGACACGGCGAAGCGGTTTGGGGTGACGGAAGTG
CCCCTGGAAGCGGTCAACTTTATCGCCCACGCCACACAGTCACGCCTTCGAACCGTGCTA
GAGAAGGTGTCTGCCATTGCCCAACACCGCATGGACACTTGCAAAGATGACGAGTGGTAT
GAGCAGTCGACAGACGTACGGTCACAGCTGAAGTTCTTTGAGCAGCTGGAGAGGATTGAG
AAACAGAGAAAGGACGAGCAGGAGAGGGAGATTCTCCTCAAAGCAGCCAAAAGTCGCTCG
AGGCAAGAGGACCCAGAGCAGGCTCGGCTGAAGCAGAAAGCTAAGGAGATGCAGCAACAG
GAGCTGGCCCAGATGCGTCAGCGGGACGCCAACCTGACTGCGTTGGCCGCCATCGGCCCC
CGCAAGAAGCGCAAGGTGGACTCACCAGGGGCGTCGTCATCAGGGACCGAGGTGTCGGGA
AGTTCTGTGGGTTCGCCGGCTGCCTCGTCGTCGGCCTCC---ACGTCGTCACGGCAATAC
GCCCGGCAGCGGATCACCCGTGTCAACCTCAGGGACTTCATCTTCTACATGGAACAGGAG
CGAGAGATGGCACGCTCCCTCCTGCTGTACAGAGCGCTGCTCAAGTAG
>Distichodus_sexfasciatus_gill_4|026071|scaffold5898|m.6287
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------ATT
AACGACGTGGCGTCGATGGCCGGAGTTAACCTGAACGAGGAGAGCGCTCGCATCTTAGCC
ACAAACTCGGAACTGGTGGGAACGCAGATCCGGTCCTGTAAAGATGAAGCGTTCCTCCCC
ACGGGCCTGCTGCACCGACGCATCTTGGAGACTGCTAAGAAGTTCGGCGTGACCGAGGTT
CCTCTGGAAGCGGTCAACTTCATCTCCCACGCCACGCAGTCGCGCTTGAGGACCGTGCTG
GAGAAAATCTCGTCCATCGCTCAGCACCGCATGgattccaacaaGGATGAGGAGCTGTTG
GAGCAGTCGTCGGACGTTCGCGCTCAGCTGAAGTTTTTCGAGCAGCTGGAGCGTCTGGAG
AAGCAGAGGAAGGAGGAGCAGGAGCGAGAGATTCTGCTGAAAGCTGCTAAAAGTCGCTCG
AGGCAGGAGGACCCAGAGCAGGCTCGTTTGAAGCAAAAGGCAAAAGAGATGCAGCAGCAG
GAGCTGGCACAGATGAGGCAGCGGGACGCCAACCTCACGGCTCTGGCAGCCATCGGCCCC
CGGAAAAAGCGCAGAGTGGAC---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------
>Gasteropelecus_sp._gill_3|020926|scaffold32799|m.36006
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---GTTCCTGCCATCCAGACGAGTAAAAGCCCCAATGCACTCCCTGTCCAAATCCCAGGG
ACCCCGAAGAACAAACTCAATGACCCTGGGGGAGGCTCCTTCAGGGATGATGATGACATC
AACGATGTGGCTTCAATGGCCGGGGTCAACCTGAATGAGGAGAGTGCCCGTATCTTAGCA
ACCAATTCGGAACTGGTGGGAACTCAGATCCGATCTTGTAAAGATGAGGCCTTCCTGCCC
ACGGGCCTGCTGCACCGACGAATCCTGGAAACTGCTAAGAAGTTCGGAGTGACTGAGGTG
CCTCTGGAGGCAGTAAACTTCATCTCTCATGCAACGCAGTCGCGGTTACGAACGGTCCTG
GAGAAGGTCACGTCCATCGCCCAGCACAGGATGGATTCCATTAAGGACGAGGAgtggtac
gagCAGTCGTCAGACGTTCGCTCTCAGCTGAAATTCTTTGAGCAGCTGGAACGACTGGAG
AAACAGAGGAAAGATGAGCAGGAGAGGGAGATTCTCCTCAAAGCAGCTAAAAGTCGCTCG
AGGCAGGAGGACCCAGAGCAAGCTCGTTTGAAGCAGAAGGCAAAAGAGATGCAGCAGCAG
GAACTGGCCCAGATGAGGCAGAGAGACGCTAACCTGACGGCTCTGGCCGCCATCGGCCCG
CGGAAAAAGCGTAAGGTGGACTCGCCGGGAGCCACGACGTCGGGCACTGAGGTGTCCGGA
AGTTCTGCCGGATCTCCGGCTTCTTCGTCCACAGTTTCC---ACATCCTCACGCCAGTAC
CCTCGCCAGAGAATCACACGAGTCAACCTCAGGGACTTCATCTTTTACATGGAACAAGAA
CGAGAGACGAACCGATCGCTCTTACTGTACCGAGCTCTGCTGAAGTAG
>Melanotaenia_praecox_viscera_mixture_8|003223|C435482|m.28886
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------GCCCGTATCCTGGCA
ACCAGCTCAGAGCTGGTCGGCACCAAGATTCGGTCCTGTAAAGACGAGTCCTTCCTGCCA
ACGGACCTGCTGCACCGGCGCATCCTGGACACAGCAAAGAAGCTGGGGGTGACGGAGGTT
CCTCTGGACGTGGTGAACATCATCTCCCATGCCACCCAGTCCAGACTTCGCTCTCTGCTG
GAGAAGGTTTCTGTCGTCGCTCAGCACCGCACCGATGGAGGAAAGGATGAAGAGGTCCAG
GAGCAGACGTCGGACGTTCGCTCTCAGCTCCGTTTCTTCGAGCAGCTGGAGAGGATGGAG
AAGCAGAGGAAAGACGAGCAGGAGAGGGAGATGCTGCTGAAGGCCGCAAAGAGTCGAGCG
CGACAAGAAGATCCAGAACAGGCTCGACTCAAACAAAAGGCGAAAGAGATGCAGCAGCAG
GAACTCGCTCAGATGCGACAGCGTGATGCCAACCTCACGGCTCTCGCCGCCATTGGACCA
CGCAAGAAACGGAAGCACGACGCAATGGGCGGAGCCACGGCCGGCAGTGAGGT-------
--GGCTTCAGGCTCCAGCTCTGTTTCCTCTGCAGCC------GTCTCCCCCCGCCAGCAG
CTCCGTCAGCGGATCACTCGGGTCAACCTCAGGGACTTCATC------------------
------------------------------------------------
>Pantodon_buncholzi_mixed|019453|scaffold5253|m.6070
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------ACAGCGAGGAAGTTTGGGGTGACGGAGGTG
GCGGCTGAGGCTGTGAACCTGATCTCCCACGCCACGCAGGCCAGGCTGAGGACGGTGCTG
GAGGGAGTGTCGGCCATTGCTCAGCACCGTATGGACACGTGTAAGGATGATGAGCATTAC
GAGCAGTCGTCGGACGTGCGATCACAGCTGCGCTTCTTTGAGCAGCTGGAGAGGATAGAG
AAACAGAGGAAGGATGAGCAGGAGAGGGAGATCCTACTGAAAGCAGCGAAGAGTCGCTCC
AGGCAGGAGGACCCGGAGCAGGCTCGGCTGAAGCAGAAGGCTAAAGAGATGCAGCAGCag
gagctggCCCAGATGAGGCAGCGGGATGCTAACCTGACAGCGCTAGCAGCTATCGGGCCT
AGGAAGAAACGCAAACTCGACTCACCGGGAGCATCAGCAGCAGGAGCTGAGGTTCCAGGA
GGTTCTACGGGTTCTCCGGCAGGCTCAGCCGCCGCCTCCGCTGCCTCGTCTCGGCAGTAC
GCCCGCCAACGCATCACCCGCGTAAACCTCAGGGACTTCATCTTCTACATGGAGCAGGAA
CGGGAGACGGCGCATTCGCTGCTGCTTTACCGGGCCCTTCTAAAATAG
>Sargocentron_rubrum_gill_6|023206|scaffold6731|m.7685
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------ATCAAGCTGGCGTCCCATAATTCCCCCTCCCCAGACACCTCC
AAGAATGTGAAGGCCCTGGTGCAGGATCTACTCGATGCTAAGATTGAGCCGGAGGAGTTC
ACCACTCGGCTGCAGGCTGAGCTGAAGTCCTCCCCACAGCCCTACCTCATCCCCTTCCTA
AAGAAAAGCCTTCCTGCCCTGCGCCAGTCTCTGCTCAACAACCAGCAGTCTCTCATGACG
CCCAC-CCCCAGCACCTCtactccacccctggg--tgcccccggcgCCGTCACCA---CC
ACCATCAGGCCGCGGC------TGCCCACCAGCACCGCCGTCGGCACCGTCAG------A
CTGAACCCACCCCTCGCAAACACAGCGTCCTTGAATGTGAGGAGACCAGGGGTGCAGACA
GTCCAGACCCGCATGCCCATGGTCATCACTCAGACCGTCAGACCCCAAGGTACACTTGTG
AGGGGACCCACGATtATAGCTGGCAAAAGTCCTGCTGCCCTGGCAGCCCAA------GCC
AATCAGAAG---AAACTGAGTGACCCTGGGGGCGGGACATTCAGAGATGACGACGACATC
AACGATGTGGCGTCCATGGCCGGTGTCAACCTCAACGAGGAGaacgccCGTATCCTAGCA
ACCAGCTCGGAGCTTGTGGGCACCAAGATCCGATCCTGTAAGGACGAAGCATTCCTGCCC
ACCGGCCTGCTCCACCGCCGTATCCTGGACACCGCCAAgaagttggGCGTGACCGAGGTG
CCGGTGGAGGTGGTGAACTACATTTCCCATGCCACCCAGAGCAGGCTCCGCTCCCTGCTG
GAGAAGGTTTCAGCCGTCGCCCAGCACCGCAGCGACGGGGGCAAGGACGAGGAGGTGTA-
------------------------------------------C-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------
>Scleropages_formosus_red_gill|015075|scaffold23248|m.30248
TCACAGCCTACGGTTTCCCTGGACGGCCCGTCGCCATCCCTGCAGAGACTGCCGGGTCAC
ATCATGGTCAGCGTTTCCCACAACGGCACCGGCGGCGCTGCGGTCCCGGGCGACTCCGCT
GCCCCGGCGGCGGTGAACCACAACAAGAGCGCAGAGGTCGGCAGCGCCCCGGCAGAGCCT
CCGCTCCCGGCTACGCAGTCCACGGTGATCATGCCGAGCCAGGCCGGCGCGGGCACGCCG
CTGCCAAGTCCTGTCACCTGTGCTGCCCCCACGGCCAGCGCAGCCCCCGCTCAGCTCCAG
AGCACCGGTGCGCCCGTCTCCAGCAGCTCCCTGCCTCTTGCACCGCCCGTGAAAGCGACT
GCGAGTGTGAGCGCGACCTCGCAGCCTCCGGCCAGCACCGTGGTGAGCGCGCTGAGACCA
CCCGGGGTGCCGGCACCCTCTGCCACGCAGCCCCAGCAGATCAGGCCCACGACGGCGGCG
GCCGCCCAGAGGATAGTGGCGCCGCAGCTGATCGTGAGGCCGCCGCAGCAGCAGACCACG
ATCCAGCTTCCTCCGGGCTTCACCATCCCGCCGGGCATGGTGCTGGTCCGCACCGAAATG
GGCCAGCTGGTCATGGTTCCTCAGCAGGCTCTGGctcaggcccaggcccaggctcaggcc
caggcccaggcccagAACAGCATCTCCCCACGACCTGCTGCCCCCACCACTGCGACCACC
TTCCGGGTGACTACTACACAGTCTCCTGTGACGTCCCAGGCCATCCGCCCGTGTCCTCCT
GTCCAGGCCAAGGTGGTTCCTTCACCCTCTCCCGCTGGGAGCACCGCCCTCCAGAAGGCA
GCTGTGATGGGGGCCCCGGCGACAGCACCGCAGCAGCCGACCACAGTGATCGCAGCAGGA
CAGAGCGGCCCCCAGGCCACCGCAGCCTCGCAGAGCACCGCCTCAGCCATCCCCGCCACC
CCTGCCCCGGCTGTCTCCGTCATCTCACAGGAGATGCAGGAGAATGTGAAGAAGTGCAAG
AACTTCCTGGCCACTCTGATCAAGCTGGCGTCACACAACTCACCGTCTCCGGAGACGTCC
CGCAACGTGAAGGCGCTTGTGCAGGACCTCTTGGATGCAAAGATCGAGCCCGAGGAGTTC
ACCAGTCGACTGCAGACGGAGCTCAAGTCCTCCCCTCAGCCTTACCTGGTCCCCTTCCTT
AAGAAAAGCCTTCCTGCTCTGCGGCTCTCGCTCCTCAACAGCCAGCAGTCGCTGACGCAA
CCCCCAGCCCAGCAGGCCAAGCCTTCCACGGGGCCTGTGCCCACCATCGTGGCTGGACCC
ACAGTGAGAGTGCGCCACCCTGTGCCCAACAGCGTGGCTGGGGGTGTACCTAGTGTGCTG
CCCAGTGCGGCTCATGGACATACTACAACCCTGGGTGTGAAGAGGCCAGGTGTTCAAGCA
ACTCCAGTGCGGATGCCTGTGGTTATCACGCAGACAGTGCGACCTCAAGGCACACTTGGG
AAGGGACCAGCAATACAGGCGAGCAAAAGTCCCGTGGGCCCAGCTGCCCCAGGCGCTGCC
AATCAGAAAAACAAGCTCAACGACCCCGGGGGTGGTTCTTTCAGGGATGACGACGATATC
AACGACGTGGCCTCTATGGCTGGTGTGAACCTCAACGAGGAGAGCGCCCGCATCCTGGCC
ACCAACTCGGAACTGGTGGGCACACAGATCCGCTCCTGCAAGGATGAGGCCTTCCTGCCC
ACGAGCCTGCTGCACCGGCGCATCATGGAGACAGCTAAGAAGTTCGGACTCACAGATGTG
CCTGCAGAGACGGTCGGCTTAATCTCCCACGCCACGCAGGCTAGGCTGCGCAGCATGCTG
GAGAAGGTGACTGTCATCGCACAACACAGGATGGAGACGTGCAAGGATGACGAGCACTAT
GAGCAGTCGTCGGATGTGCGCTCCCAGCTGCGGTTCTTCGAACAGCTGGAAAGGCTGGAG
AAGCAGAGAAAAGACGAGCAGGAGAGAGAGATTCTGCTGAAGGCCGCTAAAAGCCGCTCG
AGGCAAGAGGACCCGGAACAAGCCCGCCTCAAACAGAAAGCTAAGGAGATGCAGCAGCAG
GAACTTGCACAGATGAGGCAGCGGGATGCCAATCAAACTGCACTGGCGGCGATCGGACCT
CGGAAGAAGCGCAAGCTGGACACGTCCGGGGCCACAGCGCCAGGGGGTGAGGTATTAGGC
AGTTCAGTGGGCTCACCGGCCGGGACCTCCTCGATCGGC---GCCTCCTCCCGCCAGTAC
GCAAGGCAGCGCATCACCCGCGTCAACCTCAGGGACTTGATCTTCTACATGGAGCAGGAG
CGGGAGACGGCCCGCTCTCTACTGCTCTACCGCGCCCTGCTCAAGTAG
>Synodus_sp._gill_5|019662|scaffold25160|m.34914
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------TTCAGAGATGATGATGACATC
AATGACGTGGCCTCCATGGCTGGGGTCAACCTCAATGAGGAGAACGCGCGTATCCTGGCA
ACCAGCTCCGAGCTCGTAGGCACGGAAATCCGCTCCTGTAAGGATGAGGCATTCTTGCCC
ACTGGTCTGCTGCATCGCCGTATCTTGGAAATTTCAAAGAAGTTTGGGGTGAATGAGGTG
CCAATGGATGTGGTGACCTACATGTCCCATGCGACTCAGAGCAGACTGCGCATGCTACTG
GAGAAGATGTCAGCTGTGGCCCAACATCGGGCTGAGGGAGGCAAAGACGAGGAGTGGTAC
GAGCAGTCCTCGGACGTGCGGGCCCAGCTGCGCTTCTTTGAACAGCTGGAGAGGATGGAG
AAGCAGAGGAAAGACGAGCAGGAGAGGGAGATCCTGCTCAAGGTTGCCAAGAGTCGGGCC
AGGCAAGAAGATCCCGAACAAGCTCGACTGAAGCAGAAAGCAAAAGAGATGCAGCAGCAG
GAGCAGGCTCAGATCCGCCAGCGCGATGCCAACCTCACCGCCCTGGCCGCCATCGGGCCA
CGCAAGAAGCGCAAGCTGGACTCCCCGGGTGcggCCGCAGCAGCAGCAGAGGT-------
--TGCTTCAGGCTCAGGGGCTGGCTCGTCCACAGCT------GCCTCCTCTCGCCAGCAG
CTTCGTCAGCGGATCACGCGAGTTAACCTCAGGGACTTTATCTTCTGTCTGGAGCAGGAG
AGGACAACATCCAGGTCCCTACTGCTCTACAAGGCACTACTGAAATAA
