>Corydoras_julii_viscera_mixture_8|004842|C1245684|m.30406
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------ATGA
AACATT-----GTATTCAACAACCAGCTGTCATGGAAACCAAGGCGAATGGTTCGATGGA
AAGCAAAAGTACGGTGGAGAACGGACAGCTTTCCAATCCTGCACACTGGGCTGTAGCCGA
TGTAGTTAATTATTTTAAAGCCACTGGATTTGAAGAGCAAGCCATCGCTTTCCAAGATCA
GGAAATTGATGGTAAATCTCTTTTGCTTATGACTCGTAACGATGTTCTGACTGGACTTTC
AATAAAACTGGGGCCTGCACTAAAGATCTATGAGTACCATGTGAAGCCGCTCCAGACTCA
ACACCAAAAAAGCGATGCCTCG------TAG
>Lepidogalaxias_salamandroides_Head_2|027955|scaffold7660|m.9993
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------ATGCTTCT
GATGGAGCAATGCCATGATGCTGTAAAATTGAAGAAATCAA------------AGGAAAA
ACTGCTTTCGGACACAAAAGAATCTGCTGGGATGGACAATAAGGCCAACGGTTCAGTGGA
CAACAAAAGTCCCGTGGAGAACGGTCAGCATCCCGACCCCGCCAGCTGGGCTGTGGCGGA
CGTAGTGAACTACTTCAAAGCGACAGGCTTTGAGGAGCAGGCCAACGCTTTCCAGGAGCA
GGAAATTGATGGCAAATCTCTTCTCTTAATGACACGCAACGACGTCCTGACCGGACTGTC
AATAAAACTGGGCCCCGCCCTGAAGATCTACGAGTaTCACGTAAAACCCCTTCAGACCCA
GCACCTGAAGAGCAGCGTGTCA------TAG
>Melanotaenia_praecox_viscera_mixture_8|010600|scaffold15597|m.15181
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------ATGAAAA
ATTACT-----TCAACGTTACAGAATCCGGCatggaagacaaggcaaatggctcATTGGA
CACCAAAAGCCCAGTGGAGAACGGCCAGCTGCCAGACCCTTCCAACTGGGGAGTTACTGA
CGTTGTCAATTATTTTAAAGCAACAGGGTTTGAGGAGCAAGCCACAGCTTTCCAGGATCA
GGAAATTGATGGTAAGTCGCTGCTCCTAATGACTCGAAATGACGTCCTGACAGGACTGTC
AATAAAGCTTGGCCCTGCGCTCAAGATTTACGAGTACCATGTGAAGCCACTACAAACTCA
GCACCTGAAGAGCAACGCCTCA------TAG
>Pantodon_buncholzi_mixed|010286|scaffold12917|m.16382
GAGCGGATCTGCCGCATGGTGCGCCGGCGCCACGGGTCCGAGCCGGAGCAGACGCGCTGC
GAGCTGGAGAAGCTCATCCAGGAGCGCACGGTGCTCAAAGTTTGCTACAAGGGCTCCATC
TCGTACCGCAACGCGGCCAAAGCGCAGCGCCGCAGCCGCAAGAAGGCGCAGGAGGATGGG
GAGGAGGAGGAGGAGGAGGCGCGGCCTGAGGCGCGGAGCAGCCAGGGGGGCGCGGGCGCC
GGGAGCAGCAGCAGCACCCACAGCTCCACGGACCAGGGGGAGACGGGCGAGTCTGAGGAG
GAGGAGAAAGAGTCTGTGTGCACAGAGGAGCACATTCCCGAGGAGGAGGATGTGAGGAAG
ATGGAGGTGGAGCCGAGCTGCAGCAGCGCGCACACGGTGGAACAGTGCGCGTCCAATTTA
CAGCACAAAAGCGGTCCGGCAGATGAGCTTGCCGATAACACCTCCACCTGTCAGTCACAC
CAGGCCTCCGCCCCCAAGCCTCACACACTGGAGGGGAGCGACGCTGCAGCTCACCCCGCT
GCGTGCTGCACGTCTGCAGACGCACAACCGGCCCTAAAGCACGATACGGGAGATCTGGAT
CCAGGCGTCCAgcCTCGGGCTGTGTGTCCTACTGTGCAGAAGGACCCGATGACGGCTGAG
GAGGAGATGAGAGTGGAGGAGAGCGCCGTCACCCCCGACCAGCTGGTTACGGAATCTTCT
AACACACAGGATCAGGTGGTGATGCGTTCTGAGAGGGGAGGGCAGACCTCGCTCGGCCCT
AGTGAAG------------ACTATTTGGAATGTAAAGCAGAAATTGG-----TGTGAGTT
CCTGTTCGCCTCCCCCATCAGCCCCCTGCCAGCAGAAAGGCAGGGCCACAGAT--GCAGG
GTCACAGAGTGTAGCGTGTTGTGAGAGCCGGCGGGACACTGTTCACTGGAGCGTGTCGGA
TGTGGTCAGCTATTTCTCTACGGCTGGGTTTCCCGAACAGGCTGCCGCTTTCAGGTCTCA
GGAGATCGACGGGAAGGCCCTCCTACTAATGCAGCGCAGTGATGTGCTCACCGGCCTGTC
CATCAGGCTCGGACCCGCCCTCAAGATCTACGAGAAGCACGTGAAGGTGCTGCAGAAGAG
CCACTTTGAGGACGACGGGGCGCTGTGCTGA
>Sargocentron_rubrum_gill_6|016526|scaffold25129|m.32181
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------ATGAAAA
ATTACT-----GTAACAGTGCAAATTCTGGCATGGATGACAAGGCGAATGGTTCCGTTGA
CACCAAAAGCCCTGTGGAGAACGGCCAGCTGCCAGACCCTGCCAACTGGGGGGTAGCGGA
CGTCGTCAATTACTTCAAAGCAACAGGGTTTGAGGAGCAAGCCACAGCTTTTCAGGATCA
GGAAATCGATGGCAAGTCTCTGCTGCTGATGACGCGTAATGATGTCCTGACGGGACTGTC
AATAAAGCTGGGCCCCGCGCTGAAGATCTACGAGTACCATGTGAAGCCGCTGCAGACCCA
ACACCTGAAGAGCAACGCCTcg------tag
>Scleropages_formosus_red_gill|003529|C1278402|m.73476
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------CAGGTCATGAGGGGGTC---AGGCCGTGGGCAGATGTCCTTCGTTCCT
ACTCAGG------------AGTACCTGGGGTGTAAAACGAGTGTGGA-----CGCAACTT
CCTGTCTACTGACACCGACTGCCTCTCCCAGATGCCAGGACATCACAACGGAA--GCAAA
GATGACCACAGGAATGTACCTGAAGACACACCACAACCCCGCACAGTGGACCGTGGCAGA
TGTGGTGAGCTACTTCTCTGCAGCTGGCTTTCCGGAGCAGGCCGCAGCATTCAGGACTCA
GGAAATTGACGGGAAGTCCCTCCTCCTGATGCAGCGAAGCGATGTGCTCACTGGCCTGTC
AATCAGACTTGGCCCTGCCCTCAAGATCTACGAGTTCCACGTGAAAGAGCTGCAGAGGAC
CCACTTTGAGGATGATGGCTCTGTGTGTTGA
>Synodus_sp._gill_5|017836|scaffold23337|m.31202
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------ATGAAAA-----------------------------------------------
----------------------------------------------------ATGATCCT
GCTGGAA-----TTCTCAACCCATTAAGTTCGCAAGACGAGAGAAGACATCTCATGAAAA
TATACT-----GTAACATTGCAGAGCTTGGAATGGATGACAAGGAAAATGGCTCAGTTGA
AACCAAGAGCCCAGTGGAGAATGGTCAGCTACCAGACCCTGCTAATTGGGGGGTAGCTGA
TGTCGTCAACTATTTCAAAGCAACAGGGTTCGAAGAGCAAGCCTCAGCTTTCCAGGAACA
GGAAATCGATGGCAAGTCTTTGCTCCTGATGACACGCAACGACGTCCTCACCGGGCTGTC
CATCAAGTTGGGCCCGGCGCTGAAGATCTACGAGTACCATGTGAAACCACTGCAGACGCA
GCATCTCAAGAGCAATGTCTCG------TAG
