>Amblygaster_clupeoides|029782|TR5294|c0_g1_i2|m.9936
------------------ATGGCAGGACTGCTGGAGGCTGCCCTTACCACATGTGTGTGC
AAAGTGTGCCTTAGCATCGTCGGCGTCCGCGTGGTCCGAGGAGGATCCCTGGGCTCGGTG
GGGCTGTGCTCCAGCAGTCTCCTGCTCCTCACCGACTTCACTATCACGCTGTTCCTGGCC
TTCCTACGGCTGGCGGACTACTGGCAAGTGGCCTTTCCAGTCTCTGGCGACATCATTGCT
CTCCGATTCCTCCTCTTCCTCACTCACACCTATGGGAGCGTGATGCTGCTCACCATCCCT
CTGGTCACCGTGGAGATGGCTTTTCTTCTCCGCTGGCCCCACCTTGGAGGGACAGAGGGA
GAGGGCCATGGAGGGAAGGGCACGCGCATGAGGGGAGACGAGAGCCGCGTTCCTCTGTGC
TCTGACCCAGGGGAGGCAGAGAGCGGAGAGGCCTCTCTTGAAAGAGCAAAGCAGCAAGAG
AGGCACACTTCCTCGGC--------TGCCGTTCTGGCTCACGCTGCGTGCGT-CCTGAGC
TGCCTGCTGGCATGGTGCATCTCAGGGCTTCGCGCCGAACGCCGCTGGGCCCGGGAC---
-----------TTACCCACAGTCGAGCTTTGCCTGGAGAGATACGCCATTGATGGTGATG
GAGGCAGAAGCATCGGGGTCTCTCTCTGGCACTGTCTCCCCAGCTTGCTCTCCGTGGCCT
GGACGGACCTCAGTGAGCCCTGCTGGGGTTTCCTGGCTGTCATGGTTCTCCTGGGCCA--
-------CTATGTGAGCCTGCGTCTCAGCCTCAGGTCTGACCCCCAGCATGTACGCTCAG
AGAGGGACAAATCTTCACTCGTGAAGGAAAAGGACAAAGGAAAGCACCCCCACGTGGATA
CCCATGAGCAAATGGCAACAGCCAGCATGGGCTTAGAGAATGTTGCCGTTTCCCTGGAGG
AAGAGGAGGAGAAAGAACCGGAGCACATGACGAATATGGACGTCCGAGTGCAAATGCAAA
CACAACCTTCTCTCTGCGTAATTGTTAATCCCTCAGATGGCATCTGGACACAAAGCCTCA
CTGTTGACACGGAAACAACAGCCAGCAAGAGCCAAGTCCTCGACACGGGCACGCCTTGCA
GCGCTGAGAGACGTCAAGCGCCCTGTCCTCATGGAAAAGGCTGCCTTTCATCTCGCAGCT
TTGCATCCATGCCCGACAGGTGCAGGTCCCTGGTCAAAGTCAAGGGTGCGGATAGGCAAA
TGCAAGATAAACAGCCGCCAACATCTGGACAGCAGCCACTGCGAAAGGGCAGTGACATGG
CAGAGAATATGTGTTTTGTGTGGGTGTCACCACAGTCAGACTGCAGTGGGGTGTGGGAGG
GCCCACAGG-------ACCCGCTGCAGTGCCCTAGGCGCTGTTGCCAGAGGTGGGGTTTC
CCTGG--------GGGATCCCCCTGCCC--------GAGAGGCCTGCTGATAGCAGT---
--------------GCTTATGTGGGGGATATTTATCTGCCTTTTCCC-CGTGCCTGTGGG
CTTTTGTGTCTTAGTCATCCAACATACAGAGACCCTTGTTTTGTTTGGG
>Distichodus_sexfasciatus_gill_4|020094|scaffold29510|m.34957
G------GAGGCACTAGAATGGATGGTGTTCTGGAGGTCATTGTTGCTCTGTGTGGCTGC
AAAGTGCTGTGCAACTTTTCATGTCTGCCGTTGTTC---AAACGCCCTCTGTCCATCGTC
ACCCTCTGTTGCAGCTGTCTCTTATTCTTCACCGACCTCTCCATTTTTCTGTTTCTGGCC
TACCTCTGGTACACCGCTACTGGACCTATGTCCTCTAACCCATCTTCCGACATCATCTCT
CTGCGTTTCCTGCTGTTCCTCAGCGACACCTATCGGCCAGTGCTGATGCTGACGCCTCCG
CTGGTTGCTGTAGAGGTTCTTATCAgtcttctgggtcctaaTGAGAATCTGATGGAACTG
ACT-GTGAAGAGAGGGAC-------CTTTAAAGAGACAAAAGGGTCTCAAAA--------
--TGGTGCAACTGAGACCAGGGAGGTCAGATCAGATCTAAACAAAGCGAAGAAGAAAGGG
TCTGAAGTACCATCGCTGGTTTCCATGGAAGTTTGCAATGACCTAGCGG-----------
--------GGTCTGAAAAGTCACCAACGAGACCGGAGGTGAACATCAAGACCATGGAAGA
AAAAATGAGGTCTCAAAGTGGAGCAACCAAGACTGGGGTGGTCAGATTATTACAGAAGGG
GGAGAAGAGCGAGGAGAAT-----------------------------------------
----GGGTCTGATGTAGTCCGGTTGG------------------TTGCTGTAGAGGTTCT
TAATGATCTACCGGGGCCTGAAGAGACACTGACGAGACTAAAGTTGAATGGCAAGACCC-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------TGGAAG------------------
------------------------------------------------------------
------AGTCTGAAAGTGGATCAACCAAGATTGG--------------------------
------------------------------------------------------------
---------------------GGAGATCA---------------GATGTTTACAGACAAG
GGAGAAGGGAGGCTCCGATTTCA-------------------------------------
-----------------------------------------------GACCTGTGGGCTG
CCTCATCTGT--------------------------------------------------
-------------------------------------------CTTCTGTTATGGG----
----------------TCATATGTGGGACATGCGCCAGATCTAGCT--------------
-----------------------------------------------GG
>Lepidogalaxias_salamandroides_Head_2|010020|C546926|m.50017
GTTCCTGTGAGCACAGCGATGGATGGTGTGTTGGAGGCTGCAGCTGCTCTCTGTGCATGT
AAGCTGGCGTTCAGTTGGCTCTTCCTCTCCACCCTC---ACGTCCTCCCATAGCGCGGTC
AGCTTCTGCTGCGGGTGTCTGCTGCTTGTGACAGACCTCGTGGTCACAGCCTTCCTGCTC
CTCCTCTGGTTGGCCGAGCCCTGGCTACCTCCGTTTCCCACCTCCAGCGACGTCGTTGCC
CTGCGCTTCCTGCTCTTCCTCGGCCACACCTACTGGACGGCACTGCTGCTGAGTGCGCCC
CTGGTCGCCGTGGAGACCGCGGCGAGGCTGCGCTGGCCCCGGCCGAGCGGGGAGGAGGGG
G----------------------------------GGGAGTCAGCGCTGGAC--------
------------------------------------------------------------
-----------------------------------------GCGGCGGGCTT-CCTGGGC
TGCCTCGCCGTGTGGATCCTGAGCGGTCTCTACGCGGGGCAGGAGCGGAGGACAGA----
----------------------------------GGAGCTGTGGGCGGAGGCATGTCTGA
GGACGAGCGCC---------TCCCTCCCCCCGTGCCTCCCCGGGCCTCTCGGTGCCGCCC
CGCCCGCTCTGGCTCGGGCCTGGTGGGTCCTGCCCGCCGTGACGGTGCTGTTGGCGCTGG
------------TGGAGGCGCTGAGCGGACGCCCGGCCCACCACACACATGCGAGGACGG
ACGTGGAGGCACAGCGGCTCACG-------------------------------------
------------------------------------------------------------
------------------------------------TGCACG------------------
--------------------------------------------------------CTCG
CTGTTGACTCAGAGAAAACACTCCCCAGGTGTGC---CTTTCACACCGTGGCATCTCTCA
GCAGCAAGCAGCTGCCACTCCACCCCCCCGCCAGCATCCCCCGCCTTTCA--GCAGAGCT
TCGCCCGGGTGACCAGCAAGAAGAGACCC---------------------------CGTG
TGCAGGGCGAGCCCACCCCAGCCC---------------------GGAGCAGCAGCAGGG
C---------CCCCTGAGGCTCAGCGCCCCCGCCTCTGCTCCTCCTCGGCTTTCGGGGGC
CCCCACCCGTGGACACACGCGCTGGGGTTCACCACGCGTGTTTGGTGGACTGGTGTGTGT
CCTGGTGGCGTGTGTGTTCCCCATGCTCCTCGGGGTGAACGTCCTCCTGGTCAGGACCGT
GGAGCTGGTCACACGCTGGAGCGTGAAGAGCCTACTGGCTCCACCCCGCAGGACGATGGA
C--------------AGTCAGAACCACGGGGACTCGT----------GA
>Melanotaenia_praecox_viscera_mixture_8|002175|C421900|m.27408
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------CTCAGCCACACCTATGGGGCCGTGCTGCTCTTGAGTACATTT
CTGATTGCTGTGGAGAAACTGATCAGACTGTTGTGGCCTCACACTGTTGTCAGTCACAGG
GC----------GGTGAG----------TCAAACTGGTGCACAGCAGTG-----------
--TCATGTTGGGGAGGAAAAAGTCGAAGAGGAGGAGGACATCAACGGCTTGGATAATGAC
--------------------------ATGAGCTTGCAACAAGTTGGCGGCTT-CCTCTGT
TGCTTGTCGGTGTGGATCGTTGTCGCCCTGAATGTCAGATGGCGTTGGAAAGTGGA----
----------------------------------GGAAAAGTGGGCTGCGGACTGTTTGT
ACACAACCGAC---------TCACTTGTCAGATGTCTGCCTAACCTGCTTGCAT---CCA
TGCCCAGTGCAATGAATCCCTTTTGGAGCATGGCTTTCCTCTTCCTCCTCCTACTGCTGC
TGACCATCAGCCCAGGCCTGCAGAGACAACACCAGACCCCTGCACAGGCAGAGAGCACA-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>Sargocentron_rubrum_gill_6|001159|C647827|m.43240
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------GGCGCTCTGGACCTGCACTGTCATGATTTA----
------------------------------------------------------------
---GAGGTCGCGGAGGAAAGGAATCATGGGAATGACACAGAGAGTGACCCCAAAAAAGAT
--------------------------ACTAGGCTGTTCCAAGTCATCGGCTA-CCTTTGC
TGCCTGTCAGTGTGGATTGGCGTTGGCCTCAGTGTCAGGTGTGGATGGAAGCTGGA----
----------------------------------AGAGGTGTGGGCCGCTGCTTGCATGC
ACACAACTGGC---------TCCCTCATCGGATGTTTACCCCGTC------------CCA
TGCCCAGCACCCTGGATCCCTGCTGGGTCGTGGCGTTCCTCTCCCTCCTCCTGCTACTAA
CGATGGTTA---TGGGCCTGCACAGGCGGCACCAGGCCCAGGCACACACTGTGAGCACAC
ACACGGAGAAACATGGAACT----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------AACAGTAAC----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>Scleropages_formosus_red_gill|000422|C1185361|m.67056
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------AGCGACGCCATTGCC
CTGCGCTTCCTGCTCTTCCTCGGCCACACCTACGGCGAGGTGCTGCTGCTGACGATTCCG
TTCGTCGCCGTGGAGACGGCGTGCAGACTGCAGTGGCCCCTGTCAGGTGGAAGAGAGGCA
G----------------------------------GCTGCGTGGCGCTGCAA--------
--GGGCGAAACAGAGCCACGGGAAGCTGGAGAGGCTGTGAAGAGACGGAGAGACTGCAGG
------------------------------------------------------------
-------------------------GCGCCTGCACTCACGATGGACAAAACCCGGG----
---------------------TCGCGGCGGATGTGGAGCATGGGACGGGGAGATGGACGC
GGTGCACTGGCAGCGGG-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------AAG
GGCAGAGAGAGTCC----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>Synodus_sp._gill_5|003340|C558105|m.45028
------------------ATGGAAGGTGTGTTGGAGGGGGCAGTTGTGTTTTGTCTGTTG
AAGCAGGCATCCAACCTCTTGTTCCTGCCTTTCGTC---CCTGCTTCTCTCAGCCCCATT
AGTCTATGCTGCTGCTGTCTGCTCATCTTCACAGACTTCTTCGTAACAACATTCCTAGTT
TTCTTGTGGGTTGCTGCCTCCTGGTTATCATATCTGTCCCCTTCCACTGATGTCATCGCT
CTGCGCTTCCTGCTCTTCCTTGGTCATACATATGGGACAGTTCTACTATTGATAACACCT
CTGCTCGCTGTAGACACTGTGTTGAGGCTGCAGTGGGCCAAAGTGGAACGCAGTGAGGTA
ACC-ACCGAAGAGGGGAG----------TAAGGACACTCAGAGGCAATGGAA--------
---------AGAGAAAGAGGAGGAGAAGAATACAGACACAGAGGAAAGTCAAAGTAAAGG
--------------------------GAAGATTGGCTCCCAGTTACCTGCTTATCTCTGC
TGTCTGTCTGTATGGGTTCTCTCAGGCCTCCAGGCCGGGTTTGGGAGGAAACTGGA----
----------------------------------GGAACAGCAAGCTACTGCCTGTGTGC
AAAACACCAGC---------TCCCTGGTCGTGTGCCTGCCCAGCCTGCTTCCAGGGCTTG
GGCCAGATGTGGTGGAGCCATGCTGGAGTCTGGCGCTGCTCTATCTC-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
