>Amblygaster_clupeoides|040607|TR67332|c1_g1_i1|m.96414
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------GGGGAGAAGCCCTACCATTGTGAGCAGTGCAGTTACTCCTGTGCTGAG
CCCTCCAGACTAAAGTATCATATGAGAATTCATCAGGAGGAAAGGAAATACCTTTGTCCG
GAGTGTGGCTACAAATGCAAGTGGGTGAGCCAGCTGAAGTATCACATGACAAAGCACACA
GGAGCCAAGCCATATGCATGTGAGGAATGTGAGTATCGCACCAACCGGCCTGATGCCTTG
CGTGTCCACCGGGAAACCCGCCATTGTGATGTGCGCTCCTTCATGTGTGAGAAGTGCGGC
AAGGCCTTCAAGACACGCTTCCTGCTCAAGACCCACCAGCAGAAGCACAGTGAGGAGCGC
CCATTTGTGTGCAGGCTGTGTTCCAAGGCTTTTCGCTGGGTGGCTGGCCTAAAGAACCAC
TACCTGACCCACACCAACCAGCAACCCTATCACTGCCTCCACTGCAGCTACCGGGCCAAG
CAGAAGTTCCAGGTGGTGAAACACCTGCAGCGGCATCACCCAGACCTACCTGTGAAGGAG
GGTGTGGGCCGCCACCCA------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------
>Corydoras_julii_viscera_mixture_8|011646|scaffold20423|m.15488
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------ATGAGGACTCACCAAGAGGAGCGTAAATATCTCTGTCCA
GAATGTGGATACAAGTGCAAATGGATAAACCAGCTGAAATACCACATGACTAAACATTCA
GGAATCAAATCGTACGCATGTGAGGAATGTGACTATCGCACCAACCGCGCAGACGCACTA
CGGGTCCATCGTGAGACACGACATCAAGATGCACGCTCCTTCATCTGTGAGAAATGTGGA
AAGGCTTTTAAAACTCGCTTCCTGCTTAAGACACACCA-------------NNNNNNNNN
NNNTACATTTGTTCGGTGTGTCGCCGTGGCTTCCGCTGGCCAGCTGGTCTCCGGCATCAC
TACCTCAGTCACACCAACCAGCTGCCCTTCCGCTGCCTTTATTGTTCCTACCATGCCAAG
CAGAAGTTTCAGGTTGTAA-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------
>Distichodus_sexfasciatus_gill_4|023154|scaffold32715|m.40703
GGCAAAAGAGCACGACTCAGCTGTGAACTTTGCGAGTTTACTTGCAAACAGGAGAGGTGC
TTGACCCAGCACGTGGCGCTGAAGCACGAGGGTGCGCGACCCTTCCGATGTCGCTTCTGC
GACTTCAGCACGGCGCGTCGCCATCGCTTGGAGGCCCACGAGTCTATGCACACAGGTGTT
GGAAGACACTGCTGTGAGCTGTGTGGCCAGACGTTTGGGACCACATCCAAGCTGCGCCTG
CATCGCCAGCGGATTCACGATAAGCAGCCCACACACTTCTGTTCTTTGTGCGATTACAAA
GGCTACAACCCAACTGACGTTAGCCGCCACACCCTCAGCTGCCACACGGGAGAGCTAAAC
CACGCCTGCAGCCAGTGCAAAGCCTGCTTCAGCTCAGAAGTCGCCTTGAAACAACACTGC
AAACGAGCACACAAGACTGCCTGGCAGCAGTGCATCCATTGCAGCCTTACCTGCAACAAC
CAGGCCAGTCTGAAAGCTCACTTGCAACGTGAACATCCTCAAAATGATAACGCCACTGTC
TCTCAGCTTCT---------------CCCTGAGAAGCGCCGCAAGAACTCCTTCCCCCAG
ATATGTCCAGATTGTCCTTTCAGTACTGGAAAAAGGCTGCTGCTCATTCAGCACATCATG
GACGAGCATGAGgggggacgtcctgaAGAAAGACCTTTCAAATGTGATGTCTGTGGCTTC
TCTTGCTGGCATCAGCTGGTGTTTGACCAACACGTCCGCTCACATGGTGGTACCTGTCTG
TACAAATGTACAGAGTGTGACTTTTCCACTCGGAACAGACAAAAGATCACCTGGCACATT
CGGATCCACACTGGAGAGAAACCATATCGCTGTGAAAAGTGCAGCTACAGCTGTGCTGAT
CCTTCGAGACTGAAGTATCACATGAGGATTCACCAGGAAGAACGCAAATATCTCTGTCCC
GAGTGTGGCTATAAATGCAAATGGATCAACCAGTTAAAGTACCACATGACAAAGCATTCA
GGAACTAAATCCTATGCATGTGAGGAATGTGAGTACCGTACAAACCGAGCCGATGCTCTA
CGCGTCCACCGTGACACGAGGCACCGAGATGAGCGTTCCTTCATCTGCGAGAAATGTGGC
AAGGCTTTCAAGACCCGCTTCCTTCTTAAGACGCACCAGAAGAGGCACAGTGAAGAGCGG
CCGTATGTGTGCTCTGTGTGCCGACGTTCTTTCCGTTGGCCTGCTGGCCTCCGCCACCAC
TACCTCTCGCACACCAGTCAGCTGCCTTTCCGCTGCCTCTATTGCCCCTACCGAGCCAAA
CAGAAGTTCCAGGTGGTGAAGCATCTGCGTAAACACCACCCAGACCGGCCGCTGCAGGAT
GGGGTGGATAAGGACCCGGACGCTCTCAACGTCCCAATGCAGAAGGCCCGACTTGGGCCG
ATGGAAGACCACCAGACAGATGTGCAGGTTAGCACAGAAGGGGAGAAAGAAATGGAAGAA
CTACAGG-----------------------------------------------------
-------GTTTATAG
>Lepidogalaxias_salamandroides_Head_2|004079|C492151|m.39875
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------AGCCAGCTGAAGTACCACATGACCAAGCACACA
GGGGCGAAGCCTTACCAGTGTGACGAGTGCGAGTACCGGACCAACCGACCCGACGCCCTG
CGCACCCACCGCGAGACGCGCCACCGGGAGCTGCGCCCCTTCGTCTGCGAGCGGTGTGGC
AAGGCCTTCAAGACGCGCTTCCTGCTCAAGACGCACCAGCGGCGGCACAGCGACGAGCGG
CCGTACGTTTGCCGCGTCTGCCGCCGGGCATTCCGCTGGCCCGCAGGCCTCCGACACCAC
TACCTCACCCACACCAACCAGCGGCCCTTCCGCTGCCTCCACTGCGCGTACCGGGCCAAG
CAGAAGTTCCAGGTGGTCAAGCACCTCCAGAGGCACCACCCGGATGAGCCCGTGGAACAG
AGCGTGGCGAAGGACTCAGCGAGCAGGAACGTGACTCTGCAGGAGGCTCGACTGCAGGTG
GGGGTGGATGAG------------------------------------------------
------------------------------------------------------------
---------------
>Pantodon_buncholzi_mixed|011338|scaffold14095|m.18269
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------AAATACCACATGAGAACCCACCAGGAGGAACGAAAATATCTCTGCCCA
GAATGTGGCTACAAATGCAAGTGGGTGAACCAGCTGAAGTATCACATGACCAGGCATACA
GGAGCAAAGCCACATGAATGCGATGAGTGTCCGTACCGCACCAATCGTGCTGACGCCCTG
AGGATCCACAAGGCCACACGGCATGGCGATACCCGCGCCTTCATCTGTGAGAAGTGTGGC
AAAGGGTTCAAGACGCGCTACTTGCTGCGCACACACCAGCGTAAGCACAGTGAAGCTCGG
CCTTACGTGTGCCGCCTGTGCCGACGGGCTTTCCGCTGGCCTGCTGGCCTCCGCCATCAC
TTCCTCACCCACACAGAACTGCTGCCTTTCTACTGTCGCCACTGCTCCTACCGTGCCCGT
CAGCGCTTTCAGGTAGTAAGGCACTTACTCAGACACCACCCAGATCAATCAGCCGAGGAG
GGTGTGGCCCGGGAACTGGGGTNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNATCTCCCT
GCAAGAGGCATGTTTGCAGGG---------------------------------------
------------------------------------------------------------
------------TGA
>Sargocentron_rubrum_gill_6|022357|scaffold5364|m.6003
--------------------------------------------------------ATGC
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNCTCC---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------AGGTCTGCTTCTCC---------------------------
------------------------------TGCATGCAGTGTGACTTCATGTGTAGCAGT
GAGGCCACACTCAAGAGCCACCAGCAGAGCAACCACCCTCATCTAAAGTGTGCCACCTGC
CAGGAGTCTTTTGAGACAAAGGAAAGCCTTGAGATTCATCGGAGAACCCACTTGGCCCAT
CAGTGCCAGCTGTGCTCCTTTGCTACTAAAACAAGGCAGGTATTAGCTCAGCACCTACTG
AATGAGCATGAGGAGGGATCCCCAGAGGACAAGCCTCTTAAGTGCAGCATCTGTCAGTTT
GCCTGCCGGCATCAACTTGTATTAGAGCAGCATCTCCGTTCTCATGGGGGCAAACGTCTT
TACAAGTGCACGGACTGCAAGTATTCGACCCGGAACAAGCAGAAGATCACATGGCACATT
CGCATACACACTGGAGAGAAGCCTTACAGCTGTGAGCAGTGCAGTTACACCTGCACTGAT
CCCTCCAGGTTGAAGTTTCACATGAGAGTTCACCAGGAGGAGAAGAAATACCTGTGTCCA
GAGTGTGGCTACAAATGCAAGTGGGCAACCCAGCTGAAGTACCACATGACTAAGCACACA
GGGGAGAAGCCATATGCCTGTGATGAGTGTGACTACCGTACCAACAGAGCAGACGCCCTC
CGTGCCCACCGGGATACACAGCACTGCGACATGCGCTCTTATATCTGCGAGAAATGCGGC
AAGGCCTTCAAGACTCGGTTCATACTAAAGACCCACCAGCGGCAACACAGTGACGATCGG
CCATACACATGTGGTTTGTGCCACAAGGCTTTCCGGTGGCCGGCGGGTCTCAGGCATCAC
TACCTCTCTCACACCAAGCAGCAACCTTTCTGCTGTCGCCACTGTTCCTACAGAGCCAAG
CAGAAGTTCCAGGTGGTTAAGCATCTGCAGAGACACCACCCAGAAATGTCAGTGGAGCAG
GGGGTAGTGAGGGACTCAGAAGCAGTTAGCTTGACCTTGAAGGAGGCTTTGCAAGGGACA
CTGGATGAAAGA------GCCATGGAAGTGGACAAGGAGGAGCAGGAAGGAGCTCAGGGG
------------------------------------------------------------
------------CAG
>Scleropages_formosus_red_gill|027926|scaffold43941|m.58389
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------ATGCTGCTGTTTACA
GGTGCCAAACCATACATGTGTGAGGAGTGCGATTACCGCACCAACCGGGCTGATGCCCTG
CGGGTGCACCGTGAGACGCGCCACCGTGATGCCCGACCCTTCATTTGTGAAAAGTGCGGC
AAGGGCTTCAAAACACGCTTCTTGCTGCGGACACATCAGCGCCGACACAGCGAGGCACGC
CCCTACGTGTGCCGGCTGTGTCGCCGGGCGTTCCGCTGGCCCGCAGGTTTACGACATCAC
TTCCTGACTCACACCCAACGCCAACCCTTCCACTGCTGCCACTGCCCATACCGAGCCCGC
CAGCGCTTCCAGGTGCTCAAACACATTCGGCGGCATCACCCGGAACAGCCGCCGGAGCAG
GGCGTGGGCCGCGACCCAGGCCCACACACTGTGTCATTGCACGAGGCTCGCCTGGAGCTA
AGAGAAGAGATGGGGCCAGAGACTGAACGGACACAGGTAGGGGAGGAGCAGGAAGCAGGG
CCAGAGACAGAGCAGGTCCACCCAACACATTTCCCTCTCCCACTTGAAAATGTCTGCCAC
ACAGTCCAGCTTTGA
>Synodus_sp._gill_5|002180|C537749|m.43088
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---TGCAGCCATCAGCTGGTTTTGGAGCAGCACCTCCGCTCACATGGGGGGAAGCGCCTC
TATAAGTGCACAGATTGCCAGTATTCAACCCGTAATAAGCAGAAGATCACATGGCATATC
CGCATACACACCGGAGAAAAGCCTTACAGATGTGAACACTGCAGTTACACTTGCACGGAT
CCTGAAAGATTAAAGTATCACATGCGAGTTCATCAAGAGGAGAAGAAGTATCTGTGCCCT
GAGTGTGGCTACAAATGCAAGTGGATGAACCAGCTCAAATACCACATGACCAAACATACA
GGGGAGAAGCCATTTGCCTGTGAGGAGTGTGACTACAGTACAAACCGAGCAGATGCCCTC
AAAGTCCATCGGGATACACAGCACCGAGACGTGCGTTCTTACATCTGTGAGAAGTGCGGC
AAAGGCTTCAAGACAAAGTTCCTACTGAAGGCCCACCAGCGGAAACACACAGATGAC---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------
