>Amblygaster_clupeoides|019035|TR32970|c0_g1_i1|m.54499
------------------------------------------------------------
---------------------------------ATGGCTGTCCTGCTCAAAGCCCTG---
TCCATTTTCGGAGTCCTACTT--------TCTATCTCCCTGCAGACAAGCAGCGCCTCTC
CGTTTCCTAGACTGTGCCAATGCATGGACACAAATTCCATAGAAAGATTCCGTCATCTGA
ACAAAATCACGGACTTCTCCATCAAGGAAAGAGGAGACGGATGTGACACAGAGATCATAC
TGACCACTTCCCATGAAGATGCTCCAG---------AGATCTGTCTGAAACCAGGAAAAA
CCCAGGCAAAAAGGCTACAAAATTGCTGGGAGAAGACAATCCAGAGGGATGAGAGCAGAA
AGCAAGAGTGCCTCCACAAGTTGTTCAGACCATAA-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------
>Chanos_chanos_liver|000802|gb|GDQX01003671.1||m.1203
ACGCTAC-----------------------------------------------------
------------------------ACAGTCAACATGAGTTCCACACTTCACACATGCCGC
TCTCTGCTAGCGCTGCTGCTCTGCATCTACCTCTTACAGCCCAAAAGGCAGAAGCTACAC
ACGTCCCCAGAG------GATGCGTGTGTCCTAAATCAGTCCCCAGAGTCAAGG------
CACTCCTGTCCAGCTTCAAAGTCTCCTCAAAAGGATCAAACTGCGACAAAGTTGAAATAA
TAGTTGTTCTGAAGCGGAATAATCAGA---------CCGTGTGTCTGAGTCCAGATGGGA
GACAAGGCAAGAAACTACTCCACTGTTGGGAAAGGAGTG---AGAAAACT----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------
>Corydoras_julii_viscera_mixture_8|012194|scaffold21265|m.16344
------------------------------------------------------------
------------------------------------------CTACTACACACACTTTCT
GCTCTCCTTGCTTTAGCTTTCTACATT--CACTTTACAGCTCAGCTGGTGGAAAGTCAGT
ATGTTCCCATGC------ACTGCATGTGTCCAAAAACCAAGGCTGGAGTGCAGG------
GGCCATTTTCAGATTTTAAGGTCACATTAAAAAGACCTGGTTGTAACCGAGATGAAATCA
TAGTTGTACTGGAAAAGGACAATCGCC---------AAGTGTGCCTAAGTCCTCAGGGGC
CTCAAGGCAAACGGCTACTGAATTGCTGGCACAGGAGAA---TAAAAGAAGACAAAAATG
TAAAGACATGCATGGGAAGGTTGAGGATGCGGAGGAAGAAACATCGT-------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------GGCAAATC-----------
----------------------------------------------AAtatcataa
>Distichodus_sexfasciatus_gill_4|002982|C869653|m.48977
------------------------------------------------------------
------------------------------------------------------------
------------GTAGGACTCTTCCTC--TGCCTCAAAGCTCAGGTAGGAGAGTGTCAGC
ATGTTCCAGGCC------GATGTGTGTGCCCGAAAACCAGGTTAGGAGTCCTGG------
AGCCTGTTTCAGATTTTAAAATCATGCCCAGTGGAGGGGTCTGCGAGAAAACCGAGATTA
TACTCACACTGAAGAACGGTGGTCGGA---------AAGTGTGTCTGAGCCCCAAAGGAC
ACCAAGCAAAAAGACTACTCAAGTGCTGGAAAAGAGCAC---AGAAGGAAGGCACAGACG
CGATGAAATGCAAGAGGCAGCTGAAACCACGTGCGCGCAAAACGAAA-------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------ATTAAATCCAAGCTGGT--
----------------------------------------------GAAATCGTGA
>Gasteropelecus_sp._gill_3|002318|C903715|m.45691
------------------------------------------------------------
---------------------------------------TGCACACTACATATCTGTTCT
GCTCTGCTGGCTGTGGTCCTCTATATC--CTTCTTACTGCTCAGGTGGGAGCAAGCCAAC
ATGTTCCAGTCC------GCTGCCTTTGCAGTAAAGCCAGGACCAGTGTCAAAC------
TACCGATTTCAGATTTTGAAGTCTATCTAAAAAGACCTGGCTGTAGTAGAGATGAAATCA
TAGTTACAGTGAAGAAGACCAGCAAGA---------CATTGTGTCTGAGTCCTGATAAAC
CACAAGGAAAAAGACTGCTGAAATGCTGGCGGAGAAAGA---TGCAGAAGACAAAAGATG
TGAAGAAATGCATAAGACAGAACACCCGAAAGAAGCAGACCAGATCA-------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------AAGAAGAC-----------
----------------------------------------------AACCTCATGA
>Lepidogalaxias_salamandroides_Head_2|015507|scaffold13233|m.17490
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------AAGCTTCGGG------
GACCCTTCACCGATTTCAAAGTAATCCCTAAAGGATCAAGCTGTGACAGAGATGAAATCA
TAGTCGTTCTGAAGAGGAACAAAAGTT---------TGGTGTGTCTGAGTCCAAACCATC
GGCAGGGCAAACGGCTGCTTGGATGCCGGACAAGGGCCA---ATCAGTCAGGCGGGGACC
CAAAGAGCTGCCTGCAAAGGCTTGGCAGAAGACGGCCGGGAGGGCAGCAGCGCGGCTCCT
CAAGGGGGGGGGGCCATCTGAACTTGGCAGCGGCGGCCGGTCGACCAAGCGAGGGGGAAG
CCACACTGATTCAGGGAGACGGGTCTCCCTCCCTAATAGAGGACCTTAGGCACACAAGAC
TCGTCGTTGACGACAAACTAGCGTGCTGCGGGAGCTACGTTAGCACATCCAAACCGATTC
ATAatggttcccgggtaagagagacgagtgttctatcacgtttgggtatattgtga
>Melanotaenia_praecox_viscera_mixture_8|003567|C439804|m.29405
CTTTCACTTCAACTGGAATTCACTCGAGCTCTCACTTTCTCCTCAGAGGAATTTTCTGGA
CTTCTTTCTCTTTCAGCGGATAAAACAGAGAAAATGGGCCTTTCGCAGATAAACAGTGCT
CTTCTACTCACTGTTGTGGCT--------GTGGTTTGCATAGAGCTCTATCAGGCACAGT
ACATCCCTGGAC------GCTGCTTGTGCCCCACCTCAGTCAAGAAAGTCAAAG------
GCAACATTTCCGATTTCATTGTAAATGAAAAGAAACCCAGATGTGATAAACAGGAATTGA
TAGTAACTATCACCAGACCAGACAACTCCACCTTCCAGCGCTGCCTCGACACTCAGGAAG
AGATGGGCACGGGTATAATTCAGTGCTGGAAAAACATAA---ACAGGAACGAAAGCCGGA
AGATGGAGTGTATGGACAAAAGGATGAAGAAGGCAGAGCA--------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------GTAA
>Pantodon_buncholzi_mixed|004061|C627722|m.35329
------------------------------------------------------------
---------------------------------ATGGAGCTCACAGGACAACTGAGCTGC
TTCATCCTGGCAGTGCTGCTCCACATT--CAGCTGCAAGCTCAGCTGGGAGACACCGCCT
ACATACCAACGA------GGTGCCAGTGTCCCAAAAATGAGGAGATAATTCAAG------
AAACCGTAACAAATTTCACCATAACCGAGAAAGGACCGCACTGCCAGACTGATGAAATCA
TAGTAACCCTGAAAAGAGAAAACATGA---------AAGTGTGTTTGAGCCCAGGGGGAA
GGCAAGGCCAGTTCATCCTCACATGTTGGGAGAGGATAA---ACAAAGACGAATCTTTGA
AGAAGAAGTGCCTTAGGAAAAAGAAACCCCACTGA-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------
>Sargocentron_rubrum_gill_6|003051|C692645|m.46210
------------------------------------------------------------
---------------------------------ATGGCCTTTTCACTGAAAACCTGCACT
TTCCTCCTGGTCGTTGCGGCT--------GCATTTTGTGTGCAGCTCTATGAGGCCACTT
TCGTTCCTGGATC---CAGGTGTTTATGTTATGGCACCATCAAGTTCACTCCAG------
AAAAAGTTTCAGATTTCAGAGTCATTGATGAGAAACCCGGCTGTGAAAAAACTGAAGTCA
TTGTCACAATACAGAAACAAGACATGAGCACAGAGCGTGCATGTCTGAACCTCGAGGGGA
AGCAGGCCAAGGCTCTTCTTGCATGCTGGAACAACAAGATAAACAGAGATGAGAGCCAGA
AGATGAACTGCTTGAGACGGAGAAAGGCAGAGTGA-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------
>Scleropages_formosus_red_gill|002604|C1253982|m.71608
------------------------------------------------------------
------------------------------ACTATGGAGCTCACACACAGACTACTATGC
CTTTCCTTGGCCTGCCTGACATGCATC--TTCCTTGAAGCTGACATTGGAGAAGCGACAT
ATGTACCAACAA------GTTGCTTGTGCCCAGTATCAAACAAACATGTCAAATTTT---
CACTTATTGAAGACTTCAGCATTACTGAAAAGGGGCCACACTGCAACACTGACACAATCA
TTGTCAAGTTGAGTCAGGGCAACCTGA---------AAGTCTGCTTAAATCCAGAGGGCA
AACAGGGCCAGGGTCTCCTCGCCTGCTGGAAGAGGATTA---ATGAAGATGAAAGCCAGA
AGAAGACATGCCTGAGAAGGAAACAACCTCTGTGA-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------
>Synodus_sp._gill_5|003686|C563946|m.45600
------------------------------------------------------------
---------------------------------ATGGCTCTCTCACCCAAAGCTCAAGGT
CTCATCCTGATTACTCTGTTT--------GCACTTTGCATTCAGCTTCATGAAGCTCAGT
TCATTCCTGGAGC---CAGATGTATATGTTATAAAACCATCAAGTACACTCCGG------
AAACAATTACTGATTTCCAAGTCATCGAGAGAGGACCCAGCTGCGATAAAACACAAGTCA
TTGTCACCCTGCAGAGGTTGGAAAAGAGTGAAG---CAATGTGTCTGGACACTGAGGGGA
AACTGGCCAAAGCATTTCTGCAGTGCTGGAACAGGATAC---AGAAGGACGAAAGCCAAA
AGATGACATGTCTCAACAGAAGAAATAAGGCGGAGTAG----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------
