>Amblygaster_clupeoides|041968|TR69856|c3_g1_i1|m.98106
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------ACGGCTGG-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------TATTGATCCAAGTCTCATGTTCATG
-----GAGGAAAAGAACACTGTGCAAGCATGGATGAA----AAGGAGGAATGACATTGGT
GCCTTTCAGTCAGACCACTTTCAGACATACCTTCCGCCCTTTGTAAGCGCCATCAATACC
TTGCAGTGTCTGCTTATGGCCAAGACAACGTTGTTAAAACATTCCCTAAGTATCCTGCCC
AACAATCCTAAAGAGGCAACTAGTGATAGAAGGACAGCGGAACATTTGGATGCTGTTAGA
AGTTTGGTGAGGGAGAAGTTCAGCAGTAATCCTGCTTACCAGACCCTGAAGACCCGTTTT
TTGTCCTGTTTTGCTATGCCTGCCCTCTTGGCCACTATTGATCCTGCCAGGAGCATCAAT
CAAAGTGATGATGAAGATGATCTTGATGATAATGATTGA---------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Corydoras_julii_viscera_mixture_8|008416|scaffold14963|m.10479
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------ATGTTT--------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------GTCCCTGTACAA--ATTCCTCCTGTT
CAAATTGATGCTAATGTCCCATTAAGACATGTAACCCCAAGTTTGCAAATCA--------
----GACCCCCAGCTGTAGCTAT-GCAAATGCTCTCCCAAGACAA--------------A
ACGCTAACTGTTCAAAGTC---------------------CAGCCCCT--------TTTC
AGCTTAAT-------CCACTTCCAAGTGCTTTAAACTGTGATCTAAACTCGATGTTTTTG
-----GAGCATCCAATTGAAGTCCTGCCCTGGCTTTC----TGGGGAAGGTGGCATTCCA
GTTCCTCCTCTTAACAAGAAAATGCCTTATCTTCCACCTTTTGGGGACAGCATCAATACA
TTGGCTTCTTTGCTTAAAACGAAAAAGACTTTATTAAGAACAGCTGAGTCAATCCTTCCG
GAGGCAGACCGAGAGAACAGC---GAAGAAGCCAAAA---------TCAGAGCCGTCCGT
CAGATCGTATCCGAGAGATGTCAAAATAATCCAGCATATTTACTTTTAAAGGCTCGCTTT
TTGTCCTGCTTTACTTTACCTGCCCTTCTTGCCACAATAAATCCAAAGAAAGAGACCACA
GAGACTGAAGACAAGGAGGAAGAGGAGGATGAAATCACAGAT-----------------C
AACTCGAATTAAATGAGGCTCTGTGTCAGCCTCAGACAGAGGAATCCTTGCT---TACAG
ATGAAAGCGAAGCATCAGCTCCACAGTCACTACGACCCCGAAGAAAAAAACAATCACGTA
AC---------------TAA
>Distichodus_sexfasciatus_gill_4|022704|scaffold32297|m.39839
TTAGTTCCTCTGTTAGCAAAGTCTAAAACATGGATTCTCACTCCTTGTCTGGTCCCTGTG
TCCGGAATTAACTTTCCGTCCCCTGTTGTCCTCGGTAATCAGAACCAAGTTTTGCCAGAC
GCGGATCCTCAGGTGTTATTCCGACCGCCAGTTGTATTGAACAAAAATGGTTCTTCCTCA
CCAGCTAAGACTGTTCAACTAAGCAGTCCAGCGCTGCCAACTGCTGGAACAAATCCGAAT
CTTTTGCCATCCTCTGTCTCAAACACGCCCAATATCTCCACTAACTCGGCTACTGTTGTT
TCTATAATTCCATCTAATGCGTCCACCTCTGTCCCTCGCCCTGCTATCCACCAAGTACCA
CCCTCTAAAAGCCCATGTCATTCAAAACAAGGCATCTTGAATGTTTCCCCTCAACTGACA
TTTCAACCACCTGTAATTATGAACCAAAATGGTTCCACTGAACTACCAAAAATTCACTCA
GTTACCCGCTTGGCCCCTGTTTCAGGAGATGCCTCCAAACCTCAGAATCCTACATCAGCT
GCTTCTGATGCAATCAAAGTGTCTTCTTTTAATAACTTAAGTGTCTCTTCAGTCTCTGTC
ACATGTGCATCTGTTATCCCTCAGGTTAATCCTGTTGCTTTAAACAAAGATCGTCCTGTA
GTGCAGATGCCACCTGCTGTTGTTAAAGGTGATCAGAATCAATGCATGCCAATCCAAGTG
CCTCAGGTGGCATTTCAACAGACAGTCTTAGCAAACCACAACCGGACATTGGCTAATGTC
AGTACTACTGGACCTTCTTCACTCAGTGGCTCACAGGGCATTATTCTTTCTAAGGTGACA
CCCAGTTCTGAGGCATCTAATGCCAGCAAAAACAAAGAGCCTTCCACCAGTGACCCAGCT
TTTTCTGCAACAAAGACATCCACGTCCGTCACTCCAGCCCCATCTTCTGCTTTAAAAGTA
GCCACTTCTGTTGCTGAAAGTGAAATTTCCACTATTACCT-----CATCCGACACCACTC
TCCGGCTCAGTTTAACACATG-----ATCCAACCGTCCCTGTACAA--AACAGTTTAGCA
GACAGCACAAAAAGTCCCTCCACTCCTCATTTGACTCCTAATAGTTATGTCAG-------
---GCGTCAGAATCAGGTGTTACCACAAATGCTAATGGAACACAG--------------T
GAACTCCAAGCCAAAAATCTGCCCCTGCAGAC---AGAAACCTCCCTC--------TCTA
GTCATAGC-------CGCAGTCCCGATACTTTGACTTTTGAGCCCAACTTGATGTTCCCA
-----GAGGATCCAGCGCAAGTGCAGACCTGGATGAA----GGGGGAAGGTGGAATATCA
CTGCCTGAGCTGGACGAAAAAGTGCCTTACctccctccattCGTCAGCAGCATCAACACC
TTGACTTCTTTGCTCAAGGCTAAGAAGTCATTGGTTAAAGCAGCTGAGCAACTCTTGCCT
GAAGAAGACCGACGCAGTAGTGAGGAGGAAACTAAAG---------TAGCTGCTGTTCGC
AAACTGGTATCTGACAGGTTTAAAACGAACCAAGCATATATGCTTCTGAAGGCTCGCTTC
TTGTCATGCTTTACTTTACCCGCACTTCTGGCCACCATACATCCATGCAAAGAAGCTGGG
TCGTCTGATGACCCTAAAGATGATGACGACGATGATACCAATGATGAA------------
------------------------------------------------TTCACGCTTGAG
ACTGTAGGA-----------TCCCAGCTC----AAATGA---------------------
--------------------
>Gasteropelecus_sp._gill_3|014637|scaffold24399|m.24497
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------AGCCTGGTATCTAGCGTGTCTTCA-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------ACTTCCTCTGTTAATAATGGAACAAATTCTGTCACTGTCA--------
----CTTCAGCGCCTGCTGTTATGAGGAACACTTCTACAGT------------------T
GTAATGCCACTTAAAA---------------CTTCAGGGGTCACCACA--------TCTA
ATCTGAAC-------CCCAATCCTAAGTGTTTGTCTTTTGACTCCAACCTCATGTTCctt
-----gagcatccagctCAAGTTAGTAACTGGATTAA----AGGTAACAATGGGATTTCA
CTTCCTGAACTGGATCACAAAATGCCTTATCTTCCACCATTTGTCAGCAGCATCCAAACA
CTGGTGTCTTTGCTCAAGGCAAAAGAATCTTTGTTGCAGGAGGCAGTGAAGATATTGCCT
GAAGAGGATACAGAAAGCACTGAGGAGGAAACTAAGG---------TCACTGCTGTCCGT
AAACTGGTTTCAGAGAAGTTTAAAACAAACCCAGCTTATTCACTCCTGAAAGCTCGTTTT
TTGTCATGTTTTACTCTCCCTGCCCTCCTGGCCACCATCGATCCATGCAAGGAAACCGAA
GTATGTGGGTCAAAAATGCTTGATGACGAGGGTGAAGAAGATGGTACAG--AAGAAGTCC
ATCCCATACCAAGTGGAAAT---GATCAGGCCCAGCCTCCTGACTCCTTCCTCAACACAA
ATCATAGGGATGAATCTGCCTCACAGTTCTCTGGAATGAGTGCAAGAAAGGAAAAACAGG
ACAACCATGCTAGTGCATAA
>Lepidogalaxias_salamandroides_Head_2|004828|C499820|m.41169
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------GTTGG-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------ACAGGGC---------------------
------------------------------------------------------------
----------------------------------CAGCTCCA------------------
-----------------------------------TACCT-----TATCCCCCGTCCCTG
TGTCAGCCAACGCCCCTCAC--------------ATCCCAGCCCAAGTAGCTTCTCAGCA
GGCTTTAAAGGTGGTCAGTGCAGCTTCCGTCCTCCCCAGAGTGCCAGTGACCAAAGTGCA
GAAGGCTCTCTCCCCAGCGCCGCCCCCACGGCTAGC----CACCG--------------G
GATGGCCCAGCCGAATCAGTGCCCTTTACAGCCTGCCGAACCCCCGCC--------TCCA
------------------AAACCAGATGCCATGCCTCTTAATTCCAAAATCATGTTCCTG
-----GAGGACCCAGAGCAGGTGAAGCGTTGGATGGG----GGACAGGAGGGGAGTGAAG
CTCCCCCACCTGGACGTCTCTCTGCCCTACCTGCCCCCGTTCGTCAGCAGCCTCAATGCC
CTGACGTCCCTCCTCCAGGAGAAAAGGGCTTTGACTCGCAGTGCCATGCAGCTTGTACC-
--------CCCGCACAGGTGTGGGGACGGGACCCAGG---AGCAGGTGGAGGCCGTTCGC
CGCGTCGTGGCCGAT---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------
>Melanotaenia_praecox_viscera_mixture_8|003086|C433814|m.28697
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------AGCATGTGGGTC-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------ATGACTCATAGCGGATTGGTCCAGCTG--------
------------------------------------------------------------
------------------------------GCTCAGGCTCCGGCTCAAGGCATGAAGGTT
GT----------------------GTTTGTACCTCCACCTGGAGGTGTTTTAAACCCTTC
TCTGGCCCCGTCTCCTTTAAGACCGAACCTAACCATCCCAGCAAAC--CGCCCTTTTCTT
G-------------------------------------------CTATACCTA------T
GAGCCACTGCAAGCCCCATCCTTCATCTATCCCACTACCGCATAACTCCTCCCACCTGCA
CCGACCTTCCCCAAAAGTGAATCTTC-----CTTATAAGGGCACTGTCAAAGCGGATTCA
GAGAAGGCTCCGTCACTCAGGTATGAGCGGCTGCAGTTTGATCCCTCGCTGATGTTCCTG
-----GAGCCTCGAGAGGTGGTGTGTAATTGGCTGAG----TGGATTGGGTGGGGTTGTA
GTTCCCGGGGCAAGGATGGCGCTACCCTACCTGCCTCCCTTCATCAGCACTCTGAGCACG
CTCAGTTTGCTTCTGCAGACCAAGAAATCTCTGATGCAGGCGTCCCTGCAGCTGCTGTCA
AAAGA-------------------AATGCATCCCCCT----CCATCCAAACCTTGTCCCA
CCCA---------------------------GCCCCTACCTGACCTGCCAGACTCCACCT
CAGACCTCAA--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------CCCAGCAGAGGAAGAG-----------------
--------------------
>Sargocentron_rubrum_gill_6|001922|C667567|m.44461
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------AACAC----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------GCTCAGCGCTCTGCTCTGCGCCAAAAGGTC
GCTG--------------------------------------------------------
--------------------------ACCAAGACTGCCCTGCAGAT--------------
------------------------------------------------------------
----------------------------ATTGCCGCAGAGCGCCG---------------
-------------------------------AGCACAAACGCACCCCA--------CCGG
GTCAGAGC-------ACCAAACACAACCCGCCAGGTCAGAGCGCCAAACGCACCCCGCCG
AGTCAGAGCGTGGAGCCCAAACCCGACAGCAGCCTGGTCCTGGACCACGACTACATCCAG
AGTCCCTGTCTG--------TCTGACATGTCTGCTTCC------------------TGCC
CCGAGTCCAAACCTGCAGAGGACACACAGCCAGCTCCCGGCGTCAGCGCCGAGCCTGAGG
AGGAGGAGCAGGGGGAG-------GAGCAAGATCGCA---------TAGCAGCGGTACGC
CAGCTGGTGGCGGAGCGTTTTGCCGCTAACCCCGCCTACCAGCTGCTGAAGGCCCGCTTC
CTGTCCTGCTTCACTGTCCCCGCCCTCCTCGCTACCGTCCAGCCAACCACAAAGACGACT
GCGCCCCA----------------------------------------------------
------------------------------------------------------------
---------------------------CCCAGCCAGTGAGGAGGAG--------------
--------------------
>Synodus_sp._gill_5|019862|scaffold25340|m.35318
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------ATCTGGGGTTCGAAGGTA
A-----------------------------------------------------------
------------------------------------------------------------
----------------------------------------------ACACCAT------T
ATTGGACCCCAACCCCTCCCTCCCACCAATCACAGTGCAGCACCA--------------G
CCAAGCCTCGCCCAGTCCCAAGCCCA-----TCTCCTGAAGCTCCGCC--------CCCC
GAGCAGCCCCGG---CTCCGCTGTGAGGCCGTGCAGTTCGACTCCTTCCTGCTGAGCTCC
-----GAGCCCATGAAAAACGTCTTGCATTGGCTCAG----CGGCCGAGGGGGCGTGGCT
GTGCCAGGGGTGGGCGTGTCCCTGCCTTATTTGCCGCCTTTCGTCAGCAGTCTGAGTGCG
CTCAGTGCGCTCCTCAGTGCAAAGAAGGACCTGACTGCCTCTGCACTGCAGCTGTTTCAC
AGCAA-------------------GAGGAAACCCAGA----GCGGCTCCGCCCTGCACCC
AGGG---------------------------CCCCGCCCACGGTACCCAGGGCCCCGCCC
ACGGCACCCAGGGCCCTGCCCACAGCACTCAGAGCCAC-------GCCAACGGCACTCAG
AGCTCCGCCCACTCCTCCTCTGACCAGGAGACCCACACACACCCCTCCACCCCCATGCCC
AGCTCGGACCATGATTACCT---CCCCTCCCCTCCCCCACAGGCCTCCCCCAGCACTCAG
CCTGCTGAGGA----TCCCCCGTCAGCTCCAGCAGCTGNNNNNNAGCGGTGCGTCTGA--
--------------------
