>Amblygaster_clupeoides|005241|TR1510|c1_g1_i1|m.3178
ATGTCT---------------------------------------GCGAAATCAACAGCC
AAGAAAGGAGGTAAACATG----------------------TTAGTGACGACCCTGTCCG
TAATTTCGAGAAATGGAGGAAAAAATACGACAGGACGAAAAAACGAGTTAAAGTCGTGAG
ACAACCTCCTAAGAAGAAACGAGTGTGGGAGTCCGAACGAGATGGCATAGG---------
---------------CAAACTGGTGTCTAAATATGACCAGATCAATCCCAAGGATGTCGT
GAACTTCTCAGATTTCCCCCTGTCAAAGAGAACCCTTAAAGCTTTGGTGGAGGCACAGTA
TCGTCAGCCGACAGAGATCCAGCGGCAGACCATAGGCTTTGCCTTGCAGGGAAAGGATGT
GCTGGGGGCAGCCAAAACTGGCTCTGGAAAAACACTTGCCTTCCTTATACCTGTTCTGGA
GTGTTTATATCGGAACCAGTGGACAGCCATAGATGGACTTGGTGCCCTCATTATTTCCCC
CACTAGGGAATTGGCCTACCAGACATTCCAGGTTTTGCGGAAAGTGGGGAAGAACCATGA
GTTCTCTGCTGGGCTGATCATAGGTGGCAAGGACTTGAAGGATGAGGCAGAGAAGATTCA
TCGTACCAATATCATTATCTGCACCCCTGGGCGCTTGCTGCAGCACATGGATCAGACCTC
TGCTTTTCATGTCTCGGACCTACTCATGTTGGTCCTGGATGAGGCTGACCGTATTCTGGA
CATGGGCTTCTCTGAGACGCTCAATGCCATTGTGGAGCACCTCCCTACCCAGCGTCAGAC
CCTGCTGTTCTCC-----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------
>Corydoras_julii_viscera_mixture_8|010605|scaffold18729|m.13879
---------------------------------------------GAGAAGGAAGATTCA
G-------------------------------------------TCCCGGACCCGGTTAA
GGACTTTGAGAAGTGGAGGAAGCGGTATGATAAAACCAAGAAACTCAGCAAGACCCAGAA
A---------------AAGAGAGAATATGAGGTGGAGAGAGAGCACATCCACAAACTGGT
GTCCAAATACTCACNCAAACTGGTGTCCAAATACTCACAGATTAATCCCCGAGAGGTGGT
GAAGTTTTCGGATTTTCCTCTGTCGAGAAAAACTTTAACAGGTCTGTTGCAGTCTCAGTA
TCGGCAGCCCACAGAGATCCAGAAACAGACCATAGGCTTTGCTCTGCAAGGAAAGGATGT
GCTCGGCGCTGCGAAGACCGGCTCTGGGAAAACTTTAGCCTTTTTAATTCCTGTGCTGGA
GTGTTTGTACCGTAACCAGTGGATGGCGTTGGACGGTCTGGGTGCTCTGATTATCTCCCC
CACCCGAGAGCTGGCTTATCAGACGTTCGAGGTGCTGAGGAAAGTAGGAAGGAACCACGA
CTTTTCGGCCGGACTTGTGATTGGTGGGAAGGATCTGAAGGACGAGCTGAAGAAAATCCA
TCGTACGAACATCATCATTTGCACTCCAGGACGTCTGCTGCAGCACATGGATGAAAATTC
CTGTTTCCACACCTCAGATCTCCACATGCTCGTGCTGGATGAAGCAGACAGGATCCTGGA
CATGGGTTTTGCCGACACTCTCAATGCCATCATCGAGAATCTGCCCAAGACCCGACAGAC
GCTGCTGTTCTCCGCCACACAGACCAAGTCGGTGAAAGATCTGGCTCGATTGAGTCTGAA
GGATCCTGAATATGTGTGGGTTCATGAGCAG-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------
>Distichodus_sexfasciatus_gill_4|004841|C897431|m.51964
---------------------ATGCGAATG---------------AAAACGGGCAAAGCG
AAGAAAAAAGTCG-------------------------------CAAACGACCCGGTTAA
GAATTTTGAGAAATGGAAAAAGAACTATGCCAAAACCAAGAAACATGCCAAACAGCCGAA
G------------AGGAAGCGCGAATGGGAGGTAGAGAGAGAAAACATCCA---------
---------------GAAGCTGGTGAACAAATACGCCGAGATAAATCCGAAGGAGGTTAT
TAAGTTCTCTGACTTTCCGATCTCCAAGAACACTCTGAGAGGCCTGCTTGATGCTCAGTA
CCGGCTGCCCACAGAGGTCCAGAGACAGACTATCGGTTTTGCTTTGCAAGGGAGAGATGT
GCTTGGGGCTGCGAAGACTGGTTCTGGAAAAACCCTGGCCTTCCTCATTCCTGTTTTGGA
ATGTTTGTACCGTAACCAGTGGACGGCTATGGACGGACTTGGCGCTCTTATTATCTCTCC
AACTCGAGAACTCGCTTATCAGACGTTTGAGGTGCTAAGAAAAGTGGGCAAGAACCATGA
CTTCTCAGCTGGCCTTGTCATGGGTGGAAAGGACCTTAAGGACGAGTCGATGAAGATTCA
CCGTACAAATATCATTATTTGCACTCCGGGGCGTCTGCTGCAGCACATGGATGAAAATGC
CACCTTCCACGCCTTGGATTTGCACATGCTCGTTCTGGATGAAGCAGACAGAATTTTGGA
CATGGGCTTTGCAGATACTCTCAATGCCATCATAGAGAACCTTCCCAAAACCAGACAGAC
ACTGCTGTTCTCTGCCACGCAAACCAAGTCTGTCAAAGACCTGGCCAGACTCAGCCTAAA
GAACCCCGAGTATGTCTGGGTGCACGAGCAGGCTAAATTCAGCACCCCAGCCACGCTGGA
ACAGAGCTACGTGGTGTGTGAACTCCATCAGAAGGTCAATATGCTCTTCTCATTTTTGAA
GAGCCACTTGCAAAAGAAGATTATAGTTTTTTTTGCGTCCTGTAAAGAGGTGCAGTATCT
GTTCCGTGTGTTCTGTCGGCTGCGGCCCGGTATCTCGGTTCTGACTCTGCACGGCAAACA
GCAGCAGATGAAGAGAGTGGAGAACTATAACGAC--------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------
>Gasteropelecus_sp._gill_3|020678|scaffold32523|m.35560
---------------------ATGCGAGTT---------------AAAAAGGGAAAGGAA
GCGAAGAAACCCGGCCAGT----------------------TAAAAACCGGACCGGTTCA
GAACTTCGAGAAGTGGAAAAAGAAATATGACAAAACCAAGAAACAGGCCAAACAACCCAA
G------------AGGAAGCGCGAGTGGGAGACGGAGAGGGAGAACATCCA---------
---------------GAGGCTGGTGGTCAAATATGGAGCGATCAATCCAAAAGAAGTAAT
AAAGTTCTCAGACTTTCCACTCTCGAGGAAGACACTGCAAGGTCTGCTTGAGAGTCAGTA
CCGACAACCCACAGAGATCCAAAAACAGACCATTGGCTTTGCTTTGCAAGGAAAAGATGT
CCTGGGTGCTGCAAAAACAGGTTCTGGGAAAACTCTGGCATTCCTCATTCCTGTCTTGGA
GTGTTTATACCGTCACCAGTGGACAGCGATGGATGGTCTGGGCGCTCTTATTATCTCTCC
CACTCGAGAGCTGGCATACCAGACATTTGAGGTGCTGCGGAAAGTGGGAAAAAATCATGA
TTTCTCTGCTGGCCTTGTAATTGGTGGAAAAGATCTCAAAGACGAGTTATTGAAGATCCA
TCGCACAAATATCGTAATCTGCACGCCTGGCCGTCTGCTGCAGCACATGGATGAAAATTC
CACTTTCCATGCATCAGACTTGCACATGCTGGTGTTGGATGAAGCAGACAGAATTTTGGA
CATGGGATTCGCAGAGACGCTCAATGCCATTGTAGAAAACCTTCCCAAAACCAGACAGAC
TTTGCTTTTCTCCGCCACACAAACCAAGTCTGTCAAAGACCTGGCTAGACTCAGCCTGAA
GAACCCTGAGTATGTCTGGGTTCATGAGCAGGCTAAATTCAGTACTCCTGCTACTCTGGA
GCAGAGCTACGTGGTGTGTGAGCTGCATCAGAAGGTCAACATGCTCTTCTCGTTCTTAAG
GAGTCATCTGCAAAAAAAGATTATTGTCTTCTTTGCTTGCTGTAAAGAGGTGCAGTACCT
CTTCCGTGTATTCTGTCGACTCAGGCCGGGTATCTCAGTGCTGGCCCTGCACGGAAAACA
GCAGCAGATGAAGAGGGTGGAGGTCTACAATGACTTTGTCCGCAAGAAAGCAGCCGTGCT
CTTTGCAACGGACATTGCTGCGAGGGGACTAGATTTCCCAGCTGTGAACTGGGTTTTGCA
GTTTGACTGTCCAGAAGATGCCAACACATACATCCACAGAGTTGGAAGAACAGCCAGGTA
TAAGGAAGGAGGGGAGGCGCTACTCATCCTTTTGCCCTCAGAAGAAAAGGGTATGACCAC
CCAGCTTCAAGAGAAAAAAGTTCCAATTAACAAAATCCAGGTTAACCCGGAGAAGCTGGT
GGCTGTGCAACAGAAGCTGCAGGCCTTCCTGGCCCAGGAGAAAGAGCAGAAGGAAAGAGC
TCAGAGATGTTTTGTGTCCTATCTTCGCTCCATCTATCTGATGAAGAACAAAGAAGTCTT
TGATGTGTTTCAGATCAAGCTCTTGGAATACGCCATGTCTTTAGGTCTAGCCATTGCTCC
TCGAGTTCGATTCCTCAATAAAGCTCATAAGCAACGAGAGGAGGTGGCGGCGCAGGGGAG
CAGCACTGCTGCCGAGTGTGATTCTGATGAGGAACTCAAAAACTTCAAGGCCCAGCTCAG
ACCCAGCACCCACCTCTCCCAGTCTGAAAGTGAGGAGGACAGCGATGAAGAGGAGAAGGA
TGACGATGAAGAAGAAGAGGAGGAAGATGATGATGAAGAAGAAAAGAAGGTGAAGCCGGA
AGGTCTGTTTGCGGTTGATGAGGATGACGAGGAGGATGAAGACCTCAAGGACCTAGATCT
ACTGACGGTCAAACAAAAAGATGTGTTTAATGTCAACAATGATGAGACTGACCAAGAGGA
TGACGCAACCAAGAACAAGAAAGAGTCCAGATTCAAGGAGGCAAAGAAAATTCAGAAACG
ACAATTTAAAGTGAACACCAAGAAGATTTTCACGGATGAAGGAGAGGTGGTGCAGCAGTG
GCCTCCACAACAGAGGGCCATAGTGCAAGACGAAGAGGAGGAAGAAATGTCCGGTATTAA
CGTGGAGGCAGCCAAGGAGCGGCTACGCAGGGAGGACCAAGAATTTGATAAGAAGGAGTA
CAGCAGAAAGATTAAAGAGAAACACAGGGAGAAAAGGCTGAAGGAGAAGGCTGCACGAAG
AGAAGCCAACAAGCAGACAAAAGAGGCGAAGAAAGCTGCTGCTGCTGATGGTGGTGGTGG
TGGTGGCAATAACGACGACGACGACGACGATGATGANNNNNNNNNNNNNNNNNNNNNNCA
GGAGCTAATGATGAAGAGTTTGACCCCAGCACACTGCCTGACCCCGACAAAGTGCGAGAT
TCAGAGGATGATGAAGAAGAAGAAGAAGGTGCTCCTGAGTCCACCGGACGAAAGAGAACC
CACAGAAGCAGCAGCAGTGATGATGATGAGGATAACGATGAGGATGACTATGAGCAGTGG
GGCACAGGAAGGAAAAAGGCCAGGCAGCACTCTTCAGCAACCAGGCCTCTGGACACTGGC
CTCTCTTTGGCTGAGGATGAAGAACTGGTGA
>Melanotaenia_praecox_viscera_mixture_8|008680|scaffold13096|m.12203
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------GGCTTCGCTTTGCAAGGTAAAGATGT
TCTCGGTGCGGCGAAGACTGGCTCAGGGAAGACCTTAGCCTTTCTCATTCCGGTGCTGGA
ATGTCTTTATCGCCAGCAGTGGACCTCAATGGACGGCCTTGGTGCTCTCATCATATCTCC
CACCAGAGAGCTTGCATACCAGACCTTTGAAGTTCTTCGCAAAGTGGGCAAGAACCATGA
GTTTTCCGCGGGGCTGGTCATCGGTGGAAAGGACCTACAAACTGAGTCAGAGAGAATACC
CCAAACTAACATTGTCATTTGCACACCGGGCCGGCTGCTTCAGCACATGGACGAGACAGC
CTCTTTTCATGCCAGCAGTCTTCACATGCTCGTCCTGGACGAGGCAGACCGCATCCTGGA
CATGGGTTTTGCAGATACACTCAATGCCATTGT---------------NNNNNNNNNNNN
NNNNNNNNNNNNNGCCACACAGACCAAGTCTGTTAAAGACCTGGCCAGGCTCAGTCTCAA
AGATCCAGAGTATGTCTGGGTCCATGAGAAAGCCAAATTCAGCACGCCAGCCACCTTGGA
GCAAAGCTATGTGGTGTGTGAGCTTCACCAAAAGGTAAACATGCTTTACTCATTTATAAG
AAGC--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------
>Pantodon_buncholzi_mixed|005149|C637770|m.37003
ATGACCGGAAACACACAGGGCACACGACCCTCTGGCTCTGCGCCGAAAAAGCAGACGTCA
AAGAAAACTGACACTAAAG----------------------CTG---------CTGTGAA
AAACTTTGATAATTGGAAGAAAAAATACGACAAGACTAAAAAACGCGTGAAATTCGAGAA
AAAA---CGGGTGAAGAAGCCTGAATGGCAGCTCGAGAGGGCTAATATCCA---------
---------------GAGACTGGTGGATAGGTATTCCGAGATTAATCCTGTGGATGTTGT
GAGGTTTTCAGATTTTCCGTTATCGAAGAAGACGCTACAAGGATTGTTGGAAGGCCAGTA
CCGACATCCCACTGAAATACAGAGGCAGACCATTGGGTTTGCTTTAAAGGGAAGAGACGT
CTTGGGTGCTGCAAAGACAGGATCTGGAAAGACGCTTGCCTTTCTCATTCCAGTGTTGGA
GTGCTTGTTTCGGCAGCAGTGGACAGCAGATGATGGCCTGGGAGCCCTCATCATCTCACC
CACACGTGAGCTGGCCTTTCAGACGTTTGAGGTTCTGCGCAAAGTGGGCAAGAACCACGA
GTTTTCTGCTGGCCTCATCATTGGTGGAAAGGATCTGAAATATGAATCAGAAAGGATCCA
CCGCACCAGCATCATCATCTGTACACCTGGGCGCCTGCTGCAGCACATGGATGAGACCTC
TACCTTCCATGCCTCTAGCCTTCAGGTTCTTGTTCTGGATGAGGCAGATCGTATCCTCGA
TATGGGGTTTGCAGACACTTTGAATGCCATTGTGGAGAACCTCCCAAAGACCCGTCAGAC
TCTGCTGTTCTCTGCCACCCAGACAAAATCTGTGAAAGATTTGGCCAGGCTAAGCCTGAA
GGACCCCGAGTACATCTGGGTCCACGAGAAGGCCAAGTTCAGTACCCCAGCG--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------
>Sargocentron_rubrum_gill_6|012252|scaffold19752|m.23905
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------AACGCCAAGGACGCTGT
CAAGTTTTCGGATTTCCCCATTTCCAAAAAGACGCTGCTGGGTTTGCAGGAGGCTCAGTA
CCGTCAGCCCACGGAGATCCAGAGGCAGACAATCGGCTTCGCTCTGCGGGGGAAAGATGT
GCTCGGTGCGGCCAAGACCGGCTCCGGCAAGACTCTGGCCTTTCTTATCCCCGTGCTAGA
GTGTCTGTACCGGCAGCAGTGGACCGCCATGGACGGCCTGGGCGCCCTCATCCTCTCCCC
CACCAGGGAACTCGCCTACCAGACCTTCGAGGTGCTCCGCAAGGTAGGCAAAAACCACGA
GTTCTCCGCGGGGCTCGTCATCGGCGGTAAGGACCTGAAGAGCGAGTCGGAGCAGATTCA
CCGCACCAACATCGTCATCTGCACGCCGGGCCGGCTGCTGCAGCACATGGACGAGACCGC
CGATTTCCACGCCTTCAGCCTTCACATGCTGGTGCTGGACGAGGCCGACCGCATCCTGGA
CATGGGCTTCGCCGACACCCTCAACGCCATCGTGGAGAACCTGCCTAGGACGCGGCAGAC
GCTGCTCTTCTCGGCCACGCAGACCAAATCGGTGAAGGACCTGGCCCGGCTCAGTCTCAA
AGACCCCGAGTACGTGTGGGTTCACGAGAAAGCCAAGTTCAGCACGCCGGCCACGCTGGA
GCAGAGCTACGTGGTGTGTGAGCTCCACCAGAAGGTCAGTATGCTCTACTCGTTCATCCG
GAGCCACCTGCAGAAGAAGGTGATCGTCTTCTTCGCCTGCTGCAAGGAGGTGCAGTACCT
TTTCCGGGTTTTCTGCCGGCTGCGGNNC------------------CTGCACGGCAAGCA
GCAGCAGATGAAGAGGGTGGAGGTCTACAACGACTTCATCAGGAAGAAACACGCCGTGCT
CTTCGCCACGGACATCGCCGCCAGAGGCCTGGACTTTCCCGCTGTGAACTGGGTGCTGCA
GTTCGACTGTCCGGAGGACACAGACACCTACATCCACAGGGtgggCCGGACCGCCCGCTA
CAAGGAGGGCGGGGAAGCCCTGCTGGTGCTGCTGCCGTCCGAGGAGGAGGGCATGGTGGC
TCAGCTCCAAGCCAAGAAGGTCCCGATCAACAAAATCCAGGTGAACCCAGACAAACTGCA
GAATGTGCAGCAGAAGCTACAGGCCTTCCTGGCACAGGAGAAGGAGCAGAAGGAGCGAGC
ccagaGGTGCTTCGTCTCCTACCTGCGCTCCGTCTACCTGATGAAGAACAAAGACATTTT
TGATGTGTTCAAGCTCCAGATTCATGAGTACGCCCTTTCCCTCGGCCTGGCCGTGGCTCC
AAGGGTTCGCTTCCTGAGCAAAGCTCAGAAACAGAGAGCCCAGAGGGAGGAGCCAAG---
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------AGAGGA
AGAGCCGTCCGAGGACGAGGCGGAGCT---------------------------------
---------------------GAAGAGCTTCACG--------------------------
------------------------GCAAAGCTAAGAGGAGAG------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------GATCCTGGTGTTGG
GAG---------------------------------------------------------
-----------------------CCCAAGCATG---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------
>Scleropages_formosus_red_gill|009498|scaffold13983|m.18158
ATGAG----------------GGGCGAGAC---------------GAAAGGAAGACGGCA
GAGCGGAAATGCGCCGAAGGAGCGCGCGGCGGCGGCACAACAAAGCCGCGACCCGGTGGA
GAACTTCGAGAAATGGAAGATAAAGTACAGCCGGACCAAGAGTCGCGTGAAACAGCAGAG
GAAG---CGGAACAAGAAGCCCGAGTGGCAGGTGGAGCGGGACAACATCGG---------
---------------CAGACTGCTCAATAAGTATTCCGAGATGAACGTCCAGGATGCGGT
CAAGTTCTCCGATTTCCCCCTGTCGAAGAAGACGATTGGCGGACTGCTGGGGGCGCAGTA
CCGACAGCCCACCGAGATCCAGCGACAGACCGTCGGCTTCGCCCTCCGGGGCCGGGACGT
GCTGGGAGCCGCGAAGACGGGATCCGGAAAGACTCTGGCCTTCCTCGTTCCCGTTCTCGA
GTGTCTCTACCGGCAGCAGTGGACGGCCGAGGACGGCCTGGGGGCGCTCATCATCTCGCC
TACCCGGGAGCTCGCCTACCAGACCTACGAGGTGCTGCGCAAAGTGGGCAAGAACCATGA
GTTCTCCGCGGGCCTCATCATCGGGGGAAAGGACCTGCAGAACGAATCGGAGAGGATCCA
CCGCACCAACATCATCGTGTGCACGCCGGGCCGCCTACTGCAGCACATGGACGAGACGTG
CACCTTCCATGCGTCGAACCTGCAGATTTTAGTTCTGGACGAGGCCGACCGCATCCTGGA
CATGGGCTTCGCGGAGACGCTCAACGCCATCGTGGAGAACCTCCCCAGGACACGGCAGAC
GCTGCTCTTCTCCGCCACGCAGACCAAGTCGGTCAAAGACCTGGCGCGGCTCAGCCTCAA
GGACCCTGAATACGTGTGGGTGCACGAGAAGGCCAAGTTCAGCACCCCCGCAACACTGGA
GCAGAGCTACGTGGTCTGCGAGCTGCACCAGAAGGTCGACCTGCTCTTCTCCTTCATGAG
GAGCCACCTGCAGAAGAAGGTGATCGTGTTCTTCGCCTGCTGCAAGGAGGTGCAGTACCT
GTACCGGGTGTTCTGCCGGCTGCGCCCCGGTATCCCCGTCCTCGCGCTCCACGGCAAGCA
GCAGCAGATGAAGAGGGTAGAGGTGT----------------------NNNNNNNGTGCT
CTTCGCCACCGACATCGCCGCCAGGGGTCTAG----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------
