>Amblygaster_clupeoides|039345|TR65884|c3_g1_i2|m.93861
ATGATGAATAACGCGCAAGATATGTCTCCCGATTTTGTGTTGATGCGCTTGGTATCTGCA
GCGGAATATGACCGTGTAGACGAGGAGAATTTGTTGACGGGGAGCGGAGTGGTTTCCGGA
TTCGGGAAAGCAGC---TTTGGGTCATCAT----GGCAACAACATCACCA----------
----------------------GTGGGTTTGAGTTGGACCCCGCTAACCCC---TCCGCA
GGCCCGGCTTGCCAGACCAATCCCTCCCCGCACTGTAGTTCGCAACCAGAGAGCGGGACA
GCAGCGCTTGACAGCGGC------GTAATGCTGACTCGACCCTCGCTGTCTGATACGCCA
CCGCCGCCCGACTTTGCCGTGGCCCAGCGCTTCGAATTCCCACACACGGGGGGCCGAGGC
TCGCGCGCACAGCTCATGGTTTTTCAAAACCTCCTAACGACCGGAGA-------AGGACT
CGAGCCGTCCGGTTATCAGACAGGCGACAA-CGACACGCAGGACGGCAGCAGCACAGGTG
TGTCAAACGGCGGCGTCGATGACAGTTCGAACTACGGCATAAGCGCACATCAGAGAATAC
CCTCACAAAGGCTCCAGTGGCACCCAGTCATGCAACTCACCAAGGTAGCAGTGGAAGGCA
GCGACTTCCCCATGGGAAGAGGAGGTCTCTGCCACAGGCACCATTTAGTTACTGATACCA
TGGACTGGCCTCCTTTACTAGACAAATCCTTGCAGTTTGGCCTGCTGGACCCACGTAAGG
TCTGTACTGT---GGCAGGGAGTGAACACCACAGGGAGGACCCGGTGCTGAGCCTGGCCC
GACGTCTGGGGGAGCTGGGCCAGGCCTCGGAGAAGCTCCTGAAGGATGGCGAGCCGTTGC
GCTGTTCCTGCCAGAGCGTCCTGGCGTCAGCCACGGCGGGCATGAGGCCCGGAGAGGACC
CGAGTGAGACCAGCGATGCGCTCCTGGTGCTGGAGGGCCTGGGCTCGTCAGAGGTGGGCG
AACTGGCCATGGGCGGGTGCCCGTGCCCCGGTCCGGACGGATTCAAAGGAGAACCAGGGG
CCCAGTCAGGTGGGAAGGAGGGGGAGCCGGATACGGGGCAGGAGGGGGCGACGACGCCGA
TGACCATGACGACCATGACGGTAGCTGCGGCAACGGCCACCTTCTCCAGCAGCTCTCTGA
GCGGCCTCATGCAGCAGGTGCAGAGACTGGCTGCGGCTGGGGCAGCGTTGGGGGCTGACG
CCCGCTGTGACCCACAAACATGCCGCCCTTCCCTCCCAGACACCC-CCAGCCCCTCAGCC
TCGCTGGCACCAGATGCCTCCTGCTCCTCTATGCTTACTTCGGAAGTGTCATCCGTCGCC
ACCGCTGCTGCTGCTGCAGTACCAGCAGTGGAGCCCCGTCAGCCCCTGGACACGACCCCT
TCCCCACCCACCCCTACCCCCACCCCTGCGGCCCACACACCGCTGAGCCGACCCCCCACA
CCCAAACGTATTGGTTCCCCAATGGCTGTGGCGGCGTCCCTGGGCAGCGCCACCTTGGCC
AGCGGCAGTGGAGGCGCCCTCGGCGAGAGCCAGAAGAGCCGGGGGAAGTCGAGGAAA---
GGCTCCCTGAAGATCCGTCTCAGCAAACTCTTTCGCACCAGGAGCAGCGGTGCAGGAGTG
GGCAGCGCGGCGGGCACCTCGGGGGCCAGTGGCGGTGGGGGCAGTGGGGGCCCCAGCCCT
CTCCTGGACAAGCGTCCCTCCCTGGCCTCGTCCACGTCCTCTGGGGGCAGCCTGATGGAC
GTGTGGGGTTCGTCCAGCGCAGAACCCGAC---GCTGGCAGCAGACCCCAGCTGTCGAGG
CCCCAAAGTGCCTTTTCCCCTGTGCCCTTCAGTCCTGCCTTCACTGACGACTTCGGAGGG
CCCCAGCCCGGAGCGTCCCTGGACAA---CGTGGTGGGGGCGTCCATGCAGTCGCTCCCC
CTAAG------GGCTCCACCTCCTTCCCACGCCATCATCCAGCACAGCCTCAGCCTCAAC
GACACCTTCCTCAGAGGACTGCCGCGGCCCATACCCCTGGTGCCAGAAGGTCCAAACTCG
GCCCGACACGAGCAGCGTCCCACTCTGTTTCCGCTGAGCCGGCCCGACGCAAACAGCTTC
GCCACCAGTCTGAGAGAGCTGGAGAAGTGTGGCTGGTACTGGGGCCCCATGAACTGGGAG
GATGCTGAACTGAAGTTGAAGGGGAAGCCAGACGGTTCCTTCCTGGTGCGGGACAGCTCT
GACCCACGCTACATCCTCAGTCTCAGCTTTAGGTCGCAAGGAGTCACACACCACACACGC
ATGGAGCACTACAGAGGGACCTTCAGTCTGTGGTGCCACCCCAAGTTTGAGGACCGCTGC
CATTCAGTGGTGGAGTTTATCGAGCGTGCCATCATGCACTCCAAAAACGGAAAATTCCTA
TACTTCCTACGCTCTCGTGTACCAGGGTTGCCGCCCACACCGGTGCAGCTGCTGTACCCA
GTGTCCCGGTTCAGCTCAGTCAAGTCCCTCCAGCACCTGTGCCGCTTCTGCATCCGCCAG
CTAGTGCGCATCGACCACATCCAGGAGCTGCCGCTGCCTACGCCTCTGATTGAGTACTTG
AGGAAGTTCTACTACTACGACCCTGAGGAGGAGATGTACATGTCCATCAGAGACGCGAGG
CGGAACACTAGCACTGCACCGCCTACTGAGACGCAGACGTAG
>Corydoras_julii_viscera_mixture_8|004118|C1239810|m.29373
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------GAGATGAAGCTAAAGGAGAAAGCTGACGGTTCGTTCCTGGTACGAGACAGTTCA
GATCCACGCTACATCCTCAGTCTGAGCTTCAGATCACAGGGGGTTACACATCACACACGC
ATGGAGCATTACAGAGGTACATTCAGTCTGTGGTGCCACCCAAAGTTTGAGGACCGCTGT
CACTCCGTGGTGGAGTTTATTGAACGTGCCATCATGCATTCCAAAAATGGACGCTTCCTT
TACTTCTTGCGCTCTAGAGTTCCTGGTCTCCCCCCGACTCCAGTGCAGCTGCTCTACCCG
GTGTCTCGCTTCAGCAGTGTCAAATCTTTGCAGCATCTCTGTCGCTTTTGCATTCGACAG
CTTGTTCGCATCGACCATATTCAGGAGCTCCCACTGCCCACGCCATTGATCTTGTACCTG
CGTAAGTTTTATTTCTATGATCCAGAAGAAGAACAAAACCCAACAGTCAAAGATTCAGGG
CGGGACTCTAGTGC---ACAGGAGACGGAGTCTCAGACGTAG
>Distichodus_sexfasciatus_gill_4|006726|C916151|m.55257
------------------------------------------------------------
------------------------------------------------------------
------------------------CATCATCATCAACATCAACATCATCATCATCATCAT
AATGGCCACAACCTGGGCGGCAGTGGGTTCAAATGTGACGAGGGTAACTCCGTTACCTCG
GGCCCGGA----------------------CGCTCCAGCTCA-------TATGCAAGACA
GCGGCGC-CGAAAACGGCGCGGCGGCGACGATGATTACGACCACGACGTCTCACACGCCT
TCGCC---------------------------CGACTTCCC---------------CGGT
TCGCGAGCCCAGCTGATGGTGTTCCAGAACCTGCTCCGAGCCGGTGA-------CCGGGT
TCTGGAGTGCGGCCTGGAGAAACCCGACAAGCAGGAGGTGGGGCTTCAGC----------
---------------TGGTCGACAGCTCTAACTACGACTCGGACCCGCACCCAGGACGGT
CGGTGCAGATGCTTCAGTGGAATCCGGTTCTCAGACTCACTAAGGTGGCCGTA-------
--GATTTGCCCGAGAACCGGGAAGGTCTGTGCCAGAGACACCGGCTCATCTCGGATACTG
TGGAGTGGCCGCCCCGAGTGGAAAAAAGCTTTGGGTTTGGGACGACGGACCCCCACAAGC
CCTTAACGGCAGGTGCTCCGGTTAAAGCCGAC------GATCCGGTTCTGAGCCTGGCCC
GGAGGCTGGGAGAGATGGGTCAAGGGTCAGACGTTTTGCATAAGGACGGTGACGCCCCGC
TCTGCTCCTGTCAGAGCATCCTGGGTTCGGCC---GGTAGCGCCCACCCAGGAGATGACC
CGAGCGAGACCAGTGATGCCTTGCTGGTACTGGAGGGTCTTGGTACAGATGAGGTG----
-GCTGGGCTCGAGCGGGGTGACGCCATTC----------------AGGGCGAGACGGCGG
GCCAGGCGTTTGGGCAGAAAAGCGACT------------------------CCATGACTC
CGTGCCGAGAGCTCACCGCGGGAGCCAGCCTGCCATCTGCCTTCTCGTCCAGTTCTCTCA
GCGGCCTCATGCACCAAGTACACCGCCTGGCAGGA---------------------GAGG
CCTGCTGCGAG-----------------------ACCAGACCC-------AACCACAATG
GGATGGACACTAGAAGCCC------------------GGGCGATACCTTAATCCGTC---
----------CTGCTCCGGTAC---------------TTTCGACCCAGGGCGCGG-----
-------------CTGTGACTGCAGCCCCTGTCTCTGCCCCTCTTAGCCGACCTCCCACG
CCCAAGCATGTTGGATCTCCACTGGCCCTGTCAGCTT---------------------GT
GGCAGCAGAGAAGTCGAGCGAGG------------CAGTCGGGCAAAGTCCAGAAAG---
GGCTCGCTGAAGGTGTGCCTCAGCAAACTCTTTCGCACCAAAAGCACCAGC---------
------------------------------AGTGGCAATGTCCCC------------CAC
ACAGCTGACAAGAGGCCATCGCTGGCCTCCTCCACCTCCTCTGGGGGCAGCCTCGTGGAT
GTGTGGGCCTCCAGCGGACCCGAACCGGAC---ATGAGCAGCAGACCCCAGCAGGCCCGG
CCCAGAAGCGCCTACTCACCTGTTC------------CCTTCACCGATGACTTTGGTGGA
CCACAAACTGGACGTCTACT------------------GGCATCCATGCAGTCACTACCA
ATCCGGCCG--AGCGCTG----CTTCACATGCTGCAATACAACACAGCCTAAGTCTTAAT
GACACCTTTCTGCCCGGCATCCCGCGGCCTCTCCCTCTGCAGCCTGATAGTCAGTCAGCT
GACCGGGTGGACCAGCGCCCCCTACTGTGTCCTCTGAGCCGACCCGACGCCAGCAGCTTC
GCCACCAGCCTCCGAGAGCTGGAGAAGTGTGGATGGTACTGGGGACCCATGAACTGGGAG
GATGCTGAGATGAAACTGAAGGGGAAACCAGACGGCTCCTTCCTGGTGCGGGACAGCTCT
GATCCACGCTACATCCTCAGCCTCAGCTTCCGCTCACAGGGCGTCACACACCACACACGC
ATGGAACATTACAGAGGAACCTTCAGCTTGTGGTGTCACCCCAAATTTGAGGATCGTTGT
CACTCTGTGGTGGAGTTTATTGAACGTGCCATTATGCACTCCAAGAACGGCAGGTTCCTC
TATTTCCTGCGCTCTCGGGTTCCAGGGTTGCCCCCTACTCCTGTACAGCTCCTGTATCCT
GTGTCCCGCTTCAGCAGCGTTAAGTCCCTACAGCATCTCTGTCGCTTCTGCATCCGACAG
CTCGTCCGCATAGACCACATTCAGGAGCTCCCCCTGCCTACACCCCTGATAGTGTATTTG
AGGAAGTTTTATTTCTATGACCCCGAGGAGGAGAAGTACCTGTCACACAAAGAGTTGGGA
CGGGACACTGGTGCTACACAGGAGGCGGAGTCTCAGACGTAG
>Gasteropelecus_sp._gill_3|020033|scaffold31776|m.34355
ATGATGAGCGGAGCGCGGGACGCGTCTCCCGATTTCGTGCTGATGCGTTTGGTTTCGGCC
ACGGAGT------------ACGAAGAAGATCCG---------------GTGCGTTCAGGG
TTGGGCAAGACGGGGCATCTTCATCATCATCTCCAGCATCACCACCATCATCACCACCAT
Catcaccaccac--------------------------caccaGCATCTCCAGCATCTCC
AGCATGGC----------------------CTCGGTGGCTCAGAGCT--CGAGCGAGACG
GCCGTTC-----------------------------------------------------
--------------------------------------------------------AGAA
GCGGGTGGTCAACTCATGGTCCTGCAAGACCTCCTGGGTCCAGGTGACCCTGGTCCGGGC
GCACCTGCAGGTCCAGGAGACCCGGGAGAG-CA---------------------------
----------------------------GAACTGTGGTGTGGATGCTC------------
CAGTGAGCAGGTTTGAGTGGAGTCCCGTCTTCAGCCTCACAAAAGTGTCCAGG-------
-----------GAGGTCTCGGAGACCCTGTGTCAAAGGCATCGCCTTATCTCGGACACTC
CGGAGTGGTCACCCTTAGCAGACCA----------CCTGGCC--ACTGGTTCTCATAAGC
CTCCTAATGC---TGCTGCGGTGGCGTCCGACCTGCAGGACCCCGTCTTGAGCCTGGCCA
GGCGGCTCGGGGAGCTAGGCAGGGG---GGATGTCTTGCAGAAGGACACGGATGTTCCCC
TGTGCACCTGCCAAAGCATCCTGG---------------GAGCCCAGCCTGGGGAGGACC
CAAGTGAGACCAGTGATGCTTTGCTAGTTCTTGAGGGTCTGGGGGCACAGGATGTG---G
AGTCGGACAAGGCTGGCATGGTGGGCTCC---CAGGACGGGTCAGAGGGTAGTGCCGGGG
CTCAGGCGTTTCCCCAACAGGGTGA--------------------------TGGTCACAC
CAGTCAGGAACCTCAGAA----------------------CTTCTCCAGCAGCTCCCTCA
GTGGACTCATGAACCAGGTGCACCGTCTGACCCAG---------------------GAAG
CCTGCTGCGAC-----------------------CCTGGACCTCCAGCAGAACCTGACGG
ATCCAGACTCCAGA----------------------------------------------
-------------------------------------CTCCAGTCCAGGATGCAG-----
----------------------TGGCTTCTGCCCAGGCCCCGCTGAGTCGACCCCCCACA
CCCAAACACGTTGGTTCACCCCTGACCTTTGCGGCCT-----------------------
-GCAGCAAGGACAGGGACAGAGG------------CAGTCAGAGGAAGTCGAGGAAA---
GGTTCACTGAAGGTGTGCCTGAGCAAACTGTTTCGCACCAAAAGCAGTGGC---------
------------------------------AGTGCAGGCAGCAGCTCCAGCTTGGGACAC
CCCACCAACAAGAGGCCCTCGCTTGCCTCCTCCACGTCATCTGGGGGCAGTCTGGTGGAC
GTGTGGGGCTCTAGCAGCACTGATCCTGAC---ATGGGCAGCAGATCTCAGCTGGCCAGG
CCTCAAAGTGCCTACTCTCCTGTAC------------CCTTCACAGATGATTTTGGAGGC
CCTCAACCTGGATGTTCACTCTCTAC---TGGGGGCGCAGTGTCCATGCA----------
-----------AACTCTGACACATACACACACCACCATCCAGCACAGCCTCAGCCTCAAT
GATTCATTTCTTCGCATTGTCCCAAGGCCCCTCCCTCTCCAGCCTAATGGCCAATCAGCT
GCAGCAGTTGAACAGCGCCCCTTGCTGGTCCCTCTCAGCCGGCCAGACTCCAGCAGCTTT
GCCACCAGCCTCAGAGAATTGGAGAAATGTGGCTGGTACTGGGGACCAATGAACTGGGAG
GATGCTGAAATGAAGCTGAAAGGGAAAGCAGATGGATCCTTCCTGGTGCGGGACAGTTCA
GATCCAAGATACATCCTCAGCCTCAGCTTTCGATCCCAGGGTGTCACACACCACACACGG
ATGGAGCACTACAGAGGAACATTCAGCCTGTGGTGTCACCCCAAGTTTGAGGACCGCTGT
CACTCTGTGGTGGAGTTTATTGAGAGGGCCATCATGCACTCCAAAAATGGACGATTTCTC
TACTTCCTGCGCTCTCGCGTTCCTGGTCTCCCGCCCACTCCAGTACAGCTGCTGTACCCA
GTGTCCCGCTTCAGCAGTGTTAAATCTTTGCAGCACCTCTGCCGCTTCTGCATCCGCCAG
CTTGTGCGCATTGACCACATCCAGGAGCTGCCTCTGCCTACACCACTGATAATGTATTTG
CGGAAATTTTACTTCTATGACCCTGAGGAGGAGACATACCTGTCAGTCAAAGACTCAGAG
CGAGACAGCAGCGCCACACAGGAAGCAGATGCTCAAACGTAG
>Melanotaenia_praecox_viscera_mixture_8|004600|C450288|m.30901
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------GAGAAGAC-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------GTCTCGGGGGAAGTCCAGGAAAGGG
GGGTCCCTGAAGGTCCGGCTTAGCAAGCTGTTCAGAACCAAGAGCTCCAGCGGGG-----
------------------------------GGTCGGGGGGGCTGC---------------
----TGGACAAGAGGCCGTCCCTGGCCTCGTCCACCTCGTCTGGGGGCAGCCTGCTGGAC
GTGTGGGGGTCCACCAGCAGCAACAATGACCAGGACGGCAGCAGGTTGCTGCCGTCCAGA
CCTCACAGTGCCTTCTCTCCGGTGCCGTTCACGCCAGCTTTCACCGATGACTTCGGAGGT
CCTCCGCAGCAGGGTCCCTTCGTGGAGCGCGGCGTGGGGGCTTCCATGCAGTCCTTGCCC
CCCCGACCAATGGCCCTGCCCCCCTCCTTCAGCAACATCCAGCACAGTCTGAGCCTCAAC
GACACACTCCTGCGAGGTTTACCCCGCCCAGTTCCTCTGCGGCCTGATGGGCA--CCACC
CCCCACCCCGACTCGCGCCCCGC----TGCCCGCTCAGTCGACCCGACGCTGGCAGCTTC
GCCACCAGCCTCAGAGAGCTGGAGAAGTGTGGATGGTACTGGGGTCCGATGAACTGGGAA
GACGCTGAGATGAAGCTGAAGGGAAAACCCGACGGATCGTTTCTGGTCCGGGACAGTTCT
GATCCTCGATATATTCTGAGTCTGAGCTTCAGGTCGCAGGGCGTCACCCACCACACACGC
ATGGAGCACTACCGAGGGACCTTCAGTCTGTGGTGTCACCCGAAGTTTGAGGACCGCTGT
CACTCCGTGGTGGAGTTCATAGAGAGAGCCATCATGCACTCCAAGAATGGAAAGTTCCTC
TACTTCCTGCGCTCCAGAGTCCCAGGTCTGCCCCCGACTCCGGTCCAGCTCCTGTACCCG
GTGTCCAGGTTCAGCAGCGTGAAGTCTCTGCAGCATCTGTGTCGGTTCTGCATCAGACAG
CTGGTCCGGATAGACCACATTCAGGAGCTGCCTCTGCCCACGCCTCTGATCGCCTACCTG
AGAAAGTTTTATTACTATGACCCCGAGGAGGAGATCAGCCCTACGCTGCCGGAGCGAGGG
CCGGAACGAGG------------------------------A
>Sargocentron_rubrum_gill_6|007764|scaffold13484|m.15375
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---ACCAGCCTGCGGGAACTGGAAAAGTGCGGCTGGTACTGGGGTCCGATGAACTGGGAG
GACGCAGAGATGAAGCTCAAGGGGAAACCGGATGGCTCCTTCCTGGTGCGGGACAGCTCC
GACCCTCGATACATCCTGAGCCTGAGCTTCAGGTCGCAGGGAGTCACACACCACACACGC
ATGGAGCACTACCGGGGTACCTTCAGCCTGTGGTGTCATCCGAAGTTTGAGGATCGTTGC
CACTCGGTGGTGGAGTTTATCGAGAGAGCCATCATGCACTCCAAGAACGGAAAATTCCTC
TACTTCCTGCGCTCCAGAGTGCCCGGTCTGCCCCCCACCCCGGTCCAGCTCCTGTACCCA
GTGTCCAGGTTCAGTAGCGTCAAGTCGCTGCAGCACCTCTGTCGCTTCTGCATCAGACAG
CTGGTCCGCATCGACCACATCCAGGAGCTGCCCCTGCCCACGCCTCTGATCATCTATCTG
AGAAAGTTCTACTACTACGACCCCGAGGAGGAGATGTACCTGTCAATCAAGGAGAGGGGG
CAGGACCAGAACACCCAGCCGGGGGTGGAGTCTCAAACGTAG
>Synodus_sp._gill_5|008561|scaffold11483|m.13060
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------TGGGGGCCCATGAACTGGGAG
GACGCAGAGATGAAGCTGAAGGGCAAAGCGGACGGGTCCTTCCTCGTACGGGACAGCTCC
GACCCCCGATACATCCTGTCCCTCAGCTTCAGGTCACAGGGCGTCACACACCACACGCGC
aTGGAGCACTACAGAGGTACCTTTAGTCTATGGTGTCATCCTAAGTTCGAGGACCGCTGT
CACTCTGTTGTAGAGTTCATAGAAAGAGCCATTATGCACTCCAAGAATGGGAAATTCCTC
TACTTCCTGCGTTCCCGCGTCCCAGGCCTTCCCCCTACCCCAGTCCAGCTGCTCTACCCA
GTGTCCCGGTTCAGTAGCGTCAAATCTCTGCAGCATCTCTGCCGCTTCTGCATCCGACAG
CTAGTCCGCATCGACCACATCCAGGAGCTGCCACTCCCCACACCGCTGATCATGTACCTA
AGGAAGTTTTACTACTACGACCCTGAAGAGGAGATGTATCTGTCAATCAAAGGAAGAGGG
CGGAGCCAGAGCAGCCAGCCAGGGGTGGGCTCTCAAACGTAG
