>Amblygaster_clupeoides|009449|TR19561|c0_g1_i1|m.38039
------------------------------------------------------------
------------------------------------------GGCGGTGCGCTTCAGCCT
CCACCCCCTGCCGGGGTGGGCTCGGAGCAGCAAGGCATGCTGGAGCAGCTGGGACAGACG
CAGGTGGTGGGGGGCCCCCAGCAGGTGGCGCTGCAGGCGTCGTTGACTGAAGAATCCCTG
GTGCAGGACGATGACCAGTTTGTGGCGCCGCAGCACCCCCTCCAACAGAACATGGGCCAG
TATGATGCTTCAGCCCTGCCTCAGCCGGCCTATGACCAGCCTGCACTCTCTCAAGGTTTC
ACCATAGCTGAGGGCTTCAGTGCGCCTCCCCAGTTCTCCACAGTCCAACAGCTGCAGGAC
TCCAGCACGCTTGAGTCACAGGCCCTCTCCTCCAGCTACCACCCACAGAACCTGCTGCAC
GTGTCCAATGCTGAGGT----GGCTGGTGGTCTACTGCAGGACCCACCCCAAGGGGAACT
CCAACTATCCACCAGA---CAAGACTACCAGGATGA---GGGGGAAGAGATCAAGAGGGC
CTACAGGTGTAACATCTGCAGTAAAGGCTTCAAGAAGTCCAGTCACCTGAAGCAGCATGT
GCGCTCGCACACGGGCGAGAAACCTTACAAGTGTAACATGTGTGGCCGCAGCTTCGTCTC
GGCCGGGGTGCTCAAGTCCCACCTCAACACGCACACAGGACTCAAAGCCTTCAAGTGCAA
CGTGTGTGACGCCTCCTTCACCACGAACGGCAGCCTGAACCGCCACACGATCATCCACCT
CAACATGAAGCCCTTTAAGTGTCCCATGTGTGTCGAGACCTTCAGGACCAACCTGCTGTG
CAGGAAGCATCTGAAGAAAGATCATGCCGTTGGGTCCAGAGTGCTGGG---------GGA
GGAAGAGGGTGAAGAGGAGGACGGTTA------CGGTCGCTCTGGCACCAAAAGGAACCG
GGCCGGCATCATCACCTTCACCGAGGAGCAGGCCGCCGAGTTGGCCAAACAGGAGCCGGG
CGACGGGGCGTCGCTGTCGGAGAAGGTCCTGGCCCAGTCGGCCGCCGAGCGCGACCGCAT
CAGTGAGATCAAGGACAAGGCTGTGGAGCTGGAGACTGAGCCCAAGTTCGCCAACCGCTG
CACCTACTGTCCCAAGAGCTTCAAGAAACCCAGCGACCTCGTCAGGCATATTCGGATCCA
CACAGGAGAGAAACCTTACAAGTGTGATGAATGTGGCAAGAGCTTCACGGTGAAGTCCAC
GTTAGACTGTCATGTGAAAACACACACAGGTCAGAAATTGTTTGGCTGCCACATGTGCCA
CACATCCTTCTCCACCAAAGGCAGTCTGAAGGTGCACATGCGTCTGCATACGGGCTCCAA
GCCTTTCAAGTGCCCCATCTGCGAGCAGCGCTTCCGCACCTCCGGCCACCGCAAGACGCA
CATCCAGAGCCACCTGCGGCCCAGCTCCGAGGGCAAGAGAGCCAAGCGCAGCGCAGGGTC
TGGCTCCTCATCCAGTTCAGACCGCCAGGCGGCCAGGCACCAGGCCTCGGAGGGCGACCC
GAGCCAGGCCGCCGGCCAAGCCTCCCAGCAGTCCGCAGGAGGGCCGGCGCCGCCACCGAC
AGACACCCTGCCGCCCGTGGGCCTGCTTCAAACTACCGGCGCCGACCCAGGAATCTACAT
CCCCAGCACCTCGGTCCTCACGGGCCAGTACGACCACAACCTGCTGCAGCCCGGGCTGGT
GGGCCAGGCCATCTTACCCGCCACCATGTCAGCGGGGGGTGACCTGACGGTGTCTCTTGG
CGAGGGGCTGGCCACTCTGGAGGGCATCCATCTGCAGCTGACCCCCGCTAACATAGTGTG
TCCCAACGTTCAGATCTCTGGCATCGACGGCAGCAACATCAACAACATCACTCTGCAGAT
TGACCCCAGCATCCTGCAGCAGACCCTCCAGCAAGGAGGGCTCTTGTCCCACCCTGTGGC
TGGTGACCCGGGCCTTTCCCAGCACGCCGGCCCTCACCTCATGGCCACCGCCGACTCCTC
GGTGCCCGCCAACGTGGTCCTGCACCCTCTCACCAGCCTGTCGCTGCAGCCTCCCGTTGT
CCCCAGCAACGTCAGCATCACTGGCATGCCTGAGCAGGACACCTTAGGCTCTCAGGAGCT
GTCGCACGTGATGGGTGCCGCAGGGCTGGTAGCGGGCGCAGGCGGCAGCCAGGAGATCAC
GCTGACCATCAATAACTCCAGCCTCACGCAGGTGCTCGCCCACGCCCAGGCGCATGTCAC
CGGCGCCGTAGCCGCACCCTCGGCCAACAACACGCAAGAGATCACCCTCACCATATCAGG
GCAAGACCTTCTGCCTCAGCACAGCGCCCCCTCTGGAACAGACCTGAACAGCGGGATCAG
GCTGGCATCACCCATGGGCACTCAGGCCAATAGTGCCACCCTCACCATCGGCAATGAGCA
ACTGCTGCCTCACAGCCCATCTAACACCTCCATGACTGTCACCAGCCTGCCTCCCAGCAC
CTCCCTGTCACACACATCCGTGTCATCCCAGAGCCTGGTGATGTCATCAGCAGGCATGGG
CAGTGATGGGAGTGTGACTCTCACACTGGCAGACACCCAGATGCTGGATGCGGTAACACT
CAACCTGAATTCACAGCAAAGCCAGCAGTACCCCAGTGTGATGAGTGAGCAGGGGCTCCC
CGGGCAACCGGCCACCTCTACCCAGCAGGTCATTCTCGTTAGCCACCCCACCCAGACTAC
TGTGGCAACGCTGGAGGACAACCTCAGGCCAGAGAATAAGGAGGTGGAACAGAGGGAGAA
GCGTGTGTTGAACCAGTGCTACTTCTGCGATCAGGTGTTCGTCACAGCCAACATGCTGCG
GCGGCACTGCAGGCTGAGCCACGGCAAGGACCGCTGCCACGTCTGCCGCATCTGCAACAA
GGCGTTTAAACGCGCCACGCACCTCAAGGAACATGAGCATGTGCACCAGAATGGCCCATC
TCTGAGCTCCCAGAGGCCTCGCGTGTTTAAGTGTCCTTCCTGTGACAAAGCCTTCGCCAA
GCCCAGCCAGCTGGAACGACACAACCGCACTCACACAGGAGAGCGTCCCTTCAAGTGCAC
GCAGTGCGACCGGGCGTTCAACCAGAAGAGCGCGCTGCAGGTGCACCGCGTCAAGCACAC
GGGGGAGAAGCCCTACAAGTGTGAGGTGTGCAGCATCGGCTTCACCCAGAAGAGCAACAT
GAAGCTGCACATGAAACGCTCCCACGGATACGGTCGTCCCCAGCAGCAGGGAATCCAGCA
GCAGCAGCAGCGTCAACAGCAGTCGGAGGTGTGTGTGGAGGTCACCACTGGCGATGAGCA
TCAAGAGGAGGAGGACGATGAGGAG
>Distichodus_sexfasciatus_gill_4|015283|scaffold2295|m.2351
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------TTTGTGAGCTCTCAGC---------------ACATGAGCCAG
TTTGAGACGCCTGCTCTCTCTCAACCGACATACGACCAACCAGCTCTTACGCAAGGTTTC
TCTATAGCCGAAGGTTTTCCTCCTCAGTCTCGTCTCTCGGCTGTGCAGCAGCTGCAGGAC
TCCAGCACGTTGGAGTCTCAGGCTCTCACTCCCACTTACCATCCACAAAGCCTGCTGCAT
GTGGCTAACACCGAGGT----GACGGCGGGTTTGCTGCAGGAGGCGGGTGAGGGAGAGCT
GCAGTTGAGCAGACAGACGGAGGAGTACCAGGATGA---AGACGAGGGCAGCAGGAGGGT
GTACAGGTGCAGTGTGTGTGATAAGGGCTTTAAGAAGTCGAGTCACCTGAAGCAGCACAT
CCGCTCACACACCGGGGAGAAGCCGTACAGGTGTAACCTCTGTGGGAGGAGCTTCGTATC
CGCTGGCGTCCTCAAGTctcacCTCAACACACACACGGGAGTGAAGGCGTTTAAGTGCAA
CGTGTGTGACTCGAGCTTCACCACTAACGGCAGTCTGAACCGTCACATGGTGATTCACCT
CAAC--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Gasteropelecus_sp._gill_3|006669|scaffold10942|m.10131
GAGCA------CTCAATGGATGGGGCTAATGCAGTAGAAGACCCATTGGGTGGAACCAAT
GCCATAACACATGACCTACAGGTGGAGATGCAGGTGGGGCCAACAGGACTAACACAGTCC
TCTTCTGCCATGGGAGCAGA------------------------GCCTCAGGCCCTGCTC
CAGGTCGTGGCCAGTGGCCAGCAGGTGGCACTGCAAACACAACTAGGAGAAGGCACACTG
GTGCAAGACGCAGACACGTTTGTGAGCACACAGC---------------ACATCAGCGAG
TATGAAACACCAACAATTCCACAGCCTGTGTATAACCAGCAACCGCTGACTCAAGGTTTC
TCGATCTCTGAAGGTTTTT---CCCAGCCGCAACTCTCCACTGTGCAGCAACTCCAAGAT
TCCAGCACACTGGAATCACAAGCACTGAACTCAACATACCACACACAGAGCTT-------
---------ACTGACGCCTGAGGCAGCTAGTTTACTGCAGGAGACAGCTGAGGGGCAGTT
ACAGTTGAGCAGACGGTCAGACCAGTACCATGATGA------AGAGGAAAGCAAGAGAGC
CTACAGGTGCAACATGTGTGACAAAGGATTTAAGAAATCCAGCCACCTAAAGCAGCATGT
TCGCTCACACACTGGTGAGAAACCATACAGGTGTAACCTCTGCGGCCGGAGCTTCGTTTC
TGCAGGAGTGCTTAAATCCCACctaaacACACACACAGGTGTGAAAGCTTTTAAGTGTAA
TGTGTGTGACTCATCATTCACCACTAATGGCAGTCTGAATCGGCACATGATCATTCATCT
GAACACAAAGCCCTTCAAGTGCTCTGTCTGTGATGAAAGCTTCCGCACACACTTGTTACG
CAGGAAACACATGAAGCTTTTCCATGCTATCAGACCCAGAGTGCTGGA---------TGG
GGAAGAAGCAGGTGAGGAGGATTC---------GGATCATTCTGTGATGAAAAGGAGCCG
AGGTGGCATCATCACCTTTACAGAGGAGCAAACAGCCGAGTTGGCCAAGACGGAGCCTGG
GGACAATGCCTCTGTCTCTGAGAAGGTTCTGGTCCAGTCAGCTGCAGAGCGGGACCGCAT
CAGTGAGATAAAGGACAAAGCagtgGTTCTGGACCTAGAGCCCAAATTTGCCAACTGCTG
CCAGTACTGTCCAAAAAGCTTCAAAAAGCCCAGCGACTTGGTCAGACACATCCGGATACA
CACAGGAGAGAAGCCA--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Pantodon_buncholzi_mixed|009283|scaffold11710|m.14641
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------AACTTCTGCCACAAAGGCTTTAAGAAGTCCAGCCACTTGAAACAGCATGT
ACGTTCCCACACTGGGGAAAAACCGTACCGGTGCCAAATCTGCAGCAGAAATTTTGTCTC
GGCCGGAGTGCTGAAGTCACATCTCAACACACACACTGGTGTTAAAGCCTTCAGGTGCGA
CATATGTGACGCTTTGTTCACCACCAATGGGAGCCTGAACCGTCACATGACCATGCACCT
GGATATGAAGCCGTACAAATGTCCCATGTGCCCGGACACCTTTCGCACCAACCAGCTCTG
CAAGAAgcacgttaaaaaggaccacatgatctccgaagga------G------------A
GGAGCCTGCGGAGGAAGAGGTTCCCGAGCGAGGTGACCAGGCCTCCCTCAAACGCAATCG
CACAGACATAATAACCTTTACAGAGGAGCAGGCGGCGGAGCTGGCCCGCAACGAGCCCGC
GGACGACGCCTCTGTGTCAGAGAAGGTGCTGGTGCAG-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Sargocentron_rubrum_gill_6|008844|scaffold15069|m.17513
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------CAGGCC
GAGGTTGTGAGTGGAGGCCAACAGGTGACGTTGGAGGCACCGCTGACTGACCAGCCTCTG
GTTCAAGGAGAGGACTCCTATGTGACTACCCAGCATGCTTTGCCTCAGAATATCAGCCAG
TTTGAGACGCAGACACTTCCTCAGCCTGCCTTTGACCAGCAAGCACTAACACAAGGCTTC
ACCATCACTGAAGGCTACA---CTCAGCCCCAGTTCTCCACCGTCCAGCAGCTGCAGGAC
TCCAGCACCTTGGAGTCCCAGGCCCTGTCCTCCAGCTATCACTCCCAGAACCTGCTGCAT
GTGCCCAGCACCGAGGT----GACGAGCGGacttcttcagcagagcAGTCAGGGTGAGCT
TCATCTGACTGCTGAGACGCAGCACTTCCAAGACGACAGTGAAGATAACAGCAAGAGGGC
TTACAGGTGCAACTGGTGTAATAAGGGTTTCAAGAAATCTAGCCATCTCAAGCAGCATGT
ACGTTCTCACACTGGTGAGAAACCGTACAGATGTCATCTGTGTGGGCGAGCCTTTGTATC
GGCCGGGATGCTGAAGTCACACCTCAATACACATACAGGAGTGAAGCCCTTCAAGTGTAA
TGTCTGCGATGCCTCGTTCACCACCAACGGCAGCCTGAACCGCCACATGATCATCC----
--ACGTCAAGTCTGTCAAATGCTCCATGTGCGACGAGAGCTTCAGAACCAACCTGCTGTG
TAAAAAACATATGAAGAAGGAGCATGCTGTGGTGGACAGAATTATAGGCCTGGATAGTCA
AGAAGTTGATGATGATGAGGATGAAGA---CGGGGAGCAGAGGACGTCGAAGAGGAGGGG
TATAGACATCATTACTTTCACTGAGGAGCAGGCGGCTGAGCTGGCC---AAGGATCCCGG
TGAGGAGGCCTCGGTGTCGGAGCGGATTCTCGCCCAGTcagcggctgagagggatcggat
cagcgagatCAAAGACAAGGCCGTGGAACTGGAAACAGAGCCCAAATTTGCCAACTGCTG
CAGCTTCTGCCCCAAGAGCTTCAAAAAGCCCAGCGATCTTGTCAGGCACATTCGGATCCA
TACAGGCGAAAAGCCCTACAAGTGTGATGAATGTGGGAAAAGCTTTACAGTAAAGTCCAC
CCTGGACTGCCATGTGAAGACGCACACAGGTCAGAAACTCTTCAATTGTCACATGTGCAA
CACCTCCTTCTC---------------NNNNNTGCACATGCGCCTCCACACTGGCTCCAA
GCCCTTCAAGTGCCCCTTCTGCGAACTTCGCTTCCGCACCTCCGGCCATCGCAAAACCCA
CATCCAGTGCCACTACCGGCCCAACAGCGATGGCCGCAAGTCCAAGC----------GGT
TGGCTTCGTCTGCTGGTCAGGCCAGCCAG-GGCCAAGAGCCAG-----------------
AGACTGGGCAGCCNNNNNNNNNNCTGGGCAG-CAGCAGGCAGCTCA--------------
AGAGGCACTTCAGCCAGTGGGTCTGCTCCAGGCCTCCAACTCAGACCCCAACATTTACCT
CCCAGCCAACCAAGTCCT------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------GA
>Scleropages_formosus_red_gill|013852|scaffold21126|m.27576
GGAGACACCCCCTCCCTGGAGAGTGCCATTGGA---------------GGGGTAGCAGAG
GCCGCTACA------ATCCAGGTGGAGATCGAG---------ACCGATGCGCTGCAGCAG
CCCTCCGCCG---------------ATCAGCAAGGCATTCT---GGGACTGGCTCAGGCT
CAGGTGGTGGGCAGTTCCCAGCAGGGAGCGCTGCAAACACAGCTGACTAACCAGCCACTG
GTGCAAGAAGAAGATACACTTGTGTCATCCCAGCATGCTTTGCCTCAGAACATCAGCCAA
TTTGAGATGCAGACGCTTCCCCAGCCATCGTTTGACCAGCAGACACTAACACAAGGCTTC
CCCATGACAGATGGATTCACTCAGCAGCCCCAGTTCTCAACAGTTCAGCAGCTGCAGGAT
TCCAGCACCCTAGAGTCACAGGCCCTGTCCTCCAGCTACCACCCACAGAACCTCTTACAT
GTTTCCAGCACCGATGTGCA-GCCCAGTCGCCTGCTCCAGGATCCACCTCAGGCTGACCT
TCAGTTGCCTGCCCACAGCCAGGAGTTCCCAGAGGATAGTGATGAAGACAGCCGGAGGGT
CTACAGATGTTCCTACTGCAGcaagggctttaagaagtccagccaCCTGAAGCAGCACGT
GCGCTCACACACCGGGGAGAAACCCTACAGGTGCAACATGTGTGGCCGGAACTTCGTCTC
AGCGGGGGTGCTCAAATCCCACCTCAACACACACACTGGTGTAAAGGCGTTCCGCTGTAG
CGTGTGCGATGCCTCTTTCACCACCAATGGAAGCCTGAACCGTCACATGGCCATGCACAC
GGACACCAAGTCCTTCAAGTGTCCCATGTGCTCAGAGACGTTCCGCACCAACCAGCACTG
CAAAAAGCACATAAAAAAGGACCATGAGATGGCAGCTAGAGCCCTGGA---------GGA
GAATGCAGAGGATGAGGAGGTTAC---------TGATCGGGTCCAACCGAAGCGCACCCG
TGCTGACATCATCACCTTCACTGAAGAGCAGACAGCAGAGCTGGCCCGGAACGAGCCCGG
TGACGATGCCTCTGTGTCGGAGAAGGTActggtgcagtcgGCCGCAGAGCGGGACCGTGT
CAGCGAGATGAAGGACAAAACGGCTGAGCTGGAAGCAGAGCCCAAGTTTGCCAACCGCTG
CAACTACTGCCCCAAAAGTTTCAAGAAGCCCAGTGACCTTGTCCGACACATTCGGATCCA
CACAGGA-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
>Synodus_sp._gill_5|000710|C512087|m.40713
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------CAGGAGAACAGCCAGAATGACCT
TCAGCTGTCTGCCGAGACTCAAGATTATCAGGAGGA---TGAGGATAACAGCAAAAGAGC
CTACAGGTGCACGTGGTGTAATAAAGGCTTTAAGAAATCCAGCCACCTGAAGCAACATGT
GCGCTCCCACACGGGAGAGAAACCTTACCGGTGCAACTTATGCGGCCGAGCCTTCGTCTC
TGCTGGAGTGCTGAAGTCACACCTCAACACGCACACAGGAGTAAAACCCTTCAAGTGTAA
TGTCTGCGATGCCTCGTTCACCACCAACGGCAGCCTGAACCGTCACATGATCATCC----
--ACATGAAGTCCTACAAGTGCCCG-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------
