>Amblygaster_clupeoides|006671|TR16654|c0_g1_i1|m.32109
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------GACACTAGGAAC-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------GTGACTATGAGACCCAGA--------------------------
CTACTGGAGGA-------------------------------------------------
-----------GAGCTGGGAGAGCTGTGAGACCCAGCTGGTCGATAGCACACAGGAGCTG
GAGGATATGAAGGCCAGACTGAAGCAGCCGATCCCAGATCACCTGGATGAGATGCATGAA
GCAGAGCAGTTTGTAAAGGAGGTGGAGGACTCCTTGGGCGAGTGGGCTCTGCGTCTGGGG
AAACTGAGCAACATGAAGACGGATCTGTCCCAGTACATCATCACTGACGACGTGCTGCTG
CTTCAAGAACAGGTCGACCATCTGCACGGACAGTGGGAAGAACTCTGCCTCAAAGTGTCT
CTGCGAAAGCAGGAGATTGCTGACCGTCTGAATGCATGGATCATCTTTAACGAGAAGAAC
AAAGAGCTGTGTGAATGGCTCACCCAGATGGAGAACAAGGTGGCGCACAGCACTGAACTT
AGCATCGAGGACATGGTGGAGAAACTCAAGAAGGACTGTATGGAGGAGATCAATCTGTTC
AGTGAGAATAAGACCCATCTGAAGCAGCTAGGGGAGCAGCTCATCACTGCCAGCAATAAG
ACCAAAGAGGCCGAGATCAACGACAAACTCAAAGACATCAACGACCGATGGCAACACCTC
TTTGACCATATAGAGGCCAGGGTGAGGAAGCTGAAGGAGACTCTAGTGACGGTCCAGCAG
CTGGACAAGAACATGAGTAACCTGCGGACGTGGCTCTCCCGCATCGAGGCCGAGCTGGCC
AAGCCTGTGGTCTACAGTGTGTGTCACCACGATGAGATCCAACGCAAGCTTGCAGAGCAG
CAGGACCTGCAGCGGGATATCGAGCAGCACACAGAGGGTGTGGCTTCTGTTCTGACGCTG
TGTGACGTGCTGCTCCACGATGCAGACGCCTGTGGGAGCGACCTGGAGAACGACTCCATC
CAACAGACCACCAGGAGCCTGGATCGCCGCTGGAGGAACATCTGTGCCATGTCTATGGAG
AGGAGAATGAGGATTGAGGAGACGTGGCGTCTGTGGTGTAAGTTCCTGGACGACTACTCT
CGCTTCGAGGACTGGCTCAAGGCCGCCGAGCGGACGGCTTCCAATCCAGCCACCTCCGAC
ACACTCTACACCAGTGCCAAGGAGGAGCTCAAGAAGTTTGAGGCCTTCCAGAGGCAGGTC
CATGAGCGGCTGACGCAGCTGGAGCTGGTGAATAAGCAGTACCGGCGTCTGGCCCGGGAG
AACCGCACGGATGCAGCCAGCAAGCTCAAGGAGATGGTTCACAAGGGCAACCAGCGCTGG
GACTGCCTGCAGAGACGCGTCACCGCCATCCTGCGTAGACTTAAGTACTTCACGTCCCAG
AGGGAGGAGTTTGAGAGCACGAGAGAGAGCATCCTGGTTTGGCTCACAGAGATGGACCTG
CAGCTCACCAACGTGGAGCACTTCTCAGAGAGCGACATCCACGACAAGATGAGACAGCTC
AATGCGTTCCAGCAGGAGATCACTCTGAACACCAATAAGATCGATGCTCTGATTGTGTTT
GGCGAGACCCTGATTCAGCGCAGCGCTCCGCTAGACGCCGTTCTCATCGAGGACGAACTG
GAAGAGCTCCACTCCTACTGCCAGGAGGTGTTTGGACGTGTCGCAAGATTCCACCAGCGC
CTGACCACCAGACGCCCTGTGCTGGAGGAGGAG------CTGTCAGATCGGGATTCAGAC
CTGGAGGAGTCGGGGGAGTTGGGGAGGTCTTGGGAGGAGAAGGAAGAGGACGAGAGCCGG
GCGGGGGAGGGGTCAGGGGTCGCGTCCGTCACACGACAGGTGTGTCATCTGCTGGCCCCG
CCCCTGGAGCGCTCAGGGCGTGAGACGCCCGTCAGTGTGGACTCCATACCACTGGAGTGG
GACCACACAGTGGACGTGGGCGGGTCTTCATCGC------ACGAGGAGGAGGAGGA---C
ACCTACTACAGCGCCCTCTCAGTAGGTAAGGCTGATGTTACATGGCATC-------ATTC
TCCAGACCCC--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------CATCAAAGG
AAGAGACA----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------------CA
CACACACACACACA----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------CACACTATCCA-------------
------------------------------------------------C
>Gasteropelecus_sp._gill_3|023047|scaffold34969|m.40123
ATGGTAGGTTTACTACATGCTGTACAGCCAGAGCCAATGGGAGCCTTTTTCTTTTCCAGC
TGGTTGGAGGTGAAGCAGAATCTCACACACACTTCTGTGCGGTCACACACACTGCTGGAA
GCCTGGAAGCAGTACTCAGCTCTGCTGGACCCCTGCTCCCAGAAGCTACATCAGATCAGA
GAGCAGTTGTCCTCACTGTCACAAGCTGCATCTGAACCTGAGGGCAGCACTGAGAGACTT
TCAGCCTGTGTACGGCAGCTACAGGAGTTGCTGGAGAAGACGAATTGTCTCCAGACTGAC
CTGGACAGAGTGCATGGAGCCTCCAAAGAGCTGGTTTGCCAGATGGAGCCGAGCTCAGCA
GCCTTCGTCAAGTCCGAGTGCCGGCTCTTGACGCGTGGTTGCCTCCAGCTTGAGGAGGTC
GTGAAAGGAAAACTGGGGGAAACAGAAGAGGATCTCAAGCAGCTTCAGGAGTTTGAGCAG
CAGCTGGAGTCACTAGAAGGTCATTTAGAGGACTGGAAGAAGAAACAAAGTGGACACGCT
GATACCGAACACACAGATGTCACTAAGTCGGGCTTGTTAGAGTTGAGCTCCCACTCTGCT
GACCTGGAGCTGCTCAATGGACTCAGCTACAGACTGACCCTAAGTGACCTCACCACTCGG
CGGTTACAGACCCTGAACAAGAAGTGGGCTCAGGCTTCGGCTCATGCTCAGGAGAGATGC
AGTGAGCTGCAGGCAGCCTCTCTTCAGAAGCAGGATTTTGAGCAGAGGTGTGAGAGCTGG
ATGGTGTTTCTGCAAAGAATGGAGGACAACCTGGTTGGAGAAATGTCATCAACCTACCCT
CAACTCAGACAGCAGCTACGCACACACCAGCATTTCCAGGCTGAGCTGTCTTTAGGTCAC
CAGATCCTGCACTCGGTCATCACTGAGGCTCTGCTGCTCTTACACAGAGGCGAGGTGGAC
GATAGGAGTGATTTCCTGCTGAAGTTGGCTCAGCTGAGAGAGCACTGGCAGGGCGCAGTG
CAGAGAGCAGCTCAGCGGCGCTCCCTAGTGGAGGGGCTGGTACAACACTGGCATCTCTAT
ACACACACGCTGCGCAAACTCCGCAGACTGCTCACACACACTCACACACTCCTCCCTCCC
GCCGGACCCACGCACTGCAGCGTCCTGCAACTCCGGCTCTCGCTGGAGGACATGAAGCGT
GCCCAGTTGCTGTTCTGCAGGTCGGTCTCCTGCTATCTTCTGCTGCTGGACGTGGGTCGG
CAGCTCTTCCCTGTGAGTGATGAGGTCACTCAGGCCCGGTTGCAGACCGAACTTGCCACC
CTGCAGGATGACTGGGAGAGCTCTCAGTTCACACTGGGAAAGAGGAGCAGCCTTACCGCT
GACATCATCAAGACCTGGGAGAGCTGTGCAGCCGGACTGGCCAATCACACGCAGCGGCTG
GAGAAGCTGAAGACCAGACTGAACCAGCCGATCC------------AAGAGACGGAGGAG
GAGCATGGCTTCATTAAGGAGATTCAGGACTCTCTGGACGACTGGGCGGTGAGTCTGTCC
GAACTCAGCACCATGAAGACGGACCTGTCCCAGTACATCATCAGCGAGGACGTCCTGCTG
CTGCAGGAGCAGGTGGACCATCTGCACGGCCAGTGGGACGAGCTCTGCCTGAAAGTGTCT
CTCCGTAAACAGGAGATTGCAGACCGCCTGAATGCGTGGATCATCTTTAACGAGAAGAAC
AGGGAGCTGTGTGAATGGCTCACTCACATGGAAAACAAAGTGGCTGATAGTGCTGAGCTC
AGCATCGAGGAGATGGTGGAGAAGCTGAAGAAGGACTGCATGGAGGAAATCAACCTGTTC
AGTGAGAATAAGACTCATCTGAAGCAGCTGGGAGAGCAGCTCATCAGCGCCAGCAATAAG
ACCAAGGAGACAGAGGTCAACGACAAGATCAAGGACATCAGCGACCGCTGGCAGCACCTG
TTTGACCACATTGAGGCCAGGGTGAGGAAGCTGAAGGAAACGCTGGTGATGGTGCAACAG
CTGGATAAGAACATGAGCAACCTGCGGACGTGGCTGTCCCGGATCGAGGGGGAGCTTTCC
AAGCCTGTCGTCTACAGCGTCTACCATGACGACGAAATCCAGCGCAAACTGGCTGAACAG
CAGGACCTGCAGAGGGACATTGAGCAGCACACAGAGGGCGTGGCCTCAGTGCTGACACTG
TGTGACATGCTGCTGCATGATGCGGACGCATGCGGCAGTGATGTGGAGAATGACTCCATC
CAGCAGACCACCCGCAGCCTGGATCGCCGCTGGAGAAACATCTGCGCCATGTCCATGGAG
AGGAGGATGAGGATCGAGGAGACATGGCGTCTGTGGCGTAAGTTTCTGGAGGACTACTCT
CGCTTTGAGGACTGGTTGACCACAGCCGAGCACACGGCAGCTAACCCGGCCAGCACGGAC
GTCCTCTACACCTGCGCCAAAGAGGAGCTCAAGAAGTTTGAGGCCTTCCAGAGGCAGGTG
CACGAGCGTCTGACACAGCTGGAGCTGGTGAATAAGCAGTACCGGCGTCTGGCCCGAGAG
AACCGCACCGACACCTCCAACAAACTGAAGACGATGGTGAACGAGGGGAACCAGCGGTGG
GACGCCCTGCAGAGGAGAGTGGCCGCCGTGCTCCGCAGATTAAAGCACTTCACGTCCCAG
AGGGAGGACTTTGAGGGGACGCGGGAGGCCATTCTGGTGTGGCTGACCGAGATGGACCTG
CAGCTCACTAACGTGGAGCACTTCTCCGAGAGCGACATCCATGACAAGATGAGGCAGCTC
AATGCGTTTCAGCAGGAGATCACTCTGAACACCAATAAGATCGACGCTCTGATCGTATTT
GGAGAGAATTTGATCCAGAAGAGCTCTCCACTGGACGCTGTGCTGATAGAGGACGAGCTG
GAGGAGCTGCACTCCTACTGTCAGGAGGTGTTCGGCAGGGTGGCCAGATTCCACCACCGC
CTCATCAATAGGAGCCCGGTCCTGGATGATGAGACTGACTTCTCAGACAGAGATACAGAT
GTGGAGGACTCTCTGGAGCTGGGGGCAGTGTGGGCAGAGGAGGAGGACATGATGGATGCT
GGGA------------TGGCCACACCTGTGGAGCAGTCAGTGCACGTCCTCCTCCCACCT
CCGCATGATCGGTCAGGCCGTGAGACACCGGTCAGCGTGGACTCCATTCCTCTCGAATGG
GACCACACTGTGGATGTGGGTGGATCTTCATCACCTGAAGATGAGGAAGAGGAGGAGGCC
ACGTTTTACAGTGCTCTATCAGTA-GGGAGGTCGATGACGGAGCCCCCCAGCTGGCATTC
TCCACCCCCCGCAGACAGGAGACGCATCATCCGTAGCCTGACATCATCACCTGTACACAC
CAGCACCTCTTACCATCCGCAGGGATATGCTAAGCTAATGTCTGAGTGCACAGAGAGCAT
CGATAACGTGAAGCGAGTCAAGCTAATCCTGGATGATGACGAGATGCTGGAGGACCAGGG
TCTGACCACTCTGTCTTCAGCAGACAAACAGACCGGTGTGATCGAACGCTGGGAACTGCA
GCAGGCGCGGGAGATGGCTGACCTACAGCAATGGCACAAGCTGACCTCTGACCTCATCGA
AGTCACAACCTGGCTGGACGGCGTCGTTCCCGAACTGGAGGCTCTGCAGAGAGCAGAAGT
GTCCGGCAGCATCAGAGACATGGAGAACAGCATCCACAAACTGAAGGAGGTCCAAAAGAC
GTTCAGCATCTACAAGGCTCTGATGATCGGAATGAATGTGAGTGGGCAGGACATCCAGCG
AGGAGACAGGATGGAGCTTCAGGAGCTGAGGACGGGCCTGCATGCAACCAATCAGAAATG
GACACACGCCTGCGCCCTTCTGGACGGGTGGGAGTTTCAGCTGCATCGTGCGCTCCTGCA
GTGCCAGGAGTTTCATGAGAAGCTGCACTCTCTGCTGCTGTGGCTGGCTCGGGCTGAGAG
CCAGCGCTACATGGTCAACATTCACGACTGCAACACAGACACCAACATCCTGCAGGAGCA
CAGAGACACACTCAAGGATCTACAGCAGGAGCTGTGTAGTCGGGAGCAGGAGGTTCTCTC
TCTGCAGGAAATCTCCACCCATATCCTGCATCTGGACCAAGGAGAGGACAGCCTAGAGGC
CAAAGAGAAGGTCCACGTCATCAGCAACAAGCTCTGCCTCCTCCTCAGACAGGTGGCCTA
TGACCTGAACATGCTGCAGGATAGACTGGACTTTGAAGGTTCATCAGTGGACAGTGGGGA
AGGGAGGGTCACCACAGGCGCCACTGCACTATTAGACAAGGAGTCAAGGACTGCTGAAAA
GAAGCCTGAAAGTGCTAGGCCAAAGAAGAAGGACGTGTCCCCCGGCAGACCCTTCCTGTA
CCGGGTGCTGAGGGCAGCGTTCCCCCTGCACCTGCTCTTCCTGATGCTGCTGGTGCTGGC
TTGCCTGGTCCCTCTGTCTGAGGACGACTACAGCTGCACCCTCTCCAACAACTTTGCCCG
CTCCTTTTACCCCATGCTCCGCTACATCAACGGACCCCCTCCTACATGA
>Lepidogalaxias_salamandroides_Head_2|027031|scaffold647|m.830
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------GACGAGGCCCTGCACCTGCTGGAGAGGACCGAGGGGGTG
GACAGGAGTGACTTCATCCTTAAGCTGGCCCAGCTGAGGGAGCACTGGCAGGGGGCCGTT
CGGCGGGCCCAGCAGCGGCGCTCTCTAGTGGAGGGGCTGCTGAAGCAGTGGCAGCTCTAC
CCCCGCGACCTCAGGAAGCTCCAGAGGTTCCTGTCTGACACGCGCTGCCTGCTCCCTCCC
GCCGACCCATCGCAATGCAGCCTGAGCCTCCTCCGCCGGTCTCTGGCCGGCCTCAAGCGC
ACAGAGCTGCTGTTCCAGAGGCACCAGTGCAGCTACGGCCAGGTGCTGGAGGTGGGCCGG
CAGCTCTTCTGCATGGGGGACGAGCAGGCGCAGGCGCGGCTGCAGACAGAGCTGGGCGCC
CTGCAGGAGGAGTGGGAGCGCACGCAGAGGCTGCTGGGAAAGAGGAGGGAGCTCACGGAA
GCCGTCATCCAGAACTGGGAGCAGTGTGAGGCCAGGCTGGCCCACGTCGGCCGGCAACTA
GAGGAGGTGAAGGCCCAGCTGAACCCCCCCCTCCCTCTGCACCTAGAAGAGCTGAAACGG
GCAGAGCGGCCCACCAAGGAGACCGAGGACTCGCTGGAGGACTGGGCTGAGAGCCTGACG
GAGCTAGCCACCATGAAGACCGATTTGTCCCAGTACATCATCGCTGACGACGTCATGCTC
CTACAAGAGCAGGTGGAGCATCTCCACTGCCAATGGGAGGAACTGTGTCTGAAGGTGTCC
CTACGCAAGCAGGAGATTGCGGACAGACTCAACGCGTGGATGATCTTCAACGAGAAGAAC
CGAGAGCTCTGTGATTGGCTGACGCAGATGGAGAACAAGGTGGCACACAGCAGCGACCTC
AGCATTGAAGAAATGGTGGAGAAGTTAAAGAAGGATTGCATGGAGGAGATCAACCTCTTC
AGCGAGAACAAAACCCACCTGAAGCAACTTGGGGAGCAGCTCATCACCGCTAGCAACAAG
ACCAAGGAGACTGATATCAATGACAAGCTCAAGGACATTAATGACCGCTGGCAGCACCTG
TTTGACCACATTGAGACCAGGGTGAGGAAGCTGAAGGAGACCCTGGTCACCGTGCAGCAG
CTGGATAAGAACATGAGTAACCTGCGGACGTGGCTCTCGCGCATCGAGGGCGAGCTGGCC
AAGCCCGTGGTCTACAGCGTCTGCCACAGCGAGGAGATTCAGCGGAAGCTCGCCGAGCAG
CAGAACCTGCAGTGGGACATCGAGCAGCACACGGAGGGCGTGACCTCTGTGCTGACGCTG
TGTGACGTGCTGCTCCACGACGCCGACGCCTGTGGGAGCGACGTGGAGAATGACTCCATC
CAGCAGACCACCAGGAGTCTGGACCGCCGCTGGAGGAACATCTGTGCCATGTCCATGGAG
AGGAGGCTGAGGATTGAGGAAACGTGGCGACTCTGGTGCAAGTTCCAGGACGACTATTCG
CGCTTCGAGGAGTGGCTTCGGTCGGCCGAGCGCACTGCGGCCAGCCCCTCGTCCACGGAC
GTCCTGTACACGTGTGCCAAGGAGGAGCTGAAGAAGTTTGAGGCGTTCCAGAGGCAGGTT
CACGAGCGACTGACCCAGCTCGAGCTCGTCAATAAGCAGTACCGACGCCTTGCCCGGGAG
AACCGCACCGATGCCGCCAGCAAGCTGAAGGTCATGGTCCATGAAGGCAACCAGCGCTGG
GACAGTCTGCAGAAGAGGGTTGGGGCCATCCTCCGCAGACTCAAGCACTTTACTTGCCAG
AGGGAGGACTTTGAGGGCACTCGTGAGGGCATTCTGGTGTGGCTGACTGAGATGGACCTG
CAGTTGACTAATGTGGAGCACTTTTCAGAGAGTGACATCGACGACAAGATGAGACAGCTG
AACGGCTTCCAGCAGGAGATTACTCTGAACACGGATAAGATTGACGCGCTGATTGTGTTT
GGGGAGAACTTGATCCAGAAGAGCGCTCCGCTGGATGCCGTTCTGATCGAGGACGAGCTC
CAGGAGCTGCATTCCTACTGCCAAGAAGTCTTTGGCAGGGTGGCCCGCTTTCACCAACGC
CTCGTCAGCCGACGCCCGGCTGTTGACGAGCGG------------------GACACGGAC
CCGGAGGAGACGACCGAGCTGGCCGGGACGTCCTGGGGGGACGAGGACAAGGAGGAGGAC
GAGAGCGCGGTGACAGCGGACACAGTCCGCCACCACGTCGCGTGCCGCCTGCTGGCCCCC
CCGACGGAGCGCTCAGGCAGAGAGACCCCCGGCAGCGTGGACTCCATCCCTCTGGAGTGG
GACCACACTGTGGACGTGGGGGGGTCCTCGTCCC------ACGAGGATGAGGAGGAAGCC
TCCTTTTACAGTGCCCTGTCAG---GGAAGTCTGTCAACGAGCCACCC------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>Pantodon_buncholzi_mixed|016221|scaffold18917|m.27016
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------TCCCAG---------------------------
------------------------------------------------------------
--------------GCTTTCCATCTGTGTTTGTGTATGTGTGTTCATTACTGGAATGACC
T------------------------------------------CCTTTTGTCCTGCACCC
TGC----------------------------AGGATTGCATGGAGGAAATCAACCTGTTC
AGTGAGAACAAGACCCACCTGAAACAACTGGGCGAGCAGCTGATCCGTGCCAGTGATCGT
GCCAAGGGGGCCGAAGTCAACGACAAGCTGAAGGATGTGGGCGACCGCTGGCAGCACCTT
TTCGACCACATCGAGTCCAGGGTGAGGAAGCTGAAGGAAACGCTGGTGACAGTGCAGAAG
CTGGATAAGAATATGAGCAACCTTCGGTCATGGTTATCCCGCATTGAGGCAGAACTGGCT
AAACCTGTGATCTACAGCGTTTGCCAAAGTGAGGAGATCCAGAAGAAGCTGGCTGAGCAG
CAGGACCTCCAGCGAGACATTGAGCAGCATTCTGAGAGTGTAGCCTCCGTGCTGACATTG
TGTGATGTGCTGCTTCGGGATACGGATGCCTGCGGAAGCGAGTCTGAGAGTGATTCTATC
CAGGAGACCACGCGCAGCCTGGACCGCCGATGGAGGAACATCTGTACAATGTCTATGGAA
AGGAGGATGAAGATTGAGGAGACGTGGCGACTCTGGtgcaagTTCCTTGATGATTATGCA
CACTTTGAAGTTTGGCTAGACGCCGCCGAACACATGGCCGCCAACCCCAACTCGGCTGAT
ATCCTTTACACTAGCGCCAAAGAGGAGCTAAAGAAGTTTGAGGCCTTTCAAAGGCAGGTG
CACGAGCGACTCACTCAGCTGGAGCTGGTCAACAAGCAATATCGGCGACTTGCCCGAGAG
AACCGTACTGACACAGCAAGCCGACTTAAGCTCATGGTGCAAGATGGTAACCAGCGTTGG
GATGGGCTGCAGCGTCGCGTAGCTTCTATCCTGCGTAGGCTCAAGCACTTTACATCGCAG
AGGGAAGAGTTTGAGGGCACAAGGGAAGCTCTTTTAGTATGGCTGACGGAAATGGACCTA
CAGCTCACCAATGTGGAGCACTTCTCAGAGAGCGATGTCCATGACAAGATGCGACAACTA
AATGGTTTCCAGCAGGAGATTACCCTAAATACCAATAGAATTGACCAGCTCATTGTGTTT
GGAGAGAACCTGATCCAGAAGAGTTCCCCACTGGATGCTGTGCTAATTGAGGATGAACTG
GAGGAGTTACACTCTTACTGTCAGGAGGTTTTTGGCCGGGTGGCCCGTTTTCACCACAGA
CTCATCAATTGTCGCCTGCCTATAGAGGATGAG---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------CATGAG----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>Sargocentron_rubrum_gill_6|008613|scaffold14725|m.17044
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------CTGGGCACC
CTGCAGGAGGAGTGGGACAACCTGCACAGCCTGCTGGGACGGAGGATGGACCTCACCGAG
GCTATCGTCAAGAACTGGGAGCGCTGTGAGGCCTCGCTGGCCGATAGCGTGCTGCGGCTG
AAGGAAGTGAAGACCAGACTGAACCATTCGAGGTCTGAGTATGATGACGAGCTGCAGAAA
AACGAACAACTCAACAAGGAGAACGAGGACTCCCTGGAGGACTGGGCTGAGAGCCTGACG
GAGCTGGCCACCATGAAGACGGACCTGTCCCAGTACATCATCGCCGACGACGTGCTCCTC
CTCCAGGAGCAGGTGGAGCACCTCCACTGCCAGTGGGAGGAACTCTGCCTCAAGGTGTCT
CTGCGTAAACAGGAGATCGCCGACCGGCTGAACGCCTGGATCATCTTCAACGAGAAGAAC
AAGGAGCTGTGTGAGTGGCTGACGCAGATGGAGAACAAGGTGGCTCACAACTCCGACCTC
AACATCGAGGAGATGGTGGAGAAACTCAAGAAGGACTGCATGGAGGAGATCAACCTGTTC
AGTGAGAATAAAACCCACCTGAAGCAGCTCGGGGAGCAGCTCATCACCGCCAGCAACAAG
ACCAAGGAGACGGAGATCAACGACAAGCTGAAGGACATCAACGACCGCTGGCAGCATCTG
TTCGACCACATTGAGGCCAGGGTGAGGAAGCTGAAGGAGACGCTGGTCACTGTGCAGCAG
CTGGACAAGAACATGAGCAACCTGCGGACGTGGCTGTCTCGTATCGAGGCGGAGCTCGCC
AAGCCGGTGGTCTACAGCGTCTGCCACAGCGACGAGATCCAGAGGAAGCTGGCcgagcag
caggacctgcagcgggacatcgagcagcacacagaggGCGTGGCCTCGGTGCTGACCCTG
TGTGACGTCCTGCTGCACGACGCCGACGCCTGCGGCAGCGACTCGGAAAATGACTCCATC
CAGCAGACAACGCGCAGCCTGGACCGCCGCTGGAGGAACATCTGCGCCATGT--------
------------------------------NNNNNNNNNNNNNNNNNNNNNNNNNNNNNT
CGCTTTGA----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>Scleropages_formosus_red_gill|027350|scaffold43168|m.57166
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------CTCTTCCAACGCCACCAGAGCACCTATATGCAGACCCTGGAGGTGGGCCGG
CAGCTGTTCTCCATGGGCGATGCGGAGACACAGGCGCAGCTCCAGACAGAGCTGGGATCC
CTGCAGGAGGACTGGGAGAAGACCTGCGCCCTGCTGCAGAAAAGGAGGAACCTCGCTGAC
ACCGTGCTGCAGACCTGGGACCGCAGCGAGGCCGGGCTAGCCGATGGCGAGCGTGGTCTG
GAGGAGGTGAAGCGCAGGCTGAAGCAAGCACCGCCGGAGCGTCTGGATGAGCTGCAGACT
GAGGAGCGTCTCATCAAGGAGTGCGAGGGTGAGCTCGAGGACTGGGCTTGCAGGCTGACG
GAGCTAGCCACCATGAAGACGGACCTGTCCCAGTACATCATGGGCGAGGACACGGTGCTG
CTGGGCGAGCAGGTGGAAGGCTTGCACCAGCAGTGGGAAGAGCTGTGCCTGAAGGTGTCG
CTGCGCAAACAGGAGATCGCGGACCGGCTCAACGCCTGGGTCATCTTTAACGAGAAGAAC
AAGGAGCTTTGCGAATGGCTGACGCAGATGGAAAACAAGGTGGCTCACAGTGCCAACCTC
AGCATCGAGGAGATGGTGGAGAAGCTGAAGAAGGACTGCATGGAGGAGATAAACCTCTTC
AGCGAGAACAAGACCCACCTAAAGCAACTAGGTGAGCAACTCATCAGCGCCAGTGACCGG
ACCAAGGGAGCTGAGGTCAATAATAAGCTGATGGATGTCAATGACCGCTGGCAACATCTA
TTTGACCACATTGAGGCCAGAGTAAGGAAGCTGAAGGACACGCTGGTGACGGTGCAGCAG
CTGGATAAGAACATGAGTAACctgCGGACCTGGCTGTCCCGAATTGAGGCTGAGCTGGCC
AAGCCTGTGGTCTATAGCGTCTGCCACAATGACGAGATCCAACGAAAGCTGGCCGAGCAG
CAGGATCTGCAGCGGGACATCGAGCAGCACACAGAGGGCGTGGCCTCCGTGCTGTCGCTG
TGCGAGGTGCTGCTGCGGGATGGCGATGCATGCAGCAACGAAGCAGAGAGCGAGTCCATC
CAGGAGACAACACGTAGTCTGGACCGCCGCTGGAGGAACATCTGCGCCATGTCCATGGAG
AGGAGGATGAGGATTGAGGAGACGTGGAGACTGTGGTGTAAATTCCTGGAGGACTACTCC
CGCTTTGAGGACTGGCTGAAGACGGCAGAGATCACCGCGGCTAACCCCAACTCTGCTGAC
GTCTTGTACACCAGTGCCAAAGAGGAGTTAAAGAAGTTTGAGGCCTTTCAAAGGCAGGTC
CACGAGCGACTTACTCAGCTGGAGCTGGTGAACAAGCAGTATCGGCGGCTGGCCCGGGAG
AACCGCACCGATTCTGCCAGTCGGCTCAAGCACATGGTCCAGGAGGGGAACCAGCGCTGG
GATGTGCTGCAGAGGCGTGTGACCGCCATACTGCGCCGACTCAAGCATTTCACGTCCCAG
CGGGAGGAGTTTGAAGGGACGCGGGAGGCCCTCCTGGTGTGGCTCACAGAGAtgGACCTG
CAGCTCACCAATGTGGAACACTTCTCTGAGAGCGACGTGCACGACAAGATGCGGCAGCTC
GACGCCTTCCAGCAGGAAATCACCCTCAATACTAACAGGATCGACCAGCTGATTGTGTTT
GGGGAGAACCTGATCCAAAAGTCGGCCCCGCTGGATGCCGTGCTCATAGAGGACGAGTTG
GAGGAGTTGCACTCCTACTGCCAGGAGGTCTTTGGCCGAGTGGCCCGCTTTCACCACCGC
CTTACAAGCCGCCGGCCGGTGCTGGATGAGGAGAGAGACCTGTCGGACCGAGACACAGAT
GTGGAGGACTCCGGG---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
>Synodus_sp._gill_5|013020|scaffold17619|m.21703
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------GACGATGTGCTGCTG
CTGCACGAACAGGTGGAACATCTCCATTGCCAGTGGGACGACCTCTGCCTCAAGGTCTCG
CTACGGAAGCAGGAGATAGCTGACCGTCTGAACGCTTGGATCATCTTCCATGAGAAGAAC
AAGGAGCTGTGCGAGTGGCTGACCCAGATGGAGAACAAGGTGGCCCACAGCTCCGACCTC
AGCATCGAGGAGATGGTGGAGAAGCTCAAGAAGGACTGCATGGAGGAGATCAACCTGTTC
AGTGAAAACAAGACGCATCTGAAACAACTGGGTGAGCAGCTCATCACCGCTAGCAACAAG
ACCAAGGAGGCCGAGGTCAACGACAAGCTCAAGGACATCAACGACCGCTGGCAGCACCTG
TTCGACCACATAGAGACCAGGGTGAGGAAGCTGAAAGAGACCCTGGTGACGGTGCAGCAG
CTGGACAAGAACATGAGCAACCTGCGGACCTGGCTGTCCCGCATCGAGGCCGAGCTGGCC
AAGCCCGTGGTGTACAGCATCTGCCACAGCGAGGAGATCCAGAGGAAGCTGGCCGAGCAG
CAGGACCTACAGCGGGACATCGAGCAGCACACGGAGGGCGTGACCTCGGTGCTGACGCTA
TGCGACGTGCTGCTGCATGACGCAGACGCCTGCAGCTCCGACTCGGAGAACGACTCCATC
CAGCAGACATCCCGCAGCCTGGACCGACGCTGGAGGAACATCTGCGCCATGTCCATGGAG
AGACGGATGAGGATCGAGGAGACGTGGCGTCTGTGGTGCAAGTTTCTGGACGACTACTCC
CGCTTCGAGGACTGGCTGAAGTCGGCCGAGCAGACGGCGGCCAACCCCATCACGGCTGAC
GTCCTGTACACCAGCGCTAAGGAGGAGCTGAAGAAGTTCGAGG-----------------
---------------------------NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNNGCCGCCAGCAAGCTCAGGCTGATGGTGCACGAGGGCAACCAGCGCTGG
GACGGCCTGCAGAGGAGGGTGGCCGCCGTGCTCCGCAGGCTCAAGCACTTCACCTCTCAG
AGGGAGGACTTCGAGGGCACGCGGGAGGGCATCCTGGTGTGGCTGACCGAGATGGACCTG
CAGCTCACCAACGTGGAGCACTTCTCCGAGAGCGACATCGAGGACAAGATGAGGCAGCTC
AACGGTTTCCAGCAGGAGATCACTCTGAACACCAACAAGATCGACGCGCTGATCGTGTTC
GGGGAGAACCTGATCCAGAAGAGCGCCCCATTGGACGCGGTTCTGATCGAGGACGAGCTG
GAGGAGCTGCACTCCTACTGTCAGGAGGTGTTTGGCAGGGTGGCCCGCTTCCACCACCGC
CTCACCCACCCACATCCGGTTCTGGAGGAGGACCGTGA----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------
