>Amblygaster_clupeoides|026582|TR45031|c0_g1_i1|m.69208
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------CACCTGAAGCAGGTGCACAATGCTGAGGACCCCGCCG-----------------
-CGCTGCTGGCCACACTCTCGGACGCCCTGCTTCAGTGCAATTTCTGCCCGGAGGTCCTG
GGTGACCTCAACGCCCTGCAGGAACATATCCGCTGCTCCCACGGCTTCCCAAGCCCCGTG
GCCA---------AGGAGAGCAACGCCTTCTTCTGCCCGCAGTGCTTCATGGGTTTTCTG
ACCGAGGCCACGTTGGAGGAGCACGTGCGTCAGACCCACTGCGACTCGGGCAGCCTGCGC
TTCGACTCGCCCCTGGCCGTGAGCTCCAAGGACCCCATCGTGGAGGTCTACTCTTGCTCG
TACTGCACCAACTCGCCCATCTTCAACAGCGTGCTGAAGCTCAACAAGCACATTAAGGAG
AACCACAAGAACATCCCGCTGGCACTCAACTACATGAACAACGGCAAGCGGTCCCTGAGG
GCCCTGAGCCCCTCG-TCGCCCATTTCCGTGG---ACACGGCGCT---GCTCAAGCACGC
CACGCAGTCTTCACGCTCGGCCAGCGAGTTCATCTGTAACCAGTGCGGCGCCAAGTACAC
CAGCCTGGACCTCTTTCAGACCCACCTCAAGACGCACCTGGACAGCGTGGTGCCGCAGCT
CACCTGCCCGCAGTGCAACAAGGACTTCCCCAA---CCAGGAGTCCCTGCTGAAGCACGT
GACGGTGCACTTCACCATCACCTCCACCTACTACATCTGCGAGAGCTGCGACAAGCAGTT
CACCACGGTCGACGACCTGCAAAAGCATCTGCTGGAGATGCACACCTTCGTGTTCTTCCG
CTGCACGCTCTGCCAGGAGGTGTTTGACTCGAAGGTGTCCACCCAGCTCCACCTGGCCGT
CAAGCACAGCAACGAGAAGAAGGTGTACCGCTGCACCTCCTGCAACTGGGACTTCCGCCA
CGAGACCGACCTGCAGCTGCACGTCAAGCACAACCACCTGGGCCACCCG-----------
-------AGC--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------
>Distichodus_sexfasciatus_gill_4|016138|scaffold24204|m.27505
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------GACCAGGACCAG
GATCTGTACAT-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------GTGCGATTACTGTGAGGAGACCTTTAGCCAGACCGATGAG
TTGGAGAAGCACGTGCTGACCCGCCACCCCCAGCTTTCT---------GACCGAGCC---
------GAACTGCAGTGCATCCACTGCCCTGAGATCTTTAGCGATGAAGGTGCCCTGCTC
ACCCACATCGACCAAACACAT------GCCAACAAAAAACACAAGTGCCCCATGTGTGCA
GAgcagttctcatctgtggaggatgtgtACTGTCACCTGGACAGCCACCGGCAGCCGGAT
TCCAGCAACCACAGTGCCAGCCCCGACCCAGTGCTTGGCAGCGTGGCATCCATGAGTAGC
GCCACTCCCGACTCCAGTGCCTCATTGGAGAGAGGATCCACCCCAGAC---------TCA
ACCCTCAAGCCTATGCAGGGCCGGCGCAAACTGGCCCCAT---CATCTGACCATGATGAG
GGAGGCTGGG------------CAGGAAAGATCACATACAGCTGCCCTTATTGCTCCAAG
AGAGATTTCAACAGCCTAGCAGTTCTGGAGATTCACCTGAAGACCATTCATGCAGACAAA
CCCCAGCAGAGTCACACTTGCCAACTGTGTTTGGACACCTTACCAACTCTCTACAACCTG
AATGAGCAT---------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------
>Gasteropelecus_sp._gill_3|025363|scaffold6480|m.5979
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-AAACACAGCAACGAAAAGAAAATGTATCGTTGCACAGCGTGTGCCTGGGACTTCCGGAA
GGAGATTGACCTGCAGACACATGTGAAGCACACTCACCTGAGTCAGCCGTCTGGGCCTGG
GGTTACCGGCAAAGCTCGCAAATGCATATTCTGTGGGGAGAGTTTTGGCACAGAGGTGGA
GCTCCAGTGCCACATCACCACCCACAGTAAGAAATTCAACTGCCGCTTTTGTGGGAAGGC
CTTCCATGCCATTGTCCTGCTTGAGAGACATCTCAGAGAAAAGCATTGCATGTTCGATGG
AGGCAACGGTAATGGAAACGGGGGAAGTCAGAATGGAACTCCCAATGGAGTGACTCAAAG
CTCTAAGCGTGGAGGAGGAGGT---------TCAACTGCAGCTGCTGAGCAAGCAGACCT
TCAGAA----------------CATGATTTTGAAGGGAGGAACCCAAGAAACGGCC----
---------AATAGCCATGAAGCCAGTGGAGGTGAAGAGGAGATGGATGCCTCAGAACCG
ATGTATGCTTGTGACATCTGCGGGGCTGCATATACCATGGAGTCCCTTCTCCAGAACCAC
CGGTTGCGTGATCACAATATAAGGCCTGGTGAAGACGATGCAGGTTCCCGGAAAAAGAAG
GCCGATTTCATCAAGGGCAATCACAAGTGCAATGTCTGCTCAAGAACCTTCTTCTCTGAG
AATGGCCTGAGGGAACATGCCCAGACCCACCGTGGTCCAGCCAAACACTACATGTGCCCC
ATCTGTGGAGAGCGTTTCCCCTCTCTGCTCACCCTCACAGAGCACAAGGTCACCCACAGC
AAGAGCCTGGACACAGGCACCTGCAGAATCTGCAAGATGCCCCTGCAAAGCGAGGAGGAG
TTCATTGAGCACTGCCAGATGCATCCGGACCTGAGGAACTCGCTCACAGGCTTTCGCTGT
GTGGTCTGCATGCAGACGGTcacctcaaccctggagctaaagatccatggcacCTTCCAC
ATGCAAAAGCTGTCTTCGTCAGGGGGTAGTGGCGGTGGAGGAGGGTCAGCCTCATCATCT
CCCAATG-----GCCAGTTGCAGGCCCACAAGCTCTATAAGTGTGCACTCTGCTTGAAGG
AGTTCAAAAATAAGCAGGAGCTTGTCAAGCTGGATGTCAACGGCCTACCCTTTGGGCTGT
GT------------------GCTGGCTGCATGAGCC----------------------GA
GGCACCAACGGT------------------------------------CAGTCGTCCAGT
GGGGTTGTGACACCTCAGGAGCAAGG--GGACAAGG------------------------
--------------------------GNNNNNNNNNNNNNNNNNNNNNNNNTGAAGTTCG
AGACCTTGGAAGATCTGGAAAACCATGTTCAGGTAGACCATC------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------CCGAGATGAGCCCA
GA----------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------G
ACCAGTGCAGCTAA
>Lepidogalaxias_salamandroides_Head_2|016237|scaffold14127|m.18751
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------AACCCTGGAGGTGGG
CCTGAGACGCA-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----GCTGATGATGCTACAAGGGTCACCTATG--TCTAGGA------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------T
CAGCCCCCCCGAAGAGAAGAAGACATACCAGTGCATTAAGTGCCAACAAATCTTCTACAG
TGAGTGGGACATCCACGTTCATGTGGCAAGTCACATGCTAGAAGAG--------------
-------GGACTGAATCATGACTGTAAGCTTTGCAACCAGACACTGGATtCTCCTGCCAA
ACTCCAGTGCCACCTTATTGAGCACAGC--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------TTTGAGGGA-----------------------
------------------------------------------------------------
---------------ATGGGCGGGAC----------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------CTTCAAGTGTCCA
GTCTGT----------------------------------------------TTCACAGT
ATTTGTCCAGGCA-----------------------------------------------
--------------------------------------------AGTAAGCTCCAGCTGC
ACATCTTCTCTGCACACGGC----------------------------------------
------------------------------------------------------------
--------------------CAAGATGACAAGATCTACGACTGCTCTCACTGTCCACACA
AATTC-------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------TTCTTCCA--
------------------------------------------------------------
------------------------------------------------------------
-------GACAGAGCTACAGAACCATAC--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------GATGAGT---
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------C
AACATAGCAGCTAA
>Melanotaenia_praecox_viscera_mixture_8|008484|scaffold12846|m.11903
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------GACAGTTGCCGGCAGGTGTTCGAGTCGCTGAGCGAT
CTCACCGAACACAAGATTAATCAATGCCAGCTGACAGACGGTGCTGATCTTGAGGATGAC
CCGTCATGTTCTTGGCCAGCATCATCTCCGTCCAGTAAGGATCAGACTTCTCCAGGACAT
TGTGAGGACTAtgattttggtgaggacgAAGGAGGCCCTGGTCTACCATACCCATGCCAG
TTCTGTGACAAGTCCTTCAGTCGCTTAAGCTTTCTCAAGCGCCACGAACAGAGCCACGGC
GATAAACTTCCTTTCAGCTGTACCTTCTGCAGCCGCCTGTTTAAACACAAGCGCAGCCGA
GATCGGCACGTTAAGCTACATACTGGTGATAAGAAGTACCACTGTGGAGAGTGTGACTCA
GCCTTCTCCCGCAGTGATCACCTCAAAATACACATGAAAACCCACGCCTCCAACAAACCC
CATAAGTGCCCTGTGTGCCGTCGAGGTTTCCTTTCGTCCAGCTCTCTTCACGGCCACATG
CAAGTACATGAAAGGGGCAAAGATGGCAGCAGCTCAAGTTTTTCAAGAGCTGATGAATGG
AAGTTAAAGGAAACTCGAAAATGCAGCCGCTGTGAGGAAGGCTTTGACGTTCCAGAGGAG
CTTCAGAGGCACATCGCAGAGTGTCACCCTGAGTGCTCTCCATCAGAGGATGGAGGTCTG
GGTGCGACCCTGCAGTGCATCTACTGCCATGAGCCCTTCAGTGATGAGGGCACCCTACTG
ACCCACATTGACCAGGCCCACAGCAGAGATAGGAAAGGCCACACCTGTGCTATCTGCTCT
GAGCACTTTTTGTCTGTTGAGGATCTCTATGCTCACATGGACATTCACCAACTCCCTGAA
TCCAGTAACCATAGTAACAGCCCTTCCTTGCTTACTGTAGGCTACACCTCTGTCTCTAGC
ACTACACCTGACTCCAACCTCTCTGTCGACAGCTCCACAATGGTGGAGACAGCACCACCT
GTGCCCAAAACAAGGGGCAGGAGAAAGAGAGCTGCTCAGAACACATCTGACATAGGAGGG
CGTTCCTCAAA---------ACAGCCTAAAGTCTCCTACAGTTGCATCTACTGCAACAAG
CAAGTATTCTCCAGCTTGGCTGTACTTCAAATTCACCTACGTACCATGCATCTGGATAAG
CCAGAACAAGCTCATACTTGCCAGTTTTGTTTGGAGGTTCTGCCCTCTTTATTAAATCTA
AATGAACATCTTAAGCAGGTTCACAATGCAGAAGACCATGCTG-----------------
-CCCTGTTAGCCAGCCTGCCTGATGCTCTCCTTCAGTGTAATTTTTGCCCTGAGGTGCTG
AGTGACCTAAATGCTCTCCAGGAACACATTCGCTGCTCCCATGGCTTCCCCAGTCCCGTT
GCCA---------AGGAGAGTAATGCCTTCTTCTGTCCACAATGCTTCATGGGGTTCTTG
ACAGAGGCTACCTTGGAAGAGCATGTTCGTCAGACCCATTGTGATGGGGGTAGCCTGCGC
TTTGACTCACCATTGGCTGTAACTCCCAAGGAACCTATAGTAGAGGTGTACTCCTGTTCA
TATTGCACCAACTCTCCCATATTCAACAGTGTTCTAAAGCTCAACAAGCACATCAAGGAG
AATCACAAAAACATTCCCCTGGCCCTAAACTACATCAATAATGGAAAGAAATCCCTACGC
ACTCTCAGCCCCTCT-TCACCAATATCAGTGGAACAAACTGCCAT---GCTGAAACAAAG
CAGCTCAGCCTCACGC---ACTAGTGAGTTCATATGTAACCAGTGTGGAGCCAAGTATAC
AAGTTTAGACCTTTTCCAGACTCACCTCAAAACTCATCTGGATGGTCTGCAGCCTCAGCT
CACTTGTCCACAGTGCAACAAAGAGTTTCCCAA---TCAAGAATCCCTGCTAAAGCATGT
GACAATTCACTTCACTATTACTTCCACTTATTACATCTGTGAGAGCTGTGACAAGCAATT
CACTTCAGTGGATGATCTGCAGAAGCACTTACTTGATATGCATACATTTGTGTTCTTTCG
CTGCACTCTGTGCCAGGAAGTGTTTGACTCAAAGGTATCCACCCAACTTCACCTGGCAGT
AAAACACAGCAATGAAAAAAAGGTATACCGCTGCACATCCTGCAACTGGGACTTCAGACA
TGAGACTGACCTACAGCTGCATGTCAAACACAGCCATCTGGAGAACCAA-----------
-------GGACGCGCCCACCGATGCATTTTTTGTGGAGAGTCATTCGGCACAGAGGTGGA
GCTGCAGTGCCACATCACCACCCACAGCAAGAAGTACAACTGT-----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------
>Pantodon_buncholzi_mixed|020391|scaffold6571|m.7679
GATTACGCACGGAGCGGGTCCCTGCGGGCTGGGGGCCCCCTCTGGAGCCATCCTGATGGC
TTTGGGGGCCTCGCTTCCATTTTCCATTATTATGTGGACTACCGGAGCGGCGGCGCAGTC
CGAGAGCTGGCAGTTGTGCGCGAAAAGGGGGGAAGCCGGATTTTGTGGGATACCCGCGGG
TCTGTCGTGTGCGCGAGTGTCGGGGCAACTTCGGCCGATTTCTTTAGGATGTCTCGCCGC
AAGCAAGCCAAACCAAGATCCCTGAGAGTGGAGGAACAGGAGCTAGAAGACCAGCATGCT
TCGGCCCGCAAGTCTGCTACTGACAGGAATTCCGACAGCAAACTTGAGAAGCGGGTGGAG
GATGGCGAGGACGTAGATGTGAAGAAGCGTCTGGTTTCTCCGGAGGAGGGGGAGGAGGCT
GAGGAGGAGGCGCTGCACAGCTGCGACGGCTGCCTGCAGGTGTTCGAGTCACTGAGCGAT
CTCACCGAGCACAAGATTAATCAATGCCAGCTGACAGACGGAGCCGATCTAGAGGATGAC
CCTTCGTGCTCTTGGCCAGCATCCTCTCCATCTAGCAAAGACCAAACGTCGCCGGGACAC
GGCGACGGGTACGATTTTGGCGAGGAGGAAGGGGGCCTGGGACTGCCGTACCCCTGCCAG
TTCTGCGACAAATCCTTTAGCCGCCTCAGCTTTCTGAAGCACCACGAGCAGAGCCACAGC
GACAAGCTGCCTTTCAAGTGCACCTTCTGCAGCCGCCTCTTCAAGCATaAGCGCAGCCGC
GACCGCCACGTCAAGCTGCACACCGGCGACAAGAAGTATCACTGCGGCGAGTGCGACGCC
GCCTTCTCGCGCAGCGACCACCTCAAGATCCACCTCAAGACGCACACCTCGAATAAGCCC
TACAAATGCACCGTTTGCCGCAGGGGCTTCCTGTCCTCCAGNNNNNNNNNNNNNNNNNNN
NNNNNNNNNNNGGACGGCGGACAGGTC------------CTCTCCAGGTCTGACGAGTGG
AAGCTGAACGAGACCAGGAAGTGCAGTCGCTGCGAGGAAGGCTTTGACGTCCCCGAGGAG
CTGCAGAAACACATTGCGGAGtGCCACCCGGAGTGCTCCCCAACGCAGGAGCGGGGT---
------GCCCTGCAGTGTATTTATTGCCCAGAGCTGTTTGCCGAAGAGAACTCTCTCCTG
AGTCACATCGACCAGGAGCACAACAGAGACAAGAAGGGCCACACTTGCACCATCTGCTCT
GAGCATTTCCACTCAGTGGAGGAGCTCTACAGCCACATGGACATCCACCAGCAGCCAGAA
TCTAGTAACCATAGCAACAGTCCCTCCCTGGTGACAGTGGGCTATACCTCTGTCTCCAGC
ACCACGCCAGACTCCAACCTTTCCGTTGACAGCTCTACCATGGTTGACGTGGCGCCACCC
TTGCCAAAAAC---CCGCGGGAGAAAGAGAGCAGCCCAGCACGCAGCTGACATTGCTGGG
TTGTCCTCTAA---------GCAGGCCAAAATCTCATACAGCTGCATTTATTGCAACAAG
CAAGTGTTCTCCAGCCTGGCTGTATTACAGATACACCTCAAGACTATGCACCTGGATAAG
CCGGAGCAGGCTCACACCTGCCAGTATTGTTTTGAGGTACTGCCCTCCCTCTATAATTTG
AATGAGCACCTGAAGCAGGTCCATGACAACCAGGACCACAGCA-----------------
-CTCTGTTGGGGAGCATGTCTGGAGGCATCCTTCAGTGTAACTTCTGCCCTGAGGTTCTA
GGCGATCTCAATGCCCTACAGGAGCACATCCGCTGCTCTCATGGCTTTCCTAGCCCGGTG
GCTA---------AAGAGAGCAATGCCTTCTTCTGCCCGCAGTGCTTCATGGGCTTCCTC
ACTGAGACTAGCTTAGAGGAGCATGTCCGTCAGACCCATTGCGATGGGAGCAGCACGCAT
TTTGACTCTCCTTTAGCGGGGACACCCAAGGACCCAGTGGTGGAGGTCTATTCATGTTCA
TACTGCACTAACTCTCCCATATTCAACAGTGTTTTAAAGCTGAACAAGCATATCAAGGAG
AACCACAAGAACATCCCGCTTGCTCTTAATTATGTAAATAATGGCAAAAAATCTAATCGA
ACCTTGAGCCCCCCT-TCCCCGGTATCTCTGGAACAAGCTACCATTAAAATAGGACAAAG
TGGATCCTCAACTCGCTCAAGCAGCGAATACATTTGCAATCAGTGTGGTGCCAAGTACAC
TAGTTTGGACCTATTCCAAACACACCTTAAAACGCATCTGGACACAGTCCTCCCCAAACT
CACCTGcccccaatgcaaCAAAGAGTTCCCCAA---TCAGGAGTCTTTGCTGAAGCATGT
CACCATGCACTTCATGATCACATCAACATACTATATTTGTGAAAGTTGTGATAAGCAGTT
CACCTCAGTGGATGATCTTCAAAAGCACTTGCTTGACATGCACACATTTGTATTTTTCCG
CTGCACTCTTTGTCAGGAGGTGTTTGACTCCAAAGTATCCATCCAGCTACACCTGGCTGT
GAAACACAGCAACGAGAAAAAAGTCTACCGGTGCACCTCCTGCAACTGGGACTTCCGCCA
TGAGTCAGATCTGCAGCTGCATGTCAAACACAACCACTTAGAGAACCAG-----------
-------GGCAAAGTCCATAAGTGCATCTTCTGCGGG-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------
>Sargocentron_rubrum_gill_6|013838|scaffold21826|m.27004
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------AACAGTGTTCTTAAGCTCAACAAGCACATAAAGGAG
AATCACAAGAACATTCCATTGGCATTGAACTACATCAATAATGGAAAGAAATCCTTGCGC
ACCCTCAGCCCTTCC-TCTCCAATATCTGTGGAACAAACTGCCTT---GTTGAAGCAAGG
CGGCTCAGCCTCTCGCACAACCAGTGAGTTCATCTGTAACCAGTGTGGCGCCAAGTATAC
CAGCCTGGACCTTTTCCAGACTCATCTAAAAACTCATTTGGATGGCCTGCAGCCTCAACT
CACTTGCCCACAGTGCAACAAAGAGTTCCCCAA---C------NNNNNNNNNNNNNNNNN
NNNNNNNNNNNNNNNNNNNNNCTCCACTTACTACATCTGTGAGAGTTGTGACAAGCAGTT
CACCTCGGTGGATGACCTACAGAAGCACCTACTTGACATGCATACCTTTGTGTTTTTCCG
TTGCACACTGTGCCAGGAAGTATTTGACTCCAAGGTGTCCACACAGCTCCACCTGGCTGT
TAAGCACAGCAATGAGAAGAAGGTGTACCGCTGCACCTCCTGCAACTGGGAC--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------
>Scleropages_formosus_red_gill|014686|scaffold2255|m.2884
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------GGGGGC------------------------
------------------------------------------------------------
------------------------------------------------GAGCTAGACCAG
GACCTATACAT-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------GTGCGACTACTGCGAGGAGACCTTCAGCCAGACAGACGAG
CTGGAGAAGCATGTGCTCACACGCCACCCCCAGCTCTCA---------GACCGAGCC---
------GACCTGCAATGCATCCACTGTCCTGAGATCTTCTGTGACGAGGGGACACTGCTC
GCCCACATCAGTCAGATGCAT------GCTAACAGGAAGCACAAGTGTCCTGTGTGTGCT
GAACAGTTCCCCTCTGTGGAGGACGTCTATTGCCACCTGGACAGCCACCGGCAACCTGAC
TCTAGCAACCACAGCGCCAGCCCTGACCCTGTGCTGGGCAGCGTAGCGTCTATGAGCAGC
GCCACCCCTGACTCTAGTGCCTCCCTGGAAAGAGGATCCACCCCAGAT---------TCC
ACGCTGAAGCCGTCCCGCAGCGGCCGCAAGATGGCCCCCTCTTCCTCTGACCGTGAAGAA
GGGGGTTCAGGTTGGTCGTCATCGGGGAAGGTGACTTACAGCTGCCCGTACTGTTCCAAA
CGGGACTTCAACAGCCTGGCGGTCCTGGAGATCCACCTGAAGACCATCCATGCTGACAAG
CCTCAACAGAGCCACACATGCCAGCTGTGCTTGGAGACTCTGCCAACGCTATACAACCTC
AACGAGCATGTGCGCAAGGCTCACCGCACCAGCAGCAGCACCAGTGCTGCATTTCCACTC
CTGCAGTTCAGCAATGTTTCTG------CCTTCCACTGCAACTACTGCCCTGACATGTTT
GCTGACATCAACACTCTGCAGGAGCACATCCGTGTTTCGCACTGCCTGCCGGCATCCGGC
TCCACCACCTTGGAGGGAAACCACGCCTTCTTTTGTAACCAGTGCTCCATGGGATTCCTG
ACTGAGTCCTCCCTTACCGAACACATCCAGCAGACGCATTGCAACAGTGCCGTGGCGAAG
CTGGAGTCTCCTGTACTGCAGCCTTCCCAG---TCCTTCATGGAGGTCTACTCCTGTCCT
TACTGCACTAACTCGCCCATCTTTGGTTCCCTTCTCAAGCTCACCAAGCACATCAAGGAG
AACCACAAGAACATCCCTCTGGC---CAACAACAAACGTCAGGCTAAGGTGGCAGACCAC
AGCCCTGCCTCTTCTGATGTTGAGATCTCTTCCCCAAAGCGCCAA-AGGCTGGCAGCTGA
TGCTACTCCGGTAAACTCTAACGGGGAATACCCCTGCAACCAATGCGACCTCCGATTTTC
CAGCTTTGAAGGGTTCCAGGCCCATCTCAAGACCCATCTCGAGTTGCTGCTGAGGAGGCA
GTCCTGCCCCCAGTGCAACAAAGAAGACTTTGAATCCCAGGAGGCCCTTCTGCAGCATTT
GACCATCCACTACACAACCACATCAACCCAGTACGTCTGTGAAAGCTGCGATAAGCAGTT
TTCGTCGGTCGACGACCTGCAGAAGCACCTGTTGGACATGCACACTTTTGTACTCTACCA
TTGCACACTCTGTCAAGAGGTGTTTGACTCAAAGGTTTCCATCCAGGTCCACTTGGCTGT
CAAGCACAGCAATGAAAAGAAGATGTACCGCTGCACGGCTTGCGCCTGGGATTTTCGCAA
GGAGGGTGACCTACAGCTGCACGTCAAACACAGCCACCTTGGTCACCCAGTGGGGTCT--
-GCTGGTAGCAAGGCACGGAAGTGCATCTTCTGTGGTGAGACTTTTGGTACGGAAGTGGA
ATTGCAGTGCCACATCACCACTCACAGCAAGAAGTACAACTGCCGCTTCTGCAGCAAGGC
TTTCCACGCCATTGTCCTGCTGGAGAGGCATCTGCGGGAGAAACACTGTGTCTTTGACGG
AGGCAATGGCAACGGTAATGGAGGCAGCCAGAATGGGACGCCGAATGGGGTGACGCAGAG
TTCCAAACGGGGAGGGGGTGGTAGCAGTGGCTCAACCACTGCTGCAGAACAAGCAGATCT
TCAGAA----------------CATACTGTTGAAGGGA---AGCCAAGATGCAGCC----
---------AACAGTCACGAGGCCAGC---GGTGAGGATGAGATGGATGCCTCGGAGCCC
ATGTACGGCTGTGACATCTGTGGGGCGGCCTACACCATGGAAGCTTTGCTGCAGAACCAC
CGGCTGCGGGACCATAATATCCGCCCAGGCGAGGACGATGCTTGCTCCCGCAAGAAGAAG
GCGGACTTCATCAAGGGCAACCACAAGTGCAACGTGTGTTCACGGACCTTcttCTCCGAG
AATGGCCTGAGGGAGCACGCACAGACGCACCGTGGCCCCGCCAAGCACTACATGTGTCCC
ATCTGTGGCGAGCGCTTCCCCTCTCTGCTCACGCTCACCGAGCACAAGGTCACACACAGC
AAGAGCTTGGACACTGGCACCTGCCGCATCTGCAAGATGCCCCTGCAGAGCGAGGAGGAG
TTCATTGAGCACTGCCAGATGCATCCAGACTTGAGGAACTCATTGACGGGCTTCCGCTGT
GTGGTCTGCATGCAGACTGTCACCTCCACTCTGGAGCTTAAGATTCATGGCACCTTCCAC
ATGCAAAAGCTGTCCTC---------CAGCAGCGGAGgtGCCGGCTCTGCTGCTTCCTCG
CCCAATG-----GCCAGTTGCAGGGCCACAAGTTCTATAAGTGTGCTCTCTGCCTCAAGG
AGTTCAAAAGCAAGCAGGACTTGGTCAAGCTGGATGTCAATGGGCTGCCT----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------
>Synodus_sp._gill_5|025725|scaffold9249|m.10355
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------AATGCTGAAGACCATGCTG-----------------
-CCCTACTGGCAAGCCTACCTGATGCCTTGCTTCAGTGTAACTTCTGTCCTGAGGTGTTA
AGTGATCTCAATGCCCTCCAAGAGCACATTCGCTGTTCGCATGGCTTTCCCAGCCCAGTG
GCCA---------AAGAGAGCAATGCCTTCTTCTGCCCTCAGTGCTTCATGGGCTTCTTG
ACAGAGGCTACCTTGGAGGAACATGTCCGTCAGACTCACTGTGATGGAGGGAGTCTGCGC
TTTGATTCCCCCTTGGCTGTGACTCCCAAGGAGCCCATCATGGAGGTGTACTCCTGCTCC
TACTGCACCAACTCCCCCATATTCAACAGTGTTTTGAAGCTCAACAAGCATATCAAGGAG
AACCACAAGAACATTCCCTTGGCACTGAACTATATAAACAATGGAAAGAGATCCCTTCGC
ACCCTTAGCCCATCT-TCTCCCATATCTGTGGAACAAACGGCGCT---CCTCAAGCAAGG
T---TCATCCTCTCGCAGTGCAAGTGAGTTCATCTGTAACCAGTGTGGGGCCAAATACAC
CAATCTGGACTTGTTTCAGACCCATCTGAAAACTCATCTAGATGGCCTACAGCCTCAGCT
CACCTGCCCACAGTGCAATAAAGAGTTCCCCAA---CCAGGAATCCCTGCTCAAGCATGT
GACAGTCCACTTCACCATTACCTCCACATACTACATCTGTGAGAGCTGTGACAAGCAGTT
CACCTCCGTCGATGACCTTCAGAAACACCTACTGGACATGCACACCTTCGTGTTTTTCCG
TTGCACCCTTTGTCAGGAAGTGTTTGACTCCAAGGTGTCCACACAGCTTCATCTTGCAGT
GAAACACAGCAATGAAAAGAAGGTCTACCGCTGCACCTCCTGCAACTGGGACTTCAGGCA
CGAGACGGACTTGCAGCTGCATGTCAAACACAGCCACCTGGAGAACCAG-----------
-------GGACGTGCGCACAGGTGCATCTTCTGCGGGGAGTCTTTTGGTACCGAGGTGGA
ACTGCAGTGCCACATCACCACCCACAGCAAGAAGTACAACTGCCGTTTCTGCAGTAAGGC
TTTTCATGCCATCGTGCTGCTTGAGAAGCACCTTAGGGAGAAGCACTGTGTGTTTG----
-----------------------------AGGGCAAGGCTCAGAACTGTGGCGCCAATGG
CTCCACGGCCGCAGGAGGGGAAGG-------TCAG-----GCTAAAGAGGATGTTGAGCT
GCAGGGAATCCTGACCAATAGCCATGGTGCTGGGGCA-----GCTGGAGGACAGCCGGCT
GAGTCCCAGAACAGCCATGATGGCA------GTGAGGAGGAGGTGGACACTGCAGAGCCA
ATGTATGCGTGCGACATCTGCGGGGCCTCCTATACTATGGAGTCCCTCCTTACCAACCAC
CAGCTTAGGGACCATAACATTCGCCCTGGGGAGAGCGCCATGA------TGAAAAGGAAA
GCTGATATGATCAAGGGTAACCATAAATGTAACGTCTGCTCCCGTACCTTCTTTTCCGAG
CCTGGGCTAAGGGAGCACATGCAGACCCATCTTGGGCCTGTCAAACACTACATGTGTCCA
ATCTGTGGGGAGCGTTTCCCCTCCCTGCTGACCCTGACTGAACACAAGGTCACCCATAGC
AAGAGCCTGGATACTGGGAGCTGCCGCATATGTAAGATGCCTCTCCAGAGCGAGGAGGAC
TTCCTTGAGCATTGCCAAATGCACCCTGACCTTAGGAACTCCCTGACGGGTTTCCGCTGT
GTGGTCTGCATGCAGACCGTCACCTCCACCCTGGAACTGAAGATCCACGGCACCTTCCAC
ATGCAGAAAACGGGCACCATGTCCACCAACCACCCCATTGTCCG--TAACACTTCCCTCT
CCCAAGACCAGCGCCACCACCAGGTCCAGAAGCTCTTCAAGTGTGCCTCTTGCCTGAAGG
ATTTCCGCTCCAAGCAGGACCTGGTGAAGCTGGACATCAATGGACTGCCGTACGGCCTGT
GTGCCACCTGTGTGGCAGCGGCTGGCTCCAAGAGCTCCAGCCCCACGGTGAACGGAGGCA
GGCAGCAGCAGCAGGGTGGAGCCACCACCCCTGCAACGACCACAGCTGCATGGATCCAGG
GGGAGAGCCTCAGCCCAGGGGAGGGGAAAGGCAAGGTGGCCTCTTCTGCATCCTCCTCCT
CCTCCATCTCCTCCTCTGCTGCTGCCAAGACGAGGTGCTCAAGCTGCAACGTGAAGTTTG
AGTCGGAGGCGGAGCTGCAGAACCACATCCAGACGGTTCACCGGGAACAGGGGGGTGACA
GTAACAGTGGGCAGCTCAGGACCCCCCAGGTGTCCCCCATGCCCAGAGCCAGCCCATCCC
AGACTGAAGAGAAGAAGACATACCAGTGCATCAAATGTCAGATGGTGTTTTACAGTGAAT
GGGACATCCAAGTTCACGTGGCCAACCACATGCTGGAGGAAGGGCTGAACCATGAATGCA
AGCTCTGCAATCAGTCATTCGACTCACCAGCGAAGCTGCAGTGCCACCTGATTGAGCACA
GCTTTGAGGGCATGGGTGGAACCTTCAAGTGTCCTGTCTGCTTCACAGTGTTTGTCCAAG
CTAGCAAGCTCCAGCAGCACATCTTCTCAGCTCACGGCCAAGAGGACAAGATCTACGACT
GCTCCCAGTGCCCGCAGAAGTTTTTCTTCCAGACAGAGCTACAGAACCACACGTTGACTC
AGCACAGCAGCTAA
