>Amblygaster_clupeoides|010460|TR22355|c0_g1_i1|m.39852
AT----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------TTATGCTTTATTAAAAACTCCTGTTGAGAAAGCATAT
TTCTTCCAGGAGGTATATCCTGTGGAATATGGACCAAAATATGACACTGCAGTTCAGGAA
CTGATGCAGGAATTAATTGCAAGACTTGAGCAATGGATGTCTGTACCAGACATGGACCAG
GTCGTGTCATGGGTCACTGCTGTTCCTGCTTTTTCTGAGAATTGTGTGCAGCTGGGGACA
AAAGACCTGAAGTTCCTGCTGCAGTACTGTCCG------------------AACCGACAC
TTCAGCCCCGCTCC------------TTCCACTTCCTCCAAGGGAGAATGCATCCTGAGT
TCTCTCGCCACCCCTCCCCCCTCCATCAAGGTTGTGGTGGCCACGGAGCCCGTGACCTAT
CACATCCAATCTGACTCAGCCTGCATGGGCATTCTGGGCCCTGGCTCTCTGGCAG---AC
GTAGTGACTGAGACCATCATCGTGACGGAGTACACCGAGGTGGAGCTCAGGACGAGCGAG
GAGGGTGATGGCGCTGCTGTAGAAGAGGATCAACCGAACGTTGTTCAACTGGTCAGTGAC
GAAATTGAGGTTAAGATGCAGAGCAGTGGACCGGGGGAGGTGAGGGCTGTCCTTGTGGAT
CCAAGTCATGTGAGCGAGGAGGTCGTGACCGTGGAGGAGTCATTGTGTGTGGCAGACTCA
GTGAATAGCCAAGTCAAGGACACCATTGTAACCATTTCAAAGGGATCAGAGCACTCTCAA
TCAGTGGATGATGACAAAGTGGTGGACTCGCTGCAGAATGTATCTGTGCAGTGGGAGTCG
ATTCCTGGAGCAGTGGTCATCGAGGCACCTGATACTCCACAGAGCACTGCTGATATGAAA
GAAAATGCTCCCTGCAGCAAAATAAGTAGTGATCCCGCTGCTGAAAATGTCACAACCTCA
AGCAGAGATGGAGAGCAGAGCGACGTCAGTAACATTATTATTCAGTGCAGTCAGCAAAAC
TGCAAG-GCAGAACCTGCTGGGTCTTTAATACAAGCTGAGACATTGCCATCACAGAAAGA
GGAC---------TCTGGTGTCGTCATGGAACCTTCTGAAGATGT---CTCAACTCCTGA
GGTAACCGAGGCTCCA------------------CAAACATTGACGCCTCGTCGTGGCCG
TGGAAGGCCAAGGAAGAGCGAGCAGAAGTCGGGTCCGGTCAGCATTCCGAGACGAAGGGG
TAGGCAGCCAGCTATAAAGAAGGAAGTTGAGGACATCTCCGTGGTCATCCCTCTGTCCTC
TGACAAAGAGAATGGCAAAGAAGTCTTGACAAACAAAGACAGAGCGGGTGAAATAGCTGG
AGAAGGGCAGCCTCAGGAAAACTACAAGGATTCTAATCTGGACCAACTGAGCAAGGCTGC
AGAGTCCAAACAGAATGGTGCTGACATTCCCAAGCCCTCTGCTGCCGGCTCCTACCGAAC
ACGGAGATCCTCGTCCTCCTCCGTCTCCTCCTCAGTTGTATCCTCCAAGGACCCACCAGT
GAAAAGCTCCCACTACCGTTACAAGTGTGACAACTGCGGCAAGACCTTCACGCGCTCGTC
GGACGTGCGGCGGCACCAGCTGATCCACACAGGCGAGCGGCCCTTCCACTGCTCACACTG
CGACAAGACCTTCCAGCACGCATGGGACCTCACCAAGCACCAGCGCAAGACCCACGGCGA
GTGCATCTTCCGCTGCCAGGCGTGCTCCACCGACTTCCCCAACCTGCGCATGCTGGCGGC
GCACCACAAGAAGAGTCACGAGGGGCCCATGCCACACACGTGCTCCATTTGCGGCGAGAG
CTTCAAGGCGGCGGAGCAGCTCGTCCAGCACCGCAAGACACACGGCGACAAGCTCCAGTA
CAAGTGCCAGCACTGCGGCGAGGGCTTCGACACGCTGCTGGAGCGCTCCAAGCACCGGCT
GACGCACGTCGGCAAGCGGCAGTTCAAGTGCCCGCAGTGCGACAAGACGTACACGCGGCG
TGCGGACGTCAAGCGCCACCAGCTGTCACATACGGGCGAGCGCCCGCACCAGTGCACCCA
GTGCGGCCGCTGCTTCGGCCTCAACTCGGCGCTCAAGAAGCACCTGGCGGTGCACACGGG
CGAGCGGCCGCACCAGTGCGCGCACTGCCCCAAGCGATTCACCCTCTTCTCCATCTTGGA
GCGTCACCAGCGGATGCACACGGGCGAAAGGCCCTTCTTGTG------------------
---------------------------------------------CTCCCAATGCGGCAA
GCGCTTCCTGTCGCTCGGCGAGCTCTCCAAGCACTACAAGTCGCACACCGACGAGCGGCC
GTTCCCGTGCGCAATGTGCGGCAAGCGGCTCAAGTCCAAGCGGGCGCTGCGCGAGCACAT
GCTGGTGCACACGGGCGAGCGGCCGTACCCGTGCTCGTACTGCGGCAAGTGCTTCACCAA
GCCCTTCGCGCTCACCCGCCACCATCTCATGCACACCGGCGAGAGGCCCTTCGCATGCTC
GCACTGCGACAAGACCTTCCTGACGGCAGCCGAGGTGGCGCTGCACGAGCGCGTGCACAC
GGGGGAGCGGCCCTACGCCTGTGCCGAGTGCCCCATGAAGTTCCGCAGCTCATCGGAGCT
GGCGCGGCACAGGCGGAGCCACACTGGA---GAACGGCC------CCATACTTGCACGAT
CTGCTCCAAAGCATTCACCAGCCCGGCCAAATTGAACAAACACAAGTTGACGCATGCTAA
GGACAAG---GCCGTTACTTGTGTGGGCTTGCCTGATAATTCTGAGGGACTGCATCAGGC
TGCCAGCATAGTGGGGGAGCACAGGGTTGTTCTGACCTTAACAACAACCCAGAATGCAGT
GGATATGTGA
>Corydoras_julii_viscera_mixture_8|007860|scaffold13899|m.9672
G-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------ACAGCCAGGTGGCGCCCATCA--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------GACG
CGGGAGACCAAGGAAGAACTGTGGACCAACGAAGATGGCTCAAAAACACAGAAGAAAAGG
ACGACCACCGTCACACAGCAAACACACAGCG-----------------------------
----------AATGAAGAAGACGTTGGCAGTAATACAGAAAAAGAAGCCAGAACACCTGA
ATCTGAAGCGACCAGTGGGGACTCCTGTGACGCC--------------------------
-----------------------ACCTTACCGAACCCTCATCAGGGCGGTCCT-------
------------------------------------------------------------
-GAGAACCCCCGAGCTCGTTATGTGTGCAGCACATGTGGGCGCAAGTTTACCCGCACGTC
------------------GNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNGTTCCCAGTG
CGAGAAGACGTTCCAGCACGCGTGGGACCTGACCAAGCACTGCCGCAAGTTCCACGGCAA
CGCCACGTTCTCCTGCAGCCTCTGCTCGAGCCAGTTCGTGAACCTTCGCGCTTTGACGGC
CCACCACAAGAAGAGCCACGGCAGCGAGGTGCCGCATTACTGCTCCATCTGCGGCCTGGC
CTGTCCCACCGGCGCGGCGCTAATCCAGCACCGGAAGCTGCACAGCGTGACCCAGCAGTA
CTGGTGCGAGCAGTGCGGCGAGGGCTTCGACACGCTACTGCAACGCTCGCTGCACCGCCA
GAGCCACCGCATCCATCCCAAGTTCACCTGCCCGCAGTGCGACAAGACGTACTCGCGCCG
TTCCGACGTCAAGCGC--------------------------------------------
----------------------------------------CACATGCTGAGCCACACCGG
CGAGCGGCCGCACAAGTGCAACCATTGTGGAAAAAGTTTTATGCTGCGGGCAGGCCTTCA
GAAGCACCAGCTGATCCACACGGGCGAGAAGCCGTTCCCCTGCCCGCACTGCCCCAAAGC
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNCTCGCAATGCGGCAA
GCGTTTCCTGTCGCTCGGCGAACTCCTCAAGCACGACAAGTCACACACGGACGTGCGGCC
TCATTCCTGCGCCCAGTGCCAGAAGAGCTTCAAGTCGAAGCGGGCGCTGCAGGTTCACGC
TGTCAGTCACACCGGCATGCGGCCGTACTCCTGCTCCTACTGCGGCAAAAAGTTCTCCAA
AGTCTTCGCCCTCAACCGGCACCATCTGATCCACACGGGGGAGCGACCCTTCGCCTGCTC
GCACTGCGACAAGACCTTCCTGACGGCCACCGAGCAGGCGCTGCACGAGCGCGTCCACAC
CGGAGAACGACCCTACAGCTGCTCCGAGTGCCAGTGGACGTTCCGGAGTTCCTCGGAGCT
GGGCCGCCACAAGCGCACACACGGCCGC---CGGCTCGC------CTACTCCTGCGGTCA
CTGTTCCAAAACGTACACCACCGCCGCCAAGCTAAAGAAACACATTCGCCTCCACATGCT
GATGGAACCTCACAGCAGGGGTCCTGTGGAGATCAGCCACACGGTGGAGGTGC-------
--------------------------------CAGCATCCACAGTGGCTTAG--------
----------
>Distichodus_sexfasciatus_gill_4|022368|scaffold31960|m.39201
ATGGACAAACAACACTTAACGAAAACAGAAGGCTGTAGACTCCCGTTCTCCTCTTTGCGC
CTCCTGGTTCCTCCTTTCCACCTGATGTCTGCGTTCATGTGGCACGTCCTGCAGCAGAAA
CACGTCCTGCATTACGACAAGCTGGAGGAGTTTGTGTCCATGGTCACAGAGACCGTTCCA
CATCTGCTCAGTTACAGACAAAGAGCACAACTTATCCTGGGGTTGAGGGCAAGGATGGTT
TTAGAGATATTACGAGACCGAGCAGACACCACAGTTGTTCAGACTCACTTGGATAAAATG
CACCTACCTTCCATTCCAGCTGGATGCCCACTAACCGTTGATCCAGATTTAGAGCTGCCA
GTTTCTAACTTCAGGGCTCTCGTTCTTGCATTGCTGAAGGACCCAGCAGAAAAGGCATAT
TTCTTTCAGGAGGTCTTTCCTGTTGAATATGGCTCACAGTATGATGCGGCACTGAACGAC
TTAATGTGGGAACTGCTGTCCTGTTTGGAAAGGCTTCTTCCAGTTCCTGACTTTAAAAAG
ACGGTGTCTTGGCTTAACGCTGCTCCTGCTGGCTTGAAAGAGTGCATGGAATTTGAATCT
AAAAACTTTCAAGCGCTTTTACAGCAGCATAAAATCACTGGCAATGTGGACAATCAGTAT
TACAGTAAAGTTTCGAAATTAGGAACACTGTCTTCCTCCTCAGGAGACTGCATCCTTTCC
TCTCTTTCCA---TTCCTCCATCAACACATGTTGCAGTCACTACAGAGCCCGTGGTCTAC
CACATCCAG------CCAGCAGCTGTGACCATCTTGAGCCAGAGTTCCCTGGGAGGACAA
GTAGGCTCCGAGGCCATAATCGTGACCGACTACACTGAGGTTGAGCTTACCAGCAATGAA
GTAGTGGATGA---GGTTTTGGAGACCGGTCACATCTGCCCTGAGGAAATGGAAGGAAGA
GGGTTGGagctaaatacagagaACAGC---------TCTGTGGTGGCAGCCCTTGGTGAT
GAGTGTATTATAGAAGAAGAG---------------------------------------
---------------AAGATAATTACTGTAGGC---------------CAACAGTTAGAG
ACCATCAGTAACAGCAAAGAAGAGAAAATTCTTTGTGACAAATCTACACAGTGTGACAT-
----------------------------------CTTAACAGACTTTCTGAGAGATGAGG
GAAGTTTATCC-------------ATCAATCATCTAGCAGTGGAAG----------CTCT
AGAGAATTTGGAAAA---------------------------------GGTCAAGAAAGC
TGAAAGAGCTGAACTTGGTGAG---GGGAGACAAAATGAAGTTGTCCAGCAAGAGAAAGA
GGTCACACATGTATCTGAGACTGGTGCTGAAACTGACAAACAAGTAAACTCGACACCAAA
GGAGGAACAAATCTCGGAAAGCGCATGTGTAGACCAGACTGTGCCGCACCGGCAAGGACG
AGGCCGACCAAGGAAGAACGCGGTACCGTTGAAGGTGGTTCAGACAGGGAGGCGGAGGGG
ACGTCCCCCATCAGTGAAAGTGGAAAAAGCC-------CCAGAGC---------------
--AAGAGGGAAGTGAAGATGGCAACAGAAGAAATAAAGACAGAACTCTTGGCAACCCTGA
AGACGAGCAGAAT----------------------------------------GGCTTGC
AGAGTAC--------------------------ACCATCACCTGGTGGTCCCCA------
------------------------------CACACCCGAATCGCTCAAGACAGAAACTAC
AGAAAACCCTCGTGCTCGTTACCTGTGTAACATCTGTGGCAGGCACTTCACCCGCACGTC
TGATGTCCGCCGACATCAGCTGACGCACACGGGTGAGCGTCCCTTTCACTGCACTCAGTG
CGAGAAGACCTTCCAGCACGCGTGGGACCTGACCAAGCACTGCCGTCGGCACCACGGCGA
GGCCACATTCTCCTGCCGGCTCTGTCCGTGCAGTTTTGTCAACCTCCGTGCCCTGACCAG
TCACCACAAGAAGAGCCACGCCAGCGAGCTGCCCCACTACTGCTCCATCTGCGGCGAGAC
CAGCCTGAGCGCCAGTGCCCTGATTGAGCATCGCAAAACGCACAGCGTCACGCACCAGTA
CAGGTGTGAGCAGTGCGACGAAGGCTTCGACACCTTGCTCGAGCGCTCCATCCACCGTCA
GAGCCACCGGCGGCACCACAAGTTCAAGTGCCCGCAGTGCGAGAAGACGTACTCCCGCCG
GGCTGACGTCAAGCGCCACCTGCTGACCCACTCGGGTGAGCGCCCACACCAGTGCGGCCT
GTGCGGCAAAACCTTCGCCTTGCGCTCCGGGCTGCATAAGCACCAAATGACCCACACAGG
CGAGCGGCCATTCCAGTGCCCGCACTGCCCCAAGTCGTTTAACCTCCTCTCAATTCTGCA
CCGACATGAGCGCATGCACACAGGCGAGCGACCCTTCCTGTG------------------
---------------------------------------------CTCGCAGTGTGGGAA
GCGCTTCCTCTCTCTGGGCGAGCTGCTCAAGCACAAGAAGTCGCACGTGGACGAGCGGCC
CTACTCGTGCACCCAGTGCCACAAAGGTTTCAAATCCAAACGAGCCCTGCGCGAGCACGT
CCTGAGCCACACAGGCACGCGTCCATACGCGTGTCGCTACTGCGGGAAGAGGTTCACCAA
ACCATTCACTCTGAACAGGCACCACTTGATGCACACGGGTGAGAGGCCCTTTCCGTGTAC
GCAGTGCGAAAAGACCTTCCTCACCTCCACAGAGCTGGCCCTCCACGAACGCGTGCACAC
AGGTGAGCGGCCCTACGCCTGCACAGAGTGTCCTTGGAAGTTCCGCAGCTCCTCCGAACT
GGCAAGGCACAGGCGCACCCACGGCCAG---CAGAGGAT------GTTCGCCTGCAGCTA
CTGTCCCAAAACGTATACCAGTGCTTCCCGCCTGAAAAGTCATGTACGGGTCCACGCGTG
GGAGGAG---GAAGTCAAGTGTCCTGTCAGTGTAAGCTGTAAGGTGGAAGTGCAGGAGGA
CA---------------------------------CGCTTACAGAGGGC-----------
----------
>Gasteropelecus_sp._gill_3|019520|scaffold31175|m.33407
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------ATGCACACAGGTGAGAGGCCCTTTTTGTG------------------
---------------------------------------------CTCGCAGTGCGGCAA
GAGGTTCCTCTCTCTGGGTGAGCTAATTAAACACGACAAGTCGCACACGGACGAGAGGCC
GCACCCCTGCACCCAGTGCAAGAAGAGCTTCAAGTCCAAGCGAGGGCTCCGTGAGCACGT
TCTCAGGCACAGCGGCATACGGCCGTATGCGTGCAAGTACTGCGGGAAAAGGTTCACCAA
GTCATTTGCCTTGAACAGGCACCACCTGATGCACACTGGAGAAAGGCCATTTGCATGCAC
CTGCTGCCAAAAAACTTTCCTGACCTCCATGGAATTGGCCCTGCACAAGCGCATGCACAC
CGGTGAGCGGCCTTACAGCTGTTCGGAGTGTCCCTGCAAATTCCGAAGCTCCTCAGAGTT
GGCGAGGCACAAGCGCACCCACAGCAAGATCAAGAGAGC------GTACGCTTGCAGCTA
CTGCCCCAGAACATTCCCCAGCATGACCAGACTGACGCACCATGTGCAAATCCACACAAG
GGTCAAC---CAGGCCAAGTGCCCTGTGACCATCAGCCAAGTGGTAGAAGTGCAGGAGTC
TG---------------------------------TGCTTGCAGTGGGCAAGGTTGCAGA
AGCCCTGTTA
>Lepidogalaxias_salamandroides_Head_2|020530|scaffold19289|m.26522
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------ATGGTTCACACGGG
GGAGCGGCCTTTCCAGTGCTCCCACTGCCAGAAGCGCTTCACCCTGGTCTCCATCCTGGC
CAGGCACGAGCGCATGCACACGGGCGAGAGGCCCTTCCTCTG------------------
---------------------------------------------CTCGGAGTGCGGGAA
GAGCTTCCTGTCCCTGGGCGAGCTCTCCAAGCACGACAAGTCCCACACGGACGAGCGGCC
ACACGCCTGCAGCCAGTGCGACAAGCGCTTTAAGTCCAAGCGTGCGTTGCGCGAGCACAT
CCTGGCCCACAGTGGGGCGCGGCCCTACCCCTGCTCCTACTGTGGAAAGATGTTCACCAA
GCCCTATGCCCTGACTAGACACCACCTGATGCACACGGGCGAACGACCCTTCCCCTGCTC
TCACTGCGGGAAGAGCTTCCTCACTTCGGGGGAGCTGCTTCTGCACCAGCGCGTGCACAC
GGGCGAGAGGCCCTACCCCTGCCCACACTGCCACATGAGCTTCAGGAGCTCCTCAGAGCT
GGCCAGGCACAAGCGCTGCCACACCGGG---GAGAGGCC------CTACTCCTGCCTGCA
GTGCCCCGAAAACTTCTCCTGCTCGGCCAAGTTAAAAAAGCACATGAAGAGCCACTCGGG
AAAGAAG------------------GGGCTCTCTGACTTTAGGACAGGACTGGAGCAGGC
AG----------------------AGGCGGATGACCCACAGCAGGAGGAAGGAATGC---
-----CATGA
>Sargocentron_rubrum_gill_6|013954|scaffold21966|m.27233
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------ATGCTGATGAAGCACCTCCATGTTCACACAGG
AGaGCGGCCTTTCCAGTGCTCCTACTGCCCAAAGAGGTTCACTCTGGTGTCCATCCTCGC
CAGGCATGAGAGGATGCACACAGGGGAGAAGCCTTTCCTCTG------------------
---------------------------------------------CTCCCAGTGTGGCAA
AGGCTTTCTCTCCCAAGGAGAGCTCTCAAAGCACCACAGGTCCCATGTGGACGACAGGCC
CTATTCTTGCACCCAGTGCGATAAGCGCTTCAAGAGCAAAAAAACCCAGCAGGAGCACAT
CTTCTCCCACACCGGCGCCCGCCCGTACCCATGCACCTACTGCGGGAAAGGCTTCACCAA
GCCATATGCACTGACCAGACACAATCTCATTCACACGGGAGAGAGGCCGTTCCCTTGTGG
CCACTGTGAGAAGACGTTCCTCACCCTCAGCGAGGCTCAGCTACATCAACGTATTCACAC
AGGGGAAAGGCCCTATCCCTGCACCATGTGCGAGCTCAAATTCAAGAGCTCCTCAGAGCT
GGCACGACACAAACGCAGCCATTTAGGC---ATGAAGCCGCTGAAGCCGTACTGTGAGCA
GTGCATGAAAACATTCACCTCCAAAGCCAAGCTGAAGAAACACATGGNNNNNNNNNNNNN
-------------------NNNNCTCAAATGCCTGAACAATCCAAGTAACTGA-------
------------------------------------------------------------
----------
>Synodus_sp._gill_5|015236|scaffold20331|m.26134
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------ATGCTGGTCAAACACCTGAAGGTTCACACGGG
GGAGAGACCCTTCCAGTGCTCCTACTGCCCCAAGCGCTTCACACTGGTGTCCATACTGGC
CAGGCACGAGAGGATGCACACGGGGGAGAAACCCTTCCTCTG------------------
---------------------------------------------CTCCCAATGTGGGAA
GGGTTTCCTGTCACAGGGGGAGCTGTCCAAGCACAGCCGCTCCCATGTGGACGACCGTCC
TTACTCCTGTGACCAGTGCGACAAGCGCTTTAAGAGCAAAAAGACCCAGCAGGAGCACAT
CTTCTCCCACACCGGAGCTCGCCCGTACCCCTGCACCTACTGCGGCAAGGGCTTCACCAA
ACCCTACGCCCTGACCCGGCACAACCTGATCCACACAGGGGAGAGACCCTTCCCCTGTGC
CTACTGCGGGAAGACCTTCCTCACCCAGGGGGAGGCCCAGCTGCATGAGCGTATCCACAC
TGGGGAGCGACCCTACCCCTGCAATGTGTGCGAGCTCAAATTCAAGAGTTCCTCAGAGCT
GGCGCGGCATAAACGCTGCCACTCCGGG---ACCAAGCCGCTGAAGCCTCACTGTGAGCA
CTGCGCCAAGACCTTCACCTCCAAAGCCAAGCTGAGGAAGCACATGGAGACCCACGCAGA
CATGGGA-----------------------------------GAGGCACCTACATCAATG
GAC-----------------------TCGGACTTGCACTTGCAAACAGAATGA-------
----------
