>Amblygaster_clupeoides|029421|TR5148|c0_g1_i1|m.9675
ATGGAGTTCCCAGGGCACAGTCAGCAGCTCCTTGCGAGTCTGCGCTCCCAGCAGCAGCAA
GGTTTCCTCTGTGACTGTTTAGTGCAGGTGGGTCCTTCGCGCTTTCAGGCCCATCGTGCC
GTATTGGCCTCCTGCTCCCCTTTCTTCCACATGTTCTACTCCGAACACCCGCTGGGCACT
GGTGCCAGCTCCGCAGGACCCCGCAGGGAAACAGTTGTCACAATCAATGGGCAGATTGTC
ACCCCGGCAGCCTTTGGGCTGCTGCTGGACTTCATGTATGAGGGGGTGCTGAAGCTGGCT
G---------CCCACCCTCCACCGGAGGATGTGCTGGCTGCAGCAAGCTTCCTGCACATG
AATGATGTGGTGCAGGTCTGTAAAAAGAGACTGCAGGGCCGTGGCT---TGGCTGAGGCC
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------
>Corydoras_julii_viscera_mixture_8|006706|scaffold11551|m.7961
A-----------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------GCACC
ACCTTTACAGTGAACGGGGGGCCGGACACAGACACAGTCACCATCAGCGGAGATATCGTG
ACTCCACAGGCGTTCGGACTGCTCCTCGATTTCATGTATGAGGGGGTATTGCGATTGGCA
C---------CTCACCCTCCTCCGGAGGACGTGCTAGCTGCGGCCAGTTTCCTGCATATG
AACGACGTTGTGCGTGTCTGTAAAAAACGTTTGCAGGGGCGTGGCC---TGGCAGAAGCA
GACAGCACCCGGGCAGAGGAGGGAGCTGGAGAGAATGGGGGGGAAAAGAGGGCT------
-------------GTGGGGAGGCTGTTGGGTAACATGAGTAACATGCAGGA---------
--------GGTGGCAGGAGGTCCCAGTGTTTC---CTCAGATGCATC---ATCACCTTCA
GTT------------------------CAGC---ACGTTCCCATCATCACTGGCACCAAA
ACAGAAAGCAACCTGGCAGTGCCCACCTGCCCCACACACCATGCT-AGTCCAGACATGGC
CGACACCACCCAACCGGGCATGGACTCCCTCCCTGCCGTG--------------------
-CAGGAGTCTTCTCCTGGACCTGTTAAAACGAATCAATCTGCAACCTCtggcaGCGTGGA
GTCGGCCCTGTCCAGCCCATGTAGCACAACCGAACTGGTTTTGACCGGTACAGAGGTGCA
---CAGGCTCCGGACTCGTGAGGAGTGTGTCCAAGATCAGAC------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------CTTCACCGCC---------------
-------------
>Distichodus_sexfasciatus_gill_4|012099|scaffold18038|m.19882
ATGGAGTTCCCTGGACACAGCCAGCAGCTTTTGTCAAGCTTgcgctcccaacgtctgcag
gggtttcTGTGTGACTGTACAGTGAAGGTCGGCCCCACTCGTTTTCTGGCCCATCGTGCT
GTGTTGGCGTCCTGCTCTCCGTTCTTCCATATGTTCTACTCCGAACACCCCATGGGAAAT
ACATCCACGGTAAATGGAGGACCAGAAAGAGACACGGTCACCATTAATGGGGACATTGTG
ACCCCTCAAGCCTTCGGATTGCTTCTTGATTTTATGTATGAGGGAGTGCTGAGACTGGCT
G---------CTCACCCTCCTCCAGAAGACGTACTTGCAGCAGCCAGCTTCTTGCACATG
AATGACGTGGTTCGAGTGTGTAAGAAAAGACTGCAGGGTCGTGGAC---TGGCTGAAGCA
GACAGCACCAGGGCAGAAGATGGAGGCAGCGAGACTGGTGGAGATGGGCCGACTTTTGGT
GGCACATCTGCAGAGGAAAGGACTAATGGGGAAAGAGAGAGAAATGCAGGAAGAGGACTG
GTAGTGGAAGTGCAGGGAGCTGCAAGTGCTTCGATCTCAAATTCAAC---ATCACCCTCA
ATAGCACAGCATCCTCAGCCAAGCCAGCAGATACCTTTTCATGTTGACACTAAAACTGAG
ACCATGAGAATGA---------------ATGTTGTTGACTTGGGC-AGTCCAGACATGGC
AGACACGACTCAGCCAGGTATGGATTCTCTTCCAGGAACAAGTGATTCCGGGCCAGGTTT
GTACAGTTCGTCTCCTGGGCCTGTTAGAGCAGCGACGTCAGCAACACCTGCTAATCTCGA
GT---CGCTTTCAAGTCCCTGTAGCAcaacagaattggttcagacAGGGACTGAAATT--
-GCCAACGTTATGGTTCTGAGTGCTGTTATTAACTGCCAGACTAGTGACATTGCACACAT
GTCCGTGTCAAAAGAAGCCAATACTG----------------------------------
--CAAAAGCTAAGCAAGCCCAGCGTAATGGACAGCGGGCCACTCGTGCAAGACTTGCAGC
ATCACAGCAATCTCTAAGACAAACCGTGAGAGGTTTGGATCAGCAACCGCGTTCTACAGC
AGCATTGTCTTTAGCAAAAAGAGGAGCTGAGCAAGAAGCTGAGGAGGAAGATAGGGTGAA
GGTAAAGGTAGAGGCCATTGTTATCTCGGACGAAGAACCAGAAGACCTAGATGAGACGGT
TGTAATGAACAGGGGTCAAAGCAGAGATGCAGACTTGGAGGAACGAGAGGAATATGACAG
CAGCCATGATGTAGAGGAGATCACCAGTGCTCATTTCATGCCGCCCCACTCGTTAATGCA
GCTTTCCCACGATCACCAAGAACCCCTTTCCTTCCCTCTTTCTCCGCAGGGTCCAAGTGC
TTCCTCTTCTGATGCGACTAACGTTAGCTTTTCCTCGTCCCTTTTTCAAAACTCTGGTCA
GCAATCAGAgcagcaaacaATTTATTTTGAAGAGCTTCAGGGTTCTCTTGGGAATTACGT
GGAAGACGTGCCTACGTGCAACACTTGCGGCAAGACGTTTTCATGTGCTTACACACTTAG
GAGACACGCTATAGTACATACAAGAGAGCGTCCCTATGAGTGTCGTTACTGCTACCGTAG
TTACACACAGTCTGGGGACCTGTACAGGCACATACGGAAAGCTCACGATCATGACTTGCC
AGTCAAACGTAGCAGAACAGAATCAGACCCTCCTCCTTCTCCACCT---------CAGCC
TCCTCAGACATAA
>Gasteropelecus_sp._gill_3|006036|C960603|m.52128
ATGGAGTTCCCCGGACACAGTCAGCAGCTCCTGGCCAGTCTGCGCTCCCAGCGCCTGCAG
GGATTTCTGTGCGACTGTACTGTGAAGGTTGGCACCACTCGTTTCCTGGCTCACCGTGCC
GTGCTGGCCTCCTGCTCCCCATTCTTCCACATGTTCTACTCTGAACATCCAGTCGGGAAC
AGGTCCACGGTCAACGGCGGTCCAGAGAGAGACACCGTCACCATTAACGGAGACATAGTG
ACCCCTGCAGCATTTGGGCTTCTCCTTGACTTTATGTATGAGGGGATTCTGCGATTGGTA
A---------CTCACCCCCCTCCTGAAGATGTGCTTGCCGCAGCAAGTTTCCTGCACATG
AACGATGTGGTCAGAGTGTGCAAGAAAAGGCTGCAAGGCCGAGGAC---TGGCGGAGGCA
GACAGCACCAGGGCAGAAGAGGCGGGGAGCGAGGCGGGGCGCGA------------TGAT
GGGTCATCTAGAGAAGGAAGGTCAAACGAAGCAGGGGAGAGAAATGATGGAACGGGATTG
GTAGCG---------------GTCAGTATTTCGGGATTGAATGCATCTTTATTACCTTCA
TTATCACAGTGCTTTCAGCCAAGCCAGCAAA---ACTCTCACGTGGACACTAAAACTGAG
ACAGGTGCTGGAGAGCCTCGAATCTCTCACAGTGCAAATCTGGGC-AGTCCAGACATGGC
GGACACTACTCAACCTGGCATGGACTCTCTGTCAGCAATGAGCGATTCTGGGCCCAGCTT
GTACACATCCTCTCCCGGGCCTGTTAGGGCTGGAACATCAACAACGTCATGTAGTGTCGA
GTCTGCGCTTTCAAGCCCTTGCAGCTCCACAGAACCAATTCTGACCGGGACAGAAACTCA
GCCCAGCATCTCGACTGTTAAAACTCTGCTTTACGTGGACGCCAACCGATCTGGAGGCTC
GTCC------AAAGAAACCAGCACGGTGCTCGCACACGGCAGCTCTCAGCACGGTTCGAC
GACAAAACCCAACTCTGCTCAGCGCAGAGGACTGAACTTCACCATCTCA------GTACC
AACTCAGCACGGTCCGAGTCAGACTGAGGGGAG---------------GCAGCCTTCAAG
AAGTTTGGCTGAACAGCAACCGAGCTGTGAACCGGAGACGGACGATGAAG---GGGTGAA
GGTAAAGGTGGAGGCCATCGTGATCTCAGATGAAGAGCCAGATGATGTTGAGGAGACGCT
GGGGCATGTCAGAGATCAAAGGAGAGGTGCCAGTTCAGAGGAGACTGAGGATTATGACAG
TAACCATGATGTCGAGGAGATCACTAGTGCGCACTTCATACCTCCCCACACACTACTGCA
GCTCCCCCACGATCACCAAGAACCACTCTCTTACCCCATTTCACCACACGGCCCTAGTGC
TGCATCTTCTGAAACG------GCTAGCTTTCAGTCCTCCCTTTTCCCAGCTGCCAACCA
GCAGTCGGAACAGCAGCCGATCTACTTTGAAGAATTTCACGATCCCCTTAGCAGTTACAT
AGAAGACGTGCCAACATGCAACACTTGCGGAAAGACATTTTCCTGCGCTTACACGCTGAG
GAGACATGCCATAGTGCATACGAGGGAGCGTCCTTATGAATGCAGCTACTGTTACCGTAG
TTACACGCAGTCTGGAGACTTATACAGGCACATAAGGAAGGCACATGATCACGACCTGCC
AGTCAAACGCAACAGAACAGATAATGATCCTCTCCCTTCACCACCTCTTCCTCAGCAGCC
TCCCCAGACATAG
>Pantodon_buncholzi_mixed|012573|scaffold15454|m.20423
ATGGAGTTTCCCCAGCACAGCCAGCAGCTGCTGGCCAGCCTGCGCTCGCAGCGTCAGCAG
GGTTTCCTCTGTGACTGTACGGTACAGGTGGGGCCCGCCCGCTTCTTGGCGCACCGCGCC
GTGCTGGCGTCCTGCTCGCCCTTCTTCCACATGTTCTACTCCGAGCAGCCGCTGGGCAAG
CG------------------------AGACGCCGAGGTCaccatcaacggggagATTGTC
ACGCCCGCGGCGTTCGCGCTGCTGCTGGATTTCATGTACGAGGGCACGCTGAGGCTCTCC
GAGCAGCAGCAGCAGCCCCCGCCCGAGGACGTCCTGGCGGCCGCCAGCTTCCTGCACATG
AACGATGTGGTGCGGGTGTGCAAACGCAGGCTGCAGGGCCGGGGGC---TGGCGGAGGCG
GACAGCACGGAAAGCGGGAGCGTCGGGGCTCCGCTGGGGGCTGC------------CGGC
GGGACGCCC------------TCTGCCGGGGTGGGCGGGGCCGCT---------------
------------------------------------------------------------
---------------------------CAGT---ACGCTCGCGCAGTCGAGAGGAAGACG
GAGGAGCAGCAGGAGATTCCCATTCTCGACACTTTAAGTAAATGC-AGTCCGGATGTCGC
CGACACCACCCAACCGGGGATGGATTT--------------GGGAT--------------
-TAGGCGTCGGCTGTTGTACCGGTT----CCACCCAACCGAGACCCAGAAGTCAAGGGGA
GTCTGCGCTGGCCAGTCCGTGCAGTACCAGTGAGGTG-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------TACGCCAG
CAGCC-------------------------------------------------------
---------------------ACCACCCTTCTTCCTCATCC-------------------
---------------------------TCTTTGCTCAGACTTCCTACCCATCTCATCTCT
GCAA-CGGAAAAGCACACAA---------------------ACCCCACCGTGACTCAGGT
GGA---------------------------------------------------------
----------------------------------------CGCGGCTACCACCAGCCCAG
TGCGGATCGCACCGGTGACCTCCGAAGACCC---TGTAATGCTAATGCCCA--------A
AGTCATCCGC--------------------------------------------------
-------------
>Sargocentron_rubrum_gill_6|023113|scaffold6600|m.7492
------------------------------------------------------------
------------------------------------------------------CGGGCC
GTCCTGGCCTGCTGCTCGCCTTTCTTCCACATGTTCTACTCTGATTCCCCAGGGGGTGGA
AA------------------TGGTTCCAGCAGCTCCGTCACGCTGGACAGCGATATTGTC
AcggctgctgccttcgggttgctcttgGACTATGTGTATGAAGGCGTGCTGCAGCTGGAA
G---------CTGCTCTGCCAGTGGAGGACATATTGGCGGCAGCCAGTTTCCTGCATATG
AACGAGGTGGTGCGGGTGTGCAAGAGGCGGCTGCAGAGACGAGGGCCTGTGGCTGAGGCA
GACAGCACTCGTTCTGAAGAGAGC------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------
>Synodus_sp._gill_5|014922|scaffold19985|m.25518
ATGGAGTTCCCTCTGCACTCCCAGCAGCTGTTGTCAGCCCTGCGTTCTCAGCGCCAGAGG
GGCTTCCTGTGTGACTGCACCGTGCTGGTAGGCTCGTCCCGTTTCCTCGCTCACCGGGCC
ATCCTGGCCTCCTGCTCGCCCTTCTTCCACATGTTCTACTCTGAGCCCCCGGGGGGTGCC
AG------------------------CTCCAACGCCGTGACGCTGGACAGTGACATCGTG
ACGGCCGCTGCCTTCGGCCTGCTGCTGGACTTTGTGTACGAGGGCGTGTTGCGTCTGGAC
G---------CTGCGCTGCCCGTGGAGGACGTCCTGGCGGCCGCCAGCTTCCTGCACATG
AATGAGGTGGTGCGCGTGTGCAAGAGGCGGCTGCAGCGCCGCGGCCCGCTGGCGGAGGCC
GACAGCACACGGCCCGAGGAGAGCGCCGGC---ACCCGAGAGGC---------------C
GGGGTGCCCGAGAGAGGCCACGGCAGCGCCGAGGGGGCGGGG------------------
---------------------TCCGGGGTCGC---CATGGAAACA---------------
----------------------------------NNNCCGGTGAAGTCGGAGGGGAGGTG
CGCGGGGGTTTCCGGGGCGTCGCCGGCCAGGGCACAGACGCCGCTGAGCCTGGACATGGC
GGACACCACCCAGCCCGGCATGGATGCCCCAGCCCCCCCG--------------------
-CCGCCAGGGGAGCACGGCCTGGGGAGGGCCTCGGGCTCCGCACCCCCCTCTAGAGCTCA
GGGGGTG-----------------------------------------------------
---CAGGGTTTGGCTACGGGGGGC------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------CAGGGGGGGGAGGGG----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------
