>Amblygaster_clupeoides|024870|TR42902|c0_g1_i1|m.65830
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------GACGACCTCCACAGCCTGGTGTGTGCTGTAGACCG
GTCACTAGCTGACTGCCTGCAGTTGCTTCAGGAGGGCTGTCCCTCAGAACAGGTGGTTCA
AGTGCTGTCTCGTGTCCC---CATGGCCCAAAAGTTCTGCAAGTACTGGATG---TGCCA
GGCCAGGCTGATGGAGCGAGAGGGCAACTATGAAGTTCTGCCCCTGTTTGAAGAAGCTGT
T---CGCCTGGTGAGGGAGCCAGTAG--------------------------ATGAATTG
CGGGCAGTGGTGTTTGAAATTCTGAAGAAAAAGGAGACCAAGGA------------AATT
TCAGGACAAGGAACACGCATCAACAAGGAGACTATGGAGGAGCAGAAAGAGGAGGCAGTG
ATAACTGAAG---------------------ACAATGTCCTGTTCACTCCTAAGGC----
----------------------TGTGAGCGCTTTCATCCGCGGTGTGAAGGGAGACTCAT
CCGTT-------------------------------------------------------
---GTGAAATACAAAATCACAG----------------------CCACTCCAGGCGGGCG
AAGGAGTCAGCA---TCAGGAGCCCTTGTGTGTGGATG----------------------
------------------------------------------------------------
-------------GGCAGGAAGTCCGCTTCCTCACTCCTGTGCGTCGTTCAGTGCGCATT
GAG--------AGGTCTGCCCCAAGTTACCCATCAGCACTGCAGGAGCAGGACCCTTGTG
TGGCCTCCTTTCGGGACCTGCTTTCC------------------------TCTTCTTCCT
CCCCTTACATTGAAAAGTCCCCACTCTACATCTTCAGGGAAAATGAAGCCCTCAAAGACC
AGGTGCAGGTTCAGCTTTTCCCAGAGGAAAGT----------------------------
--TAG
>Corydoras_julii_viscera_mixture_8|002421|C1218989|m.27027
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------CAGGTGAGGGA
CGTTCTGTCTCGGGTTCC---GATGGCACAGAAATTCGCCAAGTACTGGATT---TGTCG
CGTGCGACTGATGGAGAGGGAGGGAAACCTGAATGTGCTGCCAACATTCGAGGAAGCTGT
G---AGAACCGTACGAGAGCCGGTGG--------------------------ATGAGCTG
CGCTCCGTCGTATTCGATATCCTGAAAAAGAAAGAAGCTGA---------------AGCT
TCATCATTGG---------------------CTCTAAAAGAGGAAGAAGATGTTGGTGAC
AGTAAAGAGG---------------TGGAGGAGCAGAACATCTACACCCCAAAACC----
----------------------TGTTGGAGCACTGATTCGTGGAGAGCGAAGAGACTCAT
CAGTA-------------------------------------------------------
---ATCAAATACAAGATCACTG----------------------CTACTCCAGGTGGGAG
GAGAAGTCAGCAGAGTGAGAAACCAGGCCGTGTGAACG----------------------
------------------------------------------------------------
-------------GCAGCGAAATCCGGTTCTTCACCCCCGTACGCCGCTCGACGCGCATC
GAG--------AAAACGATGACTCGTTACCCAGCATCTCTGCAGGAACACGAC-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>Distichodus_sexfasciatus_gill_4|006684|C915807|m.55174
ATGGAAACATTAATGAATAAGGATGGAGTCAAACTTTCCCGAACAGAGTTACGCAAGCAG
AAACTTGCAGAGTACCTGGCAGCGAAGGGCAGATTAAAACCACCTAATCCAAAACCTTAT
CTGAAGGACAATGCTGTTTCGATAAAGCAGCCAGGGACTATACAGATGCCTCGAATTACC
TTTGGAGGAAAGGAGAATCAGGCCTCTGGTACTGTGGGCCTAAGGAAAGATGTAAAGAAG
GGAAACACACTGGCAGAGAAGAATATGAACATGGTCCACACACGCACCTCACAA-CCGCA
GATAAGGGTCTCATCCAAAGTCCCTTCTACTGCTATTCAAAATTTTCAAAAACAGTCTGT
TCTTAAAGCTACTCAGCTTGTACCTGAACCTTCTAGAACACAGTCCAAACAGTCTGTCAT
CTTTAGAAATGCTCCTTTCAAAAAGCCACAGACTTTATCATCTGTTCACACACATGCAGA
GCCTCACAAGCATAAACCTGCCAAGATGGACCCCAAATCTACTTGTAGCGAAGCACATTT
TACAAGCTTGAATGTCAGGACACAGCCGA-GCAGTGCCAAGAGGTGTTTA--------GT
TAC-TGGAAAAGAAAAGGGCTCTGATAAAAGAGCTGGCAGAAATCAAGCCAAATGTCCCA
TGACAACAAAACAACTGCCAGACATAATCCAAAGCAGGACTGAAGGAAAGGCTGTGTTAA
AGAAAGCTAAAATTCAGCCAACACTTGCTGTTAATCATAATGTTGCAAGACCAGAGAATT
CTCAGAGTCTGAAAAGGTTTAGTGGGGTCATTCAGCCCAGGAAGCCTGTGAACGTCAATT
CACTGGTAAGATCGAGCAGGTCGGATGTGACTCACAATGAGTCTTGTTCCCAAGTATCCC
GCTTAACAAAGGTGAGAAGTAAAACGGATCTTGCCGTTCTAAACAGAAACACTCCTTGTA
TTACAAGACAAAAGCCAACTCTCGCTTCAGCTTCTTCCAAAACTGCAAACACTCTCAAAT
CAGGTACCACAGAGGTCGTTGTCAAAAATGTACTACCACACCCACAGAGCACCACAGTTA
AACTATCTCCTAAGCCCAATGTTCGAGCCCCAGCGTCTTGCACTCTTCCACGACCTGCTA
AACCTTCTCGCCAGACCTGTCATATAGTGCAGACAAAAACTCCCAAATCAAGTTCCAGCC
CCGGAACTCAAGGAGTCAGAACCGTACCTCTGGATGGCATGAAGAAGCCAAATGCTGCTC
AGGCGGAAAGACTGCGTAAACTTCAAGAATGGCGGGAATCAAGAGGCATTACCTATAAAC
GTCCTCCGATGCCCGTTCGGCCA--GTCAGGAGGAAGACTACCGGAGCTCTTCCTCAGGA
GTACTGGTCCACTATAGACGAGGAGGATGAGGTTCACGGCTTCGTTTGTGCCGTGGACCA
GTCGCTGAGCGATCTCATCAAACTTGTACAGCAGGGCTGTTCTGCAGATCATGTGAGAGA
CGTTCTGTCTCGATTGCC---CATGGCACAGAAATTTGTTAAGTACTGGATC---TGCCG
GGTCCGGCTGATGGAGAAAGAGGGAAACCTGGACGTGCTGTCCACATATGAAGAGGCTCT
T---CGCACCGTCAGAGAGCCTGTGG--------------------------ATGAACTG
CGCTCTGTGGTCTTTGACATCTTAAAAAAGAAAGAAGCAAA---------------AGTT
TCATCACCTT---------------------CTTGGGCTGAGAACGAGGATGACCAAGAA
AGTGAGAAAGATGGAGAGCAGC---------AGGCCAACATGTTTACACCAAAAGC----
----------------------AGTCAGAGCGCTTATTCATGGTGCAAAGGGAGACTCTT
CTGTG-------------------------------------------------------
---ATAAAATACAAGATCACGG----------------------CTACCCCGAGTGGGAA
AAGAAGTCAGCAGACAGCGAAACCAGGTCAAGTTAATG----------------------
------------------------------------------------------------
-------------GCCAAGAAATCCGCTTCTTCACACCAGTGCGACGTTCGGTGCGAATC
GAG--------AAAACGGCCCCCCGGTACCCAGTGGCACTGCAAGAGCATGACCCCTGTG
TGACCTCCCTTCGGGACCTTCTGACAGAGGG---TGAAGCACAGGAAGCAGATAAATGTG
GGGCAGAAAGGTCAATTTCCCCACTTTACTTGTACTTAGAGAACAAAGCTTTGAAGGAGC
AAGTGCAAATTCAACTGGTTTACGAGGAAGGTGATAATGATGAGCTCAGCACAGACACAA
CATAG
>Gasteropelecus_sp._gill_3|003221|C924264|m.47114
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------ATCCTGAAAAAGAAAGAAGCGAA---------------AGAT
TCCGCTTTTC---------------------CTTGTACGGAGGAAAGGGATGGGGTAGAC
CGCGACGAAG---------------------GGTGTGATGCGCATACTCCAAAACC----
----------------------TGTGGCCGCTCTGATACGAGGGGCGAAGGGAAACTCCT
CCGTC-------------------------------------------------------
---ATAAAATACAAGATCACAA----------------------CAACTCCAGGTGGGAG
AAGGAGTCAGCAGAGGGAGAAATCCGGACGGGTTAACG----------------------
------------------------------------------------------------
-------------GCCAGGAACTTCGCTTCTTCACTCCTGTACGCCGCTCGCTGCGCATC
GAG--------AGAACGGCCTCTCGTTACCCCACAGCCCTACAGGAACACGACCCCTGCG
TGACCTCTCTCCCAGACCTTCTGACCGAGGA---CCAATGCGAGGCTGGCAGCGCATGTG
CAGAAGAGCCTAAGGACTCCCCGCTCTACGTGTATCGTGAGAACGAAGCCCTGAAAGAAC
ATGTGGCGATTGAGCTGGTTTATGAG----------------------------------
--TAA
>Lepidogalaxias_salamandroides_Head_2|002264|C473669|m.36858
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------CTGGAAGCAAGGAAAACTGAGCCTACAG-----------
------------------------------------------------------------
-------------------------------AAGACCTCTTAACCCCTCCCCGAGC----
----------------------TGTAGGGGCCCTCATTCAAGGAGCAAAAGGGAACTCAT
CAGTG-------------------------------------------------------
---GTGAAATACAAGATCACCG----------------------CTACTCCAGGGGGCTG
GAAAAATGTTCG---ACAAGGAGCGATGCAGCTTAACG----------------------
------------------------------------------------------------
-------------GTCAGGAGGTGCGCTTCTTCACTCCGGTGCGTCGCTCCGTAAGGATA
GAG--------AGGTGTGCCCAGACACATCCAGCTGCCCTGCAGGAACATGACCCCTGTG
TGACCTCTTTTCAAGATCTGATGGCCAGAG------------AGGAAGAGGACCATCCCC
CAACGTACCTT---AATTCTCCGGTTTATATCTACAGGCAAAATGAGGCCTTGAAGGACC
AA----------------------------------------------------------
-----
>Sargocentron_rubrum_gill_6|024626|scaffold9119|m.10290
-------------CAAGCTCAGAACAAGTCTAATTCT-----------------------
------------------------------------AAACCACTTCAAGACAAACCT---
-------------CTTTGTCCATCATGTA-------------------------------
-------------AAAGTCAACCGTCTG-----TTGGGCCTAAATCAACATAT-------
----------------------GTCTCCTCTAGGCGCACAACAGCACCTGTCAAGACAGA
GGAAAGGGT-----------------------------AAGAGTATCAAAAACTGTTAAA
TC----------------------------------------------------------
-----------------------AACTGCAGAGTTCACAAAC----------AAGGCAGC
ACAGCAGAGACCTAAGGTTGGCGAGGCAG---------------GTAATG--GCCTACTG
TGTGAAGCTGGCTCTCATGCATCATTGGGCGCAGTGAGTCGGTACACTTCCAGAGCAGGT
CACAGGGTTACGCAGGCTGCTGTGGCTGAGCTGAGAGAAAAAGCCAAGACATGTA-----
------------AACTGATGGACA--------------ACCGGAAGGAGGGCAGTTC---
----AGCAAAAGTCCCACCACCACGGG---------------------------------
----TAGACTCAAAAAGAACAGGTGCTCCATTCATGCCACAGACAGTGCCA----CGTTC
TGCCAGGACGGCCAGCCAAGCAGGATGGGTCTCAGA------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------TGTTAAGACACCCAGAGCCCCC--------
------------------------------------------------------------
------------------------------------------------------------
--------------ATCAGAGTCATTGCCCAGACAGAGGGAAAGAAAACGACTGCAGCCC
AGGAGGAGAGAatgaggaagctgcaggagtggCGGGAAGCCAAGGGCATTTCCTACAAGC
GTCCTCCTATGCCAGTGAAACCTCGGGTCAGGCGA-----ACTGTGGCCTTGCCCCAGCC
TTACTGGGCCAGCATGAAGGAGGAAGACGAGGCccactccctcatctgtgctgtggacag
aTCCCTGGCTGACTGCCTCAAATTGCTGGGAGAGGGCTGCCCCACAGACCAGGTGAAGGA
GGTTCTGTCACGTTTGCCAGCGGTGGCCCAGAAGTTTGCCAAGTACTGGATT---TGTCA
GGCCCGCCTGATGGAGCAACAGGGCAACCTGGACGTCCTGCCCATGTTTGAAGAGGCTGT
A---CGTGTTGTGTTAGAGCCAGTGG--------------------------ATGAGCTG
CGGACTGTGGTGTTTGAGATTCTGAAGAAAAAGGATGAGATCCA------------AGGT
CCCTCATCTGGATCT------------GAGGTTGCGATAGAGGACGAAATGCTGGAACCA
AGGGACGGCACTCCTGAAAATACCT------CCAACCCCATGGTGACCCCTAAGCC----
----------------------CGTCAGAGCTCTTATCTGCGGGGAGAAGGGGAACTCGT
CTGTA-------------------------------------------------------
---GTCAAGTACAAGATCACAG----------------------CCACCCCTGGTGGGGT
TCAAAGCCAGCA---ACGGGAGCCAGCACAGGTCAATG----------------------
------------------------------------------------------------
-------------GCCAGGAGGTGCGCTTCTTCACTCCTGTTAGGCGTTCAGTGCGAATC
GAG--------AGGGCGTCGCTCCTCTACCCT----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----
>Scleropages_formosus_red_gill|004906|C1306858|m.76151
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------GTCCTCCTG--------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------GATCGAAGAATCCACAA--------------------
------------------------------------------------------------
-------------------------------TGCTGGGACGGTGCGCTC-----------
--------AAAGACGTTCGTCGCAGCCGATTTGCCGGTCAGAA--CAGCTACGTG-----
------------------------------------------------------------
-------------------------------------------TGTGAGACC--------
----AAACCTCAGAAAG-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------ACTGCGTCT--------
------------------------------------------------------------
------------------------------------------------------------
--------------ATCGGAACTGTCCCCT---------------------CTAAAGCCC
TGGCAG-----CTGCAGCAGCTCCTTCCATGGCTAATCTCCAA--------CCTTCAAGC
ACGATGCGAAGTAAGTCGGACCTTG-----------------------------------
---------------------------------CTTCCGTTTCATCTAAATTGCTGCCTG
GTACCTG-----------------------------------------CCAAATGAAGGT
CAATCCACC----------GGTGAGGCAGCGAAGCCCTACGAATACTACGTCGAGTGTCA
AGCTTGT-------------------------------------TGCCAGCAGACATTGT
AGAGCTCACTGTAAAGGAGCCAGTGATCCTAGTGGCTCCAAGGATGCTTCATCTGAGCCA
C------TGCTGATCAGACCTCAGCGGAAAAATGCAGCAAATCCTGCACCGCCAA-GGAA
CCGTGACACGGTCCCTC------------------------GGCCCAGGACCGGCCACCG
AGCAACAGGACCACAGCGTG-----------CCAAGGACCAGGCTCCTTCCAGAGCGCGG
GGCTCGGCACTGCACAAAGTGATGCTTCAGGCAATCTCTAAGATGGACAAGGAGACATCC
CGGCAGGCTGCGTCCAGGGTCAATGGACCAGAAACTGATAGCAAGGTCCTGAAAACAACT
CGGATGAGAAATAAAACCACAGAAGCAGCTCAGCCTTCCACTTTACGCACCAGGCAGCTT
AAGGGGCCAGCAGTTCTAAAGACCCATGCTGTTCAGAGTCAAACTGATCAAGGAGGTTTT
ACCACAGCCCCCAGAAATGACCAACAGAAATCAATCACAGCACAGGAGGAGAGACTGAAG
AAGCTCCAGGAATGGCGGGAGGCAAAGGGTATTTCCTACAAGCGGCCGCCCATGCCCATC
AGGCCAAGCCTGAAGAAGGCACCCACGGTCCCTCAGCACTACTGGAGCACCAT-------
----------------------------------GGAAGCAGAGGACGA-----------
---------------------------------------AGCACAACACCTTGTGTGCAC
CATCGATAGT--------------------------------------------------
-----
>Synodus_sp._gill_5|003890|C567262|m.45950
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------CAAGTTGCGGA
GGTCCTTTCCCGGTTACCAGATGTGGCCAAAAAGTTTGCCAAATACTGGATC---TGTCA
GGCACGTCTGATGGAATGCCAAGGAAATCAGGAAGTGCTGCCCTTGTATGAGGAGGCTGT
T---TGTGTTGTTATAGAGCCAGTGG--------------------------ACGAGTTG
CGGAGGGTGGTGTTTGACATCCTGAAGAAGAAAAAAAATGATAACCAAGGACAATCGGTG
TCCCCGTGCG---------------------TAGTGACTGAGGTGGTGGAAGAACCAGCA
GATATCAGTTCCCCTGAGCACGGTG------ACGAAGTCATGGTTACCCCCAAGCC----
----------------------AGTTAAAGTCCTCATCCGTGGGGAAAAAGGCAATTCAT
CAGTC-------------------------------------------------------
---ATCAAGTACAAGATTACAG----------------------CCACCCCAGGGGCTAT
ACGCAGCCAGCA---GAAAGATCCAGTACGTATCAATG----------------------
------------------------------------------------------------
-------------GCCATGAGGTGCGATTCTTTACTCCCGTTCGACGTTCTGTTCGGATC
GAG--------AGGGCCTCACTTCACTACCCAGCATCCCTCCAGGAGCAAGACCTCTGCG
TGACCTCTTCCAACCATCTGATGGCTGAGGAGAAGGAGGCAGCAGAAAGTGAAACGGGCA
CCCTGTCCGTCCACAACACTCCTATGTACATCTACTGGGAGAATGAGGCCCTGAAAGATC
AGGTGCAAGTAAAGCTGGTCTATGAGAGTGAC----------------------------
--TGA
