>Amblygaster_clupeoides|008363|TR17943|c0_g2_i1|m.35974
A-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------GAGGGGAGCTCCAGGCCCG
C---CAGGAAGAGCGCTG------------------------------------------
CCAGGAAGAGCGGGACAGGT----------------------------------------
---------------------------------------------GGCGAAAGAGGGTCC
GGGACAAGCGGCAAGGGCGAGACGGGAGAAACAAAGACCACAAGAGGGAGAGAGATGCAA
GTGGAGACCAGGAG-------------CGAAGGAGAAGGAAGAGGGAGAGGAGGAGGGAG
CGAGAGCAGAGAAGGAAGCGTAAGGAGGAGCAGAGTCGTTCCAAGAGGAGAGAGAGGAGG
AAAAGGAGACGCGAGCGACTCCTCCAAGCACGTGCCCTCTCCCCCCTCAATGCCACATCC
ACCCAAGAGTCCCATGACCGCTCCCTTCGGCCCGTCCTCCCTAAG---------------
---------ATCCGCTACTGCCCTTACCTGTCCACGTGCCACAGCTCGGACCGGCGC---
------------CGCCGCTGGGTCCTGCGCTCTGCCGTGCA-------------------
-----------GTCTGCTCGGCAGGCCATGCAAAGC------------------------
------------------------------------------------------------
------------------------------------GCCGTCTTC---------------
------------------------------------------------------------
----------------
>Corydoras_julii_viscera_mixture_8|013952|scaffold23637|m.19122
ATGCATC-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------ATGAAGGTGGTCACATCGAGGTGGAAATTGAAAAGGACCTTG------
-----ATCAAGAGC-CTGAGAACCTCTGGTGGCGACCTTTGACCTCGGACGACCTCTCGT
CAGAAAACACCGACATGGAGAT--GGGTGACGTTGAGAGACCCAAAT-------------
---------------GCACGGAAAACCGCTCTGCTATGGTATTAAAGCTCAGAAAGGTTT
ACTTTA---CCAATGGCCGCCGTCGACAAGTATCTCACTACCAGAGAGTCCTGGATC---
---------------------------AGTCTGAAGTTAACGACTTGGGCCG--------
------------------------------------------------------------
--------ACACAAGCGCAGTAACCGGAAAACGAAATTACGAC-----------------
-------------------------ACTCGCTCACCTCCTCCAAG---------------
---------ACTCATCAGCGCTCATTTCAGACCAAATTACAAACTTCAAAGCGCAGA---
------------AGGAGGTGGACACTTCGGTCAGCAGCGCATC-----------------
----------AAGATCACACACAGCCCTCGAACAAAAGCTTACCAGACCTGGTGGGAAAA
AGGATCCGACACCTTTATGAGGAGAAGGATAAGACTGAGGTGTGGTATCAGGGCAGGGTG
CTGCGTATCCACGAGTCTCATCCCAACCCCCTCAAAACCGTATTCGAGGTCAAGTACGAC
AGTGAGCCGGAGTGGCAGTACTACCTGGAGCTACTTATG---------------------
----------------
>Distichodus_sexfasciatus_gill_4|026406|scaffold6455|m.6911
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------ATGGTGCTGAAGCTGAGGAAGGTTT
GCTGCG---GCGACCGGCGCCA------AGGGCCACACTACCGCCGGGTCACTGAGC---
---------------------------GCTCCGAATCCCGAGAGGGGGGGCG--------
----------------------------------------------------------GC
AACAGCGGAGACACAGGGCACAGGAGGAAGAGGAAGGTT---------------------
-------------------------CCAGGTACGGAGTGTGGCGG---------------
---------GCGGAGAGGAGGCTGGTGTCCGAGAGGAGACGGAGGCCGGAGCGCTGGAGA
CATTCGGAGCGCAGGAGGTGGGCGCTGCGCTCGGACGGACGCTCGGCCGGGAATTCGGAG
GGGCGGGGGACGGAGACGAGGACGACGACGAGGGACTCGTACCCCAACCTGGTGGGCAAA
CGGATCCGGCacctgtacGAGGAGAAGGACAAGACGGAGGTGTGGTACCGTGGGGTGGTG
CTGCGCGTCCACGAGCCCCACGCCAACCCGCTGAAAACCGTGTTCGAGGTGAAGTACGAC
AGCGAGCCCGAGTGGCAGTACTACCTGGAG------------------------------
----------------
>Gasteropelecus_sp._gill_3|008181|scaffold13801|m.12798
ATGCCAGTGCCTGCAATGTCTTTGATTCAAGTCCTACAGATGATGTCCAAAANNNNNNNN
NNNNNNNNNNNATATATGGAATGCTCAGATGAAGCTGAAAGTTCTGTGAATGATTTAGAG
GTATGCAGCACATCCCCAAGGCCACAAACGCCAGATACTGTGATGCATCTGGAGAACCTC
AGAGAGCTGTCTCCTCTGAAGACGTGCAAAAGCAAAGGCAGGGTGAAGAGTGCCTGCAAG
AGGATGTTTTTGGAAGATAACGGTTCTTCAGATGAGGACGAGTCTGACAAGGAAACCACA
AACT-----GGTGCTTTGAGGGCCTGTTTGAGGGGGAAGTGTGGGAAAACCTCGTTGCAG
CCACCAGTGGCGACGAAGAGGGCCGTGTGGAGGTAAAGATTGAGGAGGACTCCG------
-----AACAAGAGC-CTGAGAATTCCTGGGCACGGCCTCTGACTTCAGATGATCTTTCAT
CGGGGAGCAGCGATGTAGAGACTGAGGTGACCTCTTGGTCGTCACATCGGAGCTGGTCAT
CAAGTACTT------TCTCCAAGAGCCGATCAGGAATGATCCTGAAGCTGAGGAAAGTTT
ACTACG---GCAATGGACACCAGGGCAGAGTGTCGCAGTACCAGAGAGTCCAGGACC---
---------------------------ACACCGAGGCTCAGAACACGGAGAGCA------
----------------------------------------------------------GA
GGGGACAAACATGAGCGACACCACAGGAAAAGGGAACACGGTTCTTCCAAAAACAAG---
------------AATCGACACGCGTTTTCCTCCAGTCTGCGGCGG---------------
---------GCGAAGCACTGCTCCTACCTCTCTGCTCAGCACACCTCTAAACACAGGCG-
------------------------------NCTGCCGTTCA-------------------
-----------AACCACCAAGAAGGACATGA-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------
>Lepidogalaxias_salamandroides_Head_2|014404|scaffold11858|m.15593
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------T
CAGCCATCTCCAACGGCCTCCTCCCGGAGTCGGAGCCCGAGGACTGGGGCAACTCCA---
-------------------------------GGAGGAGGCCGTTGGA------GATGGCC
GAGGGGAGGTGTCGGCGGCGTA--------------------------------------
----------------------------CCCGCAGCTCGTCCAGGGCACAGCGCCGCTCC
CGGATGCGCATCAAGTACTGCCCCTACCTCTCCGCATGCCACAGCGCCGTGCGCCGG---
------------AGGAGGTGGGTCTTGAGGTCGGCCGTGGA-------------------
-----------GAGCGCCAGGCGGGCCATGAGGAGCAGCCTGCCGGAGCTGGTGGGCAGA
CGGATCCGCCACCTGTACGAGGAGGATGACAAGACGGAAGTGTGGTACAGAGGAATGGTG
GtgcgtgtgcacaAAGCTCACCCCAACCCCCTTAAGACGGTCTTTGAAGTCAAGTATGAC
AGCGAGCCCGAATGGCAGTACTACCTGGAGCTGCTGATTGACTAC-AAGAAAGGCTGGCT
AAAAGTGGAAGACTGA
>Melanotaenia_praecox_viscera_mixture_8|015585|scaffold20967|m.23287
ATGTTTCC----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------AGATGACACCTGTTCAGATGACGAAGAGGCAGGTGATGTAGAGAAAATG
GGCTATGAGGGTGTTCCAAGCACATTTACAAGGAGAAATTGTGA----------------
-------TGCCTATAGAACTGGGAATAAAGGAATTGAACACATGGATTCCTCTGCTGCTT
CACAAATCACAATCTCTGACAATTCATGGGTATGTCCTTTAACATTAGATGAGCTGTCTC
CATTTCCTAGTGACACAGAAACTGAGAAATCCTCAAATCTGTTGTCTTGTAATCAGTCTG
CAGGACCTCAGGTCAAATCCAAGAATTGCTCAGGCATGATTCTTAAACTGAGAAAGAT--
-GTTCG---GTAAGGGTCTAAACAGAAAAAAGACCTGCTACCAGGCAGTGTCGGTGCCTG
GGACATTTGCTGATTCTTCACAGTCCCAGGCTAATGATGGAGAGGGTGTCAGCACCA---
-------------------------------AGAGGGACCTACGCAG------GACATCC
AAATTAAAACACAGGTTGCAGAGAAAAGGAAGTTTATCTCATG-----------------
-------------------------CCCTTAGCAACCCCTCTAAAAAGAAAGTCAGATCG
CTACTGAAGATTAAATACTGTCCCTACTTGTCTGCCTGCCACAGCGCTGAACACAGA---
------------AAGCGATGGGTCCTGCGCTCAGCTGTCCA-------------------
-----------GAGGGCTCGCAAGGCCATGAGGCTTTACTACCCAGACTTGGTAGGAAAG
AAGATCAGACATTTGTATGAGGAAGACGACAAATCGGAAGTGTGGTACACAGGAGAGGTG
CTGCGTGTTCATGAGGCTCACACCAACCCTCTAAAGACTATTTTCGAGGTCAGGTATGAC
AGTGAGCCAGAGTGGAAGTACTACCTCGAACTGTTGATAGACTAT-AAAAAAGGCTGGCT
AAAAATTCAAGACTAG
>Sargocentron_rubrum_gill_6|020820|scaffold29300|m.41076
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------ATGATTCTCAAGCTGAGGAGGGTTC
TGTTTA---GCGAAGGCCTGAACAGAAGAAAGGCCCGCTACCAAGCAGTCTCTGACTCAA
GGACAAGTTCTGATCCTTCCCTCCCACAGGCTGAGAGTGGGCAGGGAGAAGAGACCAGAG
AGAGGAGCGGTG-------------------AGAGTGAACTCCACAGGATGAAGACATCT
AAGGGCACCCACAGATGGCATAGAACAGGAGGCTTCTCTCATGCCCTGCAACCCATC---
------------------------TCCTCTACCAGTTCTTCTAAAAGACGCCACAGATCC
TTCATAAAGATCAGATATTGTCCCTACTTGTCTGCGTGCCACAGTGCTGAGCACAGG---
------------AGGCGTTGGGTCCTGCGCTCAGCGGTCCA-------------------
-----------GAGGGCCCGGCGGGCCATGAAGTTCTACTACCCAGACCTGGTGGGAAAA
AAGATTCGACATCTGTATGAGGAGGATGACAAGTCAGAGGTGTGGTACAGAGGAGAGGTG
GTGCGTATCCATGAGGCTCATCCCAACCCTCTGAAGACTGTTTTTGAAGTCAGGTATGAC
AGCGAGCCTGAGTGGAAGTACTATCTGGAGCTGCTGATAGACTATAAAAAAAGGCTGGCT
CAAAATCGA-------
>Synodus_sp._gill_5|022415|scaffold3865|m.4143
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------ATGATTCTTAAATTAAGGCGAGTGC
TACTTA---ACAAGGGATGTGGCCGTAGAAAGGCCCACTACCAAGCAATATCGGACCCAG
AGGTGGTTCTCAACCCTTCACCTGCAGTGGCTGAGGATCGGGAGAGAGAGAAGGCTAGAG
GTAGGGGAGATG-------------------GCAGAGG---CAAAAGGTGGATGGTATCA
AAGGGTACCAATAGGTGGCAGCAAATGGGAAGATTCTCTCGTGGCCTGCGAC--------
-------------------------CCCTGGCTAGTTCCCCCAGGAGACTGCATGG----
--GNNNNNNATCAAATACTGCCCTTATTTGTCAGCATACCATAGCGCTGATCACAGG---
------------AGGCATTGGGTCCTCCGCTCTGCTGTCCA-------------------
-----------AAGGGCTCGGCGGGCCATGAAGTTTTACTATCCAGACCTGGTGGGCAAG
AGGATTCGCCACTTGTATGAGGAAGATGACAAATCAGAGGTGTGGTATGGAGGAGAGGTA
GTGTCCATTCATGAGGCTCACACCAATCCTCTTAAGACTGTATTTGAGGTGAAATATGAC
AGTGAGCCTGAGTGGAAATACTACCTGGAGTTACTGaTGGACTAT-AAAAAAGGCTGGCT
TAAAATAGAAGACTGA
