>Amblygaster_clupeoides|033188|TR59116|c0_g1_i1|m.80477
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------TCAAGTCCCTTGAGTCCCGGAGAGGCCATGCG
GAGGGTTCTAGAATGCATCGCCACGGGAATCCTCTTACCAGATGGCCCAGGCCTTCTGGA
CCCTTGTGAGAAAGACCAGACTGATGCTCTGGATGGTATGAGCAAGCAAGCTAGAGAGGA
CATAACTGCTAGTGCACAGCATGCCTTGCGGCTACTTGCCTTCCGGCAGATTCACAAAGT
CCTTGGCATGGAATCCCTGCCTGCATCAAAAGCTGGTACCAGGAATCGCAAAAGGCGACG
GGACGGCAGCGAAGCTGGGGAGGGAGAAGGGGAAGGCAAAAAAGACAAAAAGGAAGACTT
AGAGGATGCTTGA
>Corydoras_julii_viscera_mixture_8|014747|scaffold24561|m.20298
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------ATCATCCGCATTCT
ACGAGACCTCCGTCAGCGCGTTCCAACTTGGACCCAGATGCCGGATTGGCCACTGGAATT
GCTGGTGGAGAAGGTCATCAGCAGTGTGTCGGTCCCTTTGAGTCCAGGGGAGGCCATGCG
CAGAGTTCTAGAGTGTATAGCAAGTGGAATGCTTCTTCAAGATGGTCTGGCTATTTCAGA
CCCCTGTGAAAAAGGGCAAACTGATGCGTTGGGGCCCATGAGCAGGCAAGCCAGAGAAGA
TGTAACAGCAAGTGCTCAGCACGCCCTGCGTCTGTTGGCCTTCCATCAGATCCACAAAGT
CTTGGGGATGGACACACTGCCGACTTCCAAGGCCGTTCCATGCAACCGCAAGAGAAGAAG
CGATG------------CAGCAGATGAGTCTGTGGGAAAGAAGGACAAGAAAGAG-----
-------TTCTAA
>Distichodus_sexfasciatus_gill_4|007024|C918269|m.55890
----------------------CTGAAGTTGGCTAAAATGGCTGCTAGTAATTATTATGG
ATTCGCGCACGGCCCCAGTCCTCAATACAGCACCCAGCCGCCTCCTGCTTACTCCCATCA
AAATGCTGCCAACTACAGCGTCCAGGTGGCCCCCACCGGAGTCCATACAGTCACGGCCTC
ATATGCTCCCGCCGCTGTCCAGACCGCTCGCCCGGTGGCGTCTCCGGCTTACCCAAACTA
CCAGACCCACGCCGGGCCC---GATTACGGCTACCGGCAGCC---TCAAGAAACGGCACC
TCAACCAACCAGCACGCCGCAGACCTATCAGGTCTTCACTGAAGCGGAAAACTTCAGCTA
TGCACGGCAGGTGTCGGTCAGCAGTTATGAGAACAAACAGTACTATCAGACGAGCATCGC
ACCTGCACAGCGCACCACGGCAGAAGCCTACTTTCAGCCAGGTTTAAAGAGCGCTTATAG
ACCTGTAAACTCAGCG---TACAGTCAGC---CTCCTCCTCAGAGACCGGTCACAGGCCT
CAAACCACTTCCTCCAGTCAGCTCCGTTTCTACGAGTTACAGTATTTATCCTGCGTCAAC
CAGTGTGCAGCAGCAGCAGCAGCAGCCCACCCCCATATCCA---CCACCTACACCCCCGC
TACCTCGTATAACTCAACCGCC---GCCACGTCTTACTCTGGTCTCAGCTATTCCAGTTA
CGAATCCACTGGCTACACTTCCACTACGTCGTATTATCAACCAACCCATCTTGGCCCTCA
ACAGGCACAACCCCCTTCCCATCAGCTTCAGGCCACCTCCCATCAGCCCCAGCCTGTTTC
CCATCAGCCTCAGCCTCAGGCTCCACAGCAGCAGAGCCAGACCCCCAGTAAGCAGCTCAC
TAGCGCCTCCTGGAGCAGTTCCGGGAGCAACGCTGTCACAGGTTCTGCTGTCAGCACCTA
CAAGAAGCCCATGTTCCATCAGAATAAGGTGCAGAAACCTAAAGGTCCCCCTAAACAGCC
TCAGCTTCACTACTGTGACATCTGCAAGATAAGCTGTGCTGGTCCTCAGACCTACAAAGA
GCACCTGGAGGGCCAGAAACACAAAAAGAAGGAGGCAACTCAGAAGTCCGGCGGTCAGA-
-----CCAGCAACGGGCCACGCGGTGTGCAGACGCAGCTGCGCTGTGAGCTCTGTGACGT
CTCCTGCACCGGTGCAGACGCCTACGCAGCACATATCCGGGGGGCCAAGCACCAGAAGGT
GGTCAAACTGCACACAAAACTTGGCAAACCCATTCCCTCAACCGAACCCGTTTTGGTGAA
TTCTAATCCGCTTCCTGTGACGACGACATCCGGAAAAGCTGCACCTCCTGTTTTAGCTCC
TGCCTCTCCTTCTGTGCCTCTGAAA------ACGACTGTTCCAAACCCTCCC--------
-------------------------------AAAGCACAACCACTGGCAAAGAAACCCAC
TCTGCCTAAAGCTACAGTCATTACCAGCAA---AGCTGCTGTTCCAGACCTGA-------
-----------------------------------------------TAAAGGTGGAGGA
GGCAAAACAGTC---------------GGACGCTCTGAGT---GATGAGGAAGGTGATGG
ACGCGGTGC------TCAGGGAGACATTCAACCTGTAGGCCACGACTACGTGGAGGAGGT
TCATAATGACGATGGCAAAGTGATACGCTTCCACTGTAAGCTGTGTGAATGTAGCTTTAA
TGACCCAAATGCTAAAGACATGCACCTGAAGGGGAGGAGACACCGCCTGCAGTATAAGAA
AAAGGTGAACCCCGACCTGATGGTGGAGATCAAGCCGAGTAACCGGGCGCGGAAACTTCT
GGAAGGCAAGCTGAGAAAGCAGAAACAAAAAGCGGAGCTGAAGAGGGCGCATGAGGACGA
GCAGCGATGGCACATGGAGATCAGGAGGTATGAGGAGGAGATGTACTGGAGGAAGGCAGA
AGAGGATCAGCTGTACTGGGTGGAGCAGAGACGCAGAATAATCCCCCCGCCCCTACTGAG
TCGCCCTGGGATGCCCCTTCCCCCTTTACTGCCC---GTTCGACGTCCCGACTCTCCCGA
TGACCGGCACATCATGGCCAAGCATTCTGCAATCTACCCAGTGGAGGAGGAACTGCAGGC
GGTGCAGCGGATCGTGTCACACTCGGAGCGAGCGCTCAAACTAGTGTCTGACTCGCTGCT
GGAGCAAGAGACTGCCTCCGAGAAAACTAA---CTCAACAGATTCACAGACGGACCC---
------------------------------------------------------------
---------TCAGGGCCGCATCCTGAAGGGGGTGATGAGGGTTGGAATCCTAGCCAAAGG
CCTGCTGCTCCACGGTGACCGCAACGTCCAGCTCATCCTGCTGGTCGCTAAGAAACCCAC
CGTCTCCCTGCTGACCAACATCGCCCACCAGCTTCCCAAGCAGCTGCTGAGCTTTTGTGA
AGATCAGTATGAGGTGCAGGCTCACCCTGAGGAAGCCAACATCGTCATTATTTCCAGCAA
GGAACCAAAAATGCAGGTCACGATCTCTCTCACGTCGCCAGTGATGCGGGAGGACGCCGG
TCCTGGCGTGGAGGAGCAGGCAGCAGGCAGACTGCCCGAGAAAGGT---CCAGAAACGGA
TCCTCCAGACATTCTAAACAGGACAAAGTGTCTTGAGTATTTGGCCGCTCTGCGTCATGC
AAAGTGGTTTCAGGCTCGAGCAAACGGTCTTCAGTCCTGTGTAATCATCATCCGAGTGCT
TAGAGATCTTTGCCAGCGTGTTCCCACCTGGAGCAAGGTGCCCGATTGGGCCATGGAGCT
GCTGGTGGAGAAGGCGATCAGCAGTGCTTCTGCTCCGCTCAGCCCAGGAGAGGCCATGAG
GCGGGTTCTGGAGTGCATCGCTAGTGGAATCCTCCTCCAAGACGGTCCGGGCCTCTTGGA
CCCCTGCGAAAAAGAGCAGACGGACGCGCTGGAACACATGAACAAGCAAGCCAGAGTGGA
CGTAACCACAAGCGCTCAGCATGCGCTGCGGATGTTGGCTTTCCGTCAAGTCCACAAAAT
CCTGGGGATGGACTCGCTGCCGGCGTCAAAGGCCAGCACTCGCAACCGCAAGAGACGAAG
AGACG------GAGCGGACGAGGGCGAGGGAGACGGCAAGAAGGACAAAAAAGAAGACTG
CCAAGATGCTTGA
>Gasteropelecus_sp._gill_3|017106|scaffold27938|m.28944
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------ATGCAGGTCACCGTCTCTCTCACTTCACCAGTGATGCGGGAAGACCCTGC
CTCAAGCCCAGAGGAACAGACAGACCTCAAGCTGCCTGAGAAAG---TGCCTGAAAAGGA
TCCTCCTGACATTCTAAACAGGTCAAAGTGCCTTGAGTATTTGGCAGCCCTACGTCATGC
CAAATGGTTTCAGGCACGTGCCAATGGTCTCCAATCTTGTGTGATCATCATCCGCGTGCT
CAGAGACCTCTGCCACCGCGTGCCTACCTGGGGAAAGATGCCAGCCTGGGCCATGGAACT
GATTGTGGAGAAAGCCATCAGCAGTACGTCGGGTCCTCTGAGTCCAGGAGAGGCCATGCG
GAGGGTTCTGGAGTGCATTGCAAGTGGAATCCTTCTGCAAGATGGTCCAGGTCTGTTTGA
CCCTTGTGAAAAAATCCAGACAGATGCTTTAGATAGCATGAGTAAACAAGCCAGAGAAGA
TGTAACTGCGAGCGCCCAGCATGCTCTGCGGTTGTTAGCATTTCGTCAGGTCCACAAAGT
TCTGGGGATTGACTCCCTGCCAGCGTCCAAGGCCGGCACTTTCACCCGCAAAAGACGAAG
AGATGGCGCAGATGCAAGCGAGGGGGAAGGTGAAGGAAAGAAAGACAAAAAAGAAGATTC
TCAAGATGCTTGA
>Lepidogalaxias_salamandroides_Head_2|019050|scaffold17579|m.23771
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------AAGCCCAC
CGCCTCCCTCCTGCAGCGGATTGCCGAGCAGCTGCCCAAGGAGCTGATGACTTTTTCTGA
AGATCAGTATGAGGTGCAGGCTCACCCCGACGATGCCTCCATCGGGATCCTTTCGAGCAA
GGAGCCCAAAATGGCGGTGAGCGTCTCCCTCACGTCCCCGACGATGAGGGAGGAGGCCG-
-----AGGACGAGGAGCAGAGCGCAGACAAAGCGGCCGTGAAAGGGAGGACTCAGAGGGA
TCCGCCCAGCGTTCTCAACAAGGCCAAATGTCTGGAGTACCTGGCTGCCCTCCGCCATGC
CAAATGGTTCCAGGCACGGGCCAACGGGCTGCAGTCGTGTGTGATCGTTATCAGGGTGTT
ACGGGACTTGTGTCAGCGGGTCCCAACCTGGGGGAAGGTACCGGCCTGGGCTATGGAGTT
GTTGGTGGAGAAGGCCATCAGCAGTGCCCCCGGTCCTCTCAGTCCTGGGGAAGCCCTGCG
GAGAGTTCTGGAAAGCATAGCCACGGGACTCCTTTTGCCTGATGGGCCAGGGCTGCTTGA
CCCCTGTGAGAAAGATCAAACTGATGCCCTGGGCAGCATGACCAAACAAGCCAGAGAGGA
CATTACTGCCAGTGCACAGCATGCACTGCGGCTGCTGGCGTTTCGGCAGATCCACAAGGT
CCTGGGGATGGAGCTGCTGCCCGCGTCCAAGGCCGGCA------GCCGGAAGCGGCGGCA
CGTCG-------------------------------------------------------
-----------GG
>Melanotaenia_praecox_viscera_mixture_8|002796|C430220|m.28280
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------AAGCAGGGAGAAGAAAAAGCGGCTGAGAAAGGTGTGGTTGAGAATGA
TCCTCCTGATCTTCTGCATAAAAAGAAATGTTTGGAATACCTGGCAGCTCTCCGTCATGC
CAAATGGTTTCAGGCTCGTGCAAATGGGCTGCAGTCTTGTGTGATCGTCATTCGGGTGCT
GAGAGATCTATGTCAGCGTGTTCCCACCTGGGGGAAGATGCCTGGTTGGGCAATGGAGCT
GCTGGTGGAGAAGGTGATCAGCAGTGCCACAGGCCCGCTCAGCCCAGGGGAGGCCATGCG
AAGAGTTCTGGAGTGCATCTCTACAGGCATCCTGTTGCCAGATGGGCCAGGTTTGATGGA
TCCCTGTGAGAAGGATCAAACAGATGCTTTGGAGTGCATGAAGCTTCAAGCCCGGGAGGA
CATAACTGCTAGTGCACAGCACGCTCTGCGGCTGCTTGCCTTCAGACAGATCCACAAGGT
CCTGGGTATGGAGTCACTACCGGCATCAAAGGCCAGCGCACGCAACCGCAAACGACGACG
GGACATCAGCGACACGGGTGAAGGCGAGGGAGAAGGC-----------------------
-------------
>Sargocentron_rubrum_gill_6|018406|scaffold27157|m.35893
TGTCTGCCCGTACTGTACCGTACTGGAGAT-GCCAAGATGGCTGCAAGCAATTATTATGG
CTTCACACATGGTGCCGGTCCGCAGTACAGTACCCAGCCTCCCCCGGCCTACTCCCACCC
CTCCACAGCCAGTTACAGTGTCCAGCAGGCTCCAGCTGTGGCTCATGCAGTGACTGCATC
CTACTCCCCTGCCCCGGTCCAGGCAGCCCGGCCCGTAGCCTCGGCCCCTTACCCGGCCTA
CCAGAGCCACCAGGCACCCCCAGACTATGGCTACAGGCAGCCAGACCCCCCAGCCCCCCC
ACAGCCCACCACCACCCCACAGACGTACCAGGTGTACTCAGACACGGACAGCTACAATTA
TGGTCGTCCCCCCACGGTGACTACCTATGACAATAAACAGTACTACCAGACCAGTATAGC
CCCAGCCCAGAGGACACCCACAGAGAATTATTACCAGACTGgtgtgaagagcggttacag
tcccgCTCCCTCCACGGTCTACAGCCAGCCCGCCCCTCCCCAAAGGCAGGTAACAGCCTT
GAAACCGCTGGCCCCCTCCAGCTCCGTGTCCACCAGCTACAACATCTACCCAGCATCCAC
CAGTGTTCAGCAGC---------------CTCCCACGCCCATTTCCTCCTACACCCCCGG
CTCCTCCTTCAGCTCCGCCGCCTCAGCAACCTCTTACTCCGGCATCAGCTACTCCAGTTA
CGACTCGAGCGGCTACACCTCCACC---------------TCCACCCCCTCCTACTACCA
GCCTGCCCAGCCGACTCTCTCTCAGCCCCAGCCTCCACCCCAGCAGCCCCAG--------
----CAGCCCCAGCCCCCCAT---------------CCAGCCACCTCCCAAGCAGCTGAC
CAGCTCCTCCTGGAGCAACTCGGGCAGCAACATGGTGACGGCCCCGGCTGGAAACGCCTA
CAAAAAGCCCATGTTTCACCAGAGCAAGCTGCAGAAGCCCAAAGGGCCTCCCAAGCAGCC
CCAGCTACATTACTGTGACATCTGCAAGATCAGCTGTGCTGGCCCTCAGACATACCGGGA
GCATCTAGAGGGCCAGAAGCACAAGAAGAAAGAGGCAGCCCTTAAGTCTGGGGGCCAGAC
AGGGGCCAGCAACGGGCCCCGAGGAGTCCAGACCCAGTTACGCTGTGAGTTATGTGACGT
TTCCTGCACCGGGGTTGATGCCTACGCCGCCCATATCCGTGGGGCCAAGCACCAGAAGGT
GGTGAAACTCCACACCAAGCTGGGCAAACCCATACCTTCAACAGAGCCAGTGTTGGTGAA
CTCTACTCCAGTTTATACGACCTCAACAGCTGGGAAACATCCTGCCTCCGCCTCCGCTCC
CGCACCAACCTCAACCGCCTCAGCATCTTCTGCTGCCGCGACAACAACTCCCAACGCAGC
ATCCAAACAAGTGGTGGTGAACAGCACCGTTAAAACAACAGCGCCAGTCAAGAAACCAGT
TCCTCCTAAAATAACTGTCATTTCCAATAAGCCAGCCAGCGCTCCAGCAGCTGCAGCACC
ACCAGCAGCAGCAGCAGCAGCGGTGGCGGCGGTGGTGGTGGCAGCAGTGAAGGCAGAGGA
GCCCAAGCAGCCGACGATGCAGAAGATGGAGCCTCAGAGTGAGGATGAGGATGGTGACAG
AGCCGGGGC------TCAGGCAGACGTCCAACCAGTGGGACATGACTATGTGGAGGAGGT
TCGTAATGATGATGGCAAGGTGATTCGCTTCCACTGTAAACTCTGTGAGTGCAGCTTCAA
TGATCCCAATGCGAAAGACATGCACCTGAAGGGAAGAAGGCACAGATTGCAGTACAAGAA
GAAGGTGAACCCAGAGCTTCCTGTGGAGATCAAGCCCAGTAACCGGGCCAGGAAGTTGCA
GGAGGGCAAGCTGAGGAAGCAGAAGCAGAAGGCCGTGCTGAAGAGACAGAGAGACGATGA
GCAGCGCTGGCACATGGAGATGAGGCGATATGAGGAGGACATGTACTGGAGGAGGATGGA
GGAGGAGCAGATGTACTGGGGGGAGCAGAGACGCAGGATGGCTCCTCCTCCGCTGATGAG
CCGCCCAGGAATGCCGGTACCCCCCCTACTAACGTGTGTTCGTCGGCCAGACTCCCCTGA
TGACCGCCACATCATGGCCAAGCACTCGACCATTTACCCTGTGGAGGAGGAGCTGCAGGC
CGTCCAGAGGATCGTCTCTCACTCGGAGAGAGCCCTCAAACTGGTGTCAGACTCCCTGCT
GGAGAAGGAGAC---------------------ACCTACTGTTTCTACCTCAACTCC---
------------------------------------TGAGGAGGATGGAGAGGAGAAAGC
TGCTGAGAACCCGGGACGGCTACTCAAAGGGGTGATGAGGGTGGGCATCCTGGCCAAAGG
CTTGCTGCTTCATGGGGACAGAAATGTTGAGCTCATCCTGCTGACCGCCAAGAAGCCCAC
CATCTCCTTACTGAAGAACATTGCCAAGCAGCTGCCCAAGGAACTGGCGACATTTTCTGA
AGATCAGTATGAGGTGCAGGCTCACCCTGAGGAGGCGAACATCCTGATATTTTCAAGCAA
GGAGCCCAAAATGCAGGTGACCATTTCTCTCACCTCGCCGCTGATGAGGGAGGACCCTGC
CGCTGAGAAGGACAAGCAGGCAGGAGGAAAATCGGCtgagAAAGGTGTGGCTGAGAAGGA
TCCTCCTGATGTCCTGAATAAGAAAAAATGCCTAGAATACCTAGCTGCTCTGCGACACGC
AAAATGGTTCCAGGCCCGGGCCAATGGGCTGCAGTCCTGTGTGATCATCATCAGGGTGCT
GAGAGATCTGTGCCAGCGGGTGCCAACATGGGGCAAGATGCCAGGCTGGGCCATGGAGCT
GCTGGTAGAGAAAGTCATCAGCAGTGCCACAGGCCCGCTGAGCCCGGGGGAGGCCATGCG
CAGGGTGCTGGAGTGTATCTCCACCGGCATCCTGCTGCCAGAAGGTCCAGGTTTGCTGGA
CCCCTGTGAGAAAGAGCCAACAGATGCATTGGAAAGCATGACTGATCAAGCCAGAGAAGA
CATTACTGCCAGTGCACAGCATGCTTTGCGGCTGCTCGCATTCCGTCAGATCCACAAGGT
CCTGGGCATGGAGTCCCTACCGGCGTCCAAGGCCAGCGCCCGCAACCGCAAGCGGAGGCG
GGATGTCAGCGACACAGGCGAAGGCGAGGGGGAGGGCAAAAAAGACAAGAAGGAGGAAAC
GGCAGAAGCTTGA
>Synodus_sp._gill_5|008833|scaffold11916|m.13587
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------CCCATGTTTCACCAGACCAAGCTGCAGAAGCCGAAGGGGCCTCCAAAGCAGCC
GCAACTGCACTACTGTGACATCTGCAAGATCAGCTGTGCTGGGCCACAGACATACAGAGA
ACACCTGGAAGGACAGAAGCACAAGAAGAAGGAGGCAGcCTTGAAGTCGGGAGGCCAGGC
AGGCCCTAGCAACGGGCCTCGCGGGGTCCAGACCCAGCTGCGCTGCGAGCTGTGCGATGT
GTCCTGCACCGGGGTTGATGCCTACGCCGCACATATCCGTGGTGCCAAACACCAGAAGGT
GGTGAAGCTTCACACTAAGCTGGGCAAACCCATACCTTCGACCGAGCCAGTGCTGGTGAA
CTCTGCCCCAGTTTACACAACCACAACAGCTGGGAAAACTCCTGCCCCTGCCGCGGCCCC
AGTGCCGGCCTCTGTGGCTGCA------------GCTGTGCCAACACCGACCCCCGCTGC
CCCCAAGCCGGCAGTGGCAAATGCCACTAACAAGACGACCGTACCAGTCAAGAAGACCGT
CCCGCCCAAGACAACCATCCCTGCCAATAAGCCAGTCAGTGCTCCAGTTGCCA-------
--------------------------------------------------AGATTGAGGA
GGTCAAGCAGCCAGCGGTGCCTAAGCCAGACCCCCAGAGCGAGGATGAGGACGGGGACGG
GTCGGGGGCAGGGGGCCAGGGTGACGTCCAGCCCGTGGGACACGACTACGTGGAGGAGGT
GCGTAACGACGACGGCAAAGTGATCCGCTTCCACTGTAAACTGTGTGAATGCAGCTTCAA
TGACCCCAACGCTAAAGACATGCATCTCAAGGGACGGAGGCACAGATTACAATACAAGAA
GAAGGTGAACCCAGAGCTGCCGGTGGAGATCAAGCCCAGCAGCCGAGCCCGGAAGCTGCA
GGAGGGCAAGCTGAGGAAGCAGAAGCAGAAGGCGGTGCTGAAGAGGCAGCGAGACGACGA
GCAGCGCTGGCACATGGAGATGAGGCGCTATGAGGAGGACTTGTACTGGAGGAGGGTGGA
GGAGGAGCAGATGTATTGGGGGGAGCAGAGACGGAGGATGGCCCCCCTTCCGCTGATGAG
CCACCCTGGTATGCCCGTACCGCCACTGTTGCCG---GTGCGTCGGCCAGACTCCCCAGA
CGACCGCCACATCATGGCCAAGCACTCCACCATCTACCCAGTGGAGGACGAGCTGCAGGC
GGTGCAGAGGATCGTCTCCCACTCCGAGAGAGCCCTCAAGCTGGTGTCCGACTCCCTGCT
GGAGAAGAAAACCACTCCCGCCGAAACTGCTGCTCCTACGATTTCTCCTCCTGCCCCCTC
CGCCGACGCTGCTGACTCTGCTGATGCTGCTGCTACCGCTGGGGAAGGACAGAACAAAAG
CGCTGaatcttCCGGACGGCTGCTGAAAGGGGTAATGAGGGTTGGGATCCTGGCCAAAGG
CCTCCTACTCCACGGGGACAGGAATGTGGAGCTTATCCTGCTGACGGCGAAGAAACCCAC
CACATCCCTGCTGAAGACGATCGCAAAGCTGCTGCCCAAAGAGCTGGCTACATTTTCTGA
AGATCAGTATGAGGTGCAGGCTCACCCTGAGGAGGCCAACATCGTGATATTTTCGAGCAA
GGAGCCCAAAATGCAGGTGACCATTTCTCTCACCTCGCCGCTGATGAGGGAGGACCCTGC
TACCGAGAAGGACAAGCAGGCAGGAGGAAAGTCGGCCGAGAAAGGTGTGGCTGATAAAGA
---ACCTGATGTCCTGAACAAGAAAAAATGCATTGAATACCTGGCCTCTCTCCGCCACGC
CAAGTGGTTTCAGGCCCGTGCCAATGGTTTGCAGTCTTGCGTGATCATCATCAGGGTACT
TAGGGATCTTTGCCAGCGTGTGCCCACCTGGGGCAAGATGCCGGCCTGGGCCATGGAGCT
GCTGGTGGAGAAGGTGATCAGCAGTGCCACCGGTCCCCTCACCCCGGGAGAGGCCATGCG
AAGAGTCCTGGAGTGCATCTCAACCGGTATACTGCTCCAAGATGGGCCCGGGCTGCTGGA
CCCCTGTGAGAAAGACCCCACGGATGCGCTGGCGAGCATGAGCAGACAAGCTAGGGAGGA
CGTTACTGCCAGTGCACAGCATGCCTTGCGGCTGCTCGCGTTCCGTCAGATCCACAAGGT
CCTGGGCATGGAGTCCCTGCCCGCGTCCAAGGCCAACGCTCGCAACCGCAAGAGgaggcg
ggacggcagtgacgcgggcgAGGGGGAGGGCGAAGGGAAGAAGGACAAGAAAGAGGAAAC
GGGGGAGGCTTGA
