>Corydoras_julii_viscera_mixture_8|019807|scaffold9511|m.6408
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------ATGAAGGCA
TCTCGCAGGAATCCGTCGTCCGAG---CCGCCGCAGATCGGCGTCGAGTTGAAACGCGTC
CTCTTCAAAATGAAGGACCTGCTGCGACAGCTGCCATCTGCACATTACAGAACCCTGCAG
TTCCTCCTGCAGCACCTGCACAGAGTGACGGAAAAGGCAGACGACAACAAAATGACCGCC
AGCAACCTGGGCATCATCTTCGGCCCCACGCTCATCAAGCCGCGTCAGAAC---GATGGT
GAGGTGTCCCGCTCGTCGCTGGTGGATTACCCGTACCAGGCGCTGATTGTGGAGCTGCTC
ATCAGGCACTACCACCTGATCTTCGACTCGCCGCTCAGCTCCGCCC--------------
----------ACCAGAGCTCACCCATCCCCTTCAAA---------GCACGCCTCACCCCG
CAGG---AGAAGGAGCAGCGTCTGAGTCGCCACTCCAGGTCCCTGGTGGACATTAAGGAG
CAA---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>Distichodus_sexfasciatus_gill_4|024022|scaffold33488|m.42408
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
AACGACTTCATTGGGCTGGCGAAGGAGTGTCAGAGCGCGGTGGTGGAAGAGGTGGAGGCG
TGTCGCCTCAACAGCACCTCGGAC---GCGCAGCCGGTCAGCGTTGAGCTCAAACGCATC
CTCTTCAAAATCAAGGATCTGCTGAGACAGCTGCCGAGCGCTCATTACAAAACCCTGCAG
CTGCTCATACGACACCTGCACAGAGTGACGGAGAAGGCAGACGAGAACAAGATGACAGCC
ATCAATCTGGGCATCATTTTCGGCCCGACGCTGATAAAGCCCCGCCAGGCGTCCGACGCC
GAGGTGTCTCTCTCCTCGCTGGTGGACTACCCTTACCAGGCACTGATCGTCGAGCTGCTG
ATCCGACACTACGAGATGATCTTCGACACGCCGCTGCCCGCCTCGT--------------
-GCACGGGGGGAGAGGGTTCTCCCGCCCCCCTCAAG---------CCCCGCCTCACTCCG
CAGG---ACAAACAGCAGCAGCTCAGCCGCCACTCTAAATCCCTGATGGACATCAAGGAG
CAGCACCATGGTGCTAAGATGTACAAACGACACTCCTCTGTGATTCCATCCACTCATCTT
GTGGAGGAAGTAAAGGAGAGAAAATTCCCAGCTGGAGAAAAGGATTTTACTGGAGCTGAC
GAAGTTGATGCAGAAACTACCAACGGAGTCCTGTTCTCCAGCGTTCCCGAAACGAAGAAT
T------CGCCCGCTTTGGGAAGGCGCAACCAC------GTCAGCAGGGTCCAACTCCGC
CCTCCCCGTCCCAGATTGGGCACCCGGCCCGTCAGTCTGCCCCCCA--------------
----CCCGGGTCGACGAGCGCAACGCCCGCAACTCGGCCGACCCGACGACGC---TCAGG
TCGGGTCGCGACCCGGCGATCGAAGAAGTGTCTGAAGAGGAGAAGCCCAAAATCAGAACC
AGGAACCACTACAGGAGCACATACATTGACACCAACACGCTGCGCAGGACTTGGGACAGG
CAATACAAGCATTACGACACCGCCCCCCGGCCCGTCGCAA------CTGATTCG---CAA
ACCCAGAAAAAGGCGGGCGACACCAACCTTCTTTCCACTTCGGCCCCGCCTGAATCATTT
CTACAACACGAAAATACTTCAGGTGACGTCACCGTCACCGTC-------ATGCCAACGCC
GATTCCGGCTCCGCGGAA-----------------ACATGCCGAAGGTACCGAGCTCGTC
CTCGGCCCCATTCCCACCGCCTTCAGGCCACCCCGGACACTAAAACCGCCCCCCGGCACG
TTCTACAAACCCCCA---AGCAGCCGGGCCAAAACGTTAC---------CGGATGCAGTC
AC------------------------------------------------------CAAG
GAGAACCAAAATGAAGAAGAAGAAGACGAGGACGAAAATGAGGAATTTGGACTCGAGGTT
TCAGTGGATGAGCCCGAAGCTGAACCCCAACCTGAGCCTGAACCTGAGCCTGAGCCTGAG
CCTGAGCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
CTGATCCTCCTGTTACGCCCAGTTCCAGCCCAGAGGAACCCGAGTCCAACTCAAATTCGA
ACCCAAACCAAGCCAAACCGGTTTACCCGAGACTCCGGGTCCGACACATGCAGGACTTTG
AAAACAGGGAGGCACATTTTGTATGATTGA
>Gasteropelecus_sp._gill_3|018651|scaffold30006|m.31758
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------AAGAAGTGCCTGGAGACCCTGGCCATCCAGTGTGGCCATAAG
AAGCTGCAGGGTAAGCTGCATCTGTTCGCAGTGGACTTCGCTCAGGCAGCCCGGAACAGC
CCGGATGGAATTCCCTTCATCATCAGGAAGTGCACCTCGGAGATCGAGAACAGAGCGCTC
AACATCAAGGGAATCTACAGGGTGAACGGGGCCAAATCCCGAGTGGAGAAACTGTGCCAA
GCTTTCGAGAATGGCAAAGACTTAGTGGAGCTGTCCGACCTCTACCCTCATGACATCAGC
AATGTCCTGAAACTTTATCTGCGACAGCTTCCAGAACCTCTCATCCTCTTCCGTTACTAT
AACGACTTCATCGGCCTCGCCAAAGAGTGTCAGAGCATCATCGTTGATGAGGCAGAAACA
TCCGGTTGCAGCCCGGCATCCGGC---GCTCCACAGGTCAGCGTGGAGCTCAACCGGGTC
CTCTTTAAGATCAAAGACCTGCTGCGGCAGCTTCCGGTCACGCACTACAAAACCCTGCAG
CTGCTGATTCGCCATCTCCACAGAGTGACCGAGAAGGCTGAGGAGAACAAGATGACCGCC
AGTAACCTCGGCATCATCTTCGGCCCCACGCTGATCAAACCGCGGCAGGCC---GACGCT
GACGTCTCGCTCTCCTCGCTGGTGGACTACCCCTACCAGGCCCTGATTGTGGAGCTGCTC
ATCAGACATTACGAGATGATCTTCGATACCCCTCTGAGCCCCCTCCCGGCTGCCT-----
-GCATCGTAGGACAGAGCTCCCCACTGCCCATCAAG---------TCTCGCTTCAACCCG
CAGG---AGAAAGAGCAGCGGCTGAGCCGCCACTCCAGGTCCCTGGTGGACATAAAGGAG
CAGCACCAGAGTGCTAAGATGTATAAGCGCCACTCTTCCGTGATCCCCTCCACCCACCTG
CTGGAGGAGGTGAAGGAGGTGAAGGTGAGGCCTGATGAGACGGACTTTGCCGCTGTCTTA
GAAGCCGATTCGGAAAACGTGAACGGAACGCTGTGTTCGAGTCTCACGGAGGTGCCCATC
T------CCCCGGGGTTGTGTAGGCGGAACCAC------GTCAGCAGGGTGCAGCTCCGG
CCCCCTCGTCTCAAACTGAGCTCCCGGCCCATCAGCTTGCCACCTGAGCAACTCCTGA--
----ACCGAGTGGATGAACGCAATGCCCGGAACTCCGCTGACCAGTCGGAG------ACG
AGAGAACGCGACCCCGCCATCGAGGAGGTCTCCGAGGAGGAGAAGCCGAAGCCTAGGCCC
AGGAACCACTACAGGAACACCTACATTGACACAAACACACTGCGTAGGACTTGGGATAAG
CAGTACAAAAATTACGACGCCACTCCTCGGGCCGCCATGATCGTGGCCAAGCTG---CCG
CCAGACGCCGAAGCCACTGAGAGCATCTCTCTCTCCACGTCTGCTCCCTCAGACTCCTTC
CTGGAGCACAAAA---------------CCACCAACTCCATTTATTCTAACACTAACAAG
GCCTTCGCCTTATCAGTGCACCCTGGCCAGAACCCCCAGCCAGAGGGCATCGCGAA----
--CAGTCCCGTCCCCACCGCTTTTAGACCACCACGGACCCTGAAGCCTCCACCTGGGACC
TTCTACAAACCTCCT---GGGGGCCAGGCGAGAACGTTAGCACTAGTAGTAGACGCCGGC
ACAAACGTGAGGAGCATAGCTCCTGTGAACAGTGCGGAGGATGACGACGAAGATGAGGAG
GATGATgaagaagaagaagagGAGGAGGAAGAGGAGGAGGAGGAGTTTGGCTTGGAGATC
TCGGTGGATGAACCTGACGCTGAC------CCCGAACCCGAGACCCAACAAGGC------
-----------------------------------------------------TGCCCCC
ACTCTCCTCCTCATTCGCCCAGCTCCAGCCCAGAGGAGCTC------------------A
ACCCAAACCAGGCCAAGCCGGTGTACCAGAGGTTCAGGGCTCGGCGGATGCAGGACTTCG
AGAACAGGGAGGCTCACTTTGTATAG----
>Lepidogalaxias_salamandroides_Head_2|018930|scaffold17431|m.23543
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------GAAAAGCTGTGCCAG
GCCTTTGAGAACGGCAAGGACCTGGTGGAGCTCTCTGACCTTTATCCTCATGACATCAGC
AACGTCCTCAAGCTTTACTTAAGACAGCTCCCGGAGCCTCTTATCCTGTTCCGTTTCTAT
AACGACTTCATCGGTCTGGCTAAAGAAAGCCAGAGCATCATTGTGGACGAGGTGGAGGAA
TGTCGCGGAGCCCCCGCCTCCCAG---ACCCCCCAGATCAGCGTGGAGCTCAACCGCGTC
CTCTTCAAGATCAAGGACCTTCTGCGGCAGCTGCCTCTGGCCCACTATAAAACCCTGCAG
TTCCTCATAGAACACCTGcACAGAGTGACTGAGAAGGCTGATGAGAACAAAATGACTGCT
AGTAACCTGGGGATCATCTTTGGCCCGACGCTGGTTAAACCCCGCCAGACG---GACGCT
GAGGTGTCCTTGTCCTCGCTGGTGGACTACCCCTACCAGGCCCTGATTGTCGAGCTGCTC
ATTCGACACTACCAGACGATCTTCGCCACTCCCCTCAGCCCCCTCCCCGCCTCCT-----
-CCCCGACAGGGGAGAGCACTCCTCCTGTTCGGAAAGGCCTGGAGTCTCGCTTCACCTCA
CAGG---AGAAAGAGCAGCAGCTCAGCAGGCACTCCCAGTCTCTGGTGGACATCAAGGAG
CCG------AGCTCGAAGGTGTACAAAAGGCACTCGTCCATAATTCCTTCCACCCACCTG
CTGGATGAGGTGAAAGAGCAGAGTCTCAGGTCCGATGTGGGGAAGTTTGCACCTGTGGTG
GATACGGACTCTGAGAGCCTCAATGGCCTGCTGTCTACGAGCCTGCCGGAGGTCCAGAGG
CT---GAGCCGGGGCTTCAGCCGGCCCAGCCATG---GGGGGGGGCGCGTCCAGCTGCGT
CCACCGCGCTCCCGGTTCGTCTCACGGCCCGTCAGCCTCCCCGCGGAGCGACTCCTCAAC
CCGGCCCGCGTGGACGAGCGGAACGCCAGGAACGCTGCCGAACAGGAAGGA------GGC
GGGGGTCGTAACCCCGCCATCGATGAGGGCCCCGAGGAGGAGAAACCAAAGTCCAGGGTG
AGCACCTATTACAGGAGCGCCTACATCGACACGCAGACGCTACGCAGGACGTGGGACAAG
CAGTACAAACATTACGACGTCACGCCGCGGACCGCCATGATCGTGGCTAACCTGCCCCCT
ACGGAGAACGCGGCGGCTGAGGCCGGCGCTCCCTCGCTGGCCGTGCCGTCGGCTTACGCT
CCCGGGAGCA---------------------------------------GCGCCAGCAAG
CCCTTCAGCATGGCCCTGAGGCCTGGGAGAACTTTGAAACGGGAGGAGAACGTCAGCGAG
TTCACCCCTGTGCCCACGCTCTTCAGAACGCCACGGACCCTACAGCCCCCACCCGGAACC
TTCTACAAGCCCCCTCCCAGTAGCCGCGCCAAAGCGCTAGCA----GACGGGGGGCTAAA
GCG---------------------CTGTCCAGTG--------------------GGGGCC
AACAGCACGGAGGAGGAGGAGGATGAGGAAGATGAGGATGGGGACTTGGGGCTGGAGGTC
TCCGTGGATGAGCCCATTATTGA-------CGCGGGGGAGCAACCCGGC-----------
-----------------------------------------------------ATCCCCC
TCTCCCTGTCCCAGTCACCGAGCTCCAGCCCGGAG---------------------CTGA
GCCAAAGTGAAGCCAAGCCCTTATACCAGAGACTCCGGCCCAGGAGGCTGCAGGAGTTTG
AACACAGAGAGGCCCACTTTGTATGA----
>Pantodon_buncholzi_mixed|004357|C630744|m.35780
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------CAGGGACGTCTCCACCTCTTTGGAATAGACTTTACCCAGGCAGCAAGGAACAAC
CCTGATGGCATTCCTTTCATTATTCGAAAGTGCACCTCGGAGATTGAAAACAGGGCCTTA
AATATCAAGGGAATATACCGTGTGAATGGAGCCAAATCCCGTGTGGAGAAGCTCTGCCAG
GCATTTGAAAATGGTAAAGATCTGGTGGAGCTGTCTGAGCTGTACCCACATGACATCAGC
AACGTCCTCAAACTCTACCTTCGACAGTTACCAGAGCCTCTCATCTTGTTTCGCTATTAT
AACGACTTCATCGGCCTGGCAAAGGAAAGTCAAGGCGTTATAGCAGAGGAACTGGAGAAA
GCACGCAAGGTCATATCACCTCAA---CAGAACAACGTCAGCATGGAGCTCAACCGAGTC
CTCTTTAAAATGAAAGACCTTCTGCGACAGCTTCCCCCACCCCACTACAAAACCCTGCAG
TTCCTCATTGGACACTTACACAGGGTGACTGAGAAAGCAGATGAGAACAAGATGACTGCC
AGCAACCTGGGAATTATCTTTGGTCCCACTCTAATCAAGCCCAGGCAGTCG---GATGCA
GACGTCTCCCTCTCCTCACTTGTAGACTATCCCTACCAAGCCCTCATCGTTGAGCTGCTA
ATCCGTCACTACGAGAAGATCTTTGATACACCGCTAAGCACCATA---------------
---------------------------------------------CCTGAGCCCCCCTTG
CAGGCTCTGAAGGGACTGCAACTGTGT------------------GTATCAGCCAAGGAG
AAG---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
GAG---------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>Sargocentron_rubrum_gill_6|013762|scaffold2172|m.2460
ATGCTGGCTGCCATGCTGCGCCAGAGTAGTGGAGGAGGAGGTGGTAGTGGTGGTGGACCC
AAACTCTCCTTGGGTATCTCCCGACTCTCCAGCTCCGGCTCAGGCTCGGTGGGCCCTGCT
GGCGTGGGCCCCTGGGTGCTGGGCAGGGCCGCCAAGAGCAGCTCCATGAGCTCGGTCAGC
TCTGGCTCGGACAGCACAGACATGCCCAGCTCGGACCCTGACTACATCATGCAGCTGGTC
AACGACGTGCGCAAGTTCGCCGACGTTCTTCTACACCTCAAAGAAGTTTTCAACTCCAAA
GAGCACCAGGACTGCCTTCATCAGGCGGTCCACGAACGTCTCGGGGAGCTGCTGCGAGTC
CTGAAGGCCATTATCAGCAAACACCAGAGCCTGAACTCAGTGGACATCCTCAGCACAGCT
GGAACCGTCATCGCCAGGGTCAAAGGAGTGAACTTTAAGGAGGTGAATGAAGAGAACAAA
CAGAAGCTTTTTAGCGAGATCTACACTGCTATCGACACATTGGCATTCACCTTTGGCAAT
GTAGTGTCTGACTTCCTTATGGGAGATGTAGAGAATGGATCAGTGTTGGGGCTCCCCCTA
ACTAAGAGAAGCAGATCTTTTGAAAACCTCTGTGTGGAATCTGGAGGATCCGGTCCAGAG
AAAGATGATCCACCAGGGCCCTCTCCGCCGGTTCGGGCCGAGGAGGTGGACGGGACGCTG
CAGAGGCGGGACAGCGGGGTGGAGACGGCGCTGCTCTACGCTAAGGCCTGGTCCAAATAC
ACCAAAGAGCTGCTGGCTTGGGTGGAGAAGCGTCTCAGCATGGATATCGAGTGTGCAAAG
AGTTACACCAAAATGGCCGAATCTGCCAAGACGCTTGCCAGCCAACAGGAGTTCATGCCT
TTCCGTGAGATCTACATGTCGGCTTTCAAAAACGACATTGAGTACAGCCAGGTGCTGCTT
CACACTGCGGCCGCTCTCCAAACCAACAAATTCATGCAGCCTCTCCTGTCCAGAAAGAGC
GAGCTGGACAAACTGCGAAAAGAGGtcaaggagcagtGGCAGAGGGAGCAAAAGAAAATG
CATGATGCGGAGAACGCCCTGAGGAAGGCTCGCCTGTTGCAGGCCCAGCGGCAGGAGGAG
TACGAGAAGGCCAAGGTGTCCACCAGCCGCCTGGAGGAGGAGCAGATGGGCGGAGGAGGA
GGAGCGGCGGCGGCCAAACAGCTGGAGAGGCGGCGCAGGCTGGAGGAGGAGGCCCTGCAG
AAGGCGGAGGAGGCCAGGGAGCACTGCAAAGCCTGTCAAATCGACGTCGCAGAGAAGAGA
ATGGACTTGGCCAACACCAAGAGCGAGATCCTCACCCAGCTTAGAGAGATGATCTTCCAG
TGCGACCTCACCCTCAAGGCTGTGACGGTTAACTGGTTTCAGCTGCAGCAGGCCCAGGTT
GTGTCTCTGCCTGTCAACCACCAGAGTCTGTGTGAGAACGCCAAGCTGTACGAGCCGGGC
CAGCGCTACGTCGACTTCGTCAGGAGTCTGCCGGCCGACCGGCCTCGCGTGGAATCCCAC
TCCTTCGACTCTGGCATCACGCAGAACACAGGGATACCTTTCACCAAGCGCACACTAAGT
GGCAGCCACTCATCCCACGGCAACCTGTCGCAGGCATCTGTGACGTC---TGACCTCCTC
AGTGCAGACGAAGTGGACAGTCCCATCCACGCTCGACCCG---GCAAGATCTCAGAGAGG
CGCTCCAACAGCAGCACGGACATCCAAGCACTTAGGATTCAGGGCCCATTTCGTCCCTGG
GCGTCGGGCACTCAAGGTGGGGGGATGTGCAGCGATTCAGAAAGTGCTGGAGGAAGCAGT
GAGTCCCGATCCATGGATTCTCCCACTGCCAGTCCAGGAGACTTCAAGAGGAGATTACCC
AGAACCCCCTCAACTGGCACCATGTCGTCTGCAGACGACCTGGACGAGAGAGAGCCTCCC
TCACCCTCCGATAATGGTTTAAGTGAGATGGTGATAGAGACAGCCAGCTCTCCAGGCCCC
TTCAGAAACACCCAGATGTCCAAGGCGGCCCAAACCCACAAGCTGAGGAAGCTCCGTGCC
CCCTCCAAATGCCGCGAGTGCGACGGCCTGGTGGTATTTCACGGAGCAGAGTGCGAGGAG
TGTTCGTTGGCGTGCCACAAGAAATGCCTGGAGACGCTGGCCATCCAGTGCGGTCATAAG
AAGCTCCAAGGGAGGCTTCATCTTTTTGGCATCGACTTCACTCAGTCGGCTAAGAACAGC
CCAGACGGGATCCCCTTCATCATAAGGAAGTGCACGTCAGAGATTGAGAACCGAGCGCTC
AACATTAAGGGTATCTACCGAGTGAACGGTGCCAAGTCTCGTGTGGAGAAGTTGTGCCAG
GCGTTTGAAAACGGCAAGGACCTGGTGGAGCTTTCCGACCTTTATCCCCACGACATCAGC
AATGTGCTCAAACTCTACCTGAGACAGCTTCCAGAGCCGCTCATCCTGTTCCGCTACTAT
AACGACTTCATCGGTTTGGCCAAGGAGAGCCAGAGCATCATCGTGGAGGAAGTGGAGGCG
TTGCGGCTCAGTCCCACCCCGGTGACCCCGGCCCAGGTCAGCGTGGAGCTCAACAGAGTC
CTCTTCAAGATCAAGGACCTGCTAAGGCAGCTGCCACTGGCTCATTACAAGACCCTGCAG
TTCCTCATAGAGCACCTCCACCGAGTGACGGAGCGGTCGGAGGAGAATAAGATGACGGCC
AGCAACCTGGGGATCATCTTTGGTCCGACGCTGATCAAGCCAAGGCAGACG---GACGCA
GAGGTTTCTCTTTCTTCCCTGGTGGATTACCCCTACCAGGCCCTCATTGTGGAGCTGCTG
ATCAGACACTACCAGATGATCTTCGACACGCCCCTCAGCCCACTGCCGGGCACCTC----
-GCCCACCGGGGTCGACGCCCCGGCCGAC----------------TCCAGACTCACCCAA
CAGG---AGAAGGAGCAGCAACTGAGCAGGCACTCCAAGTCCCTGGGAGACATCAAGGAG
CAG------AGCTCTAAGGTGTTTAAGAGGCATTCCTCCATTATTCCTTCTTCCCACATA
CTGTCTGAGGTCCAGGAGACCATGCCAGGCCTTGATGGGAGGGACTTTGAATCTGCTGAA
GACGTTGATTCGGAGACCTTGAACGGAGTTTTGTCGTCGAGCATCCCCGAGGTCCAGCGG
TCTGGCGAGAGAGGCCTCAGTCGCTCCCATCACATCACCGTCACCAGAGTGCAGCTCCGG
CACCCTCGCGGCAAACTCTCCTCCCGGCCGGCCAGCATGCCCGCCGAGCGGCTGCTCAGC
CGCGGCCAGGTGGACGAGAACAACGCCCGAAACAGCTCCGACCAAGACAAAGGGAAAGGG
AGCGGCTGCGACTGGTCCATCGAGGAGGTGTGCGAAGCGGAGAAAACGGTATCGCGAGCG
GGCACGCATTACCGGAGTACGTTTATTGACACCCAGACGTTACGCAGGACTTGGGACAAA
CAGTACAAGCATTACGACGTTTCCTCTAGGACTGTCAAGGTGTTGTCCAGTTCT---ACA
GCAGAGGGCACATCAGTGGATACCAGTAACTTATCAGCCTCTGTGCCCTTGTCCACCTCC
CATGGAAGTAGCG---------GGGGCACTACGAGCTCCATGT------ACCCAAACAGA
CCTTACACCATCGCAGTGCGGCCCAGCAGGACTTTGAGAAGGGAAGACAATGTAAGTGAG
TACAGCCCTATTACAACGGCTTTCAGGGCACCAAGGACTCTGCAGCCTCCCCCAGGAACC
TTCTACAAACCCCCCTCAGGGAGCAAAGCCAAAGCGCTGG----ATAACTGTGTGCTAGC
GAA--------------------------CAGCGCTGAG---GAGGAAGAAGAGtacgag
gaggacgaggaggagGAGGAGGAAGAGGAGGAGGAGGAGCTGGGGATCGAGATCGAGGTG
TCCGTGGACGAGCCTCTTGAGGAG---------GACATCGAGGCCGAGCAGGCGGCC---
-----------------------------------------------------GTGTCTC
TCTCCATGCCCCAGTCGCCCAGCTCCAGCCCGGAGGAGCTT------------------G
GCCAAAACCAAGCCAAACCAGTGTACCAGAGACTAAGGCCCCGACGCCTCCAAGAGGTGG
AGCACCGAGAGGCTCATTTTGTGTGA----
>Scleropages_formosus_red_gill|019353|scaffold30481|m.39418
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------TTCCTTATGGGAGATGTAGACAGAGAATCAGTGCTGGGACTCCGCCGG
ACTCTCAAAAGCAGGTCTTTTGAGAACCTGTCGGTGGAGTCTCCGGGATCCATTTCCGAG
AAGGATGACCTTCCAGG------CACGCCG---CGGGCTCAGGAGGTGGACTGCGCACTT
CTGGGCAGCGACAGCGGCGTGGAGTCAGCATTGCTCTACGCCAAGGCCTGGTCCAAGTAT
GCCAAAGAGCTGCTGGCCTGGGTGGAGAAGAGGCTGAGCCTAGATATCGAATGTGCAAAG
AGCTTTGCAAAAATGGCCGAATCTGCAAAGGCACTCGCAAGTCAGCAGGACTATATGCCA
TTCCAGGACTTTTATATCTCCGCGTTTCAAAATGACATTGAATACAGTCAGTTTGTGCTG
CAAACAGCTTCCGCTCTTCAGACCAACAAATTTACTCAGCCTCTGTTGTCCAGAAAGAAT
GAACTGGATAAACTTAGGAAAGAAATGAAGGAGCAATGGCAAAGAGAGCAAAAGAAAATG
CAAGAAGCCGACTGCGCCCTGAAGAAATCCAGGCTGCTGCAGATCCAGAGGCAGGAGGAG
CATGAGAGGGCTCGCACGTCCACCAGCCGCGCGGAGGAGGAGCTGGTGGGCAGCGGAGG-
--------------CAAGCAGCTGGAGAAGAGGAGGAGGCTGGAGGAGGAGGCGCTGCAG
AAGGCAGAAGAAGCCAAGGAACAGTACAAAGCGTGTGTTGCAGACATGGAGGTGAAGAAA
GTGGATCTGGCCAATGCCAAGAGCGAAATTCTCGCTCAGATCCGGGAGCTGGTGTTCCAG
TGCGACCTGACTTTGAAAGCGGTGACGGTGAACTGGTTTCAGATGCAGCAAGCCCTGGCC
GCCTCCCTGCCGGTCCACTACCAGACCCTTTGTGAGAGCGCCAAGCTGTACGAGCCAGGT
CTGCGCTACTCCGACTTTGTAAGGAGCCTCCCCAAAGACAGGGTTCGAGTGGACGCCCTC
TCCTTCGATGTTCCCAGCCTCCAGAACACCGGGTTACCCCCGACTAAGCGACAAACAAGC
AGCAGCCACTCCTCTCACGGAAACCTGTCTCAGGTGTCGGCCACATCGGGCGACTTCCAC
AGCACTCTCGAGGTTGACTGTCCGGCTCACACACGCCTGGGACGGAAGATTGGGGAAAGG
CGCTCCAACAGCAGCACTGACATCCAAGCGCTGCGGATCCAGGGCCCGTTCCGAGCGTGG
AGTACGGGCAGCCAGGGAGGGGGGATGTGCAGCGACTCCGAAAGTGCTGGGGGGAGCAGC
GAGTCCCGCTCCATGGACTCCCCAACTGCCAGCCCAGGCGATTTTAAAAGGAGGCTCCCC
AGAACCCCCTCCACAGGCACCATGTCCTCAGCAGACGACCTGGATGAGAGAGAACCCCCG
TCCCCATCAGATCTGGGTATGAGTGAGATGGTGGCGGAGA---CCAGTTCCCCTGGACCT
TTCCGAAATGCACACATGTCTAAAGCTGCCCAGACCCACAGGCTGCGGAAGCTGCGGGCC
CCTTCCAAGTGCCGCGAATGTGATGGTTTGGTCGTGTTCCATGGTGCAGAGTGCGAAGAG
TGTTCCCTCGCTTGTCATAAGAAGTGCCTGGAAACACTGGCCATCCAGTGCGGCCACAAG
AAACTGCAGGGGCGACTGCACCTCTTTGGCATTGACTTCAGCCAAGCCGCCAGGAACAAC
CCGGACGGCATTCCGTTCATCATCAGGAAGTGCACCTCAGAGATCGAGAACCGGGCCCTG
AATATCAAGGggatctaccgcgtgaacggagCCAAGTCCCGAGTGGAGAAGCTGTGCCAG
GCATTTGAAAATGGGAAGGACTTGGTGGAACTCTCTGACCTGTACCCCCATGATATAAGC
AACGTACTTAAGCTCTACCTCCGACAGCTTCCGGAGCCACTCATCTTGTTTCGCTACTAC
AATGACTTCATTGGCCTGGCGAAGGAGAGCCAGAGTATACTCTCGGACGAGGTGGACAGG
GGACGCAGCACTGCGAAGACTGAA---CAGGCCCAGATCAGTGTCGAGCTCAACCGGGTC
CTCTTCAAAATCAAGGACCTGCTCCGACAGCTGCCTCTGGCACATTACAGAACCCTGCAG
TTCCTCATAGGACACTTATACCGAGTGACAGAGAAGGCAGATGAGAACAAAATGACCGCC
AGCAATTTGGGGATCATCTTTGGGCCAACGCTGATCAAGCCCCGGGGGGCG---GATGCT
GACGTGTCACTGTCCTCGCTGGTGGACTACCCCTACCAGGCTCTCATTGTGGAGCTGCTC
ATCCGTCACTATGAGAAGATTTTTGATGTCCCTGCTGGCCTGCCGCCAGGCCACGGCCTT
GCCCCGATGAAGGAGAGTTCCCCCATGTCAGCGAAGGGGAGCCTGCCTAGGGCCACTCCC
CGTG---AGAAGGAGCAGCAGCTCAGTAGGCACTCAAAGTCCCTGGTTGACATCAAGGAG
GAG------AGCACCAAAGTATACAAAAGNNNNNNNNNNNNNNNC---------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------TGCTAG-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
