>Amblygaster_clupeoides|031172|TR56923|c0_g1_i1|m.76218
ATGGCTGCCGAACACATACAAAAACCCGTCACAGTGCAGTGCGACCCGTGTACTAAGTCA
GACAATTATGTAGATATAAAGAAAGATGAATCTGATGTCTCTATAGGAGAACATGGAGTA
AGTGTAAAGGATTTAAGTAACGATGCTGAACTGAAAGAATCTGTGGAAACTGATGTTAAT
TCAGGGTTGGTAAGTCATGCAGAATCCAGCACAAGTCTGGTTGATTTTGAGTCGACAGCT
AGTAAAACAGAGTCGAAGATGCCCTCCCTTGTTTCCTCAAAACTTCAGCTCCAAATGGAA
TGGTCTGACACAGAGGAGGATACGG--------------GACAATCCATAATGGGGGACT
GTGGAAAAAAATCGCTTGAAGCTGATGGAGCAGATGCCACTCTTGAGTCCAGGGAAGACG
CTGTACAACCTTC---ATCCGGAGGTAAAGCTACTTTGGAACTAAAAGTAGAACCACCCG
AGCTGCAGGATGAGCCGACTGCATCAGAAGAAGTAAGGAAAGAGTTTCCTGTTGAGGAAG
CACCTTCACTAGATGTTAAGAGAGGAGAAATAGAAGATGAAAAAGGAAAGGAAGGGGAGG
AGGAAGCGGCAGCAGGCGGGGGAGGTCAGGTGGAGGAAGAGGTGGTTGTTG---------
------TCAAGCCGAGGAAGACGCGTCTGGAATGCCGCGAGTGTGGAAAGTGTTTCACTC
GCCGCGAGACGTACAACCTTCACCGTCACTTCCACATGCATCAGGATGAACAAGCCTCCC
TCACCTGCAAAGAGTGCGGCCTCACATTCCAGCACAGAAGCAGCCTCATCAAGCACCGAA
ATGAGCACAAGGAGAAGGAGAAAGAGAAAGAAAAAGCTGAATTGGCACCAACAGTACAAG
CAT--CACCAACAGCATCATCAGACAAAAAAACCCTCTTCAAGACAGCTAACTCACAAAT
TGACCCACAGTGTGAATATTGTGGGAAGACATTTGATACACTGGC------CAAGCTCCG
CACGCACAATTGTAAACTCGCCCCAGAGAAGCCCTACCGATGTCCGTTATGCCGCAAGGA
GTTTCAGTATAGAGTGTCCATCACTTCCCACATGCAGACACACTCCCTGGAATACCCTTT
CCGCTGTCTGGAGTGCAACAAGGGTTTTCAGTCGGCCATGACGCTGAGAATTCATCAGCG
GTCCCATGCTGCCCTTAAGCCCTTTGCTTGTCCTGAGTGTGGGATGGTCTTCAGGCATCG
CTCAGTCATGGAGGATCACCGGCGGAGACATACAGAGGAGCGTCCTTACCACTGCAACCT
GTGTGGCAAGTGCTTCAAGTATGCCAGCCTCCTGCACCAACATCAGTATTTGCACACAGG
CAAAAAGCCCTTTCGGTGTCGTGACTGTGGGAAAGCGTTTGCTTTTTCCCAGAACTTGCG
TGCTCACATGCGCCAGCATCAGAAGCACCCGCACAGCTGCCCTCACTGTTTGGATACCTT
TTCTGATGAGGCTAAGCTGCAGGAGCACGTTGCCACCCATGAGATG---TCAGCTGTGGT
AGACAAAGAAAATGCAAATTATGCTTTGGAGCAGCCGCGGCTTTACAACTGTCCTCTGTG
CTCCCAAGTGTATTACAGACCTGCTGACCTGAGGGTGCATATGCTGG---TACACGAAGC
AGAGTTTGAGGGCATGAGCAACGGAGTGACAGAGGCAGAGCGGACGTATGCCTGCTCTCG
GTGTTCATTGACATTCTCAGATGAAGCGAGCCTACAGTCCCATTCCATTACCCATGAGGC
T---------TCGTTCATGAGGAGGGATGTACGTGGCCTGGGCATGGGACGGAGAGAGAG
CATGCCAGGAAGTGGGATCTATGGTGACCAGATAGACAAGAAACCGCTGAAGTGCCGAGA
CTGTGGCCGAGGTTTTCGCCACCGCTCTGTACTGGAGTTGCATATGCGCATTCACAGTAA
GGAC---AAGCCATACCGTTGCAATGAGTGTGGCAAGTCCTTTAGGTTTGGCAGCTACTT
GCAACAGCACCT----CATAATCCACACAGGGAAGAAGCCATACAAATGCCCTGACTGTG
GAAAAGACTTTGCATTCCTCCAGAACATGAAGACCCATCAAAGACTTCACCAACAAAAGC
CATTTCGTTGCACGCAATGCCGTAAAGGCTACAGTGACGAGGATCAACTGCAGAGGCACA
TGCTGTCCCACACTGGTGACAAGCCACACAAATGCCACCTTTGCCACAAAAGTTTTGGCC
TGGCATACCTGCTGCGAGATCACATGAACACACACACAGGTGAGAGGCCCCATCGCTGCC
AGGAGTGCAACAAATCATTTCAGTGGCTCAGCAGCTTATTGGTGCACCAGAAGATTCACA
TGCGCAAGCATCAA--------------------------------------------GA
CGGCAAGAGG-------------GGCAGGAAAGTCAACACTTACAGATCTGACTGGCAAA
GGTGGGACAGAATTCCTGGAACAATGATGCCAACCACTTACGCTGCCTCTGCCTCACAAG
TGCCGGACTGGCAGGGAAGGATGCC-CCAGCCGCCGCAGGGCTTTGTGCATCAGTCTGAA
TCCCAGGAGCGGCCAAAGCAGCAGCCACAGCAGGAAGCGTGGCAGCCTAGTGCCCCAGTC
TCACAGCAAACACAGTGGAAACCGGAACAGAAGCAGGAACCACA-GAGGCAGCCAGAACA
GCCAGCAAAGACAGTCCATGCACAACAGCAGCAGCAGCAATGGCAAATGGAGCGA-----
-CAGACCCAGC--CAGCCCAGATGCTGCCCCAGAATTCACCATGGATTTCTGTGATGGCC
CCGCAGACGA-ACCAAGCAGTGC--------------------AACAGCAGGCACAGCAA
AAGTTA-----------------------CTGCTGCAGCAACAACAAGCTC---------
CAGCTGAAGCACTCTCTAGCAGGACTGACTCAGCTCTAACTTCACAAGCAGGAGGTGTGT
TTTCTAAACCCCACACACAGCCAGAAGATGGTCCTCTTGCTTGGGGCACCAAAACATCCC
CTGTTGTTTCACACATCCTAACCCC------------------GTCAAAGGCAGCA----
-----GAGCATGAGAAGAGTCCTCTTTCAGTCTTCTGGGGTAGCACTAGTACCTCTATGC
-------AGCCACAGACCC----CAACAAGCACTGTTCCTCTTGA--AAGTG--------
---------------------------------GGTCCATCATCTCCCCCGCTAAGCCAA
ATGACCAAGA--------GCTAAAGTTGTCACAGCCACAGTTAAAAGCTTC---------
-------------------------------------AACCTCCATA----------CAA
ACCACCCAGCCTGGGTTGCCCTCTCT------------CCCATCAAAAGATGACACTAAC
TTATGGAGTTATAAAATACCAATTAGTGTACCCCTGACTAT------ACAAGACCAGCTT
AGCAGTGGCACAGATAAACAACAACGACAG----CAAACTC-------------------
----------CAGGCTCAGCAAACCAATC---CTTAGCAACAAACCAAACTT--------
----------------CCATTATAGACCCTT-----------------------------
------------------------------------------------------------
----------------------------------------------------------CT
CGTGTAGCACCTGGGACAGAAAGCACCCACTGGACATTCCAAGCTACCTCAGGCAT-TCC
CAAGCCCCTAGGAACTCCAGATGGTAGTGCAGTAGAA--------CAGCTGCA-------
--------------------------------------------------GCAACAACTG
CAGCAACC-------------------------------------TCCGCAAC---TAAT
GCACTTGCAG-------------------------------------------CAACAAA
AG----------------------------TTACAACTACAGCAACAGCAGCAGCAAC--
------------------------------------------------------------
-------------AACAACAACACTTACAGT-----------------------------
-----------------TACATCAGCAGCAGCAG-------------------------C
AGCAGCAG-------------
>Corydoras_julii_viscera_mixture_8|010515|scaffold18573|m.13738
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------atgaacctgct-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------ggcgaaGCGGAATGGGGCGACCAGGAGGATAAGAAACAGCTGCGGTGCAAAGA
TTGTGGGAAGAGCTTCCGTTACCGCTCGGTTCTCGAGCTTCACATGCGCGTACACAACCG
CGG---------GTATCAGTGCCACATCTGCAAGAAGTCGTTCCGCTTTAGCAGCTACCT
GCAGCAGCATCTNNNNNNNNNNNNNNNNNNNNNNNNNNNNCTTCAAATGCCCCGACTGTG
GCAAGGACTTCGCCTTTCTCCAGAACATGAAGACGCACCAGAGGCTGCACCAGCAGAAAC
CGTACCGTTGCACGCAGTGTCGCAAAGGCTACAGTGACGAGAGCCAGCTGCAGCGCCACT
TGCTCTGCCACTCCGGGGACAAACCCTACAAGTGCAACCTGTGCAACAAGAGCTTCGGCC
TGGCCTACTTGCTCCGCGATCACTTGAAC-------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>Distichodus_sexfasciatus_gill_4|009094|scaffold13142|m.14203
G----AGCCGAAGCAGTGTTGTGATGAAACGGCGCAGACTGGGAGCAGTTCACCTCTTCG
AAC-----------------------CAGCTTCACCTCCGCCACAGAAAAGCACGAACCG
AAC---------------------------------------------ACTTCTGCTGGC
CTTCAGCCTGGGGATGTTCCCAAACCCGGC--------GATGTGTCTCcactccacag--
-------cgaaagtGAACTTGTCTT-----------------------------------
--GTCGGAAACAGAAGGGGATTGGGATGTTGGGCGGCCCGTCAAACCGTTCAAGGAAAAC
ACGGGGGATGA--GCTTCAAGCGAAAGCAGGTAATCAAGCTAAAGAAGACATCAAGCATG
GTCTGAAACATTCTGTATCAAAAGATGAAGATG---------TGAATGAGGAAATGTT--
---------GTGTAATGATGAAAATAAGGGCCATGAGGAAGA----------CAAGGAAG
AGGACTCTCTAGGTGAAGAGGAAGGAGAACTTGGAGGTGGAGAAAAGGGAAAAGAAGAAT
TTGAAGGAGAGGATAGAGGTGGTGGTGAGGAAGAGGAGGAGGAATTTAATGAGACAGAGA
CAGGCATGAAAAGGAAGAAAAGCCGATTGGAGTGCCATGAATGTGGCAAGAAGTTCACAC
GACGAGAAACTTACAACCTGCATCGCCACTTTCACATGCACCAAGATGAACAGGCTTCCC
TCACATGCAAAGAATGCGGCCTCACCTTTCAGCATCGCAGCAGCCTTATCAAGCACCGCA
GCGAGCACAGGCAAATCAAGA---------------------CGCCGCCCCCAGCGCCAG
TCTCACACAAGCGGTCGAGTCAGAGAGAG--------TTCAGGGTGG---------AAAG
GAGCCTTGAGTGTgaccactgtggcgATCGCTTCTCATCACTCATCGCCTACAAGCTCCA
CGC------TTGTCGGCAGAGAACGGAGAAGCCTTATCGCTGTCCACTGTGTCGCAGAGA
GTTCCAGTACAGAGTGTCCATTAATGCCCACATGCAGAGCCATTCGTTAGATAGTCCCTA
CCGCTGTCTTGAGTGCAACAAGGGCTTCCAGTGTGCACTGACTCTGCACATCCACCAGCG
CTCCCATGCCGCCCTCAAACCTTATGAATGCCCCGACTGCGGCATGGTCTTCCGGCACCG
CTCGTATATGGAAGACCATCGTCGCAAACACACAGAAGAAAAGCCACATCAATGCAAGAT
GTGTGATAAAAGCTTCAAGTACAGCAGCCTTTTGCAACAACACCAGTATCTTCACACTGG
CCAGAAGCCATACCGATGCCCAGAATGTGGGAAGAGATTCGCATTTGCTCAAAACATGCG
TGCACACTGCCGTCAGCACAAAAAG-------AAAATTGACTCCGCTAGTTCAGAACCAC
ATTTTACAAG--------------TTATGATGTGACTAATGGGACAGATTTAGAAATATG
TGGTAAAGAAAACACAAACCATGACATCCAGCAACAAC------GCAACTGTCCGCTATG
TCCTCAGCTCTTTTCTAATGCAGCTGACCTTAGGGAACATATGTTAA---TTCATGAGAT
GGAATATGAGAAAATAAACAATGG---CAGTCAAGTTGACCAGACCTTTGCTTGTCCATA
CTGCCCACTCAAGTTCTTTGATGAGTCCAGCTTACAGTCCCATGCTTTGAGTCATCAGGT
TGTACAAGCATCTTTGAGAAGGGAGGTTCTCAGTATAGCAAGGGCAGAGAGTGCTGATAA
CATGTCAGGAGGAGGGGAATGGGTGGACCAGATGGAGCGGAAATCGTTGAGATGCAAAGA
CTGTGGGAAATGTTTCCGTTACCGTTCGGTTTTAGAGCTTCACATGCGCATTCATACCAA
GGG---------ATACCAGTGTCATATTTGCAAAAAGTCCTTCAGGTTTAGCAGCTACTT
GCAGCAGCACTT----AATCATTCATTCTGGAAAGAAACCCTTCAAGTGCCCtgACTGTG
GTAAGGACTTCGCTTTTCTCCAAAACATGAAGACTCACCAGAGGCTTCACCAACAGAAAC
CCTTCCGGTGCACGCAGTGCCGCAAAGGCTACAGCGAAGAGTCTCAGCTGCAGCGTCACA
TGCTCTGTCACTCGGGTGACAAACCACACAAGTGCCACCTCTGTGACAAGAGTTTTGGTT
TAGCATACTTGTTGCGTGATCACCTGAACACCCACACTGGTGAGCGGCCTCACCGTTGCC
AAGAGTGCCATAAGTCATTTCCTTGGCTCAGCAGTCTCCTAGTCCATCAGAAGATACATG
TGCGTAAGAGGCAAGGGTTGAACCAGTCTTCCTCTTCGTTAGGGGTTTCGCAGAGGGGAA
GGACCAGAGGGGTGGGGGGTAGGGGCAGAAGAACTAGTAGGTGGGGTTCAGGATGGCCAA
GGGTGGGCGATGCTATGGGAAGGACAGGCCTACAA---CAAGCCTCTTTTTCTGGTCAGG
T------TTTGCAGGGAGTGGCGTTGACGAATATAGTGGGGCAACCCCAACCTGTCT---
----------------------------------------------TTGATGCAGATATG
CGTCAGCAAGCACGATTGAGAAC---ACAGTCTTTACAGTCCT----GGCCAACAGAGAG
CCAAGTTAGGCCTGTTCAGCTGCAGCAGCAGCAATGGCAAATACAAATCCGGCCTCCATT
GCAAGCCCAGCTACAGCCTAAATGGTTA----------------------TATGAAGGGC
AGCCAAGTGACACCCAACAACACTGGCACCAAGGATCTTACTATAAACCTATCTTACCAA
AATTAGAAGGTGTCCCAAAACTTACAAATCAGCAGCAGCAACAAAAGAGCCCTGGCTGTT
CTGCTGTGGTGCTGTCAACACAGACTGCCACAGCTGCTA-------ATCAGAACAC----
-------------CACAGAACAAGATAACAGC------GGCATGGCTAGTGAAACCTCTG
ACACTGCAAGGTTTACTTCTACCAT------------------GTCAAAAGCAAAGAATG
AACTGGAGCAAAAGACGAATGAGCAGCCAACTTTCAGAGCCAATTCACCCTCATCAACT-
---------CCAAAGGCATCACACAGTGCTGACAGACTGTCATCATCAAGTGTTCA----
----AGCACATTCTCCTGT------GACTTCACAGTCCATTAT-TCATGATCCAATCCAA
AACACTAAGGCAGAACAGTCTGAAAAGGACAACAAAACAGATGGAAGCTTGATGCAGAAT
AAGAATGAAGCAGACAAACCAGCTAAGAGTAAACACGATCCACCACAAGGACAAGAGTCA
ACGGTTCTGCCTGACTCATCTGTTTCATCAAAAATGGAGCCAGCAGAGAAAAATAATAAG
CCTTGGAATCTCCGAACTCCACTGGAAAGGTCAAGGGGCAA------GCAAGAAAAAGCT
GTGAATGAAAATGAGTCCCAGCAGCAGCAG----CAGGCCCTGCAGCCACAACCACAAAT
GTCACTCTTGCAAGAGCAGCAAGAGAAGCAGTTACAACAACAAATACAACTTCTCCAGCA
GCAAAATCAGATGGCCCCCTTGTGGGTGTCTGCGCCTCA---------------------
------------------------------------------------------------
-----------------ACCCAGCCAGTTGGGGTCAGTCAGTATTCAGCTTGGTGCAGCT
CGTTTTACTCCTGGAaatggaagtgcagtgtggggcttccagaCCGCCCCTGTTGTGTCT
CAAGCTTTAGTAAATGGACCATTGCAACAAGGGACGGTTCGAGCACAGCCGCAATCTCCG
GTGGTCTCGGGCCCTCAGATCCTTTTAAATCAGACCCCTCCATTCATCTCACTACCACTG
CCTCTGCCTCCTTCTCTTGCTTTGCCTGGACCTCATCCGATCCATTCTGTAAC---TGGG
CAGCTTGCAGGGGCGGCATCTCCAAGCATCTTTTTCACTCCACAG---AGCCTTAATGAG
AGATCTGTCCTGCCACAAGCCCTG---CCTTCACAATTAGCACAACGAACAGAGCCACT-
-----TGGCAATCAAATACCCTTTGCACCGGATCGCCGTTGTCAATGCATGATCTGTGGA
GGCACCTTACCTGGAGAATTAGAATTACAAA-----------------------------
-----------------TGCATTACATGCAACAT-------------------------G
CGCAGGGAGAG----------
>Gasteropelecus_sp._gill_3|018863|scaffold30297|m.32139
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------------GGAACAAC
AGGTAAGGAAAATGCAAACCATGAAGTTGAGAAGCAAC------GCAACTGTCCGCTGTG
TCCTCGGCTGTTTTACAAAGCGGCTGACCTTAGGGAACACATGTTAA---TACATGAGGC
AGAATATGAAAACCTGAGTAATGG---GAAAAAATCCGATCCGATCTTTCCGTGCCTGTA
TTGTCCTCTTAAATTCATGGAGGAATCTTCCTTACAGTCCCATATGTTGACTCATCAAGC
TGTCTCCGCTCCGTTAAAGAGGGAGGTTCTCAGCGTAGCAAGGGCAGGTAGTATTGATAA
CATGCCAGAAGGAGGGGAATGGGGAGATCAGTCAGAGAAGAAGCCTCTGAAATGCAAAGA
CTGTGGCAAATGCTTTCGTTATCGTTCAGTTTTAGAGCTTCACATGCGCATACACAACAA
GGG---------TTACCAGTGCCATATTTGTAAAAAGTCGTTCCGATTCAGCAGCTACTT
ACAGCAACACGT----AATTATTCATTCTGGGAAGAAGCCATACAAGTGCCCAGACTGTG
GAAAGGACTTTGCTTTTCTTCAGAACATGAAAACTCATCAGAGACTGCACCAGCAGAAGC
CTTTCCGTTGCACGCAGTGCCGCAAAGGGTACAGTGATGAGAGTCAGCTGCAACGCCACA
TGCTTTCGCACTCGGGTGAAAAACCTCACAAATGTCACCTCTGTGACAAGAGTTTTGGTT
TGGCATACTTGCTTCGTGACCACCTGAACACCCACACTGGTGAGAGACCCCACCGTTGCC
AAGAGTGCCATAAGTCGTTCCCCTGGCTCAGCAGTCTCCTTGTCCATCAAAAGATACATG
CACGAAAGCGCCAATCAATGAACCAGTCTTTCGCTTCATTTGCCGGTTC---------CA
AGACCAGGGGCACTGAAGGCCGCGGGAAGAAAAATAGCAGGTGGATTTCAAGTTGGCCAA
GAATGGGCGGAGATCTTGGAAGGGCAATGTCACTGCCCCAGGCATCTTTCCCTGATGAGA
T------TTTGCAGGGCGCAATGCTGCCTAATGTGATTGGGCGACC---ACCTGTCT---
----------------------------------------------CTGACGCTGACGTG
ATGGAACAAACAACGCTGAGATCGCAACAGCATTTAAAATCCT----GGGAGACTGAAAG
CCAGGCTAAACCTGTTCATTT---GCAACAACAATGGCAAATACACATTAAGCCC-----
-CAGCACCATCAGCAGCCTAAATGGATG----------------------TCTGACGGAC
AACAAAATGACATGAAGCAGCACTTCATGTCGGGAGTCCATTTAAAACCAATCTTGCCAA
AGCTTGC---------------------TCAGCCACACCAACAACAGAATCCTGTCTTTA
CTGATGCAGTGCTGTCAGTTCAGGCTGGACCAGCTCCCA-------AGCAG---------
---------------------------------------------CTTCTAGAGAACTGC
CCAGTGCAAGATCTTTCTCAA---------------------------------------
-----GAACAGAAGAAGCACCAACAACCTCCGTTCTGGGTGGGTTCAACAACGTCTGTT-
---------CCAAAGTCCCCATGCAATGAGGATGAATCTTC-------------------
------------------------------------------------GATGGATTTCAA
AACAT-------------------------------------------------------
-------------------------------------GTTCGCCA---------------
---------------------------------------TCGTCAAAGA-----------
----------CTCAGAATTCACCGAAAGAAT-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------GGTCGGGTTCAA-----------------------
-------------------------------------------------CTGACGCGACT
CAAAACGNNNNNNNNNNNNNNNNNNNNNNAAGGATAA-----------------------
------------------------------------------------------------
-----------------------------------------CCATTCCTTGA--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>Melanotaenia_praecox_viscera_mixture_8|016596|scaffold3017|m.2555
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
TGGGAAAAAGGACA-------------------------------CACCTGCCCACACTG
TCCTAGTATTTATCGTGATGAGTCTAGTTTAAAAGTACACTTATTAAGCGTCCACAAGAC
AA---------------------------------------------------CCACACA
ATATTTAGAAAAGTTTGCAGAGCCACCTAAACAGCAGTTTACTCCATTAGCT--------
----------------------------------------------------ACTGATAA
TGTG---------CAGGGGAAGAACGAAAGCTTAAGTATTAAGTCGTATAAGTGTTCAGA
GTGCGGCAAAACATTCCGCCATCGCTCAgTGTTAGAGTTGCATATGCGCATACATTCCAA
GGAC---AAGCCTTATCAGTGTAAAGTGTGTGGCAAGGGCTTCAGATTCAGCAGCTACCT
GCAGCAACATCT----CATCATCCACACTGGTAAGAAGCCATATAAATGTCCAGATTGTG
GAAAGGAATTTGCCTTCCTGCAGAACATGAGGACACATCAAAAGCTACACCAGGAAAAGC
CGTTCCGCTGCACCAGCTGTCGCAAAGGCTACAGTGATGAAACCCAGCTGCAGCAACATA
TGTTATCACATAACGGTGACAAACCTCATAAGTGTAACCTGTGTGACAAAAGCTTTGGGT
TAGCTTATTTGCTCCGTGATCACATGAACACACACACAGGGGAGAGGcctcATCGTTGTG
ATGAGTGTCACAAAACCTTTTCCTGGTTTAGCAGCCTATTAGTTCACCAGAAAATCCACA
CTCGCAAGAAACCGCATTCCAGCCAATACAATATTTTCCCTGTTGGGGC---------TA
GGATGAGAG---------GCAGGGGTAAGAGAGGAGGGAGGGTAGTGTGGGGCTGGTCTA
GACCTTTAGGGGGCTCGGGAATGGTTAGTCATCAG---CAGCCTCTGTATCCTCTC----
-------TCTCCATTGAGGGATGCTGATTTGCACAGAAGGGTACCA--------------
---------------------------------------CAACCGCCGTCTTCCATGCTC
CCGAATCGCATGGATTTACAAAGCAGGCAGCAGAAGGAGCCGT----GGCTTTCTGAGCC
ACATGCTCAGCCAGTGCAGTG--------GAAGGTGGACGGTGGAGAGGTGATGC-----
-CTGTCCCATCCACAGGGCA----------------------------------------
---------ACACAGAGCTCCACAGCAGACT-----CAGTTTGACAGCCCAACACCGGCA
GGGCTG-----------------------CAACAGCACCATCAGAGAAGTCCGGGCTGGG
CAGACATCCCTCTGTTAACTCAGTCAGGCCCCACTTCAG---------------------
-------------CTCAAAGCTCGGATGCA--------CACATGAAAGAGGGGGGGTCCT
CTGTTGTCAGCTC------------------------------TCANNNNNNNNNNNGTG
AGATGGTGCAGCTCAGGCAGCACAAGCCTGCCACTTGGAGCAGCAGCCCCACCTCCACAG
TGCTAGCTTCCACAAGCTCCGTACAGCACGACTTCTCCATT-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------
>Pantodon_buncholzi_mixed|016926|scaffold195|m.236
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------CACACATCAG-------------
------------------------------------------------------------
-----------------CAGATGCCCCAAGTCAACAG-----------------------
------------------------------------------------------------
----------------------------------GATCGGAAGCCATTCAAGTGTAACCA
ATGCTGTAAGGCGTTTGAGCAGAGTTCAGTGTTGGAACGGCACATGCGTTCACATGAGAG
GGCAGAAAGACCCTTTCAGTGCAAAGTGTGTGGCAAGAGCTTCCGCTTCAGCAGTTATCT
GCAGCAGCATCT----CATCATCCACACTGGGCAGAAGCCCTTCAAGTGTCCTGAGTGTG
GCAAGGACTTTGCCTTTCTGCAGAACATGCGGACGCACCAACGGCTGCACCAACAGAAGC
CATACCGCTGCACGCAGTGCCGTAAAGGCTACAGCGAGGAAGCGCAGCTGCAGTACCACA
TGCTGTCACACAGCGGTCAAAAGCCACACAAATGCCACTTCTGTCAGAAAAGCTTTGCAT
TGGCCTATTTGCTGCGTGACCACCTTAACTCACACACGGGGGAGCGACCGCATCGCTGTG
GCGAGTGTCACAAGACCTTCCCATGGCTAAGCAGCCTGCTTGTGCACCAGAAGATACATG
CACGCAAGCGTCAAGGTATGGAGGTGTCTGCAGC-------GCTGAGCCC-------TCG
GGCCCTGGGGCAT----------GGACAGCGGAGCAGACGGCATGCATGGCACCGGCCAT
TGCAATCGCAGGACTT--------------------------CCCTCTACTCCCCTCATA
CAC----ACAGCAGTGGGT--------------CAGTGGGTTGCTA--------------
------------------------------------------------------------
-----------GAAACTGTACAGGTTAGGTATGAAGCAACCACTTCAGACAGGAGGAATG
TTTTGTGCAGTTTGCTGAGTG-------TGGCTGTTCCTGAAGAAAAT------------
-----CCCAGTAGCAACCAGGAC---------------------------CATGGAGACC
AAGAAAGTGATCTGAAGCTTCAGTGTCACTC-----TCCAGAGAGAAATGAGCAGCAGAC
GGGTGAGT----TCAGCAAACCTGCATGTCCTCAGGGTCAGCAACCGAGTGAGGGGCCAG
CAGCTGGGCCT-------------------------------------------------
--------------------------------------------------GACAAACTCT
C-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------GTGCCCCAGA-------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------CTGCTGCA-------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------GTGTATGATCTGTGGC
TGTTCTGTACCCTGTGAGCTTGACCTCCATG-----------------------------
-----------------AACACTACATGCAGCAT-------------------------G
CACAGGGCCACA----TCTGA
>Sargocentron_rubrum_gill_6|022075|scaffold4862|m.5483
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------AAC
ATACAAGGAAAATG----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------GAGGAATGATGGTGCAAGTAGTAAGTCATACAAGTGTTCGGA
GTGTGGCAAATTGTTCCGTCACCGCTCGGTGTTAGAGTTGCATATGCGCATTCATTCCAA
GGAC---AAACCCTACCAGTGCAAAGTGTGTGGCAAGCGCTTTCGATTCAGCAGCTACCT
ACAGCAGCATCT----CATCATCCACACAGGCAAGAAGCCCCACAAATGTCCTGACTGTG
GGAAGGACTTTGCCTTCCTTCAGAACATGAAGACCCAtcaaaagctgCATCAGGAGAAAC
CATTCCGTTGTACCAGCTGCCGCAAAGGTTATAGTGATGAGGCTCAACTTCAGCACCACA
TGTTGTCACATAATGGTGAGAAACCTCACAAGTGT-------------------------
-----NNNNNNNNNNGCGATCACATGAACACTCATACAGGAGAGAGACCTCATCGCTGTG
ACGAGTGTCACAAATCCTTTTCCTGGTTTAGCAGCCTCCTAGTACACCAGAAAATCCATG
CTCGCAAGCGCCAAGGTTTCAGTCAGTATACTTCCTTTCCTGTGAGCAC---------TA
GGATGAGAGGCAGAGGAAGCAGGGGAAGGAGAGGGGGTAGGTTTGCGTGGGCCTGGCCTC
GATCAGCGGGAGGCTCAGGGATAGTTACCTCTCAGCCTCCACCTCCATATCAACTT----
-------TCTACACTGAGAGATGCTGAAATGCACCGGAGGGCAGTG--------------
---------------------------------------CAACCACTCTCTCCCATGGTA
TCATCTCGCATGGAATTACAAGGCAGACAGCAGAAGGAGCCAT----GGCTTTCAGAGGT
TCACCCTCCACCGGTCCAGTG--------GAAAGTGGATGGTGGAGAGGTAATGC-----
-CTGTTCCATTGTCTCAGCAGACTCAGC--------------------------------
-----AGCCACTTTTAGCACTACAGCAAACA-----CAGTTTGACAACCCACCACAACCT
GGCCTA-----------------------CAGCAACACCATCAGAGAAGTCCAGGCTGGG
CAGATAGCCCTCTCATATCTCAGTCTGGCACTTCTTCAG---------------------
-------------TGCAGAGTTTAGAGTCATC-----GCACCTGAAGGACAGCACAGTTT
CGATTGTCAGCTCCCTCCCAGCAGCTCTGCCAAAAAAGTCCAGTCCGTCAGTAGTAAGTG
AGATTGAGCAGCACAGGCAACCCATGCCTGCAACTTGGAGTAGCACATCTGCATCCACAG
CACTAGCGTCCACTAGCTCGTCACAAAATGAATTTACTGTTTCCTCAAACTACATAGAAG
GGGCAGCACTTTGGAGTGTAAGACCGACTCCACTAGCAGCAACCTCACAGAGCTCCCCAA
ATAAATCTGG------------------------------TCAAGATCTTC---------
--------AGCTGCCAAGATGGTCAA-----------GTGCCCCAGG---GTCAACACAA
AAGACTGGGAATGAGCCATCAGTAGT------------TCCTAAAAAAGATGATAATAGA
GTGTGGGACTTAAGTAATCCTCAAGTAATACCGTCGACTGTTAGCCAGGCAGAAAAGCCA
TGGAATGGATGTGAGCCGCAAAAACAGTGGGCTTCGGGCTTAGCAGGTGCATCCAC----
--------CTCAGCTCAAGTAGACCAAAGCAACCCTATGTCAGTTTCAACCCCTGTATCT
CATGGGGTAGGTAGCACCTTGTGGGACTTCCAAACACCGCCAGGCATTCCAAAGACTATA
AGCCCCTCTGAGAAATNNNNNNNNNNNNNNNNNCAAAAACAGGTGTCATCTGGCTGGGCC
AATGTACAAAGTCAGGCATCCACTCAGAAGGTTCCCATTTCTATACAATATGAGCCCCAC
CGCTTTCCCCATGGGATGGGAACGGCAGTGTGGGGTTTCCAAACTAATCCTGTGGGTCCT
CAAACCCTGCTCGCTGGACAACTCAAGCCAGGGAATGGACAGGAGCTGCAGCATCAACCA
ATGGTAACGGGCACTCAAATAATCATAAATCAGCCTTCTCCCTTTTTCTCACCTCCACTT
GCTCCGCTCCCCCCTCTTGCTTTGCCTGGTCCTCACCCTCTTCATTCTGTTGCAGTAGGT
GCACTTCCAAGACCTCCACACCCAAATATTTTTTTCACACCACAGGCAGTCATGAGCGAG
AGACCACACATGTCACAGACCCTGTCCCTACCTCAGCTTGCCCCACGGACAGAACCTCAC
AAACTCGGAACTCGTTTGCCTTTTGCCCCAGAACGGCTTCTTCAGTGCATGATATGTGGG
TGCTCTCTTCCTCGGGAGTTGGATCTACNNNNNNNNNNNNNNNNNNNNNNNNTGCACAAG
GAGAGATTTGACAATTTTACACTAGCAACAAAGTTAAGCTTTGTTTTATCATTTCTGTCC
AATAGAGCCTCATTAATTTGA
